### ISSUE TITLE
rsyslogd: set SO_TIMESTAMP failed on '/dev/log': Invalid argument [v8.16.0]

### ISSUE THREAD

**Issue by steowens** [drwetter/testssl.sh#1000]
Please make sure that you provide enough information so that we understand what your issue is about.
This issue happens when rsyslogd starts up.
   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
testssl.sh: Command not found

2. what exactly was happening, output is needed
On rsyslog startup syslog is emitting the following line to /var/log/syslog:
  rsyslogd: set SO_TIMESTAMP failed on '/dev/log': Invalid argument [v8.16.0]

3. what did you expect instead?
I did not expect rsyslog to emit any errors to the syslog.  The default configuration should work.  I have been able to get rid of the other errors by disabling kernel logging and attempts to notify to xconsole, but I can't get this one to go away.

4. steps to reproduce

   1. testssl.sh command line: This command is not supported
 
    1. if possible: target IP  doesn't matter this is local host and does not involve networkinig
 
    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
        OpenSSL 1.0.2g  1 Mar 2016
 
    1. your operating system (uname -a)
         Linux LAPTOP-OT0BG026 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by drwetter** [comment]
???

Steve, despite the filled out template I can't derive any sense from it. Don;t know what rsyslog should has to do with testssl.sh. testssl.sh doesn't have anything to do with system logging.

And why it says 'This command is not supported' or 'Command not found' looks to me you tampered with your system .

Sorry, can't help here. Cheers, Dirk

**Comment by steowens** [comment]
I must apologize, I accidentally issued this request to the wrong project.  Thank you for the valiant effort at trying to make sense of the issue, but it was intended for an entirely different project.  Please accept my apologies.

**Comment by drwetter** [comment]
no prob. Humans sometimes do mistakes. I appreciate you apologized.

Cheers, Dirk
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection
