### ISSUE TITLE
CAA RR should by default be inherited by subdomains

### ISSUE THREAD

**Issue by Nimloth** [drwetter/testssl.sh#1001]
If I read [RFC6844](https://tools.ietf.org/html/rfc6844#section-4) (Section 4) correctly, the policy set by CAA RRs is effectively inherited by subdomains, but this seems to be ignored by testssl.sh

Version used: 2.9.5
OS: macOS 10.13.3
Verified on: FreeBSD 11.1

This works as expected:

`testssl.sh siriusmail.net`
...
`DNS CAA RR (experimental)    OK (issue: \;)`

while this does not:

`testssl.sh mail.siriusmail.net`
...
`DNS CAA RR (experimental)    --`

**Comment by drwetter** [comment]
Yes, that is true for 2.9.5. In 2.9dev this has been addressed.

Not sure this will be backported as I want to finalize 2.9dev at a certain point of time. I'll look into it.

**Comment by drwetter** [comment]
Final say: At this point of time I'd rather point to 2.9dev.
