### ISSUE TITLE
no ports && FreeBSD 9 / MacOS X: protocol FP

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#101]
/usr/bin/openssl s_client -state -ssl3 -connect testssl.sh:443 -servername testssl.sh &>/dev/null && echo FALSE_POSITIVE
     /usr/bin/openssl s_client -state -ssl2 -connect testssl.sh:443 &>/dev/null && echo FALSE_POSITIVE

happens if called like `testtssl.sh --ssl-native -p testssl.sh`, probably also STARTTLS

See also #40 .

Using `OpenSSL 0.9.8za-freebsd 5 Jun 2014`, no ports

**Comment by drwetter** [comment]
This won't be fixed, at least not in the near future. (code relies on proper return values)

**Comment by drwetter** [comment]
Darwin now has a binary #127

**Comment by jpluimers** [comment]
What steps do I need to test this on Mac OS X?
