### ISSUE TITLE
no ports && FreeBSD 9 / MacOS X: RC4

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#102]
has not complete output of ciphers, see also #40  
using `OpenSSL 0.9.8za-freebsd 5 Jun 2014`, no ports

**Comment by drwetter** [comment]
This won't be fixed, at least not in the near future. (code relies on functioning openssl -V and preper return values)

**Comment by drwetter** [comment]
see #114. Fixed cipher table might help but the openssl version will be still crappy

**Comment by drwetter** [comment]
Darwin now has a binary #127

**Comment by jpluimers** [comment]
What steps do I need to test this on Mac OS X?
