### ISSUE TITLE
./testssl.sh: line 9862: : command not found

### ISSUE THREAD

**Issue by aaww01** [drwetter/testssl.sh#1021]
Please make sure that you provide enough information so that we understand what your issue is about.
I suspect this line is evaluating to an empty set, since do_starttls is never being set unless -t option is specififed.  Missing initialization?
`          if "$do_starttls" && ( [[ $tls_content_type == 35 ]] || [[ $tls_content_type == 34 ]] ); then`

   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
```
    testssl.sh       2.9dev from https://testssl.sh/dev/
    (ffd89f8 2018-03-21 12:36:25 -- )
```
2. what exactly was happening, output is needed:
```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      ./testssl.sh: line 9862: : command not found
not offered (OK)
 TLS 1      ./testssl.sh: line 9862: : command not found
./testssl.sh: line 9862: : command not found
./testssl.sh: line 9862: : command not found
./testssl.sh: line 9862: : command not found
```

3. what did you expect instead?
No errors :)

4. steps to reproduce

   1. testssl.sh command line: ./testssl.sh https://www.vmaxsor.com  
 
    1. if possible: target IP 204.19.165.185
 
    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on centmon:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")

    1. your operating system (uname -a)
2.6.32-696.20.1.el6.x86_64

**Comment by drwetter** [comment]
Thx!
