### ISSUE TITLE
Timeout missing - no error given if run using warnings:batch

### ISSUE THREAD

**Issue by bradparks** [drwetter/testssl.sh#1027]
Please make sure that you provide enough information so that we understand what your issue is about.

When running `testssl.sh` with the following args:

` --warnings batch --openssl-timeout 20 `

it will simply give an empty response, if the user doesnt have the `timeout` command installed on their machine.
   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)

    testssl.sh       2.9.5 from https://testssl.sh/    
    (7b48a05 2018-04-05 11:37:39 -- )

2. what exactly was happening, output is needed

    Nothing was output - empty results

3. what did you expect instead?
An error message telling me that I didnt have `timeout` installed.

    ```Neccessary binary "timeout" not found. Continue without timeout?  -->```

4. steps to reproduce

   1. testssl.sh command line
 `testssl.sh --warnings batch --openssl-timeout 20  tls1test.salesforce.com`
 
    1. if possible: target IP
```        This is a public domain, so it should be resolvable.```
 
    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
```
 Using "OpenSSL 1.0.2o  27 Mar 2018" [~125 ciphers]
 on bparks-wsm:/usr/local/opt/openssl/bin/openssl
 (built: "reproducible build, date unspecified", platform: "darwin64-x86_64-cc")
```

    1. your operating system (uname -a)

```Darwin bparks-wsm.internal.salesforce.com 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64```

**Comment by drwetter** [comment]
Hi Brad,

thx for the report. 

I am a afraid It's more an user error. ``--warnings=batch`` deliberately switches off those kind of warnings.  Documentation For the user ``--warnings-batch`` and for a single test as you described this shouldn't be used. It's automatically inserted if mass testing will be done (serial or parallel).

Cheers, Dirk
