### ISSUE TITLE
no ports && FreeBSD 9 / MacOS X: BEAST

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#103]
Linux vs FreeBSD 9 is false positive on FreeBSD, see #40 

using `OpenSSL 0.9.8za-freebsd 5 Jun 2014`, no ports

**Comment by drwetter** [comment]
This won't be fixed, at least not in the near future. (code relies on functioning openssl -V and preper return values)

**Comment by drwetter** [comment]
see #114. Fixed cipher table might help but the openssl version will be still crappy

**Comment by drwetter** [comment]
Darwin now has a binary #127

**Comment by jpluimers** [comment]
What steps do I need to test this on Mac OS X?

**Comment by drwetter** [comment]
Am 15. August 2015 10:47:07 MESZ, schrieb Jeroen Wiert Pluimers <notifications@github.com>:
>What steps do I need to test this on Mac OS X?
>

Thx, Jeroen. This (and the other issue) affects the old openssl version 0.9.8 which doesn't understand the  "cipher -V" option and also causes other pain. New OSX seems to have LibreSSL and thx to you this project has even better binaries to test with ;) and I also compiled one for FreeBSD 9.x.

So basically this is not a real issue anymore. I just left that open as my plan is in the next development phase to work with a fixed cipher table instead of generating it on the fly.

Thx, Dirk
