### ISSUE TITLE
Clarify meaning of different branch

### ISSUE THREAD

**Issue by franklinyu** [drwetter/testssl.sh#1035]
[question] Currently there is `2.9dev` branch and `2.9.5` branch. Previous releases were tagged on commits in `2.9.5` branch, but latest `v2.9.5-4` were tagged directly on `2.9dev` branch, so `v2.9.5-3` is not ancestor of `v2.9.5-4`. Is there any specific meaning about this? Are we supposed to upgrade from 2.9.5-3 to 2.9.5-4?

**Comment by drwetter** [comment]
Thanks for the hint. That was meant for 2.9.5 instead. I deleted the release and made a "-5". Unfortunately there's a "-4" in the banner now which I realized after releasing "-5". 

Apologize the confusion.
