### ISSUE TITLE
Lucky13 issue reported

### ISSUE THREAD

**Issue by vickyy222** [drwetter/testssl.sh#1058]
In AWS we are using latest TLS policy 2017. Yet lucky13 issue is reported in our server instance when Testssl was ran on the WEB UI portal. We contacted AWS, they claimed that lucky13 issue will not be seen in TLS policy 2017. So is this a bug from Testssl software. I used the latest testssl from github.

**Comment by drwetter** [comment]
Please read the output carefully and don't pipe the output 1:1 to somebody else. 

"potentially" is the keyword here, see https://github.com/drwetter/testssl.sh/issues/1011#issuecomment-389962542 and https://github.com/drwetter/testssl.sh/issues/1011#issuecomment-372953654
