### ISSUE TITLE
Minor typos/erros in manual docu (2.9dev branch)

### ISSUE THREAD

**Issue by LeslieGerman** [drwetter/testssl.sh#1071]
Hi Dirk,

In first line of ["EXIT STATUS"](https://github.com/drwetter/testssl.sh/blob/2.9dev/doc/testssl.1.md#exit-status):

> 0 testssl.sh finished successfully without errors and without unambiguous results

unambiguous => ambiguous
(Unless I misunderstood something...)

In the ["AUTHORS" section:](https://github.com/drwetter/testssl.sh/blob/2.9dev/doc/testssl.1.md#authors)
The link https://github.com/drwetter/testssl.sh/blob/master/CREDITS.md is broken.

And thanks for the improvement on the exit status codes!
Bests, Leslie

**Comment by drwetter** [comment]
Somebody really reads the docu, whohoo ;-)  

No, really: Please correct (PR) or just speak up if you spot further problems.
