### ISSUE TITLE
Adding support for sending cookies as part of testing request

### ISSUE THREAD

**Issue by jauderho** [drwetter/testssl.sh#1077]
I just checked and there does not look like there is an option to offer up a cookie(s) to a URL as part of testing. 

The URL I'm trying to reach is behind an authn/authz mechanism so testing TLS support is challenging unless I'm able to reach past the gatekeeper URL.

**Comment by drwetter** [comment]
okay, specifying a header should no big deal (not only for cookies but also bearer tokens or Basic Auth,...)

But: Cookies and friends are a matter of the application layer in the OSI model. TLS is below. Not sure whether this will help you.
