### ISSUE TITLE
Check for incorrect certificate ordering

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#1080]
As noted in #1079, some servers are sending incorrectly formatted lists of certificates.  draft-ietf-tls-tls13 (soon to be RFC 8446) says:

> The sender's certificate MUST come in the first CertificateEntry in the list.  Each following certificate SHOULD directly certify the one immediately preceding it.

In RFC 5246, the "SHOULD" in this text was a "MUST".

testssl.sh should add a check that each certificate in the list of certificates sent by the server directly certifies the one immediately preceding it.

The change would be similar to the one in #1079, except that the issuer and subject DNs would be extracted from **every** certificate in the list and a check would be done to verify that the subject DN in each certificate was the same as the issuer DN in the preceding certificate. A low-level warning could then be issued if a problem was found in the list.

**Comment by amenk** [comment]
Thanks for this check

Slightly off topic: It's currently a yellow warning only, but it looks like this is really creating problems in real-world, for example when connecting via LFTP to a server with invalid certificate ordering.

See for example: https://github.com/lavv17/lftp/issues/143#issuecomment-344195654

Just wanted to leave this here for fellow searchers :-)
