### ISSUE TITLE
Feature Request: Exit codes based on vulnerabilities

### ISSUE THREAD

**Issue by pachonk** [drwetter/testssl.sh#1081]
First of all, if feature requests are not allowed here please simply close this issue.
   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
```
    testssl.sh       3.0beta from https://testssl.sh/dev/
    (488cb03 2018-06-28 20:25:46 -- )
```
2. what exactly was happening, output is needed

Unless there is an operational failure, the exit code will always be 0.

3. what did you expect instead?

At the end of a potentially vulnerable certificate, it would be really sweet if the exit code exited as 1, or if there was a flag to make this functionality happen.
The reason I'd love this functionality is to be capable of running this as an automated test in a CI environment or monitoring in order to give notifications on vulnerable certificates.
Something that could be done is potentially a threshold of critical, high, medium, or low warnings as discussed in #327 

4. steps to reproduce

   N/A

Somewhat related to #327
I do realize that the functionality would need to exist for Nagios support, but #327 is purely talking about Nagios plugin, not usable exit codes

**Comment by LeslieGerman** [comment]
Hi @pachonk,
I'm glad to see you need this feature, too.
Please see => #752 , #985 , #986 ...
So welcome in the club :)

It seems to me, @drwetter collects every exit code related stuff in #327 , so maybe it's better to discuss this there...

Cheers

**Comment by pachonk** [comment]
Thanks @lesliegerman

**Comment by drwetter** [comment]
> First of all, if feature requests are not allowed here please simply close this issue.

no, that's absolutely fine and the right place. It's only that as you already spotted (and @LeslieGerman ) it is being tracked already. So I'll close this. 

In addition please also see in ``testssl.sh(1)``: ``EXIT STATUS`` --> 50-200. This is the plan for server exit codes. Please note that there are client side codes as well (>=240) and other problems (1 though ~10)

**Comment by pachonk** [comment]
Sounds great, thanks!
I'm excited for this upcoming exit code feature and I'm well versed in bash. If you need anything, please do reach out.

**Comment by drwetter** [comment]
@pachonk , thanks! There will be certainly things to do.

For this release see https://github.com/drwetter/testssl.sh/milestone/4, in particular #924,/#547 would be a good start.

For 3.1dev one topic will be improving the performance, see https://github.com/drwetter/testssl.sh/issues?q=is%3Aopen+is%3Aissue+label%3Aperformance. One part is the logic, one part is the code. Maybe the latter is something for you? 

For coding it is important to use as many bash internal functions as possible and to keep in mind that the code is supposed to work not only on several Linux flavors, but on MacOSX (bash 3.2) and on Windows with bash. People say forking is expensive here.
