### ISSUE TITLE
testssl No engine or GOST support via engine with your /usr/bin/openssl

### ISSUE THREAD

**Issue by lizewen1991** [drwetter/testssl.sh#1083]
My command is  ./testssl.sh 192.168.4

Fatal error:Neither "dig","host","drill" or "nslookup" is present

**Comment by drwetter** [comment]
Am 6. Juli 2018 08:23:10 GMT+01:00 schrieb lizewen1991 <notifications@github.com>:
>Fatal error:Neither "dig","host","drill" or "nslookup" is present
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/issues/1083

Please see information how to file a potential bug
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by Devender210590** [comment]
Below command will help you to solve problem.

`yum install bind-utils -y`

**Comment by HillGnur** [comment]
> Below command will help you to solve problem.
> 
> `yum install bind-utils -y`

Tried this, not working, also tried with bind9-utils on Debian WSL, same thing.

**Comment by drwetter** [comment]
you need to find the package for Debian and use the right front end to your DB packet mgmt system.
