### ISSUE TITLE
HTTP redirect follow discrepancies

### ISSUE THREAD

**Issue by gkroon** [drwetter/testssl.sh#1088]
Hi @drwetter Please find below the detailed information regarding my problem, what I expected and how to reproduce.

   
**1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)**
`    testssl.sh       2.9.5-4 from https://testssl.sh/`

**2. what exactly was happening, output is needed**
The redirection follow seems to parse the HSTS header on the next hop just fine, whereas the remaining Security headers on the same next hop are not included. When scanning the next hop directly, it parses fine.

For example, when scanning a host that has an HTTP redirect on its document root, the redirect is followed and testssl parses the HSTS header just fine, but notice the absence of further Security headers.
```
➜  ~ testssl.sh --headers xxx.xxx

###########################################################
    testssl.sh       2.9.5-4 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2o  27 Mar 2018" [~125 ciphers]
 on nostromo:/usr/bin/openssl
 (built: "reproducible build, date unspecified", platform: "linux-x86_64")


 Start 2018-07-17 20:31:04        -->> xxx.xxx.xxx.xxx:443 (xxx.xxx) <<--

 rDNS (xxx.xxx.xxx.xxx):     --
 Service detected:       HTTP


 Testing HTTP header response @ "/"

 HTTP Status Code             301 Moved Permanently, redirecting to "https://www.xxx.xxx/"
 HTTP clock skew              +3 sec from localtime
 Strict Transport Security    180 days=15552000 s, includeSubDomains, preload
 Public Key Pinning           --
 Server banner                nginx
 Application banner           --
 Cookie(s)                    (none issued at "/") -- maybe better try target URL of 30x
 Security headers             --
 Reverse Proxy banner         --


 Done 2018-07-17 20:31:06 [   3s] -->> xxx.xxx.xxx.xxx:443 (xxx.xxx) <<--


```

Then, when performing a `curl` with `-IL` to only display the headers, and to follow the redirections, we can observe the next hop has indeed several Security headers.
```
➜  ~ curl -IL xxx.xxx
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 17 Jul 2018 18:31:44 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Keep-Alive: timeout=5
Location: https://www.xxx.xxx/

HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Keep-Alive: timeout=5
Cache-Control: must-revalidate, no-cache, private
Date: Tue, 17 Jul 2018 11:50:38 GMT
Link: <https://www.xxx.xxx/>; rel="canonical", <https://www.xxx.xxx/>; rel="shortlink"
Link: <https://www.xxx.xxx/node/16>; rel="alternate"; hreflang="nl"
Link: </node/16>; rel="canonical"
Link: </node/16>; rel="shortlink"
Link: </node/16>; rel="revision"
X-UA-Compatible: IE=edge
Content-language: nl
X-Content-Type-Options: nosniff
X-Frame-Options: SameOrigin
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Vary:
X-Generator: Drupal 8 (https://www.drupal.org)
Content-Security-Policy: report-uri /report-csp-violation
X-Content-Security-Policy: report-uri /report-csp-violation
X-WebKit-CSP: report-uri /report-csp-violation
X-XSS-Protection: 1; mode=block
X-Drupal-Cache: HIT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload

```

Then, when scanning the next hop directly using testssl, it parses the Security headers just fine:
```
testssl.sh --headers www.xxx.xxx

###########################################################
    testssl.sh       2.9.5-4 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2o  27 Mar 2018" [~125 ciphers]
 on nostromo:/usr/bin/openssl
 (built: "reproducible build, date unspecified", platform: "linux-x86_64")


 Start 2018-07-17 20:35:25        -->> xxx.xxx.xxx.xxx:443 (www.xxx.xxx) <<--

 rDNS (xxx.xxx.xxx.xxx):     --
 Service detected:       HTTP


 Testing HTTP header response @ "/"

 HTTP Status Code             200 OK
 HTTP clock skew              -24289 sec from localtime
 Strict Transport Security    180 days=15552000 s, includeSubDomains, preload
 Public Key Pinning           --
 Server banner                nginx
 Application banner           --
 Cookie(s)                    (none issued at "/")
 Security headers             X-Frame-Options SameOrigin
                              X-XSS-Protection 1; mode=block
                              X-Content-Type-Options nosniff
                              Content-Security-Policy report-uri
                              /report-csp-violation
                              X-Content-Security-Policy report-uri
                              /report-csp-violation
                              X-WebKit-CSP report-uri /report-csp-violation
                              X-UA-Compatible IE=edge
 Reverse Proxy banner         --


 Done 2018-07-17 20:35:27 [   3s] -->> xxx.xxx.xxx.xxx:443 (www.xxx.xxx) <<--


```

**3. what did you expect instead?**
I expected testssl to also parse the Security headers on the next hop it redirects to.

**4. steps to reproduce**

   1. testssl.sh command line
`testssl.sh --headers [hostname] && curl -IL [hostname] && testssl.sh --headers [hostname-of-next-hop]`

    2. if possible: target IP
I' d like to avoid this. 

    3. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
```
  on nostromo:/usr/bin/openssl
 (built: "reproducible build, date unspecified", platform: "linux-x86_64")

```

    4. your operating system (uname -a)
`Linux nostromo 4.17.5-zen #1 ZEN SMP PREEMPT Tue Jul 10 20:13:39 -00 2018 x86_64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz GenuineIntel GNU/Linux` Still on Gentoo here.

_Note: also applicable to v3.0beta from your GitHub on the 2.9dev branch_

**Comment by drwetter** [comment]
Sorry for the late repsonse.

> I expected testssl to also parse the Security headers on the next hop it redirects to.

Not sure we want this. Despite any internal logic which help a user testssl.sh is a tool like a <s>hammer</s> swiss army knife and not an mind-reading jack-of-all-trades tool. Means: a human should read the output and if e.g. "/" was not the best idea, you need just to rerun supplying a proper path, i.e. target of the redirect. 

Secondly the redirect is kind of a headache: 1) http needs to be dropped 2) other sites as well 3) what about other domains? 4) if there are different security headers which ones should be displayed if they are contradicting or one has a different set? Some headers are domain,  some host and some path specific.

**Comment by gkroon** [comment]
Thanks for explaining! I agree with you and we should just scan the proper path then.
