### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by mike-aungsan** [drwetter/testssl.sh#109]
not critical, just report that I am see too many syntax error.

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

OpenSSL 1.0.1f 6 Jan 2014

XXXXXXXXXXXX

testssl.sh: line 3386: [: *: integer expression expected
testssl.sh: line 2841: [: too many arguments
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1825: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1684: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1829: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1830: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1719: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1989: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1964: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1998: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1999: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1770: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1779: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 2009: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 340: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 804: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 344: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 832: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1140: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1180: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1180: [[: *: syntax error: operand expected (error token is "*")
testssl.sh: line 1180: [[: *: syntax error: operand expected (error token is "*")

**Comment by drwetter** [comment]
Am 28. Mai 2015 01:47:26 MESZ, schrieb mike <notifications@github.com>:
>not critical, just report that I am see too many syntax error.
>
>Distributor ID: Ubuntu
>Description:    Ubuntu 14.04.2 LTS
>Release:        14.04
>Codename:       trusty
>
>OpenSSL 1.0.1f 6 Jan 2014
>
>XXXXXXXXXXXX
>
>testssl.sh: line 3386: [: *: integer expression expected
>testssl.sh: line 2841: [: too many arguments
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1825: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1684: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1829: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1830: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1719: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1989: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1964: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1998: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1999: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1770: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1779: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 2009: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 340: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 804: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 344: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 832: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1140: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1180: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1180: [[: *: syntax error: operand expected (error
>token is "*")
>testssl.sh: line 1180: [[: *: syntax error: operand expected (error
>token is "*")
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/issues/109


Couldn't reproduce it. When did you pull it?

Dirk

-- 
Sent from my mobile

**Comment by PeterMosmans** [comment]
And could you please state your bash version ?
    bash --version

By the way, I wouldn't recommend the stock openssl version for testing purposes, as it has many ciphers disabled by default.

**Comment by keith4** [comment]
that might be dash instead of bash, no?

**Comment by drwetter** [comment]
Am 05/28/2015 um 05:36 PM schrieb keith4:
> that might be dash instead of bash, no?

then why are you using dash?

prompt% head -1 `which testssl.sh`
#!/usr/bin/env bash
prompt%

Dirk

**Comment by mike-aungsan** [comment]
GNU bash, version 4.3.25(1)-release (x86_64-pc-linux-gnu)

**Comment by drwetter** [comment]
Am 28. Mai 2015 22:57:59 MESZ, schrieb mike <notifications@github.com>:
>GNU bash, version 4.3.25(1)-release (x86_64-pc-linux-gnu)


Sorry, that doesn't help much.

Please pull the latest and try to run it and tell us how you ran it.

As @keith4 (apologies for my previous answer) said it looks to me like you were using dash. 

Thx, Dirk

**Comment by drwetter** [comment]
Hi @mike-aungsan , feel free to reopen this once you tell us how to reproduce it with a recent release. 

Thx! Dirk
