### ISSUE TITLE
supplied openssl

### ISSUE THREAD

**Issue by bbday** [drwetter/testssl.sh#1093]
I wanna use testssl also for check mysql,postgress but doc say "the supplied openssl" required.
But i dont' understand what i need to do, i check on google about it but i didn't find anything.

Thanks

**Comment by drwetter** [comment]
The binaries provided don't support this yet. Either you wait a bit or help yourself by compiling the fork from Peter Mosmans, see bin directory here: https://github.com/drwetter/testssl.sh/blob/2.9dev/bin/Readme.md
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by bbday** [comment]
thanks for your answer, now i understand it

**Comment by drwetter** [comment]
see #559, #179
