### ISSUE TITLE
Site certificate expired

### ISSUE THREAD

**Issue by franklinyu** [drwetter/testssl.sh#1094]
Certificate of https://testssl.sh has expired. Renewal should be automated.

**Comment by drwetter** [comment]
Thx for the reminder, Frank. 

I do not like smart-ass-like-comments though. This is a spare-time project for me and it would be better honoring our work.

**Comment by franklinyu** [comment]
Sorry if it sounds pushing. I'm not a native speaker so I may have express some feelings the wrong way. This project is very active and helped me a lot.
