### ISSUE TITLE
testssl.sh certificate expired

### ISSUE THREAD

**Issue by naumanshah03** [drwetter/testssl.sh#1095]
Certificate for testssl.sh site has expired recently i.e 2 days ago.

Please get it renewed
![image](https://user-images.githubusercontent.com/22236992/43448565-f30e47da-94cb-11e8-8944-8cf28c1dccba.png)

SSLLabs result - https://www.ssllabs.com/ssltest/analyze.html?d=testssl.sh

**Comment by drwetter** [comment]
it's done
