### ISSUE TITLE
doesn't seem to be a TLS/SSL enabled server RDP scan

### ISSUE THREAD

**Issue by mlied** [drwetter/testssl.sh#1096]
Please make sure that you provide enough information so that we understand what your issue is about.
   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
    testssl.sh       3.0beta from https://testssl.sh/dev/
    (94828ae 2018-07-26 22:45:36 -- )

2. what exactly was happening, output is needed

 Start 2018-08-02 14:30:06        -->> 10.20.30.40:3389 (10.20.30.40) <<--
 rDNS (10.20.30.40):   myhostname
 10.20.30.40:3389 doesn't seem to be a TLS/SSL enabled server
 The results might look ok but they could be nonsense. Really proceed ? ("yes" to continue) --> 

3. what did you expect instead?
  normal output like other server, e.g. Windows 2012R2 with same parameters

4. steps to reproduce

we get this since we need to set RDS Security Level, e.g. on Windows 2016 Server:
- TLSv1.2 (only)
- disabled 3DES
- disabled MD5
- disabled PKCS
- change the RDS Security level to "RDP"
last step is needed for Nexpose finding "TLS/SSL Server Supports The Use of Static Key Ciphers"

do we have any chance to test/watch these patched server furthermore?
thanks in advance

**Comment by drwetter** [comment]
Hi @mlied ,

thx. The problem I have is that I currently do not have a server 2016 handy. 

> change the RDS Security level to "RDP"

what does that do? 

> last step is needed for Nexpose finding "TLS/SSL Server Supports The Use of Static Key Ciphers"

What do you mean by  that? (I know Nexpose is a scanner)

**Comment by mlied** [comment]
Hi @drwetter ,

_RDP Security Layer Communication between the server and the client will use native RDP encryption. If you select RDP Security Layer, you cannot use Network Level Authentication._
[https://technet.microsoft.com/en-us/library/ff458357.aspx](url)

TLS/SSL Server Supports The Use of Static Key Ciphers
_The server is configured to support ciphers known as static key ciphers. These ciphers don't support "Forward Secrecy". In the new specification for HTTP/2, these ciphers have been blacklisted._
[https://www.rapid7.com/db/vulnerabilities/ssl-static-key-ciphers](url)

for 2016 server, we need to set this parameters.
perhaps a bigger problem, if i use

_openssl s_client -connect 10.20.30.40:3389_

i only get 

_CONNECTED(00000003)_
_write:errno=104_
_---_
_no peer certificate available_
_---_
_No client certificate CA names sent_
_---_
_SSL handshake has read 0 bytes and written 247 bytes_
_---_
_New, (NONE), Cipher is (NONE)_
_Secure Renegotiation IS NOT supported_
_Compression: NONE_
_Expansion: NONE_
_---_

**Comment by drwetter** [comment]
Remote analysis is always difficult but based on what you described it seems you seem to have enabled -- quoting you above -- 'change the RDS Security level to "RDP"' which enables native RDP encryption. The latter looks to me rather proprietary which means it is out of the scope of testssl.sh. 

As an indicator of openssl s_client -connect doesn't work - if it's the supplied one.
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by drwetter** [comment]
I am closing this based on my previous assumption. Correct me if I am wrong and provide clearer details and I am happy to reopen. Thx
