### ISSUE TITLE
Debian:Experimental: "No engine or GOST support via engine with your ./bin/openssl.Linux.x86_64"

### ISSUE THREAD

**Issue by sanderjo** [drwetter/testssl.sh#1098]
This is on Debian:Experimental (with openssl experimental, although I think that is not relevant), so this is FWIW and FYI. I don't know if this is a problem in testssl, or in Debian Experimental, or just PEBKAC.

I'll update if I find more information. 
I made an openssl binary myself based on https://github.com/drwetter/testssl.sh/blob/2.9dev/bin/Readme.md , but with the same result.

In the meantime feedback is welcome.

I get `No engine or GOST support via engine with your ./bin/openssl.Linux.x86_64` with testssl.sh:

```
root@2e75fd87c788:/testssl.sh# ./testssl.sh www.google.nl

No engine or GOST support via engine with your ./bin/openssl.Linux.x86_64

###########################################################
    testssl.sh       3.0beta from https://testssl.sh/dev/
    (94828ae 2018-07-26 22:45:36 -- )
```
So looking at 
https://github.com/drwetter/testssl.sh/blob/2.9dev/testssl.sh#L15666-L15669
I ran `./bin/openssl.Linux.x86_64 engine gost -v 2>&1` with this result:

```
root@2e75fd87c788:/testssl.sh# ./bin/openssl.Linux.x86_64 engine gost -v 2>&1
Error configuring OpenSSL
24672320:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
24672320:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:233:
24672320:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:271:module=ssl_conf, path=ssl_conf
24672320:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:212:module=ssl_conf
root@2e75fd87c788:/testssl.sh# 
```
Ah. That is something else than expected; healthy output is like (on my Ubuntu 18.04)
```
sander@witte:~/git/testssl.sh$ ./bin/openssl.Linux.x86_64 engine gost -v 2>&1
(gost) Reference implementation of GOST engine
     CRYPT_PARAMS
```

Maybe related to https://github.com/openssl/openssl/issues/4788 ?

Probably NOT related to https://github.com/drwetter/testssl.sh/issues/388

**Comment by sanderjo** [comment]
OK, thanks for the explanation.

Shall I close this for now? Re-open if it pops up in a mainstream distribution?

**Comment by drwetter** [comment]
Yes, pls close it. Feel free to re-open it so that we can look into it, albeit I believe there isn't so much we will do about it. We'll see...

**Comment by A1vinSmith** [comment]
**kali is Debian experimental. nvm**
_Kali testssl 3.0 gets warning `No engine or GOST support via engine with your /usr/bin/openssl`_

**Comment by drwetter** [comment]
@A1vinSmith What did you wanted to say / Did you read everything from above?

**Comment by A1vinSmith** [comment]
kk, I made an assumption. thought kali is not Debian experimental.

**Comment by msveden-123** [comment]
The problem was resolved when I installed libengine-gost-openssl1.1
