### ISSUE TITLE
Doesn't work with v6 hosts.

### ISSUE THREAD

**Issue by MrSorcus** [drwetter/testssl.sh#1100]
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
> testssl.sh       2.9.5 from https://testssl.sh/

2. what exactly was happening, output is needed
```
$ testssl.sh -6 inwebse.com                                                                         ~

Using "OpenSSL 1.1.0h  27 Mar 2018" [~144 ciphers]
(built: "reproducible build, date unspecified", platform: "linux-x86_64")

Testing all IPv4 addresses (port 443): 78.47.69.85 2a01:4f8:a0:438a:c2d8:356:8451:cd8c

Start 2018-08-11 06:14:17        -->> 78.47.69.85:443 (inwebse.com) <<--

further IP addresses:   2a01:4f8:a0:438a:c2d8:356:8451:cd8c 
rDNS (78.47.69.85):     static.85.69.47.78.clients.your-server.de.
Service detected:       HTTP
```

```
testssl.sh -6 --starttls smtp --debug 6 mx.inwebse.org:587                                           ~
do_allciphers          = false
do_vulnerabilities     = false
do_beast               = false
do_lucky13             = false
do_breach              = false
do_ccs_injection       = false
do_ticketbleed         = false
do_cipher_per_proto    = false
do_crime               = false
do_freak               = false
do_logjam              = false
do_drown               = false
do_header              = false
do_heartbleed          = false
do_mx_all_ips          = false
do_pfs                 = false
do_protocols           = false
do_rc4                 = false
do_renego              = false
do_std_cipherlists     = false
do_server_defaults     = false
do_server_preference   = false
do_ssl_poodle          = false
do_tls_fallback_scsv   = false
do_sweet32             = false
do_client_simulation   = false
do_cipher_match        = false
do_tls_sockets         = false
do_mass_testing        = false
do_display_only        = false
URI:                   : mx.inwebse.org:587

No engine or GOST support via engine with your /nix/store/9pp9w4b71dzr4cqr7yi9scjksrhw6cz8-openssl-1.1.0h-bin/bin/openssl

###########################################################
    testssl.sh       2.9.5 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.0h  27 Mar 2018" [~144 ciphers]
 on nixos_laptop:/nix/store/9pp9w4b71dzr4cqr7yi9scjksrhw6cz8-openssl-1.1.0h-bin/bin/openssl
 (built: "reproducible build, date unspecified", platform: "linux-x86_64")


mx.inwebse.org:587
/
Testing all IPv4 addresses (port 587): 78.47.69.84 2a01:4f8:a0:438a:c09a:d1af:93b1:95f6
---------------------------------------------------------------------------------------------------------------------------------------------
/run/current-system/sw/bin/testssl.sh: connect: Connection timed out
/run/current-system/sw/bin/testssl.sh: line 7332: /dev/tcp/78.47.69.84/587: Connection timed out

Unable to open a socket to 78.47.69.84:587. 
Fatal error: Can't connect to "78.47.69.84:587"
Make sure a firewall is not between you and your scanning target!
```

3. what did you expect instead?

Expected works with ipv6 only. Not v4. `--ip` option doesn't help.

4. steps to reproduce

> testssl.sh -6 inwebse.com

> 2a01:4f8:a0:438a:c2d8:356:8451:cd8c

> Using "OpenSSL 1.1.0h  27 Mar 2018" [~144 ciphers]

> Linux nixos_laptop 4.14.59 #1-NixOS SMP Sat Jul 28 05:55:45 UTC 2018 x86_64 GNU/Linux

or 

> testssl.sh -6 --starttls smtp mx.inwebse.org:587

> 2a01:4f8:a0:438a:c09a:d1af:93b1:95f6

> Using "OpenSSL 1.1.0h  27 Mar 2018" [~144 ciphers]

> Linux nixos_laptop 4.14.59 #1-NixOS SMP Sat Jul 28 05:55:45 UTC 2018 x86_64 GNU/Linux

**Comment by drwetter** [comment]
A) '-6'  tests ALSO ipv6, pls see documentation. B) you need an IPv6 enabled openssl binary. Don't know whether yours is one (supplied binary from here, Fedora, Gentoo)

Am 11. August 2018 08:29:43 MESZ schrieb MrSorcus <notifications@github.com>:
>1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4
>| tail -2)
>> testssl.sh       2.9.5 from https://testssl.sh/
>
>2. what exactly was happening, output is needed
>```
>$ testssl.sh -6 inwebse.com                                            
>                            ~
>
>Using "OpenSSL 1.1.0h  27 Mar 2018" [~144 ciphers]
>(built: "reproducible build, date unspecified", platform:
>"linux-x86_64")
>
>Testing all IPv4 addresses (port 443): 78.47.69.85
>2a01:4f8:a0:438a:c2d8:356:8451:cd8c
>
>Start 2018-08-11 06:14:17        -->> 78.47.69.85:443 (inwebse.com)
><<--
>
>further IP addresses:   2a01:4f8:a0:438a:c2d8:356:8451:cd8c 
>rDNS (78.47.69.85):     static.85.69.47.78.clients.your-server.de.
>Service detected:       HTTP
>```
>
>3. what did you expect instead?
>
>Expected resolving ipv6 only. Not v4. `--ip` option doesn't help.
>
>4. steps to reproduce
>
>> testssl.sh -6 inwebse.com
>
>> 2a01:4f8:a0:438a:c2d8:356:8451:cd8c
>
>> Using "OpenSSL 1.1.0h  27 Mar 2018" [~144 ciphers]
>
>> Linux nixos_laptop 4.14.59 #1-NixOS SMP Sat Jul 28 05:55:45 UTC 2018
>x86_64 GNU/Linux
>
>or 
>
>> testssl.sh -6 --starttls smtp inwebse.com:587
>
>> 2a01:4f8:a0:438a:c09a:d1af:93b1:95f6
>
>> Using "OpenSSL 1.1.0h  27 Mar 2018" [~144 ciphers]
>
>> Linux nixos_laptop 4.14.59 #1-NixOS SMP Sat Jul 28 05:55:45 UTC 2018
>x86_64 GNU/Linux


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by MrSorcus** [comment]
But v6 works fine after test v4 if i will allow v4 on firewall. :confused:

**Comment by drwetter** [comment]
There's a bug wrt to ``--ip=<IPv6address>`` which should test the IPv6 branch only -- thanks for reporting. Other than that I believe testssl.sh works as expected and documented.
