### ISSUE TITLE
testssl showing wrong cipher order.

### ISSUE THREAD

**Issue by cjingade** [drwetter/testssl.sh#1102]
testssl showing wrong cipher order. Can you please help why testssl showing wrong cipher order. Can you please help. As show in the below snapshot, 
Cipher order shows like this 
Cipher order TLSv1: DES-CBC3-SHA AES128-SHA AES256-SHA 
TLSv1.1: DES-CBC3-SHA AES128-SHA AES256-SHA 
TLSv1.2: DES-CBC3-SHA AES128-SHA AES256-SHA. 

The cipher order should be higher to lower, but here I see, DES-CBC3-SHA as the first one followed by AES 128 and AES 256. Why this order showing in the reverse order.

Also negotiated Cipher is DES-CBC3-SHA, which is the lowest in the 3.

<img width="814" alt="screen shot 2018-08-11 at 7 08 48 pm" src="https://user-images.githubusercontent.com/42297571/43992239-03948926-9d9a-11e8-8cea-b3e75ade73ae.png">

**Comment by drwetter** [comment]
I am pretty sure testssl.sh shows the cipher order configured. 

Maybe you can share the configuration of your server, so that others can help. 


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by drwetter** [comment]
I am closing, reason see above. If you provide reproducible info why you think this is wrong I am happy to reopen
