### ISSUE TITLE
Update client simulation info from SSLlabs API

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1104]

**Comment by drwetter** [comment]
From the commit log:

```
Thus the wishlist gets longer (c15e0425dcb4ba95cab471d77b6aba70ef7a9712).
Missing is Android 8 and 9, OpenSSL 1.1.1, Safari on OSX 11 and 12. Java 10
and 11.
```

If somebody wants to contribute that would be great! 

@seccubus: Your perl script ~/utils/wireshark2ciphers.pl would be handy for this. Not sure what input it expects though?

**Comment by seccubus** [comment]
@drwetter wireshark2ciphers sure looks like mine, but I have no clue anymore as to why I wrote it.
I gets all ciphers from openssl. If a line that is sent to stdin matches a certain format if will output the openssl cipher suite name. E.g.:

```
echo "Cipher Suite: (0x31)"|utils/wireshark2ciphers.pl 2>/dev/null


DH-RSA-AES128-SHA
```

I guess it could be used to extract ciphers from an wireshark dump of a TLS handshake.

I did write update_client_sim_data.pl which takes data from `https://api.dev.ssllabs.com/api/v3/getClients` and turn it into client-simulated_generated.txt which is similar to `etc/client_simulation` however I just ran it and it doesn't seem to support all ciphers annymore.

```
 | FIXME:  "android_237" has 0x0004 (4) | FIXME: 0x0005 (5) | FIXME: 0x002F (47) | FIXME: 0x0033 (51) | FIXME: 0x0032 (50) | FIXME: 0x000A (10) | FIXME: 0x0016 (22) | FIXME: 0x0013 (19) | FIXME: 0x0009 (9) | FIXME: 0x0015 (21) | FIXME: 0x0012 (18) | FIXME: 0x0003 (3) | FIXME: 0x0008 (8) | FIXME: 0x0014 (20) | FIXME: 0x0011 (17) "0xFF"
 | FIXME:  "android_404" has 0xC014 (49172) | FIXME: 0xC00A (49162) | FIXME: 0x0039 (57) | FIXME: 0x0038 (56) | FIXME: 0xC00F (49167) | FIXME: 0xC005 (49157) | FIXME: 0x0035 (53) | FIXME: 0xC012 (49170) | FIXME: 0xC008 (49160) | FIXME: 0x0016 (22) | FIXME: 0x0013 (19) | FIXME: 0xC00D (49165) | FIXME: 0xC003 (49155) | FIXME: 0x000A (10) | FIXME: 0xC013 (49171) | FIXME: 0xC009 (49161) | FIXME: 0x0033 (51) | FIXME: 0x0032 (50) | FIXME: 0xC00E (49166) | FIXME: 0xC004 (49156) | FIXME: 0x002F (47) | FIXME: 0xC011 (49169) | FIXME: 0xC007 (49159) | FIXME: 0xC00C (49164) | FIXME: 0xC002 (49154) | FIXME: 0x0005 (5) | FIXME: 0x0004 (4) "0xFF"
```

Do you want me to fix that?

Also should we discuss how we can turn this so you can maintain it?
