### ISSUE TITLE
Inconsistent / incorrect ROBOT attack results

### ISSUE THREAD

**Issue by ArtiomL** [drwetter/testssl.sh#1107]
Hi,

`testssl.sh` is being widely used to scan for the ROBOT CVE.
The results of the scan are inconsistent / incorrect based on various vendors running patched SSL versions.
   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
```
root@a242da076181:/testssl.sh# ./testssl.sh -b 2>/dev/null | head -4 | tail -2
    testssl.sh       3.0rc1 from https://testssl.sh/dev/
    (8d7dd66 2018-08-24 15:43:25 -- )
root@a242da076181:/testssl.sh# 
```
  

2. what exactly was happening, output is needed
```
 Testing for Return of Bleichenbacher's Oracle Threat (ROBOT) vulnerability 

 ROBOT                                     	not vulnerable (OK)

```
and
```
 Testing for Return of Bleichenbacher's Oracle Threat (ROBOT) vulnerability 

 ROBOT                                     VULNERABLE (NOT ok) - weakly vulnerable as the attack would take too long

```
for the **same** website.  

3. what did you expect instead?
A consistent:
```
 Testing for Return of Bleichenbacher's Oracle Threat (ROBOT) vulnerability 

 ROBOT                                     	not vulnerable (OK)

```
as we have verified they are running a patched version of the SSL proxy, which has been tested locally and is **not vulnerable**.

4. steps to reproduce

   1. testssl.sh command line
`./testssl.sh --robot <FQDN>`

    1. if possible: target IP
Will send via email.
 
    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
 ```
 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on a242da076181:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")
```

I have also tested using the latest openssl:
```
./testssl.sh --robot --openssl /usr/bin/openssl <FQDN>
No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl.sh       3.0rc1 from https://testssl.sh/dev/
    (3fdcd03 2018-08-23 11:40:50 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1-pre9 (beta) 21 Aug 2018" [~164 ciphers]
 on 2ebde63ac518:/usr/bin/openssl
 (built: "Aug 21 19:00:17 2018", platform: "debian-amd64")

```

1. your operating system (uname -a)

`Linux a242da076181 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux`

**Comment by drwetter** [comment]
As sent via mail: _currently_ the server doesn't seem to use RSA key transport ciphers.

On a side note: also in a docker container you shouldn't the script as root at least when you scan third parties

**Comment by drwetter** [comment]
First of all: it's weakly vulnerable. Don't take this as an example you should follow but Big Blue doesn't seem to care for Domino servers. 

The server seems now also regarding the headers different (BigIP).  If that's the terminating device @hannob might be also interested in. His robot-detect runs into a timeout 2x AND also reports a weak oracle as you did with testssl.sh (I comply with @dcooper16 here: still see an obviously  wrong output "Server does not support any cipher suites that use RSA key transport")

The run time I mentioned before is the default run. Only ``BB`` takes 46s for me.

**Comment by drwetter** [comment]
Closing this, no false positive. See internal communication.

**Comment by famzah** [comment]
@drwetter, please re-open this if appropriate, or delete my comment and I will submit a new issue instead.

---

I'm experiencing the same inconsistency in the results when repeatedly testing the same Debian server.

Here is an example for ports 465 (SSL-only) and 587 (STARTTLS):
```bash
famzah@vbox64:~/testssl$ for i in {1..20} ; do ./testssl.sh --robot famzah.net:465|grep " ROBOT" ; done
 ROBOT                                     not vulnerable (OK)
 ROBOT                                     VULNERABLE (NOT ok)
 ROBOT                                     VULNERABLE (NOT ok) - weakly vulnerable as the attack would take too long

famzah@vbox64:~/testssl$ for i in {1..20} ; do ./testssl.sh --robot --starttls smtp famzah.net:587|grep " ROBOT" ; done
 ROBOT                                     not vulnerable (OK)
 ROBOT                                     VULNERABLE (NOT ok)
 ROBOT                                     VULNERABLE (NOT ok) - weakly vulnerable as the attack would take too long
```

I cannot reproduce this on port 25 (STARTTLS) where I consistently get "not vulnerable (OK)". This is the expected result as the server is using the patched OpenSSL by Debian. Note: ports 465 & 587 are served by a different server implementation compared to the server for port 25.

You should be able to reproduce on your end easily. It takes a couple of attempts to get different results. Usually in less than 10 attempts you will encounter a different result.

It you can't reproduce, I have saved the screen output and the "/tmp" dir content for both "not vulnerable (OK)" and "VULNERABLE (NOT ok)" runs executed with `debug=3`. If you need the saved data, I will attach it here.

The question is -- Is "testssl.sh" encountering a bug and reports inconsistent results, or is it the server for ports 465 & 587 which does something weird and really is vulnerable.

Thank you.

---

Here is my environment:
```bash
famzah@vbox64:~/testssl$ ./testssl.sh -b 2>/dev/null | grep "from"
    testssl.sh       3.0.6 from https://testssl.sh/

famzah@vbox64:~/testssl$ ./testssl.sh -b 2>/dev/null | grep -A3 OpenSSL
 Using "OpenSSL 1.1.1f  31 Mar 2020" [~79 ciphers]
 on vbox64:/usr/bin/openssl
 (built: "Aug 23 17:02:39 2021", platform: "debian-amd64")

# maybe related to: https://github.com/drwetter/testssl.sh/issues/1119
famzah@vbox64:~/testssl$ ./testssl.sh --robot --starttls smtp famzah.net:587|head -n2|tail -n1
No engine or GOST support via engine with your /usr/bin/openssl

famzah@vbox64:~/testssl$ lsb_release -a
Description:    Ubuntu 20.04.3 LTS

famzah@vbox64:~/testssl$ uname -a
Linux vbox64 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by drwetter** [comment]
Hi @famzah ,

please open a new issue. It should be consistent. Please report also the IP address as it seems the MX records point to google whereas famzah.net seems to point somewhere else. If it's your Debian server it would be great to know a bit about the server side (openssl version, qmail version).

You don't have to post private data here if you dont' want to  (``grep SWCONTACT =testssl.sh``)

Thx, Dirk

**Comment by famzah** [comment]
I've created issue #2083. Thank you.
