### ISSUE TITLE
Alert Id changes

### ISSUE THREAD

**Issue by CSPF-Founder** [drwetter/testssl.sh#1111]
Hi,

The alert Id is getting changed in each update. Example: In previous versions, the weak 128 bit cipher alert id was "std_128Bit", it is changed to "cipherlist_128Bit".  Many other alert id also changed in new updates.  

If you keep on changing the alert id, it won't be useful in corporate environment.  If you want the tool to be popular and useful for everyone, it should be standardized and maintain a proper format and alert ids(especially alert id should not be changed in updates).  Otherwise people will afraid of updates and ignore the new issues.

**Comment by drwetter** [comment]
The basis of development is moving forward.

It's your choice: if you don't want changes or worry about those pick the releases and don't use the development branch - as Linux distributors do.



-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection
