### ISSUE TITLE
Make JSON <s>great again</s> more robust

### ISSUE THREAD

**Issue by asadasivan** [drwetter/testssl.sh#1112]
Please make sure that you provide enough information so that we understand what your issue is about.

   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
    testssl.sh       3.0rc1 from https://testssl.sh/dev/

2. what exactly was happening, output is needed
    Getting a JSONDecodeError because of trailing commas in JSON output file.

3. what did you expect instead?
    JSON output should not contain any trailing commans

4. steps to reproduce
    A. ./testssl.sh --jsonfile "/home/tmp/testssloutput.json" --std --protocols --server_defaults --vulnerable <URI>
    B. Open testssloutput.json file and search for cert_notBefore and cert_notAfter. Both tests will have leading commas.
    C. Ex: 
         {
              "id"           : "cert_notBefore",
              "ip"           : "<host>/<host>",
              "port"         : "8443",
              "severity"     : "INFO",

          }
,         {
              "id"           : "cert_notAfter",
              "ip"           : "<host>/<host>",
              "port"         : "8443",
              "severity"     : "OK",

          }
      D. Reasoning:
          JSONDecodeError due to trailing commas which needs to be removed
      E. Tried on both mac and ubuntu: 16.0 versions

**Comment by dcooper16** [comment]
Hi @asadasivan ,

I just tried this and did not encounter the problem that you did. After the "severity" there should be an entry specifying a "finding". In the case of "cert_notBefore" and "cert_notAfter" the "finding" should be the notBefore and notAfter value, respectively.

Looking at the source code I see that an entry will not be printed if the value is empty. So, if for some reason the notBefore and notAfter dates were not correctly determined, then that could result in the "finding" not being printed, which would result in the trailing comma that you are seeing.

What are you seeing in the printed output? There should be a line that looks something like:
```
 Certificate Validity (UTC)   4503 >= 60 days (2016-07-21 10:36 --> 2030-12-30 09:00)
```
My guess is that you are seeing just "( --> )" within the parentheses, and that the number of days until expiration isn't right either? If so, then this isn't specifically a JSON error, but an error in extracting the dates from the certificate. So, we need to try to figure out why the dates are being extracted correctly.

**Comment by drwetter** [comment]
Hi @asadasivan ,

1) any IP would be helpful (mail: ``grep SWCONTACT testssl.sh)
2) does that only work on this IP? Check ``testssl.sh -S --json testssl.sh``

Cheers, Dirk

**Comment by asadasivan** [comment]
Hello Dirk / David,

It is an internal host that is using self signed certificate. I started
using JsonComment to address any comments/trailing commas. I also tried it
on the 2.9.5 branch and I did not get the formatting error. For your
information, I am also running testssl.sh as Docker container with alpine
linux as base image. The host is mac / Ubuntu 16.

Thanks,
Arun

**Comment by drwetter** [comment]
Hi Arun,

ok, 1) is then off the table but still you need to provide us with the information requested. 
See 2) above. And what is the screen output for the validity (see David's question).

Dirk

**Comment by asadasivan** [comment]
Hello All,

Please find attached snapshots. Getting an invalid date error on the
console. Also, you could see on the second snaphot about the trailing
commas for both cert_notBefore and cert_notAfter. JSON file should not
contain any trailing commas. This is failing only on the dev branch. On
2.9.5 it works fine.

Thanks,
Arun

**Comment by asadasivan** [comment]
Hello All,

Sending the files again. Not sure if it sent the files.

Thanks,
Arun

**Comment by drwetter** [comment]
Did not arrive here, Arun. :(

I guess inserting a payload to github works only with the browser, not via mail. ;-)

**Comment by asadasivan** [comment]
<img width="798" alt="screen shot 2018-09-01 at 9 01 35 am" src="https://user-images.githubusercontent.com/16688352/44947091-68072600-adcd-11e8-87ff-a25f359baf77.png">
<img width="606" alt="screen shot 2018-09-01 at 9 05 39 am" src="https://user-images.githubusercontent.com/16688352/44947092-68072600-adcd-11e8-90f3-e80b4a1e00bf.png">

**Comment by drwetter** [comment]
There's also no IP address and the value in _certs_countServer_ seems strange. If you run it from busybox as the nslookup error message indicates -- that is not really supported. Where did you pull the  docker container from?
 
Could you please run ``./testssl.sh -S --debug=1`` and pass to me he host certificate (``/tmp/testssl.<seestringonscreen>/host_certificate.pem`` to me?

**Comment by asadasivan** [comment]
I am able to figure out why the date column was not working. It looks like
if you are using alpine Linux then you need to install bindtools, coreutils
and curl for it to work. The current output is as follows:
Certificate Validity (UTC)   317 >= 60 days (2015-06-09 20:47 -->
2019-07-18 20:47)

**Comment by drwetter** [comment]
As said, please check with the docker image / file provider. Feel free to use my docker file or pull the corresponding image from dockerhub (see docu).

I'll leave this open to make the JSON output more robust. Please consider your point as close though.
