### ISSUE TITLE
no matching cipher in this list found (pls report this)

### ISSUE THREAD

**Issue by Tributh** [drwetter/testssl.sh#1115]
Hi,
here are all details to reproduce:

./testssl.sh -b 2>/dev/null | head -4 | tail -2
    testssl.sh       3.0rc1 from https://testssl.sh/dev/
    (8d7dd66 2018-08-24 15:43:25 -- )

/testssl.sh --quiet --warnings off tributh.net:853|grep report

 Has server cipher order?     no matching cipher in this list found (pls report this): DES-CBC3-SHA:RC4-MD5:DES-CBC-SHA:RC4-SHA:AES128-SHA:AES128-SHA256:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-RSA-AES128-SHA:ECDH-RSA-AES256-SHA:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA256:ECDHE-RSA-DES-CBC3-SHA:ECDHE-RSA-AES128-SHA256:AES256-GCM-SHA384:AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA256:ADH-AES256-GCM-SHA384:AECDH-AES128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-AES128-SHA:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256  . 
 Session Resumption           Ticket resumption test failed, pls report / ID resumption test failed, pls report

**Comment by drwetter** [comment]
Thx for reporting, Torsten.

This check is one of the few leftovers which hasn't been migrated by 100% from openssl to sockets. It works with a recent openssl 1.1.1 version:

```
 Testing server preferences

 Has server cipher order?     yes (OK)
 Negotiated protocol          default proto empty
 Negotiated cipher            default cipher empty, 253 bit ECDH (X25519)
 Cipher order
    TLSv1.2:   ECDHE-ECDSA-CHACHA20-POLY1305
    TLSv1.3:   TLS_CHACHA20_POLY1305_SHA256 TLS_AES_256_GCM_SHA384 TLS_AES_128_GCM_SHA256
```

The catch is ``Negotiated protocol`` and ``Negotiated cipher`` being empty though. So except your original issue there's another hiccup.

Dirk

**Comment by TTributh** [comment]
Hi,
I haven't checked the whole code, but it seems to me that several connections are tried with a too short Cipher list. I know that I have only very few ciphers active here. For me it seems that the CHACHA Cipher is not always checked which gives results, like no cipher or protocol is active.

The server is running openssl-1.1.1-pre9 with TLS1.3 enabled and only one TLS1.2 Cipher active.
When I enable an extra GCM cipher, the results are much better.

Ideas?

Torsten

**Comment by drwetter** [comment]
> When I enable an extra GCM cipher, the results are much better. Ideas?

For TLS 1.2  you're getting your output as _one_ cipher matches in two connects. There need to be two matching ciphers in the list to get a result.

Maybe it's a good idea to add code when only one cipher matches.

For TLS 1.3 servers:  parser for ``default proto empty`` is ``get_protocol()``. This has a problem with some TLS 1.3 connects. There is more than one possible reply for SSLv3-TLS1.2. Same applies for ciphers.

**Comment by drwetter** [comment]
@Tributh . This should be off the table by @dcooper16's changes to ``run_server_preference()``. Thus I am closing it. Happy to reopen if the problem persists
