### ISSUE TITLE
Asterisk expansion in header checling

### ISSUE THREAD

**Issue by shiftbreak** [drwetter/testssl.sh#1123]
The "csv" file output expands asterisk (*) that are in HTTP response headers leading to "ls ./" output being appended to the scan results.

Tested with following response header:

Content-Security-Policy-Report-Only: d * d

using the following command syntax:

./testssl.sh --csv -h -n none --assume-http https://XXXXXXX/

**Comment by drwetter** [comment]
Thanks for reporting! (e.g. can be seen at ``dev.testssl.sh``)

**Comment by drwetter** [comment]
Cool finding!

Anymore like this?
