### ISSUE TITLE
csv output no longer including IP/fqdn

### ISSUE THREAD

**Issue by fishouttah20** [drwetter/testssl.sh#1128]
Please make sure that you provide enough information so that we understand what your issue is about.

   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
**3.0rc1 from https://testssl.sh/dev/
(ef442f1 2018-09-19 09:30:28 -- )**
2. what exactly was happening, output is needed
**Parallel scan with csv output completes but csv file doesn't place IP/fqdn in the name, example:**
"id","fqdn/ip","port","severity","finding","cve","cwe"
"service","INFO","HTTP","","","",""
"SSLv2","OK","not offered","","","",""
"SSLv3","OK","not offered","","","",""
"TLS1","INFO","offered","","","",""
"TLS1_1","INFO","offered","","","",""
"TLS1_2","OK","offered","","","",""
"TLS1_3","INFO","not offered and downgraded to a weaker protocol","","","",""
"NPN","INFO","not offered","","","",""
"ALPN","INFO","not offered","","","",""
"cipher_order","OK","server","","","",""
"protocol_negotiated","OK","Default protocol TLS1.2","","","",""

3. what did you expect instead?
**value after first comma should be an IP address, no way to know which results correspond to which hosts.**

4. steps to reproduce

   1. testssl.sh command line
**./testssl.sh --file test.txt --mode parallel -p -S -P -h --openssl-timeout 60 --quiet --csvfile test.csv
Also tried with -oA
test.txt is text file with just IP addresses in it, one on each line.** 

    1. if possible: target IP
Don't believe this is relevant but DM if needed
 
    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
 **Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on evan-vm:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")**

    1. your operating system (uname -a)
**Linux xxxx-vm 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by drwetter** [comment]
Thx, can reproduce it.

A unit test for CSV output would have discovered this. ;-(

**Comment by drwetter** [comment]
will be done this evening

**Comment by drwetter** [comment]
Thx for reporting
