### ISSUE TITLE
TCP fragmentation caused by \x0a sent to socket

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1130]
As noted in the discussion of PR #1113 it seems that ``printf -- "$data" >&5 2>/dev/null`` does not do what it is intended. ``$data`` contains a ClientHello, 5 is the fd of a socket. "$data" is  a ClientHello like

``\x16\x03\x01\x2\x00\x01\x00\x1\xfc\x03\x03\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0a\...``

Each \x0a like the last one causes a new TCP fragment to begin which can be spotted when using wireshark while running e.g.

``testssl.sh --assume-http -p testssl.sh``

Starting from the SSLv3 ClientHello the first reassembled packet ends with 0a.

This ticket is for continuing the discussion from https://github.com/drwetter/testssl.sh/pull/1113#issuecomment-423555340 on

**Comment by drwetter** [comment]
dd might be worth looking into it .I am afraid that it is a "feature" of bash

**Comment by drwetter** [comment]
It turned out not to be a feature of bash + sockets but of the internal printf:

```
prompt> strace -ewrite bash -c 'printf "one\ntwo\n"' >/dev/null
write(1, "one\n", 4)                    = 4
write(1, "two\n", 4)                    = 4
+++ exited with 0 +++
prompt> strace -etrace=write /usr/bin/printf "one\two\n" > /dev/null
write(1, "one\two\n", 7)                = 7
+++ exited with 0 +++
```

We could also use ``stdbuf`` or ``dd`` (latter either directly for writing into the socket or as a pipe after any printf). : 

```
prompt> strace -etrace=write bash -c 'stdbuf -o1M printf "one\ntwo\n"  ' > /dev/null
write(1, "one\ntwo\n", 8)               = 8
+++ exited with 0 +++
prompt> bash -c 'printf "one\ntwo\n" | strace -e write,read -o/tmp/log.txt dd status=none bs=1M' > /dev/null
prompt> cat /tmp/log.txt
[..]
read(0, "one\ntwo\n", 1048576)          = 8
write(1, "one\ntwo\n", 8)               = 8
read(0, "", 1048576)                    = 0
+++ exited with 0 +++
```

**Comment by drwetter** [comment]
See commit. Solved

**Comment by drwetter** [comment]
see https://github.com/drwetter/testssl.sh/commit/305eefc9e81f7821f38eb045eea6bac5f7c7ef40 and #1134, #1135

**Comment by drwetter** [comment]
BSDish systems are still open -- at least if they do a write flush after "\x0a" which I don't know but assume.

@dcooper16 : You mind checking? There's a small chance that OS X libc behaves different

**Comment by drwetter** [comment]
note to self: ``/usr/bin/printf --version 2>&1 | grep -q GNU`` would have been better

**Comment by dcooper16** [comment]
As far as I can tell, it is the same with OS X. I am seeing the ClientHello message being broken into fragments.

**Comment by drwetter** [comment]
:-( but thanks. Long / mid term solution is probably ``dd``. Do you have stdbuf on OSX?

**Comment by dcooper16** [comment]
> Do you have stdbuf on OSX?

No. At least not on my computer.

**Comment by drwetter** [comment]
sigh

**Comment by drwetter** [comment]
Any good ideas how to convert hex to binary?

Just a few thoughts I thought to share:
I tried a few things today but it seems to me ``printf`` in general is still the best option.

Atm the best solution I see for OS X and FreeBSD in order to avoid fragmentation is piping ``printf` through ``dd`` or ``cat``. 

Interesting:  The internal ``echo -e``.  The internal one also does fragmentation btw.

**Comment by drwetter** [comment]
see also commit 1b52834dfcbc7da77fa69e0eca4df44be8cfa295
