### ISSUE TITLE
Missing TLSv1 and TLSv1.2 protocols from Cipher order

### ISSUE THREAD

**Issue by aidanadia** [drwetter/testssl.sh#1132]
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
   
testssl.sh       3.0rc1 from https://testssl.sh/dev/
(441f14a 2018-09-24 10:30:30 -- )

2. what exactly was happening, output is needed

The following is the output when executing this syntax : 
> ./testssl.sh --jsonfile-pretty testssl_result.json {hostname}
```
Testing server preferences

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH (P-256)
 Cipher order
    TLSv1.2:   ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA AES128-GCM-SHA256 AES128-SHA256 AES128-SHA AES256-GCM-SHA384 AES256-SHA256 AES256-SHA
```

While the following is the output while executing this command : 
> ./testssl.sh -P {hostname}
```
Testing server preferences 

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH (P-256)
 Cipher order
    TLSv1:     ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-SHA AES128-SHA AES256-SHA 
    TLSv1.1:   ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-SHA AES128-SHA AES256-SHA 
    TLSv1.2:   ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA AES128-GCM-SHA256 AES128-SHA256 AES128-SHA AES256-GCM-SHA384 AES256-SHA256 AES256-SHA
```

3. what did you expect instead?
Both command produce the same output on Testing server preferences 

4. steps to reproduce

i.  testssl.sh command line

>  ./testssl.sh --jsonfile-pretty testssl_result.json {hostname}

ii. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)

```
 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
./bin/openssl.Darwin.x86_64
 (built: "Sep  7 19:34:54 2016", platform: "darwin64-x86_64-cc")
```

iii. your operating system (uname -a)
```
16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
```

**Comment by drwetter** [comment]
you didn't explicitly mention it: Is <hostname> in both examples the same?

**Comment by aidanadia** [comment]
If you mean the same hostname, yes, both command using the same hostname.

**Comment by drwetter** [comment]
Then I would need the hostname please in order to reproduce it -- I can't with arbitrary hostnames.

``grep SWCONTACT testssl.sh``

**Comment by aidanadia** [comment]
You're welcome and thanks!

**Comment by drwetter** [comment]
For the default scan the protocols are detected wrong. This is just the result. There's a strange prob putting the clienthello together under FreeBSD+ MacOS X.

**Comment by aidanadia** [comment]
Yes, it works now under OSX. Thanks!
