### ISSUE TITLE
Nice to have: equiv of JSON property "target host" w/ no spaces

### ISSUE THREAD

**Issue by bitsofinfo** [drwetter/testssl.sh#1150]
With `--json*` arguments the resulting JSON's `"target host"` property is not parseable by certain libraries tools due to the space in it.

```{
          "Invocation"  : "testssl.sh --logfile .........",
          "at"          : "ABCD.........",
          "version"     : "3.0rc2 7adc1b6 from 2018-10-29",
          "openssl"     : "OpenSSL 1.0.2-chacha from Sep  7 19:34:54 2016",
          "startTime"   : "1540838810",
          "scanResult"  : [
          {
                    "target host"     : "whatever.com",
                    "ip"              : "192.168.0.1",
                    "port"            : "443",
                    ....
```

3. what did you expect instead?

Would be nice to see something like this instead: (retaining existing name for back compat)

```{
          "Invocation"  : "testssl.sh --logfile .........",
          "at"          : "ABCD.........",
          "version"     : "3.0rc2 7adc1b6 from 2018-10-29",
          "openssl"     : "OpenSSL 1.0.2-chacha from Sep  7 19:34:54 2016",
          "startTime"   : "1540838810",
          "scanResult"  : [
          {
                    "targetHost"     : "whatever.com",
                    "target host"     : "whatever.com",
                    "ip"              : "192.168.0.1",
                    "port"            : "443",
                    ....
```

**Comment by drwetter** [comment]
a) Seems your JSON parser is broken  ;-)
b) But you're right, looks more consequently changing this. :-) 

I would rather like to remove the legacy target name then too. It has been introduced not a long time ago

@ all: heads up. This is a warning for a possible breaking change..``target host`` will be changed ~today  to ``targetHost``

**Comment by bitsofinfo** [comment]
agreed, the json parser should support it, however it also hinders alot of things that turn property names into actual variables inside code object etc, or class generators etc.

i'd suggest leaving "target host" for backwards compatibility, there could be a ton of people with automation around this. I don't see any harm in leaving it?

**Comment by drwetter** [comment]
> there could be a ton of people with automation around this.

The number should be not as high as ``target host`` has been introduced not too far back.

> I don't see any harm in leaving it?

It would be an ugly relic which would make it into the release.

So be warned

**Comment by drwetter** [comment]
done
