### ISSUE TITLE
Weak 128 Bit ciphers

### ISSUE THREAD

**Issue by exploide** [drwetter/testssl.sh#1157]
I think the current rating regarding "Weak 128 Bit ciphers (SEED, IDEA, RC[2,4])" is a bit confusing and unclear to me.

Why is SEED considered a weak 128 bit cipher? I tried to research but found no known weaknesses that make this algorithm bad. The relevant point for the rating is that in TLS, SEED got only specified in CBC mode and in combination with SHA-1 KDF/MAC. And then it got removed from the standard because less researched algorithms do not bring a huge benefit.

(IDEA, on the other hand, appears to has some more attacks but not of real practical relevance. But is also operates on 64 bit blocks, so maybe it is susceptible to SWEET32 like Triple-DES.)

So, is there a reason why SEED (and maybe IDEA) is considered a weak 128 bit cipher? If not I propose to change the wording or restructure the whole cipher categories section.

A possible change would be:

- change "LOW" to  "weak algorithms", put RC2/4 into this category
- change "Weak" to "Deprecated 128 bit ciphers" for IDEA and SEED

Maybe it could be structured even better.

But at first, I'm curious about what you think and why the structure is as it currently is.

**Comment by exploide** [comment]
Yeah, it's complicated to structure all this stuff...

Maybe IDEA falls into the same category as 3DES, due to the cipher with 64-bit block length thing.

SEED, on the other hand, could be omitted, since it isn't that bad to be criticized but it is also not as good as AES, especially because there is no cipher suite in TLS that combines SEED with a strong block mode or a strong hash function.

If the Weak category is rather empty then, maybe shift RC2/4 to the LOW category. They aren't much stronger than DES, aren't they?!

So in the end, maybe we have categories like

- Low: DES, RC2, RC4
- Medium: 3DES, SEED
- High: AES, Camellia
- AEAD ciphers

(Besides I'm wondering whether weakened hash functions like MD5 and SHA-1 for KDF/MAC use shoule be penalized with a yellow marking, e.g. in the cipher table. But that's a different topic and not really urgent since attack MAC algorithms is pretty hard even with bad hash functions.

**Comment by drwetter** [comment]
Moved RC2, RC4 to low first. Please note that I change also for  the file output 'DES+64Bit' --> 'LOW'

**Comment by drwetter** [comment]
before:

![screenshot_20190117_120957](https://user-images.githubusercontent.com/8036727/51317846-f9172a80-1a58-11e9-9852-5e6b61a751d6.png)

after:

![screenshot_20190117_125550](https://user-images.githubusercontent.com/8036727/51317857-03d1bf80-1a59-11e9-8fb4-86fe0435410e.png)

**Comment by drwetter** [comment]
Just scratching my head wrt to SEED.

> SEED, on the other hand, could be omitted, since it isn't that bad to be criticized but it is also not as good as AES, especially because there is no cipher suite in TLS that combines SEED with a strong block mode or a strong hash function.

The latter is true and a good point but OTOH I also have other ciphers in HIGH with AES which are comparable to SEED:

![screenshot_20190117_151512](https://user-images.githubusercontent.com/8036727/51324388-e4dc2900-1a6a-11e9-9320-026640caa6c5.png)

Probably this section needs new criteria at a certain point in time (hash functions, protocol consideration too), but in this phase I'd rather not do this.

**Comment by drwetter** [comment]
see commit.

**Comment by djcater** [comment]
@drwetter Thanks for this change.

I now find something slightly odd though: AES-128 in CBC mode is coloured yellow, whereas AES-256 in CBC mode is coloured green. I think the security benefit of AES-256 CBC over AES-128 CBC is debatable?

If you look at the Chrome browser handshake as well for example at https://www.ssllabs.com/ssltest/viewMyClient.html you can see that they prefer 128 over 256 (all else being equal), presumably because the threats against AES-128 are minimal and it's faster.

To me it would make more sense if they were considered in the same category at least.

**Comment by drwetter** [comment]
It's getting more complicated as I wanted it to be at this time. Looking just at the [Cipher Security Summary](https://en.wikipedia.org/wiki/Cipher_security_summary) 256 bit requires definitely way more time for an attack. 
  
But, you're right, as I differentiated between AEAD ciphers (CCM, GCM) on one hand and 128 bit CBC ciphers before, I can as well downgrade 256 bit CBC ciphers (AES, Camellia, Aria) to join their 128 bit counterparts and SEED+IDEA ciphers as well and rename the JSON identifier to something else then ``128Bit``. 

But then I might be unfair to put 256 bit ciphers in the same category as 128 bit SEED or IDEA. The only thing to argue then is that this drawer contains the deprecated species.

Last order ;-)

**Comment by djcater** [comment]
@drwetter I definitely think it makes more sense to differentiate between CBC and GCM than it does between 128 and 256. I think AES 128 CBC and AES 256 CBC should be in the same group.

IDEA uses 64-bit blocks, so presumably is vulnerable to SWEET32, so should be shown in a weaker category than SEED or Camellia (maybe combine IDEA with 3DES into a category for weak block sizes?).

**Comment by drwetter** [comment]
For SEED there's no information available wrt to any weakness for what you claim. Not in the SWEET32 paper, not in the cipher security summary.

We need to stick to what is known.

**Comment by djcater** [comment]
@drwetter I think you may have misinterpreted my comment, apologies if it was unclear. I was not claiming that _SEED_ is vulnerable to SWEET32.

I said:

> IDEA uses 64-bit blocks, so presumably is vulnerable to SWEET32, so should be shown in a weaker category than SEED or Camellia

So I was referring to **IDEA**.

IDEA _is_ listed in the SWEET32 paper as an example of a cipher which uses 64-bit blocks, and is shown in red in Table 1 (alongside DES, 3DES, and Blowfish), implying that it would be vulnerable to the same type of attack. This makes sense, as any block size will experience collisions eventually, but due to the much smaller number of possible blocks values (2^64 times less than with a 128-bit block size), the chance of a collision is plausible within a relatively short amount of time due to the birthday problem.

Therefore I'm suggesting that, due to its 64-bit block size, IDEA is shown as weaker than SEED and Camellia. Hopefully that makes sense.

**Comment by drwetter** [comment]
oh well, I am sorry. I had a flu and I was half way between dead and alive ;-) 

I agree on this.

Wrt to the 256 bit CBC ciphers (i.e. not using authenticated encryption) they will be merged into the 128 bit category. So we'll loose the high ciphers category.

**Comment by drwetter** [comment]
Language issue: Is there any word you could think of for labeling the SEED +128/256 bit CBC ciphers?

_medium_ sounds IMO too mediocre, _high_ too good.  Something in between would be great.

**Comment by drwetter** [comment]
Thanks for the discussions!

**Comment by djcater** [comment]
@drwetter Thanks for the changes! I think the grouping is much better now.

However I think there's a bug. I get the output:
```
 Average: SEED + 128+256 Bit CBC ciphers       not offered
```
on every server I've tested, even if the server supports AES CBC-mode cipher suites such as `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`.

If I run the `grep` command from the code inside an up-to-date testssl.sh:
```
egrep -w "256|128" etc/cipher-mapping.txt | egrep -v "Au=None|AEAD|RC2|RC4|IDEA"
```
Then the relevant cipher suites do show up in the output.

Edit: I just tested with `--ssl-native` and it works.
```
 Average: SEED + 128+256 Bit CBC ciphers       offered
```
So the problem is with sockets.

**Comment by drwetter** [comment]
Thanks for your scrutiny. An empty variable was the cause.

**Comment by drwetter** [comment]
Some changes ahead, see #1416

**Comment by bilogic** [comment]
Hi,

Can I ask, what are 128/256 bit CBC ciphers? I'm trying to disable them in my postfix/dovecot and apache. Thank you.

**Comment by exploide** [comment]
Hi, let me answer your question step by step:

128 or 256 bit refers to the length of the symmetric key used in a cipher like AES. Both length are totally fine and are considered secure as of today.

When encrypting data with a block cipher like AES, the input in split into blocks of a fixed length, since the actual encryption scheme operates on such blocks, one after another. These multiple blocks need to be combined in some way to make sure that equal input blocks do not encrypt to the same output blocks (that would be insecure and reveal information about the input's structure). There are several different ways to do this and those are called block modes.

One block mode is the cipher block chaining mode (CBC). It was (and is) used for a long time and was once considered to be state of the art. However, in the past couple of years, several attacks were published targeting CBC mode. Sometimes it was not really CBC's fault but the way it is used in combination with authentication checking (MAC). So it turns out using CBC in a secure way was more difficult than expected and patches in the OpenSSL library turned out to be huge and even introduced other vulnerabilities.

After all, we have stronger block modes today. One example is the Galois counter mode (GCM). Hence, for very strong security (i.e. against Nation State Adversaries, ...), it is recommended to disable TLS cipher suites that make use of the CBC mode.

If you want to disable these cipher suites, you need to know how they are called in the respective application's configuration. Usually they contain CBC, like in `RSA-AES-128-CBC-SHA1`. But sometimes the CBC part is left out and it reads `RSA-AES-128-SHA1`. It depends on your application and crypto library. But it should be easy to look that up, now that you know what you are searching for.

Generally, I recommend Mozilla's TLS configuration generator: https://ssl-config.mozilla.org/

It can generate secure TLS configurations for a multitude of applications.
However, note that disabling cipher suites can have a negative impact on the compatibility with older clients. You decide if you care.
