### ISSUE TITLE
Unnecessary SSLHonorCipher warning

### ISSUE THREAD

**Issue by NetBender** [drwetter/testssl.sh#1160]
### Issue description
Hi.
I just tested a server and I noticed that, even if it does not support other protocols than TLS 1.2, testssl.sh warns me about the missing server's cipher order.

![cipherorder](https://user-images.githubusercontent.com/3443323/48950734-741e0200-ef3c-11e8-9660-49edf611354c.png)

The issue is that, according to the (Apache) mod_ssl [documentation](https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslhonorcipherorder), the server's preference is only needed when supporting SSLv3 or TLSv1.

Am i missing something or, in this case, the script should not warn me about this "absence"?

Best regards.

### My configuration

1. testssl.sh v3.0rc2 from https://testssl.sh/dev/ (5b3e610 2018-11-19 10:57:29 -- );
2. OpenSSL v1.0.2-chacha (1.0.2i-dev);
3. Linux, 4.18.0-11-generic;
4. command run: `testssl.sh -p -P <website>` (that only supports TLS 1.2).

**Comment by drwetter** [comment]
Hi @NetBender ,

that is a wrong assumption. The docu says ``When choosing a cipher during an SSLv3 or TLSv1 handshake, normally the client's preference is used.``. Given that it doesn't say that for >=TLS 1.1 it will be the always the server.

``If this directive is enabled, the server's preference will be used instead.`` <-- this is the important sentence.

The test determines in fact the ciphers which come first when the server has the say which one to choose first.

If you change it you should see a difference in the client section too.

Dirk
