### ISSUE TITLE
Compiling curl with the OpenSSL library from there

### ISSUE THREAD

**Issue by slayerulan** [drwetter/testssl.sh#1161]
Hello,
How can i compile curl with OpenSSL library that you have in the bin/ folder?

Thanks

**Comment by teward** [comment]
FYI what you're after are the OpenSSL **libraries** not the binaries shipped in `/bin`.  I'm pretty sure you won't be able to.  (And your question is not related to the TestSSL tool...)

**Comment by drwetter** [comment]
I do not provide the libraries. But you can help yourself see Readme.md @ https://github.com/drwetter/testssl.sh/tree/2.9dev/bin starting from ``git clone https://github.com/drwetter/openssl``
