### ISSUE TITLE
Fatal error: repeated openssl s_client connect problem, doesn't make sense to continue

### ISSUE THREAD

**Issue by MirkoDziadzka** [drwetter/testssl.sh#1172]
Please make sure that you provide enough information so that we understand what your issue is about.

1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)

    testssl.sh       3.0rc2 from https://testssl.sh/dev/

2. what exactly was happening, output is needed

Running testssl in a docker container against a web server. Scan started and then ended with an unclear error message.

Here is the full output
```
###########################################################
    testssl.sh       3.0rc2 from https://testssl.sh/dev/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2g  1 Mar 2016" [~124 ciphers]
 on b8aa539994ae:/usr/bin/openssl
 (built: "reproducible build, date unspecified", platform: "debian-amd64")


 Start 2018-12-05 14:03:07        -->> 193.99.144.80:443 (heise.de) <<--

 Further IP addresses:   2a02:2e0:3fe:1001:302:: 
 rDNS (193.99.144.80):   redirector.heise.de.
 Service detected:       HTTP


 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 TLS 1.3    not offered
 NPN/SPDY   http/1.1 (advertised)
 ALPN/HTTP2 not offered

 Testing cipher categories 

 NULL ciphers (no encryption)                  not offered (OK)
 Anonymous NULL Ciphers (no authentication)    not offered (OK)
 Export ciphers (w/o ADH+NULL)                 not offered (OK)
 LOW: 64 Bit + DES encryption (w/o export)     not offered (OK)
 Weak 128 Bit ciphers (SEED, IDEA, RC[2,4])    not offered (OK)
 Triple DES Ciphers (Medium)                   not offered (OK)
 High encryption (AES+Camellia, no AEAD)       offered (OK)
 Strong encryption (AEAD ciphers)              offered (OK)


 Testing robust (perfect) forward secrecy, (P)FS -- omitting Null Authentication/Encryption, 3DES, RC4 

 PFS is offered (OK)          ECDHE-RSA-AES256-GCM-SHA384
                              ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA
                              DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256
                              DHE-RSA-AES256-SHA DHE-RSA-CAMELLIA256-SHA
                              ECDHE-RSA-AES128-GCM-SHA256
                              ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA
                              DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256
                              DHE-RSA-AES128-SHA DHE-RSA-CAMELLIA128-SHA 
 Elliptic curves offered:     prime256v1 


 Testing server preferences 

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH (P-256)
 Cipher order
    TLSv1.1:   ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-SHA DHE-RSA-AES128-SHA
               DHE-RSA-AES256-SHA AES128-SHA AES256-SHA DHE-RSA-CAMELLIA256-SHA
               CAMELLIA256-SHA DHE-RSA-CAMELLIA128-SHA CAMELLIA128-SHA 
    TLSv1.2:   ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384
               DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES256-GCM-SHA384
               ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA
               ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA
               DHE-RSA-AES128-SHA256 DHE-RSA-AES128-SHA DHE-RSA-AES256-SHA256
               DHE-RSA-AES256-SHA AES128-GCM-SHA256 AES256-GCM-SHA384
               AES128-SHA256 AES256-SHA256 AES128-SHA AES256-SHA
               DHE-RSA-CAMELLIA256-SHA CAMELLIA256-SHA DHE-RSA-CAMELLIA128-SHA
               CAMELLIA128-SHA 


Fatal error: repeated openssl s_client connect problem, doesn't make sense to continue

```

3. what did you expect instead?

Should succeed or give a better error message

4. steps to reproduce

Use the following Dockerfile

```
FROM ubuntu

RUN apt-get -y update
RUN apt-get -y install bsdmainutils
RUN apt-get -y install dnsutils
RUN apt-get -y install openssl
RUN apt-get -y install wget

WORKDIR /test-ssl
ENV TESTSSL_INSTALL_DIR=/test-ssl
RUN wget https://testssl.sh/etc+doc.tar.gz
RUN wget https://testssl.sh/testssl.sh
RUN tar xvzf etc+doc.tar.gz

# CMD /bin/bash /test-ssl/testssl.sh https://10.151.20.35/
CMD /bin/bash /test-ssl/testssl.sh https://heise.de
```

create a docker image and run it

```
docker build -t scanner . && docker run --rm -it scanner
```

Note that when you attach to this docker image, s_client is working fine

```
$ docker run --rm -it scanner bash
# openssl s_client -connect heise.de:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = redirector.heise.de
verify return:1
---
Certificate chain
 0 s:/CN=redirector.heise.de
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFXjCCBEagAwIBAgISA+p5m5ll6yYEsoDgE2as9X51MA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODEyMDIyMjA0M
...
```

**Comment by drwetter** [comment]
Hi Mirko,

> Fatal error: repeated openssl s_client connect problem, doesn't make sense to continue

see testssl.sh(1). :-P Means that there was a connection problem. There's a counter and if it reaches the threshold testssl.sh assumes that the target is not reachable anymore and gives up.

My first suspicion was that heise.de had some measures in place but I can't reproduce it. Can you?

You can adjust the number of failed attempts by enlarging the threshold like ``MAX_OSSL_FAIL=4 testssl.sh <yourcmd>`` and e.g. ``MAX_SOCKET_FAIL=4``. The default is two for both which proved sufficient for all cases so far.

**Comment by MirkoDziadzka** [comment]
@drwetter Well, I see this problem not only with `heise.de`, this was just my external example. I see this on  internal servers  too. And this reproducible on every run. Which let me assume that it is not a problem on TCP level.  

Is there a way to seen the original openssl error in addition to this connection error message?

On the other hand, when changing  `MAX_OSSL_FAIL` to 64, it is actually working for my case.

Thanks

**Comment by drwetter** [comment]
> Which let me assume that it is not a problem on TCP level.

I have my doubts but I am happy if you can prove me wrong. ;-)

> Is there a way to seen the original openssl error in addition to this connection error message?

Not really. You might see some and the last remainder in /tmp/testssl.xxxxx if you run with a ``--debug=Y`` switch. (xxxxx will be output on the screen).
 
With the recent commit you will see an additional warning if there's a connection problem. But you need to use github as your source. You might as well try ``docker run drwetter/testssl.sh <TARGET>`` with the Dockerfile form here.

> On the other hand, when changing MAX_OSSL_FAIL to 64, it is actually working for my case.

There are not so many openssl connects anymore. Most is done with TCP sockets. Which OTOH makes me believe that you could have a problem with openssl otherwise you would see a different error message.

**Comment by MirkoDziadzka** [comment]
it works with the latest github source instead of `https://testssl.sh/testssl.sh`

Thanks

**Comment by drwetter** [comment]
Thanks for the feedback, albeit I do not see a difference wrt your point. 🤔
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection
