### ISSUE TITLE
Questions: how can testssl.sh with OpenSSL 1.0.2 verify for TLS1.3?

### ISSUE THREAD

**Issue by sanderjo** [drwetter/testssl.sh#1173]
Not a bug, but a question:

How can testssl.sh with OpenSSL 1.0.2 verify for TLS1.3?

On my stone-old Ubuntu 14.04, testssl.sh correctly says:

```
 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]


 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
```

How does testssl do that? I want to use the same trick in some niche tool I use.

**Comment by dcooper16** [comment]
It's not using OpenSSL. As the documentation says:

> Any OpenSSL or LibreSSL version is needed as a helper. [Unlike] previous versions of testssl.sh almost every check is done via (TCP) sockets. Despite that some some statically linked OpenSSL binaries for major operating systems are supplied in ./bin/ .

There are some tests that testssl.sh performs that are performed just using OpenSSL, but for most tests OpenSSL is just used as a helper, either to perform auxiliary function (e.g., extracting information from the server's certificate) or to help speed things up.

**Comment by sanderjo** [comment]
Ah, I see. Clever. 

And: my question is wrong? Rephrase to "how can testssl.sh on old OSes verify for TLS1.3?"

**Comment by drwetter** [comment]
Or to phrase it differently: testssl.sh is just an application. And one of the good things is that it has minimal requirements for running on several platforms.
