### ISSUE TITLE
[Question] How to extract additional Info for each check

### ISSUE THREAD

**Issue by sashank** [drwetter/testssl.sh#1180]
This is really a Question and not an issue.
   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)
3.0 rc3

2. what exactly was happening, output is needed
We are running testssl.sh -oJ output.json $target , this is generating a json file with very basic information something like below 

```
                         {
                                "id"           : "cert_chain_of_trust",
                                "severity"     : "CRITICAL",
                                "finding"      : "failed (self signed)."
                           }
```
We could not make out much from the id "`cert_chain_of_trust`" , is there any additional information that can be printed with some flags to testssl.sh ? 

3. what did you expect instead?
Flags to print more information about each check

**Comment by drwetter** [comment]
Normally it should be self-explanatory. If not you need to correlate this with the terminal output. 

This this particular example just tells you what you can read: the certificate's chain of trust failed as the certificate is self signed. 

Don't know what your expectation is supposed to be?
