### ISSUE TITLE
TLS_FALLBACK_SCSV (RFC 7507) false negative ?

### ISSUE THREAD

**Issue by mpgn** [drwetter/testssl.sh#1183]
Hello,

I just scan a server that only accept SSLv3

![image](https://user-images.githubusercontent.com/5891788/51669615-23bb3300-1fc5-11e9-8dab-07836796b118.png)

But when it comes to check the `TLS_FALLBACK_SCSV (RFC 7507)` it says: `No fallback possible, TLS 1.2 is the only protocol (OK)`

![image](https://user-images.githubusercontent.com/5891788/51669705-4f3e1d80-1fc5-11e9-861c-e7da9cba3b96.png)

**testssl version : 2.9.5**

**Comment by mpgn** [comment]
Hello @drwetter 

The problem seems fixed in the 3.0 :+1: 

![image](https://user-images.githubusercontent.com/5891788/51683491-46ac0e00-1fea-11e9-91dc-325f33553121.png)

Keep the good work :)

**Comment by drwetter** [comment]
Thanks. 

Yet another reason to use 3.0rcX.
