### ISSUE TITLE
JSON output does not contain cert key algorithm

### ISSUE THREAD

**Issue by exploide** [drwetter/testssl.sh#1187]
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)

testssl.sh       3.0rc3 from https://testssl.sh/dev/

2. what exactly was happening, output is needed

When running a scan, the text output contains `Server key size              RSA 4096 bits` while the JSON output only contains

```json
         {
              "id"           : "cert_keySize",
              "ip"           : "host/ip",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "4096 bits"
          }
```

Since ECDSA certificates also exist, it is necessary to take the algorithm into account when talking about key sizes.

3. what did you expect instead?

The JSON output should also contain information about the certificate key algorithm.

**Comment by drwetter** [comment]
Hi @exploide,

not sure what you mean. The ``cert_signatureAlgorithm`` is in another object.

1) testssl.net shows one ECDSA cert
```
              "id"           : "cert_numbers",
              "ip"           : "testssl.net/104.18.35.81",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : "1"
          }
,         {
              "id"           : "cert_signatureAlgorithm",
              "ip"           : "testssl.net/104.18.35.81",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "ECDSA with SHA256"
          }
,         {
              "id"           : "cert_keySize",
              "ip"           : "testssl.net/104.18.35.81",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "256 EC bits"
          }
```

2) cloudflare.com shows multiple certificates 

``` 
prompt% grep -A4 -E 'cert_keySize|cert_signatureAlgorithm' cloudflare.com_p443-20190206-1646.json  
              "id"           : "cert_signatureAlgorithm <cert#1>",
              "ip"           : "cloudflare.com/198.41.214.162",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "SHA256 with RSA"
--
              "id"           : "cert_keySize <cert#1>",
              "ip"           : "cloudflare.com/198.41.214.162",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : "2048 bits"
--
              "id"           : "cert_signatureAlgorithm <cert#2>",
              "ip"           : "cloudflare.com/198.41.214.162",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "ECDSA with SHA256"
--
              "id"           : "cert_keySize <cert#2>",
              "ip"           : "cloudflare.com/198.41.214.162",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "256 EC bits"
--
              "id"           : "cert_signatureAlgorithm <cert#3>",
              "ip"           : "cloudflare.com/198.41.214.162",
              "port"         : "443",
              "severity"     : "MEDIUM",
              "finding"      : "SHA1 with RSA"
--
              "id"           : "cert_keySize <cert#3>",
              "ip"           : "cloudflare.com/198.41.214.162",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : "2048 bits"

prompt%
```

**Comment by exploide** [comment]
Uhm, right... Maybe I just overlooked something. Sorry!

I have to check tomorrow if this really applies to my case, otherwise I will comment again.

**Comment by exploide** [comment]
Ah, I remember. I tought `cert_signatureAlgorithm` states the algorithm used to sign the server certificate (i.e. algorithm of the issuer). What I was asking is the algorithm of the subject's public key.

Can you solve my confusion and explain which of these two the `cert_signatureAlgorithm` field indicates?

(Besides, thanks to your example, I see that the `cert_keySize` field contains "EC" when it is about an elliptic curve public key. That's what I needed.)

**Comment by drwetter** [comment]
@exploide : is that solved now? See RFC 5280.l

signatureAlgorithm => you're right

cert_keySize => public key algo + bitsize 

However I sense a problem here. For Cloudflare.com e.g. there's on the terminal  ``Server key size              RSA 2048 bits`` whereas the JSON doesn't contain RSA.

**Comment by drwetter** [comment]
should be clearer now, see last commit

Sorry, I read your comment a while back but as the last line contained _That's what I needed_ I thought it's all fine.

**Comment by exploide** [comment]
Yes, I think your latest changes improve the situation. Thanks!

Just a small thing: For ECDSA keys, you just state EC. This is currently unambiguous, because it is the only elliptic curve algorithm in use. But in the near future and thanks to https://tools.ietf.org/html/rfc8410 I expect Ed25519 and Ed448 certificates in the wild. While these could easily named a bit differently in testssl, they are definitely elliptic curve algorithms, too. So maybe it would be less ambiguous to say ECDSA instead of EC.

**Comment by dcooper16** [comment]
> Just a small thing: For ECDSA keys, you just state EC. This is currently unambiguous, because it is the only elliptic curve algorithm in use. But in the near future and thanks to https://tools.ietf.org/html/rfc8410 I expect Ed25519 and Ed448 certificates in the wild. While these could easily named a bit differently in testssl, they are definitely elliptic curve algorithms, too. So maybe it would be less ambiguous to say ECDSA instead of EC.

I do not believe that a change is needed here. The text is intended to describe the type of public key that appears in the certificate. In this case it is an elliptic curve (EC) public key, which could be used to either create digital signatures (using ECDSA) or to perform key agreement (with [ECDH](https://en.wikipedia.org/wiki/Elliptic-curve_Diffie%E2%80%93Hellman) or [ECMQV](https://en.wikipedia.org/wiki/MQV)).

As you note, in the future we may see certificates with public keys using Curve25519 or Curve448 intended for use with [EdDSA](https://en.wikipedia.org/wiki/EdDSA) (Ed25519 or Ed448). However, public keys of these types may also be used with ECDH, and they still are elliptic curve public keys. So, I believe it is most appropriate to refer to them as EC keys.

However, if we start seeing certificates that are signed with EdDSA, then we could consider updating the code that outputs the "Signature Algorithm" to include options such as "EdDSA with SHA256".

**Comment by drwetter** [comment]
We could be more precise wrt the algorithm, I thought about that. For now (3.0) we better leave it like it is as it could break things
