### ISSUE TITLE
mass scan --file having problem

### ISSUE THREAD

**Issue by irawanhd** [drwetter/testssl.sh#1189]
Please make sure that you provide enough information so that we understand what your issue is about.

   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)

2. what exactly was happening, output is needed
###########################################################
    testssl.sh       2.8rc3 from https://testssl.sh/dev/
    (1.562 2016/11/05 13:55:29)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on 9e51ad324a21:/usr/local/bin/testssl/bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")

====== Running in file batch mode with file="single" ======

====================================================================================
/usr/local/bin/testssl/testssl.sh --csv  --warnings=batch -q --append 1.1.1.1

" available: No IPv4 address for "1.1.1.1

3. what did you expect instead?

batch will work 

4. steps to reproduce

   1. testssl.sh command line
  
**testssl.sh --file file.txt**

    1. if possible: target IP

 **1.1.1.1**

    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)

 **testssl.sh       2.8rc3**

    1. your operating system (uname -a)

**Linux  4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux**

**Comment by drwetter** [comment]
@irawanhd : thanks for filing this one. However 2.8rc3 is a rather old version (see also date: ``2016/11/05``).  It's not supported anymore. Can't reproduce this with current 2.9.5-7 or 3.0rc3.

Where did you get the version from? It seems even it's running within a docker container. The easiest thing would be  https://github.com/drwetter/testssl.sh/blob/2.9dev/Dockerfile.md

**Comment by irawanhd** [comment]
hi @drwetter could gave me sample of file of mass scanning?
I probably do it wrong

thanks
