### ISSUE TITLE
"sed: invalid option -- 'E'" error

### ISSUE THREAD

**Issue by ilya-il** [drwetter/testssl.sh#119]
Hi! 
I'm using SLES 11 SP3 x64, GNU sed version 4.1.5 and testssl.sh version 2.4. There is an error running testssl.sh:
```
sed: invalid option -- 'E'
```
As I can see in documentation there is no '-E' option in sed - http://www.gnu.org/software/sed/manual/sed.html

So, I changed "-E" to "-e" on these lines and all works fine:
```
   841          data=$(echo "$1" | sed -e 's/# .*$//g' -e 's/ //g' | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//; /^$/d' | sed 's/,/\\/g' | tr -d '\n')
  2055          tls_proto_offered=$(grep -aw Protocol $TMPFILE | sed -E 's/[^[:digit:]]//g')
  2169          tls_proto_offered=$(grep -aw Protocol $TMPFILE | sed -E 's/[^[:digit:]]//g')
```

**Comment by drwetter** [comment]
Thx first!

''-E'' s tolerated on newer GNU sed version and is needed for regexp under BSD  -- there's a world outside GNU which I want to support too. ;-)

Didn't know though that older GNU sed version fail. This needs a workaround. 

Not that I want to base a workaround on this but just to satisfy my curiosity: what version of GNU sed is this? Even OpenSuse 11.4 Evergreen has GNU sed 4.2.1 and supports this option.

**Comment by drwetter** [comment]
Description of the headaches I went through: https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed/131940#131940

**Comment by ilya-il** [comment]
What a nice zoo with 'sed' =)

SLES is enterprise and conservative distribution, so sed is just 4.1.5
```
> sed --version
GNU sed version 4.1.5
Copyright (C) 2003 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.
```
No special variable set.

```
> set | grep -ai posix
        ZYPPER_CMDLIST=($(LC_ALL=POSIX $ZYPPER -q -h |                          sed -rn '/^[[:blank:]]*Commands:/,$ {
            opts=(${opts[@]}$(echo; LC_ALL=POSIX $ZYPPER -q lr |                                sed -rn '/^[0-9]/{
        opts=(${ZYPPER_CMDLIST[*]}$(echo; LC_ALL=POSIX $ZYPPER -q help 2>&1 |                   sed -rn '/Global Options:/,/Commands:/{
        opts=$(LC_ALL=POSIX $ZYPPER -q help $command 2>&1 | sed -e "1,/$magic_string/d" -e 's/.*--/--/' -e 's/ .*//');
                opts=(${opts[@]}$(echo; LC_ALL=POSIX $ZYPPER -q lr |                                    sed -rn '/^[0-9]/{
                opts=(${opts[@]}$(echo; LC_ALL=POSIX $ZYPPER -q ls |                                    sed -rn '/^[0-9]/{
                opts=(${opts[@]}$(echo; LC_ALL=POSIX $ZYPPER -q ll |                                    sed -rn '/^[0-9]/{
```
P.S.
I have new SLES 12 on my testserver with sed 4.2.2 and '-E' options works fine there.
```
> sed --version
sed (GNU sed) 4.2.2
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
```
> echo 'aaa' | sed -E 's/aaa/bbb/'
bbb
```

**Comment by drwetter** [comment]
Thx @ilya-il  ! 

(Thought SLES 11 would be based on opensuse 11.4 , but it looks it's even older)

SLES 11 has also openssl 0.9.8. Be very careful when using with this -- I can't recommend it at all. I would love to drop support for this. But a company in Cupertino is selling expensive computers with this ridiculous old version...

**Comment by dvv** [comment]
This is what I see is called:

```
...
sed -r s@/*:|([^\\]):@\1\n@g;H;x;s@/\n@\n@
sed -r s@/*:|([^\\]):@\1\n@g;H;x;s@/\n@\n@
sed -E s/^([Ll]inux|[dD]arwin) //
...
```

In fact `sed -E` === `sed -r` as `man sed` states.

Can we normalize the code to use `sed -r` everywhere?

TIA

**Comment by drwetter** [comment]
> Can we normalize the code to use sed -r everywhere

"everywhere" -> in the code or on every platform?

Off the top of my head I can't tell whether -r is supported under every flavor. The few lines which actually use sed regex can be written better in bash e.g.

**Comment by dcooper16** [comment]
I can't find the code @dvv is referencing, but the current code seems fine: use `-E` for most systems and `-r` on old systems that don't support `-E`. According to the link in the initial comment, http://www.gnu.org/software/sed/manual/sed.html, just using `-r` and hoping that it works everywhere would not be the best option:
> -E
> -r
> --regexp-extended
> 
>     Use extended regular expressions rather than basic regular expressions.
>     Extended regexps are those that egrep accepts; they can be clearer because
>     they usually have fewer backslashes. Historically this was a GNU extension,
>     but the -E extension has since been added to the POSIX standard
>     (http://austingroupbugs.net/view.php?id=528), so use -E for portability.
>     GNU sed has accepted -E as an undocumented option for years, and *BSD seds
>     have accepted -E for years as well, but scripts that use -E might not port to other
>     older systems.

**Comment by dvv** [comment]
```
sed -r s@/*:|([^\\]):@\1\n@g;H;x;s@/\n@\n@
sed -r s@/*:|([^\\]):@\1\n@g;H;x;s@/\n@\n@
sed -E s/^([Ll]inux|[dD]arwin) //
```

This list is from a sed wrapper I made on the target system to see where it fails.
So I just pointed out it is definitely called inconsistently.
