### ISSUE TITLE
Default cipher list

### ISSUE THREAD

**Issue by slayerulan** [drwetter/testssl.sh#1190]
Hello,
I've built openssl-1.0.2.bad to work with cURL.
Whats --ciphers values should i pass to accept SSLv2, SSLv3, ..well; anything.
--ciphers 'DEFAULT' enables all of those or do i need --ciphers 'ALL'?

Thanks

**Comment by drwetter** [comment]
Hi @slayerulan ,

we are using the weak openssl port just as a helper for testssl.sh.  Unfortunately this is the wrong place to ask here. Please head over to a curl related repo.

RTFM: You might want to consult the man page of curl before.

Cheers, Dirk
