### ISSUE TITLE
testSSL hangs with --file option and --openssl-timeout does not work

### ISSUE THREAD

**Issue by drshooter** [drwetter/testssl.sh#1208]
Hello, 
When running against an individual application which port is verified open, testSSL hangs unless the "--openssl-timeout" option is passed.  This is great, however I need to use the --file option and then this is used along with the "--openssl-timeout" testSSL only errors as shown in the below output.  Can you please assist.  Thank you.

1. version info
testssl.sh       2.9.5-7  

2. what exactly was happening, output is needed

STDOUT Error's:

`/testssl.sh/testssl.sh` --fast --quiet -p --wide -E -h -R -S --openssl-timeout 5 --jsonfile=/tmp/testssl.HXRYAG/jsonfile_child.json --warnings=batch `111.222.333.444:443`

cannot find specified ($OPENSSL=timeout --preserve-status 5 /testssl.sh/bin/openssl.Linux.x86_64) binary.
 Looking some place else ...

Fatal error: cannot exec or find any openssl binary

3. what did you expect instead?
Expected to be able to run testSSL with the "--file" option successfully  

4. steps to reproduce

   1. `testssl.sh` --fast --quiet -p --wide -E -h -R -S --openssl-timeout 5 --jsonfile my.json --file `testssl.feeder` 
 
    2. n/a

    3.  `on` ip-xxx-xxx-xxx-xxx:/usr/local/bin/openssl
         (built: "reproducible build, date unspecified", platform: `"linux-x86_64")`

      `/usr/local/bin/openssl` version
      OpenSSL `1.0.2k`    

    4. `Linux` ip-xxx-xxx-xxx-xxx 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 `GNU/Linux`

**Comment by drwetter** [comment]
Thanks for reporting, fixed.

Please note that 3.0. will soon be released -- it has also other bugs fixed which I am likely not fixing here.

**Comment by drshooter** [comment]
Thank you very much and for the timely response.
