### ISSUE TITLE
JSON File not created if file not existing with --append flag

### ISSUE THREAD

**Issue by Loris1123** [drwetter/testssl.sh#1210]
TestSSL Version: 3.0rc4
OpenSSL Version: OpenSSL 1.0.2-chacha (1.0.2k-dev)
Operating System: Arch Linux

**What is happening?**
The JSON File is not created, when specifying a json-file, which does not exist and using the --append flag. However, a CSV File is created in the same case.

**What should hapen?**
Create a new JSON File and write the JSON-Output to the file. Just like the CSV file.

**Steps to reproduce**

    testssl.sh --jsonfile=test_json --append example.com

Afterwards the file `test_json` does not exist. Howver, if you try the same with `--csvfile`, the file will be created.

**Comment by drwetter** [comment]
Thanks for reporting. Done
