### ISSUE TITLE
JSON output contains wrong syntax and is out of order

### ISSUE THREAD

**Issue by ivyheasty** [drwetter/testssl.sh#1226]
Please make sure that you provide enough information so that we understand what your issue is about.

1. The Error
The JSON output contains wrong syntax and in out of order.  
![Screen Shot 2019-04-02 at 11 18 21 AM](https://user-images.githubusercontent.com/21328135/55373995-97376e80-5539-11e9-89a6-949a5c0e4ac9.png)

2. what did you expect instead?
I'm expecting the `pre_128cipher` information is placed inside the **protocols/related type** clause.

**Comment by drwetter** [comment]
ACK, for pretty JSON it's invalid. Order is fine though

**Comment by drwetter** [comment]
see 0e88072 (pending as network doesn't allow port 22)
