### ISSUE TITLE
Switch for disabling color tags for logfile

### ISSUE THREAD

**Issue by noraj** [drwetter/testssl.sh#1229]
## Context

By default testssl is outputting to stdout with color tags. It is possible to disable that with `--color 0`.

## Actual behavior

`--log`, `--logging`, `--logfile` allow to save logs into a file **BUT** will use the same output as for stdout.

So you can:

- (by default) allow color output but you will have the color tags in your logfile
- disable color (so this will be ok for the logfile) but you won't have color for stdout

Example:

![image](https://user-images.githubusercontent.com/16578570/55492630-d1873580-5637-11e9-897f-1c3fa84c2752.png)

## Expected behavior

logfiles should most often be in plain text, without color tags independently from the stdout choice.

Having logfile with color tags can be convenient if you want it as a trace of the test you did and we able to replay it with color to quickly identify vulnerabilities later.

So a new options can be added `--log-color <0|1|2>` and setting 0 as default. (keeping 2 by default for stdout)

## Information (irrelevant here)

1. uname -r: `4.19.32-1-lts` (archlinux)
   
2. testssl version from the banner: 

```
$ testssl -b 2>/dev/null | head -5 | tail -1
    testssl       2.9.5-7 from https://testssl.sh/
```

4. openssl version used by testssl.sh:

```
$ testssl -b 2>/dev/null | head -15 | tail -1
 Using "OpenSSL 1.1.1b  26 Feb 2019" [~163 ciphers]
```

**Comment by drwetter** [comment]
Hi @noraj ,

I am afraid I have to disappoint you -- this is intended behavior. At the moment at least. 

You should see that as a screen dump. If you don't like this, there are ways post processing the log, like piping it though ``'s/\x1b\[[0-9;]*[a-zA-Z]//g'  `` (using ``perl -pe `` or ``sed ``)

**Comment by noraj** [comment]
@drwetter I guessed it was intended but don't see this issue as a bug report but a feature request for adding `--log-color <0|1|2>`. I quickly looked at the code and the feature won't take time for someone who master the code and bash.

**Comment by drwetter** [comment]
Okay. Changed subject.

**Comment by noraj** [comment]
I made a start here https://github.com/drwetter/testssl.sh/pull/1230

In the function where log are written there must already a check for color (`COLOR`) that just need to be change by a check for `LOG_COLOR`.

**Comment by dcooper16** [comment]
Hi Noraj,

Unfortunately, my guess is that implementing this feature would not be as easy as you believe. The relevant line for creating the log file is in the `prepare_logging()` function:
```
exec > >(tee -a -i "$LOGFILE")
```
where the manual page for `tee` describes it as:
> tee - read from standard input and write to standard output and files

So, testssl.sh is just using the single command to specify that everything that is printed to stdout should also be written to a file. This is very different from the creation of HTML output, where testssl.sh has separate code for printing to stdout and for writing to the HTML file.

Could you explain why you believe this feature is needed? Do you want to be able to develop code that parses the log file and the color codes make that more difficult? If the idea is to have a program process the output, wouldn't it be easier to have it process the CSV or JSON output? If you aren't trying to develop code to parse the output, why are the color codes a problem?

**Comment by drwetter** [comment]
David described that correctly. 

What is very difficult is in your WIP PR that we can't have a complete set of different colors.

What I thought looking into at some point of time was washing the log output _after_ creation. That means it would be possible to only remove, not to add any escape codes. And my word "after" insinuates that if it could be possible in the very end of a run -- which needs to be tested as ``$LOGFILE`` is still open. Or later when the testssl.sh process exists, the washer process is spawned. But that is probably not trivial either looking at mass testing as there a concurrent processes to get synced.

**Comment by noraj** [comment]
> Could you explain why you believe this feature is needed?

Every time I launch a testssl scan, I need to log the output (without tags) to be able to easily copy paste later and have a proof. If the logfile contains color tags I can't copy/paste.
But I still want to be able to get the stdout in color to quickly see the RED `VULNERABLE` for example. They are not easy to spot when this is pure test.

TL;DR : for each scan I need a colored stdout and a plain text logfile



> What I thought looking into at some point of time was washing the log output _after_ creation. That means it would be possible to only remove, not to add any escape codes. And my word "after" insinuates that if it could be possible in the very end of a run -- which needs to be tested as `$LOGFILE` is still open. Or later when the testssl.sh process exists, the washer process is spawned. But that is probably not trivial either looking at mass testing as there a concurrent processes to get synced.

You're right, it may be easier to code by duplicating the stdout to log file and then remove tags if asked for but this make execution time longer and logically writing something to remove it right after is weird.

Is that not possible to run the test without color and post-adding it (in live) for stdout and do not add it for the log file?

**Comment by drwetter** [comment]
> Every time I launch a testssl scan, I need to log the output (without tags) to be able to easily copy paste later and have a proof. If the logfile contains color tags I can't copy/paste.

You can cleanup manually the escape codes as suggested above. As much as testssl.sh tries to help the user pls keep in mind that it is one tool for one purpose and there are other tools specifically on a Linux system for other purposes.

> You're right, it may be easier to code by duplicating the stdout to log file and then remove tags if asked for but this make execution time longer and logically writing something to remove it right after is weird.

Additional execution time would be minimal on top. And it's not weird, it is the way I currently see.

> Is that not possible to run the test without color and post-adding it (in live) for stdout and do not add it for the log file?

Almost everything is possible, but now this is weird :-)

> But I still want to be able to get the stdout in color to quickly see the RED VULNERABLE for example. They are not easy to spot when this is pure test.

There's machine readable output as David suggested. ``jq`` is your friend for JSON or use ``testssl.sh --severity --json...``.

**Comment by drwetter** [comment]
Closing as you can do that manually if you want it. It's too much and we rather focus on the core functions
