### ISSUE TITLE
PostgreSQL Test Does't Work

### ISSUE THREAD

**Issue by Verequies** [drwetter/testssl.sh#1249]
Trying to test my PostgreSQL instance with testssl, and its failing to handshake. Testing with SSLyze works fine. 

Also maybe a suggestion is not already done, as far as I know PostgreSQL doesn't do OCSP Stapling, so maybe we skip the checks when running against PostgreSQL. The same can be said maybe for the other Start TLS protocols.

**Comment by drwetter** [comment]
> Trying to test my PostgreSQL instance with testssl, and its failing to handshake. Testing with SSLyze works fine.

Hmm, ok. Thanks for the feedback. @sdann : do you have a server handy to check?

 > Also maybe a suggestion is not already done, as far as I know PostgreSQL doesn't do OCSP Stapling, so maybe we skip the checks when running against PostgreSQL. The same can be said maybe for the other Start TLS protocols.

From the code perspective it's much effort to test this, also if the test will contain no result - or what do you get returned?

**Comment by drwetter** [comment]
@Verequies  Can you pass me the output of ``./testssl.sh --debug=4 -p -t postgres <URI>``?

**Comment by drwetter** [comment]
... and check also with ``--ssl-native``

**Comment by Verequies** [comment]
Sorry for the wait, I've now run those tests. Two against PostgreSQL ( one ssl-native, and the other normal ), and again against the main site.

[testssl-postgresql-ssl-native.log](https://github.com/drwetter/testssl.sh/files/3164250/testssl-postgresql-ssl-native.log)
[testssl-postgresql.log](https://github.com/drwetter/testssl.sh/files/3164251/testssl-postgresql.log)
[testssl-ssl-native.log](https://github.com/drwetter/testssl.sh/files/3164252/testssl-ssl-native.log)

I also noticed in the debug info that 'tr' wasn't found, however it is definitely in the system.

As for the check to see if OCSP Stapling is supported, maybe we can just do a check to see if testing against PostgreSQL (or any other that doesn't support it) and it we are, just write N/A for both parts instead?

**Comment by drwetter** [comment]
Thanks!

I think that doesn't work because it tries to send nullbytes via echo. Not sure that mysql will work without openssl as the "login request" isn't probably send either :-(

And the "missing tr" was a wrong debug statement. tr is there otherwise testssl.sh would have refused to start -- it checks the requirements before. tr is one of them.

**Comment by drwetter** [comment]
done, see  #1299
