### ISSUE TITLE
Is it time to warn for TLSv1.0 and 1.1

### ISSUE THREAD

**Issue by Night1** [drwetter/testssl.sh#1251]
Is it time to depreciate old TLS versions? 

Security is a critical part of any system, and in part this starts with supported protocols, 
Github has already removed support and PCI compliance also require removal of TLS1.0.
Chrome should also start warning / removing support soon too. 

My suggestions is that we edit 
 Line 4890 to 4895 From

```

         0)   outln "offered"
               fileout "$jsonID" "INFO" "offered"
               latest_supported="0301"
               latest_supported_string="TLSv1.0"
               add_tls_offered tls1 yes
               ;;     
```

To 

```
          0)   prln_svrty_medium "offered (Not ok. Consider removing support)"
               fileout "$jsonID" "MEDIUM" "offered"
               latest_supported="0301"
               latest_supported_string="tls1"
               add_tls_offered tls1 yes

```

and from 4965 to 4970

```
        0)   outln "offered"
               fileout "$jsonID" "INFO" "offered"
               latest_supported="0302"
               latest_supported_string="TLSv1.1"
               add_tls_offered tls1_1 yes
               ;;       
```

To 

```
          0)   prln_svrty_medium "offered (NOT ok. Consider removing support)"
               fileout "$jsonID" "MEDIUM" "offered"
               latest_supported="0302"
               latest_supported_string="tlsv1.1"
               add_tls_offered tls1_1 yes

```

If it is high medium of even critical  can be up for discussion however I think it is time warn for old protocols.  I have a fork ready to create a pull request. 
any comments?

**Comment by drwetter** [comment]
For 3.0 I am hesitating but still thinking. One point for it would be a change in recent (also German) government standard to deprecate TLS 1.0 and 1.1. NIST was ahead, right @dcooper16 ?

For 3.1dev: yes. RSA kx e.g. is another point.

**Comment by drwetter** [comment]
The risk label is important: Counter question: Why "medium"?

**Comment by Night1** [comment]
Lable is current set to Info, which turns on a none warning symbol if one is to display it red or with a notice that it is not ok to still be using old protocols it might entice more to upgrade..

I changed mine to post this our for TLS1.2 and 1.3

```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered (OK)
 TLS 1.1    not offered (OK)
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   h2, http/1.1 (advertised)
 ALPN/HTTP2 h2, http/1.1 (offered)

```

where as with support for TLS1.0 and 1.1 it will clearly state that is not ok in red text. 


```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered (not ok. Consider removing support)
 TLS 1.1    offered (not ok. Consider removing support) 
 TLS 1.2    not offered
 TLS 1.3    not offered
 NPN/SPDY   http/1.1 (advertised)
 ALPN/HTTP2 http/1.1 (offered)
```


Current head has this as output

```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    not offered
 TLS 1.2    not offered
 TLS 1.3    not offered
 NPN/SPDY   http/1.1 (advertised)
 ALPN/HTTP2 http/1.1 (offered)
```

Where offerd is posted with white text, this is not synonymous with a bad result. 
on that mather TLSv1.3 should be treated as TLSv1.2 and be recommended.

**Comment by drwetter** [comment]
Also there needs to be a distinction between HTTP and the other protcolis as browsers will deprecate < TLS 1.2 sooner or later.

**Comment by Night1** [comment]
Indeed, a little clean up in simulations  and ciphers is in order du toe depreciation from Chromium core and Microsoft move from Webkit to Chromium for Edge along with weighted ECDHE/ECDSA higher, I've played around with simple scoring and their I do weigh ECDSA higher and down for RSA el. 

IE11 should be the latest supported simulations as should Android 6/7, if one would set a limit like 5 years support natural clean up could be done on a continues  cycle such lower the technical dept.  

My goal is to have a cleaner and support higher implementations of higher level of encryption and tbh when we did migration away from sub TLSv1.2 at work we did not noticed any difference, not that the webpage would render on such old browsers anyways. 

 
I'm not sure when OpenSSL and  similar will start removing support from such old protocols, 

As we see with ssllabs they no longer support old browsers/devices++ not that it should be a goal to be aligned but a baseline which defines support cycles would be nice to have.

**Comment by drwetter** [comment]
> I'm not sure when OpenSSL and similar will start removing support from such old protocols,

Not anytime soon probably. Current LTS version is 1.1.1 which will be supported until ~9/2023. And using ``enable-ssl3`` I still can compile SSLv3.

**Comment by dcooper16** [comment]
> For 3.0 I am hesitating but still thinking. One point for it would be a change in recent (also German) government standard to deprecate TLS 1.0 and 1.1. NIST was ahead, right @dcooper16 ?

[SP 800-52 Rev. 1](https://doi.org/10.6028/NIST.SP.800-52r1) was published in April 2014, and it was still trying to get everyone to implement TLSv1.2. So, it required support for TLSv1.1 while also requiring servers to add support for TLSv1.2 by January 2015. TLSv1 was listed as shall not for government-only applications and may for citizen and business facing applications.

[SP 800-52 Rev. 2](https://csrc.nist.gov/CSRC/media/Publications/sp/800-52/rev-2/draft/documents/sp800-52r2-draft2.pdf), which we are working on finalizing, requires all clients and servers to support TLSv1.2 and encourages them to support TLSv1.3. Since it assumes that all government-owned clients support TLSv1.2, it says that servers supporting government-only applications should not support TLSv1.1 and shall not support TLSv1. For servers that support citizen and business facing applications "The use of TLS versions 1.1 and 1.0 is generally discouraged."

It leaves open the possibility of supporting TLSv1.1 and TLSv1.0 in cases where the benefits outweigh the risks. There are still some old clients out there that do not support TLSv1.2 (e.g., old Android smart phones). If one of these clients tries to connect to a site like https://www.weather.gov, is it better to prevent the connection or to allow the client to view weather information over a potentially insecure connection?

https://tools.ietf.org/html/draft-ietf-tls-oldversions-deprecate is currently in working group last call, and it goes a bit further than SP 800-52 Rev. 2. It says that TLSv1.1 and TLSv1.0 MUST NOT be used.

> on that mather TLSv1.3 should be treated as TLSv1.2 and be recommended.

Good point. My guess is that the rating for TLSv1.3 was set back when TLSv1.3 was still in draft, and it was never updated. I think we would only want to give a rating of "best" for servers that implement the final (RFC 8446) version of TLSv1.3. If a server only implements some draft version, then that should continue to be rated as neither good nor bad.

**Comment by Night1** [comment]
Well tbh, if a web browser supports TLS1.1 it will support 1.2,(few exception for some java builds/libs) so phasing out both is not a big loss, and a policy that there is where I work. Only support TLS1.2 and 1.3 with modern cipher after Mozilla (with small alteration to 4k keys and ocsp) 

Yes there are some legacy where TLS1.0/1.1 is needed but those are so far an in between and those who run those should spend some money to upgrade their system, end user equipment is  not that much of a concern enterprise level api gateways /proxy / was  and such are the real hurdal for TLS supports. 

Government of some .eu states are now facing out TLS1.0/1.1 and even replacing VPNs with TLSv1.3 on some levels. I belive that goverment should set an example and be the kick to stop supporting legacy. 

I left it open to what comment should be displayed on support for TLS1.0 and 1.1 and custom comment like, You should consider upgrading due to the large gap in risk assessment,however it is still not ok to still support legacy TLS.
 
As you say this all comes down to risk, and what risk are you willing to take from measurements I did prior to removing support for old TLS the figures where so small and ever decreasing that we decided that the benefits of no longer supporting old tls /browsers far outweighed the handfull of users who still used old browesers .

**Comment by drwetter** [comment]
testssl.sh is not about HTTP only. Yes, Government standards are deprecating TLS 1.0 and 1.1 as David and myself were indicating. Browsers will deprecate those protocols in ~2020. So there will be a change in testssl.sh too. It's just a matter of labeling and phrasing it appropriately. Atm I think _medium_ is too much of a good thing.

Devil's in the detail though: It's not the best configuration possible but there's not much risk leaving TLS < 1.2 _also_ enabled, as long as client and server agree on >= TLS 1.2, e.g. no downgrade attack possible, and the server picks the protocol. And from the technical standpoint it is not the protocol but the ciphers which are not available in TLS < 1.2 (AEAD), instead it's often AES + CBC only which has intrinsic problems. Fixing those problems seems a bit like a whack a mole game to me. OTOH AES+CBC ciphers are also available in TLS 1.2 though but not in TLS 1.3.

**Comment by drwetter** [comment]
@Night1 / all: you mind to give  the branch protocol_improvements (https://github.com/drwetter/testssl.sh/tree/protocol_improvements) a try?

(I must have squashed somehow the old commit 22ad490)

**Comment by bknowles** [comment]
So far as I can tell, this branch doesn't seem to be giving any warnings on TLS 1 and TLS 1.1, as requested above by @Night1 .

**Comment by bknowles** [comment]
I'm seeing:

```
 TLS 1      not offered
 TLS 1.1    not offered
```
And:
```
 TLS 1      offered
 TLS 1.1    offered
```
Which does not correspond to the deprecation that was requested by @Night1

**Comment by bknowles** [comment]
Please ignore my previous comments.  They were a result of operator error.  I think I was mistakenly on the 3.0 branch and not the protocol_improvements branch.

Tested against some of our internal hosts, I am now seeing:
```
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
```
And:
```
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
```
I'm still working on finding a good TLS 1.3 host to test against.

**Comment by Night1** [comment]
Great thank you, looking great and it helps to push people away from old an insecure protocols.

**Comment by sonawanesarvesh** [comment]
Hello,

Recently observed, 

1. TLS1_1 is marked as deprecated but with Severity as LOW - I guess we should mark it  as High now 
2. TLS 1_2 is marked as OK should be shifted to High as well if 1.3 is offered with final else to High

   ```
   {
              "id"           : "TLS1_1",
              "ip"           : "-------",
              "port"         : "443",
              "severity"     : "LOW",
              "finding"      : "offered (deprecated)"
          }


        {
              "id"           : "TLS1_2",
              "ip"           : "-------",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "offered"
          }
```

         {
              "id"           : "TLS1_3",
              "ip"           : "-------",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "offered with final"
          }

**Comment by drwetter** [comment]
If you want to argue about this, you would need to give a reason. So why would you mark this as high?

**Comment by Night1** [comment]
> If you want to ague about this, you would need to give a reason. So why would you mark this as high?

PCI now requires TLS1,0 and 1.1 to be disabled for compliance. NIST has also updated their services 
https://www.nist.gov/oism/tls-10-being-turned-wwwnistgov

Microsft have removed TLS 1.0 and 1.1 for their services in Azure etc

**Comment by drwetter** [comment]
I was asking for a technical reason (cryptography), not for a recommendation of standards. 

High is currently
* SSLv3 
* RC4 ciphers
* DES ciphers
* no trust in cert chain
* cert expired
* ...

So: no. 

I has to be in line with other ratings. And I recommend to read CVSS rating guides what a final score of critical, high etc. means, see https://nvd.nist.gov/vuln-metrics/cvss / https://www.first.org/cvss/v3.1/specification-document.

**Comment by teward** [comment]
Would IETF RFC 8996 be relevant here?

https://datatracker.ietf.org/doc/rfc8996/

It defines "MUST NOT USE" for both TLS 1.0 and 1.1 and explains some justifications for this statement within it

**Comment by drwetter** [comment]
Ok, thanks. 

As it says "MUST NOT", so there's a change in the wording needed as just 'deprecated' seems to weak. The justifications in there though are something which we're testing for. But I am still scratching my head why this should be labeled as HIGH. Maybe MEDIUM but I need to look in detail at it.

@dcooper16 ?

**Comment by teward** [comment]
I agree with MEDIUM given RFC8996, but I don't think HIGH should be considered.  SHA1 hashes though should be HIGH because it's a known vulnerable hash/sig algo now, but otherwise I agree with MEDIUM for TLS 1.0 and 1.1 warnings/justification (with a link in docs somewhere to 8996)

Unless we want to use Section 3's justifications for High, though I think this might warrant a Medium more than a High (personal opinion, but I'm not a decision maker here)

> 3.  SHA-1 Usage Problematic in TLS 1.0 and TLS 1.1
> 
>    The integrity of both TLS 1.0 and TLS 1.1 depends on a running SHA-1
>    hash of the exchanged messages.  This makes it possible to perform a
>    downgrade attack on the handshake by an attacker able to perform 2^77
>    operations, well below the acceptable modern security margin.
> 
>    Similarly, the authentication of the handshake depends on signatures
>    made using a SHA-1 hash or a concatenation of MD5 and SHA-1 hashes
>    that is not appreciably stronger than a SHA-1 hash, allowing the
>    attacker to impersonate a server when it is able to break the
>    severely weakened SHA-1 hash.
> 
>    Neither TLS 1.0 nor TLS 1.1 allows the peers to select a stronger
>    hash for signatures in the ServerKeyExchange or CertificateVerify
>    messages, making the only upgrade path the use of a newer protocol
>    version.

If we hold SHA-1 deprecation as MEDIUM then it makes sense to be at the same level there, however if SHA-1 deprecation was decided as HIGH then it makes sense as High.
