### ISSUE TITLE
[Feature Request] Show expiry of intermediate certs

### ISSUE THREAD

**Issue by CRCinAU** [drwetter/testssl.sh#1264]
With the latest mozilla gaff with signing certs, it shows that some people easily lose track of the expiry details of intermediate certificates.

Is it possible to show the expiry dates of intermediate certs in the provided chain as well as the certificate itself?

This would show in a nice, easy fashion critical details that are often overlooked - sometimes with major consequences.

**Comment by drwetter** [comment]
you're right. There should be and will be checks, see e.g. #1004 .

**Comment by drwetter** [comment]
fixed
