### ISSUE TITLE
Logfiles not available when running with docker :)

### ISSUE THREAD

**Issue by deknos** [drwetter/testssl.sh#1272]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a
   ubuntu 18.04 :)

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
your latest docker image :)

3. git log | head -1 (if running from git repo)
your latest docker image :)

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
your latest docker image :)

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
docker run -ti drwetter/testssl.sh --json --logfile /tmp/testsslfile.log --severity HIGH https://DOMAIN

6. what exactly was happening, output is needed
the logfile is written INTO the container and not on the host.

7. what did you expect instead?
a documentation tidbit, that i should mount a volume where i put the logfile :> i am used to docker but even i had to think for 10 minutes why there's no logfile in my HOME :D

**Comment by deknos** [comment]
And apparently both do not produce a json file:
 * docker run -v "/home/benutzer01/tmp:/data"  -ti drwetter/testssl.sh --json --logfile /data/testsslfile.log -oa /data/myjsonlog.txt --severity HIGH https://domain
* docker run -v "/home/benutzer01/tmp:/data"  -ti drwetter/testssl.sh --json -oa /data/myjsonlog.txt --severity HIGH https://domain

**Comment by drwetter** [comment]
-oa writes every logfile. There's no need to add --json --logfile or whatsoever. Please read the help.
I am deliberately also not checking for those things, thus it's unpredictable what happens.

Why do you run docker in the first place if you have a linux host?

**Comment by deknos** [comment]
i didn't see the documentation, i just looked at the --help parameters. I use linux, since containering helps contain not clutter the rest of my environment. but with docker -v "$(pwd):/certaindirectory and -oa /certaindirectory/foo it works :) 

Issue can be closed therefore :)

**Comment by drwetter** [comment]
I was actually referring to ``testssl.sh --help``. ;-)

Please not that the creator of an issue can also close the issue.
