### ISSUE TITLE
maketempf() assumes /tmp is writable 

### ISSUE THREAD

**Issue by danieldjewell** [drwetter/testssl.sh#1273]
Hello!

Although this is probably a minority of cases, running testssl.sh on a system that does not permit writing to /tmp (e.g. Termux on Android) causes the entire script to fail because the path /tmp is hardcoded and assumed to be writable:

https://github.com/drwetter/testssl.sh/blob/d6fb23215239cbe33847902589ac7f61a5739a95/testssl.sh#L16676-L16677

A simple fallback to trying to write to the current directory seems like an easy and workable solution? I can write it up and do a PR if you'd like.

**Comment by drwetter** [comment]
Hi @danieldjewell ,

sounds good, we could work on that. Just out of curiosity: Did you get testssl.sh to work on Android? I tried a (longer) while back and I didn't get anywhere fast enough. 

Cheers, Dirk

**Comment by drwetter** [comment]
Daniel: in the case I wasn't answering clear enough: yes, please go ahead if you want to submit a PR.

I am happy to do it as well otherwise.

**Comment by danieldjewell** [comment]
@drwetter Sounds good! I'll work on it!

Actually, no, the script does not run fully ... there are a few other issues on Termux that I'm going to look at ... the next one is quoted below. The error is that one can't write to /dev/stdout on Termux (not rooted)... I'm not sure if there are other things that are breaking it. 

The script *does* start running on Termux -- it detects OpenSSL, it starts some of the scans, and does output *some* results. (I'm not 100% sure but I don't believe the deb package of openssl-1.1.1b-3 from termux-packages enables all of the "old" ciphers for testing -- it seems it might not enable SSLv2/3 by default -- see: https://github.com/termux/termux-packages/blob/master/packages/openssl/build.sh for the build options... but that's not too terribly difficult to fix -- I've compiled openssl before directly inside Termux with additional options.)

That said, I'm not too sure if there are additional things that could break. I'll dig in and find out. I see a few ways to possibly address these issues:

* Write some kind of platform detection into the system and then modify the various things that would break on that platform (e.g. on Termux, $PREFIX and $HOME are set to /data/data/com.termux/files/usr and /data/data/com.termux/files/home, respectively) ... This would be good if there are mutliple platforms that need very custom settings to work (are there others?) ... obviously, this is also somewhat complex to maintain ... 
* Use more of a "test and fallback" approach - this should work for the /tmp issue, but I'm not sure about the /dev/stdout issue... This method could be good in that it might cover more "edge"/"fringe" cases automatically without having to write specific per-platform customizations (like Termux or other somewhat non-standard systems)
 
You know the code *far* better than I -- I'm not sure what the best approach is here.  

I hope my message doesn't sound too critical ... I do really appreciate the work you've done :grin: (Eine Frage... Ich habe bemerkt, dass Sie in Hamburg wohnen? Sind Sie Deutscher? In diesem Fall verzeihen Sie bitte meine amerikanische umständliche Antwort... :grin: ... Wenn Sie Deutscher sind, kann ich natürlich im "Direktmodus" schreiben/antworten -- Ich mag die deusche Direktheit (und die Direktheit der deutschsprachigen Länder) lieber :grin:)

MfG,

-Daniel 

https://github.com/drwetter/testssl.sh/blob/91e98f1fc3b22ba8451dd40b7655ca3edde12480/testssl.sh#L7569

**Comment by drwetter** [comment]
> The script does start running on Termux -- it detects OpenSSL, it starts some of the scans, and does output some results. (I'm not 100% sure but I don't believe the deb package of openssl-1.1.1b-3 from termux-packages enables all of the "old" ciphers for testing -- it seems it might not enable SSLv2/3 by default -- see: https://github.com/termux/termux-packages/blob/master/packages/openssl/build.sh for the build options... but that's not too terribly difficult to fix -- I've compiled openssl before directly inside Termux with additional options.)

That's a matter of fine tuning. For the most part, also an openssl 1.1.1 is fine as the critical things are done with network sockets. Actually David and myself were discussing whether we're should use openssl 1.1.1 in the future.

> Write some kind of platform detection into the system and then modify the various things that would break on that platform (e.g. on Termux, $PREFIX and $HOME are set to /data/data/com.termux/files/usr and /data/data/com.termux/files/home, respectively) ... This would be good if there are mutliple platforms that need very custom settings to work (are there others?) ... obviously, this is also somewhat complex to maintain ...

Platform detection is not good and I try to avoid it. Think about e.g. BSD's sed: I can't tell whether the user also has GNU's sed installed throw ports, similar to Mac OSX. So what testssl.sh does is testing whther a feature / capability exists and populate global vars for this.

> Use more of a "test and fallback" approach - this should work for the /tmp issue, but I'm not sure about the /dev/stdout issue... This method could be good in that it might cover more "edge"/"fringe" cases automatically without having to write specific per-platform customizations (like Termux or other somewhat non-standard systems)

Actually if there are more cases like with stdout it would be better to think about a global approach (see previous comment) instead of hundreds (exaggerating) of small PRs. Because at the moment I don't have a picture what breaks on termux and what's to come. I appreciate if testssl.sh works on more platforms but I would like also to have a good code quality. 

If you think it's more to come, you can also just get ~everything to work in your fork and when you think that a part of it is ready, then submit a PR.  This part can be a "resolving the tmpfile issue" or "resolving the stdout issue".   

> hope my message doesn't sound too critical ... I do really appreciate the work you've done (Eine Frage... Ich habe bemerkt, dass Sie in Hamburg wohnen? Sind Sie Deutscher?

Ja. But we should continue in English here as it's the common denominator.

> Ich mag die deusche Direktheit (und die Direktheit der deutschsprachigen Länder) lieber

Depends on where you are in the US or other English speaking countries. E.g. New York, especially the city, is not known for polite and indirect waffle. ;-)

**Comment by drwetter** [comment]
All replacement PRs merge. A check on your side whether that helped would be appreciated.

I am closing this but that shouldn't stop your feedback. Thanks!

**Comment by ahsodex** [comment]
I tested on termux today. It throws an error but works. Thanks!

```
$ termux-info
Packages CPU architecture: aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages: All packages up to date
Android version: 9
Kernel build information:
Linux localhost 4.9.112-16352588 #2 SMP PREEMPT Wed Nov 20 12:24:41 KST 2019 aarch64 Android
Device manufacturer: samsung
Device model: SM-N960U

$ ./testssl.sh testssl.sh:443
mktemp: failed to create directory via template ‘/tmp/testssl.XXXXXX’: No such file or directory

No engine or GOST support via engine with your /data/data/com.termux/files/usr/bin/openssl                      
###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (51ca429 2020-01-25 12:37:28 -- )
```

**Comment by drwetter** [comment]
I suppressed the error message now, see 4b573dd

**Comment by ahsodex** [comment]
Looks good. Thanks again!

```
$ ./testssl.sh testssl.sh:443

No engine or GOST support via engine with your /data/data/com.termux/files/usr/bin/openssl

###########################################################
testssl.sh  3.1dev from https://testssl.sh/dev/ (c3bab98 2020-01-26 01:30:58 -- )
```

**Comment by drwetter** [comment]
That's cool! 

Does that work completely now or are there more problems?

**Comment by ahsodex** [comment]
It works great!
