### ISSUE TITLE
Dont show  certificate smtp-starttls 

### ISSUE THREAD

**Issue by suffixbabai** [drwetter/testssl.sh#1280]
1. uname -a

4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2

testssl.sh       3.0rc5 from https://testssl.sh/dev/

3. git log | head -1 (if running from git repo)

Not from git

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'

Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]
 on s0565b4ce:./bin/openssl.Linux.x86_64
 (built: "Jan 18 17:12:17 2019", platform: "linux-x86_64")

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host

testssl.sh -t smtp mail.babai.ru:25

6. what exactly was happening, output is needed

show self-signed certificate 

7. what did you expect instead?

openssl, sslyze, immuniweb.com/SSL show good thawte certificate.

**Comment by drwetter** [comment]
> 5.    steps to reproduce: testssl.sh or docker command line, if possible incl. host

testssl.sh -t smtp mail.babai.ru:25

That didn't work for me as very early I was blocked. Tried two IPs.

**Comment by suffixbabai** [comment]
Oh, yes - it's my paranoic.

Please write your ip I will bring them in exceptions

**Comment by drwetter** [comment]
dig +short testssl.sh

**Comment by suffixbabai** [comment]
> dig +short testssl.sh

Added. Check please

**Comment by suffixbabai** [comment]
I apologize, you managed to pass completely a test your program? does not block your IP address any more?

**Comment by drwetter** [comment]
Hi @suffixbabai ,

nope, didn't get to it yesterday at all. Bear w me.

Dirk

**Comment by drwetter** [comment]
sorry, I meant looking at the issue. Blocking is no longer there, thanks!

**Comment by drwetter** [comment]
It's related to #316 :

```
prompt> openssl s_client -starttls smtp -connect mail.babai.ru:25  </dev/null 2>/dev/null | awk '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/'  | openssl x509 -text -noout | grep -A7 'Serial Number'
        Serial Number:
            dd:a5:68:63:7a:66:af:1e
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = XX, ST = XX, L = XX, O = XX, OU = XX, CN = localhost, emailAddress = root@localhost
        Validity
            Not Before: May 18 13:17:36 2016 GMT
            Not After : May 16 13:17:36 2026 GMT
        Subject: C = XX, ST = XX, L = XX, O = XX, OU = XX, CN = localhost, emailAddress = root@localhost
prompt> openssl s_client -starttls smtp -connect mail.babai.ru:25  -servername mail.babai.ru </dev/null 2>/dev/null | awk '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/'  | openssl x509 -text -noout | grep -A7 'Serial Number'
       Serial Number:
            05:9d:fc:97:95:95:f1:8d:de:24:ed:fc:aa:f1:35:24
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Thawte RSA CA 2018
        Validity
            Not Before: May 23 00:00:00 2019 GMT
            Not After : Jun 21 12:00:00 2021 GMT
        Subject: CN = mail.babai.ru
```

**Comment by drwetter** [comment]
See PR. Thanks for the reminder. That was actually a long forgotten issue.
