### ISSUE TITLE
import the result in DefectDojo

### ISSUE THREAD

**Issue by NRGLine4Sec** [drwetter/testssl.sh#1284]
What is the better argument or the combinaison of argument to create a report file which can be imported in [DefectDojo](https://github.com/DefectDojo/django-DefectDojo).
I have create an issue in DefectDojo to add the ability to import the result of a scan with testssl (https://github.com/DefectDojo/django-DefectDojo/issues/1061) but, maybe you can help us to add testssl to DefectDojo.

**Comment by drwetter** [comment]
aha? That is ages ago.

testssl.sh exports a variety of standard output formats, see help.

**Comment by NRGLine4Sec** [comment]
Yes, If you take a look at the issue in DefectDojo, I already use aha. But there is also some output format of testssl and I would like to know what is the best of these output to define more easily a vulnerability in the result of testssl. I would like to extract vulnerability in the result of testssl and import these to DefectDojo.

**Comment by drwetter** [comment]
Sorry, @NRGLine4Sec. The minimum requirement before posting is to read the builtin help and consult the documentation also.
