### ISSUE TITLE
No way to prevent doing 'client simulation'

### ISSUE THREAD

**Issue by nrathaus** [drwetter/testssl.sh#1287]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a
   3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
    testssl.sh       3.0rc4 from https://testssl.sh/dev/
    (053a226 2019-03-06 19:48:21 -- )

3. git log | head -1 (if running from git repo)

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
./bin/openssl.Linux.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
There is no way to disable the variable 'do_client_simulation', while its by default set to 'false', it set by 'set_scanning_defaults' to true with no directive to disable it (set it to 'false')

6. what exactly was happening, output is needed

7. what did you expect instead?
Have some sort of directive like '--client-simulation=false' to prevent it from being run

8. Concept fix?
```
diff --git a/testssl.sh b/testssl.sh
index bfdeda6..154a7ae 100755
--- a/testssl.sh
+++ b/testssl.sh
@@ -18524,8 +18524,14 @@ parse_cmd_line() {
                -h|--header|--headers)
                     do_header=true
                     ;;
-               -c|--client-simulation)
-                    do_client_simulation=true
+               -c|--client-simulation=*)
+                    do_client_simulation=$(parse_opt_equal_sign "$1" "$2")
+                    [[ $? -eq 0 ]] && shift
+                    case "$do_client_simulation" in
+                         true|false) ;;
+                         *) tmln_magenta "\nclient-simulation can be either \"true\", or \"false\""
+                              help 1
+                    esac
                     ;;

```

**Comment by nrathaus** [comment]
Better patch (which actually works :D)
```
diff --git a/testssl.sh b/testssl.sh
index bfdeda6..5a2aeb2 100755
--- a/testssl.sh
+++ b/testssl.sh
@@ -18339,7 +18339,7 @@ set_scanning_defaults() {
      do_server_defaults=true
      do_server_preference=true
      do_tls_fallback_scsv=true
-     do_client_simulation=true
+     # do_client_simulation=true
      if "$OFFENSIVE"; then
           VULN_COUNT=16
      else
@@ -18524,8 +18524,14 @@ parse_cmd_line() {
                -h|--header|--headers)
                     do_header=true
                     ;;
-               -c|--client-simulation)
-                    do_client_simulation=true
+               -c|--client-simulation=*)
+                    do_client_simulation=$(parse_opt_equal_sign "$1" "$2")
+                    [[ $? -eq 0 ]] && shift
+                    case "$do_client_simulation" in
+                         true|false) ;;
+                         *) tmln_magenta "\nclient-simulation can be either \"true\", or \"false\""
+                              help 1
+                    esac
                     ;;
                -U|--vulnerable)
                     do_vulnerabilities=true
```

**Comment by dcooper16** [comment]
Hi @nrathaus,

If you don't want to run all of the "standard" tests, then the solution is to list the tests that you do want to run. For example, to perform all of the tests except client simulation that would run without specifying command-line options, the following would work:
```
testssl.sh -p -s -f -P -S -h -U -e <URI>
```
The patch that you suggested would not work as you seem to believe. It would just remove client simulation from the list of tests that are run by default.

**Comment by nrathaus** [comment]
Ok

I guess that is a way to do it, though I am interested in all the default settings and only exclude one of them, so it would seem logical that I had the ability to selectively disable just that one.
