### ISSUE TITLE
Request: include ARM prebuilt openssl binaries

### ISSUE THREAD

**Issue by f-s** [drwetter/testssl.sh#129]
Would be great: Most ARM openssl are ancient. Thanks!!

**Comment by teward** [comment]
Tricky to achieve unless you've got an ARM device lying around.

And for Ubuntu, it will take a ***long time*** to compile even one of those binaries.  Trust me on that, it takes a long long time even on an RPi 2.

**Comment by drwetter** [comment]
One can always use a cross compiler. For Opensuse and Trusty Tahr toolchains seems to be in the standard repositories.

Still then: There are at least two ARM architectures...

**Comment by teward** [comment]
Of which Ubuntu where I think the binaries were made will only support one - armhf for the v7 architecture.  Older ones need Debian armel, the last time I checked.

**Comment by teward** [comment]
Note that I have two RPis coming in in a couple weeks, I could dedicate one of those to build the binaries (a long long time though to complete), but again we run into SupportedArchitectures - armel is dead by Ubuntu, and armhf is for ARMv7 and not earlier.

**Comment by drwetter** [comment]
Cross compiler rules! 

There's also the thing to get this done by OBS ("open build services") which seems to have some ARM support -- but there my knowledge comes to a halt

**Comment by f-s** [comment]
I did compile it on Arm from GIT (odroid C1), simple and ~4min. Thanks

**Comment by PeterMosmans** [comment]
For what's it worth, I would highly recommend using the openssl 1.0.2-chacha fork (more ciphers included). Note that I'm slightly biased here... ;)
https://github.com/PeterMosmans/openssl

**Comment by drwetter** [comment]
@f-s : Totally agree to @PeterMosmans. 

And adding though:  If you want to test security of SSL/TLS stacks you shouldn't use something which has the broken stuff disabled  In the standard openssl git repo are at least FREAK+ LOGJAM related ciphers disabled and some 40/64 bit ciphers.

Per policy I warn at least if a test cannot be done or not be done sufficiently but momentarily that doesn't help you to test those features.

**Comment by f-s** [comment]
The https://github.com/PeterMosmans/openssl wont compile on ARM:

https://github.com/PeterMosmans/openssl/issues/24

**Comment by drwetter** [comment]
see 7dce6d18881cad066bfc3c57fa2b39c38f408ac0. Thx
