### ISSUE TITLE
Time to deprecate CBC algorithms?

### ISSUE THREAD

**Issue by bknowles** [drwetter/testssl.sh#1298]
Folks,

Thanks to the article at <https://news.ycombinator.com/item?id=20284883>, I just found out about the fact Qualys SSL Labs will be deprecating the CBC algorithms, supposedly starting in April of 2019 (see <https://blog.qualys.com/technology/2019/04/22/zombie-poodle-and-goldendoodle-vulnerabilities>).

Is it time for testssl.sh to do the same?

I searched for what appear to be relevant issues that had previously been opened on this subject, and didn't find anything obvious.  If I've missed something, please let me know.  Thanks!

**Comment by drwetter** [comment]
At a certain point it'll be labeled accordingly, yes. (I prefer not to use the word deprecate here as testssl.sh is not e.g. a RFC).

Some of the predecessors of newer problems with CBC ciphers are labeling those ciphers already. But this is not the right place, probably it'll be a test in standard ciphers.

**Comment by drwetter** [comment]
I'll mark this for 3.0 to be considered at least

**Comment by drwetter** [comment]
See  #1363  . I know it might be less than you anticipated but other than that I'd need either to mark every cipher as deprecated which in a standard run I don't want atm (but --color=3 shows you). Or I need to test the four newer POODLE vulnerabilities which for 3.0 is not going to happen.
