### ISSUE TITLE
Wrong signature algorithm reported in case of multiple certificates

### ISSUE THREAD

**Issue by jensguballa** [drwetter/testssl.sh#1310]
I am using testssl.sh against a server which is configured with an ECDSA- as well as an RSA-certificate. In the output two certs are displayed, but it looks like for the RSA-cert the signature algorithm is not correct (cert `#1`):

    Server Certificate #1
    Signature Algorithm          ECDSA with SHA256
    Server key size              RSA 3072 bits
    ....
    Server Certificate #2
    Signature Algorithm          ECDSA with SHA256
    Server key size              EC 256 bits

testssl.sh version: 3.0rc5 from https://testssl.sh/dev/

openssl version: OpenSSL 1.0.2-chacha (1.0.2k-dev)

Using JSON output reveals the same issue.

**Comment by drwetter** [comment]
> but it looks like for the RSA-cert the signature algorithm is not correct

By the sparse input you provided I can't tell whether it's correct or not.

**Comment by jensguballa** [comment]
Hm, I was confused by the fact that an RSA key is signed with ECDSA, but this is exactly how the server certificate of my test setup looks like. I double checked the certificate and the result testssl.sh provides, everything looks fine. Therefore this issue can be closed as it was based on my misapprehension.
