### ISSUE TITLE
When stable 3.0 version?

### ISSUE THREAD

**Issue by guettli** [drwetter/testssl.sh#1314]
According to this page: https://testssl.sh/ this is the latest version:

> Apr 25,2019: Version 3.0 Release Candidate 5 of has been made public, see 3.0rc5 @ github 

When will be the (non RC) release of version 3.0?

**Comment by drwetter** [comment]
Hi @guettli ,

it is ready when it's ready (Debian analogy). For what is missing, please see https://github.com/drwetter/testssl.sh/milestone/4 .

It is stable already but the last finishing polish need to be applied.

Cheers, Dirk
