### ISSUE TITLE
ATTENTION: No cipher mapping file found! What to do now?

### ISSUE THREAD

**Issue by guettli** [drwetter/testssl.sh#1315]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a: `Linux aptguettler 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux'
   
2. testssl version from the banner: 
`===> testssl.sh -b 2>/dev/null | head -4 | tail -2
Please note from 2.9 on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.
`

6. what exactly was happening, output is needed

```
./testssl.sh https://my-intranet-host

ATTENTION: No cipher mapping file found!
Please note from 2.9 on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.

Type "yes" to ignore this warning and proceed at your own risk --> ^C
```

7. what did you expect instead?

I expected some guidance. What can I do to solve this? How to obtain a cipher mapping file?

Please provide a luser compatible error message.

**Comment by drwetter** [comment]
Hi @guettli,

>  I expected some guidance. What can I do to solve this? How to obtain a cipher mapping file?

don't know how you got there but it is an installation problem. For installation see e.g. https://github.com/drwetter/testssl.sh#user-content-installation. When you just search this repo for ``cipher-mapping`` you'll find it. Also please RTFM ;-) , section ``FILES``.

Cheers, Dirk

**Comment by guettli** [comment]
I came from here:

https://testssl.sh/

> Download shortcuts
> Note the following features are supported by the webserver configuration:
> 
>     curl -L https://testssl.sh or  wget -O - https://testssl.sh pulls the current stable code from here
>     curl -L https://testssl.sh/dev/ or  wget -O - https://testssl.sh/dev/ pulls the current development code from github
> 
> – each to standard output. Please note however that for 2.9dev you need the mandatory files in etc/ though.
> 

Please provide a link from above page to the github README (if you want newcomers to understand it soon).

**Comment by drwetter** [comment]
> Please provide a link from above page to the github README (if you want newcomers to understand it soon)

hmm.. I thought the part ``you need the mandatory files in etc/ though.``. I added a link, hoping it helps.

When releasing 3.0 the web site will be changed anyway and probably I'll remove the **Download shortcuts** section

Thanks for the hint.

**Comment by Spongman** [comment]
it might help if the installation instructions were front-and-center and clearly listed. it's a pipe-dream expecting your users to read through a wall of text just in order to get it installed correctly.

btw: i came from here: https://testssl.sh/

**Comment by rvalitov** [comment]
I also came from https://testssl.sh/ in 2025 and following the instructions there I downloaded the single file and got this error. Thank you for posting this issue, as Google indexed it and helps to resolve this. I hope the website will be updated one day 🥰
