### ISSUE TITLE
incorrect domain resolution with IDN

### ISSUE THREAD

**Issue by bjmgeek** [drwetter/testssl.sh#1319]
1. uname -a
   Linux xxxx 5.1.12 #1 SMP Thu Jun 20 08:36:36 EDT 2019 x86_64 GNU/Linux

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
    testssl.sh       3.0rc5 from https://testssl.sh/dev/
    (3e4cd58 2019-09-13 10:56:15 -- )

3. git log | head -1 (if running from git repo)
commit 3e4cd58f7b4918bab1ce2be6ee48963113040606

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
$PWD/bin/openssl.Linux.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
testssl.sh ☮️.com

6. what exactly was happening, output is needed
Fatal error: No IPv4/IPv6 address(es) for "☮️.com" available

7. what did you expect instead?
testssl.sh should run and test the server.  It should resolve the domain name as xn--v4h.com

**Comment by drwetter** [comment]
thanks

**Comment by teward** [comment]
Note the specified URL/IDN **is not valid** for a URL.  This is confirmed by dig, etc.

**Comment by bjmgeek** [comment]
> Note the specified URL/IDN is not valid for a URL. This is confirmed by dig, etc.

And yet, it works in Firefox and Chrome, as well as curl:
````
 curl -v http://xn--v4h.com
* Uses proxy env variable no_proxy == 'localhost,127.0.0.0/8,::1'
*   Trying 54.36.56.87:80...
* TCP_NODELAY set
* Connected to xn--v4h.com (54.36.56.87) port 80 (#0)
> GET / HTTP/1.1
> Host: xn--v4h.com
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Cache-Control: public, must-revalidate, proxy-revalidate, max-age=3600
< Location: https://www.geniusofpeace.org/
< Content-type: text/html; charset=UTF-8
< Content-Length: 0
< Date: Wed, 18 Sep 2019 20:21:52 GMT
< X-IPLB-Instance: 16677
< 
* Connection #0 to host xn--v4h.com left intact
````

**Comment by teward** [comment]
@bjmgeek Track #1321 for further investigation and details.
