### ISSUE TITLE
fails to detect http service on port 443 when using IDN

### ISSUE THREAD

**Issue by bjmgeek** [drwetter/testssl.sh#1320]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a
   Linux xxxxxx 5.1.12 #1 SMP Thu Jun 20 08:36:36 EDT 2019 x86_64 GNU/Linux

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
    testssl.sh       3.0rc5 from https://testssl.sh/dev/
    (3e4cd58 2019-09-13 10:56:15 -- )

3. git log | head -1 (if running from git repo)
  3e4cd58f7b4918bab1ce2be6ee48963113040606

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
  $PWD/bin/openssl.Linux.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
  testssl.sh --ip 23.236.62.147 ♨️.com

6. what exactly was happening, output is needed
Nothing happened for a while, then  
````
 Start 2019-09-17 16:37:06        -->> 23.236.62.147:443 (♨️.com) <<--

 A record via:           supplied IP "23.236.62.147"
 rDNS (23.236.62.147):   147.62.236.23.bc.googleusercontent.com.

23.236.62.147:443 doesn't seem to be a TLS/SSL enabled server
 The results might look ok but they could be nonsense. Really proceed ? ("yes" to continue) --> 
````

7. what did you expect instead?
Using the punycode name, (which still needs the ip address, see #1319 ), the correct http detection occurs.

````
 Start 2019-09-17 16:33:32        -->> 23.236.62.147:443 (xn--j6h.com) <<--

 A record via:           supplied IP "23.236.62.147"
 rDNS (23.236.62.147):   147.62.236.23.bc.googleusercontent.com.
 Service detected:       HTTP

````

**Comment by drwetter** [comment]
That should work too now.
