### ISSUE TITLE
Can't use both "file" and "--ip one" - "Fatal error: couldn't identify supplied "CMDLINE_IP" "

### ISSUE THREAD

**Issue by user23498723452** [drwetter/testssl.sh#1328]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a

   Linux 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2

3.0rc3

3. git log | head -1 (if running from git repo)

n/a

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'

"OpenSSL 1.1.1  11 Sep 2018" [~164 ciphers]

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host

./testssl.sh --json --quiet --ip one --file dnsNames-to-scan.txt

6. what exactly was happening, output is needed

Fatal error: couldn't identify supplied "CMDLINE_IP"

7. what did you expect instead?

Script to run and limit each "host check" to a single IP scan. (so 1 IP scanned per line in the file)

**Comment by drwetter** [comment]
Hi @user23498723452 ,

can't reproduce it e.g. with google.com + testssl.net. 

First thing I would recommend is to update your testssl.sh to the latest & greatest. Then: could you please try with google.com + testssl.net?

Cheers, Dirk

**Comment by randomstability** [comment]
well, the script doesn't even appear to run on one of my systems (WSL Ubuntu 18).  

This is just from running it without options.

```
./testssl.sh: line 5: $'\r': command not found
./testssl.sh: line 67: $'\r': command not found
./testssl.sh: line 68: $'\r': command not found
./testssl.sh: line 85: $'\r': command not found
./testssl.sh: line 86: $'\r': command not found
./testssl.sh: line 91: $'\r': command not found
./testssl.sh: line 430: syntax error near unexpected token `$'{\r''
'/testssl.sh: line 430: `set_severity_level() {
```

**Comment by randomstability** [comment]
Yeah,  all but confirmed the file encoding is the issue.  Could you please support more than native unix formats?  It will be a bit hard to police this and seems a bit too strict.

**Comment by dcooper16** [comment]
Hi @randomstability ,

Thanks to your comment I was able to reproduce the original error (and your inability to run the script on WSL).

If running on a Unix system, create dnsNames-to-scan.txt with the list of servers to test and then run
```
unix2dos dnsNames-to-scan.txt
./testssl.sh --json --quiet --ip one --file dnsNames-to-scan.txt
```
Similarly, running
```
unix2dos testssl.sh
./testssl.sh
```
results in
```
testssl.sh: line 5: $'\r': command not found
testssl.sh: line 67: $'\r': command not found
testssl.sh: line 68: $'\r': command not found
testssl.sh: line 85: $'\r': command not found
testssl.sh: line 86: $'\r': command not found
testssl.sh: line 91: $'\r': command not found
testssl.sh: line 435: syntax error near unexpected token `$'{\r''
'estssl.sh: line 435: `set_severity_level() {
```
My guess would be that even when running on WSL, bash can only handle Unix line endings (\n) and that it gets confused by DOS/Windows line breaks (\r\n).

This is really a Bash issue, not a result of a decision for testssl.sh to only support Unix formats. There may be a workaround, but I'm not sure at the moment what is the best way to do this.

**Comment by randomstability** [comment]
This is what occurs for the Windows formatted input file.

```
user@PC:/mnt/c/Users/user/Documents/storage/testssl$ ./testssl.sh --json --quiet --ip one --file dnsNames-to-scan.txt

No engine or GOST support via engine with your /usr/bin/openssl

====== Running in file batch mode with file="dnsNames-to-scan.txt" ======

============================================================
./testssl.sh --json --quiet --ip one --warnings=batch www.google.com

No engine or GOST support via engine with your /usr/bin/openssl

Fatal error: couldn't identify supplied "CMDLINE_IP"

============================================================
./testssl.sh --json --quiet --ip one --warnings=batch testssl.net

No engine or GOST support via engine with your /usr/bin/openssl

Fatal error: couldn't identify supplied "CMDLINE_IP"
```

**Comment by drwetter** [comment]
@user23498723452 : we assume it the windows input format was also your problem. That has been fixed. If not, please speak up and give us more details. I'll reopen the issue then.

**Comment by randomstability** [comment]
I have confirmed this fixed the issue with the input file.  Thanks!
