### ISSUE TITLE
Inconsistencies with Android 8.1 client simulation

### ISSUE THREAD

**Issue by dilyanpalauzov** [drwetter/testssl.sh#1333]
`./testssl.sh autoconfig.aegee.org` prints:
```
 Running client simulations (HTTP) via sockets 
 Android 8.1 (native)         TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 253 bit ECDH (X25519)
```

but https://www.ssllabs.com/ssltest/analyze.html?d=autoconfig.aegee.org reports:
```
Handshake Simulation

Android 8.1 | - | TLS 1.3 | TLS_AES_256_GCM_SHA384   ECDH x25519  FS
-- | -- | -- | --
```

**Comment by drwetter** [comment]
Hi,

SSLlabs uses normally (for some reason) the chrome browser. I used the OS and not a browser. 

Cheers, Dirk

**Comment by dilyanpalauzov** [comment]
I asked also at https://github.com/ssllabs/ssllabs-scan/issues/749

**Comment by drwetter** [comment]
TLS 1.3. might have been added with an update though. It wasn't there in ~February(?) when I took this sample and the device was still alive.

 If somebody has a recently patched device or a stronger Google-Fu, let me know.

**Comment by dilyanpalauzov** [comment]
According to https://developer.android.com/about/versions/10/features#tls-1.3 TLS 1.3 was added to Android 10.

**Comment by drwetter** [comment]
I was about the post that too. But actually a stock Android 9 here had TLS 1.3 when it upgraded was from 8.1.

**Comment by drwetter** [comment]
housekeeping
