### ISSUE TITLE
SSLv3 check fail 

### ISSUE THREAD

**Issue by uwe-schwarz** [drwetter/testssl.sh#1353]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a
Linux app 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
testssl.sh       3.0rc5 from https://testssl.sh/dev/

3. git log | head -1 (if running from git repo)
commit f5c3b4e41da3ded6431b9e3562e2d53f57932346

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
./bin/openssl.Linux.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
testssl.sh sip.dvag.com

6. what exactly was happening, output is needed
```
 Testing protocols via sockets except NPN+ALPN

 SSLv2      not offered (OK)
 SSLv3      ^C
```
It just hangs when testing for SSLv3 (I waited a few hours, because this hang when running over night). It is working with --ssl-native.

7. what did you expect instead?
Not hanging, passing the test.

**Comment by drwetter** [comment]
Can reproduce it, thanks.

```
SSLv3      
sending client hello... sending client hello... 
"\x16\x03\x00\x00\xcb\x01\x00\x00\xc7\x03\x00\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0b\x85\x03\x90\x9f\x77\x04\x33\xd4\xde\x00\x00\xa0\xc0\x14\xc0\x0a\xc0\x22\xc0\x21\xc0\x20\x00\x39\x00\x38\x00\x37\x00\x36\x00\x88\x00\x87\x00\x86\x00\x85\xc0\x0f\xc0\x05\x00\x35\x00\x84\xc0\x13\xc0\x09\xc0\x1f\xc0\x1e\xc0\x1d\x00\x33\x00\x32\x00\x80\x00\x81\x00\x82\x00\x83\x00\x31\x00\x30\x00\x9a\x00\x99\x00\x98\x00\x97\x00\x45\x00\x44\x00\x43\x00\x42\xc0\x0e\xc0\x04\x00\x2f\x00\x96\x00\x41\x00\x07\xc0\x11\xc0\x07\x00\x66\xc0\x0c\xc0\x02\x00\x05\x00\x04\xc0\x12\xc0\x08\xc0\x1c\xc0\x1b\xc0\x1a\x00\x16\x00\x13\x00\x10\x00\x0d\xc0\x0d\xc0\x03\x00\x0a\x00\x63\x00\x15\x00\x12\x00\x0f\x00\x0c\x00\x62\x00\x09\x00\x65\x00\x64\x00\x14\x00\x11\x00\x0e\x00\x0b\x00\x08\x00\x06\x00\x03\x00\xff\x01\x00"
reading server hello...
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001560

TLS message fragments:
     protocol (rec. layer):  0x0000
     tls_content_type:       0x00
     msg_len:                0
```

Don't know yet why the server returns null bytes. testssl.sh keeps on reading and then it stops. 

And a minor thing: the server banner is there twice. Need to make #1351 more robust.

**Comment by drwetter** [comment]
Hi @uwe-schwarz ,

thanks for the bug report. David fixed it (see #1356) in a sense that it doesn't hang anymore. Not sure yet why it doesn't like the socket's client hello.

**Comment by dcooper16** [comment]
With #1356 and #1357 testssl.sh doesn't hang anymore, but there is still a remaining issue. The output for `run_protocols()` is now:
```
 SSLv2      not offered (OK)
 SSLv3      Fixme: unexpected value around line 5028, rerun w DEBUG>=2 or --ssl-native
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered
```
`tls_sockets()` is sending back a return value of 8 to indicate that the response was malformed, but `run_protocols()` expects a return value of 0, 1, 2, 3, 4, 5, or 7. So, `run_protocols()` should be modified to handle a return value of 8 from `tls_sockets()`.

**Comment by drwetter** [comment]
Yes, but the reason is that either openssl sends a more compliant (from the server's view) ClientHello, we send something which the server is not fine with or our parser for the ServerHello has a flaw.

My guess is the first.

**Comment by uwe-schwarz** [comment]
It's a load balancer from https://kemptechnologies.com/. If it helps I can get some more info like which model exactly, configuration, etc. But my guess would also be a difference between openssl and testssl.sh.

**Comment by dcooper16** [comment]
> Yes, but the reason is that either openssl sends a more compliant (from the server's view) ClientHello, we send something which the server is not fine with or our parser for the ServerHello has a flaw.

As noted in #1356, I am not seeing a difference between `tls_sockets()` and openssl. In both cases the server responds to the SSLv3 ClientHello with a bunch of null bytes.

The only "difference" I am seeing is that OpenSSL 1.0.2-chacha responds to these null bytes with a handshake_failure alert, whereas `tls_sockets()` does not send a failure alert to the server. (OpenSSL 1.1.1d, configured to support SSLv3, doesn't seem to send an alert either.)

I just tried sending an SSLv2 ClientHello to sip.dvag.com with both `sslv2_sockets()` and `openssl s_client`. In both cases the server responded with just a bunch of null bytes.

So, I don't think this is a difference between openssl and testssl.sh. It just seems that the server responds to SSLv2 and SSLv3 ClientHello messages with garbage, but it properly handles TLS 1, TLS 1.1, TLS 1.2, and TLS 1.3 ClientHello messages.
