### ISSUE TITLE
Nmap gnmap file issue

### ISSUE THREAD

**Issue by gbiagomba** [drwetter/testssl.sh#1361]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a
```
Linux kali 5.2.0-kali3-amd64 #1 SMP Debian 5.2.17-1kali2 (2019-10-17) x86_64 GNU/Linux
```   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
```
testssl -b 2>/dev/null | head -10 | tail -6
    testssl       2.9.5-7 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!
```
3. git log | head -1 (if running from git repo)
N/A
4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
```
 Using "OpenSSL 1.1.1d  10 Sep 2019" [~162 ciphers]
```
5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
```
testssl --assume-http --csv --file 2019/10-28/Nmap/Example-2019Q4-nmap_portknock.gnmap --html --json-pretty --log --parallel --sneaky
```
6. what exactly was happening, output is needed
```
No engine or GOST support via engine with your /usr/bin/openssl
/usr/bin/testssl: line 797: : No such file or directory
/usr/bin/testssl: line 803: : No such file or directory

###########################################################
    testssl       2.9.5-7 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1d  10 Sep 2019" [~162 ciphers]
 on kali:/usr/bin/openssl
 (built: "Oct 12 19:37:55 2019", platform: "debian-amd64")



Fatal error: Nmap file 2019/10-28/Nmap/Example-2019Q4-nmap_portknock.gnmap is not in grep(p)able format (-oG filename.gmap)
```
7. what did you expect instead?
I expected it to parse the file and perform a scan of the  hosts in it

**Comment by gbiagomba** [comment]
@drwetter unfortunately I can not share the file because it has work information in it. I can run it against a dummy target and see if the error occurs again. But it could be that either the issue was fixed in the newer release. I will try to download the latest version and see how that works then get back to you

**Comment by gbiagomba** [comment]
@drwetter Ya it looks like it was an issue with the older version because the new took the file just fine. I am going to see if I can reach out to the kali team to get them to upgrade the current version to the latest. In the meantime I will make some tweaks to my build to use this version instead.

**Comment by drwetter** [comment]
>  I am going to see if I can reach out to the kali team

that would be great. If it helps: here's an excerpt of the readme of the latest 2.9.5-8 (https://github.com/drwetter/testssl.sh/releases/tag/v2.9.5-8):

``It is highly recommended to switch to >=3.0rc4 now (see tag in the 2.9dev branch) now. There are a few known bugs in 2.9.5 which won't be backported as it requires a larger effort. Besides another leap forward in features (bigger ones: TLS 1.3 and ROBOT check) 3.0rc4+ is also working with OpenSSL 1.1.1.``

2.9dev was dropped and we're at the 3.0 branch.
