### ISSUE TITLE
Error when trying to run in batch/parallel and saving HTML file.

### ISSUE THREAD

**Issue by smseidl** [drwetter/testssl.sh#1366]
Please make sure that you provide enough information so that we understand what your issue is about.

1. uname -a
   `Linux uxtst401 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 13:49:55 PST 2018 x86_64 x86_64 x86_64 GNU/Linux`
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
`testssl.sh       3.0rc5 from https://testssl.sh/dev/`
3. git log | head -1 (if running from git repo)
`commit 6679dd7a1631da506f567ee3a0c4a6816debb683`
4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
`./bin/openssl.Linux.x86_64`
5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
Trying to run testssl.sh with a file of urls, create an html output file and run in parallel mode instead of sequential.  I'm using the following command:
`testssl.sh -oH /tmp/j38141_test2.html -iL urls.txt --parallel`
This is "failing" saying that "Fatal error: URI comes last"
If I remove the --parallel option, then it runs fine.  Due to the number of internal URLs I'm trying to scan, I'd like to run in parallel to complete faster.

6. what exactly was happening, output is needed

```
###########################################################
    testssl.sh       3.0rc5 from https://testssl.sh/dev/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!
###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]
 on uxtst401:/tmp/testssl.sh/bin/openssl.Linux.x86_64
 (built: "Jan 18 17:12:17 2019", platform: "linux-x86_64")


====== Running in file batch mode with file="urls.txt" ======

====================================================================================
/tmp/testssl.sh/testssl.sh --htmlfile=/tmp/testssl.1dFHiw/htmlfile_00000000.html /tmp/j38141_test2.html --warnings=batch --parallel https://uxtst406.xxxxxxxxx.com:4444

Fatal error: URI comes last

====================================================================================
/tmp/testssl.sh/testssl.sh --htmlfile=/tmp/testssl.1dFHiw/htmlfile_00000001.html /tmp/j38141_test2.html --warnings=batch --parallel https://uxfit1400.xxxxxx.com:4444

Fatal error: URI comes last

```
7. what did you expect instead?
If this is *expected* behavior the error message should change so its clear.  From the error message I feel like I'm supplying information incorrectly.

I'd like to see this command run in parallel and create an HTML result file of all URLs scanned.

**Comment by drwetter** [comment]
As the error message says.... 😉

You would need to put --parallel earlier.

**Comment by dcooper16** [comment]
Actually, there was a bug in the code. PR #1367 should fix it, but in the meantime replacing "-oH" with "--htmlfile" on the command line will also work.

**Comment by smseidl** [comment]
@drwetter @dcooper16 - I did try moving the `--parallel` around in the command and it did not help. I will try with the `--htmlfile` tomorrow morning and will post the results here.

**Comment by drwetter** [comment]
Pls try again
