### ISSUE TITLE
testssl insists on dns resolution, even if target is behind a proxy

### ISSUE THREAD

**Issue by xformerfhs** [drwetter/testssl.sh#1371]
1. uname -a
Linux mymachine 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
testsssl running in docker file
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
3.0rc5 from https://testssl.sh/dev/

3. git log | head -1 (if running from git repo)
N/A

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
From your docker file

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
5.1 Target is behind a proxy. Internal DNS does not know about the external URI and returns "Not found" when trying to resolve it: 
nslookup external.site.com
Server:		127.0.0.53
Address:	127.0.0.53#53
** server can't find external.site.com: NXDOMAIN

5.2 But proxy knows about the external site. So I added an option to use a proxy for the site:
sudo testssl.sh --proxy 127.0.0.1:3128 https://external.site.com

6. what exactly was happening, output is needed
Fatal error: No IPv4/IPv6 address(es) for "external.site.com" available

7. what did you expect instead?
Tests should run
testssl should not require a successful local DNS resolution of the host name if a proxy is used.

**Comment by drwetter** [comment]
Can you try ``DNS_VIA_PROXY=true ./testssl.sh <cmdline>``

PS: why you're using sudo?

**Comment by xformerfhs** [comment]
I use sudo because I run testssl with docker and if iI do not use sudo I get the following error message:

docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.

**Comment by xformerfhs** [comment]
Since I actually run testssl via "docker run -ti drwetter/testssl.sh"  I changed that to "docker run -e DNS_VIA_PROXY=true -ti drwetter/testssl.sh" but with the same effect. Maybe I just have to install testssl directly and not use the docker image.

**Comment by xformerfhs** [comment]
So, now I installed testssl locally and tried

DNS_VIA_PROXY=true  testssl.sh --proxy 127.0.0.1:3128 https://external.site.com
DNS_VIA_PROXY=true  testssl.sh https://external.site.com
testssl.sh --proxy 127.0.0.1:3128 https://external.site.com
testssl.sh https://external.site.com

All yield the same error message.

**Comment by xformerfhs** [comment]
I just realized that I was a bit negligent in my description of the environment. So here is a better one:

There are actually 2 proxies involved in this scenario:

1. Our company proxy which requires NTLMv2 authentication to tunnel through it. This proxy knows about the external domain name

2. A CNTLM proxy on the Linux machine where testssl is installed that supplies the NTLMv2 authentication that our company proxy requires. This proxy is running in our intranet and does not know about the external domain name

The proxy that I have to specify when calling testssl is the local CNTLM proxy. Otherwise I can not connect to our company proxy.

Please accept my apologies for not being clear about this.

**Comment by drwetter** [comment]
I do not have a proxy with a different DNS setup handy but if I test the proxy I have I clearly see a DNS lookup done by the proxy -- this without ``DNS_VIA_PROXY=true`` as this is the default. It then passes the DNS name of the object to be tested to the proxy instead of the IP address which is being resolved locally before.

Maybe another person can give a hand in here and confirm. 

I just fixed a bug in  #1372 while looking at this. I don't think it's related but to be sure best is to check again.

**Comment by drwetter** [comment]
OTOH I can't get it working with a proxy on my local machine like ``./testssl.sh -p --proxy=http://localhost:3128 testssl.sh``. It's getting stuck in an openssl call(!) @ ``./bin/openssl.Linux.x86_64 s_client -connect 81.169.166.184:443 -msg -proxy 127.0.0.1:3128 -servername testssl.sh -no_comp`` in ``determine_optimal_proto()``

**Comment by drwetter** [comment]
See comment in https://github.com/drwetter/testssl.sh/issues/1371#issuecomment-552126688 . If you have new information for me, I'll be happy to reopen.
