### ISSUE TITLE
Travis CI builds take long(er) time due to 25/tcp timeout

### ISSUE THREAD

**Issue by szycha76** [drwetter/testssl.sh#1384]
This test should be revised to save both time and resources on your travis-ci.org account/pipeline.
- own docker based local smtp/25 server may be a viable approach,
- or some elaborate ssh-tunnel to actual 3rd party smtp+starttls server on tcp/25.

Anyway: keep up the amazing work!
----[ cut here ]----
Checking plain JSON output for a failed run '--mx cloudflare.com' ...
./testssl.sh: connect: Connection timed out
./testssl.sh: line 10228: /dev/tcp/74.125.124.27/25: Connection timed out

Fatal error: Can't connect to "74.125.124.27:25"
Make sure a firewall is not between you and your scanning target!

**Comment by drwetter** [comment]
Hi @szycha76 ,

you mean the test which is supposed to fail in ``t/07_isJSON_valid.t``?

```
#3
# This testssl.sh run deliberately does NOT work as travis-ci.org blocks port 25 egress.
# but the output should be fine. The idea is to have a unit test for a failed connection.
```
