### ISSUE TITLE
Cipher suite colouring (--color 3) inconsistent with "cipher categories" test colouring

### ISSUE THREAD

**Issue by Delicates** [drwetter/testssl.sh#1393]
Running latest git version (Nov-2019).

In the "Testing cipher categories" section presence of "Triple DES Ciphers / IDEA" ciphers is marked in red with "offered (NOT ok)".

However 3DES ciphers are printed in yellow throughout with --color 3 option.
They should be red as well.

**Comment by drwetter** [comment]
yes, should be resolved. Thanks

**Comment by drwetter** [comment]
I think I am going to change bring the color of standard ciphers in line with the current cipher coloring.

**Comment by drwetter** [comment]
This is related to #1157 and it looks a bit like the change is bigger than I thought. Here's an assessment.

The cipher coloring takes place in ``pr_cipher_quality()``.  Status here here (for the bad ones) is:

```
*NULL*|*EXP*|ADH*: critical
*RC4*|*RC2*      : high
*CBC*:           : medium
ECDHE*AES*|DHE*AES*SHA*|*CAMELLIA*SHA   : low
3DES: --
IDEA: --  
```

So there it seems 3DES and IDEA are missing and are always labelled low as they are CBC ciphers (unless other rules e.g. ADH are overwriting this). There's also a contradicting labeling for RC2 in this function which should be addressed.

So, in ``run_cipherlists()`` we have 

```
LOW: 64 Bit + DES, RC[2,4] (w/o export)       Critical
Triple DES Ciphers / IDEA:                               High
Obsolete: SEED + 128+256 Bit CBC cipher: low
```

RC4 is not in line with ``run_rc4()`` ( Testing vulnerabilities). That needs to be high. 
Medium seems not an option here at all. (``sub_cipherlists()`` need to be called with 3 as a fourth argument which is not the case).

**Comment by drwetter** [comment]
To me PR #1416 looks good. I'll let this sit for a day or two in the case I overlooked something

**Comment by drwetter** [comment]
housekeeping, this should have been closed after merging the PR
