### ISSUE TITLE
awk issue MSYS2

### ISSUE THREAD

**Issue by PeterMosmans** [drwetter/testssl.sh#140]
Issue when running the latest version under msys2 (Windows 8.1):
```
  testssl.sh       2.5dev from https://testssl.sh/dev/
    (9183127 2015-07-14 09:36:23 -- 1.310)

./testssl.sh --assuming-http -H testssl.sh

--> Testing HTTP header response @ "/"

awk: warning: escape sequence `\/' treated as plain `/'
awk: cmd. line:1: /tmp/ssltester.0coOKA/http_header.txt
awk: cmd. line:1:                                  ^ syntax error
```

**Comment by drwetter** [comment]
Thx, Peter. for reporting.

No clue why this is currently -- as my MSYS2 system has GNU AWK 4.1.1 and e.g. the Linux system I am currently writing from is GNU AWK 4.1.0.

**Comment by PeterMosmans** [comment]
Please let me know if I can be of any help
```
 % awk --version
GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.3, GNU MP 6.0.0)
% uname -a
MINGW64_NT-6.3 Paradise 2.1.0(0.287/5/3) x86_64 Msys

```

**Comment by drwetter** [comment]
> Please let me know if I can be of any help

yes: to understand  why this fails under MSYS2.

I should have added in my previous posting that I see the same under MSYS2, but not under Linux.

PS: also I don't need ``--assuming-http`` under Linux.

**Comment by drwetter** [comment]
see 9ffdf7f5808333ec33b7fe22dd533351503adfc0.

Repaired the parser for windowish nslookup. Tested it. Worked for me. Pls reopen it if it doesn't for you.

Thx for reporting

**Comment by PeterMosmans** [comment]
Sorry, issue still persists:
```
 ./testssl.sh --assuming-http -H www.some.site

    testssl.sh       2.5dev from https://testssl.sh/dev/
    (9ffdf7f 2015-07-21 14:20:15 -- 1.324)

 Using "OpenSSL 1.0.2-chacha (1.0.2e-dev)" [~181 ciphers]


--> Testing HTTP header response @ "/"

awk: warning: escape sequence `\/' treated as plain `/'
awk: cmd. line:1: /tmp/ssltester.BBmyl5/http_header.txt
awk: cmd. line:1:               ^ syntax error
awk: cmd. line:1: /tmp/ssltester.BBmyl5/http_header.txt
awk: cmd. line:1:                                  ^ syntax error

```

**Comment by drwetter** [comment]
Hmm... can you do a ``DEBUG=1 bash -vx ./testssl.sh <>`` for me?

Strange, as it works for me now and hasn't yesterday. But we're using the same version...
![msys2-win7](https://cloud.githubusercontent.com/assets/8036727/8803168/b3a4a206-2fc5-11e5-906f-bfa01dacab82.png)

**Comment by PeterMosmans** [comment]
Dirk, check https://gist.github.com/PeterMosmans/3a3f60e335b2721f53c9
Something's not going as planned...

If I try it with a direct domain name instead of an alias (eg. testssl.sh) it works....

**Comment by PeterMosmans** [comment]
Wouldn't the usage of dig be better in these cases ?
```
 % dig +short testssl.sh
81.169.199.25
% dig +short pr.otect.me
www.go-forward.net.
go-forward.net.
96.126.102.137


```

**Comment by drwetter** [comment]
Morning Peter,

see code. First /etc/hosts is tried, if failed dig ist tried, if failed then host, if failed then nslookup.
I can blame it here on your strange DNS entries, but I guess I was not careful enough doing input validation ;-)

Patch will come during the day.

PS: Is that related to the awk prob?

Cheers, Dirk

**Comment by PeterMosmans** [comment]
Hi @drwetter , and a wonderful morning to you too.

Yeah, I think the issues are related.
A big *sorry* about not diving into the code myself and creating a pull request (which would save you time) - currently I'm lacking the time :disappointed: due to extenal *forces*...

**Comment by drwetter** [comment]
Hi @PeterMosmans ,

could you please give it a try -- when you find a minute?

Cheers, Dirk

**Comment by PeterMosmans** [comment]
Hi Dirk,

I tried the following version:
```
testssl.sh       2.5dev from https://testssl.sh/dev/
    (6e4c33d 2015-07-23 17:11:33 -- 1.327)
```

Using the --assuming-http and -h flag I get unfortunately the same message:

```
--> Testing HTTP header response @ "/"

awk: warning: escape sequence `\/' treated as plain `/'
awk: cmd. line:1: /tmp/ssltester.OOkKx1/http_header.txt
awk: cmd. line:1:               ^ syntax error
awk: cmd. line:1: /tmp/ssltester.OOkKx1/http_header.txt
awk: cmd. line:1:                                  ^ syntax error

```

I'm probably going to dive into the code myself this weekend, to save you some time ;)

Cheers,

Peter

**Comment by drwetter** [comment]
Hey Peter,

Am 07/24/2015 um 10:04 AM schrieb Peter Mosmans:
> Hi Dirk,
> 
> I tried the following version:
> 
> |testssl.sh 2.5dev from https://testssl.sh/dev/ (6e4c33d 2015-07-23 17:11:33 -- 1.327) |
> 
> Using the --assuming-http and -h flag I get unfortunately the same message:
> 
> |--> Testing HTTP header response @ "/" awk: warning: escape sequence `\/' treated as plain `/'
> awk: cmd. line:1: /tmp/ssltester.OOkKx1/http_header.txt awk: cmd. line:1: ^ syntax error awk:
> cmd. line:1: /tmp/ssltester.OOkKx1/http_header.txt awk: cmd. line:1: ^ syntax error |
> 
> I'm probably going to dive into the code myself this weekend, to save you some time ;)

Personally much appreciated and the OSS project is thankful for every contribution ;-)

I normally do it this way:

prompt% script -a <nameofdebuggingfile.script> -c "bash -vx ./testssl.sh --debug=1
--assuming-http -h testssl.sh"
prompt% vi <nameofdebuggingfile.script>
/syntax error

"--debug=1" leaves in addition a directory in /tmp with some debugging output.


Cheers, Dirk

**Comment by drwetter** [comment]
Hi @PeterMosmans,

closing this. I Thx for your help!

Cheers, Dirk
