### ISSUE TITLE
HSTS saying not offered when it is

### ISSUE THREAD

**Issue by raweb00** [drwetter/testssl.sh#1415]
1. uname -a: 
Linux 3.10.0-1062.9.1.el7.x86_64
   
2. testssl version from the banner:
testssl.sh 3.0rc5 from https://testssl.sh/dev/

3. git log | head -1 (if running from git repo)
N/A

4. openssl version used by testssl.sh: 
/bin/openssl.Linux.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
Unsure of how to reproduce

6. what exactly was happening, output is needed
The HSTS check is saying 'not offered' when it actually is offered. This is happening consistently on 3 of 90 IP's (all the others are working)
![notOffered](https://user-images.githubusercontent.com/59024689/71106955-323aac00-218e-11ea-883d-7fcf37f26ca0.PNG)

7. what did you expect instead?
It should tell me that it is offered, I double checked with the settings and ran scan on SSL Labs to verify it was working. What it should look like:
![Offered](https://user-images.githubusercontent.com/59024689/71106954-31a21580-218e-11ea-9669-9fc1447d747b.PNG)

_Note: I am using mass scan from https://github.com/TKCERT/testssl.sh-masscan and got this from the .csv file generated. I confirmed there was no issue with this_

**Comment by drwetter** [comment]
Thanks @raweb00 . The important bit is the hostname otherwise we can't look @ it. If you don't  want to divulge it publicly, ``grep  SWCONTACT`` testssl.sh will give you a hint.

**Comment by drwetter** [comment]
The point is the path. The node you supplied doesn't have the HSTS flag at "/" but at subsequent redirects.

As testssl.sh is a tool which spots such (and others) "slight misconfigurations" I am not really motivated to change testssl.sh following the redirects. For pentests this behavior is quite useful as you want to spot such weak points.

**Comment by drwetter** [comment]
One could think on either per command line option or in a second round following redirects and then supply the results. However I am afraid this will either clutter the output -- headers need to be displayed @ every redirect before hitting the final destination. Or if the final destination only will be used (with a note that this not the URL supplied) this will be at cost of accuracy which I am not sure I like.
