### ISSUE TITLE
All openssl s_client -connect x takes a long time executed

### ISSUE THREAD

**Issue by atmouse-** [drwetter/testssl.sh#1418]
Because systemd-resolved didn't route a single-label named "x" query to DNS upstream by default,
CHECK here https://github.com/systemd/systemd/issues/6224#issuecomment-312639959.

instead, It route to LLMNR lookups if LLMNR is enabled. There will be huge huge long time waiting for command `/usr/bin/openssl s_client -curves secp521r1 -connect x` if there is no named "x" machine in the localnet.

1. uname -a
```
Linux orbment 5.5.0-rc3-1-megx570 #30 SMP PREEMPT Wed, 25 Dec 2019 07:45:27 +0000 x86_64 GNU/Linux
```
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
**My laptop runs Archlinux, the testssl.sh installed from pacman**
```
testssl -b

No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl       2.9.5-8 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1d  10 Sep 2019" [~163 ciphers]
 on orbment:/usr/bin/openssl
 (built: "Nov 13 16:09:29 2019", platform: "linux-x86_64")
```

3. git log | head -1 (if running from git repo)

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host

6. what exactly was happening, output is needed
```
atmouse@orbment ~ % testssl https://www.google.com/

No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl       2.9.5-8 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1d  10 Sep 2019" [~163 ciphers]
 on orbment:/usr/bin/openssl
 (built: "Nov 13 16:09:29 2019", platform: "linux-x86_64")


 Start 2019-12-30 22:21:04        -->> 172.217.24.68:443 (www.google.com) <<--

 further IP addresses:   2404:6800:4005:80f::2004
 rDNS (172.217.24.68):   hkg07s33-in-f4.1e100.net. sin10s06-in-f68.1e100.net. sin10s06-in-f4.1e100.net.
 Service detected:       HTTP


 Testing protocols via sockets except SPDY+HTTP2

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 SPDY/NPN   not offered
 HTTP2/ALPN h2, http/1.1 (offered)

 Testing ~standard cipher categories

 NULL ciphers (no encryption)                  not offered (OK)
 Anonymous NULL Ciphers (no authentication)    not offered (OK)
 Export ciphers (w/o ADH+NULL)                 not offered (OK)
 LOW: 64 Bit + DES encryption (w/o export)     not offered (OK)
 Weak 128 Bit ciphers (SEED, IDEA, RC[2,4])    not offered (OK)
 Triple DES Ciphers (Medium)                   offered
 High encryption (AES+Camellia, no AEAD)       offered (OK)
 Strong encryption (AEAD ciphers)              offered (OK)


 Testing robust (perfect) forward secrecy, (P)FS -- omitting Null Authentication/Encryption, 3DES, RC4

 PFS is offered (OK)          ECDHE-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA ECDHE-ECDSA-AES256-SHA ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-RSA-CHACHA20-POLY1305
                              ECDHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA ECDHE-ECDSA-AES128-SHA



```
hung here,

and `ps -ef` command shows
```
/usr/bin/openssl s_client -curves prime256v1 -connect x
```
or else.

7. what did you expect instead?

Maybe use a truely non-exist domain "nonexist.example.com" is a replacement.

**Comment by drwetter** [comment]
Thanks for filing the issue.

My usual reply would be 'please use a maintained version' but unfortunately distributors at least don't meet that expectation. And I think in 3.0rc6 it'll be the same issue.

I don't have such a setup which sounds si^Wstrange to me (shouldn't mattter/off topic). But would you mind running ``sed 's/connect x/nonexist.example.com/g/ testssl.sh >/tmp/testssl.sh; testssl.sh <your previous cmdline>`` and let me know whether that helped?

**Comment by atmouse-** [comment]
Sure

```
[atmouse@orbment ~]$ time bash /usr/bin/testssl https://www.google.com/ 2>&1 >/dev/null

real    6m35.122s
user    0m14.790s
sys     0m5.497s
[atmouse@orbment ~]$ sed -e 's/connect x/connect nonexist.example.com/g' /usr/bin/testssl > /tmp/testssl.sh
[atmouse@orbment ~]$ time bash /tmp/testssl.sh https://www.google.com/ 2>&1 >/dev/null

real    1m1.590s
user    0m14.757s
sys     0m5.573s
```

The testssl perform now as expected :)

**Comment by drwetter** [comment]
Thanks!

Will fix that in 3.0 for sure, not sure about 2.9.5

**Comment by dcooper16** [comment]
Hi @atmouse- ,

Thanks for reporting this.

The idea of replacing `x` with a non-existent domain name seems to be a good solution. However, rather than just picking a domain name that seems likely to never used in the future (nonexist.example.com), I suggest we use a reserved domain name from [RFC 6761](https://tools.ietf.org/html/rfc6761).

Based on [RFC 6761](https://tools.ietf.org/html/rfc6761), Section 6.5, names of the form *.example.com are less than ideal. It says that DNS servers and libraries need to treat these names just like other names, and these names may be registered (but only by IANA).

The best option seems to come from [RFC 6761](https://tools.ietf.org/html/rfc6761), Section 6.4. It says that DNS names that include "invalid" as one of the labels must not be registered. Even better, it says that:

> Name resolution APIs and libraries SHOULD recognize "invalid" names as special and SHOULD always return immediate negative responses.  Name resolution APIs SHOULD NOT send queries for "invalid" names to their configured caching DNS server(s).

It similarly says that DNS servers should recognize "invalid" names and should generate immediate responses rather than trying to perform a look up.

So, how about replacing `x` with `invalid.testssl.sh`?

**Comment by drwetter** [comment]
> So, how about replacing x with invalid.testssl.sh?

yeah, we could do that. But this may penalize all other users, at least in terms of privacy. Also I am not sure if somebody runs testssl.sh purely internal she/he run into other issues.

Can't we just use e.g. ``openssl s_client -ssl2 -connect 127.0.0.1`` instead, or do I overlook something?

**Comment by dcooper16** [comment]
> yeah, we could do that. But this may penalize all other users, at least in terms of privacy.

Okay. I liked the idea that RFC 6761 said the name resolution API SHOULD just return a negative response to names such as invalid.testssl.sh without sending any queries, but it seems that the DNS library on my computer does send the query to the DNS server. Also that even if the library does send out the query, DNS servers are supposed to just return a negative response for these names rather than querying yet other servers. But, I don't know how many DNS servers have implemented this.

> Also I am not sure if somebody runs testssl.sh purely internally she/he run into other issues.

So, the problem would be clients that have problems with any DNS lookup attempts?

> Can't we just use e.g. openssl s_client -ssl2 -connect 127.0.0.1 instead, or do I overlook something?

I'll have to look into this some more. In cases in which the option being tested is supported, it seems that I sometimes get a "no port defined" error, and sometime OpenSSL tries to connect to 127.0.0.1 on port 443. Getting a "no port defined" error is fine, but having OpenSSL actually make a connection attempt for each of these tests would be less than ideal.

Maybe next week I can look into the possibility of using a dummy IP address, so that no DNS lookup would be done and (hopefully) OpenSSL doesn't try to connect to anything.

**Comment by drwetter** [comment]
some brainstorming...

> I'll have to look into this some more. In cases in which the option being tested is supported, it seems that I sometimes get a "no port defined" error, and sometime OpenSSL tries to connect to 127.0.0.1 on port 443. Getting a "no port defined" error is fine, but having OpenSSL actually make a connection attempt for each of these tests would be less than ideal.

that's true.  I did a small test and it seems that on my system it doesn't hurt:

```
prompt:~|1% time (for i in {1..500}; do /usr/bin/openssl s_client -curves prime256v1 -connect x 2>/dev/null; done)    
( for i in {1..500}; do; /usr/bin/openssl s_client -curves prime256v1 -connec)  4.81s user 1.15s system 67% cpu 8.859 total
prompt:~|1% time (for i in {1..500}; do /usr/bin/openssl s_client -curves prime256v1 -connect 127.0.0.1 2>/dev/null; done)   
( for i in {1..500}; do; /usr/bin/openssl s_client -curves prime256v1 -connec)  3.85s user 0.89s system 99% cpu 4.784 total
prompt:~|1%
```

But  what if the port (here: 4433) is taken?

```
prompt:~|1% time (for i in {1..500}; do /usr/bin/openssl s_client -curves prime256v1 -connect 127.0.0.1:22 2>/dev/null >/dev/null; done) 
[..]
( for i in {1..500}; do; /usr/bin/openssl s_client -curves prime256v1 -connec)  5.31s user 1.19s system 60% cpu 10.749 total
prompt:~|1% 
```

It's not only that it takes long. It seems ugly to me. Also it's not "a low profile mode", i.e. if some people are running e.g. iptables on the localhost interface, every run of testssl.sh might cause a logfile entry -- or even worse a DROP rule is as bad as the scenario from @atmouse- .

So atm I think this is more complicated than I initially thought. It would be fine if we could detect LLMNR (which can be an ugly piece of code also) or if we use this when the user requested it explicitly (via cmd line or ENV).

FYI: BSDs already complain _no port defined_, however the preference is the first argument to ``s_client``. So there it doesn't seem to make a difference. (old FreeBSD and up-to-date OpenBSD tested) .

I haven't tested any windows stack (@ all: can you help?) or anicent openssl versions.

We should keep in mind that the complaint has a point but it seems to be a special setup (deducted from the fact that nobody else complained yet) and a fix should not introduce other problems we don't see yet.

**Comment by drwetter** [comment]
@atmouse- : is ``/usr/bin/openssl s_client  -curves prime256v1 -connect 10.in-addr.arpa.`` any better?

**Comment by drwetter** [comment]
https://tools.ietf.org/html/rfc6761#section-6.4 sounds better and more promising: ``/usr/bin/openssl s_client  -curves prime256v1 -connect invalid.``

**Comment by atmouse-** [comment]
> is `/usr/bin/openssl s_client -curves prime256v1 -connect 10.in-addr.arpa.` any better?

seems good, The openssl connect to 127.0.0.1 4433 and them be refused immediately.
```
time /usr/bin/openssl s_client -curves prime256v1 -connect 10.in-addr.arpa.
140737348187392:error:0200206F:system library:connect:Connection refused:crypto/bio/b_sock2.c:110:
140737348187392:error:2008A067:BIO routines:BIO_connect:connect error:crypto/bio/b_sock2.c:111:
connect:errno=111

real    0m0.007s
user    0m0.006s
sys     0m0.000s
```

Also I consider `invalid.` is a better one.  @drwetter 
```
time /usr/bin/openssl s_client -curves prime256v1 -connect x
140737348187392:error:2008F002:BIO routines:BIO_lookup_ex:system lib:crypto/bio/b_addr.c:724:Temporary failure in name resolution
connect:errno=11

real    0m10.940s
user    0m0.007s
sys     0m0.000s
time /usr/bin/openssl s_client -curves prime256v1 -connect invalid.
140737348187392:error:2008F002:BIO routines:BIO_lookup_ex:system lib:crypto/bio/b_addr.c:724:Name or service not known
connect:errno=22

real    0m0.007s
user    0m0.007s
sys     0m0.000s
```

**Comment by drwetter** [comment]
Excellent, PR follows. 

Good that @dcooper16 (of course :+1:  ) mentioned the RFC, otherwise I wouldn't have searched for a solution there.

**Comment by drwetter** [comment]
Closing this. If you're interested you should forward this downstream, i.e. ArchLinux maintainers, so that they backport this patch. Or telling them that they should switch to a supported version
