### ISSUE TITLE
825 Days validity

### ISSUE THREAD

**Issue by fbacchella** [drwetter/testssl.sh#1422]
Many CA agreed to restrict certificate validity to 825 days (see https://cabforum.org/2017/03/17/ballot-193-825-day-certificate-lifetimes/).
Apple implemented it in Safari: https://support.apple.com/en-us/HT210176.
But I don't think it's tested in testssl.sh as 'grep -r 825 *' in source directory returns no meaningful resuls. Is there plan to add this check ?

**Comment by drwetter** [comment]
Yeah, we could/should do that. The issuing date also matters. March 1st 2018 is the deadline here.

Thanks, Dirk

**Comment by drwetter** [comment]
WIP see https://github.com/drwetter/testssl.sh/compare/825_days

**Comment by drwetter** [comment]
done
