### ISSUE TITLE
Lookup SMTP servers when usning -t=starttls or add an new option

### ISSUE THREAD

**Issue by Night1** [drwetter/testssl.sh#1424]
Little suggestion, 

To make it easier for batch jobs there could be an option for testssl.sh to lookup SMTP servers of a given domain so  when doing batchjobs  user does not have to do this prior.

**Comment by drwetter** [comment]
How about --mx, see help?
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by teward** [comment]
To make it easier on EndUser, this is what @drwetter is referring to:

https://github.com/drwetter/testssl.sh/blob/3.0/testssl.sh#L17047
>      --mx <domain/host>            Tests MX records from high to low priority (STARTTLS, port 25)

... which I believe already does what's being requested.

**Comment by Night1** [comment]
You are right @drwetter  thank you :)
