### ISSUE TITLE
Difficult to interpret final exit status

### ISSUE THREAD

**Issue by ajbouh** [drwetter/testssl.sh#145]
Based on reading the output of testssl.sh, it appears that my host has passed, but the exit code is 3. Am I correct in interpreting that as some sort of failure? How can I tell what to fix? My best guess is the two sets of red dashes in the snippet below (coloring removed)

             # of certificates provided   1
             Certificate Revocation List  --
             OCSP URI                     --
             OCSP stapling                not offered
             TLS timestamp                random values, no fingerprinting possible

Is there a way to disable the demand for OCSP? For now I've resorted to searching output for "not ok", but I know this misses things like weak DH parameter sizes. Am I missing something in the documentation?

**Comment by drwetter** [comment]
Thx, @ajbouh.

There's no real "pass" now. If your return code is 3, it is probably due to the fact that you collected three tests which had minor issues.  That's not a rating (yet) and I was not very carefully at all inspecting what function returns which penalty. So better disregard this value.

It's not even a **weak** indicator now. Wrt rating see #100 .

**Comment by drwetter** [comment]
closing

**Comment by ajbouh** [comment]
Thanks for the quick reply. I'll stick with the grep for "not ok" for now.

**Comment by drwetter** [comment]
BTW: Exit code has changed now in d28317f2d058557338ad1c4268f2b9a39ff27b80

**Comment by ajbouh** [comment]
Awesome. Thanks for the follow-up!

**Comment by hickford** [comment]
Hi. Has "exit code always 0 unless an error occurred" changed in 2.9dev? In 2.8 `testssl.sh -U --ip one imap.gmail.com:993` exited 0, in 2.9dev it exits 20.

https://github.com/drwetter/testssl.sh/wiki/Man-page#exit-status

**Comment by drwetter** [comment]
Err, seems so, yes.

Man page is how it ~should be. The logic with ret deserves revamping.
