### ISSUE TITLE
-U (--vulnerable) does not cover -f (--pfs)

### ISSUE THREAD

**Issue by yan-foto** [drwetter/testssl.sh#1504]
**This is not a bug, rather an issue with documentation and/or program logic**

---

1. uname -a
`Darwin hampers.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
```
testssl.sh       3.0 from https://testssl.sh/
    (567450e 2019-11-19 15:13:14 -- )
```

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
`Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]`

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
Run `testssl.sh -U example.com` and see that PFS results are not printed.

6. what exactly was happening, output is needed
PFS result is missing.

7. what did you expect instead?
According to the help text:
`-U, --vulnerable              tests all (of the following) vulnerabilities (if applicable)`
perfect forward secrecy (`-f`) is also subsumed under the "following vulnerabilities" but is not tested for.

I'd expect `-f` to be part of `-U` or the documentation to be corrected (happy to send a PR, if you consider this issue as valid).

**Comment by dcooper16** [comment]
Hi @yan-foto ,

The output from `-help` does seem to suggest that testing for PFS is covered under testing for vulnerabilities. That should be changed. PFS is definitely not a vulnerability. The `-help` output should just be changed to list `-f` earlier -- perhaps between `-s` and `-p`, as it is in https://github.com/drwetter/testssl.sh/blob/3.1dev/doc/testssl.1.md.
