### ISSUE TITLE
PFS session ticket keys rotation

### ISSUE THREAD

**Issue by spinone** [drwetter/testssl.sh#1515]
I'm getting a few notifications in the testssl output saying "PFS requires session ticket keys to be rotated < daily". 
From the session ticket hint, the session time is indeed > 24hrs, but I can't find any reference for the PFS < daily rotation requirement. I need some sort of reference to validate the finding for the pen test report - can you help?
Thanks,
Spinone

**Comment by drwetter** [comment]
https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/

**Comment by drwetter** [comment]
As a compensation: how about a PR, containing the URL as a comment?
