### ISSUE TITLE
inconclusive test, matching cipher in list missing

### ISSUE THREAD

**Issue by kaushalshriyan** [drwetter/testssl.sh#1517]
Hi Dirk,

I am seeing the below information when I ran testssl.sh against a https domain.

###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (e0c83b2 2020-02-24 14:21:28 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]
 on Kaushals-MacBook-Pro:./bin/openssl.Darwin.x86_64
 (built: "Feb 22 09:55:43 2019", platform: "darwin64-x86_64-cc")

> Testing server preferences
>  Has server cipher order?     no (NOT ok)
>  Negotiated protocol          TLSv1.2
>  Negotiated cipher            ECDHE-RSA-AES128-GCM-SHA256, 521 bit ECDH (P-521) -- inconclusive test, matching cipher in list missing, better see below
>  Negotiated cipher per proto  (matching cipher in list missing)
>      ECDHE-RSA-AES256-GCM-SHA384:   TLSv1.2
>  No further cipher order check has been done as order is determined by the client

I will appreciate if you can help me understand the above mentioned issue. I am running Nginx version: nginx/1.16.1 on CentOS Linux release 7.7.1908 (Core) with OpenSSL 1.0.2k-fips  26 Jan 2017. Do I
need to configure any settings in /etc/nginx/nginx.conf? 

Thanks in Advance and I look forward to hearing from you.

Best Regards,

Kaushal

**Comment by drwetter** [comment]
Please google for the solution.
