### ISSUE TITLE
Prebuilt binary fails on Debian Buster

### ISSUE THREAD

**Issue by gabviv73** [drwetter/testssl.sh#1520]
On Debian buster:
    /usr/lib/zabbix/externalscripts/openssl.Linux.i686 s_client -connect pubserver:993 -starttls imap

`
Error configuring OpenSSL

169052196:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory

169052196:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:233:

169052196:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:271:module=ssl_conf, path=ssl_conf

169052196:error:0E076071:conf
`
uname -a
Linux firepub 4.19.0-8-686-pae #1 SMP Debian 4.19.98-1 (2020-01-26) i686 GNU/Linux

Suggestions ?

**Comment by drwetter** [comment]
export OPENSSL_CONF=/etc/ssl/

(testssl.sh does that for you automatically)
