### ISSUE TITLE
The `/bin/pwd` doesn't exist on NixOS

### ISSUE THREAD

**Issue by CMCDragonkai** [drwetter/testssl.sh#1521]
On the current master, there's calls to `/bin/pwd`, this doesn't exist on NixOS, so I had to change these things to just `pwd`.

**Comment by CMCDragonkai** [comment]
Replace master with 3.1dev.

**Comment by drwetter** [comment]
> On the current master, there's calls to /bin/pwd, this doesn't exist on NixOS, so I had to change these things to just pwd.

Ok, thanks. Will change that later to `pwd -P`

The branches are deliberately like they are

**Comment by dcooper16** [comment]
> Ok, thanks. Will change that later to pwd -P

Is there any reason not to just replace `$(pwd)` and `$(/bin/pwd)` with `$PWD`?

**Comment by drwetter** [comment]
On 3/4/20 3:58 PM, David Cooper wrote:
>     Ok, thanks. Will change that later to pwd -P
> 
> Is there any reason not to just replace |$(pwd)| and |$(/bin/pwd)| with |$PWD|?

Good point. That should be the same as pwd is a builtin and calls $PWD.

However looking at it now it seems $PWD would be slightly better as
$PWD is faster.


time for i in $(seq 1 10000); do     echo $PWD >/dev/null; done

real    0m0.101s
user    0m0.030s
sys     0m0.070s


time for i in $(seq 1 10000); do     echo $(pwd) >/dev/null; done

real    0m5.158s
user    0m3.202s
sys     0m2.303s


Others state that $PWD can be undefined. That should likely not affect
us as we're running a (maste)r bash process which probably should redefine
$PWD also if it was unset before

**Comment by drwetter** [comment]
Just confirmed it. As said, a new bash instance will set ``$PWD`` again, also if it was unset before. So the preferred solution is ``$PWD``. Probably taking ``$(pwd)`` wouldn't hurt much but let's do what makes most sense.

**Comment by drwetter** [comment]
merged
