### ISSUE TITLE
How to know testSSL finished its working?

### ISSUE THREAD

**Issue by sonawanesarvesh** [drwetter/testssl.sh#1549]
Hello
First of all, please accept my apologies for silly question

I am using --assuming-http -q -p -s -f -U -S -P --jsonfile=xyz/xzy.json https://www.exmaple.com
arguments

there is no issue, i am getting result, 

The problem is - the resulted json file is generated at very beginning and it gets appended till testssl completes its working, so i dont know at what stage the file .json becomes available completely.

i have to fed this json file to next program but i am not able to know exactly when this json completely gets ready

**Comment by sonawanesarvesh** [comment]
most of the other applications usually generates json at end in one go, but testssl creates json at start and keeps it appending

**Comment by drwetter** [comment]
It is done when testssl.sh is done :-) 

So either you monitor the console or if you monitor the JSON output watch out for ``scanTime``

**Comment by sonawanesarvesh** [comment]
:)
thank you for quick answer,
i am able to check the monitor / log manually, but i am not able to take judgement in code when its done

i will explain following is my pseudo python code - 

#pseudo start testssl.sh function
start_testssl():
  testssl.sh --assuming-http -q -p -s -f -U -S -P --jsonfile=xyz/xzy.json https://www.example.com
start_testssl()

#once json file is ready read it and print it
with open(xzy.json) as f:
    data = json.load(f)
    print(data)

this directly error out saying file does not exists, but file is already created but its not released by start_testssl() function as it is appending file

**Comment by sonawanesarvesh** [comment]
i hope you got my problem?
Without any manual log checking etc, via program I want to know whether testssl.sh is still running in background or its closed

**Comment by drwetter** [comment]
> i hope you got my problem?

yes, but I am afraid I can't help you. The problem seems you're reading the output before it's finished.  As this is beyond the scope of what the issue tracker is about and thus I am closing this.

You need to wait until testssl.sh is finished and then read it. You can do polling but it's a stupid idea.  I am not a python guy either / don't understand your pseudo code. If somebody is good in python, it's fine to speak up and  give you a hand.
