### ISSUE TITLE
testssl does not handle DNS lookups with multiple A RECORDs

### ISSUE THREAD

**Issue by gabrielfloyd** [drwetter/testssl.sh#1550]
Please make sure that you provide enough information so that we understand what your issue is about.

0. Did you check the documentation in ~/doc/ or, if it is a different problem: Did you google for it?
no

1. uname -a
   Darwin hostname.xx.yy.com 17.7.0 Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64 x86_64

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
    testssl.sh       3.0 from https://testssl.sh/
 Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]
 on HOSTNAME:./bin/openssl.Darwin.x86_64
 (built: "Feb 22 09:55:43 2019", platform: "darwin64-x86_64-cc")

3. git log | head -1 (if running from git repo)
N/A

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
./bin/openssl.Darwin.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
run testssl.sh against a URL that resolves to a single IP address with multiple A RECORDs

6. what exactly was happening, output is needed
When testssl.sh does the initial rDNS lookup, if the resulting record includes multiple names, it concatenates them together, giving the appearance of a rather long name:
$nslookup 159.www.xxx.yyy
yyy.xxx.www.159.in-addr.arpa	name = firstname.xx.yy.com.
yyy.xxx.www.159.in-addr.arpa	name = secondname.xx.yy.com.

testssl.sh output:
 rDNS (159.www.xxx.yyy):  firstname.xx.yy.com.secondname.xx.yy.com.

7. what did you expect instead?
Perhaps a space in the rDNS output to indicate it resolves to multiple hostnames.

**Comment by drwetter** [comment]
Works for me (testssl.net). Please do a git pull. This probably has been fixed  in bc9cf9f428dd46f120c55a8e161dc6a1a10dca5c .

If not please come back with an example.
