### ISSUE TITLE
Mac OS X: lines appear with pr_green and other colours. OpenSuSE Tumbleweed is OK.

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#156]
I tested both on OpenSuSE Tumbleweed and Mac OS X and the same version:

    ./testssl.sh -v
    testssl.sh       2.6rc1 from https://testssl.sh/dev/
    (d2f56a4 2015-08-04 13:44:54 -- 1.333)

Both have this:

    echo $TERM
    xterm-256color

This works on OpenSuSE with colours and all:

    ./testssl.sh beginend.net

But on Mac OS X, I get this:

    ./testssl.sh: line 1251: pr_blue: command not found
    (via sockets except TLS 1.2 and SPDY/NPN)

     SSLv2      ./testssl.sh: line 2354: pr_greenln: command not found
     SSLv3      ./testssl.sh: line 1288: pr_greenln: command not found
     TLS 1      offered
     TLS 1.1    offered
     TLS 1.2    ./testssl.sh: line 1334: pr_greenln: command not found
     SPDY/NPN   not offered

    ./testssl.sh: line 1349: pr_blue: command not found

     Null Ciphers                 ./testssl.sh: line 974: pr_greenln: command not found
     Anonymous NULL Ciphers       ./testssl.sh: line 974: pr_greenln: command not found
     Anonymous DH Ciphers         ./testssl.sh: line 974: pr_greenln: command not found
     40 Bit encryption            ./testssl.sh: line 974: pr_greenln: command not found
     56 Bit encryption            ./testssl.sh: line 974: pr_greenln: command not found
     Export Ciphers (general)     ./testssl.sh: line 974: pr_greenln: command not found
     Low (<=64 Bit)               ./testssl.sh: line 974: pr_greenln: command not found
     DES Ciphers                  ./testssl.sh: line 974: pr_greenln: command not found
     Medium grade encryption      ./testssl.sh: line 978: pr_litegreenln: command not found
     Triple DES Ciphers           ./testssl.sh: line 981: pr_brownln: command not found
    not offered (OK)
     High grade encryption        ./testssl.sh: line 969: pr_greenln: command not found
    ./testssl.sh: line 970: pr_brownln: command not found

    ./testssl.sh: line 1883: pr_blue: command not found

**Comment by drwetter** [comment]
Thx for reporting. 

Probably a bash issue due to the latest change with respect to #27

**Comment by drwetter** [comment]
Can't reproduce it on FreeBSD9. But I see on platforms which need to display something in magenta:

```
dirks@laptop:~|0% ./testssl.sh hostname                        
./testssl.sh: line 3396: pr_magentaln: command not found

###########################################################
    testssl.sh       2.6rc1 from https://testssl.sh/dev/
    (1.333 2015/08/01 23:25:38)

[..]
``` 

The color_maker introduced in e227d1ea42dedc146ac309804191635c4e7b38f9 is here initialized too late.

"Your" error is probably because bash3 won't export the colors "evaled" from the array.

**Comment by drwetter** [comment]
If I make this function from #27 global the moment it's being called the functions are being initiated. But this conflicts with the --color option which is done late.

**Comment by drwetter** [comment]
Should work now. Could you give it a try @jpluimers ?

**Comment by jpluimers** [comment]
@drwetter tried `./testssl.sh beginend.net` again, and it works fine with this version:

        testssl.sh       2.6rc1 from https://testssl.sh/dev/
        (f56139d 2015-08-05 11:31:55 -- 1.334)

**Comment by drwetter** [comment]
Thx @jpluimers for reporting and confirming it's fixed!
