### ISSUE TITLE
let testssl.sh operate as https server to test a client

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#157]
More a brainstorm idea than a direct issue:

It would be awesome when `testssl.sh` could function as a server to test and report the https handshake a non-webbrowser https-client does.

There is `openssl s_server` that can function as a base, but needs some setup (with a certificate - potentially self-signed - and probably others).

https://www.openssl.org/docs/apps/s_server.html

**Comment by drwetter** [comment]
thx! 

My 2 cents:
* sounds good
* not sure whether a separate script would be more appropriate 
* s_server only contains a mini web server
* no STARTTLS
* don't know whether it'll be practically enough

**Comment by jpluimers** [comment]
It would be ideal to test for instance what ciphers a tool like the vSphere Client is compatible with. To run that on older Windows versions, [VMware recommends](http://kb.vmware.com/kb/2049143#referLink_2054085) setting `<cipherList>ALL</cipherList>` which is stupid^w risky. I [trimmed that down to a shorter list](http://wiert.me/?p=28893&shareadraft=55c3c716ea023), but think I can make it more secure. This new feature would help a lot with that.

**Comment by drwetter** [comment]
Am 08/06/2015 um 10:46 PM schrieb Jeroen Wiert Pluimers:
> It would be ideal to test for instance what ciphers a tool like the vSphere Client is
> compatible with. To run that on older Windows versions, VMware recommends
> <http://kb.vmware.com/kb/2049143#referLink_2054085> setting |<cipherList>ALL</cipherList>|
> which is stupid^w risky. I trimmed that down to a shorter list
> <http://wiert.me/?p=28893&shareadraft=55c3c716ea023>, but think I can make it more secure. This
> new feature would help a lot with that.

Ah, ok. That means recycle some code, got ya.

Did you try your case with s_server? Just asking because I tried to mimic some testcases
like insecure client renegotiation and that did not work. Maybe me cases were too special as
it's beyond testing protcols and ciphers.

Cheers, Dirk

**Comment by jpluimers** [comment]
Not yet. There is more pressing stuff that I need to finish first.
Note my proposal would also work for something like this: https://plus.google.com/+WalterPrins/posts/RDvgQTpp8bN

> Tracing back the cause of 
>   `error: 1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac.`

**Comment by drwetter** [comment]
That can be probably done better with docker, see discussion in #209

**Comment by jpluimers** [comment]
OK. Thanks. Any idea about the server side?

**Comment by drwetter** [comment]
no really. For now it seems too far off the current project. If somebody takes the lead on this: great. Then still it needs to be discussed how that is going to work with the existing code -- I am missing ideas here.

**Comment by jpluimers** [comment]
I really wish I had the time and was better at developing this kind of stuff. It's already hard to keep up in both the .NET and Delphi worlds. If I ever get time, I will let you know.
