### ISSUE TITLE
Confusing finding: Obsolete: SEED + 128+256 Bit CBC cipher offered

### ISSUE THREAD

**Issue by pburkholder** [drwetter/testssl.sh#1571]
I was given a pentest report today that relied on `testssl.sh` and it had the confounding finding that apparently we support SEED(!) and only after lost time have I come to realize that the same language:

```
Obsolete: SEED + 128+256 Bit CBC cipher       offered
```

is used for SEED  -- OR  -- for continuing to support CBC ciphers.

While it's true that CBC is on it's way out (although still in place for nsa.gov and cia.gov), it's confusing to lump that together with SEED.  A few ideas that might make this easier on end users:

- have the finding also report the offending cipher suites (this may be possible, I don't know all our cli options yet).
- separate out the SEED finding from CBC so, e.g.:
```
       Obsolete: SEED                  not offered (OK)
       Obsolete: CBC ciphers      offered
```
- clarify the wording with the most likely reason first:
```
       Obsolete: CBC ciphers (and/or SEED)     offered
```

Anyhow, I'm new to your tool, and it's clearly a useful tool, so thanks for all your work here, and for taking my suggestion into consideration.

Version:
```
$ docker run --rm -ti drwetter/testssl.sh -v

###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (8ff4520 2020-03-25 18:28:03 -- )
```

**Comment by drwetter** [comment]
Thanks, good point. The '+' is misleading. 

Besides: If I see that correctly all CBC ciphers are being tested here. AES_CBC, SEED_CBC, ARIA_CBC and CAMELLIA_CBC.

**Comment by drwetter** [comment]
fixed in both branches. Thanks for taking the time and file the issue.
