### ISSUE TITLE
Proposed feature: More information on certificate public keys

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#1576]
The discussion in #1573 about DH groups in `run_fs()` and `run_logjam()` led me to think about the subject public key in `certificate_info()`. If the server supports ephemeral (EC)DH key exchange, we report the elliptic curves and DH groups used in `run_fs()` and `run_logjam()`, but when the server's certificate contains a EC or DH key, we just report the key's length.

Perhaps we could extend `certificate_info()` to similarly report additional information. For an EC subject public key, report which curve. In the unlikely event of a DH subject public key, report the DH group (is it a common prime?).

I checked SSL Labs, and it just reports the length for an EC subject public key. However, for an RSA key it reports the value of the exponent (e.g., "e 65537"), which we don't.

Would this be a useful feature?

**Comment by drwetter** [comment]
Sure, I think so

**Comment by dcooper16** [comment]
Hi @drwetter,

I just submitted PR #1619 for this issue. At the moment it just prints the additional information, but doesn't do anything more with the information.

I know that `run_logjam()` rates a small ephemeral DH key as worse if it is a common prime. `certificate_info()` could be changed to do the same with a static DH key.

In every RSA certificate that I've seen, the public exponent has been 65537, which is a good choice. Should testssl.sh warn if a smaller exponent is used?

The CA/Browser Forum's Baseline Requirements say:

> RSA: The CA SHALL confirm that the value of the public exponent is an odd number equal to 3 or more. Additionally, the public exponent SHOULD be in the range between 2<sup>16</sup>+1 and 2<sup>256</sup>-1

Similarly, [FIPS 186-4](https://doi.org/10.6028/NIST.FIPS.186-4), says that "_e_ **shall** be an odd positive integer such that  2<sup>16</sup> <   e < 2<sup>256</sup>."

.

**Comment by magnuslarsen** [comment]
I can chime in here, and say that for rating, RSA exponent of 1 gives a grade cap F:
https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide#changes-in-2009l-4-march-2016 (first point)

Something like this should do
`[[ $cert_spki_info -eq 1 ]] && set_grade_cap "F" "RSA certificate uses exponent of 1"`
