### ISSUE TITLE
Version 3.1dev uses ADDTL_CA_FILES instead of ADDITIONAL_CA_FILES

### ISSUE THREAD

**Issue by logopk** [drwetter/testssl.sh#1581]
Please make sure that you provide enough information so that we understand what your issue is about.

0. Did you check the documentation in ~/doc/ or, if it is a different problem: Did you google for it?
Help and doc/testssl.1.md say ADDITIONAL_CA_FILES can be used to set custom CA

1. uname -a
   Darwin xxx 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -5 | tail -2
    testssl.sh       3.1dev from https://testssl.sh/dev/.  installed from homebrew

3. git log | head -1 (if running from git repo)
n/a

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
/usr/local/opt/openssl@1.1/bin/openssl (that is 1.1.1g)

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
ADDITIONAL_CA_FILES from former version in environment
 
6. what exactly was happening, output is needed
self signed CA is invalid
 Chain of trust               NOT ok (chain incomplete)

7. what did you expect instead?
self signed CA is valid ;-)
 Chain of trust               Ok

**Comment by drwetter** [comment]
you're right, thanks! (d44a643f)

**Comment by drwetter** [comment]
fixed

**Comment by jcmcken** [comment]
FYI, the published online documentation still refers to ``ADDITIONAL_CA_FILES``:

https://testssl.sh/testssl.1.html

**Comment by drwetter** [comment]
You're right, thanks. However that still to version 3.0. The version however is not in the man page. It should be.
