### ISSUE TITLE
Request for "Final testing for 2.6"

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#160]
Hi,

the 2.6 release is scheduled by the end of this month. It would be great if that release would be 100% error free (TM)``</dreaming>.``

Especially for Darwin and MSYS2 platforms would be cool, but not limited to of course. I am planning to squash all bugs reported in the last week of August.

If you want to help tracking down problems yourself there are two good options
  * ``script``, run ``bash -vx testssl.sh <heregoesyourcmdline>``, ``exit`` and have a look at ``typescript`
  * ``testssl.sh --debug=X <heregoesyourcmdline>``, where X is s.th. between 1 and 6. It leaves a directory with single test results in ``/tmp`` after finishing and leaves more or less (X=1: none) output on the screen.

Cheers, Dirk

**Comment by jpluimers** [comment]
Mac OS X Darwin; get an error about `declare -A`.

Full log here: https://gist.github.com/jpluimers/0f42d58a920b96a7d362

Extract:

    RetinaMBPro1TB:testssl.sh jeroenp$ ./testssl.sh beginend.net
    ./testssl.sh: line 300: declare: -A: invalid option
    declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
    
    ###########################################################
        testssl.sh       2.6rc1 from https://testssl.sh/dev/
        (7f97e8b 2015-08-14 13:34:45 -- 1.344)
    ...
    RetinaMBPro1TB:testssl.sh jeroenp$ uname -a
    Darwin RetinaMBPro1TB.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

**Comment by drwetter** [comment]
Thx,  @jpluimers!

Comment see readme. This was probably a bash v3 issue on Darwin.

Further bug reports appreciated (thus leaving this one open)

**Comment by jpluimers** [comment]
Thanks. This one is fixed. Keep other reports coming (:

**Comment by drwetter** [comment]
yes please. For all other issues here pls not that only those belonging to this milestone will make it into the next release (https://github.com/drwetter/testssl.sh/milestones/2.5dev%20%282.6%29)

**Comment by drwetter** [comment]
Last couple of days now to have errors fixed in in this release. 

Pls give it a shot again.

**Comment by jpluimers** [comment]
It sometimes leaks processes:

    retinambpro1tb:testssl.sh jeroenp$ ./testssl.sh --color 0 forums.embarcadero.com:563 | gist -d "./testssl.sh --color 0 forums.embarcadero.com:563 & echo NNTP over SSL is still very vulnerable"
    https://gist.github.com/fe6bcc06aa5473f8abaa
    retinambpro1tb:testssl.sh jeroenp$ ps -ax | grep openssl
    27822 ttys019  123:31.50 ./bin/openssl.Darwin.x86_64 s_client -quiet -connect 204.216.225.61 563 -servername
    30049 ttys019    0:00.00 grep openssl
    retinambpro1tb:testssl.sh jeroenp$ kill 27822
    retinambpro1tb:testssl.sh jeroenp$ ./testssl.sh --version
    ###########################################################
        testssl.sh       2.6rc3 from https://testssl.sh/dev/
        (90db7a5 2015-08-27 23:06:06 -- 1.361)

**Comment by drwetter** [comment]
Hi @jpluimers

thx. It is a common Unix feature that you see what other processes are being called -- or do I understood you wrong?

Cheers, Dirk

**Comment by drwetter** [comment]
Last call especially to all Darwin users ;-)

**Comment by jpluimers** [comment]
Sorry for getting back so late. I've been really occupied with some other things. You understood me wrong: the `ps -ax | grep openssl` shows that after `testssl.sh` is finished, there are still `openssl` processes running (usually using a core of CPU).

I usually only note this when the fan starts spinning (which often is taking a very long time, so it is hard to track which the parent process could have been).

**Comment by drwetter** [comment]
Ok, out of the top of my head I can't imagine a condition when it happens as all background processes will be either killed after a timeout or the process terminated by itself.

If you happen to stumble over this again it would be great if you could catch the command line and the maybe try to reproduce it.

**Comment by jpluimers** [comment]
The statements I listed would sometimes reproduce it, but I've not seen it recently. Maybe the current version is more stable?

**Comment by drwetter** [comment]
Sorry, I overlooked yesterday your posting from ~20 days ago. I can't reproduce that under Linux or BSD. 

If it's reproducible under Darwin please file a separate issue.

**Comment by jpluimers** [comment]
Will do. Tried reproducing it again, cannot reproduce. If it happens again, I will file a new issue.
