### ISSUE TITLE
individual --jsonfile-pretty files with --mode parallel doesn't print header

### ISSUE THREAD

**Issue by 8zero2** [drwetter/testssl.sh#1600]
Awesome Script.

Trying to take output of domains in different json file in parallel mode
file looks like 
--jsonfile-pretty xxxx --openssl-timeout 5 --warnings off xxxx.xx.xx
--jsonfile-pretty yyyy --openssl-timeout 5 --warnings off yyyy.yy.yy

the json files do not have header printed and start with
"pretest"           : [
                            {
                                "id"           : "pre_128cipher",
                                "severity"     : "INFO",
                                "finding"      : "No 128 cipher limit bug"
                           }
                    ],
..
..
..
..

Am i missing something?

**Comment by dcooper16** [comment]
Hi @8zero2 ,

This is a limitation based on the way that testssl.sh is implemented.

What I would suggest is to change your test file to be just
```
xxxx.xx.xx
yyyy.yy.yy
```
and then make your command line
```
testssl.sh --json-pretty --openssl-timeout 5 --parallel --file <testfile> --warnings off
```
or
```
testssl.sh --jsonfile-pretty <resultsdir> --openssl-timeout 5 --parallel --file <testfile> --warnings off
```
This will give you the results you want, it's just that testssl.sh will create the names for the JSON files. With the second option, the JSON files will be placed in \<resultsdir\>.

**Comment by 8zero2** [comment]
Okay closing, I wanted different directories for different domains. Going for external forking. 

Will ask for help if I get stuck somewhere.
