### ISSUE TITLE
brotli support

### ISSUE THREAD

**Issue by 532910** [drwetter/testssl.sh#1605]
Please add brotli support.
It should show the same BREACH warning for brotli as for gzip and deflate.

**Comment by drwetter** [comment]
Thanks for the hint!

PR for the 3.0 branch is waiting to be merged. I think brotli compression is old enough to not only make it available for 3.1dev.

For 3.1dev there will be during the next days an improved version which lists also all compressions.

**Comment by drwetter** [comment]
closing this. See PR #1636 .

Thanks for speaking out loud :-)
