### ISSUE TITLE
Potential issue: beginend.net gets A on ssllabsl, but red on testssl.sh

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#161]
A rated here: https://www.ssllabs.com/ssltest/analyze.html?d=beginend.net

But testssl.sh lists `Secure Renegotiation (CVE 2009-3555)      VULNERABLE (NOT ok)`, why is that?

Note testssl.sh also doesn't test the IPv6 addresses. <strike>Should I post another issue for that?</strike> Known issue: #11 

Extract from log:

    testssl.sh       2.6rc1 from https://testssl.sh/dev/
    (7f97e8b 2015-08-14 13:34:45 -- 1.344)
    ....
    Secure Renegotiation (CVE 2009-3555)      VULNERABLE (NOT ok)
    ....
    Done now (2015-08-15 09:38) ---> 104.27.168.133:443 (beginend.net) <---
    ....
    Secure Renegotiation (CVE 2009-3555)      VULNERABLE (NOT ok)
    ....
    Done now (2015-08-15 09:38) ---> 104.27.169.133:443 (beginend.net) <---
    ....
    Done testing now all IP addresses (on port 443): 104.27.168.133 104.27.169.133

I've tested using the below systems. Apart from zlib (which is not in the Darwin openssl binary), they gave identical results.

- Linux revue 4.1.3-2-default #1 SMP Wed Jul 29 09:47:55 UTC 2015 (41613e2) x86_64 x86_64 x86_64 GNU/Linux
- Darwin RetinaMBPro1TB.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

Full logs:

- Linux opensuse log: https://gist.github.com/jpluimers/e13bd1e6b0d1253a5034
- Darwin Mac OS X log: https://gist.github.com/jpluimers/0f42d58a920b96a7d362

**Comment by drwetter** [comment]
oh yes, cloudflare. Fix follows.

**Comment by drwetter** [comment]
forgive me: Thanks a lot for your bug report and careful scrutinzing results!

**Comment by jpluimers** [comment]
Thanks. Confirmed as fixed.
