### ISSUE TITLE
How Do You Check For TLS 1.3 On Mac?

### ISSUE THREAD

**Issue by mydigia** [drwetter/testssl.sh#1613]
Hi,
I've noticed you test against TLS 1.3, but I can see the openssl binary doesn't support that. Without digging your impressive lines of code, may I please ask how you test against 1.3 on Mac/Darwin?
Thank you.

**Comment by drwetter** [comment]
Hi there,

we use bash sockets which enables us to send (TCP) packets directly over the network.

The binary is a helper for some (remaining) tasks which we cannot do otherwise. 

Cheers,.Dirk



-- 
Sent from my mobile. Excuse the autocorrection, my brevity&typos
