### ISSUE TITLE
Reverse Proxy banner output alignment is off by one

### ISSUE THREAD

**Issue by jonorossi** [drwetter/testssl.sh#162]
Looks like you purposely removed a space in front of the value in b3f65f18ae603976747c0fb6a821e0818aee07eb, however it used to be aligned but now isn't for me.

```
...
 Application banner           X-UA-Compatible: IE=Edge,chrome=1
 Cookie(s)                    2 issued: 2/2 secure, 2/2 HttpOnly
 Security headers             X-Frame-Options: deny
                              X-XSS-Protection: 1; mode=block
                              X-Content-Type-Options: nosniff
                              Content-Security-Policy: ...
 Reverse Proxy banner        --
                             ^
```

Platform: darwin

**Comment by drwetter** [comment]
Thx, @jonorossi .

In fact I did remove it because it was "an off by one" in the other direction. You have an example for me (pls also tell me your client platform).

Cheers, Dirk

**Comment by jonorossi** [comment]
Sorry, was going to include that platform, didn't think it was needed for this. On OSX/darwin again.

**Comment by drwetter** [comment]
Thx.

Is that only when the RP banner is empty?

**Comment by jonorossi** [comment]
Do I need a proxy set up to get that to report something via one of those HTTP headers?

**Comment by drwetter** [comment]
Nope, in general this would be proxies on the server side which are being detected here.

But as on Linux I actually I spotted the same I assume it is not a Darwin/BSD/Linux issue.

**Comment by jonorossi** [comment]
Oh, I just saw `X-Squid` in the list and jumped to a conclusion. You said you've reproduced it already, but just for completeness sake, it looks right with a reverse proxy detected, however you might have meant the two different headers to be on separate lines:

```
$ ./testssl.sh www.varnish-cache.org
...
--> Testing HTTP header response @ "/"

 HTTP Status Code             200 OK
 HTTP clock skew              -5 sec from localtime
 Strict Transport Security    --
 Public Key Pinning           --
 Server banner                nginx
 Application banner           X-Powered-By: PHP/5.3.10-1ubuntu3.19
 Cookie(s)                    (none issued at "/")
 Security headers             --
 Reverse Proxy banner         X-Varnish: 1950527140 1950283864   Via: 1.1 varnish  
...
```

**Comment by drwetter** [comment]
fix for the missing leading trail follows in a sec, also the suggested line feed.

Thx!
