### ISSUE TITLE
Public Key Pinning output text runs into itself

### ISSUE THREAD

**Issue by jonorossi** [drwetter/testssl.sh#163]
I didn't submit a PR because I'm not sure whether it was intended that the "No matching key for pin found" should be a new line or something else:

```
$ ./testssl.sh github.com
...
 Public Key Pinning           # of keys: 2, 59132803691015 days=300256979418256560368 s, includeSubDomainsNo matching key for pin found (CA pinned?)
                                                                                                          ^
...
```

Platform: darwin

**Comment by drwetter** [comment]
confirmed, thx for reporting. Will look into it.

**Comment by drwetter** [comment]
Fix follows.

Github is kind of special
1) max-age is 5 minutes -- that's not enough
2) at least the host cert and issuing CA keys don't match the pins (haven't checked higher CAs in the tree though)
