### ISSUE TITLE
Certigna Services Root CA not in Java store

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1648]
For www.anssi.fr there is (confirmed) the Root CA https://crt.sh/?q=+e3b6a2db2ed7ce48842f7ac53241c7b71d54144bfb40c11f3f1d0b42f5eea12d
missing in the Java keystore.

Task: Look for update. If not available: think about an exception. 

It seems the root CA is commonly used for certificates in France.

**Comment by Niko78** [comment]
hi,
any news about that ?
thx
Nico

**Comment by drwetter** [comment]
My time is limited at the moment. 

A quick shot though with the Java socket client  I have here shows under e.g. Debian 10 no problem connecting. Not sure though whether this exclusively use the Java keystore and not the ca-certificates package from Debian.

Other than that:  My idea would be to provide an exemption for certain certificates not in the Java store. I would suggest to still raise the arm if a CA is not in the Java store as there's a technical problem but  I would not suggest to penalize the trust  in the rating.

Anybody care to help?
