### ISSUE TITLE
[Feature request] warning when a cert in the chain is about to expire

### ISSUE THREAD

**Issue by rasschaert** [drwetter/testssl.sh#1653]
Sectigo's "AddTrust" root certificate [famously expired recently](https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020).

I was one of  the many sysadmins that was caught off guard by this, since it never even occurred to me that a CA would issue a certificate for a certain duration and would accompany it with certs that have a _shorter_ validity duration.

This has mostly been reported as a client side issue, because Sectigo cross-signed the affected certificates with a more modern root that is still valid until 2038. If all clients had this more modern CA in their trust store, there wouldn't have been an issue at all.

While this is true, it did lead to a situation where clients were able to connect to my servers on May 30th and were unable to on June 1st. I had no idea this was about to happen and had to scramble to figure out solutions.

In an effort to never be caught off guard by this again, I'm looking to expand my monitoring toolset and first thought to check out testssl.sh, which has been tremendously valuable to me in the past.

I still have one non-production server with the old chain, and sure enough, testssl.sh correctly detects the issue and downgrades my rating:

` Chain of trust               NOT ok (expired)`

`
 Final Score                  0
 Overall Grade                T
 Grade cap reasons            Grade capped to T. Issues with certificate (expired)
`
Fantastic.

Using an Ubuntu VM where I changed to clock to May 29th, I essentially went back in time to 1 day before the AddTrust root expired. Now, testssl.sh reports no warning on the chain of trust.

` Chain of trust               Ok`

`
 Final Score                  96
 Overall Grade                A+
`

It's not _wrong_, the chain was still valid at that time.

I think that it would be tremendously useful if testssl.sh would print out the individual expiration dates of the certificates in the chain, and would check if they expire in the next 60 days, the same way that it already does for the leaf certificate.

[According to security researcher Scott Helme](https://scotthelme.co.uk/impending-doom-root-ca-expiring-legacy-clients/) there are more root CA certificates that will expire in the near future, so this might save sysadmins from being blindsided.

**Comment by drwetter** [comment]
Hi @rasschaert ,

yes, you're right. In fact somehow others requested it, see #1264 / #1004.

It shouldn't be too difficult. Actually for the root certificates they are all there. The others will be retrieved from the server.

Cheers, Dirk

**Comment by rasschaert** [comment]
I'm sorry for creating a duplicate issue. I had tried searching but apparently not with the right search terms.

**Comment by drwetter** [comment]
Never mind. That brings it more to attention.:-)  Also citing the Sectigo story emphasizes the importance. 

Thanks!

**Comment by drwetter** [comment]
availability for OCSP server should be checked as well then. Sometimes they have been reported not being available (cc @hannob)

**Comment by drwetter** [comment]
The expiration date handling is a chunk of code in there which tries to do its best for old OpenBSD's ``date``, FreeBSD's ``date`` (which is similar to newer OpenBSD's ``date``) and GNU ``date``.

The ``certificate_info()`` function has grown historically. It's somewhat a pain to add a larger portion of code there which will add again redundant lines. 

Practically speaking we can't reinvent/rewrite  ``certificate_info()``, OTOH we should not add more redundant code. Best solution would be to have a separate function for the expiration date check

**Comment by drwetter** [comment]
fixed
