### ISSUE TITLE
# of certificates provided always reports 0

### ISSUE THREAD

**Issue by jonorossi** [drwetter/testssl.sh#167]
Maybe I misunderstand what this field is for, but I thought it would report 3 most the time. e.g. the CA cert, intermediate server CA cert, and server cert:

```
$ ./testssl.sh testssl.sh
...
 Fingerprint / Serial         SHA1 AA5FF6B618DB64D962505B4B22F65C21A3560E7F / 053F29F0E45CA1
                              SHA256 FDAB2063E38C2165A0B7471F15D86540CFCDF0D4C5EB2A67F474B2773CDB64C8
 Common Name (CN)             dev.testssl.sh (CN in response to request w/o SNI: default.name)
 subjectAltName (SAN)         
 Issuer                       StartCom Class 1 Primary Intermediate Server CA (StartCom Ltd. from IL)
 EV cert (experimental)       no 
 Certificate Expiration       >= 60 days (2015-02-20 16:51 --> 2016-02-21 05:06 +1000)
 # of certificates provided   0
...
```

https://github.com/drwetter/testssl.sh/blob/5c0559042f1ea891b158b97b0afb1c2093bb56a6/testssl.sh#L1852-L1855

Platform: darwin

**Comment by drwetter** [comment]
Keep on reporting pls. I am offline now.

**Comment by jonorossi** [comment]
@drwetter will do. I'm glad you didn't say bugger off, you are reporting too many minor things :wink:.

**Comment by drwetter** [comment]
Am 17. August 2015 09:45:02 MESZ, schrieb Jonathon Rossi <notifications@github.com>:
>@drwetter will do. I'm glad you didn't say bugger off, you are
>reporting too many minor things :wink:.

Naa, others say sometimes I am picky but I really like things to work correctly. testssl.sh is not exempt from this. ;)

Cheers, Dirk

**Comment by drwetter** [comment]
Thx!
