### ISSUE TITLE
Clarification on "INFO" severity 

### ISSUE THREAD

**Issue by jandradas** [drwetter/testssl.sh#1675]
Some of the checks done by testssl.sh result in the "severity" reported in the CSV and JSON output as "INFO", when the rest of the output seems to indicate it should be "OK" and that there is no issue with the identified configuration (or otherwise it might not be clear why the result is flagged as "info" instead, e.g. if combination with other results make it worth raising an issue with informational severity)

Some examples are the protocols section:   

```
,         {
              "id"           : "SSLv3",
              "ip"           : "192.168.25.86/192.168.25.86",
              "port"         : "443",
              "severity"     : "OK",             <--- This is fine.  No SSLv3 is a 'good' finding, thus 'OK'.
              "finding"      : "not offered"   
          }
,         {
              "id"           : "TLS1",
              "ip"           : "192.168.25.86/192.168.25.86",
              "port"         : "443",
              "severity"     : "INFO",               <--- I don't fully understand this. Not offering TLSv1.0, for me, is a 'good' finding, but I don't understand why this is flagged as "INFO" instead of "OK".
              "finding"      : "not offered"
          }
,         {
              "id"           : "TLS1_1",
              "ip"           : "192.168.25.86/192.168.25.86",
              "port"         : "443",
              "severity"     : "INFO",              <--- Same as above, but with TLSv1.1.  I think not having this is a good finding.
              "finding"      : "is not offered"
          }
,         {
              "id"           : "TLS1_2",
              "ip"           : "192.168.25.86/192.168.25.86",
              "port"         : "443",
              "severity"     : "OK",              <--- This is fine.  Offering TLSv1.2 is 'good' finding, thus 'OK' make sense.
              "finding"      : "offered"
          }
,         {
              "id"           : "TLS1_3",
              "ip"           : "192.168.25.86/192.168.25.86",
              "port"         : "443",
              "severity"     : "INFO",              <--- I understand this makes sense... Ideally, they should support TLSv1.3, so not having supported is worth mentioning, but it is not a security issue in itself (at least not yet), so "INFO" makes sense for me here.
              "finding"      : "not offered + downgraded to weaker protocol"
          }
```

I also identified this behavior in the ciphers section: 

```
{
              "id"           : "cipherlist_3DES_IDEA",
              "ip"           : "192.91.91.169/192.91.91.169",
              "port"         : "5060",
              "severity"     : "INFO",            <-- If these weak ciphers are not offered, why is it not "OK" instead? 
              "cwe"          : "CWE-310",
              "finding"      : "not offered"
}
```

**Comment by dcooper16** [comment]
Take a look at the "Color Rating" section in the documentation: https://github.com/drwetter/testssl.sh/blob/3.1dev/doc/testssl.1.md.

It explains that "INFO" is not an indication that there is a problem (i.e., that something is not OK). It just means that the "finding" is providing information that isn't an indication of something either good or bad.

**Comment by drwetter** [comment]
In addition: OK means also good or best (green colors) as we don't have that positive indicator in JSON.

**Comment by jandradas** [comment]
Thank you for your comments and clarifications.  In the text referenced above by @dcooper16 I read:

> no color at places where also a finding can be expected: a finding on an info level

From the above I had not interpreted what both @dcooper16 or @drwetter mentioned regarding the 'severity' in JSON or CSV.  However, with the clarifications set forth in this issue, I understand better the meaning.  My (new) interpretation could be summarized in:

* "OK" severity are findings that are good, usually because the contrary would be a high or critical finding (these correspond to green or light green in the normal output)
* "INFO" provides information on a finding.  It normally is a 'good' finding (e.g. not having TLS 1.0 or TLS 1.1, or not using 3DES or IDEA ciphers, which, if present, would be an issue that is not high or critical.

Thus, from a "parsing-the-CSV-or-JSON-for-issues" perspective, I would assume "OK" and "INFO" are equivalent, meaning there are no issues worth raising/reviewing.   

Thank you!
