### ISSUE TITLE
json output doesnt include all Rating data

### ISSUE THREAD

**Issue by gord0b** [drwetter/testssl.sh#1679]
0. Did you check the documentation in ~/doc/ or, if it is a different problem: Did you google for it?
Yes

1. uname -a
Linux w1sp3r 5.6.0-kali1-amd64 #1 SMP Debian 5.6.7-1kali1 (2020-05-12) x86_64 GNU/Linux
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
testssl.sh       3.1dev from https://testssl.sh/dev/
(41ac04e 2020-07-10 19:56:53 -- )

3. git log | head -1 (if running from git repo)
N/A

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
/bin/openssl.Linux.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
Output using -oJ, --jsonfile, --jsonfile-pretty & -oj command, for .json output, are missing the full 'Rating' output.
Only data received in json is below;
"rating"            : [
                            {
                                "id"           : "rating_spec",
                                "severity"     : "INFO",
                                "finding"      : "SSL Labs's 'SSL Server Rating Guide' (version 2009q from 2020-01-30)"
                           },{
                                "id"           : "grade",
                                "severity"     : "OK",
                                "finding"      : "A"
                           },{
                                "id"           : "grade_cap_reason_1",
                                "severity"     : "INFO",
                                "finding"      : "Grade capped to A. HSTS is not offered"
                           }
                    ]

6. what exactly was happening, output is needed
Full output of 'Rating' is included in the below .html output;

Rating specs (not complete)  SSL Labs's 'SSL Server Rating Guide' (version 2009q from 2020-01-30)
Specification documentation  https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide
Protocol Support (weighted)  100 (30)
Key Exchange     (weighted)  90 (27)
Cipher Strength  (weighted)  90 (36)
Final Score                  93
Overall Grade                A
Grade cap reasons            Grade capped to A. HSTS is not offered

7. what did you expect instead?
The below data is missing from the .json output, but is included in the .html output;

 Specification documentation  https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide
 Protocol Support (weighted)  100 (30)
 Key Exchange     (weighted)  90 (27)
 Cipher Strength  (weighted)  90 (36)
 Final Score                  93

**Comment by drwetter** [comment]
Makes sense. Thanks for reporting!

cc @magnuslarsen

**Comment by magnuslarsen** [comment]
I am quite busy atm, but I'll take a look at it this weekend!

**Comment by gord0b** [comment]
appreciate the effort folks
