### ISSUE TITLE
Color highlighting of HTTP header fields are broken by punctuation

### ISSUE THREAD

**Issue by jonorossi** [drwetter/testssl.sh#168]
There is a mix of light and dark yellow when there are `/`, `:` or `.` in the value. I've seen this with other servers:

```
./testssl.sh www.varnish-cache.org
```

![screen shot 2015-08-17 at 5 55 39 pm](https://cloud.githubusercontent.com/assets/126297/9300433/382a6f8a-4509-11e5-84bd-e0bfa9dc9844.png)

Platform: darwin

**Comment by jonorossi** [comment]
FYI, looks like the green output works for well "Security headers".

**Comment by drwetter** [comment]
Am 17. August 2015 09:59:05 MESZ, schrieb Jonathon Rossi <notifications@github.com>:
>There is a mix of light and dark yellow when there are `/`, `:` or `.`
>in the value. I've seen this with other servers:
>
>```
>./testssl.sh www.varnish-cache.org
>```
>
>![screen shot 2015-08-17 at 5 55 39
>pm](https://cloud.githubusercontent.com/assets/126297/9300433/382a6f8a-4509-11e5-84bd-e0bfa9dc9844.png)
>
>Platform: darwin

Need to look at it on computer to understand your point.

The color scheme is most of the time on purpose though admittedly not described good enough. Here numbers have another markup as some headers itself, e.g. version numbers are always something one can avoid.


Thx, Dirk


-- 
Sent from my mobile

**Comment by drwetter** [comment]
You mean all should be one color in "5.3.10-1ubuntu3.19"?

If so: hard to mark also dashes and points here. I am afraid if I provide a regex I am marking more than I want -- but I am happy for any suggestion here. Please confirm whether you meant this.

I did NOT label PHP in yellow PHP is 99% of the time easily spotted by the cookie or file extension.

I DID label ubuntu in yellow as that piece of information is unneccessary I would not divulge.

**Comment by jonorossi** [comment]
Sorry, I should have looked more closely at `emphasize_stuff_in_headers`. I didn't notice that `[0-9]` was being purposely coloured brown, it just looked like it was broken because it was strange looking.

Is the intention that version numbers without any text can expose details of the server running because the version number could be unique to a specific server software, or at least pinpoint what vulnerabilities to target?

**Comment by drwetter** [comment]
>Is the intention that version numbers without any text can expose details of the server running 
> because the version number could be unique to a specific server software, or at least pinpoint what > vulnerabilities to target?

yes. Any number is  IMO an insecure default or at least an verbosity which is futile.

**Comment by jonorossi** [comment]
Thanks, even though it looks a bit strange at first it makes sense and I'm happy, there is no defect or enhancement to be made here. Closing.
