### ISSUE TITLE
Check for expired intermediates in chain

### ISSUE THREAD

**Issue by hannob** [drwetter/testssl.sh#1683]
Recently there was an issue where an expired intermediate cross certificate caused failures with some clients[1][2].

Testssl could check all intermediates in the chain for their expiration date (+maybe even warn if expiration is happening soon).

Here's a test host for the addtrust incident that can be used for testing:
addtrust-chain.demo.sslmate.com

[1] https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration
[2] https://www.feistyduck.com/bulletproof-tls-newsletter/issue_66_expired_addtrust_certificate_causes_trouble

**Comment by hannob** [comment]
Sorry, this looks like a duplicate of  #1653

**Comment by drwetter** [comment]
No problem that's a duplicate. Keep's it better in mind.

**Comment by drwetter** [comment]
@hannob : while you're here: what would your opinion on severity (except an expired intermediate which is labeled as critical)

**Comment by hannob** [comment]
On the one hand it's not really a security risk, it's only more data sent than necessary and may cause incompatiblities with some (bad) clients. On the other hand... there's not really a reason not to fix it, so...

What that reflects in your severity levels you have to decide...

**Comment by drwetter** [comment]
Well, the risk is that all of a sudden people can't visit the web site any more (if there's one chain only). So there's something imminent which deserves attention. And it should raise a flag. Currently it's set to < 20 days: high. < 40 days: medium. 

At the moment this is fixed. Maybe the remaining time of the host certificate should be taken into account too

@ all: Any other opinion?

**Comment by hannob** [comment]
Ok I think we have 2 different situations here that this might cover.

One is the addtrust situation. The situation was a 2 cert chain where one cert allowed a chain to an older root, but was at some point expired. This is "mostly harmless", except not really, because many clients can't handle it.

The other would be a situation where the only valid root is via an intermediate that will soon expire (whcih we'll probably have some point next year with let's encrypt). That would be a more intermediate concern.

But I guess it's okay to treat them the same, a logic to separate these would probably be complex

**Comment by drwetter** [comment]
The determination of an "only valid root" is not clear to me and how e.g. SSLlabs is pulling another chain to the leaf cert out of their pocket. At the moment testssl.sh checks only one chain.

The intermediate check is merged now, fine tuning will follow some time
