### ISSUE TITLE
List as External/related project in Readme.md

### ISSUE THREAD

**Issue by gord0b** [drwetter/testssl.sh#1689]
_Please could you review to include the below details in the 'List as External/related projects' in Readme.md;_

Brand new free web application that was just recently completed.
Utilizes testssl.sh for scanning, output.
Utilizes ElasticSearch for data storage.
API only accessible via authorized access.

Thank you.

Details to review/include below;
________________________________
**Inspect: Webapp & API using testssl.sh**

- https://inspect.rapydblok.com
- https://api.rapydblok.com/ssl
________________________________

**Comment by drwetter** [comment]
Hi @gord0b,

didn't you read the Readme.md?

```
Attribution is important for the future of this project -- also in the internet. Thus if you're offering a scanner based on testssl.sh as a public and/or paid service in the internet you are strongly encouraged to mention to your audience that you're using this program and where to get this program from. That helps us to get bugfixes, other feedback and more contributions.
```

There might be a license change in the future (like AGPL) to make that mandatory. Last but no least GPLv2 wasn't really written in a time where the internet was where it is now.

Thanks, Dirk

**Comment by gord0b** [comment]
Hi @drwetter 

I did take note of the Readme.md. The license details are noted in multiple areas on the web app, web app is also free (non-paid).

My aim is to respect all licenses, assist people in securing TLS/SSL and also let people gain knowledge around security & scripts like testssl.sh to assist. The web app was created to make it easier for people to do this & hopefully create some awareness. 

_If you would like me to edit, add or change the info please advise._

**The GPL license noted in the following areas;**
**1:** https://inspect.rapydblok.com/about page
![image](https://user-images.githubusercontent.com/34238250/90109107-9fb5d100-dd4b-11ea-9a68-439e6e36bb7b.png)

**2:** RAW tab on the output/results page, at bottom, https://inspect.rapydblok.com/search?host=https://inspect.rapydblok.com
![image](https://user-images.githubusercontent.com/34238250/90109282-e1467c00-dd4b-11ea-995f-9139b59af4ab.png)

**3:** API call https://api.rapydblok.com/ssl
![image](https://user-images.githubusercontent.com/34238250/90109388-076c1c00-dd4c-11ea-8d8e-b96b9c5a5462.png)

**Comment by drwetter** [comment]
Apologize! You just pointed me to places where I couldn't see that immediately. Admittedly I missed the patience to click around. See PR.

Be careful with input, also from the server side. While we do filter a very lot and at least I think I'll have a reasonable security background, we cannot guarantee that it is 100% solid, I am just trying to be due diligent. Therefore one would have to inspect the code very thoroughly for that.

Good luck!

Cheers, Dirk

PS: If enough money comes in from the API, this project could have some funding -- happy to issue an invoice in return.

**Comment by gord0b** [comment]
@drwetter - Thank you, currently bootstrapped all the dev but if any funding comes thru i will fund back to testssl for sure. Have a good weekend.
