### ISSUE TITLE
Forward secrecy differences to ssllabs

### ISSUE THREAD

**Issue by jonorossi** [drwetter/testssl.sh#169]
Running against `mailgun.com`, I found that testssl.sh reports all good (i.e. it is offered), while ssllabs reports not supported for reference browsers. Both test runs report many ECDHE ciphers. Could this be because the server doesn't provide a cipher order?

**Comment by drwetter** [comment]
Nope, the missing cipher order has nothing to do with at least the view of testssl.sh.

What is missing in testssl.sh is a set of each browser ciphers being thrown in the client handshake at the server and then look whether there's a match for each browser.

Testssl.sh gives you the PFS ciphers but can't tell yet which browser supports them, see #98 .

BTW: In this case given the market share of IE I would be a bit more optimistic e.g. "FS: supported by most browsers".

**Comment by jonorossi** [comment]
Thanks for the info, makes sense.
