### ISSUE TITLE
HTTP check issues

### ISSUE THREAD

**Issue by PeterMosmans** [drwetter/testssl.sh#170]
On Windows 64 bit (8.1), using MSYS2 with openssl-1.0.2-chacha (1.0.2e-dev), the HTTP check doesn't seem to be functioning:
```
Service detected:       Couldn't determine what's running on port 443, assuming no HTTP service, skipping HTTP checks
```

tested using 

```
./testssl.sh www.onwebsecurity.com 
```

**Comment by drwetter** [comment]
Thx, Peter. 

FYI: Doesn't occur on Linux.

**Comment by drwetter** [comment]
Hi @PeterMosmans,

can't reproduce it on Windows 7 64 bit. :-/ Can you send me any debugging output? 

``script``, run ``bash --debug=1 -vx testssl.sh -H www.onwebsecurity.com ``, ``exit``.

Thx, Dirk

**Comment by PeterMosmans** [comment]
Will do (later on...)

Cheers,

Peter

**Comment by drwetter** [comment]
Hi @PeterMosmans,

did you have any chance yet for giving me input? This and a binary rearrangement are as of today the only showstoppers for the 2.6 release.

Cheers, Dirk

**Comment by PeterMosmans** [comment]
currently working on it.. ;)

**Comment by PeterMosmans** [comment]
Well ain't this weird - with the latest version HTTP gets detected. In other words: false positive.
Thanks for.. solving this ? ;)

Cheers,

Peter

**Comment by drwetter** [comment]
Yes, there has been some changes. Wasn't sure however whether that affected it...

Thx anyway. Better false positive than false negative ;-)
