### ISSUE TITLE
Chain Certificate Issue

### ISSUE THREAD

**Issue by sonawanesarvesh** [drwetter/testssl.sh#1700]
Hello

I am scanning internal corporate URLs using TestSSL, but every time i am getting Certificate Chain Issue
Chain of Trust - NOT OK (Chain Incomplete)

- Chain of trust               NOT ok (chain incomplete)
-  EV cert (experimental)       no
-  Bad OCSP intermediate (exp.) Ok
-  ETS/"eTLS", visibility info  not present
-  Certificate Validity (UTC)   expires < 60 days (58) (2017-10-12 10:58 --> 2020-10-11 10:58) 825 days certificate life time but issued before 2018/03/01
-  of certificates provided   2

But when i see it in Browser - I see its valid certificate

- Root CA Certificate
- Issuer CA Certificate

I understand that browser might be automatically using the Cached Certificate or something like that, so how can we provide / proxy this certificate to Testssl or i am not sure how to make work around this issue

**Comment by dcooper16** [comment]
If the browser is showing the path as root CA, issuer CA, server's certificate, and testssl.sh indicates that the server is providing 2 certificates, then most likely the issue is that the certificates were issued from an internal corporate PKI. I would guess that your browser has been configured to accept certificates issued by this internal PKI.

For testssl.sh, see the `--add-ca` option in https://github.com/drwetter/testssl.sh/blob/3.1dev/doc/testssl.1.md. The \<cafile\> should include a PEM encoded copy of the root CA certificate for this path.

**Comment by sonawanesarvesh** [comment]
Thanks for great help, it worked :)

**Comment by sonawanesarvesh** [comment]
Hello,

Further addition to this problem - 

I have added two certificates Root & CA - and i am able to successfully scan the internal URL -  no chain issue is found  - it went perfect- thanks for help

1. Now there is DEV environment where the URL is  = www.example.dev.com/some_path.svc

2. When accessing the **www.example.dev.com** only - it asks for authentication but when accessing complete URL **www.example.dev.com/some_path.svc** there is no authentication required and i can see results of this complete URL

3. So when i used the same two PEM files and scanned both (main URL = www.example.dev.com) & (complete URL = www.example.dev.com/some_path.svc) - i am getting following certificate chain issue


- Chain of trust               NOT ok (chain incomplete)
-  EV cert (experimental)       no
-  Bad OCSP intermediate (exp.) Ok
-  ETS/"eTLS", visibility info  not present
-  Certificate Validity (UTC)   711 >= 60 days (2020-05-08 04:43 --> 2022-07-27 04:43)
-  **No of certificates provided   1**


Here at end you can see, it detect only 1 certificate and not two certificates
So wanted to know 
1. What is difference between scanning complete URL & only main URL
2. is because of authentication 1 certificate is gone missing?

**Comment by drwetter** [comment]
> When accessing the www.example.dev.com only - it asks for authentication

Http basic auth?

In any case there's no difference with respect to the certificate numbers whether you scan the hostname or a complete path.

The path might only give you different server and/or application headers.

**Comment by sonawanesarvesh** [comment]
Hello
Thanks for quick response

1. Its not basic authentication - its SSO type of authentication - do testssl support passing arguments in SSO (multiple authentication header values)
2. I am getting certificate count difference when scanning only hostname vs scanning complete URL - 

A) Complate URL 
Chain of trust               NOT ok (chain incomplete)
EV cert (experimental)       no
Bad OCSP intermediate (exp.) Ok
ETS/"eTLS", visibility info  not present
Certificate Validity (UTC)   711 >= 60 days (2020-05-08 04:43 --> 2022-07-27 04:43)
No of certificates provided   1

B) Only Hostname - 
Chain of trust               Ok
EV cert (experimental)       no
Bad OCSP intermediate (exp.) Ok
ETS/"eTLS", visibility info  not present
Certificate Validity (UTC)   744 >= 60 days (2020-06-10 05:28 --> 2022-08-29 05:28)
No of certificates provided   2

Seems like certificate validity also got changed - is it indicating totally different certificate... now i am bit confused :(
But even when i passed two certificates still its displaying only 1 certificate provided in case A)

**Comment by drwetter** [comment]
Please double check = compare the ~~URLs~~ hostnames. 

Testssl.sh is completely agnostic whether you use SSO (OAUTH2 / SAML / whatsoever) -- as long as you test the originating server of the SSO request and the auth part is just an appended redirect. Testssl.sh also doesn't follow redirects.

Why don't you look at the DNs / CNs (and SAN) of A) and B) and ask internally where those certificates have been deployed?

**Comment by sonawanesarvesh** [comment]
Hello 
Thank you for quick responses, i really appreciate 

My main problem in understanding is - 
my command is  =  ./testssl.sh -S --add-ca root_cert.pem,ca_cert.pem https://example.qa.test.com

So i am passing two certificates even tried passing 3 certificates using - 
./testssl.sh -S --add-ca root_cert.pem,ca_cert.pem,ssl_cert.pem https://example.qa.test.com

Still the report says - 
 Chain of trust               NOT ok (chain incomplete)
 EV cert (experimental)       no
 Bad OCSP intermediate (exp.) Ok
 ETS/"eTLS", visibility info  not present
 Certificate Validity (UTC)   748 >= 60 days (2020-06-17 02:00 --> 2022-09-05 02:00)
 **No of certificates provided   1**

why it is not detecting other two provided certificates?  - I am checking the above last line - No of certificates provided - am i right?

**Comment by dcooper16** [comment]
> why it is not detecting other two provided certificates?

"No of certificates provides" indicates the number of certificates provided by the server. It just counts the number of certificates sent by the server, even if the server is sending certificates that can't be used to validate the server's TLS certificate.

**Comment by sonawanesarvesh** [comment]
Ohh.. ok

Now again i am at same level - 

DEV Environment - 
./testssl.sh -S --add-ca **root_cert.pem,ca_cert.pem** https://example.dev.test.com

QA Environment
./testssl.sh -S --add-ca **root_cert.pem,ca_cert.pem** https://example.qa.test.com

For both above environment  root and CA certificate is same, so i provided it to command

But - i see chain issue only for QA Environment

**Comment by sonawanesarvesh** [comment]
Hello
Update, i observed my organization is using different root and CA certificates for DEV and QA Environment, and this resolves my issue :)

Thanks for the continues support

Just wanted to know - can i copy all the certificates from my machine to somewhere in testssl folder and just give the path of that folder in --add-ca (or some other parameter) so that everything automatically from the list of certificates testssl will pick the correct certificate for internal URLs and solves the purpose.... am i am asking too much or its already provided feature?

**Comment by dcooper16** [comment]
> Just wanted to know - can i copy all the certificates from my machine to somewhere in testssl folder and just give the path of that folder in --add-ca (or some other parameter) so that everything automatically from the list of certificates testssl will pick the correct certificate for internal URLs and solves the purpose.... am i am asking too much or its already provided feature?

The file(s) specified with the `--add-ca` option (or the `ADDTL_CA_FILES` environment variable) can contain a list of certificates. You don't need to have each certificate in a separate file. So, just put all of the certificates in a single file and point to that (see the *.pem files in the etc/ directory for examples).

Another option, if you only care whether servers' certificates can be validated using the certificates on your local machine, would be delete the *.pem files fro the etc/ directory (Apple.pem, Java.pem, Linux.pem, etc.) and then create a new file in the etc/ directory (e.g., Local.pem) that includes all of the root certificates from your machine. Then the chain of trust finding would be based on the certificates on your machine rather than the certificates in these widely-used trust stores.

**Comment by sonawanesarvesh** [comment]
Great... 
This solves my problem... i really appreciate the quick responses

Just if someone gets benefited, so writing below 

1.  I have exported all root and CA certificates into one pfx file each - 
**all_root.pfx & all_ca.pfx**
2. using openssl converted this pfx file into PEM file - 
**openssl pkcs12 -in filename.pfx -out cert.pem -nodes**

3. final command
 **./testssl.sh --assuming-http -q -p -s -f -U -S -P --add-ca all_root.pem,all_ca.pem URL**
