### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CuttlefishJones** [drwetter/testssl.sh#1706]
Hi would it be possible to add the ability to define your own User Agent string?

**Comment by definity** [comment]
+1

**Comment by drwetter** [comment]
sure. ``--user-agent`` would be in line with wget or cURL. 

Any volunteers?

**Comment by definity** [comment]
I will try to do this... what could possibly go wrong 🤣

**Comment by definity** [comment]
Challenge accepted - #1748
