### ISSUE TITLE
Common Name doesn't match notification when it does match

### ISSUE THREAD

**Issue by PeterMosmans** [drwetter/testssl.sh#171]
testssl.sh says that the common name doesn't match when in fact it does match.
Tested using Windows 64-bit 8.1, MSYS2, openssl-1.0.2-chacha (1.0.2e-dev)
```
 testssl.sh       2.6rc2 from https://testssl.sh/dev/
    (5c05590 2015-08-15 21:33:17 -- 1.346)
```

```
Common Name (CN)             www.onwebsecurity.com (CN doesn't match but for non-HTTP services it might be ok)
```

**Comment by drwetter** [comment]
Oh, ok. 

Linux:
```
Common Name (CN)             www.onwebsecurity.com (CN in response to request w/o SNI: pr.otect.me)
subjectAltName (SAN)         www.onwebsecurity.com onwebsecurity.com 
```

**Comment by drwetter** [comment]
This I can reproduce. Will look into it soon. Thx!

**Comment by drwetter** [comment]
Now (after update) I can't reproduce it anymore, sigh. Tried desperately ;-)
![pm](https://cloud.githubusercontent.com/assets/8036727/9462698/c00e6b4a-4b17-11e5-9664-44ac4d489d06.png)

Would you be able to send me debugging output as in #170  mentioned -- after updating to the latest&greatest?

Cheers, Dirk

**Comment by drwetter** [comment]
Was that also solved by the recent changes?

**Comment by PeterMosmans** [comment]
Yep. You're on a roll! :smile:

**Comment by drwetter** [comment]
Cool! Thx
