### ISSUE TITLE
Needed the size of testssl-3.0.tar.gz in https://testssl.sh

### ISSUE THREAD

**Issue by Karibasavaraj** [drwetter/testssl.sh#1716]
Hi,

Please can you let me know the size of testssl-3.0.tar.gz in https://testssl.sh/.

I am getting as 12,77,120 bytes after download.

On windows it shows as 1.21MB. However, I see it mentioned as 1.22MB in https://testssl.sh/

Please can you confirm

Thanks

**Comment by drwetter** [comment]
> I am getting as 12,77,120 bytes after download.

That is almost correct but please have a look where you set the comma.

**Comment by Karibasavaraj** [comment]
Hi,
The comma was taken as displayed from windows machine
On Ubuntu machine we get size as 1277120 for bytes
