### ISSUE TITLE
TLS_FALLBACK_SCSV "unexpected" result when only one protocol is enabled

### ISSUE THREAD

**Issue by Ligushka** [drwetter/testssl.sh#172]
When testing against a server with only one protocol enabled, one receives something like:

TLS_FALLBACK_SCSV (RFC 7507)              test failed, unexpected result , run testssl.sh -Z --debug=1 and look at /tmp/ssltester.JTfJqK/*tls_fallback_scsv.txt

The failure result is expected if only one protocol is enabled. The result can be considered "unknown support", because without more than one protocol enabled, it is not possible to test for the server feature.

**Comment by drwetter** [comment]
Thx for reporting.

**Comment by drwetter** [comment]
Can't reproduce it on a target I know (rechnung.dsl.o2online.de) -- admittedly  the test doesn't make sense then ;-) (it just says ``Downgrade attack prevention NOT supported``).

To be sure to catch also your case: Could you give an example of a case where the error msg occurs?

**Comment by Ligushka** [comment]
Of course - run testssl against wolfemg.com and you should receive the "test failed, unexpected result" error. This server only has TLS 1.2 enabled and nginx is compiled against LibreSSL 2.2.2.

**Comment by teward** [comment]
I did a little bit of cursory hunting.

Using `openssl s_client connect ...` directly worked perfectly, there was no error.

This is the command generated by the master branch.  Ignore the extra string for the OpenSSL executable, I'm using a custom built 1.0.2 based off of the ones listed in this repo: `/usr/local/bin/openssl_1.0.2 s_client  -connect 104.131.160.112:443  -servername wolfemg.com -no_tls1_2 -fallback_scsv`

Running this directly, the output is as follows:

```
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 278 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```

Now, looking deeper into this, a google search for the error has helped me find this question on SuperUser.com, which suggests 104 is `ECONNRESET` for "Connection reset by peer" on Linux - http://superuser.com/questions/297889/does-openssl-errno-104-mean-that-sslv2-is-disabled

So, I went hunting, using the target domain you've listed.  And I ran a wireshark test.  This error we're seeing is generated by an `RST` packet being sent.  The below snippet of my screen is important.

![openssl_errors_observed](https://cloud.githubusercontent.com/assets/327952/9329996/1f975dfe-4584-11e5-8c5a-4ad2f42bab9f.png)

So we have two issues at hand.  First, we *are* getting an unexpected return - an `ECONNRESET`.  Secondly, the specified server from you, @Ligushka, is *sending* that `ECONNRESET`.

I don't think this is the `TLS_FALLBACK_SCSV` handler, but I'm not versed enough in nginx with LIbreSSL to see if that's the problem.  Perhaps this additional information will help.

**Comment by teward** [comment]
Some more insights:

Using nginx 1.8.0 compiled with OpenSSL, locally with valid SSL certs, returns the same situation.  So this may be a case of unexpected handling by the remote server with single protocols being enabled.  Note that I only enabled `tlsv1.2` in that test case.

Adding `tlsv1.1` to the list, `nginx` correctly handles this, so perhaps this is failed handling on `nginx`'s side, rather than this script.

**Comment by PeterMosmans** [comment]
@teward, excuse me, from your posts I didn't understand which OpenSSL build you are using.
The official one (https://github.com/openssl/openssl, or the 1.0.2-chacha fork (https://github.com/PeterMosmans/openssl ) ?
Just to rule out any issues with these..

**Comment by teward** [comment]
@PeterMosmans  I apologize I was imprecise (hadn't had coffee yet).  I'm using your fork, for the `openssl_1.0.2` executable that I run with the testssl script, but the nginx server I am running is the package as exists in Ubuntu 14.04.

**Comment by Ligushka** [comment]
For what it's worth, I also get a similar "unexpected result" for TLS_FALLBACK_SCSV when running "testssl.sh -t imap depechemode-live.com:143" which is a Dovecot 2.2.18 server with only TLS 1.2 enabled, I believe compiled against some version of OpenSSL 1.0.1. I am using this PPA for Dovecot: https://launchpad.net/~malte.swart/+archive/ubuntu/dovecot-2.2

tls_fallback_scsv.txt debug says:

write:errno=104
CONNECTED(00000003)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 331 bytes and written 288 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---

When running this test I also get a "no matching cipher in this list found (pls report this):" message but I can report that as a different issue.

**Comment by drwetter** [comment]
Stacktrace and freied is a bit lame.. err.. could be a bit misleading as a source for wisdom -- so I tracked the error 104 down from the source code (pm's openssl, line 1983 ./apps/s_client.c: get_last_socket_error() --> ./e_os.h --> errno --> .. --> /usr/include/asm-generic/errno.h ``#define ECONNRESET      104     /* Connection reset by peer */``

For TLS 1.2 servers this doesn't come as surprise as ``-no_tls1_2 `` is specified -- wolfemg.com and depechemode-live.com:143.

In general the fallback does only make little sense if one protocol is avaiable: practically there will be none. Theoretically it;s a nice to have as it might tell IF more protocols would be enabled whether there WILL be a fallback.

**Comment by drwetter** [comment]
See changelog.

IN the 2.7dev/2.8 branch this needs to be improved.

**Comment by Ligushka** [comment]
Small typo: https://github.com/drwetter/testssl.sh/commit/d60dadc48cda55ff24dfd6d23c82c168c5bb50ba#diff-2b772c01e86977452d2db64b3031f913R3225
"enexpected" instead of "unexpected".
Otherwise, great!

**Comment by drwetter** [comment]
Thx, will be fixed with the next commit.
