### ISSUE TITLE
ppc64le/Linux binary- do you want one?

### ISSUE THREAD

**Issue by mzpqnxow** [drwetter/testssl.sh#1724]
I use this on an IBM POWER8 machine running Ubuntu. I have a statically linked executable of the openssl cli from the patched repository that I'm happy to provide, though I'm not sure there are enough POWER8 machines out there running tools like this to make it worth the space in the repo ;)

Are you interested in a PR to add the binary to this repo? If not, you can close this out

Thanks

**Comment by jauderho** [comment]
I, for one, would actually be able to use this. Multiple E980s deployed.

So, +1 from me.

**Comment by drwetter** [comment]
To answer your question: yes, I want one, thanks :-)

But honestly I rather would like to put them on the [website](https://testssl.sh/openssl-1.0.2i-chacha.pm.ipv6.contributed/) as github is not the greatest place for blobs. Also ARM binaries and the 32bit Mac binaries reside there.

You can anyway use a PR or let me know any other way how to get my hands on it.

Cheers, Dirk

**Comment by drwetter** [comment]
If you like amend the Readme.md then (https://github.com/drwetter/testssl.sh/blob/3.1dev/bin/Readme.md)

**Comment by mzpqnxow** [comment]
OK, will send a PR in a bit.

FWIW I have toolchains handy for MIPS, MIPSEL, SPARC and bunch of other platforms, though I have no use for them. Would be happy to provide builds for those as well but I don't have machines to test on
