### ISSUE TITLE
PrioritizeChaCha detection

### ISSUE THREAD

**Issue by army1349** [drwetter/testssl.sh#1733]
Would be possible to add [PrioritizeChaCha](https://www.openssl.org/docs/man1.1.1/man3/SSL_CONF_cmd_value_type.html) detection to server cipher order test?
For example SSL Labs positive detection results in: _(P) This server prefers ChaCha20 suites with clients that don't have AES-NI (e.g., Android devices)_
Thanks!

**Comment by drwetter** [comment]
Can you show me a result from SSL labs?

First is security, so I am hesitant for giving any performance related advise. As a hint: maybe

**Comment by army1349** [comment]
Sure, [here](https://www.ssllabs.com/ssltest/analyze.html?d=cloudflare.com&s=104.17.175.85) cloudflare test result.

Well, this is kind of server cipher order preference exception, so definitely about security.

**Comment by polarathene** [comment]
> First is security, so I am hesitant for giving any performance related advise.

Isn't the cipher considered PFS? According to Mozilla's advice, when all ciphers are considered strong due to being PFS, the order doesn't matter as much, so you can allow client preference for devices to choose what they'd be more efficient at handling, such as the case here with devices lacking AES-NI.

**Comment by drwetter** [comment]
Sure. But the point is that AES ciphers are - of course - still supported. It's only slower. Have a look at the ssllabs client handshakes and try yourself at ssllabs.

**Comment by army1349** [comment]
My point is that cipher order information is now not entirely true or at least incomplete when PrioritizeChaCha is enabled.

And it would be nice confirmation that PrioritizeChaCha works correctly.
Internet.nl test misdetects this entirely, but they [plan](https://github.com/NLnetLabs/Internet.nl/issues/461) to add support for correct detection.

**Comment by drwetter** [comment]
ok, For servers using OpenSSL you have to edit a config file if I see that correctly.

Maybe something @dcooper16 at some point ca look into, he did an excellent job for the current preference implementation

**Comment by army1349** [comment]
Direct exposure of OpenSSL options is not very common, so I started to use OpenSSL config files anyway.
Postfix has native [support](http://www.postfix.org/postconf.5.html#tls_ssl_options). Nginx [resisting](https://trac.nginx.org/nginx/ticket/1445).
