### ISSUE TITLE
Document that `--file` option should end with a blank line for reliable EOF handling?

### ISSUE THREAD

**Issue by polarathene** [drwetter/testssl.sh#1737]
[Docs for `--file <fname>`](https://github.com/drwetter/testssl.sh/blob/3.1dev/doc/testssl.1.md#input-parameters) state:

> Each single line in fname is parsed upon execution. If there's a conflicting option and serial mass testing option is being performed the check will be aborted at the time it occurs and depending on the output option potentially leaving you with an output file without footer. **In parallel mode the mileage varies, likely a line won't be scanned.**

### what exactly was happening, output is needed

```
example.test:465
example.test:995
example.test:993
--starttls smtp example.test:25
--starttls smtp example.test:587
--starttls pop3 example.test:110
--starttls imap example.test:143
```

`--starttls imap example.test:143` seems to have been ignored/skipped. In testing, this appears to be due to an earlier line in the options docs:

> `EOF` signals the end of fname any subsequent lines will be ignored too.

As the file (saved on linux, only LF line endings), does not end with a blank line, and thus I assume is why the last line is being ignored?

### what did you expect instead?

If a blank line is required to properly handle `EOF`, that should properly be communicated in the options docs. It appears to be the case, adding a blank line at the end of the file did result in my last command actually being performed.

Otherwise, it would be nice if the last command being the last line of the file was not ignored?

[According to this answer on the Unix StackExchange](https://unix.stackexchange.com/a/18789), EOF is possibly being detected by the lack of a `\n` new line (or LF?) for that final line with text in it? `testssl.sh` ignores anything after that last known line presumably, it's apparently a common reason for the practice of having an empty/blank line at the end of a text file to avoid this issue... so making that more obvious of a requirement in the docs might be helpful?

### Environment

`testssl.sh` official DockerHub image run with docker-compose:

```docker-compose.yaml
# snippet:
  testssl:
    image: drwetter/testssl.sh:3.1dev
    container_name: testssl-test
    volumes:
      - $PWD/data/stepca/home/certs:/tls:ro
      - $PWD/data/testssl/tests:/tests:ro
      - $PWD/data/testssl/results:/results
    working_dir: /results
    dns: 192.168.1.12
    command: --add-ca /tls/root_ca.crt --outprefix profile_intermediate --json-pretty --log --color 0 --severity LOW --wide --show-each --file /tests --mode parallel
    depends_on:
      - coredns
      - mail
```

tests file:

```
example.test:465
example.test:995
example.test:993
--starttls smtp example.test:25
--starttls smtp example.test:587
--starttls pop3 example.test:110
--starttls imap example.test:143
```

**Comment by drwetter** [comment]
EOF  like in HERE documents. It should have been clear that this is not literally the end of file when it says _any subsequent lines will be ignored too_

The test file (w/o trailing blank line) works for me.

**Comment by polarathene** [comment]
> The test file (w/o trailing blank line) works for me.

I'm reporting it because it affects me. I have to ensure that a command is not in the last line of the file, otherwise it's ignored. I can reproduce this consistently, I'll look into verifying on another machine that it's reproducible there as well.

Once I've taken care of my current tasks I'll submit a reproduction (docker-compose) if you like? Otherwise I'm happy to contribute a warning as a troubleshooting tip in the docs that the last line may be ignored.
