### ISSUE TITLE
Small typo in comment text of "Q: So what's the difference ..."

### ISSUE THREAD

**Issue by Ligushka** [drwetter/testssl.sh#174]
"www.ssllabs.com/ssltesti/" should be "www.ssllabs.com/ssltest/" (no " i ").

**Comment by PeterMosmans** [comment]
Thanks @Ligushka, I took the liberty of fixing that one :)
Saves @drwetter some keystrokes

**Comment by Ligushka** [comment]
Great, thanks! :+1:
