### ISSUE TITLE
False result for "Secure Client-Initiated Renegotiation     VULNERABLE (NOT ok), DoS threat" testssl scan

### ISSUE THREAD

**Issue by taher9990** [drwetter/testssl.sh#1752]
Please make sure that you provide enough information so that we understand what your issue is about.

0. Did you check the documentation in ~/doc/ or, if it is a different problem: Did you google for it?

1. uname -a
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
~# testssl -v

No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl       2.9.5 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1  11 Sep 2018" [~162 ciphers]
 on SSH-JumpHost-JDC:/usr/bin/openssl
 (built: "May 27 19:15:54 2020", platform: "debian-amd64")

3. git log | head -1 (if running from git repo)

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host

6. what exactly was happening, output is needed
While scanning against for example google.com, 
This finding is not true, "Secure Client-Initiated Renegotiation     VULNERABLE (NOT ok), DoS threat " 
I tested it with openssl s_client google.com:443  and then tried to renegotiate the TLS session  "HEAD / HTTP/1.0" it gave me the error , which means that vulnerability is closed but testssl is still showing it is open,

Note: I think more important vulnerability check against TLS and SSL is needed to be added

7. what did you expect instead?

**Comment by drwetter** [comment]
2.9.5 is not supported anymore. Sorry.

All I can say that with 3.0.2 it works:

![image](https://user-images.githubusercontent.com/8036727/96737056-879ea580-13bd-11eb-8594-ab7b879458d8.png)
