### ISSUE TITLE
Display error for certificate validity of Let's Encrypt certificates (output like "15>=30 days")

### ISSUE THREAD

**Issue by keisentraut** [drwetter/testssl.sh#1755]
testssl.sh is halvening the default "warn2days1" and "warn2days2" values for Let's encrypt certificates, but it does not halve the values which it outputs. This does lead to a strange green output "15>=30 days" in testssl.sh, see screenshot below. You can use [my blog klaus.hohenpoelz.de](https://klaus.hohenpoelz.de) as test host, at least right now.

![testssl_le_expiry_bug](https://user-images.githubusercontent.com/2080545/97218444-fcf8e480-17c8-11eb-88fd-5df9ddca8a09.png)

Output should be "15>=15 days" instead.

For the sake of completeness please find other information below:

1. uname -a
```Linux laptop-klaus 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37+0000 x86_64 GNU/Linux```
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
```
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (4af9016 2020-10-20 21:00:02 -- )
```
3. git log | head -1 (if running from git repo)
```commit 4af901683aec064d17e2fafc25494f5304717c76```

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
```./bin/openssl.Linux.x86_64```

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
```./testssl.sh klaus.hohenpoelz.de```

**Comment by drwetter** [comment]
Thanks, I think I introduced this bugs recently

Edit: It should have been caught by the integration test, ...hmm

**Comment by drwetter** [comment]
closed via PR, see above. Thanks again
