### ISSUE TITLE
No matching cipher in this list found - Dovecot 2.2.18 server

### ISSUE THREAD

**Issue by Ligushka** [drwetter/testssl.sh#176]
Running "testssl.sh -t imap depechemode-live.com:143" which is a Dovecot 2.2.18 server (running this PPA: https://launchpad.net/~malte.swart/+archive/ubuntu/dovecot-2.2) with OpenSSL Version: 1.0.1f-1ubuntu11.4 installed on the server, configured with only TLS 1.2 and one cipher suite enabled, I receive the following:

![cipher](https://cloud.githubusercontent.com/assets/13472038/9333196/8cd9d998-4596-11e5-95ff-2a2262f10330.png)

**Comment by drwetter** [comment]
@Ligushka : This is because only one protocol seems enabled, see last test. This is IMO not enough for a solid number of clients to realistically have a good chance of encryption for STARTTLS enabled protocols.

**Comment by Ligushka** [comment]
Fair enough.
I only enable TLS 1.2 + ECDHE-RSA-AES128-GCM-SHA256 on Dovecot because only two IMAP clients will be connecting to my personal mail server: my Android phone, and Thunderbird clients. Postfix has a more broad configuration (TLS 1.0, 1.1, 1.2, ECDHE, DHE, & RSA cipher suites enabled).
