### ISSUE TITLE
Duplicate names for branches and tags, e.g. "3.0"

### ISSUE THREAD

**Issue by keisentraut** [drwetter/testssl.sh#1763]
There are duplicate names for git tags/branches, especially "3.0". This makes git usage a lot more complicated, i got hurt a few times now. Maybe you can rename either the branch to "3.0dev" or change the tags to the "v3.0" format?

If anyone else got stuck, [this is how i finally did it](https://markhneedham.com/blog/2013/06/13/git-having-a-branchtag-with-the-same-name-error-dst-refspec-matches-more-than-one/):
```
$ git remote add upstream git@github.com:drwetter/testssl.sh.git
$ git fetch upstream :refs/remotes/upstream/3.0
Enter passphrase for key '/home/klaus/.ssh/id_ed25519': 
Von github.com:drwetter/testssl.sh
 * [neue Referenz]              -> upstream/3.0
 * [neues Tag]       3.0        -> 3.0
$ git tag -d 3.0
Tag '3.0' gelöscht (war 0d79413)
```

**Comment by drwetter** [comment]
Not sure I can follow you? 3.0 ist the stable branch and, yes it is the tags for the initial release of 3.0. (Tags and releases are here: https://github.com/drwetter/testssl.sh/releases .)

I won't remove any tags in the past as this will hurt a lot of people. Renaming the branch, I believe this will confuse people too.

For the future, yes.

**Comment by keisentraut** [comment]
I agree renaming tags/branches is bad. Just wanted to tell you what my experience was. You can  keep your naming scheme for now, I will have to learn more git... Unfortunately, the [xkcd approach](https://xkcd.com/1597/) does not help here...

What I did: 
- I have three git repos: My local one and the branches ```origin``` (my fork) and ```upstream``` (your repository). 
- The problem is that I cannot checkout BRANCH 3.0, because ```git checkout 3.0``` will checkout the 3.0 TAG. 
- I managed to checkout ```origin/3.0```, but then I am in detached head and cannot fast-forward. 
- I can checkout the local ```ref/branch/3.0``` and fast-forward this branch, but then the name is not ```3.0```and I can't push it to ```origin``` because the name is wrong.  
- I still don't know how to fast-forward my local 3.0 BRANCH with the changes in ```upstream/3.0``` BRANCH and then push it to my ```origin/3.0``` BRANCH.

**Comment by drwetter** [comment]
Ok, thanks for the feedback @keisentraut . I appreciate that, also if @ anybody else will support this as I personally do not have that problem.

Disclaimer: I work with github for a longer while but I am no expert either and of course there maybe things which could be subject to discussion or more.

**Comment by drwetter** [comment]
> Unfortunately, the xkcd approach does not help here...

:-)
