### ISSUE TITLE
Error when trying to test imap

### ISSUE THREAD

**Issue by amenk** [drwetter/testssl.sh#1768]
Please make sure that you provide enough information so that we understand what your issue is about.

0. Did you check the documentation in ~/doc/ or, if it is a different problem: Did you google for it?

yes

1. uname -a

docker (ubuntu 20.04)
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2

from docker

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'

from docker

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host

<pre>$ docker run --rm -ti  drwetter/testssl.sh:3.1dev -t imap outlook.office365.com:993

<b>###########################################################</b>
<b>    testssl.sh       3.1dev from https://testssl.sh/dev/</b>

<b>      This program is free software. Distribution and</b>
<b>             modification under GPLv2 permitted.</b>
<b>      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!</b>

<b>       Please file bugs @ https://testssl.sh/bugs/</b>

<b>###########################################################</b>

 Using &quot;OpenSSL 1.0.2-chacha (1.0.2k-dev)&quot; [~183 ciphers]
 on 87d991094014:/home/testssl/bin/openssl.Linux.x86_64
 (built: &quot;Jan 18 17:12:17 2019&quot;, platform: &quot;linux-x86_64&quot;)

<b>Testing all IPv4 addresses (port 993): </b>40.101.19.146 40.101.80.194 40.101.80.178
------------------------------------------------------------------------------------------------------------------------------------------------------------------
<span style="background-color:#FFFFFF"><font color="#300A24"> Start 2020-11-05 09:36:18        --&gt;&gt; 40.101.19.146:993 (outlook.office365.com) &lt;&lt;--</font></span>

 Further IP addresses:   40.101.12.34 40.101.121.18 40.101.12.130 2603:1026:c03:6025::2 2603:1026:207:18b::2 2603:1026:207:14::2 
 rDNS (40.101.19.146):   --
/usr/local/bin/testssl.sh: line 10626: 3=142: command not found
</pre>

6. what exactly was happening, output is needed

Error message

7. what did you expect instead?

a check result

**Comment by drwetter** [comment]
Hi Alex, 

thanks.

Can reproduce the commnd-not-found error, thanks. Will be fixed  soon.

``-t imap`` you would need for port 143 where you need a plaintext  STARTTLS handshake upfront. On port 993 is usually plain TLS..

Cheers, Dirk

PS: Long time no hear

**Comment by drwetter** [comment]
note: doesn't affect 3.0

**Comment by amenk** [comment]
> PS: Long time no hear

I am bad with memory... Did we have contact before?
You can also ping me via mail alex dot menk at gmail

**Comment by amenk** [comment]
I also cannot reply to your mail...
