### ISSUE TITLE
Suggest '${NODE}-p${port}${YYYYMMDD-HHMMSS}.log' to not block logging

### ISSUE THREAD

**Issue by nomandera** [drwetter/testssl.sh#1775]
Please make sure that you provide enough information so that we understand what your issue is about.

0. Did you check the documentation in ~/doc/ or, if it is a different problem: Did you google for it?

1. uname -a
   Linux ubuntu 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (6558631 2020-11-05 14:07:42 -- )

3. git log | head -1 (if running from git repo)
commit 65586311f656f73060f2f7e934bf9abd0a96d25d
4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
./bin/openssl.Linux.x86_64

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
Use either
     --log, --logging              logs stdout to '${NODE}-p${port}${YYYYMMDD-HHMM}.log' in current working directory (cwd)
     --logfile|-oL <logfile>       logs stdout to 'dir/${NODE}-p${port}${YYYYMMDD-HHMM}.log'. If 'logfile' is a dir or to a specified 'logfile'

6. what exactly was happening, output is needed
You are limited to one run per minute.
7. what did you expect instead?
Not be limited to one run per minute. Only full runs take longer than a minute to complete and runs that result in error (e.g setup runs) are instant. Ideally the default naming format would not block this and result in error an artificial wait time.

Suggest ```${NODE}-p${port}${YYYYMMDD-HHMMSS}.log```

**Comment by drwetter** [comment]
Sigh, that is per design. And: it is in worst case < 1 minute, deonding when you start.

If you don't like the default, why don't you supply a different cmd line?

**Comment by nomandera** [comment]
No problems at all if the current way is the right/best way.

It is easy enough to work around as-is and I only posted since I realised today I was subconsciously working around it quite a lot and it was worth a quick discussion

Thanks for the quick reply.

**Comment by drwetter** [comment]
Know you meant something different.
 
But maybe that helps for you, see PR #1777

**Comment by nomandera** [comment]
That is excellent and as good if not a superior fix than I suggested.

Thanks again for the project, there is not a week that passes that I dont find a need to use it.
