### ISSUE TITLE
Testssl failure to install on MacOS Big Sur

### ISSUE THREAD

**Issue by cwoollard** [drwetter/testssl.sh#1784]
The following error message is displayed when installing the Testssl

brew install testssl
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Downloading https://github.com/drwetter/testssl.sh/archive/3.0.4.tar.gz
Already downloaded: /Users/chriswoollard/Library/Caches/Homebrew/downloads/ebcb0d8a44f3b698b53cccf212c32126ad3ab69bb4149233d0eb4bc5e139cab0--testssl.sh-3.0.4.tar.gz
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Error: An exception occurred within a child process:
  SystemExit: exit

**Comment by drwetter** [comment]
Sorry, that is a topic for the homebrew folks.
