### ISSUE TITLE
Enable NNTP over STARTTLS (was: How to test NNTP over SSL on port 563?)

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#179]
See the thread here: https://plus.google.com/+DalijaPrasnikar/posts/FE57gBQuBZm

I want to test the new Embarcadero forums server. I did test https. Now I want to test NNTP over SSL on port 563. How do I do that?

**Comment by drwetter** [comment]
If it's plain TLS just specify the port, see help. 

For STARTTLS enabled NNTP: the code is basically there (https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L2218-L2272) -- this is however only for bash sockets. OpenSSL doesn't have support for this. The catch is: the code is dead, i.e. not enabled yet  ;-) as higher level code forbids this to be called.

Should be no big deal however.

**Comment by drwetter** [comment]
If it's plain TLS just specify the port, see help. 

For STARTTLS enabled NNTP: the code is basically there (https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L2218-L2272) -- this is however only for bash sockets. OpenSSL doesn't have support for this. The catch is: the code is dead, i.e. not enabled yet  ;-) as higher level code forbids this to be called.

Should be no big deal however.

**Comment by drwetter** [comment]
Tried myself. It's plain TLS, no STARTTLS. (btw: he encryption is basically junk)

If you happen to come across an STARTTLS enabled NNTP server, please let me now. I'll take this as an issue for the end of year release to enable the not-enabled code.

**Comment by drwetter** [comment]
self commenting: ``news.eternal-september.org:119``

**Comment by jpluimers** [comment]
Indeed. It's as bad as their HTTPS was. `./testssl.sh forums.embarcadero.com:563` https://gist.github.com/c24d1867188089948a2e

**Comment by drwetter** [comment]
The first doesn't work as the parser stops as soon an URI is being hit -- see help. One might expect a warning here. If you like file an issue.

For the second: I do not see any escape code in Linux or BSD here. Ok, I cheated a bit (see https://github.com/drwetter/testssl.sh/commit/dddb1636bf48915d3881c89f6161630cdf999913#diff-2b772c01e86977452d2db64b3031f913) ;-)

If you still see colors / ESC codes, please file an issue with the dirty details. ;-)

**Comment by jpluimers** [comment]
@drwetter just did a `git pull` and the second doesn't fail any more.

**Comment by drwetter** [comment]
Currently ``openssl s_client`` doesn't support NNTP over STARTTLS.

The socket handshake with STARTTLS is implemented in testssl.sh but as long as testssl.sh does not __everything__ in pure sockets openssl needs to support it too.

The STARTTLS handshake (https://tools.ietf.org/html/rfc4642#section-2.2 .) looks trivial to implement in openssl (vanilla, @PeterMosmans fork).

**Comment by jpluimers** [comment]
If I were a good C programmer (:

**Comment by drwetter** [comment]
Am 6. Oktober 2015 19:36:47 MESZ, schrieb Jeroen Wiert Pluimers <notifications@github.com>:
>If I were a good C programmer (:

Who is? ;)  It's on.my list. 

Cheers, Dirk 


-- 
Sent from my mobile

**Comment by drwetter** [comment]
In openssl this will be done later, not now.

**Comment by drwetter** [comment]
In OpenSSL: https://github.com/openssl/openssl/search?q=nntp&unscoped_q=nntp . Would be great to get this in for the new set of binaries to be compiled for 3.0..

**Comment by jpluimers** [comment]
@drwetter do you need me to make new OpenSSL builds for MacOS?

**Comment by drwetter** [comment]
would be appreciated, thx. But I'll need to get the patch applied and test it.

**Comment by jpluimers** [comment]
@drwetter ping me the 24th on Hangouts and I'll try to get something done.

**Comment by drwetter** [comment]
see https://github.com/drwetter/openssl-1.0.2.bad/commit/630053d308677fb6a2be31743b29725cce105e28

**Comment by drwetter** [comment]
The catch is: Even openssl 1.1.1 doesn't seem to work https://github.com/openssl/openssl/issues/7722

**Comment by drwetter** [comment]
![untitled](https://user-images.githubusercontent.com/8036727/49165471-95626200-f331-11e8-9582-f37890734bd9.png)
