### ISSUE TITLE
Skip Validity or Validity Alert Minimum

### ISSUE THREAD

**Issue by carlheaton** [drwetter/testssl.sh#1790]
I'm doing diffs on testssl.sh results, works really great, but the "Certificate Validity (UTC)" with the counting down days until expiry obviously alerts every day.

It would be great if either:

* There was an --option to disable validity checks
* There was an --option to only alert on validity checks when less than n days

I can obviously grep out the diffs for this item (or perhaps do a more complex regexp), but either of the above would be nice features.

**Comment by drwetter** [comment]
Hi @carlheaton 

are you working on #1782?

If so, it's better to black list those. I identified them here in the first lines: https://github.com/drwetter/testssl.sh/blob/3.1dev/t/61_diff_testsslsh.t, maybe only 99% complete

**Comment by carlheaton** [comment]
@drwetter no sorry, I've been running a custom php cron some years which executes testssl, diffs the new to the previous, emails us if there's changes/diff, stores the new, just a simple way to monitor for unexpected changes to our SSL configurations. "Certificate Validity" is the only new issue where having it not fully excluded is not useful. I've already been filtering skew, Ticketbleed (as seemed inconsistent previous versions) and X-Varnish.

**Comment by drwetter** [comment]
Nah, sorry. This is too much asking. You'd need to use regexes. 😉

**Comment by drwetter** [comment]
It'll make sense though. Will be handled in #880
