### ISSUE TITLE
Docs: When running via docker, it's not easy to get to the log file

### ISSUE THREAD

**Issue by amenk** [drwetter/testssl.sh#1791]
I am running testssl via docker

    docker run --rm -ti  drwetter/testssl.sh:3.0 --csv

The CSV file is stored in the container and then lost

I think we should add some volume mount

**Comment by drwetter** [comment]
RTFM, por favor: 

https://github.com/drwetter/testssl.sh/blob/3.1dev/Dockerfile.md

**Comment by amenk** [comment]
Thank you :-D

I think we should link that Dockerfile.md in the main README ...

**Comment by drwetter** [comment]
Good point.

I realized the Dockerfile seems anyway a bit out of date regarding the versions.

**Comment by drwetter** [comment]
done.
