### ISSUE TITLE
PFS key size in PFS summary

### ISSUE THREAD

**Issue by oparoz** [drwetter/testssl.sh#18]
This is what I'm getting with [cipherscan](https://github.com/oparoz/cipherscan) when using OpenSSL 1.0.2

```
prio  ciphersuite                  protocols  pfs_keysize
1     DHE-RSA-AES256-GCM-SHA384    TLSv1.2    DH,4096bits
2     DHE-RSA-AES256-SHA256        TLSv1.2    DH,4096bits
3     DHE-RSA-AES128-GCM-SHA256    TLSv1.2    DH,4096bits
4     DHE-RSA-AES128-SHA256        TLSv1.2    DH,4096bits
5     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2    ECDH,P-384,384bits
6     ECDHE-RSA-AES256-SHA384      TLSv1.2    ECDH,P-384,384bits
7     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2    ECDH,P-384,384bits
8     ECDHE-RSA-AES128-SHA256      TLSv1.2    ECDH,P-384,384bits
```
Even though that version of OpenSSL isn't out yet, I think it would be useful to get ready and offer that kind of information as soon as it's out.

**Comment by drwetter** [comment]
Oh, I missed tto comment on that. 

@oparoz maybe you were ahead on time ;-) That was implemented in060178071dbb30d0b9235989387af29ff04f4e43  because of Logjam, see #105, #106, #107 .

**Comment by oparoz** [comment]
:+1:
