### ISSUE TITLE
Default output file names to include the path

### ISSUE THREAD

**Issue by sellersj** [drwetter/testssl.sh#1804]
**Is your feature request related to a problem? Please describe.**
When testing multiple services behind a routing load balancer, they can have the same domain but on different paths / context roots. If TLS is set to passthrough to these services, I want to be able to check for proper TLS impl and features like HSTS are correctly configured on each service. The current default file creation has node and port. Since the path is not used, it means I can't use bulk testing in parallel.
e.g.
example.com/app1/context1/
example.com/app2/context2/
example2.com

**Describe the solution you'd like**
Either the option of enabling a default file pattern, or changing the default to always include a path if it exists.
Since slashes wouldn't be allowed for file names, they could be changed to underscores or some other character.
e.g. create files like this by default
example.com_p443_app1_context1.json
example.com_p443_app1_context1.html
example.com_p443_app2_context2.json
example.com_p443_app2_context2.html
example2.com_p443.json
example2.com_p443.html

**Describe alternatives you've considered**
For testing urls that have a context root I have to test them individually setting a filename for all outputs. This works but is much slower than being able to use the parallel testing feature.

**Comment by drwetter** [comment]
Depends how you call it. When e.g. you use ``--json`` instead of ``--jsonfile`` testssl.sh automatically sticks to the predefined pattern. Using ``--jsonfile example.com_p443_app1_context1.json`` it works. But that's probably not the answer you wanted ? ;-)

**Comment by drwetter** [comment]
Maybe I should have added:

```
prompt> cat f
--jsonfile example.com_p443_app1_context1.json https://example.com/app1/context2.json
--jsonfile example.com_p443_app1_context2.json https://example.com/app1/context2.json
--jsonfile example.com_p443_appX_contextZ.json https://example.com/appX/contextZ.json
prompt> ./testssl.sh --parallel --file f
 🎉 
```

**Comment by sellersj** [comment]
Ohh, that's a much better work around than I currently had. I thought that the --file command was just to specify the domain names.

Not exactly what I was picturing, but I think it's a fine work around. Thank you very much.

**Comment by drwetter** [comment]
You're welcome. There seems to be a bug though, just trying to figure out
