### ISSUE TITLE
invalid integer constant / syntax error, operand expected, when scanning a specific internal host

### ISSUE THREAD

**Issue by shimile** [drwetter/testssl.sh#1808]
**Command line / docker command to reproduce**
testssl [internal hostname]

**Expected behavior**
Not get syntax error middle of the run

**Your system (please complete the following information):**
 - OS: ``ArchLinux``
 - Platform: ``Linux 5.9.14-arch1-1 x86_64``
 - Version: ``3.0.2``
 - OpenSSL: `` Using "OpenSSL 1.1.1i  8 Dec 2020" [~80 ciphers]``
 
**Additional context**
This is what I'm getting on a specific host (other host is OK with the same testssl executable on the same machine) :

 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered

 Testing cipher categories 

 NULL ciphers (no encryption)                  not offered (OK)
 Anonymous NULL Ciphers (no authentication)    not offered (OK)
 Export ciphers (w/o ADH+NULL)                 not offered (OK)
 LOW: 64 Bit + DES, RC[2,4] (w/o export)       not offered (OK)
 Triple DES Ciphers / IDEA                     not offered
 Obsolete CBC ciphers (AES, ARIA etc.)         offered
 Strong encryption (AEAD ciphers)              offered (OK)

 Testing robust (perfect) forward secrecy, (P)FS -- omitting Null Authentication/Encryption, 3DES, RC4 

 PFS is offered (OK)          ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES256-SHA256 DHE-RSA-AES256-SHA ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 
 Elliptic curves offered:     sect283k1 sect283r1 sect409k1 sect409r1 sect571k1 sect571r1 secp256k1 prime256v1 secp384r1 secp521r1 
 DH group offered:            ffdhe2048

 Testing server preferences 

 Has server cipher order?     no (NOT ok)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            DHE-RSA-AES256-SHA256, 2048 bit DH -- inconclusive test, matching cipher in list missing, better see below
 Negotiated cipher per proto  (matching cipher in list missing)
/usr/bin/testssl: line 1169: 16#: invalid integer constant (error token is "16#")
/usr/bin/testssl: line 12828: 2+: syntax error: operand expected (error token is "+")

**Comment by drwetter** [comment]
should be fixed in 3.0.4. Please try again and let me know if the problem persists. I'll reopen then
