### ISSUE TITLE
Change halving Let's encrypt dates to based on the O rather than the CN

### ISSUE THREAD

**Issue by sellersj** [drwetter/testssl.sh#1816]
_**Please don't remove this template. We would like to reproduce the bug and need concise information. **_

**Command line / docker command to reproduce**
The CN has changed from things like "Let's Encrypt Authority X*" to "R3", "E2", etc.
https://letsencrypt.org/certificates/

```
docker run --rm drwetter/testssl.sh:3.0 --fast --assume-http letsencrypt.org
```
Shows
Issuer                       R3 (Let's Encrypt from US)

With these lines, it should probably be changed to go against the O rather than the CN
```
     if [[ "$issuer_CN" =~ ^Let.s\ Encrypt\ Authority ]] ; then
          days2warn2=$((days2warn2 / 2))
          days2warn1=$((days2warn1 / 2))
     fi
```

**Expected behavior**
It should show a proper halving of the dates but it doesn't.

**Your system (please complete the following information):**
n/a for docker container
 

**Additional context**
n/a

**Comment by drwetter** [comment]
Thanks! PR pending for 3.1dev. I'll check for 3.0 in a minute.

Also the name changed ``Let.s Encrypt\ Authority`` --> ``Let.s Encrypt``

**Comment by drwetter** [comment]
Fixed in both branches. Thanks again for reporting
