### ISSUE TITLE
Visible "SSL_connect:error"

### ISSUE THREAD

**Issue by Ligushka** [drwetter/testssl.sh#182]
When running command "./testssl.sh -t imap depechemode-live.com:143" I receive the following:
![protocols-ugly](https://cloud.githubusercontent.com/assets/13472038/9548869/ed51440a-4d70-11e5-9a57-cac0fbf9349f.png)
I believe the "SSL_connect:error messages" are not intended to be displayed to the user.

**Comment by Ligushka** [comment]
Another similar situation with "./testssl.sh -t smtp depechemode-live.com:25":

![protocols-ugly-2](https://cloud.githubusercontent.com/assets/13472038/9548984/90a5abbe-4d71-11e5-94bb-cb7d047fda38.png)

**Comment by drwetter** [comment]
Thx for reporting!
