### ISSUE TITLE
getting issue "./testssl.sh: line 1172: 16#: invalid integer constant (error token is "16#") ./testssl.sh: line 12827: 2+: syntax error: operand expected (error token is "+")

### ISSUE THREAD

**Issue by DeadManINDIA** [drwetter/testssl.sh#1820]
Using latest kali linux could you please suggest what i need to do to avoid it?
"└─#     uname -a 
Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux"

**Comment by drwetter** [comment]
update from git.

**Comment by drwetter** [comment]
let me know if that didn't work.
