### ISSUE TITLE
How can I run testssl in continuous integration (CI)?

### ISSUE THREAD

**Issue by MartinThoma** [drwetter/testssl.sh#1821]
I would like to run testssl.sh e.g. in a [Gitlab scheduled pipeline](https://docs.gitlab.com/ee/ci/pipelines/schedules.html) or a [Github scheduled action](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule) or a [TravisCI Cron Job](https://docs.travis-ci.com/user/cron-jobs/) against my web server.

## Questions

1. Is the exit code of testssl non-zero in case of errors?
2. Is it possible to test this against NIST recommendations (e.g. [NIST SP 800-52](https://csrc.nist.gov/News/2019/nist-publishes-sp-800-52-revision-2) and [NIST CAVP](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program))?
3. If I install testssl via [a standard Debian repository](https://packages.debian.org/de/sid/testssl.sh), does testssl download the latest information against what cipher suites are considered secure? Or do I have to make sure that I install the latest testssl version?

**Comment by drwetter** [comment]
Hi @MartinThoma ,

> I would like to run testssl.sh e.g. in a Gitlab scheduled pipeline or a Github scheduled action or a TravisCI Cron Job against my web server.

sounds cool. To answer your questions:

1.) yes, currently. See  ``EXIT STATUS`` in ma npage. It's intended but not implemented to return scanning results (ret values 50-200).  Not sure whether we can pass that differently.
2) Not implemented yet, see #1085 
3) Not sure I understand your question. Debian uses stable 3.0.4. We have a rating in 3.1dev based on SSLlabs. For file output and screen output is should be approximately the same. Also testssl.sh looks at more at just ciphers.

**Comment by MartinThoma** [comment]
@drwetter Thank you for the answer!

Regarding the exit code,  I think it is zero even for errors:

```
 docker run --rm -ti  drwetter/testssl.sh expired.badssl.com; echo $?
```

Or is that docker "hiding" the non-zero exit code?

**Comment by MartinThoma** [comment]
Docker run seems to "forward" non-zero exit codes: https://docs.docker.com/engine/reference/run/#exit-status

**Comment by drwetter** [comment]
Quoting: `` It's intended but not implemented to return scanning results (ret values 50-200).``
