### ISSUE TITLE
Should  testssl.sh match www.ssllabs.com results? 

### ISSUE THREAD

**Issue by raulbarreras** [drwetter/testssl.sh#1829]
Hi!
First of all, thank you for this amazing tool!
I'm not sure if this could be considered an issue, but the results obtained by testssl.sh and www.ssllabs.com differ.
### testssl.sh:

```Grade capped to T. Issues with the chain of trust (chain incomplete)```

### ssllabs.com

```This server's certificate chain is incomplete. Grade capped to B. ```

Please, let me know if you need more info.

**Comment by magnuslarsen** [comment]
Hi Jose,

I don't think it should at all times. Testssl matches against [SSLLabs rating guide](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide) which has a few differences from the SSLLabs rating tool.

The specific error you list, I would assume falls under [this (specifically this point `Use of a certificate that is not trusted (unknown CA or some other validation error)`)](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide#certificate-inspection)

If I'm wrong though, I will of course remap the score.

**Comment by drwetter** [comment]
I cannot read your thoughts or what you were doing in order to achieve those results.

**Comment by drwetter** [comment]
@magnuslarsen : better is to have a hostname (thx for chiming in)

**Comment by raulbarreras** [comment]
I'm sorry I didn't explain myself better. 
An example could be tutortrac[.]unk[.]edu
ssllabs.com reports a B and according to testssl.sh is a T.
I think testssl.sh results are correct: chain of trust is incomplete. 

I'm using https://github.com/drwetter/testssl.sh/commit/eabc21b7c4bafb19b52dcb3440e1374270ef9797

**Comment by drwetter** [comment]
SSLlabs assumes that browsers will download the missing intermediate certificate(s). SSLlabs is about HTTPS only. If you'll click on expand path, you'll see those. We don't do that. For major browsers we can be sure, that they will dl those. For any other clients I am not sure they will do that. We don't distinguish between different clients -- yet at least. To be honest I am not sure we should. Even for HTTPS you could have an API client e.g. which doesn't do that.

Thus I am closing this.

If you or any other has convincing arguments for this, please let me know.

Cheers, Dirk
