### ISSUE TITLE
Is there a non-interactive mode?

### ISSUE THREAD

**Issue by MartinThoma** [drwetter/testssl.sh#1835]
When I run

    testssl --quiet dh1024.badssl.com

I get 

```
 rDNS (104.154.89.105):  105.89.154.104.bc.googleusercontent.com.
 Your OpenSSL cannot connect to 104.154.89.105:443
 The results might look ok but they could be nonsense. Really proceed ? ("yes" to continue) -->
```

In this specific case, I would like "no" and have a non-zero exit code. Is there a way to make `testssl` in general non-interactive?

**Comment by drwetter** [comment]
works for me. Other than that: please read the fine manual or at least the embedded help (--> batch)
