### ISSUE TITLE
Issue with CCS Vulnerability

### ISSUE THREAD

**Issue by mkurtakoti** [drwetter/testssl.sh#1836]
It seems some incorrect results for vulnerabilities. For ex yopmail.com when scanned through testssl.sh it says Not Vulnerable to CCS. However, same through ssllabs.com it shows vulnerable to CCS. Same for Forward Secrecy.

Not sure which one is correct. Is this bug? or am I missing something ?

**Comment by drwetter** [comment]
see #1841
