### ISSUE TITLE
script syntax errors in cygwin

### ISSUE THREAD

**Issue by PawelCzarnota** [drwetter/testssl.sh#184]
Both stable update and latest dev package won't compile under cygwin. 
(https://cloud.githubusercontent.com/assets/8432694/9588215/9679e76c-4fec-11e5-95c6-dc3e42627dc5.png)

The problem are lines that follow the while loops:
while ...
done < <(tr ';' '\n' < $TMPFILE | tr -d ' ' | tr -d '\"' | awk -F'=' '/pin.*=/ { print $2 }')

**Comment by PawelCzarnota** [comment]
interesting, I found that if I call the script using bash instead of sh, it actually works.

**Comment by drwetter** [comment]
Hi @PawelCzarnota,

Also if "sh" is bash, bash is emulating /bin/sh  so this cannot work as it's a bash and not a sh script.

For people using zsh/tcsh and trying the same I'll make another check. 

Cheers, Dirk
