### ISSUE TITLE
Recommendations for batch/range scanning and logging

### ISSUE THREAD

**Issue by anoma** [drwetter/testssl.sh#185]
Currently I am scanning internal HTTPS by scripting multiple calls to testssl.sh in combination with tee etc

However this feels slightly ugly to me especially since in an ideal world the log file names would contain information from the scan itself i.e. timestamps, DNS/rDNS/CN, IP, port etc

Any thoughts or recommendations?

**Comment by drwetter** [comment]
Hi @anoma,

don't understand what the problem is. ``./testssl.sl --color=0 <cmdline+host> | tee cmdline+host.out`` should do it.

Cheers, Dirk

**Comment by anoma** [comment]
Thanks for the fast reply essentially I am currently doing a variation of above.

Primarily I was just checking this was the recommended method to scan many hosts.

Specific areas I find clunky when doing it this was is building a script to call the same command over and over in the absence of a --targets=FILE option i.e. a file containing a list of IP:PORT.

Also i currently log based on IP-TIMESTAMP since it is convoluted to IP-rDNS-PORT-TIMESTAMP.

Again none of these are bugs I am just sanity checking there is no slicker way of scanning many hosts and logging without building a scripts of dozens of testssl calls.

**Comment by drwetter** [comment]
The ``--targets `` option is there, however it is called ``--file``., see help.

**Comment by anoma** [comment]
Yes sorry I should have mentioned much earlier my confusion around this specific option

> --file <file name> mass testing option:
Just put multiple testssl.sh command lines in <file name>,   one line per instance. Comments via # allowed, EOF signals end of <file name>.

The way I interpreted the wording was that you could call

> ./testssl.sh --file targets

and targets could contain lines like

> --color=0 10.0.0.1
> --color=0 10.0.0.2

but then it wasn't clear how best to log (tee) or if this in fact was the right syntax at all.

Apologies for the rambling nature of this ticket. Perhaps some multi target with logging examples in the documentation would clear this up rather than me asking in hind sight silly questions.

**Comment by drwetter** [comment]
It didn't sound silly to me, I had only problems understanding what your aiming at. :-)

Real logging per host isn't there (yet), maybe it comes with #31, maybe it comes separately. For my personal planing other points have higher priority.

WRT Documentation: ACK, see #130 .

**Comment by drwetter** [comment]
see 756a6ab41d4c2a62885421522d7774bb1a434641
