### ISSUE TITLE
--really--fast ?

### ISSUE THREAD

**Issue by singpolyma** [drwetter/testssl.sh#1852]
**Which version are you referring to**
2.9.5-7
Using "OpenSSL 1.1.1d  10 Sep 2019" 

Is there some way to do a "really fast" run for more frequent monitoring?  I'd love to have it check that STARTTSL is working, that TLS1.2 is offered (but not check other versions), that cert is valid and not expired.

**Comment by drwetter** [comment]
Hi @singpolyma ,

it sounds more like a custom ``--file`` would fit better like

```
-p <host4prototestonly>
-t smtp -s <host4starttlstest:25>
-S <host4certificatetest>
```

**Comment by singpolyma** [comment]
>```
>-p <host4prototestonly>
>-t smtp -s <host4starttlstest:25>
>-S <host4certificatetest>
>```

It seems like -p can only test *all* the protocols and -S does a lot of 
other stuff as well. So with those it's still quite a lot of stuff and quite 
slow.

**Comment by drwetter** [comment]
That is true. But how many command line switches would you need otherwise for ``--p`` alone ?

And which of the zillion checks for ``-S`` should get a separate switch?

I am afraid that's too much asking at the moment
