### ISSUE TITLE
[BUG / possible BUG] TLSv1.2 cipher probing never completes when server cipher order is active

### ISSUE THREAD

**Issue by bjorn-wiberg** [drwetter/testssl.sh#1860]
When having forced server cipher order in Apache (2.4) or stunnel (5.5), probing never completes at "Testing server's cipher preferences" for "TLSv.12 (server order)". It tries over and over again (connections are established), but never seems to complete.

**Please check this repo whether this is a known issue**

Couldn't find a similar issue.

**Command line / docker command to reproduce**

Apache:
testssl.sh -P scbbs.nsupdate.info

stunnel:
testssl.sh -P scbbs.nsupdate.info:50992

**Expected behavior**

Probing should complete and move on to the next TLS version ("TLSv1.3").

**Your system (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - Platform: Linux 4.19.0-16-amd64 x86_64
 - Version:``
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (b468071 2021-03-25 22:13:31 -- )``
 - Version if running from git repo: commit b468071d720538ae3204451343fd3064720a2649
 - OpenSSL: ./bin/openssl.Linux.x86_64

**Additional context**

Software versions:

apache2:amd64/buster 2.4.38-3+deb10u4 uptodate
stunnel4:amd64/buster 3:5.50-3 uptodate
openssl:amd64/buster 1.1.1d-0+deb10u6 uptodate (OpenSSL 1.1.1d  10 Sep 2019)

Apache configuration:

SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
SSLHonorCipherOrder On
SSLCipherSuite EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SSLv3:!TLSv1:!DHE-RSA-AES128-SHA256:!DHE-RSA-AES256-SHA256:!DHE-RSA-CAMELLIA128-SHA256:!DHE-RSA-CAMELLIA256-SHA256:!ECDHE-RSA-AES128-SHA256:!ECDHE-RSA-AES256-SHA384:!ECDHE-RSA-CAMELLIA128-SHA256:!ECDHE-RSA-CAMELLIA256-SHA384

stunnel configuration:

sslVersion = all
options = NO_SSLv2
options = NO_SSLv3
options = NO_TLSv1
options = NO_TLSv1.1
ciphers = EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SSLv3:!TLSv1:!DHE-RSA-AES128-SHA256:!DHE-RSA-AES256-SHA256:!DHE-RSA-CAMELLIA128-SHA256:!DHE-RSA-CAMELLIA256-SHA256:!ECDHE-RSA-AES128-SHA256:!ECDHE-RSA-AES256-SHA384:!ECDHE-RSA-CAMELLIA128-SHA256:!ECDHE-RSA-CAMELLIA256-SHA384
options = CIPHER_SERVER_PREFERENCE
renegotiation = no
options = SINGLE_ECDH_USE
options = SINGLE_DH_USE

**Comment by dcooper16** [comment]
I tried both
```
testssl.sh -P scbbs.nsupdate.info
```
and
```
testssl.sh -P scbbs.nsupdate.info:50992
```
and both of them ran correctly for me, with total running time being about 1 minute each time.

How long did you let testssl.sh run before stopping it?

**Comment by drwetter** [comment]
works here too (Debian 10/Buster)

**Comment by bjorn-wiberg** [comment]
Hi there, and thank you for your replies!

It appears that the following environment variables are messing things up:

LC_COLLATE=sv_SE.UTF-8
LC_CTYPE=sv_SE.UTF-8
LC_MONETARY=sv_SE.UTF-8
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8

They yield date errors (excerpt from script -c "SETX=true bash -x ./testssl.sh --debug 6 -P scbbs.nsupdate.info:50992"):

|2037>  parse_date(): LC_ALL=C
|2037>  parse_date(): date -d 2140805982 '+%Y-%m-%d %r'
date: invalid date '2140805982'

After unsetting those environment variables everything works as intended.
Perhaps those environment variables should be unset by the script in addition to LC_ALL?

Thanks in advance!

Best regards
Björn

**Comment by drwetter** [comment]
Hi @bjorn-wiberg ,

thanks for the add'tl info. I was first reproducing the problem yesterday when I set LC_CTYPE only -- like ``LC_CTYPE=sv_SE.UTF-8 testssl.sh -P scbbs.nsupdate.info:50992``. The other locale setting didn't seem to contribute to the failure.

However now, it works and I am scratching my head why it does.

What does ``locale``  return before you run testssl.sh ?

**Comment by drwetter** [comment]
The section you were mentioning: it only will be called when $DEBUG is at least 3:

```
  if [[ $DEBUG -ge 3 ]]; then
          echo "TLS server hello message:"
          if [[ $DEBUG -ge 4 ]]; then
               echo "     tls_protocol:           0x$tls_protocol2"
               [[ "0x${DETECTED_TLS_VERSION:2:2}" -le "0x03" ]] && echo "     tls_sid_len:            0x$tls_sid_len_hex / = $((tls_sid_len/2))"
          fi
          if [[ "0x${DETECTED_TLS_VERSION:2:2}" -le "0x03" ]]; then
               echo -n "     tls_hello_time:         0x$tls_hello_time "
               parse_date "$TLS_TIME" "+%Y-%m-%d %r" "%s"                  # in debugging mode we don't mind the cycles and don't use TLS_DIFFTIME_SET
          fi
```

Looking at your line `` date -d 2140805982 '+%Y-%m-%d %r'``: The caller is for sure the determination of the TLS_TIME around L13878. 

So basically that can't be the culprit where it hangs or loops? (which one is it according to the typescript file generated?)

**Comment by bjorn-wiberg** [comment]
Hello drwetter!

Attaching a typescript from:

```
script -a mydebug_with_LC.script -c "SETX=true bash -x ./testssl.sh --debug=6 -P scbbs.nsupdate.info:50992"
```

[mydebug_with_LC.script.gz](https://github.com/drwetter/testssl.sh/files/6249520/mydebug_with_LC.script.gz)

That is, running it wih all the LC_\* etc. variables set to:

```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_COLLATE=sv_SE.UTF-8
LC_CTYPE=sv_SE.UTF-8
LC_MONETARY=sv_SE.UTF-8
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
```

I aborted the run manually after a minute or two, when it was apparent that it was "looping".

The "looping" appears to occur in get_cipher(), where the cipher TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 for some reason yields cipher=TLS_ECDHE_RSA_ for which no match is found by rfc2hexcode().

Short excerpt from the typescript:

```
Protocol  : TLSv1.2
===============================================================================
Cipher    : TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
===============================================================================
Compression: NONE
===============================================================================
TLS server extension "renegotiation info" (id=65281), len=2
TLS server extension "server name" (id=0), len=0
TLS server extension "EC point formats" (id=11), len=8'
||965>  get_cipher(): [[
CONNECTED(00000003)
Protocol  : TLSv1.2
===============================================================================
Cipher    : TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
===============================================================================
Compression: NONE
===============================================================================
TLS server extension "renegotiation info" (id=65281), len=2
TLS server extension "server name" (id=0), len=0
TLS server extension "EC point formats" (id=11), len=8 =~ Cipher *: ([A-Z0-9]+-[A-Za-z0-9-]+|TLS_[A-Za-z0-9_]+|SSL_[A-Za-z0-9_]+) ]]
||966>  get_cipher(): cipher=TLS_ECDHE_RSA_
||970>  get_cipher(): tm_out TLS_ECDHE_RSA_
||541>  tm_out(): printf -- %b TLS_ECDHE_RSA_
|20628>         determine_optimal_sockets_params(): cipher_offered=TLS_ECDHE_RSA_
|20629>         determine_optimal_sockets_params(): [[ TLS_ECDHE_RSA_ == TLS_* ]]
||20630>        determine_optimal_sockets_params(): rfc2hexcode TLS_ECDHE_RSA_
||3441>         rfc2hexcode(): local hexc=
||3442>         rfc2hexcode(): local -i i
||3444>         rfc2hexcode(): (( i=0 ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_ == \T\L\S\_\A\E\S\_\2\5\6\_\G\C\M\_\S\H\A\3\8\4 ]]

(cut)

||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_ == \S\S\L\_\C\K\_\N\U\L\L ]]
||3444>         rfc2hexcode(): (( i++  ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3447>         rfc2hexcode(): [[ -z '' ]]
||3447>         rfc2hexcode(): return 1
|20630>         determine_optimal_sockets_params(): cipher_offered=
|20634>         determine_optimal_sockets_params(): [[ 0 -eq 9 ]]
|20637>         determine_optimal_sockets_params(): false
|20664>         determine_optimal_sockets_params(): false
|20668>         determine_optimal_sockets_params(): ALL_FAILED_SOCKETS=false
|20669>         determine_optimal_sockets_params(): return 0
|20835>         determine_service(): determine_optimal_proto
|20682>         determine_optimal_proto(): local all_failed=true
|20683>         determine_optimal_proto(): local tmp=
|20684>         determine_optimal_proto(): local proto optimal_proto
|20686>         determine_optimal_proto(): false
|20689>         determine_optimal_proto(): [[ -n '' ]]
|20710>         determine_optimal_proto(): for proto in '' -tls1_2 -tls1 -tls1_3 -ssl3 -tls1_1 -ssl2

(and so on)
```

Does this perhaps give some clue?

**Comment by bjorn-wiberg** [comment]
```locale``` returns:

```
bwiberg@glimmer:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=sv_SE.UTF-8
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE=sv_SE.UTF-8
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Unsetting LC_CTYPE and LC_COLLATE appears to help.
Attaching a typescript when having unset LC_CTYPE and LC_COLLATE.

```
script -a mydebug_without_LC_CTYPE_and_LC_COLLATE.script -c "SETX=true bash -x ./testssl.sh --debug=6 -P scbbs.nsupdate.info:50992"
```

[mydebug_without_LC_CTYPE_and_LC_COLLATE.script.gz](https://github.com/drwetter/testssl.sh/files/6249638/mydebug_without_LC_CTYPE_and_LC_COLLATE.script.gz)

Short excerpt from the typescript:

```
Cipher    : TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
===============================================================================
Compression: NONE
===============================================================================
TLS server extension "renegotiation info" (id=65281), len=2
TLS server extension "server name" (id=0), len=0
TLS server extension "EC point formats" (id=11), len=8 =~ Cipher *: ([A-Z0-9]+-[A-Za-z0-9-]+|TLS_[A-Za-z0-9_]+|SSL_[A-Za-z0-9_]+) ]]
||966>  get_cipher(): cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
||970>  get_cipher(): tm_out TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
||541>  tm_out(): printf -- %b TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|20628>         determine_optimal_sockets_params(): cipher_offered=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|20629>         determine_optimal_sockets_params(): [[ TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 == TLS_* ]]
||20630>        determine_optimal_sockets_params(): rfc2hexcode TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
||3441>         rfc2hexcode(): local hexc=
||3442>         rfc2hexcode(): local -i i
||3444>         rfc2hexcode(): (( i=0 ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 == \T\L\S\_\A\E\S\_\2\5\6\_\G\C\M\_\S\H\A\3\8\4 ]]
||3444>         rfc2hexcode(): (( i++  ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 == \T\L\S\_\C\H\A\C\H\A\2\0\_\P\O\L\Y\1\3\0\5\_\S\H\A\2\5\6 ]]
||3444>         rfc2hexcode(): (( i++  ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 == \T\L\S\_\E\C\D\H\E\_\E\C\D\S\A\_\W\I\T\H\_\C\H\A\C\H\A\2\0\_\P\O\L\Y\1\3\0\5\_\S\H\A\2\5\6\_\O\L\D ]]
||3444>         rfc2hexcode(): (( i++  ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 == \T\L\S\_\E\C\D\H\E\_\R\S\A\_\W\I\T\H\_\C\H\A\C\H\A\2\0\_\P\O\L\Y\1\3\0\5\_\S\H\A\2\5\6\_\O\L\D ]]
||3444>         rfc2hexcode(): (( i++  ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 == \T\L\S\_\D\H\E\_\R\S\A\_\W\I\T\H\_\C\H\A\C\H\A\2\0\_\P\O\L\Y\1\3\0\5\_\S\H\A\2\5\6\_\O\L\D ]]
||3444>         rfc2hexcode(): (( i++  ))
||3444>         rfc2hexcode(): (( i < TLS_NR_CIPHERS ))
||3445>         rfc2hexcode(): [[ TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 == \T\L\S\_\E\C\D\H\E\_\R\S\A\_\W\I\T\H\_\A\E\S\_\2\5\6\_\G\C\M\_\S\H\A\3\8\4 ]]
||3445>         rfc2hexcode(): hexc=0xC0,0x30
||3445>         rfc2hexcode(): break
||3447>         rfc2hexcode(): [[ -z 0xC0,0x30 ]]
||3448>         rfc2hexcode(): tm_out 0xC0,0x30
||541>  tm_out(): printf -- %b 0xC0,0x30
||3449>         rfc2hexcode(): return 0
```
Apparently then cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 in get_cipher(), which is correct.

So there appears to be something going on in get_cipher() -- perhaps cat needs LC_ALL=C or similar?

**Comment by bjorn-wiberg** [comment]
- Unsetting LC_CTYPE and LC_COLLATE before calling testssl.sh works.
- Unsetting those (or setting LC_ALL=C) in all cat -v calls is **not** sufficient.

So it appears some of the other utilities/commands used by the script are sensitive to LC_CTYPE and LC_COLLATE.

**Comment by dcooper16** [comment]
I haven't been able to do any testing, but it does seem that how regular expressions are interpreted in Bash depends on the locale (e.g., https://www.gnu.org/software/sed/manual/html_node/Locale-Considerations.html and https://stackoverflow.com/questions/45713960/does-bash-operator-respect-locale).

So, `([A-Z0-9]+-[A-Za-z0-9\-]+|TLS_[A-Za-z0-9_]+|SSL_[A-Za-z0-9_]+)` may work differently depending on the locale setting. It seems as if this could be an issue in many places where testssl.sh uses regular expressions. Although, I don't understand why it is an issue in that case.

**Comment by drwetter** [comment]
If I exactly set your locales, @bjorn-wiberg, again I have a classical case of "works for me"  -- with debug level 0,3,6. :-( [Debian 10]

**Comment by bjorn-wiberg** [comment]
Hello @drwetter!

Thank you for your reply!

> If I exactly set your locales, @bjorn-wiberg, again I have a classical case of "works for me" -- with debug level 0,3,6. :-( [Debian 10]

Hmm, strange... And those locales are available (enabled) e.g. using ```dpkg-reconfigure locales```, too?

```
bwiberg@glimmer:~$ locale -a
C
C.UTF-8
en_US.utf8
POSIX
sv_SE.utf8
```

**Comment by bjorn-wiberg** [comment]
Hello again @drwetter!

Attaching a small demo script which (hopefully) demonstrates the problem with bash regex matching, ranges (in this case [A-Z] in character classes ([A-Z]) and LC_COLLATE=sv_SE.UTF-8.

[swedish_vw_demo.sh.txt](https://github.com/drwetter/testssl.sh/files/6250734/swedish_vw_demo.sh.txt)
(I had to rename it to .txt in order to be able to attach it.)

When I run it, I get:

```
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

It appears that this has problem been encountered in other settings such as databases, too:
https://www.sqlservercentral.com/forums/topic/order-by-name-not-works#post-1644177

A simple work-around would be to skip using the ranges, explicitly specifying the characters A-Z (and a-z).

**Comment by dcooper16** [comment]
> A simple work-around would be to skip using the ranges, explicitly specifying the characters A-Z (and a-z).

That seems like a good idea. I believe we could define variable `AZ="ABC...XYZ"` AND `az="abc...xyz"` and use those variables in the regular expressions rather than `A-Z` and `a-z`. This way the code wouldn't be too ugly.

**Comment by drwetter** [comment]
> Hmm, strange... And those locales are available (enabled) e.g. using dpkg-reconfigure locales, too?

That did it!

@dcooper16 is basically right. But I would like to understand the problem better. Last but not least I am wondering whether the problem can also happen elsewhere. 

Wonder whether unsetting LC_CTYPE (and LC_COLLATE) globally? IDN support?

More later. Call it a day now

**Comment by drwetter** [comment]
I believe it's better to just unset / set to 'C' / 'en_US.UTF8'  LC_COLLATE in order to get **everywhere** the result we intend(ed). It also may affect the few places where we use sort but that should have a negative impact IMO.

Modifying LC_CTYPE: can't tell.

Another option would be getting through all expressions which are relevant and keep this modification in mind for any future work.

Opinions?

**Comment by bjorn-wiberg** [comment]
Hello @drwetter, and a Happy Easter to you!

As LC_ALL overrides all LC_\*, and LANG is only a default if LC_ALL and LC_\* are not set, I believe the best option would be to set LC_ALL=C to ensure proper operation.

**Comment by drwetter** [comment]
Thanks, happy Easter too.

LC_ALL does way more, so I am not sure that's good applying it now, i.e. on a "running system", so to speak.

**Comment by drwetter** [comment]
Thanks for reporting this bug @bjorn-wiberg .

Let me know if the error persists. I tried the fix on my Debian 10 machine with your locale settings
