### ISSUE TITLE
No matching cipher in this list found

### ISSUE THREAD

**Issue by hardware** [drwetter/testssl.sh#187]
List of ciphers :

```
DES-CBC3-SHA:RC4-MD5:DES-CBC-SHA:RC4-SHA:AES128-SHA:AES128-SHA256:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-RSA-AES128-SHA:ECDH-RSA-AES256-SHA:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:AES256-SHA256
```

**Comment by drwetter** [comment]
This is not enough information

**Comment by hardware** [comment]
What ? oO

Your script ask me to report this, so I report...

![screen](http://i.imgur.com/7Up9DXc.png)

What information do you need exactly?

**Comment by drwetter** [comment]
Am 6. September 2015 10:19:58 MESZ, schrieb hardware <notifications@github.com>:
>What ? oO
>
>Your script ask me to report this, so I report...
>
>![screen](http://i.imgur.com/7Up9DXc.png)
>
>What information do you need exactly?

Sorry about the short reply but that just  wasn't enough.

Please reopen with the whole output.

Thx, Dirk

**Comment by hardware** [comment]
Ok, do this ;)
