### ISSUE TITLE
[BUG / possible BUG]

### ISSUE THREAD

**Issue by tsion123456** [drwetter/testssl.sh#1873]
when running testssl --file result
where result is nmap grepable output
only the first port is being scanned!
testssl ignore other ports

**Comment by drwetter** [comment]
Why did you remove the template? It is there for a reason. You gotta be a bit more verbose.

**Comment by tsion123456** [comment]
what template?? i didn't removed nothing

**Comment by drwetter** [comment]
![image](https://user-images.githubusercontent.com/8036727/115569097-32384800-a2bd-11eb-87ed-58b79f6921b2.png)

**Comment by drwetter** [comment]
Let me know when you have new info, I'll reopen the issue then.

Thx, Dirk
