### ISSUE TITLE
[Feature request] --tls-strict option to report TLS 1.0/1.1 as (NOT ok) instead of (deprecated)

### ISSUE THREAD

**Issue by definity** [drwetter/testssl.sh#1875]
Include a `--tls-strict` option that would change the severity level for deprecated protocols to high severity.  Specifically, when TLS 1.0 or TLS 1.1 is supported.  In some testing use-cases, deprecated protocol support is not desired.  It would be better to have this option so the tool can be used to test servers where deprecated protocols should not be supported.

I'm thinking of this as a way for the user to have a little more control over what the tool reports as (NOT ok).

**Current output snippet** 
```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
 NPN/SPDY   not offered
 ALPN/HTTP2 http/1.1 (offered)
```

**Example output snippet if this option was enabled**

```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered (NOT ok)
 TLS 1.1    offered (NOT ok)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
 NPN/SPDY   not offered
 ALPN/HTTP2 http/1.1 (offered)
```

**Comment by drwetter** [comment]
Sigh, while I understand the reason behind that, it will be some effort to implement. The logic then would need to be applied also to ciphers, keysize, hash algorithms. 

I rather would vote for expectation profiles #1085 or a rating template  #1108.

As this will be addressed and discussed over there, I am closing this.

Thanks for the feedback though!
