### ISSUE TITLE
[possible BUG] Error in the definition of low_ciphers variables

### ISSUE THREAD

**Issue by qfayet** [drwetter/testssl.sh#1878]
Line 6029 of the file [testssl.sh](https://github.com/drwetter/testssl.sh/blob/3.1dev/testssl.sh), there seems to be a typo :

```bash
     ossl_low_ciphers='LOW:DES:RC2:RC4:MD5:!ADH:!EXP:!NULL:!eNULL:!AECDH'
     # egrep -w '64|56|RC2|RC4|MD5' etc/cipher-mapping.txt | egrep -v 'Au=None|export'
     low_ciphers="00,04, 00,05, 00,09, 00,0C, 00,0F, 00,12, 00,15, 00,1E, 00,20, 00,22, 00, 23, 00,24, 00,25, 00,66, 00,8A, 00,8E, 00,92, C0,02, C0,07, C0,0C, C0,11, C0,33, FF,00, FE,FE, FF,E1, 00,FF"
     sslv2_low_ciphers="01,00,80, 03,00,80, 05,00,80, 06,00,40, 06,01,40, 07,00,c0, 08,00,80, FF,80,00"
```

In the sequence `00,22, 00, 23, 00,24,` of the `low_ciphers` variable, it seems that there is an extra space between `00,` and `23,`.

**Comment by drwetter** [comment]
That doesn't matter technically. In the end the additional space will be processed by ``code2network()`` which removes all spaces (and more).

If you want to correct it for consistency feel free to issue a PR!

**Comment by qfayet** [comment]
OK, thanks for the answer 😊, I was afraid that it could impact the results.

I close the issue, if I can find a little time, I will submit a PR!
