### ISSUE TITLE
Incorrect epoch time at HSTS test

### ISSUE THREAD

**Issue by McNobody** [drwetter/testssl.sh#1879]
The ssltest.sh 3.0 prints:

 Strict Transport Security    15465600 s = 179 days is too short ( >=15465600 seconds recommended), includeSubDomains

The recommended minimum is 180 days = 15552000 s.

**Comment by drwetter** [comment]
Thanks. It' looked line an "off by one second" mistake in 3.0 branch only and would work if it would say `` > 15465600 seconds recommended`` like in 3.1 dev.

But I believe the recommendation should be ``>= 180 days`` (``>= 15552000 seconds``).
