### ISSUE TITLE
No matching cipher in this list found

### ISSUE THREAD

**Issue by hardware** [drwetter/testssl.sh#188]
Link to this issue : https://github.com/drwetter/testssl.sh/issues/187

Here the whole output : http://pastie.org/10400719

**Comment by drwetter** [comment]
Thx for the report.

It's quite odd as all openssl clients 1.0.2 I tried so far to use a wrong protocol to connect. OpenSSL 1.0.1 seems fine, OPenSSL 1.0.2 can only connect if I specify a protocol which is supported.

In my testing I never experienced this so I guess this "only" happens with certain servers.
Workaround will follow.

@PeterMosmans:  What's your opinion on this? Why does

``$OPENSSL s_client -debug -msg -trace -starttls imap -cipher DES-CBC3-SHA:RC4-MD5:DES-CBC-SHA:RC4-SHA:AES128-SHA:AES128-SHA256:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-RSA-AES128-SHA:ECDH-RSA-AES256-SHA:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:AES256-SHA256 -connect 37.59.39.113:143``

fail?

Cheers, Dirk

**Comment by PeterMosmans** [comment]
Will look into it, but from what I can see the used OpenSSL version is the vanilla one ?
```
OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by drwetter** [comment]
Am 6. September 2015 14:21:28 MESZ, schrieb Peter Mosmans <notifications@github.com>:
>Will look into it, but from what I can see the used OpenSSL version is
>the vanilla one ?

 Here, yes. But it doesn't matter. Smells again like a change introduced between the versions 1.0.1 and 1.0.2.  Remember the IIS 6 related issue?

Cheers, Dirk

**Comment by drwetter** [comment]
Seems that server has also a low tolerance for additional ciphers  -- using openssl 1.0.2 and no protocols:

```
./bin/openssl.Linux.x86_64 s_client -cipher DES-CBC3-SHA:RC4-MD5:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA -starttls imap -connect 37.59.39.113:143 </dev/null  >/dev/null && echo OK || echo NOK    
12261440:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
NOK
```
(that works with explicitly defining ``-tls1_2``)

Omitting RC4-MD5:
```
./bin/openssl.Linux.x86_64 s_client -cipher DES-CBC3-SHA:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA -starttls imap -connect 37.59.39.113:143 </dev/null  >/dev/null && echo OK || echo NOK                                                                           
depth=0 C = FR, ST = France, L = Paris, O = MESHUP, OU = MESHUP Web Services, CN = *.meshup.net, emailAddress = admin@meshup.net
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = FR, ST = France, L = Paris, O = MESHUP, OU = MESHUP Web Services, CN = *.meshup.net, emailAddress = admin@meshup.net
verify error:num=21:unable to verify the first certificate
verify return:1
. OK Pre-login capabilities listed, post-login capabilities have more.
DONE
OK
```

Now, to get everybody completely confused I specify instead of ``DES-CBC3-SHA`` ``RC4-MD5``
```
./bin/openssl.Linux.x86_64 s_client -cipher RC4-MD5:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA -starttls imap -connect 37.59.39.113:143 </dev/null  >/dev/null && echo OK || echo NOK
32520256:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
NOK
```
Neither one (``DES-CBC3-SHA`` nor ``RC4-MD5``) is supported (``./testssl.sh -E --starttls imap mail.meshup.net:143``:

```
--> Testing all locally available ciphers per protocol against the server, ordered by encryption strength

Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits        Cipher Suite Name (RFC)
-----------------------------------------------------------------------------------------------------------------------
SSLv2 
SSLv3 
TLS 1 
 xc014   ECDHE-RSA-AES256-SHA           ECDH 384   AES        256         TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                
 xc013   ECDHE-RSA-AES128-SHA           ECDH 384   AES        128         TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                
TLS 1.1 
 xc014   ECDHE-RSA-AES256-SHA           ECDH 384   AES        256         TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                
 xc013   ECDHE-RSA-AES128-SHA           ECDH 384   AES        128         TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                
TLS 1.2 
 xc030   ECDHE-RSA-AES256-GCM-SHA384    ECDH 384   AESGCM     256         TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             
 xc028   ECDHE-RSA-AES256-SHA384        ECDH 384   AES        256         TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             
 xc014   ECDHE-RSA-AES256-SHA           ECDH 384   AES        256         TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                
 xc02f   ECDHE-RSA-AES128-GCM-SHA256    ECDH 384   AESGCM     128         TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             
 xc027   ECDHE-RSA-AES128-SHA256        ECDH 384   AES        128         TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256             
 xc013   ECDHE-RSA-AES128-SHA           ECDH 384   AES        128         TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                

Done now (2015-09-06 19:37) ---> 37.59.39.113:143 (mail.meshup.net) <---
```


```
./bin/openssl.Linux.x86_64 version -a                                                   
OpenSSL 1.0.2-chacha (1.0.2d-dev)
built on: Mon Jul  6 18:05:33 2015
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_USE_BUILD_DATE -static -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_EXPERIMENTAL_JPAKE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/ssl"
```
But also other 1.0.2 versions fail and 1.0.1 version succeed. And: 1.0.2 behaves the same as 1.0.1 if I specify ``-tls1_2``.

Guess cannot hurt to sleep over a proper workaround.

**Comment by richsalz** [comment]
what's the server?  is it MS?  If so, perhaps you are hitting the handshake-size limit bug, triggere by later openssl having more ciphers.

**Comment by drwetter** [comment]
Thx!

No, it's a dovecot IMAP server connected to via STARTTLS. But it appears similar to #99, don't know whether that's what you mean by handshake-size limit bug.

**Comment by richsalz** [comment]
Perhaps join and ask on openssl-users.

**Comment by drwetter** [comment]
will do. thx.

**Comment by hardware** [comment]
Here is my Dovecot TLS configuration, if it helps :

```
ssl = required
ssl_cert = </etc/nginx/ssl/rsa-sha2/meshup.net.cert.pem
ssl_key = </etc/nginx/ssl/rsa-sha2/meshup.net.key.pem
ssl_protocols = !SSLv2 !SSLv3
ssl_cipher_list = EECDH+AESGCM:AES128+EECDH:AES256+EECDH
ssl_prefer_server_ciphers = yes
ssl_dh_parameters_length = 2048
```

**Comment by drwetter** [comment]
Thx, it (fortunately) confirms what I observed.  Maybe I should have not omitted in the cases above that neither ``DES-CBC3-SHA`` nor  ``RC4-MD5`` wa picked.

**Comment by drwetter** [comment]
For the record: The change which broke the whole thing was introduced already in openssl 1.0.1. Specifically ``openssl-1.0.1h`` works as one would expect, ``openssl-1.0.1i`` does not. Command used: 
```
apps/openssl s_client -debug -msg  -starttls imap -cipher DES-CBC3-SHA:RC4-MD5:DES-CBC-SHA:RC4-SHA:AES128-SHA:AES128-SHA256:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-RSA-AES128-SHA:ECDH-RSA-AES256-SHA:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:AES256-SHA256 -connect 37.59.39.113:143
```

**Comment by drwetter** [comment]
Hey @hardware,

there's a workaround now. It worked for me (testing the server info you supplied). 

Still need to report / clarify this on openssl-users....

Cheers, Dirk
