### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by lprada** [drwetter/testssl.sh#1881]
Hi, I run the example docker run --rm -t -v /tmp:/data drwetter/testssl.sh --htmlfile /data/ example.com and I get permission denied errors, what I have to do to export the report out o the docker image

I am using docker dektop in a windows server

![image](https://user-images.githubusercontent.com/57561/117469758-76b61b80-af2c-11eb-94fb-41e6fe1a391c.png)

**Comment by lprada** [comment]
I found a solution 

docker run --rm -t -v /c/sslreports:/data:z drwetter/testssl.sh --htmlfile /data/ example.com

**Comment by tonnyhideyori** [comment]
this problem still persists

**Comment by drwetter** [comment]
see #1974
