### ISSUE TITLE
[BUG] Certificate's expiration time is not UTC

### ISSUE THREAD

**Issue by ashfame** [drwetter/testssl.sh#1895]
**Please check this repo whether this is a known issue** ✅

**Command line / docker command to reproduce**
`/testssl.sh -S blog.ashfame.com`

**Expected behavior**
Upon running the command, the cert expiration time I see is as per my local time zone and not in UTC. Looking for `cert_NotAfter` in source, I can see the comment that they are in UTC, but they are not.

`     fileout "cert_notAfter${json_postfix}" "$expok" "$enddate"       # They are in UTC`

**Your system (please complete the following information):**
 - OS: ``awk -F\" '/PRETTY_NAME/ { print $2 }' /etc/os-release``
 Ubuntu 18.04.4 LTS
 - Platform: ``uname -srm``
Linux 4.19.128-microsoft-standard x86_64

 - Version: ``testssl.sh -b 2>/dev/null | head -4 | tail -2``
 testssl.sh       3.0.5 from https://testssl.sh/
    (29d1f07 2021-05-24 00:31:13 -- )

 - Version if running from git repo: ``git log | head -1``
commit 68299961975320eb4070036245478796f9e47a61

 - OpenSSL: ``testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'``
  Using "OpenSSL 1.1.1  11 Sep 2018" [~79 ciphers]

**Additional context**
Tried it on another linux system and there it took local system time as well.

**Comment by dcooper16** [comment]
I tried this on Ubuntu 20.04 and on MacOS. On MacOS, which uses the HAS_FREEBSDDATE version of `parse_date()`, the output is UTC time. On Ubuntu 20.04, which uses the HAS_GNUDATE version of `parse_date()`, the output is the local time. The results are the same using either testssl.sh 3.0 or 3.1dev.

On Ubuntu 20.04, `date -u -d 'Aug  1 01:32:06 2021 GMT' '+%F %H:%M'` gives the expected results. From the `date` man page:
```
       -u, --utc, --universal
              print or set Coordinated Universal Time (UTC)
```
It also works to use `TZ=GMT date -d 'Aug  1 01:32:06 2021 GMT' '+%F %H:%M'`, and adding `TZ=GMT` is already done in a few other calls to `date`.

**Comment by drwetter** [comment]
A for humans easily readable format is always the best for terminal output IMO, which translates to terminal output in local time is fine. We could think of changing that behavior with a flag like ``--utc``

Personally  I do not see a problem when JSON _would_ show everything in UTC, as it is primarily supposed to be a machine format. The comment however seems to be wrong.

The screen output should whenever possible always be consistent, independent on the OS. That becomes kind of difficult. As David indicated GNU date can translate the output from one TZ format to another. For FreeBSD style IIRC that may be possible, I am not sure though. This is also used for newer OpenBSDs. Older OpenBSD ``date`` binaries are rather.

**Comment by ashfame** [comment]
Agree that JSON output in UTC and terminal output in local time is a good choice. In my case, JSON output is also local time and not UTC. Ran this command: `testssl.sh -S --json blog.ashfame.com` and I get the same local time as if I ran without the `--json` flag.

**Comment by drwetter** [comment]
> Ran this command: testssl.sh -S --json blog.ashfame.com and I get the same local time as if I ran without the --json flag.

yes, as said above.

Bottom line: 
* e.g. ``--utc`` is a feature request
* so is conversion to UTC for JSON which I believe could be UTC. If we stick to local time it would be good to document this (either in JSON or at least in the man pages)
* the comment `` # They are in UTC`` should be removed
* FREEBSDDATE needs to display in localtime (minor bug)

The latter seems easy when looking at the code

```
elif "$HAS_FREEBSDDATE"; then      # FreeBSD, OS X and newer (~6.6) OpenBSD versions
     parse_date() {
          LC_ALL=C TZ=GMT date -j -f "$3" "$2" "$1"
     }

``` 
Note ``TZ=GMT``. Not sure whether there's was another reason for this

**Comment by drwetter** [comment]
> Not sure whether there's was another reason for this

By just running & comparing the output It seems there was none

**Comment by drwetter** [comment]
Maybe it is just easier to display everything in UTC, as David maybe indicated.

@ all: any opinions?

**Comment by drwetter** [comment]
I think I was trying to put the cart in front of the horse. 

It makes more sense displaying everything where needed in UTC, see PRs. A good thing however would be to display a time offset. See #1907

**Comment by drwetter** [comment]
Thanks @ashfame
