### ISSUE TITLE
Backport hostname dependency removal to stable

### ISSUE THREAD

**Issue by tinywrkb** [drwetter/testssl.sh#1897]
It would be great if 09c276ffa2df590b627f84534bf36ed5cae36ddc will be backported into the stable 3.0 branch.  
This would help to drop inetutils package dependency for testssl.sh in Arch Linux.  
This is an Arch Linux specific issue as it's a vanilla distro so it's hard to convince an Arch Linux package maintainer to apply patches to stable releases.

The reason for wanting to get rid of inetutils in Arch Linux described in [this bug report about securetty pam module](https://bugs.archlinux.org/task/45903).

**Comment by drwetter** [comment]
Thanks.

That has been done, see 388f3aea1929cfc8ed1216fc8c8b0123e50ceae8. Not yet in a release 3.0.6 though

**Comment by tinywrkb** [comment]
@drwetter thanks for replying.
