### ISSUE TITLE
HAS_DH_BITS test faulty

### ISSUE THREAD

**Issue by jchax** [drwetter/testssl.sh#190]
On Fedora 21, Fedora 22, RHEL (and rebuilds) 6 and 7, openssl does show the DH bits, eg

$ openssl s_client -connect google.com:443 -cipher ECDH 2>/dev/null </dev/null | grep '^Server Temp Key'
Server Temp Key: ECDH, prime256v1, 256 bits

$ openssl version -a
OpenSSL 1.0.1k-fips 8 Jan 2015
built on: Thu Aug 13 12:19:54 2015
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: -I. -I.. -I../include  [...]
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic 

On Fedora, this was added in this update:
* Thu Feb 13 2014 Tomáš Mráz <tmraz@redhat.com> 1.0.1e-40
- print ephemeral key size negotiated in TLS handshake (#1057715)

On RHEL6 (and rebuilds):
* Fri Jun 06 2014 Tomáš Mráz <tmraz@redhat.com> 1.0.1e-26
- print ephemeral key size negotiated in TLS handshake (#1057715)

On RHEL7 (and rebuilds):
* Wed Feb 12 2014 Tomáš Mráz <tmraz@redhat.com> 1.0.1e-31
- print ephemeral key size negotiated in TLS handshake (#1057715)

I'd guess that a good way to test this is something like this:

[[ $OSSL_VER_MAJOR -eq 1 ]] &&
[[ $OSSL_VER_MINOR == "0.1" ]] &&
! rpm -q openssl --changelog 2>/dev/null | grep -q "print ephemeral key size negotiated in TLS" &&
HAS_DH_BITS=false

I chose something to grep for that fits on a single line above, you might want choose something different.

**Comment by jchax** [comment]
Or, I guess, fitting in with what's already at line 3669:

[[ $OSSL_VER_MAJOR -ne 1 ]] && HAS_DH_BITS=false
[[ "$OSSL_VER_MINOR" == "0.1" ]] && 
! rpm -q openssl --changelog 2>/dev/null | grep -q "print ephemeral key size negotiated in TLS" &&
HAS_DH_BITS=false

The "! rpm ..." line is the only one inserted.

**Comment by drwetter** [comment]
Thx, @jchax.

Two comments. 

1) Better use the binaries distributed by this project. 
2) My test for HAS_DH_BITS sucks. ;-) But what you're suggesting seems worse to me. Probably only applicable to the backport(?) from RH/FC.  Also please note that portability to other platforms -- see rpm command -- is highly appreciated.

It should be tested better this capability of openssl instead relying on version numbers. Let me think about it.

Cheers, Dirk

**Comment by jchax** [comment]
I took into account rpm not being available, at least I think I did, by
discarding stderr (rpm -q --changelog openssl 2>/dev/null) and I tested
it :)   I strongly suspect other platforms haven't done the backport; I
know ubuntu 15.04 hasn't.

I didn't look to see how HAS_DH_BITS was used, but perhaps just looking
for Server Temp Key regardless of the version would be a better approach?

**Comment by drwetter** [comment]
Am 09/17/2015 um 04:00 PM schrieb jchax:
> I took into account rpm not being available, at least I think I did, by
> discarding stderr (rpm -q --changelog openssl 2>/dev/null) and I tested
> it :) I strongly suspect other platforms haven't done the backport; I
> know ubuntu 15.04 hasn't.

Ok, but testssl.sh soon becomes ugly if I would add brew, pkg, apt-cyg, pacman,
etc.. ;-)

> I didn't look to see how HAS_DH_BITS was used, but perhaps just looking
> for Server Temp Key regardless of the version would be a better approach?

that's better but still a handshake is needed. I'll look into that the next days.

Cheers, Dirk

**Comment by jchax** [comment]
I agree completely :)

If there's anything you'd like me to test for this on my collection of RHEL-rebuild and Fedora machines please don't hesitate to ask.

**Comment by drwetter** [comment]
Ok, that was more difficult than I thought.

Bottom line: I should work with the next commit always automagically. If not: there's a hidden cmd line switch ``--has-dhbits`` / ``--has-dh-bits`` (or to set via env: HAS_DH_BITS=true) -- but as said that should never be needed.

I tested it successfully on CentOS 7 which I expect to be similar to your systems mentioned. Please let me know if it doesn't work in FC or on RHEL.

Side note: The backport in CentOS at least has another "server temp key" line in the handshake with a different format to regular openssl and it's different for DH and ECDH. I needed to rewrite that parser.

Cheers, Dirk
