### ISSUE TITLE
Use `EditorConfig` to maintain the consistency of some styling?

### ISSUE THREAD

**Issue by PeterDaveHello** [drwetter/testssl.sh#1901]
Looks like there are some modelines in the shell/perl scripts, but they are not very consistent:

- `vim:tw=95:ts=5:sw=5:et` (`t/61_diff_testsslsh.t`)
- `vim:ts=5:sw=5:expandtab` (`testssl.sh`)
- `vim:ts=5:sw=5:expandtab` (`utils/00_unittest_baseline.sh`)
- `vim:tw=100:ts=5:sw=5:expandtab` (`utils/ccs-injection.bash`)
- `vim:ts=5:sw=5` (`utils/checkcert.sh`)
- `vim:ts=5:sw=5:expandtab` (`utils/create_ca_hashes.sh`)
- `vim:ts=5:sw=5:expandtab` (`utils/curves.bash`)
- `vim:ts=5:sw=5:expandtab` (`utils/generate_static_cipher_lists.sh`)
- `vim:ts=5:sw=5` (`utils/gmap2testssl.sh`)
- `vim:tw=200:ts=5:sw=5:expandtab` (`utils/heartbleed.bash`)
- `vim:ts=5:sw=5` (`utils/make-openssl.sh`)
- `vim:tw=90:ts=5:sw=5` (`utils/make-openssl111.sh`)
- `vim:tw=110:ts=5:sw=5` (`utils/prototype.ssl2proto-check.bash`)
- `vim:tw=110:ts=5:sw=5` (`utils/prototype.tls-protocol-checker.bash`)
- `vim:ts=5:sw=5` (`utils/ticketbleed.bash`)

Some of the shell scripts and most of the perl scripts do not have it:

- `utils/docker-debian10.tls13only.start.sh`
- `utils/docker-nginx.tls13-earlydata.start.sh`
- `utils/hexstream2cipher.sh`
- `utils/hexstream2curves.sh`
- `utils/resume.sh`
- `t/00_testssl_help.t`
- `t/01_testssl_banner.t`
- `t/02_clientsim_txt_parsable.t`
- `t/05_ca_hashes_up_to_date.t`
- `t/10_baseline_ipv4_http.t`
- `t/21_baseline_starttls.t`
- `t/23_client_simulation.t`
- `t/31_isJSON_valid.t`
- `t/32_isHTML_valid.t`
- `t/33_isJSON_severitylevel_valid.t`
- `t/51_badssl.com.t`

There was a pull request mentioned [EditorConfig](https://editorconfig.org/) before: https://github.com/drwetter/testssl.sh/pull/989, as author's editor stripped some whitespace from the end of some lines(trailing spaces). #1898 was also submitted to adjust the indentation styling.

I think it's worth to use a unified and centralized tool like *EditorConfig* to help maintain such styling and config, it'll make the config and files more consistent, be easier to manage and follow, as EditorConfig is a cross-editor tool, even GitHub supports it natively, we could leverage it not only in shell scripts, but also the other text-based files, like Markdown and Dockerfile files.

If you'd like the idea, I can help write one `.editorconfig`, @drwetter what do you think 😄

**Comment by drwetter** [comment]
Hi @PeterDaveHello ,

minor issue. It could be consistent, yes. In general ``vim:ts=5:sw=5:expandtab`` is the right thing. Termwidth is a private setting which should everybody decide for him/herself.

I have no clue about EditorConfig. The benefit I see is that it seems editor-independent. It worked somehow in the past though. If it helps: sure! But for vim: has one to to use a plugin and the modeline can stay?

**Comment by PeterDaveHello** [comment]
@drwetter unfortunately, vim needs plug-in, yes, and I don't suggest to keep modeline, as you can see the reasons above, they are inconsistent everywhere, hard to maintain and follow, however, maybe you've already have those configs in your personal vimrc, which means you won't really need them?

**Comment by drwetter** [comment]
@PeterDaveHello : .vimrc is globally (to the user) or I suspect at least becomes ugly when one tries to configure each file / file classes.

As a maintainer I don't like vim plugins, so for me there's no other option keeping the modeline. Sorry.

But what is the worst thing which happens when a modeline is encountered and somebody else is editing this file and the editor supports .editorconfig? I do not see a problem here.

For consistency reasons the first batch can have the same line ``vim:ts=5:sw=5:expandtab``.

**Comment by PeterDaveHello** [comment]
Besides the maintainable effort to keep them(EditorConfig + vim modeline across files) all up-to-date, EditorConfig is actually more powerful as it can handle something like the trailing spaces, final newline char, etc. Can even be used with the linters to make sure the styling consistency. So would be great if we can just use it. Unless you really don't like it, even though many projects, IDEs and GitHub support it, I can still send a PR to keep those modeline consistent first ;)

BTW, I used to prevent vim plugins, only installed a very few of them until now, EditorConfig is one of them worth it 😄

**Comment by drwetter** [comment]
The convincing deadline has been passed already with my last reply ;-) 

But to get this solved: you didn't answer my question whether there's a conflict using it when there's a modeline.

**Comment by PeterDaveHello** [comment]
From what I know it would follow EditorConfig, not vim itself.

**Comment by drwetter** [comment]
Then everybody should be happy?

**Comment by PeterDaveHello** [comment]
I might just be picky about maintainability, but you are the maintainer here, so I will just send pull requests to make vim modeline consistent and add .editorconfig, sounds good enough? 😉

**Comment by drwetter** [comment]
That sounds perfect!

The main goal from my side is that it would be consistent for others using EditorConfig.

**Comment by PeterDaveHello** [comment]
Should be done basically 🎉 
Could have more enhancement later.
