### ISSUE TITLE
[BUG] missing LF (and indentation) when server with client certificate required being scanned

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1915]
3.1dev:

![image](https://user-images.githubusercontent.com/8036727/122239274-17e7a880-cec1-11eb-82ee-dbadb98140e9.png)

3.0 (misses indentation only):
![image](https://user-images.githubusercontent.com/8036727/122239643-6432e880-cec1-11eb-824a-fffb5124291d.png)

**Comment by dcooper16** [comment]
Hi Dirk,

Just a guess, but this seems to have been introduced by https://github.com/drwetter/testssl.sh/commit/17e6802fb41d1566eb46345814872ba67cc885f9:
```
       pr_bold " BREACH"; out " ($cve)                    "
           if "$CLIENT_AUTH"; then
                outln "cannot be tested (server side requires x509 authentication)"
-               fileout "$jsonID" "INFO" "cannot be tested, server side requires x509 authentication" "$cve" "$cwe"
-               return 7
+               fileout "$jsonID" "INFO" "was not tested, server side requires x509 authentication" "$cve" "$cwe"
           fi
```
I don't know if it was accidental that the "return 7" line was removed, but currently the test for the BREACH vulnerability is run even after this message is printed, which doesn't seem correct.

**Comment by drwetter** [comment]
Thanks, David!

3.1dev follows later when I can spare more time :-(
