### ISSUE TITLE
Default settings should test all resolved addresses

### ISSUE THREAD

**Issue by bert128** [drwetter/testssl.sh#1926]
**Command line / docker command to reproduce**
./testssh.sh https://www.google.com

**Expected behavior**
The default behavior should be similar to the ssllabs online ssl tester, whereby all addresses resolved are tested. However, the default for testssl is to ignore IPv6 addresses unless an explicit option (-6) is used.

If the user has supplied an FQDN, the natural assumption should be that they want to perform a thorough test of the FQDN, not a partial test. Making a partial test the default option runs the risk of users assuming the test was thorough when it was not, and drawing false conclusions from the output.

If the user wishes to do an incomplete test, only testing some addresses or protocols then they should be required to explicitly request this scenario. It should never be the default.

**Comment by drwetter** [comment]
That ist the case since a long time. This should also be documented. 

You provided little details how google.com resolved in your country. Here it does with just one IPv4 address -- normally.

**Comment by bert128** [comment]
Singapore:
% host www.google.com
www.google.com has address 74.125.200.105
www.google.com has address 74.125.200.99
www.google.com has address 74.125.200.103
www.google.com has address 74.125.200.104
www.google.com has address 74.125.200.147
www.google.com has address 74.125.200.106
www.google.com has IPv6 address 2404:6800:4003:c00::93
www.google.com has IPv6 address 2404:6800:4003:c00::67
www.google.com has IPv6 address 2404:6800:4003:c00::63
www.google.com has IPv6 address 2404:6800:4003:c00::69

UK:
$ host www.google.com
www.google.com has address 142.250.179.164
www.google.com has IPv6 address 2a00:1450:400e:802::2004

Myanmar:
$ host www.google.com
www.google.com has address 142.250.205.196
www.google.com has IPv6 address 2404:6800:4003:817::2004

USA (Chicago):
$ host www.google.com
www.google.com has address 142.250.191.196
www.google.com has IPv6 address 2607:f8b0:4009:81a::2004

There always seems to be at least 2 addresses wherever it's resolved from, wether using the local resolver provided by the ISP or using public resolvers such as google's own or cloudflare. The AAAA record(s) still show up even from providers without IPv6 support, although they are ignored in that case.
If only a single IPv4 address is resolved, there is a problem somewhere, either google has blocked AAAA lookups from your resolver because it detected a broken configuration, or your resolver is configured to explicitly filter AAAA lookups.

Google was simply an example, for any site with multiple addresses testing of all the addresses should be the default unless the user explicitly requests otherwise. The ssllabs tester works in this way, and it also sees dual stack for www.google.com. 

The user is going to naturally assume that if they specified an FQDN, that whatever the FQDN resolves to will be tested. If it's going to pick one address to test and ignore the others the assumption would be that it would pick the IPv6 address by default, as this is the standard behaviour of every modern operating system.

Also having explicit -4/-6 flags should force it to test *only* that protocol. Currently there is no way to make it ignore IPv4 and only test IPv6.

**Comment by drwetter** [comment]
![image](https://user-images.githubusercontent.com/8036727/122901974-5c09fb80-d34e-11eb-82c9-d4e7d9cf5569.png)

**Comment by drwetter** [comment]
As only a fraction of folks have IPv6 -- since 20+ years -- we cannot test it without causing headaches (delays) for the people which don't.  This is per design at the moment (there are open tickets). Feel free to submit a PR.

You compare apples and oranges: testssl.sh runs on almost every computer with any connectivity. SSLlabs checks run in their data center.

**Comment by bert128** [comment]
dig by default only does A queries, its a DNS testing tool not a general lookup tool:

% dig +short cloudflare.com
104.16.132.229
104.16.133.229
% dig +short -t AAAA cloudflare.com
2606:4700::6810:84e5
2606:4700::6810:85e5

The preferred lookup tool is "host":
% host cloudflare.com
cloudflare.com has address 104.16.132.229
cloudflare.com has address 104.16.133.229
cloudflare.com has IPv6 address 2606:4700::6810:85e5
cloudflare.com has IPv6 address 2606:4700::6810:84e5
cloudflare.com mail is handled by 20 mailstream-central.mxrecord.mx.
cloudflare.com mail is handled by 10 mailstream-west.mxrecord.io.
cloudflare.com mail is handled by 10 mailstream-east.mxrecord.io.

There is also nslookup, which on windows 10 and modern linux also does AAAA lookups (macos seems to be behind).

It's also clear from your above output that while dig has not requested the AAAA records, testssl has found them but performed no tests against them.

**Comment by bert128** [comment]
If you're testing SSL configuration of dual stack sites, then you should be doing so from a dual stack host that is able to reach the targets - not doing so is going to result in incomplete results. 
In fact, you should ALWAYS be doing testing from a host that is able to reach the targets. There are always going to be corner cases where some of the targets are down or otherwise unreachable for various reasons.

Users should experience errors when trying to test a dual stack target from a non dual stack target, as they are using a configuration inadequate for the task. The error message should be clear and make them aware of the limitations of their testing setup, rather than leading them to falsely believe that they have completed a thorough test.

If the user then chooses to do a partial test, then they should do so knowingly.

**Comment by drwetter** [comment]
I am just wondering whether you got who wrote the majority of the code, including DNS lookups. So telling me how DNS lookups with different clients work comes a bit strange across. 

Please also stop me telling us what this tool should do. If you don't like it, change it or write code and submit it back. Or at least change your attitude.
