### ISSUE TITLE
Using testssl.sh towards SMTP servers, can put the caller on a DNSBL

### ISSUE THREAD

**Issue by dilyanpalauzov** [drwetter/testssl.sh#1930]
Using `testssl.sh -t smtp ...:25` can put the machine, where testssl.sh was run, on DNS Blacklists.  Putting a server on a DNS Blacklist means, that future emails from that server are likely spam, or just future connections from that server are temporary deferred.

The particular blacklist, that triggers blacklisting when testssl.sh is called, is q.mail-abuse.com (QIL).  The explanation of the blacklist operator is:

> We detected suspicious connection attempts from this IP to our customers which triggered QIL to block this IP. It means this IP attempted an SMTP connection with our customers but does not necessarily mean an email was delivered.

testssl.sh should document the risk on arriving on a DNSBL, when used towards mail servers, and mention in partucular QIL (q.mail-abuse.com) .

**Comment by drwetter** [comment]
Ok...

Have you tried / can you try whether --ids-friendly helps?

I am not particularly knowledged when it comes to BL. Can anybody comment on this, especially about the relevance of the Trendmicro BL? Like important / not so / shares its BL with x other services / pain to get delisted

**Comment by dilyanpalauzov** [comment]
I do not want to test with ids-friendly, since I do not want to blacklist myself again.  What is --ids-friendly supposed to do?

**Comment by drwetter** [comment]
RTFM

**Comment by dilyanpalauzov** [comment]
I was told, that blacklisting an IP address was not a result of TLS tests, but happened four months ago.  The particular reason isn't known any more.

**Comment by drwetter** [comment]
Thx
