### ISSUE TITLE
testssl on non-standard ports

### ISSUE THREAD

**Issue by tghosth** [drwetter/testssl.sh#1931]
Re: 3.1dev

Is it expected that when using nmap greppable output, only port numbers appearing in ports2starttls will be scanned, even if the port is tagged as ssl/http or ssl/https or https? 

Currently it looks like non-standard port numbers are just ignored, even with that tagging. It would be good if there was at least a flag to tell it to take a best efforts approach to ports marked like that...

**Comment by drwetter** [comment]
Good point thanks. First there should be at least a detection of ``ssl`` and ``https``.

**Comment by drwetter** [comment]
looks in my scans like the hint for ssl or https comes at the fourth place:

```
3389/open/tcp//ssl|ms-wbt-server?///
12480/open/tcp//ssl|unknown///
10443/open/tcp//https?///
4443/open/tcp//ssl|https?///
```

Anybody found more for ssl/https?

**Comment by drwetter** [comment]
There's a new file ``utils/gmap2testssl.sh`` which adds a detection of ssl and https at least for the first step. Based on that I created the PR #1938. See commit details for explanation.
 
If there are patterns I should use for matching TLS/SSL enabled ports other than ^(ssl|https) please let me know. I'll probably merge that in ~a week if nobody speaks up.


Second step would be a best effort approach. Off the top of my head I can't tell how to do that without adding too many ports where no TLS/SSL enabled services runs. Ideas / discussion is appreciated.

**Comment by tghosth** [comment]
Thanks for taking a look at this, your suggestion sounds sensible, I will try and provide better feedback when I next am looking at the tool

**Comment by drwetter** [comment]
closing it. best effort sounds of of reach right now.
