### ISSUE TITLE
When executing testss.sh, it reports line 10522: 19959 Segmentation fault      (core dumped) 

### ISSUE THREAD

**Issue by okayabc** [drwetter/testssl.sh#1932]
I execute ./testssl.sh  www.baidu.com, it reports:

Testing all IPv4 addresses (port 443): 14.215.177.38 14.215.177.39
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Start 2021-07-21 15:02:40        -->> 14.215.177.38:443 (www.baidu.com) <<--

 Further IP addresses:   14.215.177.39 
 rDNS (14.215.177.38):   --
./testssl.sh: line 20741: 19353 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 19357 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 19360 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 19363 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 19366 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
 Your OpenSSL cannot connect to 14.215.177.38:443

**Comment by drwetter** [comment]
There's a template for bug reports for a reason. Thus I am closing this.

If you search here you'll find out it's a known problem likely of your platform and the openssl provided and there's a known cure.

Sorry,
