### ISSUE TITLE
Question about Segmentation fault      (core dumped) 

### ISSUE THREAD

**Issue by okayabc** [drwetter/testssl.sh#1934]
_Feel free to remove this line but please stick to the template. We would like to reproduce the bug and therefore need concise information. Depending on the completeness of your information provided we might close your issue otherwise. _

**Please check this repo whether this is a known issue**
Have found similar questions in repo, but not get a satisfied answer.

**Command line / docker command to reproduce**
 ./testssl.sh www.baidu.com

**Expected behavior**
Give info about the destination site.

**Your system (please complete the following information):**
 - OS: SUSE Linux Enterprise Server 12 SP5
 - Platform: Linux 4.12.14-120-default x86_64
 - Version:3.1dev
 - Version if running from git repo: 56dcbcdc1547c7198232f76dbd1fe02ed367deab
 - OpenSSL: ./bin/openssl.Linux.x86_64
 
**Additional context**
###########################################################
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (56dcbcd 2021-06-22 08:25:29 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]
 on linux-my7i:./bin/openssl.Linux.x86_64
 (built: "Jan 18 17:12:17 2019", platform: "linux-x86_64")

Testing all IPv4 addresses (port 443): 14.215.177.39 14.215.177.38
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Start 2021-07-21 15:57:55        -->> 14.215.177.39:443 (www.baidu.com) <<--

 Further IP addresses:   14.215.177.38 
 rDNS (14.215.177.39):   --
./testssl.sh: line 20741: 28301 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 28306 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 28309 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 28312 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
./testssl.sh: line 20741: 28315 Segmentation fault      (core dumped) $OPENSSL s_client $(s_client_options "$proto $BUGS -connect "$NODEIP:$PORT" -msg $PROXY $SNI") < /dev/null > $TMPFILE 2>> $ERRFILE
 Your OpenSSL cannot connect to 14.215.177.39:443

**Comment by drwetter** [comment]
ok, thanks

**Comment by drwetter** [comment]
For the time being please use ``--openssl=/usr/bin/openssl``

**Comment by okayabc** [comment]
It works now,thanks! 
May i ask another question, if i want to disable renegotiation with openssl1.1, how should i do?

**Comment by drwetter** [comment]
see also #1275

**Comment by drwetter** [comment]
Would it be possible for you to determine why it segfaulted?
 
``$PATHTOTESTSSL/bin/openssl.Linux.x86_64 s_client -tls1 -connect 14.215.177.39:443 -servername www.baidu.com </dev/null`` ?

and then putting ``gdb --args`` in front of the command above? Pasting / gisting the output would be appreciated.

Just want to get a clue what the problem is as Suse-flavors have not shown this in the past.
