### ISSUE TITLE
Testssl Deletes All Content of Input File

### ISSUE THREAD

**Issue by catchingknives** [drwetter/testssl.sh#1935]
**Command line / docker command to reproduce**
1. Find targets with nmap 
```
nmap -p443 -oG nmap-targets.txt 192.168.178.1-254
```

2. File is filled with targets
```
ls -l nmap-targets.txt
-rw-r--r--  1 user  staff  1039 Jul 23 14:35 nmap-targets.txt
```

3. Scan only those targets with testssl
```
./testssl.sh -p --file=nmap-targets.txt --csvfile=results.csv --append
```

4. Error:
```
Fatal error: Couldn't find any open port in nmap-targets.txt
```

5. Reason: File is empty
```
 ls -l nmap-targets.txt
-rw-r--r--  1 user  staff  0 Jul 23 14:39 nmap-targets.txt
```

Taking away write permissions to the file results in:
```
./testssl.sh: line 19008: nmap-targets.txt: Operation not permitted
```

**Expected behavior**
testssl scans hosts from file and does not delete them

**Your system (please complete the following information):**
 - OS: ``macOS 11.5``
 - Platform: ``Darwin 20.6.0 x86_64``
 - Version: ``testssl.sh       3.0.5 from https://testssl.sh/
    (ca558a9 2021-06-19 15:21:04 -- )``
 - Version if running from git repo: ``commit ca558a9c08b1ed2f81a6dcb0edb9c6895aec1fd8``
 - OpenSSL: ``./bin/openssl.Darwin.x86_64`` (LibreSSL 2.8.3)
 

**Additional context**
I use fish but now of at least one other person who has the same problem using bash

**Comment by dcooper16** [comment]
Looking at the source code, it appears that testssl.sh assumes that the nmap file name does not end in ".txt". It seems that this should be fixed, but for the moment the issue can be avoided by renaming "nmap-targets.txt" to something that doesn't end in ".txt".

@drwetter : Do you remember if there was a reason for not just always creating the new file in $TEMPDIR? Was there a reason for wanting the new file to be available (even when not in debug mode) after testssl.sh completed?

**Comment by drwetter** [comment]
Normally it expects a different extension, yes. The idea was that nmap always generates in most of the workflows the file with the gmap extension. Then testssl.sh removes that extension and adds ``.txt`` for the temporary file. There is a statement if opening for writing is not possible it tries to fallback to the tempdir. However this is not working.

To answer your question, @dcooper16: I believe the idea was to persist the generated file just for doing a good service to the user.

**Comment by drwetter** [comment]
Thanks for reporting @catchingknives . Fixed

**Comment by catchingknives** [comment]
Thanks so much! 🙌🏼
