### ISSUE TITLE
Find out what the problem is with CI runs

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1956]
**Which version are you referring to**
3.0.x

The last commits had a problem. It failed in ``t/08_isHTML_valid.t``, with the message ``Failed test 'HTML file created with --debug 4 matches HTML file created without --debug'``. Cause was (diff output):

```
- DNS CAA RR (experimental)    available - please check for match with &quot;Issuer&quot; above: heise.de has no CAA record
+ DNS CAA RR (experimental)    not offered
```

This needs to be solved.

**Comment by dcooper16** [comment]
Hi Dirk,

I believe that I've discovered the source of the problem, and it is an issue in both 3.0.x and 3.1dev.

The call to `get_caa_rr_record()` is of the form:
```
caa="$(get_caa_rr_record $caa_node)"
```
The `get_caa_rr_record()` includes the line `debugme echo $raw_caa`. So, if debugging is turned on, then the contents of `$raw_caa` get included in `$caa`. For me, when I use 3.0.x, `get_caa_rr_record()` uses `host -t`, which results in `$raw_caa` being set to "heise.de has no CAA record". With 3.1dev, `get_caa_rr_record()` uses `dig`, which leaves `$raw_caa` empty.

`certificate_info()` assumes that if `$caa` is not empty, then DNS CAA RR is available, even if `$caa` just contains "... has no CAA record."

I would guess that just removing the `debugme` statement from `get_caa_rr_record()` (from both 3.0.x and 3.1dev) will fix the problem.

**Comment by drwetter** [comment]
Thanks, David. 

I haven't had the time to look into that yet. Just filed this before it's getting lost. What puzzled me that it didn't happen for 3.1dev yet. I occurred for 3.0, there randomly. But I guess the code tells the truth.

**Comment by dcooper16** [comment]
> What puzzled me that it didn't happen for 3.1dev yet. I occurred for 3.0, there randomly.

The issue seems to be #1949. It changed `get_caa_rr_record()` so that `dig` is the third choice of resolver rather than the first choice. In 3.1dev, `dig` is still the first choice.

**Comment by drwetter** [comment]
Good point. 

This problem exists not only in ``.get_caa_rr_record()``, e.g. ``f5_hex*()``. But it seems GHA CI caught it here only. I'll try to redirect debugme to stderr which I believe should catch all instances. That spolis the trick with redirection from fd 1 to fd 0 when people want to redirect JSON to fd 2 but I believe nobody will run this szenario in debug mode.
