### ISSUE TITLE
[BUG / possible BUG] XMPP scan of URI with numbers only fails to record IP

### ISSUE THREAD

**Issue by multiflexi** [drwetter/testssl.sh#1961]
When 01337.io, 01337.ru or 616.pub is scanned, the IP in results is not 157.90.24.30 but the domain name. It happens when XMPP, STARTTLS is scanned, not for regular TLS scans.

**Command line / docker command to reproduce**
testssl.sh -t xmpp -oA 0137a 01337.io:5222

**Expected behavior**
IP address 157.90.24.30 (for 01337.io)  as a value for key [ip].

[0137a.zip](https://github.com/drwetter/testssl.sh/files/6938364/0137a.zip)

**Your system (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Platform: Linux 5.4.0-80-generic x86_64
 - Version: testssl.sh       3.0.5 from https://testssl.sh/
 - Version if running from git repo: 91523be19494543f5c1bcf3dcab60498196c485d

**Comment by drwetter** [comment]
Thanks, you mean here?

```
              "targetHost"      : "01337.io",
                    "ip"              : "01337.io",
                    "port"           : "5222",
```

Looks like the identification by a pattern for hostnames is somehow wrong.  

Need to look later into it.

**Comment by dcooper16** [comment]
The contents of the URI doesn't seem to matter. I think this will happen whenever STARTTLS is used with XMPP. I got the same results with another DNS name:
```
                    "targetHost"      : "jabber.tcpreset.net",
                    "ip"              : "jabber.tcpreset.net",
                    "port"            : "5222",
```
The reason seems to be the following from `determine_service()`:
```
if [[ "$protocol" == xmpp ]]; then
     # for XMPP, openssl has a problem using -connect $NODEIP:$PORT. thus we use -connect $NODE:$PORT instead!
     NODEIP="$NODE"
```
`$NODE` contains the DNS name, which is (in most cases) used for the "targetHost".`$NODEIP` is what is used for the "ip".

**Comment by drwetter** [comment]
still a problem for 3.0
