### ISSUE TITLE
Replace Travis' "Build passing" banner by GHA banner (or removal)

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1964]
Can somebody give a hand here?

I am referring to this line in the readme: ``[![Travis CI Status](https://travis-ci.org/drwetter/testssl.sh.svg?branch=3.1dev)](https://travis-ci.org/drwetter/testssl.sh)``

**Comment by jauderho** [comment]
Here you go, this should do the trick. #1965
