### ISSUE TITLE
Has server cipher order … no matching cipher in this list found (pls report this)…

### ISSUE THREAD

**Issue by GaryGapinski** [drwetter/testssl.sh#197]
Using version 2.7dev.

Came across this using a restricted cipher set.

Received

    Has server cipher order?     no matching cipher in this list found (pls report this): DES-CBC3-SHA:RC4-MD5:DES-CBC-SHA:RC4-SHA:AES128-SHA:AES128-SHA256:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-RSA-AES128-SHA:ECDH-RSA-AES256-SHA:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:AES256-SHA256  . 
    Cipher order
        TLSv1.2:   ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384

Have an Apache HTTP server 2.4.7 restricted to 

    SSLProtocol TLSv1.2

    SSLHonorCipherOrder On

    SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384

and using an ECDSA certificate.

**Comment by PeterMosmans** [comment]
Hi @GaryGapinski , which version of OpenSSL are you using ? This could rule out certain issues with ciphers..

Thanks,

Peter

**Comment by GaryGapinski** [comment]
Hello, @PeterMosmans:

Using the captive one: …`Using "OpenSSL 1.0.2-chacha (1.0.2d-dev)" [~181 ciphers]`.

Regards,

Gary

**Comment by drwetter** [comment]
I would need the server pls (PM is fine). 

The certificate type doesn't matter, see e.g. ``./testssl.sh --ip=one -S -P -E beginend.net``

**Comment by GaryGapinski** [comment]
@drwetter — PM (email) sent.

**Comment by drwetter** [comment]
Thx for reporting @GaryGapinski ! Fix follows.

**Comment by drwetter** [comment]
see 23802e219d1307d6a41e94de6bb08cb6751f28bf

**Comment by GaryGapinski** [comment]
Fix (23802e219d1307d6a41e94de6bb08cb6751f28bf) confirmed. Thanks much for the speedy correction. Fingerfertigkeit!

**Comment by drwetter** [comment]
:-)
