### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by tonnyhideyori** [drwetter/testssl.sh#1974]
**Command line / docker command to reproduce**
docker run  --rm t -v /tm:/data drwetter/testssl.sh --jsonfile  /data/  xx.com

**Expected behavior**
/usr/local/bin/testssl.sh: line 1381: /data//xx_p443-20210903-1534.json: Permission denied

**Your system (please complete the following information):**
 - OS: ``Ubuntu 18.04.5 LTS``
 - Platform: ``Linux 5.4.0-81-generic x86_64``
 -version ``3.1dev``

**Additional context**
what would have been the reason for this error

**Comment by drwetter** [comment]
``/tmp`` not ``/tm`` or you have messed up the permissions from ``/tmp``. Or your image ``t`` is the cuplrit

**Comment by tonnyhideyori** [comment]
I have a question, why the permission is denied when I change the /tmp to something else
