### ISSUE TITLE
Only test cipher categories

### ISSUE THREAD

**Issue by righettod** [drwetter/testssl.sh#1978]
**Which version are you referring to**
3.1dev - commit 05ef9f91b686611d33a8406e402c2235a649ba63

First, thank a lot for this amazing and very useful projject 🥇 

Is there an option to only test **cipher categories**:

![image](https://user-images.githubusercontent.com/1573775/132210383-8391626f-fe3e-4721-966c-ef86e4c8510b.png)

My goal is to just perform the protocols (`-p`) + vulnerabilities (`-U`) + cipher categories tests for an URL.

Thanks a lot in advance for your feedback 😃

**Comment by drwetter** [comment]
Hi Dominique,

``testssl.sh -s -p -U <target>``  is  your friend.

Cheers, Dirk

PS: pls keep this open as I'd like to reuse this to add "cipher categories" to the internal help which is currently not the case yet (``testssl.sh --help | grep catego`` is empfy -- or if anyone feels like doing this: pls go ahead for both branches).

**Comment by righettod** [comment]
Hi Dirk,

Thanks a lot for you reply and precious help 👍

Have a nice day

Dominique
