### ISSUE TITLE
Date conversion problem with locale

### ISSUE THREAD

**Issue by pbdname** [drwetter/testssl.sh#198]
The date conversions fail when locale is set to something other than "C". I would suggest setting LC_ALL before any "date" execution.

```
621c621
<                     HTTP_TIME=$(date --date="$HTTP_TIME" "+%s")

---
>                     HTTP_TIME=$(LC_ALL=C date --date="$HTTP_TIME" "+%s")
623c623
<                     HTTP_TIME=$(date -j -f "%a, %d %b %Y %T %Z" "$HTTP_TIME" "+%s" 2>>$ERRFILE) # the trailing \r confuses BSD flavors otherwise

---
>                     HTTP_TIME=$(LC_ALL=C date -j -f "%a, %d %b %Y %T %Z" "$HTTP_TIME" "+%s" 2>>$ERRFILE) # the trailing \r confuses BSD flavors otherwise
1998,1999c1998,1999
<           enddate=$(date --date="$($OPENSSL x509 -in $HOSTCERT -noout -enddate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M %z")
<           startdate=$(date --date="$($OPENSSL x509 -in $HOSTCERT -noout -startdate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M")

---
>           enddate=$(LC_ALL=C date --date="$($OPENSSL x509 -in $HOSTCERT -noout -enddate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M %z")
>           startdate=$(LC_ALL=C date --date="$($OPENSSL x509 -in $HOSTCERT -noout -startdate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M")
2001,2002c2001,2002
<           enddate=$(date -j -f "%b %d %T %Y %Z" "$($OPENSSL x509 -in $HOSTCERT -noout -enddate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M %z")
<           startdate=$(date -j -f "%b %d %T %Y %Z" "$($OPENSSL x509 -in $HOSTCERT -noout -startdate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M")

---
>           enddate=$(LC_ALL=C date -j -f "%b %d %T %Y %Z" "$($OPENSSL x509 -in $HOSTCERT -noout -enddate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M %z")
>           startdate=$(LC_ALL=C date -j -f "%b %d %T %Y %Z" "$($OPENSSL x509 -in $HOSTCERT -noout -startdate 2>>$ERRFILE | cut -d= -f 2)" +"%F %H:%M")
```

**Comment by drwetter** [comment]
Hi @pbdname,

Thx for reporting. 

I couldn't reproduce a failure by mangling either LC_TIME or even LC_ALL. Do you have an example for me?

Cheers, Dirk

**Comment by pbdname** [comment]
Sorry, I cannot reproduce it on Linux machine (Debian 8.1) neither. However on FreeBSD (10.2):

With "C" locale:

```
# export LC_ALL=C
# locale 
LANG=cs_CZ.UTF-8
LC_CTYPE="C"
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=C
# ./testssl.sh 127.0.0.1 > /dev/null
#
```
With "cs_CZ.UTF-8":
```
# export LC_ALL=cs_CZ.UTF-8
# locale 
LANG=cs_CZ.UTF-8
LC_CTYPE="cs_CZ.UTF-8"
LC_COLLATE="cs_CZ.UTF-8"
LC_TIME="cs_CZ.UTF-8"
LC_NUMERIC="cs_CZ.UTF-8"
LC_MONETARY="cs_CZ.UTF-8"
LC_MESSAGES="cs_CZ.UTF-8"
LC_ALL=cs_CZ.UTF-8
# ./testssl.sh 127.0.0.1 > /dev/null
Failed conversion of ``Jan 18 11:01:50 2038 GMT'' using format ``%b %d %T %Y %Z''
date: illegal time format
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``Oct 30 11:01:50 2013 GMT'' using format ``%b %d %T %Y %Z''
date: illegal time format
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
```

**Comment by drwetter** [comment]
Thx, now I now where to look at. 

Can reproduce it under FreeBSD as well.

**Comment by drwetter** [comment]
Fix follows. Just should out loud if it doesn't work for you.

**Comment by robertlagrant** [comment]
Is this back? If I do testssl.sh https://google.com I get it. E.g.

```
Testing server defaults (Server Hello) 

 TLS extensions (standard)    "renegotiation info/#65281" "session ticket/#35" "next protocol/#13172" "EC point formats/#11" "extended master secret/#23" "signed certificate timestamps/#18"
                              "application layer protocol negotiation/#16"
 Session Ticket RFC 5077 hint 100800 seconds but: PFS requires session ticket keys to be rotated < daily !
 SSL Session ID support       yes
 Session Resumption           Tickets: yes, ID: yes
 TLS clock skew               -1 sec from localtime
 Signature Algorithm          SHA256 with RSA
 Server key size              RSA 2048 bits
 Fingerprint / Serial         SHA1 8A97F680B8CE113A89182444A2484DBE6E3EECE9 / 606FE6CD94FCD766
                              SHA256 BD34FA414F08BBC25A3CDB7D7F2D5D48B0FEE10366CE0CEE5C4A7E230DF1A2CB
 Common Name (CN)             *.google.com
 subjectAltName (SAN)         *.google.com *.android.com *.appengine.google.com *.cloud.google.com *.db833953.google.cn *.g.co *.gcp.gvt2.com *.google-analytics.com *.google.ca *.google.cl *.google.co.in
                              *.google.co.jp *.google.co.uk *.google.com.ar *.google.com.au *.google.com.br *.google.com.co *.google.com.mx *.google.com.tr *.google.com.vn *.google.de *.google.es
                              *.google.fr *.google.hu *.google.it *.google.nl *.google.pl *.google.pt *.googleadapis.com *.googleapis.cn *.googlecommerce.com *.googlevideo.com *.gstatic.cn *.gstatic.com
                              *.gvt1.com *.gvt2.com *.metric.gstatic.com *.urchin.com *.url.google.com *.youtube-nocookie.com *.youtube.com *.youtubeeducation.com *.yt.be *.ytimg.com
                              android.clients.google.com android.com developer.android.google.cn developers.android.google.cn g.co goo.gl google-analytics.com google.com googlecommerce.com
                              source.android.google.cn urchin.com www.goo.gl youtu.be youtube.com youtubeeducation.com yt.be 
 Issuer                       Google Internet Authority G2 (Google Inc from US)
 Trust (hostname)             Ok via SAN (same w/o SNI)
 Chain of trust               Ok   
 EV cert (experimental)       no 
 Certificate Expiration       Failed conversion of ``2018-05-30 19:52'' using format ``%F %H:%M %z''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
-17614 >= 60 days (UTC: 2018-03-07 19:26 --> 2018-05-30 19:52)
```

My locale info:
```
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

**Comment by drwetter** [comment]
Can't reproduce it (e.g. FreeBSD 9, 2.9dev, LC_ALL=en_GB.UTF-8) . "Certificate Expiration" is not the latest & greatest, should be Certificate Validity (UTC).

More input (OS, testssl.sh version) is needed.

**Comment by robertlagrant** [comment]
Apologies, yes. What a chump.
```
$ uname -a
Darwin DRA-W10-MAC027 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$ testssl.sh --version

###########################################################
    testssl.sh       2.9.5 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2n  7 Dec 2017" [~125 ciphers]
 on DRA-W10-MAC027:/usr/local/opt/openssl/bin/openssl
 (built: "reproducible build, date unspecified", platform: "darwin64-x86_64-cc")
```

**Comment by drwetter** [comment]
I own no Mac, but normally FreeBSD 9 is the closest thing (except bash which is version 3 under Darwin). I ran 2.9.5 under FreeBSD 9 and it worked for me:

```
myhost:~/git.testssl.sh|% export LANG="en_GB.UTF-8"                           
myhost:~/git.testssl.sh|% export LC_ALL="en_GB.UTF-8"                                                                                                      
myhost:~/git.testssl.sh|% ./testssl.sh-2.9.5 -S --proxy=REDACTED https://google.com                                                                      

###########################################################
    testssl.sh-2.9.5       2.9.5 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~197 ciphers]
 on myhost:./bin/openssl.FreeBSD.amd64
 (built: "May 12 15:47:16 2017", platform: "BSD-x86_64")


 Start 2018-03-25 18:19:23        -->> 172.217.21.206:443 (google.com) <<--

 Via Proxy:              REDACTED 
 further IP addresses:   2a00:1450:4001:818::200e 
 rDNS (172.217.21.206):  fra16s12-in-f14.1e100.net. fra16s12-in-f206.1e100.net.
 Service detected:       HTTP


 Testing server defaults (Server Hello) 

 TLS extensions (standard)    "renegotiation info/#65281" "session ticket/#35" "next protocol/#13172" "EC point formats/#11" "extended master secret/#23"
                              "signed certificate timestamps/#18" "application layer protocol negotiation/#16"
 Session Ticket RFC 5077 hint 100800 seconds but: PFS requires session ticket keys to be rotated < daily !
 SSL Session ID support       yes
 Session Resumption           Tickets: yes, ID: yes
 TLS clock skew               -1 sec from localtime
 Signature Algorithm          SHA256 with RSA
 Server key size              RSA 2048 bits
 Fingerprint / Serial         SHA1 8A97F680B8CE113A89182444A2484DBE6E3EECE9 / 606FE6CD94FCD766
                              SHA256 BD34FA414F08BBC25A3CDB7D7F2D5D48B0FEE10366CE0CEE5C4A7E230DF1A2CB
 Common Name (CN)             *.google.com
 subjectAltName (SAN)         *.google.com *.android.com *.appengine.google.com *.cloud.google.com *.db833953.google.cn *.g.co *.gcp.gvt2.com
                              *.google-analytics.com *.google.ca *.google.cl *.google.co.in *.google.co.jp *.google.co.uk *.google.com.ar *.google.com.au
                              *.google.com.br *.google.com.co *.google.com.mx *.google.com.tr *.google.com.vn *.google.de *.google.es *.google.fr *.google.hu
                              *.google.it *.google.nl *.google.pl *.google.pt *.googleadapis.com *.googleapis.cn *.googlecommerce.com *.googlevideo.com
                              *.gstatic.cn *.gstatic.com *.gvt1.com *.gvt2.com *.metric.gstatic.com *.urchin.com *.url.google.com *.youtube-nocookie.com
                              *.youtube.com *.youtubeeducation.com *.yt.be *.ytimg.com android.clients.google.com android.com developer.android.google.cn
                              developers.android.google.cn g.co goo.gl google-analytics.com google.com googlecommerce.com source.android.google.cn urchin.com
                              www.goo.gl youtu.be youtube.com youtubeeducation.com yt.be 
 Issuer                       Google Internet Authority G2 (Google Inc from US)
 Trust (hostname)             Ok via SAN (same w/o SNI)
 Chain of trust               Ok   
 EV cert (experimental)       no 
 Certificate Expiration       66 >= 60 days (UTC: 2018-03-07 20:26 --> 2018-05-30 20:52)
 # of certificates provided   3
 Certificate Revocation List  http://pki.google.com/GIAG2.crl
 OCSP URI                     http://clients1.google.com/ocsp
 OCSP stapling                --
 OCSP must staple             no
 DNS CAA RR (experimental)    OK (issue: pki.goog)
 Certificate Transparency     yes (TLS extension)


 Done 2018-03-25 18:19:32 [0010s] -->> 172.217.21.206:443 (google.com) <<--
```

Either somebody with Darwin or you can try to reproduce it without brew by git pull from 2.9.5.
Or ask the brew guys @ https://github.com/Homebrew/homebrew-core . I suspect they are still @ 2.9.5-1 or so but that's just a guess.

**Comment by drwetter** [comment]
brew seems up to date: https://github.com/Homebrew/homebrew-core/search?q=testssl&type=Commits&utf8=%E2%9C%93 

Did you miss an update?

**Comment by drwetter** [comment]
Anybody with Darwin to verify this under 2.9.5-3?

**Comment by bknowles** [comment]
On Apr 4, 2018, at 5:13 AM, Dirk Wetter <notifications@github.com> wrote:

> Anybody with Darwin to verify this under 2.9.5-3?

I just updated with brew, and I'm on 2.9.5-3.  It seems to work for me:

$ ls -la `which testssl.sh`
lrwxr-xr-x  1 brad  admin  40  4 Apr 08:52 /usr/local/bin/testssl.sh -> ../Cellar/testssl/2.9.5-3/bin/testssl.sh

$ export LANG="en_GB.UTF-8"
$ export LC_ALL="en_GB.UTF-8"
$ testssl.sh -S https://google.com

###########################################################
    testssl.sh       2.9dev from https://testssl.sh/dev/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on frobgaiju:/Users/brad/src/testssl.sh/bin/openssl.Darwin.x86_64
 (built: "Sep  7 19:34:54 2016", platform: "darwin64-x86_64-cc")


 Start 2018-04-04 08:54:16        -->> 172.217.12.110:443 (google.com) <<--

 further IP addresses:   2607:f8b0:4000:801::200e
 rDNS (172.217.12.110):  atl26s14-in-f14.1e100.net.
 Service detected:       HTTP


 Testing server defaults (Server Hello)

 TLS extensions (standard)    "renegotiation info/#65281" "session ticket/#35" "next protocol/#13172" "EC point formats/#11"
                              "extended master secret/#23" "signed certificate timestamps/#18"
                              "application layer protocol negotiation/#16"
 Session Tickets RFC 5077     100800 seconds (PFS requires session ticket keys to be rotated <= daily)
 SSL Session ID support       yes
 Session Resumption           Tickets: yes, ID: yes
 TLS clock skew               0 sec from localtime
 Signature Algorithm          SHA256 with RSA
 Server key size              RSA 2048 bits
 Fingerprint / Serial         SHA1 D45684BF0B9D9AD42209B272492A203FC198B60E / 2E2436C6F0C98D59
                              SHA256 2C37EB06F4158B12ABC62F760CCB857F93E769AE97D084C348E1F2FCD8B6F968
 Common Name (CN)             *.google.com
 subjectAltName (SAN)         *.google.com *.android.com *.appengine.google.com *.cloud.google.com *.db833953.google.cn *.g.co
                              *.gcp.gvt2.com *.google-analytics.com *.google.ca *.google.cl *.google.co.in *.google.co.jp
                              *.google.co.uk *.google.com.ar *.google.com.au *.google.com.br *.google.com.co *.google.com.mx
                              *.google.com.tr *.google.com.vn *.google.de *.google.es *.google.fr *.google.hu *.google.it
                              *.google.nl *.google.pl *.google.pt *.googleadapis.com *.googleapis.cn *.googlecommerce.com
                              *.googlevideo.com *.gstatic.cn *.gstatic.com *.gvt1.com *.gvt2.com *.metric.gstatic.com
                              *.urchin.com *.url.google.com *.youtube-nocookie.com *.youtube.com *.youtubeeducation.com *.yt.be
                              *.ytimg.com android.clients.google.com android.com developer.android.google.cn
                              developers.android.google.cn g.co goo.gl google-analytics.com google.com googlecommerce.com
                              source.android.google.cn urchin.com www.goo.gl youtu.be youtube.com youtubeeducation.com yt.be
 Issuer                       Google Internet Authority G3 (Google Trust Services from US)
 Trust (hostname)             Ok via SAN (works w/o SNI)
 Chain of trust               Ok
 EV cert (experimental)       no
 Certificate Expiration       69 >= 60 days (2018-03-20 12:53 --> 2018-06-12 11:55 -0500)
 # of certificates provided   2
 Certificate Revocation List  http://crl.pki.goog/GTSGIAG3.crl
 OCSP URI                     http://ocsp.pki.goog/GTSGIAG3
 OCSP must staple             No
 OCSP stapling                --
 DNS CAA RR (experimental)    OK (issue: pki.goog)


 Done 2018-04-04 08:54:42 [0029s] -->> 172.217.12.110:443 (google.com) <<--



Maybe it's an interaction with macOS ?  I'm on Sierra 10.12.6:

$ uname -a
Darwin frobgaiju.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64


--
Brad Knowles <brad@shub-internet.org>

**Comment by drwetter** [comment]
Thanks for checking, Brad. 

You're sure you picked up / linked the right version? Banner says ``2.9dev`. It is supposed to say `` 2.9.5`` instead -- at least it does for me. And the trailing line "Certificate Transparency" is missing (not complete c&p?).

**Comment by robertlagrant** [comment]
Just tried again :-)
```
$ brew list --versions | grep testssl
testssl 2.9.5-3
$ testssl.sh https://google.com | grep "illegal time format"
Failed conversion of ``2018-06-12 17:55'' using format ``%F %H:%M %z''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Failed conversion of ``2018-06-12 17:55'' using format ``%F %H:%M %z''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
$ uname -a
Darwin DRA-W10-MAC027.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by bknowles** [comment]
On Apr 4, 2018, at 9:52 AM, Dirk Wetter <notifications@github.com> wrote:

> Thanks for checking, Brad.
> 
> You're sure you picked up / linked the right version? Banner says 2.9dev`. It is supposed to say 2.9.5`` instead -- at least it does for me. And the trailing line "Certificate Transparency" is missing (not complete c&p?).

I had a previous clone of the testssl.sh repo on my machine, and alias set up to point to it.  So, even though I had just installed testssl.sh 2.9.5 via brew, and the "which" command showed me the path to the correct binary, it turns out that wasn't the one that was actually being used.

Sigh....

The local clone of the repo has been purged, and I'm trying again.


And now I get the same errors that Robert has reported:

$ testssl.sh https://google.com | grep "illegal time format"
Failed conversion of ``2018-06-12 11:54'' using format ``%F %H:%M %z''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Failed conversion of ``2018-06-12 11:54'' using format ``%F %H:%M %z''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

$ brew list --versions | grep testssl
testssl 2.9.5-3

$ uname -a
Darwin frobgaiju.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

$ testssl.sh --version

###########################################################
    testssl.sh       2.9.5 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2o  27 Mar 2018" [~125 ciphers]
 on frobgaiju:/usr/local/opt/openssl/bin/openssl
 (built: "reproducible build, date unspecified", platform: "darwin64-x86_64-cc")


--
Brad Knowles <brad@shub-internet.org>

**Comment by drwetter** [comment]
Hi @robertlagrant / @bknowles ,

would you mind running ``./testssl.sh --debug=1 <anyhost>`` and passing ``/tmp/testssl.XXXXXX/environment.txt`` to me?

Where does the date command come from: OSX or brew?

Thx, Dirk

**Comment by robertlagrant** [comment]
@drwetter when you say `./testssl.sh`, do you want me to run a particular local script file rather than the brew one?

**Comment by drwetter** [comment]
good point. Nah, I used the trailing dot-slash to be clear which one you're using.

I assume the Brew builds are automatically done. So there shouldn't be a difference to the ones from github
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by robertlagrant** [comment]
@drwetter how can I get the info to you?

**Comment by drwetter** [comment]
I know where it's failing but I currently don't get why Mac OSX' date seem to behave different.

Does anybody of you guys mind to pull/ dl testssl.sh from ``https://github.com/drwetter/testssl.sh/tree/dateissue``, run ``./testssl.sh -S google.com 2>&1 | tee log.txt``` and send the log to me?

**Comment by bknowles** [comment]
On Apr 5, 2018, at 2:10 PM, Dirk Wetter <notifications@github.com> wrote:

> I know where it's failing but I currently don't get why Mac OSX' date seem to behave different.
> 
> Does anybody of you guys mind to pull/ dl testssl.sh from https://github.com/drwetter/testssl.sh/tree/dateissue, run ``./testssl.sh -S google.com 2>&1 | tee log.txt``` and send the log to me?

Here you go:

$ git branch
  2.9dev
* dateissue

$ git log
commit 8a793c56c8c06ad02366fc8f6ad52a4bee9d3970 (HEAD -> dateissue, origin/dateissue)
Author: Dirk Wetter <dirk@testssl.sh>
Date:   Thu Apr 5 16:59:47 2018 +0200

    code with debug info

commit 68b07f1ebc761bd61ca8a9e05fc13bbcf708344d (tag: v2.9.5-3)
Author: Dirk <dirk@testssl.sh>
Date:   Sat Mar 24 19:45:21 2018 +0100

     workaround for missing date format conversion (OpenBSD) in http date

commit 7cd872313e61589d3d376ae4108232c4f8192a86
Author: Dirk <dirk@testssl.sh>
Date:   Fri Mar 23 14:28:39 2018 +0100

    better matching of empty server banners

    Backport of b1b30b3fb8988e56855475f662cab411dda4d18b

commit 4ff442ad7fc6ee2b9a203fef8e1727c8af7dfb72
Author: Dirk <dirk@testssl.sh>
Date:   Wed Mar 21 15:06:09 2018 +0100

    Backport of fix for #1021

    Note: The order of an if-statement matters if a variable isn't
    declared. ;-)

    Probably this 2.9.5 can live without it but rather play safe
    and clean...


$ ./testssl.sh -S google.com 2>&1 | tee log.txt

###########################################################
    testssl.sh       2.9.5 from https://testssl.sh/
    (8a793c5 2018-04-05 16:59:47 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on frobgaiju:./bin/openssl.Darwin.x86_64
 (built: "Sep  7 19:34:54 2016", platform: "darwin64-x86_64-cc")


 Start 2018-04-06 19:34:49        -->> 216.58.194.46:443 (google.com) <<--

 further IP addresses:   2607:f8b0:4000:802::200e
 rDNS (216.58.194.46):   dfw25s12-in-f46.1e100.net. dfw25s12-in-f14.1e100.net.
 Service detected:       HTTP


 Testing server defaults (Server Hello)

 TLS extensions (standard)    "renegotiation info/#65281" "session ticket/#35"
                              "next protocol/#13172" "EC point formats/#11"
                              "extended master secret/#23"
                              "signed certificate timestamps/#18"
                              "application layer protocol negotiation/#16"
 Session Ticket RFC 5077 hint 100800 seconds but: PFS requires session ticket keys to be rotated < daily !
 SSL Session ID support       yes
 Session Resumption           Tickets: yes, ID: yes
 TLS clock skew               0 sec from localtime
 Signature Algorithm          SHA256 with RSA
 Server key size              RSA 2048 bits
 Fingerprint / Serial         SHA1 C28001472BA07D7B5FB4E5FA52F9187B0E981599 / 7C762774337ECB85
                              SHA256 5823AF1FEEB91972F349B23FF379053E5BD4338D6D5BCA5C65EC163A966CAD2C
 Common Name (CN)             *.google.com
 subjectAltName (SAN)         *.google.com *.android.com *.appengine.google.com
                              *.cloud.google.com *.db833953.google.cn *.g.co
                              *.gcp.gvt2.com *.google-analytics.com *.google.ca
                              *.google.cl *.google.co.in *.google.co.jp
                              *.google.co.uk *.google.com.ar *.google.com.au
                              *.google.com.br *.google.com.co *.google.com.mx
                              *.google.com.tr *.google.com.vn *.google.de
                              *.google.es *.google.fr *.google.hu *.google.it
                              *.google.nl *.google.pl *.google.pt
                              *.googleadapis.com *.googleapis.cn
                              *.googlecommerce.com *.googlevideo.com
                              *.gstatic.cn *.gstatic.com *.gvt1.com *.gvt2.com
                              *.metric.gstatic.com *.urchin.com
                              *.url.google.com *.youtube-nocookie.com
                              *.youtube.com *.youtubeeducation.com *.yt.be
                              *.ytimg.com android.clients.google.com
                              android.com developer.android.google.cn
                              developers.android.google.cn g.co goo.gl
                              google-analytics.com google.com
                              googlecommerce.com source.android.google.cn
                              urchin.com www.goo.gl youtu.be youtube.com
                              youtubeeducation.com yt.be
 Issuer                       Google Internet Authority G2 (Google Inc from US)
 Trust (hostname)             Ok via SAN (same w/o SNI)
 Chain of trust               Ok
 EV cert (experimental)       no
 Certificate Expiration       |||6229> 	certificate_info(): ./bin/openssl.Darwin.x86_64 x509 -in /tmp/testssl.xqyPPA/host_certificate.txt -noout -enddate
|||6229> 	certificate_info(): cut -d= -f 2
||6229> 	certificate_info(): parse_date 'Jun 12 16:54:00 2018 GMT' '+%F %H:%M' '%b %d %T %Y %Z'
||1257> 	parse_date(): LC_ALL=C
||1257> 	parse_date(): date -j -f '%b %d %T %Y %Z' '+%F %H:%M' 'Jun 12 16:54:00 2018 GMT'
|6229> 	certificate_info(): enddate='2018-06-12 11:54'
|||6230> 	certificate_info(): ./bin/openssl.Darwin.x86_64 x509 -in /tmp/testssl.xqyPPA/host_certificate.txt -noout -startdate
|||6230> 	certificate_info(): cut -d= -f 2
||6230> 	certificate_info(): parse_date 'Mar 20 17:03:51 2018 GMT' '+%F %H:%M' '%b %d %T %Y %Z'
||1257> 	parse_date(): LC_ALL=C
||1257> 	parse_date(): date -j -f '%b %d %T %Y %Z' '+%F %H:%M' 'Mar 20 17:03:51 2018 GMT'
|6230> 	certificate_info(): startdate='2018-03-20 12:03'
|6232> 	certificate_info(): false
||6236> 	certificate_info(): parse_date '2018-06-12 11:54' +%s '%F %H:%M %z'
||1257> 	parse_date(): LC_ALL=C
||1257> 	parse_date(): date -j -f '%F %H:%M %z' +%s '2018-06-12 11:54'
Failed conversion of ``2018-06-12 11:54'' using format ``%F %H:%M %z''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
||6236> 	certificate_info(): LC_ALL=C
||6236> 	certificate_info(): date +%s
|6236> 	certificate_info(): days2expire=-1523061311
|6237> 	certificate_info(): days2expire=-17628
|6239> 	certificate_info(): grep -q '^Let'\''s Encrypt Authority'
||6244> 	certificate_info(): ./bin/openssl.Darwin.x86_64 x509 -in /tmp/testssl.xqyPPA/host_certificate.txt -checkend 1
|6244> 	certificate_info(): expire='Certificate will not expire'
|6245> 	certificate_info(): grep -qw not
|6250> 	certificate_info(): secs2warn=2592000
||6251> 	certificate_info(): ./bin/openssl.Darwin.x86_64 x509 -in /tmp/testssl.xqyPPA/host_certificate.txt -checkend 2592000
|6251> 	certificate_info(): expire='Certificate will not expire'
|6252> 	certificate_info(): echo 'Certificate will not expire'
|6252> 	certificate_info(): grep -qw not
|6253> 	certificate_info(): secs2warn=5184000
||6254> 	certificate_info(): ./bin/openssl.Darwin.x86_64 x509 -in /tmp/testssl.xqyPPA/host_certificate.txt -checkend 5184000
|6254> 	certificate_info(): expire='Certificate will not expire'
|6255> 	certificate_info(): echo 'Certificate will not expire'
|6255> 	certificate_info(): grep -qw not
|6256> 	certificate_info(): pr_done_good '-17628 >= 60 days'
|467> 	pr_done_good(): tm_done_good '-17628 >= 60 days'
|465> 	tm_done_good(): [[ 2 -eq 2 ]]
|465> 	tm_done_good(): false
|465> 	tm_done_good(): tm_out '\033[0;32m-17628 >= 60 days'
|416> 	tm_out(): printf -- %b '\033[0;32m-17628 >= 60 days'
-17628 >= 60 days|465> 	tm_done_good(): tm_off
|501> 	tm_off(): [[ 2 -ne 0 ]]
|501> 	tm_off(): tm_out '\033[m'
|416> 	tm_out(): printf -- %b '\033[m'
|467> 	pr_done_good(): [[ 2 -eq 2 ]]
|467> 	pr_done_good(): false
||467> 	pr_done_good(): html_reserved '-17628 >= 60 days'
||399> 	html_reserved(): false
||399> 	html_reserved(): return 0
|467> 	pr_done_good(): html_out '<span style="color:#00cd00;"></span>'
|404> 	html_out(): false
|404> 	html_out(): return 0
|6257> 	certificate_info(): expfinding+='-17628 >= 60 days'
|6269> 	certificate_info(): outln ' (UTC: 2018-03-20 12:03 --> 2018-06-12 11:54)'
|413> 	outln(): out ' (UTC: 2018-03-20 12:03 --> 2018-06-12 11:54)\n'
|410> 	out(): printf -- %b ' (UTC: 2018-03-20 12:03 --> 2018-06-12 11:54)\n'
 (UTC: 2018-03-20 12:03 --> 2018-06-12 11:54)
|411> 	out(): html_out ' (UTC: 2018-03-20 12:03 --> 2018-06-12 11:54)\n'
|404> 	html_out(): false
|404> 	html_out(): return 0
|6271> 	certificate_info(): exit 0
|6271> 	certificate_info(): cleanup
|11817> 	cleanup(): true
|11817> 	cleanup(): [[ 0 -gt 0 ]]
|11818> 	cleanup(): [[ 0 -lt 0 ]]
|11831> 	cleanup(): [[ 0 -ge 1 ]]
|11836> 	cleanup(): [[ -d /tmp/testssl.xqyPPA ]]
|11836> 	cleanup(): rm -rf /tmp/testssl.xqyPPA
|11838> 	cleanup(): outln
|413> 	outln(): out '\n'
|410> 	out(): printf -- %b '\n'

|411> 	out(): html_out '\n'
|404> 	html_out(): false
|404> 	html_out(): return 0
|11839> 	cleanup(): html_footer
|966> 	html_footer(): false
|971> 	html_footer(): return 0
|11840> 	cleanup(): fileout_footer
|785> 	fileout_footer(): false
|789> 	fileout_footer(): return 0
|11842> 	cleanup(): grep -q xtrace
|11842> 	cleanup(): false
|11842> 	cleanup(): exec
./testssl.sh: line 11842: 42: Bad file descriptor



Is there anything else?

--
Brad Knowles <brad@shub-internet.org>

**Comment by drwetter** [comment]
> Is there anything else?

Thanks, @bknowles.

Does ``LC_ALL=C date -j -f '%F %H:%M %Z' +%s '2018-06-12 11:54'`` work for you?

**Comment by bknowles** [comment]
On Apr 7, 2018, at 2:05 AM, Dirk Wetter <notifications@github.com> wrote:

> Does LC_ALL=C date -j -f '%F %H:%M %Z' +%s '2018-06-12 11:54' work for you?

Nope:

	$ LC_ALL=C date -j -f '%F %H:%M %Z' +%s '2018-06-12 11:54'
	Failed conversion of ``2018-06-12 11:54'' using format ``%F %H:%M %Z''
	date: illegal time format
	usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
	            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]


According to `man strftime`, %Z is the timezone name, and you're not providing a timezone in your string.  This command does work:

	$ LC_ALL=C date -j -f '%F %H:%M %Z' +%s '2018-06-12 11:54 CDT'
	1528822444

The only thing I added here is the timezone.

--
Brad Knowles <brad@shub-internet.org>
