### ISSUE TITLE
Pretty json output is inconsitent accross testssl versions

### ISSUE THREAD

**Issue by noraj** [drwetter/testssl.sh#1994]
**Command line / docker command to reproduce**

```
$ docker run --rm -t -v /tmp:/data drwetter/testssl.sh --jsonfile-pretty /data/confidential.json --mapping no-openssl --cipher-per-proto https://confidential.host/
```

**Expected behavior**

I have used [TLS map](https://github.com/noraj/tls-map) many times to extract ciphers from testssl output file.

The specific format required is generated by [`testssl --jsonfile-pretty example.org.json --mapping no-openssl --cipher-per-proto example.org`](https://noraj.github.io/tls-map/yard/TLSmap/App/Extractor).

And then I would normally use `tls-map extract ~/Share/confidential.json testssl` to parse testssl outpout and extract ciphers.

Here tls-map was casting an error. I debugged and found that until until testssl 3.0.x I had an outpout like this: https://github.com/noraj/tls-map/blob/master/test/file_sample/testssl.json where all cipher id where respecting [this regexp](https://github.com/noraj/tls-map/blob/0414c6527b2b2f386f7d81e2b95ee9d3111458e0/lib/tls_map/app/extractor/extractor.rb#L215) (`/cipher-(\w+)_x\w+/`, eg. cipher-tls1_x35) but with testssl 3.1dev (OpenSSL 1.0.2-chacha) the cipher ID began to be inconsistent eg.

```json
...
                           },{
                                "id"           : "cipher-tls1_x0a",
                                "severity"     : "MEDIUM",
                                "finding"      : "TLS 1   x0a     TLS_RSA_WITH_3DES_EDE_CBC_SHA                     RSA        3DES        168"
                           },{
                                "id"           : "supportedciphers_TLS 1",
                                "severity"     : "INFO",
                                "finding"      : "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA TLS_RSA_WITH_AES_256_CBC_SHA TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_3DES_EDE_CBC_SHA"
                           },{
...
```

What caused the regexp to fail is that before there were only cipher findings as INFO severity with a consistent ID and now there are cipher findings with various severity and a consistent id but also a new type of finding with some `supportedciphers_TLS` id that makes id unconsistent that seems to be containing a summary of all ciphers present for that TLS version.

Now that the the "normal" cipher findings are all with a severity including OK, LOW, etc. but never INFO and that only those "summary" findings seems to use the INFO severity, a dirty trick would be to ask the user to ad a severity filter.

Adding a severity filter to the testssl command doesn't seem like the proper solution but even so I'm not sure how it would behave because while `--severity LOW` would filter INFO it would also filter OK ones.

```
--severity <severity>         severities with lower level will be filtered for CSV+JSON, possible values <LOW|MEDIUM|HIGH|CRITICAL>
```

Another dirty workaround would be to parse differently output before 3.1 and after 3.1 but it requires 2 testssl parser then so I don't want to do that.

In general it feels like the JSON output even in pretty format is always changing and is inconsistent making it an unreliable input for third party tools.

I think the new "summary" finding shouldn't be stored in `['scanResult'][<id>]['cipherTests']` but rather in a new `['scanResult'][<id>]['cipherSummary']` node to make the output backward compatible. Not chaning the behavior of existing nodes and adding new features output in new nodes.

What do you think?

**Your system (please complete the following information):**

The official docker, outputing this:

```
          "at"          : "0ccefadfd4fd:/home/testssl/bin/openssl.Linux.x86_64",
          "version"     : "3.1dev ",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019",
```

**Additional context**

Given above.

**Comment by drwetter** [comment]
Hi @noraj ,

sorry, read that and forgot to comment.

The world's changing, so is testssl.sh . From one version to another versions we change JSON identifiers because we want to move things ahead. Also severities are subject to change if e.g. there's new research out there.   

We keep things stable in 3.0 (and will do the same in 3.2) -- unless e.g. some research finds out that e.g. Cipher X doesn't offer any encryption. 

But consumers of testssl.sh will experience changes from branch to branch and also within the development / rolling release branch.
