### ISSUE TITLE
[INFO] Action for all users required after renaming the 3.0 tag

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#2004]
FYaI: The old ``3.0`` tag has been renamed to ``v3.0`` which hopefully makes it easier to deal with this repo as the tag _had_ the same name as the branch.

The best way I found so far was deleting the old tag and pushing the new one pointing to the same commit. The good thing is: remote has not the 3.0 tag anymore. The catch: Unless **you** delete the 3.0 tag locally it's still there for you. So best is for everybody on an existing directory to issue ``git tag -d 3.0``. (And also as the release was pointing to the 3.0 tag I had to issue a new release) 

From now on all tags in the 3.0 branch will be named  **v3.0.x**, as just happened with the released 3.0.6. The ones before still don't have a leading 'v' but as there's no conflict, I don't touch them

(I'll leave this open for a while so that people have a good chance to read it)

**Comment by jauderho** [comment]
I was wondering what happened. I'll rename my images to reflect  the vX.X.X convention too.
