### ISSUE TITLE
Certificate Validity date count wrong

### ISSUE THREAD

**Issue by FinzelStefan** [drwetter/testssl.sh#2007]
The date count given by Certificate Validity (UTC) is wrong, e.g.:

./testssl.sh https://127.0.0.1:8016 
...
Certificate Validity (UTC)   3642 >= 60 days (2021-09-24 14:57 --> 2031-09-25 14:57)
...

but its correct value is 3653

OS: Red Hat Enterprise Linux
Platform: Linux 3.10.0-957.1.3.el7.x86_64 x86_64
Version:  testssl.sh       3.1dev from https://testssl.sh/dev/
OpenSSL:  ./bin/openssl.Linux.x86_64

**Comment by dcooper16** [comment]
The `3642` is the number of days remaining until the certificate expires.
