### ISSUE TITLE
[BUG / possible BUG]: Fatal error: cannot exec or find any openssl binary with Fedora 34

### ISSUE THREAD

**Issue by michaelbra** [drwetter/testssl.sh#2008]
**Command line / docker command to reproduce**
After upgrading from Fedora 32 to 34 I'm not able to run testssl.sh anymore:
```
./testssl.sh 1.1.1.1

ATTENTION: No cipher mapping file found!
Please note from 2.9 on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.

Type "yes" to ignore this warning and proceed at your own risk --> yes

ATTENTION: No TLS data file found -- needed for socket-based handshakes
Please note from 2.9 on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.

Type "yes" to ignore this warning and proceed at your own risk --> yes

Fatal error: cannot exec or find any openssl binary
```

**Your system:**
 - OS: ``Fedora 34 (Container Image)``
 - Platform: ``Linux 4.4.1-1.el7.elrepo.x86_64 x86_64``
 - Version: ``v3.0.6``
 - Version if running from git repo: ``commit c3d2cf75b41f14dad9f22aa33f9386dc4523b028``
 - OpenSSL: ``OpenSSL 1.1.1l  FIPS 24 Aug 2021`` (From `` /usr/bin/openssl`` )

**Additional context**
Can this be related to the issue described in #1982 ?

**Comment by drwetter** [comment]
can: maybe, but don't think so though. My crystal ball isn't working right now.

Your  input is not consistent. 

A) Container Image: a container image doesn't have the problem of a missing etc dir
B) did you exec in to the image? (./testssl.sh)

Then I expect users to read the warnings. There are two. And there are capitalized words. 

Closing for now.

**Comment by michaelbra** [comment]
Thanks for you fast feedback. I choose to "ignore" the warnings to show you the complete error message in the report.

I created my own docker container based on Fedora. Inside the container I clone the testssl.sh repo and execute testssl.sh from there (directly in source code directory). This was working fine with Fedora 32, but stopped working when updating to Fedora 34.

Not sure where you see inconsistencies in my report? Everything runs inside the docker container.
