### ISSUE TITLE
[BUG] JSON parse error: Invalid escape 

### ISSUE THREAD

**Issue by frapava98** [drwetter/testssl.sh#2010]
**testssl.sh -oj testssl_results.json --fast --ids-friendly --openssl-timeout 10 --warnings off {hostname}:{port}**

It sometimes happens that I am not able to parse the output file due to a parse error that claims something like: 'Invalid escape at line 335, column 107'. It is always caused by this kind of finding content: 

![immagine](https://user-images.githubusercontent.com/45664945/137485268-612d7f51-9d4e-43b2-b4ef-39400ed9216d.png)

**System Info:**
 - OS: ``Ubuntu 20.04.3 LTS``
 - Platform: ``Linux 5.10.0-1049-oem x86_64``
 - Version: ``testssl.sh       3.1dev from https://testssl.sh/dev/``
 - Version if running from git repo: ``commit d496c0d44beb95f148ec63f48c4ca1a798e43845``
 - OpenSSL: ``./bin/openssl.Linux.x86_64``

**Comment by drwetter** [comment]
Thanks for reporting.

A little bit more input would be helpful as this is not reproducible to me. We could remove the quote but that's likely a false serial or if not: it'll not be the cause.

Could you send the / any public IP to me (``grep SWCONTACT testssl.sh``)

**Comment by drwetter** [comment]
Thanks, got it.

I got to chew on it a bit. The strange thing is that ``openssl x509 -noout  -text -in host_certificate_1.pem`` shows the correct (colon separated) serial but  ``openssl x509 -noout -serial -in host_certificate_1.pem `` inserts <s>a blank and</s> a linefeed before ``:a8`` which is here represented as quoted blank. The latter is independent on whether the supplied openssl version is used, version 1.1.1 or e.g. LibreSSL 3.4.1 .

I am tempting to just correct the error by *SSL but it feels wrong.

@dcooper16 : have you seen anything like that?

**Comment by drwetter** [comment]
![image](https://user-images.githubusercontent.com/8036727/137772939-40a93316-2fc0-4af7-980a-107bb05464a1.png)

![image](https://user-images.githubusercontent.com/8036727/137772993-366524ff-63ae-44e6-b3be-8b56be93d28f.png)

**Comment by drwetter** [comment]
Length in ASCII representation of the serial is 72 chars (including A8).  

https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.2

**Comment by drwetter** [comment]
fixed
