### ISSUE TITLE
[Feature request] Ignore Let's Encrypt's expired root CA for old devices

### ISSUE THREAD

**Issue by l4rm4nd** [drwetter/testssl.sh#2019]
**Which version are you referring to**
3.1dev

**Describe your feature request (if it's a technical feature)**
Let's Encrypt's older root CA "DST Root CA X3" expired on September 30, 2021 ([source](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)). It was used in the beginning of Let's Encrypt, but has been replaced by a newer root CA called "ISRG Root X1". Modern browsers will use the new root CA and therefore a trusted chain. No warnings will occur. However, older devices which do not get updates anymore will start to throw warnings, since they have to use the expired root CA "DST Root CA X3".

Testssl.sh reports the old "DST Root CA X3" root certificate generally with ``Chain of trust: NOT ok (expired)`` as red alert. This is basically correct for old devices, but has no impact for modern devices, since they use the newer "ISRG Root X1" root certificate. This is currently not respected by testssl.sh, since the old root CA will always throw the above warning. The red alert might cause some misunderstandings for users, since they won't actually experience any warnings within their browsers.

![image](https://user-images.githubusercontent.com/21357789/138184930-fe47bc88-5d55-4ce6-a481-3c0713b405a5.png)

Random example host scanned: www.crusoemedia.com

**Describe the solution you'd like**
Some validation, whether the older LE root CA is used for chain trust audit and if so, only throw a warning or ignore it at all. Alternatively, only use the newer "ISRG Root X1" root CA to simulate a connection with modern devices. 

Hope this makes sense. It caused some initial understanding problems for me, until I checked for more details.

**Comment by drwetter** [comment]
Hi & thanks.

there were two updates a while ago (3.1dev: #1997, #2002), so for me it looks like this

![grafik](https://user-images.githubusercontent.com/8036727/138227463-e45e4d5b-63e4-430f-9ccc-4586e000b207.png)

Cheers, Dirk

**Comment by l4rm4nd** [comment]
Yikes, I indeed didn't use the latest version. Jokes on me, sorry for bothering.

Cheers!
