### ISSUE TITLE
Cannot download from website

### ISSUE THREAD

**Issue by rugk** [drwetter/testssl.sh#203]
The link https://testssl.sh/testssl.sh shows:
```
The page you are looking for cannot be accessed.
Maybe try later. 
```

**Comment by drwetter** [comment]
Am 26. September 2015 18:54:31 MESZ, schrieb rugk <notifications@github.com>:
>The link https://testssl.sh/testssl.sh shows:
>```
>The page you are looking for cannot be accessed.
>Maybe try later. 

ACLS fixed, did a backport of #202 today.

Thx for reporting, Dirk 


>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/issues/203


-- 
Sent from my mobile
