### ISSUE TITLE
[BUG] Server grade assessment when NULL ciphers are involved

### ISSUE THREAD

**Issue by Wahnes** [drwetter/testssl.sh#2033]
When testing a server that offers `NULL` ciphers, i.e. just TLS handshake and no encryption, this is clearly marked in red letters as dangerous in the _Testing cipher categories_ section. For instance, the output may look like this:
```
 NULL ciphers (no encryption)                      offered (NOT ok)
 Anonymous NULL Ciphers (no authentication)        offered (NOT ok)
```

Unfortunately, this test result is not reflected in the overall server grade. A server that offers `NULL` encryption (like shown above) may receive an `A` or `A+` overall rating. This not only feels wrong, it also does not conform to the server rating rules.

Consider Table 5 of [SSL Labs Server Rating Guide](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide#user-content-cipher-strength) which assigns a "0 %" score when there is no encryption. Given the calculation method for cipher strength (add strongest and weakest, divide by two), this should yield a 50 % score at most. With a 50 % score for cipher strength, the overall rating of a server that offers `NULL` encryption should be `C` at best.

The discussion of the "2009n" changes in the _Changes_ section in the [SSL Labs Server Rating Guide](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide#changes-in-2009n-19-january-2017---3-april-2017) also mentions an "explicit penalty" for weak ciphers, but does not give details. Or at least I could not find any details on that. But I suppose that this would make `F` the appropriate grade for a server that offers `NULL` encryption at all.

**Comment by drwetter** [comment]
Thanks for reporting.

cc @magnuslarsen

**Comment by magnuslarsen** [comment]
Thanks for reporting! I'll take a look this evening :-)

**Comment by magnuslarsen** [comment]
Testing against `null.badssl.com` confirms the bug:
```
 Testing cipher categories                                                                                                                                               
                                                                                                                                                                         
 NULL ciphers (no encryption)                      offered (NOT ok)                                                                                                      
 Anonymous NULL Ciphers (no authentication)        offered (NOT ok)                                                                                                      
 Export ciphers (w/o ADH+NULL)                     not offered (OK)                                                                                                      
 LOW: 64 Bit + DES, RC[2,4], MD5 (w/o export)      not offered (OK)                                                                                                      
 Triple DES Ciphers / IDEA                         not offered                                                                                                           
 Obsoleted CBC ciphers (AES, ARIA etc.)            not offered                      
 Strong encryption (AEAD ciphers) with no FS       not offered                                                                                                           
 Forward Secrecy strong encryption (AEAD ciphers)  not offered 
[...]

Rating (experimental)  

Cipher Strength  (weighted)  90 (36)
```
In this case, the score should be a solid 0. 

I also believe a grade cap of `F` should be given to null ciphers here (and some others too):
> Introduce an explicit penalty for using cipher suites weaker than **112 bits.**

I'll look to implement it before the end of the weekend.

**Comment by magnuslarsen** [comment]
Hi @Wahnes - can you check my PR and verify that it works for you now?

> With a 50 % score for cipher strength, the overall rating of a server that offers NULL encryption should be C at best.

This is not entirely true. The final grade is calculated based on the 3 categories (weighted score) combined, and not a single one (unless any category is 0)

**Comment by drwetter** [comment]
I merged it for the time being as it is defintely an improvement. 

That shouldn't stop you, @Wahnes, to speak up.
