### ISSUE TITLE
JSON FORMAT

### ISSUE THREAD

**Issue by mrrobothack1** [drwetter/testssl.sh#2036]
3.1dev version

how can i print the output straight in a JSON FORMAT ? Now its coming in a normal way @drwetter

**Comment by teward** [comment]
This is documented in the `--help` output from the script:

```
file output options (can also be preset via environment variables)
     ...
     --json                        additional output of findings to flat JSON file '${NODE}-p${port}${YYYYMMDD-HHMM}.json' in cwd
     --jsonfile|-oj <jsonfile>     additional output to the specified flat JSON file or directory, similar to --logfile
     --json-pretty                 additional JSON structured output of findings to a file '${NODE}-p${port}${YYYYMMDD-HHMM}.json' in cwd
     --jsonfile-pretty|-oJ <jsonfile>  additional JSON structured output to the specified file or directory, similar to --logfile
     ...
```

You can have it still output the data to console as it's doing 'normal', but then add `-oj FILENAME.json` or `-oJ FILENAME.json` to output in standard JSON or Pretty JSON respectively.

You can alternatively just do `--json` or `--json-pretty` and it'll generate the file in the current working directory with the file formats as indicated.

I would suggest following this and *not* attempt to pipe the output from the script directly to file, instead letting the script create the files and otherwise *not* keep the standard output as your 'output' to rely on.

**Comment by teward** [comment]
(@drwetter I'm pretty sure this can be closed, as this is less a 'bug' and more a 'help please')

**Comment by mrrobothack1** [comment]
If i run like this  ./testssl.sh --jsonfile test.json google.com this will make a file locally.. 

I want to know whether the entire output can be visible in the terminal only, not as a file @teward

**Comment by teward** [comment]
> If i run like this ./testssl.sh --jsonfile test.json google.com this will make a file locally..
> 
> I want to know whether the entire output can be visible in the terminal only, not as a file @teward

I don't see a mechanism that would permit this in the current script, devel or otherwise, only the solution to run in quiet mode and then output to file.

**Comment by mrrobothack1** [comment]
yea, I wanted to know whether I can get the json format from the terminal logs as I am running this as a cronjob in kubernetes.  @teward

**Comment by drwetter** [comment]
two options:
* do a host mount (see Dockerfile.md)
* see https://github.com/drwetter/testssl.sh/issues/1290#issuecomment-533883685

**Comment by mrrobothack1** [comment]
When I am running like 
` ./testssl.sh --quiet --color 0 --jsonfile /dev/stderr  falabella.com 2>&1 >/dev/null`

It is giving me the output in correct json format.  But if im trying to store this output into a file like 

` ./testssl.sh --quiet --color 0 --jsonfile /dev/stderr  falabella.com 2>&1 >/dev/null > file.json` 

the file.json will be having normal output @drwetter

**Comment by drwetter** [comment]
> the file.json will be having normal output @drwetter

Please inspect your cmdline. Github is about issues and development. It is not the place to learn basic things like I/O redirection, sorry.

 Try ``testssl.sh --quiet --color 0 --jsonfile /dev/stderr <URL>  2>\! file.json``
