### ISSUE TITLE
[possible BUG] False Positive Secure Client-Initiated Renegotiation 

### ISSUE THREAD

**Issue by BreakfastSerial** [drwetter/testssl.sh#2038]
`testssl.sh <target>` reports the following issue:

```
[...]
 Secure Renegotiation (RFC 5746)           supported (OK)
 Secure Client-Initiated Renegotiation     VULNERABLE (NOT ok), DoS threat
[...]
```

In comparison to `sslyze.py <target>`:
```
 * Session Renegotiation:
       Client Renegotiation DoS Attack:   OK - Not vulnerable
       Secure Renegotiation:              OK - Supported
```

Furthermore, if I test the behavior manually with OpenSSL (Described here: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection#, Example 3 Checking for Client-Initiated Renegotiation and Secure Renegotiation Via OpenSSL (Manually)) :

```
openssl s_client s_client -connect <target> 
HEAD / HTTP/1.0
R
RENEGOTIATION
Can't use SSL_get_servername
[...] (certificate information)
```
No further response is given, unless another `HEAD / HTTP/1.0 \nR` is sent, which results in the same response again.

**Expected behavior**
Either `testssl.sh` or `sslyze` reports Secure Client-Initiated Renegotiation as a false positive.

**Your system (please complete the following information):**
 - OS: `Ubuntu 20.04.3 LTS`
 - Platform: `Linux 5.4.0-89-generic x86_64`
 - Version: `testssl.sh 3.1dev`
 - OpenSSL: `Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]`

The target also supposedly runs an BIG-IP F5 load balancer.

**Comment by drwetter** [comment]
How are we supposed to check this without a hostname / IP?

**Comment by BreakfastSerial** [comment]
I'm afraid I can't reveal the hostname/IP due to an NDA.
