### ISSUE TITLE
Git tag for 2.6 release missing

### ISSUE THREAD

**Issue by rugk** [drwetter/testssl.sh#204]
The git tag for the 2.6 [release](https://github.com/drwetter/testssl.sh/releases) is missing.

**Comment by teward** [comment]
There is a 2.6 branch.  Perhaps that's where 2.6 resides

**Comment by drwetter** [comment]
Thx guys, I added the release and also release notes.

**Comment by rugk** [comment]
Okay, just remove the `h Intro` headline - I think you don't need this there. :smiley:
