### ISSUE TITLE
How to build  docker.io/drwetter/testssl.sh

### ISSUE THREAD

**Issue by wewang58** [drwetter/testssl.sh#2080]
**Which version are you referring to**
3.1dev
Hi, @drwetter can you provide dockerfile or configuration about how to build the image: docker.io/drwetter/testssl.sh? thanks.

**Comment by drwetter** [comment]
HI @wewang58 ,

please see the Readme.md and [Dockerfile.md](https://github.com/drwetter/testssl.sh/blob/3.1dev/Dockerfile.md)

Cheers, Dirk

**Comment by wewang58** [comment]
Thanks @drwetter !
