### ISSUE TITLE
Update bundled openssl s_client to support TLS 1.3

### ISSUE THREAD

**Issue by dilyanpalauzov** [drwetter/testssl.sh#2087]
`testssl.sh -t ldap ldap.aegee.org:389` reports `Fatal error: FIXME: LDAP+STARTTLS over sockets not supported yet (try "--ssl-native")`.

Callig `testssl.sh --ssl-native -t ldap ldap.aegee.org:389` prints ` TLS 1.3    Local problem: ./bin/openssl.Linux.x86_64 doesn't support "s_client -tls1_3"`.

I use v3.0-719-g06890d4.

**Comment by drwetter** [comment]
A 'won't fix' as it works as designed -- so far. 3.0 is the stable branch. We won't change anything here.

For 3.1dev it hasn't been decided whether we'll use another binary. It's a only helper anyway as it is for most parts being used not for handshakes. Usage of ``--ssl-native`` is discouraged. 

See also  #1258, socket implementation of LDAP, needs to be implemented.

**Comment by drwetter** [comment]
That will be done hopefully in 3.1dev, not in 3.0

**Comment by drwetter** [comment]
See  #2088

**Comment by drwetter** [comment]
Closing this updated my comment above
