### ISSUE TITLE
[BUG / possible BUG] Error: too many connections from

### ISSUE THREAD

**Issue by Antict** [drwetter/testssl.sh#2089]
When testing the mail server with IP 159.69.231.212 I get the error message :

    sending client hello... === starting smtp STARTTLS dialog ===
    === reading banner ... ===
    S: 421 4.7.0 is-comm2.is-ol.de Error: too many connections from [my_server_ip]
    === full read syntax error, expected regex pattern ^220- (cont) or ^220  (end) ===
    === finished smtp STARTTLS dialog with 2 ===
     Oops: STARTTLS handshake failed (code: 2)
    stuck on sending: 6

**Command line / docker command to reproduce**
`./testssl.sh --debug 2 -p -t smtp 159.69.231.212:25`

**Expected behavior**
If I test the IP address with https://www.checktls.com/TestReceiver, then a valid result is returned. I expect that the test also works with TestSSL.

**Your system (please complete the following information):**
 - OS: ``Ubuntu 18.04.2 LTS``
 - Platform: ``Linux 4.15.0-47-generic x86_64``
 - Version: ``testssl.sh       3.1dev from https://testssl.sh/dev/``
 - OpenSSL: ``./bin/openssl.Linux.x86_64``

**Additional context**
Does TestSSL open parallel connections and then the server terminates them because there are too many at the same time? If yes, how to prevent this issue?

**Comment by drwetter** [comment]
> Does TestSSL open parallel connections

not yet.

It seems either you have tried too often or the server is overloaded.

**Comment by drwetter** [comment]
The server side is blocking after 3 attempts. For those the handshake is fine (220). The following connect 421 is answered.

So, sarcastically speaking: Welcome to the internet. Some servers choose to throttle or block connections if they decide it's not a real one ;-)

**Comment by Antict** [comment]
Is there an option to throttle the requests from testssl to for example 1 request / 30 seconds?

**Comment by drwetter** [comment]
Unfortunately no / not yet.

But if you like: edit ``fd_socket()`` and add a delay using ``sleep``. That'd be my first idea to tackle this.
Let us know how it goes please.
