### ISSUE TITLE
Third party engine

### ISSUE THREAD

**Issue by xuekun0703** [drwetter/testssl.sh#2097]
Hi, can I use testssl.sh to call our own third-party engine?  And if so, how，thank you.

**Comment by drwetter** [comment]
Hi,

thanks!

Whatever you have in mind, it need to be compliant to the license (GPL v2), see license file.
When you call testssl.sh that _should_ be fine, I am not a lawyer though.

Then, see Readme.md:

```
Attribution is important for the future of this project -- also in the
internet. Thus if you're offering a scanner based on testssl.sh as a public and/or
paid service in the internet you are strongly encouraged to mention to your audience
that you're using this program and where to get this program from. That helps us
to get bugfixes, other feedback and more contributions.
```

Other than that: Usage in free software is always appreciated and an entry in the Readme.md can be achieved via PR.

If you want to let me privately know what you have in mind -->`` grep SWCONTACT testssl.sh``.

Does that answer your questions?

**Comment by xuekun0703** [comment]
Hi,

Thank you for your prompt reply!

My apologies. I mean, How can I use testssl.sh to verify the functionality of a custom openSSL engine?
GOST engine is default, how can I use my engine from the command line or other means?

Looking forward to hearing from you!

**Comment by drwetter** [comment]
😂 What a wonderful misunderstanding ...

This is not straight forward. We just use the GOST engine on old openssl versions to have two additional ciphers in openssl. And openssl is only being used for a couple of operations. The rest is done in sockets.

To get you started: In general it boils down to the question for which openssl version it should be for. Then you need testssl.sh to point to this openssl version by just using ``--openssl=<path>`` -- when not using the supplied one.

Next point is to make sure your engine is really used. There are some hacks in the code to ensure the old GOST engine is loaded when possible (``initialize_engine()``). The hacks ensure that under any openssl versions it works. So as you have a different goal you could change that in your code to fit your needs.

Cheers, Dirk
