### ISSUE TITLE
bug converting a tls handshake to hex value

### ISSUE THREAD

**Issue by digininja** [drwetter/testssl.sh#2099]
Scanning a site that is not publicly accessible.

This is the result of running without any flags for modifiers, just straight `testssl.sh <site>`

```
 Testing ~standard cipher categories 

 NULL ciphers (no encryption)                  not offered (OK)
 Anonymous NULL Ciphers (no authentication)    not offered (OK)
 Export ciphers (w/o ADH+NULL)                 /home/robin/tools/web/testssl.sh/testssl.sh: line 1016: 16#: invalid integer constant (error token is "16#")
/home/robin/tools/web/testssl.sh/testssl.sh: line 8785: 2+: syntax error: operand expected (error token is "+")
```

Running with the -s flag I got the call to `hex2dec` being made from around line 8789, I added this above the call:

```
printf "\n\n-%s-\n\n" $server_hello
```

And got this back:
```
 Testing ~standard cipher categories 

 NULL ciphers (no encryption)                  not offered (OK)
 Anonymous NULL Ciphers (no authentication)    not offered (OK)
 Export ciphers (w/o ADH+NULL)                 

--

/home/robin/tools/web/testssl.sh/testssl.sh: line 1017: 16#: invalid integer constant (error token is "16#")
/home/robin/tools/web/testssl.sh/testssl.sh: line 8790: 2+: syntax error: operand expected (error token is "+")
```

The variable is empty which explains why trying to convert it to hex is failing.

I don't know enough about TLS to know what this means so can't comment further.

Happy to retest this at any time as long as I still have access to the client server.

**Expected behaviour**
It not break.

**Your system (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)

 - Platform: ``Linux 5.10.0-11-amd64 x86_64``
 - Version: ``2.9.5-8``
 - Version if running from git repo: commit 51247361a164d848f4d1e9689b8f5474b618a6fd
 - OpenSSL: ``/usr/bin/openssl``

**Additional context**
I get this at the top of the script but from what I've read this shouldn't affect things.

```
No engine or GOST support via engine with your /usr/bin/openssl
```

**Comment by drwetter** [comment]
Hi @digininja!

The version is pretty old. 

3.0.6 is the latest stable. 3.1dev is basically our rolling release. The error sounds familiar, could you try one of those and let me know how it went?

Cheers, Dirk

**Comment by digininja** [comment]
All that debug work, and just getting the latest branch fixed it!
I did get a different error about collate on that, but that isn't a stopper.

**Comment by drwetter** [comment]
> 
> All that debug work, and just getting the latest branch fixed it!
> I did get a different error about collate on that, but that isn't a stopper.


Shouldn’t happen. It could be worth reporting it.

 
Cheers, Dirk

**Comment by digininja** [comment]
Reported.

**Comment by drwetter** [comment]
Thanks!
