### ISSUE TITLE
LC_COLLATE: cannot change locale

### ISSUE THREAD

**Issue by digininja** [drwetter/testssl.sh#2100]
**Before you open an issue please check this repo whether this is a known problem**
If in doubt check the git log and/or check whether you run the latest version from the git repo.

**Command line / docker command to reproduce**
I get this error when I start running a scan.

```
$ ~/tools/web/testssl.sh/testssl.sh digi.ninja
/home/robin/tools/web/testssl.sh/testssl.sh: line 239: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
```

Based on this issue https://github.com/drwetter/testssl.sh/issues/1860 you set the locale to en_US.UTF-8 but I don't have that installed because I'm on a UK based box.

```
$ locale -a
C
C.UTF-8
en_GB.utf8
POSIX

$ locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Expected behavior**
No errors.

I've had a skim read of the old issue, could you check if that locale is installed and either put up a warning or set some other value if it isn't?

**Your system (please complete the following information):**

- OS: Debian GNU/Linux 11 (bullseye)
- Platform: Linux 5.10.0-11-amd64 x86_64
- Version:  3.1dev - commit 13f0388539b0748d3019da1ce8a0b71645af4374
- OpenSSL: /usr/bin/openssl

**Additional context**

**Comment by drwetter** [comment]
Thanks! I believe the fix in #1860 should be different. 

Scratching my head though how, as I am not a unicode expert. As a reminder: it was because of [bash pattern matching of some charsets ](https://github.com/drwetter/testssl.sh/issues/1860#issuecomment-812641647)

Anybody has thoughts on this:

Try LC_COLLATE=C.UTF-8, if if fails set to en_US.UTF-8, if it fails set to en_GB.UTF-8, if that fails too, issue a a warning and proceed?

**Comment by digininja** [comment]
Could you do a grep on the output from locale to work out which, if any,
are available, and then set appropriately.

Have a preference order based on ones you know work.

**Comment by drwetter** [comment]
sure, as long it is being checked for the appropriate ones like above.

**Comment by drwetter** [comment]
fixed, see above. Thanks again for reporting

**Comment by digininja** [comment]
I've just done a `git pull` and all looks good now, no collation errors on
startup.

You also give my site an A+ which matches SSL Labs so I'm happy with that.
