### ISSUE TITLE
Docker container is not working properly. It returns an "/tmp/testssl_output.json" that breaks my Jenkins job when I try to use it to create my Jenkins Test Results

### ISSUE THREAD

**Issue by snigel-nelson** [drwetter/testssl.sh#2103]
## Description of the Issue

I have a Jenkins job that uses the official _testssl.sh_ docker image (https://hub.docker.com/r/drwetter/testssl.sh) to run a container to verify several domains. This container creates a JSON file, _"/tmp/testssl_output.json"_, which I use to create my Jenkins test results report to be available for consulting.
The problem is that on the last build my Jenkins job downloaded a newer Docker image which produces invalid JSON which in turn breaks the job build causing it to fail. You can see this in the following image:

![image](https://user-images.githubusercontent.com/91899315/154134587-766da413-b6a2-40fd-af8c-8a2a2a6799bd.png)

And it fails here:

![image](https://user-images.githubusercontent.com/91899315/154134671-6c681be6-ec53-488d-bba8-d066536eeacd.png)

## Test results
As I mentioned in the description I'm using the JSON file produced by the container and stored at  _"/tmp/testssl_output.json"_ to create the XML file, with the standard format of JUnit tests, in the _./logs/${tldDomainName}.xml_ location, and allow Jenkins to read and create the Test Results dashboard to report as represented in the image below:
![image](https://user-images.githubusercontent.com/91899315/154136351-b63357b5-3364-42f9-b842-a832ac888a15.png)

The problem is that this new Docker image produces invalid JSON which causes the Jenkins Job to break when it tries to convert the JSON -> XML.  You can verify the structure of the new JSON produced by this new version of testssl.sh Docker image in the attached file:
[testssl_output.txt](https://github.com/drwetter/testssl.sh/files/8074380/testssl_output.txt)

## Command line / docker command to reproduce
These are the commands that I'm using in my Jenkins job to verify the services and create the Test Results dashboard:

`
  String tldDomainName = domain.split('/')[0]; // Get top level domain name
  sh 'docker rm testssl || exit 0' // remove container before running
  sh "docker run -i --name testssl -v ${WORKSPACE}/logs:/home/logs -e DAYS2WARN1='30' -e DAYS2WARN2='20' drwetter/testssl.sh:${params.tag} --jsonfile-pretty=/tmp/testssl_output.json --color=0 ${domain}"
  sh "docker cp testssl:/tmp/testssl_output.json ./logs/${tldDomainName}.json"
  sh 'docker rm testssl || exit 0' // remove container after running
  xml = convertJsonToJunit(tldDomainName, readFile(file: "logs/${tldDomainName}.json", encoding: 'UTF-8'));
  writeFile(file: "logs/${tldDomainName}.xml", text: xml, encoding: 'UTF-8')
`

**Variables**
The _params.tag_ = 3.0

## Expected behavior ##
The JSON file containing all the output with all the results of the tests made in a certain domain.com and stored at _/tmp/testssl_output.json_ should have a valid structure. At the top of the JSON there's an object that shouldn't be there, or at least, wasn't present before:
`
{
		"severity": "WARN",
		"finding": "locale(1) support for any of 'C, POSIX, C.UTF-8, en_US.UTF-8, en_GB.UTF-8' missing"
}
`

## Questions

- Is this a problem with this Docker Image?
- Is this new JSON structure (which is invalid) from now on? Or is going to be reverted?
- Can I use an older Docker image? Which version/tag? Is this advisable, because we should always use the LTS version?

I'll be looking forward for your reply.

As usual, if you need more info just let me know.

Thanks,

Nelson

**Comment by drwetter** [comment]
Thanks for reporting, @snigel-nelson . The binary "locale" is not in the container but was introduced two days ago in #2101 .

Try to fix that by the end of today (CET)

**Comment by drwetter** [comment]
in 3.0 this should work again as soon as the docker hub automagic updated the container.

**Comment by snigel-nelson** [comment]
> in 3.0 this should work again as soon as the docker hub automagic updated the container.

Thank you @drwetter for the fast response and fixing. I was about to ask you which version I should use, I mean LTS, if I should upgrade to 3.0.6 but you already answered my question: The 3.0 is fixed, so I'll continue using that. At the end of the day I'll run again the Jenkins job and see if it works.

Best regards,
Nelson

**Comment by drwetter** [comment]
Hi Nelsen,

3.0.6 is basically a LTS. We label it as "stable" though whereas 3.1dev is a rolling release.

Cheers, Dirk

**Comment by snigel-nelson** [comment]
Hi @drwetter. 

I've run again the Jenkins job using the Docker image of testssl 3.0 and worked just fine, didn't fail this time. Performed all the checks on all the domains I want, 
The logging files "/tmp/testssl_output.json" used to create the XML JUnit files to create the Test Results dashboard it's correct now, the JSON doesn't have an invalid structure and creates perfectly the dashboard with all the test stats of the Jenkins job.
Once again thank you for your help.

Cheers,
Nelson
