### ISSUE TITLE
[BUG / possible BUG] Lucky13 Vulnerable  is wrong.

### ISSUE THREAD

**Issue by tvhoa289** [drwetter/testssl.sh#2110]
**Which version are you referring to**
3.0.x or 3.1dev? (please check also how old your version is compare to the ones here)
Hi ,
I think luckly13 vulnerable in script is wrong.
Is That right?
Refer link :  https://github.com/drwetter/testssl.sh/issues/789
I don't see any label or update about lucky13 in script.
Please share me your thoughts.

Thanks,
Hoa Truong

**Comment by drwetter** [comment]
Please fill out the template properly
