### ISSUE TITLE
[BUG / possible BUG] "./testssl.sh: line 11363: printf: missing hex digit for \x"

### ISSUE THREAD

**Issue by guidorugo** [drwetter/testssl.sh#2128]
Version: 3.1dev
OS: Mac
Platform: Darwin 21.3.0 x86_64
OpenSSL: LibreSSL 2.8.3
Using fish.

<img width="751" alt="Screenshot 2022-03-21 at 13 48 15" src="https://user-images.githubusercontent.com/1023222/159275026-df826362-7682-41a8-aa16-da333368ba04.png">

If I change lines 11363 and 11365 everything seems to work as expected.

**Comment by drwetter** [comment]
1) The template has to be filled out completely. The much I appreciate bug reports I don't like hunting for details. It's just a waste of time

2) do a git pull

Thx, Dirk
