### ISSUE TITLE
False positive generated by the BREACH test?

### ISSUE THREAD

**Issue by GianpaoloPedrazza** [drwetter/testssl.sh#213]
Hi everybody,
I had a look at the check for the BREACH test. According with http://breachattack.com, to be vulnerable, a web application must:
1. Be served from a server that uses HTTP-level compression
2. Reflect user-input in HTTP response bodies
3. Reflect a secret (such as a CSRF token) in HTTP response bodies
From my undestanding, if the first point is true the web server is immediately marked as vulnerable. In my opinion, this could generate a false positive if the HTTP response is only supposed to provide static content.

**Comment by drwetter** [comment]
HI @GianpaoloPedrazza,s

For the latter: Yes: If it's static content the information from testssl.sh is misleading. I can't test though what kind of content that is.

The attacker needs also additional control over the browser content to make use from the compression oracle. That's the trick for other attacks too.

The thing with CSRF was IIRC an example which they could exfiltrate. If I understood correctly it could be any secret in the page as compression is effective enough (irony here) let say if you have a cookie in the page named ``mysecret=AAAABBBBCCCC`` and you start guessing it by adding first ``mysecret`` or ``CCCC`` you will see for compression characteristic changes in the length, i.e. you add 4+ chars but the compressed length doesn't change that much. 

Bottom line: I maybe should add a hint. If anybody now a crispy short description let me know.

Cheers, Dirk

**Comment by teward** [comment]
@drwetter Perhaps "Vulnerable if compressed secrets are present" ?

**Comment by drwetter** [comment]
Fix for wording follows.  

Thx, @GianpaoloPedrazza
