### ISSUE TITLE
[Bug or Feature ???] FTP STARTTLS is only attempted when advertised properly via FEAT

### ISSUE THREAD

**Issue by mzpqnxow** [drwetter/testssl.sh#2132]
I'm testing against a service that happens to be an Axway Secure Transport FTP server with a hard requirement for STARTTLS. It has quirky behavior for STARTTLS and doesn't advertise in `FEAT` like the RFC seems to suggest is required. This causes `testssl.sh` to fail without any option to force / proceed anyway

NOTE: The documentation doesn't explicitly state that `--ssl-native` is required for FTP (it mentions mongo only) but it seems required, at least for this particular implementation. More of an FYI, it could be a quirk of this implementation, you would know better than I

## Command

```
./testssl.sh --ssl-native --openssl /usr/bin/openssl.testssl -t ftp x.x.x.x:21
```

## Debug Output

```
...
  > succeeded: sent FEAT
=== reading banner ... ===
=== we'll have to search for "^ AUTH TLS" pattern ===
S: 211-Extensions supported
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  AUTH
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  USER
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  PASS
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  QUIT
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  PORT
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  PASV
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  EPSV
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  EPRT
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  TYPE
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  STRU
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  MODE
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  RETR
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  STOR
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  ABOR
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  DELE
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  CWD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  XCWD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  LIST
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  NLST
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  SITE
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  SYST
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  STAT
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  HELP
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  NOOP
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  MKD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  XMKD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  RMD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  XRMD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  PWD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  XPWD
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  CDUP
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  XCUP
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  SIZE
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  MDTM
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  RNFR
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  RNTO
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  REST
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  FEAT
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  ADAT
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  PROT
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  PBSZ
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  APPE
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  XCRC
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  CCC
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  COMB
end_pattern/cont_pattern: ^211  / ^(211-| )
S:  UTF8
end_pattern/cont_pattern: ^211  / ^(211-| )
S: 211 END
end_pattern/cont_pattern: ^211  / ^(211-| )
  > found:  211 END
=== finished ftp STARTTLS dialog with 3 ===

Fatal error: No STARTTLS found in handshake
```

## The Issue

The following patch is enough to show that it is just a surface level issue and not something more complicated- this just forces `starttls_ftp_dialog()` to return success, even though the server isn't advertising `AUTH TLS` as it should, per the RFC...

```diff
diff --git a/testssl.sh b/testssl.sh
index 6e3429d..6ff55aa 100755
--- a/testssl.sh
+++ b/testssl.sh
@@ -10978,6 +10978,7 @@ starttls_ftp_dialog() {
      starttls_full_read '^234-' '^234 '     ''                   "received ack for STARTTLS"
      ret=$?
      debugme echo "=== finished ftp STARTTLS dialog with ${ret} ==="
+     return 0
      return $ret
 }
```

With that patch, everything works as expected

## Behavior of Server

Here's some of the output from the server so you can see what I mean:

```
$ telnet x.x.x.x 21
Trying x.x.x.x ...
Connected to x.x.x.x.
Escape character is '^]'.
220- xxxxxx ....
220-
220-
220 x.x.x.x FTP server 5.4 ready.    
FEAT
211-Extensions supported
 AUTH
 USER
 PASS
 QUIT
 PORT
 PASV
 EPSV
 EPRT
 TYPE
 STRU
 MODE
 RETR
 STOR
 ABOR
 DELE
 CWD
 XCWD
 LIST
 NLST
 SITE
 SYST
 STAT
 HELP
 NOOP
 MKD
 XMKD
 RMD
 XRMD
 PWD
 XPWD
 CDUP
 XCUP
 SIZE
 MDTM
 RNFR
 RNTO
 REST
 FEAT
 ADAT
 PROT
 PBSZ
 APPE
 XCRC
 CCC
 COMB
 UTF8
211 END
```

Particularly notable because it could be used to handle this cleanly and reliably is the following behavior- any command other than 

```
HELP DERP
530 SSL is mandatory.
DERP
530 SSL is mandatory.
```

These error messages (`SSL is mandatory`) could be used, but that's probably not the cleanest way to do this. Returning a `530` is not helpful as it's just a generic "can't log user in" code. Probably one of the following is a better option for solving this without requiring the user to force the protocol:

Using `AUTH`:

```
AUTH TLS
234 SSLv23/TLSv1
```

Using `PROT`:

```
PROT C
200 Command PROT okay.
```

## Proposed Fix

I think there are two ways you would be amenable to:

1. Giving the user a choice to force/override, much in the way they are given such an option when connecting to an HTTPS service that doesn't speak valid SSL/TLS
2. Implement an additional detection method, either actively or passively (preferably passively.) I don't have time to read the RFC at the moment, nor have I looked very closely at the `FEAT` output,  but is seeing `PROT` good enough to detect the capability?

Thanks!

**Comment by drwetter** [comment]
Hi @mzpqnxow ,

why do you believe ``--ssl-native`` is required? And when you refer to ``starttls_ftp_dialog()`` -- that is a socket function. I am wondering how that goes along with ``--ssl-native``?

Your "fix" is not correct. You can't just return 0 for everything. 

However the RFC reads that ``AUTH`` must be advertised and _the AUTH  command should have a reply that identifies 'TLS' as one of the  possible parameters to AUTH_ . 

So the proper fix would be to change ``local reSTARTTLS='^ AUTH TLS'`` to ``local reSTARTTLS='^ AUTH'``. Could you try please and report back?

Thx, Dirk

**Comment by mzpqnxow** [comment]
> Your "fix" is not correct. You can't just return 0 for everything.

Obviously :)

As I stated, that quick change was how I completed my immediate task and identified the issue. I needed the cipher-suite data but didn't have time to assess the problem let alone properly fix it. I know very little about any FTP-related RFC after the year 2000 and I barely had the few minutes free to determine what the issue was, let alone properly fix it. That's why this is entered as an issue and not a PR

The only reason I *mentioned* this "fix" (I had to try it anyway, just to get it working for the moment) was to demonstrate it wasn't anything more than a surface level issue, and ideally narrow it down a little. Rather than say "FTP with TLS extensions is broken", I thought the additional information would be helpful. Next time I can omit that. It wasn't my intention to complicate things and I'm sorry I misrepresented it as a solution to the problem- it was a solution to *my* problem, at that moment, and (I thought) helpful context to pinpoint where the proper fix needed to be made

> So the proper fix would be to change local reSTARTTLS='^ AUTH TLS' to local reSTARTTLS='^ AUTH'. Could you try please and report back?

As expected this works just fine, thanks

The rest isn't related (as far as I know) to this issue- hence the "FYI" prefix- please feel free to ignore it, I included some info here to answer your question but I consider this matter closed. Read on at your own peril ;)

> why do you believe --ssl-native is required? And when you refer to starttls_ftp_dialog() -- that is a socket function. I am wondering how that goes along with --ssl-native?

The two are not at all related as far as I know- in fact I don't ever use `--ssl-native` nor have I looked much into exactly how it works, nor do I care to- at least until a time comes where I need to

To directly answer your question ("why do you believe --ssl-native is required?") this is what I saw when I ran it without `--ssl-native`, when I initially ran it (after patching out the `AUTH TLS` check)

```
$ ./testssl.sh --quiet -t ftp X:21                    

 Start 2022-04-06 14:10:51        -->> X:21 (X) <<--

 rDNS (X): X.
 Testing with X21 only worked using ./bin/openssl.Linux.x86_64.
 Test results may be somewhat better if the --ssl-native option is used.
 Type "yes" to proceed and accept false negatives or positives --> yes
 Service set:            STARTTLS via FTP

 Testing protocols via sockets 

 SSLv2      not offered (OK)
 SSLv3      likely not offered (OK), received 4xx/5xx after STARTTLS handshake, rerun with DEBUG>=2 or --ssl-native
 TLS 1      likely not offered, received 4xx/5xx after STARTTLS handshake, rerun with DEBUG>=2 or --ssl-native
 TLS 1.1    likely not offered, received 4xx/5xx after STARTTLS handshake, rerun with DEBUG>=2 or --ssl-native
 TLS 1.2    likely not offered, received 4xx/5xx after STARTTLS handshake, rerun with DEBUG>=2 or --ssl-native
 TLS 1.3    likely not offered, received 4xx/5xx after STARTTLS handshake, rerun with DEBUG>=2 or --ssl-native
...
```

With `--ssl-native`, it behaved as it normally would and identified TLS1.2


## FIN

Thanks again for the work you do on this project and the quick response

**Comment by drwetter** [comment]
Should work now if tou do a fresh git pull on 3.1dev.
