### ISSUE TITLE
starttls brocken

### ISSUE THREAD

**Issue by TuxCoder** [drwetter/testssl.sh#214]
I can't get starttls working in the new version

`$ ./testssl.sh -t imap mail.example.org:143` outputs always
`Fatal error: momentarily only ftp, smtp, pop3, imap, xmpp, telnet and ldap allowed`

I think the error is in line 4566:
`protocol=${protocol%s}` because protocol is a local varible and never seted.

Changeing to `protocol=${STARTTLS_PROTOCOL%s}` works fine for me but I'm not sure thats the nice way.

ps. thx for the tool

edit: compered with the 2.6 version.
think the line should be `protocol=${1%s}`

**Comment by drwetter** [comment]
thanks for your thx and for reporting.

Fix follows.
