### ISSUE TITLE
Client Authentication sclient_connect_successful

### ISSUE THREAD

**Issue by Iansus** [drwetter/testssl.sh#215]
Hi !
In client authentication cases, the server will not issue a session id since it has not been able to verify the client cert (none offered).
For that reason, the sclient_connect_successful() function will always fail in these cases.
Example below : 

```
SSL handshake has read 11944 bytes and written 242 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES256-SHA256
    Session-ID:
    Session-ID-ctx:
    Master-Key: FB3DD95BEEB93...EA6EF125085D52
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1444811171
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
```

Imho, the cipher existence test was OK for most purposes, or you can slightly modify your function if you want to keep the Master-Key check : 

```bash
# function which 
sclient_connect_successful() {
     [[ $1 -eq 0 ]] && return 0
     [[ -z $(awk '/Master-Key: / { print $2 }' "$2") ]] && return 1
     fgrep 'Cipher is (NONE)' "$2" &> /dev/null && return 1
     # what's left now is: master key not empty and Session-ID not empty ==> probably client based auth with x509 certificate
     CLIENT_AUTH=true
     return 0
}
```

Again, I agree with you, though I almost 100% sure that when the cipher choice equals "s_client successful", coupling it with Master Key checks should be more efficient but would still need to be extensively tested.

Regards, 
Iansus

**Comment by Iansus** [comment]
Additionnaly, I think that you could perform a first test (after confirming that SSL is enabled) to check for client auth (rather than doing it at the first enumeration).

Pseudo-code : 

```
1. Connect without any restriction to the target with openssl
2. If $? == 0, CLIENT_AUTH=FALSE && return
3. Else, search for "Acceptable client certificate CA names" in output
4. If found, CLIENT_AUTH=TRUE && return
5. Else use an all-purposes (in terms of signature hash algorithms and certificate types) certificate and try to connect again
6. If connection successful, CLIENT_AUTH=TRUE && return
7. Else, target/port is not available for SSL && return
```

Justifications : 
- (3) If client auth is enabled, server must send a list of acceptable CA names for issuers, except for...
- (5) ... TLS1.2 in which CA Names is optionnal, and therefore the certificates are only filtered on their capabilities (RFC 5246, 7.7.4 : `If the certificate_authorities list is empty, then the client MAY send any certificate of the appropriate ClientCertificateType`)
- (6) and indeed there was client auth but an empty acceptable CA

Of course, the best solution would be to analyze the raw message sent by server to check for the "Certificate Request" handshake type (0x0d). Maybe with the `-msg` option : 
```bash
openssl s_client -connect <target:port> -msg | egrep '^<<<(.+)CertificateRequest'
```

To be tested,
Regards, Iansus

**Comment by drwetter** [comment]
Hi Iansus!

thx for checking...

Am 10/14/2015 um 11:00 AM schrieb Iansus:
> Hi !
> In client authentication cases, the server will not issue a session id since it has not been
> able to verify the client cert (none offered).

I think the handshake process is a different one, see e.g.
https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/sslmessages.gif

(step 7)

See also https://tools.ietf.org/html/rfc5246#section-7.4.6

"7.4.6.  Client Certificate

   When this message will be sent:

      This is the first message the client can send after receiving a
      ServerHelloDone message.  "


You should be also to be able to sport the order with a recent openssl version using -trace if
you do
client authentication manually with s_client.

WithOUT client auth I always saw so far a session ID in the server hello:

openssl s_client -connect auth.startssl.com:443 </dev/null


Sooner or later I probably remove the check for the session ID -- if it affects the speed
of testssl and after regression tests.


Cheers, Dirk

**Comment by Iansus** [comment]
Well, tests with Wireshark clearly show : 
- Client hello
- Server hello
- ...
- CertificateRequest
- ...
- Server Hello done
- No certificate available for testssl.sh
- Encrypted alert shutting down the connection

So no Session Id is established.
Take a look at the new test I have that will tell you for sure if Client Auth is enabled AND required : 

```bash
openssl s_client -connect <target:port> -msg | egrep '^<<<(.+)CertificateRequest' && CLIENT_AUTH=true
```

As for the session-id : 
```
The server
      may return an empty session_id to indicate that the session will
      not be cached and therefore cannot be resumed
```

So if your server does not perform SSL session caching, you will never have a Session-Id set before you receive the encrypted alert.

Regards,
Iansus

**Comment by drwetter** [comment]
Am 10/15/2015 um 05:35 PM schrieb Iansus:
> Well, tests with Wireshark clearly show :
> 
>   * Client hello
>   * Server hello
>   * ...
>   * CertificateRequest
>   * ...
>   * Server Hello done
>   * No certificate available for testssl.sh

I clearly see the certificate.

Wireshark is not really good showing the handshake properly
as a server hello might exceed one packet on the network.

>   * Encrypted alert shutting down the connection
> So no Session Id is established.

Well, I see that with openssl.


> Take a look at the new test I have that will tell you for sure if Client Auth is enabled AND
> required :
> 
> openssl s_client -connect <target:port> -msg | egrep '^<<<(.+)CertificateRequest' && CLIENT_AUTH=true

Thx (need to look into that). Any idea since when -msg is available?

> As for the session-id :
> 
> |The server may return an empty session_id to indicate that the session will not be cached and
> therefore cannot be resumed |
> 
> So if your server does not perform SSL session caching, you will never have a Session-Id set
> before you receive the encrypted alert.

Oh, ok. That is important, sure.

Most servers nowadays have session caching enabled (in fact in older versions of apache
and nginx yopu can't even disable it IIRC)

A test for SSL session caching was anyway a thing I wanted to add.

So, yes. That line (my) has to disappear/changed.


Cheers, Dirk

**Comment by drwetter** [comment]
> Thx (need to look into that). Any idea since when -msg is available? 

0.9.7

**Comment by Iansus** [comment]
Well that *should* be enough !

**Comment by Iansus** [comment]
"I clearly see the certificate.

Wireshark is not really good showing the handshake properly
as a server hello might exceed one packet on the network."

I was talking about the client cert ;)

**Comment by drwetter** [comment]
Am 10/15/2015 um 07:21 PM schrieb Iansus:
> Well that *should* be enough !

Yup. Thx for the hint!

I have something prepared, needs thorough testing though to really make
sure, that the new core function works.

Thx for the fruitful discussion!

Cheers, Dirk

**Comment by drwetter** [comment]
Hi @Iansus,

did thorough tests and it eventually it worked. There seems to be no need for a second test.

Also there will be a line now whether SSL Session ID are supported.  If you have more servers with client authentication maybe you could give the following commit a try.

Thx, Dirk
