### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by DonatoReis** [drwetter/testssl.sh#2159]
**Which version are you referring to**   @drwetter 
3.1dev

**Describe your feature request (if it is a technical feature)**

**If your feature request is related to a usage issue, please describe it**
I need to send the output to a log, but the escape code record ends up interfering with the report

**Describe the desired solution**
You could add an example parameter: --no-colour.
to avoid outputting escape codes.

**Comment by dcooper16** [comment]
Please read about the `--color` option in https://github.com/drwetter/testssl.sh/blob/3.1dev/doc/testssl.1.md.
