### ISSUE TITLE
no matching cipher in this list found 

### ISSUE THREAD

**Issue by Mark32** [drwetter/testssl.sh#216]
Hi, when I run the test I get the following:

Any suggestions to fix please?

--> Testing protocols (via sockets except TLS 1.2 and SPDY/NPN)

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 SPDY/NPN   not offered

--> Testing ~standard cipher lists

 Null Ciphers                 not offered (OK)
 Anonymous NULL Ciphers       not offered (OK)
 Anonymous DH Ciphers         not offered (OK)
 40 Bit encryption            not offered (OK)
 56 Bit encryption            not offered (OK)
 Export Ciphers (general)     not offered (OK)
 Low (<=64 Bit)               not offered (OK)
 DES Ciphers                  not offered (OK)
 Medium grade encryption      not offered (OK)
 Triple DES Ciphers           offered (NOT ok)
 High grade encryption        offered (OK)

--> Testing (perfect) forward secrecy, (P)FS -- omitting 3DES, RC4 and Null Encryption here

 PFS is offered (OK)

--> Testing server preferences

 Has server cipher order?     no matching cipher in this list found (pls report this): DES-CBC3-SHA:RC4-MD5:DES-CBC-SHA:RC4-SHA:AES128-SHA:AES128-SHA256:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-RSA-AES128-SHA:ECDH-RSA-AES256-SHA:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA256  .
 Cipher order
     TLSv1:     DHE-DSS-AES128-SHA EDH-DSS-DES-CBC3-SHA
     TLSv1.1:   DHE-DSS-AES128-SHA EDH-DSS-DES-CBC3-SHA
     TLSv1.2:   DHE-DSS-AES128-SHA256 DHE-DSS-AES128-SHA EDH-DSS-DES-CBC3-SHA

--> Testing server defaults (Server Hello)

It also doesn't show a negotiated protocol.

This is running on RedHat 6.6
Apache Tomcat/8.0.15

server.xml file has:
<Connector port="8443"
protocol="HTTP/1.1"
SSLEnabled="true"
maxThreads="150"
scheme="https" secure="true"
clientAuth="false"
sslEnabledProtocols="TLSv1.0"
keystoreFile="/etc/pki/tls/keystore/<file>"
keystorePass="<pass>"
/>

**Comment by drwetter** [comment]
To get a clue what's going on is difficult if the host is not known. Could you shed light into this pls (pm is fine too).

**Comment by Mark32** [comment]
Hi Dirk,

 

This was on an internal lab system with a self-signed certificate, so I don’t think name makes any difference? Anything else?

 

Thanks

 

Mark

**Comment by teward** [comment]
Details about the endpoint setup might assist in testing even if one of us replicates on an internal VM or such for testing.  Debugging this kind of error isn't very possible with just the cipher list and the error.  Not without more details about the setup and/or target.



*Sent from my iPhone.  Please excuse any typos, as they are likely to happen by accident.*

**Comment by drwetter** [comment]
yup. (thx, Thomas)


Am 10/15/2015 um 12:05 AM schrieb Thomas Ward:
> Details about the endpoint setup might assist in testing even if one of us replicates on an
> internal VM or such for testing. Debugging this kind of error isn't very possible with just the
> cipher list and the error. Not without more details about the setup and/or target.
> 
> 
> 
> *Sent from my iPhone. Please excuse any typos, as they are likely to happen by accident.*
>

**Comment by Mark32** [comment]
BTW, the test environment I'm using is based on the procedure described in this article:
http://www.colabrativ.com/self-signed-certificates-gwt-applications-apache-http-tomcat/

I can't send anything further at the moment. I'm going to try create differently as not critical for now re finer details

**Comment by drwetter** [comment]
Some housekeeping, thus closing this. If you happen to have an URL for me to test I am happy to reopen the issue. Thx.
