### ISSUE TITLE
SMTP STARTTLS causes protocol synchronization errors

### ISSUE THREAD

**Issue by notr1ch** [drwetter/testssl.sh#218]
Hello,
It seems testssl.sh sends SMTP commands before waiting for replies from the server. Some mailservers such as exim treat this as an error.

EHLO should not be sent until receiving a 220 greeting banner, and the STARTTLS should not be sent until receiving the 220 from the EHLO.

sending client hello...

=== sending "EHLO testssl.sh" ...

=== sending "STARTTLS" ...
... received result:
554 SMTP synchronization error
---> reply didn't match "220", see /tmp/ssltester.42av5S/ddreply.RTWPvc

STARTTLS handshake problem. Either switch to native openssl (--ssl-native),
   give the server more time to reply (STARTTLS_SLEEP=<seconds> ./testssh.sh ..) --
   or debug what happened (add --debug=2)

**Comment by drwetter** [comment]
Hi @notr1ch,

hmm... just out of curiosity: pls set ``FAST_STARTTLS=false`` before.

``FAST_STARTTLS=false testssl.sh <whatever>``

and let me know.

Cheers, Dirk

**Comment by notr1ch** [comment]
That worked! Thanks for the quick response.

**Comment by drwetter** [comment]
Thx for reporting!

That is not the optimal solution yet. Working...

**Comment by drwetter** [comment]
should work now automagically (upon failure a second try is being done with the flag above).

Thx also for the clearnes, saved some time.
