### ISSUE TITLE
DNS CAA RR (experimental) - TestSSL freezed

### ISSUE THREAD

**Issue by srikanthprathi** [drwetter/testssl.sh#2187]
**Command line / docker command to reproduce**
testssl.sh --connect-timeout 35 --color 0 --warnings off [IP_Address]

**Expected behaviour**
The scan should check for DNS CAA RR (experimental) and rest.

**Actual behaviour**
The scan got freezed

**Your system (please complete the following information):**
 - OS: Kali GNU/Linux Rolling`
 - Platform: Linux 5.15.0-kali3-amd64 x86_64
 - Version: testssl.sh       3.0.7 from https://testssl.sh/
 - Version if running from git repo: NA
 - OpenSSL: testssl.sh-3.0.7/bin/openssl.Linux.x86_64

**Comment by drwetter** [comment]
Hi @srikanthprathi ,

we can't read thoughts yet and thus we would need input where it hangs. Either you need to find out by yourself (https://github.com/drwetter/testssl.sh/wiki/Findings-and-HowTo-Fix-them) or give us another piece of information like the IP address and what DNS client resolver you were using.

Maybe it's only your environment and CAA lookups are being blocked, have you checked that?

Thx, Dirk

**Comment by drwetter** [comment]
PS: Probably you're aware of that but the timeout you specified has no relevance for the DNS lookup, see man page / docu.

**Comment by srikanthprathi** [comment]
The endpoint is an internal server and I guess it's the firewall rule that's blocking it. 

The below command worked good

testssl -s -p -h -g -e -E -c -U -P (just opted out the "-S" optino)

**Comment by Tib3rius** [comment]
I encountered the same issue recently. It would be nice if there were a flag to disable experimental features, I can't see one in the documentation if it exists.

**Comment by drwetter** [comment]
That has likely nothing to do with being an experimental feature or not. I suspect (but can't tell as input is missing) for some reason querying the DNS record fails. 

You can try ``--nodns=min though``.

Other than that: Please find the pointer howto provide more input above.
