### ISSUE TITLE
Data::HexDump perl module causes "hexdump" syntax errors

### ISSUE THREAD

**Issue by notr1ch** [drwetter/testssl.sh#219]
As part of the default installation of the perl module "Data::HexDump", a wrapper script called "hexdump" is installed into /usr/local/bin/hexdump. This conflicts with the system provided hexdump utility when invoked as "hexdump", causing numerous syntax errors as testssl relies on the BSD-style system binary quite heavily.

This hexdump wrapper seems undocumented, but you can see it's still part of the default installation in the module Makefile: https://github.com/gitpan/Data-HexDump/blob/master/Makefile.PL

A workaround could be to see if both /usr/local/bin/hexdump and /usr/bin/hexdump exist and use the latter. For now I've deleted the wrapper script from my system as I had no use for it.

**Comment by drwetter** [comment]
To be frank: I don't know. 

I see this more a user space issue. Not blaming anybody, sorry -- but you have configured your environment to have another hexdump command. If I start doing this the next person comes with a strange sed, awk, cat, tr, whatsoever.

Best maybe would be to hard code what I am looking for. In terms of compatibility that is a nightmare to do for all platforms. 

Maybe a sanity check whether one uses the expected binaries or something else would help. But that is not easy either.

Sorry.
