### ISSUE TITLE
broken link on website

### ISSUE THREAD

**Issue by digininja** [drwetter/testssl.sh#2195]
This link on the website homepage goes to a 404 in GitHub:

> Jan 23,2020: Version 3.0. Final Release, see [3.0 @ github](https://github.com/drwetter/testssl.sh/releases/tag/3.0). It's been a long rolling release candidate phase since the first 3.0 RC version.

I doubt anyone will be clicking on it, I just clicked it as it was the first link out to GitHub that I saw when I was looking for one.

**Comment by drwetter** [comment]
Thanks! I tried to fix that.

The web site should be better maintained here with some modern ingredients like hugo, so that other would be able to contribute.  But I have no clue how to get this done. (anybody listening? ;-) )
