### ISSUE TITLE
Get SAN url list

### ISSUE THREAD

**Issue by sonawanesarvesh** [drwetter/testssl.sh#2196]
**Which version are you referring to**
3.0.x

Can we have one parameter which will give us list of SAN Url?

**Comment by drwetter** [comment]
SAN url?

-v please. Meanwhile closing this.

**Comment by sonawanesarvesh** [comment]
Hello,

I mean to say - SAN or subject alternative names
Can we export a list of all Subject Alternative Names used for that certificate using any parameters - for some purpose I want this information (i have a few SSL certificates which are showing 60+ SAN URLs while testssl scanning - so if I can get a list of all of such domain it will be good option to protect those applications as well if any certificate issues found - please correct me if I am wrong)

**Comment by drwetter** [comment]
Hello, did you try the CSV or one of the JSON-Formats? (cert_subjectAltName)

**Comment by sonawanesarvesh** [comment]
Hello,

Thank you for quick help, its there in json but I missed it

Thank you once again
