### ISSUE TITLE
Chain of trust - NOT ok (expired)

### ISSUE THREAD

**Issue by sonawanesarvesh** [drwetter/testssl.sh#2199]
**Which version are you referring to**
3.0.x 

Hello, 
I am seeing this error Chain of trust - NOT ok (expired)
Is there anyway to know exactly which certificate is expired?

because i have imported few CA certificates so now sure exactly which certificate is expired.

The real problem is when i use the URL directly on [SSLlabs.com ](https://www.ssllabs.com/) i see A+ grade quickly

But internally the way i configured the TestSSL is i am adding CA certificates as i am not sure whether server is carrying these certificates or not - so now it seems like one of additionally supplied CA certificate seems as expired and i am not sure which one

so if we can get more information on it, then i can remove expired certificate and supply only valid group of certificates to TestSSL

**Comment by drwetter** [comment]
Try using 3.1dev.

**Comment by sonawanesarvesh** [comment]
Hello

Thanks, it resolved the issue :)
