### ISSUE TITLE
[Feature request] Make it clearer where the actual supported ciphers are in the report

### ISSUE THREAD

**Issue by huornlmj** [drwetter/testssl.sh#2208]
The current report layout makes it difficult to see which ciphers are actually supported by a server and which are not.  For example, the first section that your eyes are drawn to is the "Testing robust (perfect) forward secrecy" section.  People might conclude that this is the full list of supported ciphers  when in fact it's not.

If they are not drawn to this point they may conclude that the "Negotiated cipher per proto" section and again this is not the full list of ciphers supported.

Finally if they move to the end of the report they might conclude the "Testing {n} ciphers via OpenSSL plus sockets against the server, ordered by encryption strength", but even I cannot conclude that this is the definitive list of server supported ciphers and if it's just as the heading suggests - testing around 340 ciphers.

**Comment by drwetter** [comment]
First of all: please fill out the template properly next time. I have to guess which version you are using and this is wasting time which I'd rather would like to spend on different things. 340 ciphers???

Then there's also the point "Describe the solution you'd like" you didn't answer.

Other than that: I don't know what's difficult to understand in "Testing robust (perfect) forward secrecy" ? IHere are only ciphers shown which comply to the headline of this section.

"Negotiated cipher per proto" IS the full list of ciphers supported.

**Comment by huornlmj** [comment]
The "Clear output: you can tell easily whether anything is good or bad" mentioned at https://testssl.sh isn't the case.  As a regular user I'm just providing my feedback on this point.  To summarize, it should be made clearer which ciphers are actually supported by the server.  I'm not saying it should be front and center.  It should just be somewhere in the report.  I'm guessing that the Testing {n} ciphers via OpenSSL plus sockets against the server, ordered by encryption strength" section is this, but I could be wrong.  

[Version 3.0.7](https://github.com/drwetter/testssl.sh/releases/tag/v3.0.7) BTW

**Comment by drwetter** [comment]
@huornlmj : everything you see is what is only supported by the server.

**Comment by huornlmj** [comment]
> @huornlmj : everything you see is what is only supported by the server.

I believe the "Testing robust forward secrecy (FS) -- omitting Null Authentication/Encryption, 3DES, RC4" section does not show all of the server supported ciphers, just the ones that provide PFS.

The section "Testing server's cipher preferences" shows ciphers but I think this only appears if the server controls the ordering.  If the client does then this section is not shown.

This then leaves the "Running client simulations (HTTP) via sockets" section.  Is this the definitive list of server-supported ciphers then?

**Comment by drwetter** [comment]
_Testing 370 ciphers via OpenSSL plus sockets against the server, ordered by encryption strength_ is what you want probably.

> The section "Testing server's cipher preferences" shows ciphers but I think this only appears if the server controls the ordering. If the client does then this section is not shown.

Yes (normally only 1 negotiated cipher per proto when no server preference. But all ciphers when this is the case). That has been changed in 3.1dev so that all ciphers in any case will be shown.

**Comment by huornlmj** [comment]
3.1dev provides the solution I was referring to.  That's great.  FYI: latest stable release 3.0.7's output when client determines the order:
```
 Testing server preferences 

 Has server cipher order?     no (NOT ok)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            TLS_RSA_WITH_AES_128_GCM_SHA256 -- inconclusive test, matching cipher in list missing, better see below
 Negotiated cipher per proto  (matching cipher in list missing)
     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:                 TLSv1, TLSv1.1
     TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:              TLSv1.2
 No further cipher order check has been done as order is determined by the client
```
3.1dev's output when client determines the order (which is much better and clearer):
```
 Testing server's cipher preferences 

Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
-----------------------------------------------------------------------------------------------------------------------------
SSLv2
 - 
SSLv3
 - 
TLSv1 (no server order, thus listed by strength)
 xc014   ECDHE-RSA-AES256-SHA              ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                 
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 x84     CAMELLIA256-SHA                   RSA        Camellia    256      TLS_RSA_WITH_CAMELLIA_256_CBC_SHA                  
 xc013   ECDHE-RSA-AES128-SHA              ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                 
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
 x41     CAMELLIA128-SHA                   RSA        Camellia    128      TLS_RSA_WITH_CAMELLIA_128_CBC_SHA                  
TLSv1.1 (no server order, thus listed by strength)
 xc014   ECDHE-RSA-AES256-SHA              ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                 
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 x84     CAMELLIA256-SHA                   RSA        Camellia    256      TLS_RSA_WITH_CAMELLIA_256_CBC_SHA                  
 xc013   ECDHE-RSA-AES128-SHA              ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                 
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
 x41     CAMELLIA128-SHA                   RSA        Camellia    128      TLS_RSA_WITH_CAMELLIA_128_CBC_SHA                  
TLSv1.2 (no server order, thus listed by strength)
 xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH 521   AESGCM      256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384              
 xc028   ECDHE-RSA-AES256-SHA384           ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384              
 xc014   ECDHE-RSA-AES256-SHA              ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                 
 xcca8   ECDHE-RSA-CHACHA20-POLY1305       ECDH 521   ChaCha20    256      TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256        
 xc077   ECDHE-RSA-CAMELLIA256-SHA384      ECDH 521   Camellia    256      TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384         
 x9d     AES256-GCM-SHA384                 RSA        AESGCM      256      TLS_RSA_WITH_AES_256_GCM_SHA384                    
 xc0a1   AES256-CCM8                       RSA        AESCCM8     256      TLS_RSA_WITH_AES_256_CCM_8                         
 xc09d   AES256-CCM                        RSA        AESCCM      256      TLS_RSA_WITH_AES_256_CCM                           
 x3d     AES256-SHA256                     RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA256                    
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 xc0     CAMELLIA256-SHA256                RSA        Camellia    256      TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256               
 x84     CAMELLIA256-SHA                   RSA        Camellia    256      TLS_RSA_WITH_CAMELLIA_256_CBC_SHA                  
 xc051   ARIA256-GCM-SHA384                RSA        ARIAGCM     256      TLS_RSA_WITH_ARIA_256_GCM_SHA384                   
 xc061   ECDHE-ARIA256-GCM-SHA384          ECDH 521   ARIAGCM     256      TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384             
 xc02f   ECDHE-RSA-AES128-GCM-SHA256       ECDH 521   AESGCM      128      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256              
 xc027   ECDHE-RSA-AES128-SHA256           ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256              
 xc013   ECDHE-RSA-AES128-SHA              ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                 
 xc0a0   AES128-CCM8                       RSA        AESCCM8     128      TLS_RSA_WITH_AES_128_CCM_8                         
 xc09c   AES128-CCM                        RSA        AESCCM      128      TLS_RSA_WITH_AES_128_CCM                           
 xc076   ECDHE-RSA-CAMELLIA128-SHA256      ECDH 521   Camellia    128      TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256         
 x9c     AES128-GCM-SHA256                 RSA        AESGCM      128      TLS_RSA_WITH_AES_128_GCM_SHA256                    
 x3c     AES128-SHA256                     RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA256                    
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
 xba     CAMELLIA128-SHA256                RSA        Camellia    128      TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256               
 x41     CAMELLIA128-SHA                   RSA        Camellia    128      TLS_RSA_WITH_CAMELLIA_128_CBC_SHA                  
 xc050   ARIA128-GCM-SHA256                RSA        ARIAGCM     128      TLS_RSA_WITH_ARIA_128_GCM_SHA256                   
 xc060   ECDHE-ARIA128-GCM-SHA256          ECDH 521   ARIAGCM     128      TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256             
TLSv1.3
 - 
```
@drwetter would you know when this will make it into a stable release?

**Comment by drwetter** [comment]
I am recommending to everybody incl. Linux distributors switching now. There will be one last 3.0.8 and that's it.
 
3.1dev will then become a release candidate.

**Comment by huornlmj** [comment]
Will the reporting feature be in 3.0.8 @drwetter ?

**Comment by drwetter** [comment]
Looking back that was a poor design decision, but I don't think so. No new features in old releases. Only bug fixes.
