### ISSUE TITLE
I am using testssl.sh in my cygwin, why the error on tput

### ISSUE THREAD

**Issue by flamecopper** [drwetter/testssl.sh#222]
$ testssl.sh demo.testfire.net
/usr/bin/testssl.sh: line 96: tput: command not found
/usr/bin/testssl.sh: line 333: tput: command not found
/usr/bin/testssl.sh: line 334: tput: command not found
/usr/bin/testssl.sh: line 335: tput: command not found
/usr/bin/testssl.sh: line 336: tput: command not found
/usr/bin/testssl.sh: line 337: tput: command not found
/usr/bin/testssl.sh: line 338: tput: command not found
/usr/bin/testssl.sh: line 339: tput: command not found
/usr/bin/testssl.sh: line 340: tput: command not found
/usr/bin/testssl.sh: line 340: tput: command not found
/usr/bin/testssl.sh: line 350: tput: command not found
/usr/bin/testssl.sh: line 351: tput: command not found
/usr/bin/testssl.sh: line 352: tput: command not found
/usr/bin/testssl.sh: line 353: tput: command not found

**Comment by PeterMosmans** [comment]
Hi @flamecopper ,
I can reproduce the issue with Cygwin x64 on Windows 8.1 x64 . Please stay tuned for a fix...

Cheers,

Peter

**Comment by PeterMosmans** [comment]
@flamecopper , could you check https://github.com/PeterMosmans/testssl.sh/tree/cygwin ?

**Comment by flamecopper** [comment]
Hi Peter,

It is working for me now. Thanks. You may close the case.

Alvin Oo,Tel:(65)91172830
New Email Address : oo.yekei.alvin@gmail.com
MPP ID: D1000749

**Comment by drwetter** [comment]
see https://github.com/PeterMosmans/testssl.sh/commit/2db80bb12ecd63089f34d0a1e34313deecd8ae90#commitcomment-13971559

**Comment by drwetter** [comment]
Hi @flamecopper,

fix in official branch is pending. I would recommend in the first place to install the ncurses package which is missing in your cygwin installation:

https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fncurses%2Fncurses-6.0-1.20151017&grep=tput.exe

testssl.sh will work after the fix without tput but you'll miss some text accentuations. Probably this is true for other tools on your system too.

Cheers, Dirk
