### ISSUE TITLE
[Feature request] iiops support

### ISSUE THREAD

**Issue by bmarwell** [drwetter/testssl.sh#2221]
**Which version are you referring to**

Any

**Please check this repo whether this is a known feature request**

It is not

**Describe your feature request (if it's a technical feature)**

Java uses the iiop protocol which can be secured using TLS.
See here: https://docs.oracle.com/cd/A97335_02/apps.102/a83722/connsec6.htm

It would be nice to have this connection tested as well.

**If your feature request otherwise is related to a usage problem, please describe it**

./.

**Describe the solution you'd like**

./.

**Comment by drwetter** [comment]
Hi,

probably never head about this protocol. Counter question: have you just tried to connect to the remote service with testssl.sh or with ``openssl s_client -connect REMOTE:PORT`` ?

Thx, Dirk

**Comment by bmarwell** [comment]
No, will  try. But I  tried various  --starttls options, with no luck. Will get back to you soon.
It is very Java-specific. If it is easy to implement, I'd be happy to help. If not, we can drop that feature. I will check on twitter whether someone knows more about iiop + TLS.

**Comment by drwetter** [comment]
There was little information out there, but it looked to me proprietary. 

There are four possibilities:
* just plain TLS. That can you check with ``openssl s_client -connect REMOTE:PORT``. It's agnostic to the protocol tunneled within the TLS connection.
* STARTTLS: That is not supported (in testssl.sh or) with the -starttls option from openssl (try: ``openssl s_client -starttls foo``).
* not TLS or a mishmash (=proprietary)
* you or anybody else have not configured TLS or you didn't check not the TLS enabled PORT

PS: This https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html/configuration_guide/orb_configuration and an older article https://docs.oracle.com/cd/E19644-01/817-5445/agcorba.html looks like plain TLS to me

**Comment by bmarwell** [comment]
> Hi,
> 
> probably never head about this protocol. Counter question: have you just tried to connect to the remote service with testssl.sh or with `openssl s_client -connect REMOTE:PORT` ?
> 
> Thx, Dirk

```
# openssl s_client -connect host:11100
CONNECTED(00000003)
804401144:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 265 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1662359849
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

# uname -a
AIX D100SEUSBA31 2 7 00C3C9C84C00

# openssl version
OpenSSL 1.0.2u  20 Dec 2019
```

**Comment by drwetter** [comment]
looks to me like no encryption. 

I would try first ``nmap -sTV -p1-65535 --script=ssl\* HOST``.  Scanning all ports bc there maybe others which may be an alternative TLS-enabled port for iiops you're looking for.

If that returns some cipher at a port where iiops is running, we can use testssl.sh. If not: bad luck here.

**Comment by bmarwell** [comment]
No luck here, because I configured the iiops-Port myself. I tried some fiddling with netcat, but no luck here as well. I will ask IBM on how to debug iiops.

**Comment by drwetter** [comment]
nc doesn't help you to determine whether it's TLS/SSL enabled.

**Comment by bmarwell** [comment]
IBM said it should have worked using `openssl s_client -connect`. Will investigate and come back to you.

**Comment by bmarwell** [comment]
We had a faulty configuration. IIOPS can be scanned using testssl.sh with all the defaults.
Thanks!
