### ISSUE TITLE
[BUG] Grade cap reasons not showing weak public keys

### ISSUE THREAD

**Issue by cancom-oss** [drwetter/testssl.sh#2232]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version ( commit b3c49b584d843a28915af05e8f6ba4af6ed16be3  / testssl.sh       3.1dev from https://testssl.sh/dev/)

**Before you open an issue please whether this is a known problem by searching the issues**
I couldn't find anything 

**Command line / docker command to reproduce**
``docker run --rm -ti drwetter/testssl.sh https://dh512.badssl.com/``

**Expected behavior**
Grade cap reasons should include `Grade capped to F. Using an insecure public key and/or ephemeral key`. Currently, the cap reason is missing, but overall grade is correctly set to F.

**Your system (please complete the following information):**
 - OS: ``Alpine Linux v3.13``
 - Platform: ``Linux 5.10.0-14-amd64 x86_64`` 
 - OpenSSL: ``/home/testssl/bin/openssl.Linux.x86_64``

**Additional context**
The reason for this problem is related to the placement of `sorted_reason` and `sorted_warnings`.

```sh
IFS=$'\n' sorted_reasons=($(sort -ru <<<"${GRADE_CAP_REASONS[*]}"))
IFS=$'\n' sorted_warnings=($(sort -u <<<"${GRADE_WARNINGS[*]}"))
IFS=$old_ifs
```

[testssl.sh#L22399-22401](https://github.com/drwetter/testssl.sh/blob/b3c49b584d843a28915af05e8f6ba4af6ed16be3/testssl.sh#L22399-22401)

These are responsible for pretty printing the output. However, set_grade_cap can be invoked **AFTER** the sort already happened, for example in [testssl.sh#L22462-22466](https://github.com/drwetter/testssl.sh/blob/b3c49b584d843a28915af05e8f6ba4af6ed16be3/testssl.sh#L22462-22466) after the KEY_EXCH_SCORE is used.

We could move the sort to the bottom right before pretty printing [testssl.sh#L22572](https://github.com/drwetter/testssl.sh/blob/b3c49b584d843a28915af05e8f6ba4af6ed16be3/testssl.sh#L22572), but `sorted_warnings` is used to measure `A+` or `A-`. We could also just sort it twice, once at the current position, and once right before the `A+` and `A-` measurement.

Or even better, don't rely on `sorted_warnings` to measure the exceptional score, but use `GRADE_WARNINGS` instead. It shouldn't matter if they are sorted or not, since we are relying on the total count of warnings.

We would like to make a Pull Request for this, but not sure, which version you would prefer?

**Comment by drwetter** [comment]
@magnuslarsen : do you have a preference?

**Comment by drwetter** [comment]
(@cancom-oss : thanks)

**Comment by magnuslarsen** [comment]
Good catch! Thanks for looping me in :-)

> don't rely on sorted_warnings to measure the exceptional score, but use GRADE_WARNINGS instead.

I agree, let's do this. But this _can_ still leaves us with an unsorted `sorted_reasons` (as we have to check the KEY_EXCH_SCORE regardless).

We can avoid sorting twice, by moving the sorting block into the each of the if statements, something like this:
```sh
if [[ $GRADE_CAP == F || $GRADE_CAP == T || $GRADE_CAP == M ]]; then
  # We can do it immediately here, since it's already >F, and score is 0
  IFS=$'\n' sorted_reasons=($(sort -ru <<<"${GRADE_CAP_REASONS[*]}"))
  IFS=$'\n' sorted_warnings=($(sort -u <<<"${GRADE_WARNINGS[*]}"))
  IFS=$old_ifs
  pr_bold " Protocol Support"; out " (weighted)  "; outln "0 (0)"
  # [...]
else
  # [...]
  ## Calculate final score and grade
  IFS=$'\n' sorted_reasons=($(sort -ru <<<"${GRADE_CAP_REASONS[*]}"))
  IFS=$'\n' sorted_warnings=($(sort -u <<<"${GRADE_WARNINGS[*]}"))
  IFS=$old_ifs
  # If any category resulted in a score of 0, push final grade to 0
  if [[ $c1_score -eq 0 || $c2_score -eq 0 || $c3_score -eq 0 ]]; then
    final_score=0
  else
    final_score=$((c1_wscore+c2_wscore+c3_wscore))
  fi
# [...]
fi
```
I can take a look at it tomorrow, if you haven't made a PR yet :)
