### ISSUE TITLE
[Feature request] Differentiate between public and private PKI for 398days check

### ISSUE THREAD

**Issue by Lozik** [drwetter/testssl.sh#2246]
**Which version are you referring to**
3.1dev

**Describe your feature request (if it's a technical feature)**
In #1710 , a check has been included that verifies the certificate lifetime: if the certificate has been issued after a certain date and has been created with a lifetime of more than 398 days, the check fails. This is a good check, however it misses one important detail: As far as I can tell, browser vendors added their checks for publicly-trusted PKIs/root CAs, but not for enterprise/internal/custom root CAs.
I would thus propose to add a check wether the issuer is a publicly-trusted CA. This will help companies that might use this tool for the check of their internal certificates. 
At least a difference in alerting level would be helpful.
Unfortunately, I don‘t exactly know the inner workings of Testssl an don‘t know which truststore is used. Perhaps an useful indication is the commandline argument that allows for private/enterprise root CAs to be added during the check?

Some sources of my above statement related to the private/public PKI differentiation:
- https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/certificate_lifetimes.md
- https://support.apple.com/en-us/HT211025
- https://wiki.mozilla.org/CA/Revocation_Checking_in_Firefox#Enterprise_PKIs

I hope this would be useful for others, too, and I want to use the opportunity to thank for this great and helpful tool.

**Comment by drwetter** [comment]
Hi @Lozik ,

thanks for the input.

Technically that would be doable. However: why do you think an internal CA should issue longer living certificates than their internet counterparts? 

I understood the content of the links however I assume that people would dump their browsers of their vendors issue a warning or don't want to connect anymore. This is why they are doing it, I believe.

The point of reducing the lifetime is minimizing the window for loss of the private key, encourage people to rotate key material more often. The allowed lifetime started with 96 months. That's even the timespan when you cannot be sure that the crypto used to generate keys and certificates were good enough for the whole life time.

A good historical heads up is here: https://portswigger.net/daily-swig/tls-certificate-lifespan-cut-short-a-win-for-security-or-cause-for-chaos

So, to me a general relaxation of a warning for non-public certificates is the wrong thing to do.

**Comment by Lozik** [comment]
Hi Dirk,

I fully understand the security aspect of this and I agree that a quicker rotation is in most cases a major improvement in security. On the other hand there is the current practice of companies that do not rotate internal certificates as often. Again, security-wise a bad practice, but in the tradeoff between security and usability/maintainability, it‘s often the taken course of larger companies (if they are even using an internal PKI instead of self signed certificates).

I think one should do a differentiation of „insecure“ and „not working“. A public-PKI certificate of more than 398 days is simply not working, so it is effectively the same as an invalid certificate. An internal certificate of a lifetime of more than 398 days might very well be insecure (and a warning should appear) but it is still working in web browsers. It is then, with that information, that stakeholders can and should take an informed decision.

**Comment by drwetter** [comment]
Not sure I am following you as there's a shy warning only

![image](https://user-images.githubusercontent.com/8036727/192706847-a6673158-746c-4813-99e7-07ac5e0a7825.png)

That is independent on the CA origin. If I read your points not completely wrong should suffice for internal CAs (we maybe should consider s stronger warning on public CAs)

**Comment by Lozik** [comment]
Sure, that would be an idea. Sorry, I did not really check all the edge cases and the implications of that check in the main validity.
I think it might be worth keeping a warning (as in your screenshot above) for the insecure lifetimes (i.e. more than 1 year), but adding a clear "invalid" message if that's a cert signed by a publicly trusted CA.

For people that have included Testssl.sh in some scripts/CI/monitoring system, it will then be easy to see if it is a problem to availability or potentially in conflict with a company policy.

**Comment by drwetter** [comment]
> I think it might be worth keeping a warning (as in your screenshot above) for the insecure lifetimes (i.e. more than 1 year), but adding a clear "invalid" message if that's a cert signed by a publicly trusted CA.

Public trusted CAs won't issue certificates with a longer validity period. If they do, it could be that browser vendors remove their CA (https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.8.4.pdf) :
 _The CP for the Issuance and Management of Publicly‐Trusted Certificates describe a
subset of the requirements that a Certification Authority must meet in order to issue
Publicly Trusted Certificates. This document serves two purposes: to specify Baseline
Requirements and to provide guidance and requirements for what a CA should include
in its CPS. Except where explicitly stated otherwise, these Requirements apply only to
relevant events that occur on or after 1 July 2012 (the original effective date of these
requirements)._

![image](https://user-images.githubusercontent.com/8036727/194705114-8def9a62-1fcf-4484-83f3-c0962e3e1ee6.png)

Thus I am closing this. If you feel this is wrong, don't hesitate to speak up .

Thanks, Dirk
