### ISSUE TITLE
Error parsing a server hello

### ISSUE THREAD

**Issue by digininja** [drwetter/testssl.sh#2255]
The site requires a client certificate to access it. Trying in Chrome gives:

```
ERR_BAD_SSL_CLIENT_AUTH_CERT
```

In testssl.sh I get this:

```
./testssl.sh --each-cipher 1.2.3.4:443

.....

 rDNS (2.58.8.218):      --
 Service detected:       certificate-based authentication => skipping all HTTP checks

./testssl.sh: line 1124: 16#: invalid integer constant (error token is "16#")
./testssl.sh: line 11756: 2+: syntax error: operand expected (error token is "+")
```

I know nothing about the headers, but I assume one is missing or blank due to the certificate auth and you assume it will never be.

Happy to send you the target IP privately if you want it.

**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version ( ``git log | head -1``  / ``testssl.sh -v | grep from``)

```
$ git log | head -1
commit 981432c19a3bf45cfef146bf8e475e560c321171
$ ./testssl.sh -v | grep from
    testssl.sh       3.0rc2 from https://testssl.sh/dev/
$ git branch 
* 2.9dev
```

**Before you open an issue please whether this is a known problem by searching the issues**
Couldn't find anything 

**Expected behaviour**
It doesn't break

**Comment by drwetter** [comment]
Hi @digininja ,

that is likely fixed in the current version. What you're using is pretty old. ;-) Please use either 3.0.8 or 3.2rc2.

Thus I am closing this. Please report back if the problem persists with a newer version. 

Cheers, Dirk

**Comment by drwetter** [comment]
PS: works for me on secure.cacert.org . Feel free to send me the IP if an upgrade still doesn't help.

**Comment by digininja** [comment]
Odd as I did a git pull before running it so assumed I was on the latest
version. I'll try to work out why I'm not when I get home.

**Comment by digininja** [comment]
Got it, I did a pull and got some changes, but I didn't notice I was on the old branch.

It is working on the 3.1dev branch.

**Comment by drwetter** [comment]
good. That was backported, too to 3.0.x.
