### ISSUE TITLE
[BUG / possible BUG] Script freezes/hangs on the DROWN check

### ISSUE THREAD

**Issue by mtbike61384** [drwetter/testssl.sh#2271]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version 3.2rc2

**Before you open an issue please whether this is a known problem by searching the issues**
I couldn't find anything specifically related to my issue

**Command line / docker command to reproduce**
Which was your command line?
./testssl.sh -p -U https://192.28.122.75

**Expected behavior**
For all other hosts the script does each vulnerability check and moves on to finish. For some reason with this one host the script gets to the DROWN check and just sits there forever. No errors or nothing. Its like it is stuck in an infinite loop. 

**Your system (please complete the following information):**
 - OS: Kali GNU/Linux Rolling
 - Platform: Linux 5.18.0-kali7-amd64 x86_64
 - OpenSSL: ./bin/openssl.Linux.x86_64  "Using "OpenSSL 1.0.2-bad (1.0.2k-dev)" [~183 ciphers]"

**Additional context**

**Comment by dcooper16** [comment]
Hi @mtbike61384,

Thanks for reporting. I was able to reproduce the issue. It seems that the following command hangs in the call from `run_drown()` to `get_host_cert()`:
```
./bin/openssl.Linux.x86_64 s_client -connect 192.28.122.75:443 -no_comp -cipher aRSA < /dev/null
```
According to Wireshark, OpenSSL 1.0.2-bad sends an SSLv2 ClientHello when given this command. The connection will work as expected if the `-no_ssl2` option is added or if a version of OpenSSL that does not support SSLv2 is used. The connection will also work if the `-cipher aRSA` option is removed. So, I don't understand exactly under what circumstances 192.28.122.75 simply doesn't respond to a ClientHello (causing `$OPENSSL s_client` to hang).

It seems that the solution here is to add the `-no_ssl2` option to the command. The purpose of the call to `get_host_cert()` in `run_drown()` is to obtain the server's RSA certificate. However, the certificate is only needed in the case that the server does not support SSLv2. So, it shouldn't matter that adding `-no_ssl2` would result in the certificate being missed in case the server only supports SSLv2. I'll submit a PR soon.

**Comment by mtbike61384** [comment]
Thanks for the quick response! As a workaround I found I could use --openssl-timeout but appreciate the fix.

**Comment by drwetter** [comment]
Thanks also to @mtbike61384
