### ISSUE TITLE
--html flag not generating HTML reports when run in Docker

### ISSUE THREAD

**Issue by huornlmj** [drwetter/testssl.sh#2277]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version "drwetter/testssl.sh:latest" from Docker hub

**Before you open an issue please whether this is a known problem by searching the issues**
Couldn't find anything

**Command line / docker command to reproduce**
```console
$ docker run --rm drwetter/testssl.sh:latest --mapping iana -P --html https://some-tls-server
```

**Expected behavior**
Not sure.  I suppose the HTML files might be saved inside the container but they are stored in the container when it finished, or in my example (--rm) it vanishes as it's deleted.  So perhaps I need to mount a host volume inside the container, but to where?  I know the working dir is /home/testssl, but I cannot host volume mount that because then the testssl.sh script won't be there.

**Your system (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Platform: Linux 4.15.0-176-generic x86_64
 - OpenSSL: Using "OpenSSL 1.0.2-bad (1.0.2k-dev)" [~183 ciphers]

**Comment by drwetter** [comment]
https://github.com/drwetter/testssl.sh/blob/3.1dev/Dockerfile.md
