### ISSUE TITLE
There is difference in the results of ciphersuites between Qualys and TestSSL 

### ISSUE THREAD

**Issue by bawejaVanshita** [drwetter/testssl.sh#2287]
Following cipher suites found to be weak in Qualys(https://www.ssllabs.com/ssltest/analyze.html) tool:

`TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027) ECDH x25519 (eq. 3072 bits RSA) TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028) ECDH x25519 (eq. 3072 bits RSA) 
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x67) DH 4096 bits
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x6b) DH 4096 bits
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013) ECDH x25519 (eq. 3072 bits RSA)
 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014) ECDH x25519 (eq. 3072 bits RSA) 
TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x33) DH 4096 bits 
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39) DH 4096 bits`

but in testssl output, these are not weak. These are coded with green color.

Why is there a difference in the results of cipher suites between Qualys and TestSSL?
Are these vulnerable cipher suites?

**Comment by drwetter** [comment]
Don't know how you discovered that they are green?

![image](https://user-images.githubusercontent.com/8036727/206704675-b26ffc69-3da3-4043-9a63-fba799808fb9.png)

**Comment by bawejaVanshita** [comment]
Following is the screenshot of my output that has green coded ciphers:
![image](https://user-images.githubusercontent.com/45038162/207023201-4a4fa027-aca4-42f3-8fce-496357249639.png)

Version of testssl: 3.2 rc2
![image](https://user-images.githubusercontent.com/45038162/207023121-06d862a5-40e2-4e2a-9768-ad9032d7577f.png)

Could you check why this color coding is not matching with yours?

**Comment by drwetter** [comment]
The ciphers aren't green coded. The DH/ECDH length is. *)

--color=3 is what I used.


*) which admittedly is not consistent

**Comment by bawejaVanshita** [comment]
Yes. why ciphers didn't come with color codings for me? Is it any version difference?

**Comment by drwetter** [comment]
As said, use ``--colors=3``
