### ISSUE TITLE
[Feature request]: optionally exclude certificate issues from rating

### ISSUE THREAD

**Issue by abaumfalk** [drwetter/testssl.sh#2288]
**Which version are you referring to**
3.1dev

**Please check this repo whether this is a known feature request**
no

**Describe your feature request (if it's a technical feature)**
Ignore certificate issues in the currently experimental rating section.

**If your feature request otherwise is related to a usage problem, please describe it**
I use testssl.sh to check the webserver configuration of an embedded device's, whose software image I configure and provide for our customers. As the customer will be responsible to generate and install a valid certificate, I am using a default self-signed certificate during my test. For my test documentation I would like to exclude all certificate-related checks from the overall rating, which currently shows: "Grade capped to T. Issues with the chain of trust (self signed)" and "Grade capped to M. Domain name mismatch".

**Describe the solution you'd like**
commandline switch, such as "--rating-ignore-certificate"

**Comment by drwetter** [comment]
Hi,

thanks but no. :-)

* I am in general very hesitant to implement tweaks to the SSLlabs rating to make something look better. It is like it is.
* As a workaround you can install a certificate from a private CA and pass the public key  with e.g. ``--add-ca``. Still, the CN of the host has to match.
