### ISSUE TITLE
Better support for internal CAs

### ISSUE THREAD

**Issue by Harinus** [drwetter/testssl.sh#230]
A feature for exporting all trusted certificates from the local Browser (IE, Firefox, Chrome and others) would be nice (Manual or even automatic)
Imagine following Use-Case:
Using testssl.sh to check hundreds of internal webservers with certificates issued from a internal PKI (root Certificate self-signed) and certificates issued from public Root CAs.
To verify the Chain of trust effectively it is required to have all company issued certificates and the built-in modules in one PEM file.
I did this manually but its a lot of work and enforces maintenance when certificates will be renewed.

-> separated from Issue #199

**Comment by drwetter** [comment]
The framework is basically there but the output is not that nice yet (see pic for one of my private CAs). You just need to put a the public key as *.pem of the Root-CA in the etc directory.

![plugin1](https://cloud.githubusercontent.com/assets/8036727/10999586/2e3f6d44-849d-11e5-95ae-e1ce4737560b.png)


Note the output of the checks against the other stores -- but I translate here just what verify(1) returns, i.e. X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN.

What is open maybe is to have a switch or so that **this** is the CA is the one to ultimately trust.

Makes sense?

Cheers, Dirk

**Comment by Harinus** [comment]
Yep, i exported the Root-CA as *.pem. But: We have 15 of them in organized in 3 Trees of 3 Layers (Root->Policy->Device / User or External) so generating the .pem is not a task of 30 seconds.

I have a similar output to yours:
![store](https://cloud.githubusercontent.com/assets/5645416/11001175/3a9e466a-84a6-11e5-8159-f91aeb9f2bb1.png)


One point to avoid miscomuication: only my own PEM is green. Which is technically correct, but do i really want to have the information of all the others? which may not even be applicable to my company? therefore a feature for building one PEM for "simulating" a cooperate browser to check against would be what i see as an improvement. 

Your suggested swich sounds like a good solution: Check foreach (linux,mozilla,microsoft) if NOT OK then check(own_ca) if ok then "OK" else "notOK"

**Comment by drwetter** [comment]
Am 11/06/2015 um 04:51 PM schrieb Martin Hoffmann:
> Yep, i exported the Root-CA as *.pem. But: We have 15 of them in organized in 3 Trees of 3
> Layers (Root->Policy->Device / User or External) 

(OMF?)

> so generating the .pem is not a task of 30 seconds.

You probably need to do it once in a while.

> I have a similar output to yours:
> store
> <https://cloud.githubusercontent.com/assets/5645416/11001175/3a9e466a-84a6-11e5-8159-f91aeb9f2bb1.png>
> 
> One point to avoid miscomuication: only my own PEM is green. Which is technically correct, but
> do i really want to have the information of all the others? which may not even be applicable to
> my company? 

Maybe, maybe not. Don't know when you check external services from your company.

Attention, irony: I also would love to have testssl to complain for others when the chain is not
correct. This has some priority over your stance ;-)

So probably I end up supporting files with etc/*.PEM (in caps). And there still will
be a common warning of the stores I provide.

> therefore a feature for building one PEM for "simulating" a cooperate browser to
> check against would be what i see as an improvement.

You can export the browser store and put it into the directory, too

Cheers, Dirk

**Comment by Harinus** [comment]
Well, i do not administer the PKI, so i cant change that... 

An option to specify one .pem file as the "internal pki" which turns all other pems green even if they would give an error (due to missing non-public chain certificate) with the logic from my post above would be a good solution for all use cases in my opinion.

Can you tell me how to export the browser store on windows? (Including all manually added ones?) Having a semi-automated process is better than concatenating 15 manually exported files ;)

**Comment by drwetter** [comment]
hey @Harinus, come on!  Google is your friend -- similar as you would do it with the GUI for firefox (FF).

I wouldn't do it though as both FF and IE retrieve intermediate certificates automatically if the chain is not complete. You should only export from a unused system.

**Comment by Harinus** [comment]
Sure, i know how to export Certificates... but i did not find any information on how to export all Root-Certificates into one PEM file... Maybe we talk about different things here.

If you don't like the option for specifiying the "internal pki-pem" which should be virtually included in all other PEM files to check you can close this issue.

**Comment by drwetter** [comment]
Just as usual Click+Shift Click will select all. Then you can export them.

As I mentioned there will be a -- capital -- .PEM file which makes the output less ugly. But everybody needs to receive a quite clear warning.

**Comment by Harinus** [comment]
Selecting multiple certificates disables the X.509 format in the export dialog in the Cert-Mgr.. But nevermind thats kinda off-topic

OK, fine! Once its implemented there might be more feedback from other users to optimize this feature even more.

**Comment by rdebath** [comment]
Not sure if this is where I saw it before, but there is an issue with cloning the Microsoft trusted certificate store. It's not complete.

If windows sees a certificate it doesn't know it will attempt to download it from Microsoft's Windows Update. The `CertUtil -syncWithWU` command will download the full (Microsoft) set; looks like 362 certificates at the last count.

**Comment by drwetter** [comment]
It was #825. I removed the (17) expired certificates before putting all together.

**Comment by rdebath** [comment]
Hmm, I seem to remember that Windows doesn't care if the _root_ certificate is expired. It's just that real CA's (CAB forum) who re-issue the certificates.

**Comment by drwetter** [comment]
``testssl.sh`` needs to care -- atm this is the only way.

**Comment by krissi** [comment]
I hacked my testssl.sh to support private CAs. As all clients have the private CA installed in all browsers, I took this as precondition and concatted the private CA files to testssl's bundles in `testssl.sh`. I want to use the unmodified bundles distributed with testssl as reference, so I did not just modify these.

```patch
diff --git a/testssl.sh b/testssl.sh
index 987522d..bcc2caa 100755
--- a/testssl.sh
+++ b/testssl.sh
@@ -5778,9 +5778,9 @@ determine_trust() {
           # set SSL_CERT_DIR to /dev/null so that $OPENSSL verify will only use certificates in $bundle_fname
           (export SSL_CERT_DIR="/dev/null"; export SSL_CERT_FILE="/dev/null"
           if [[ $certificates_provided -ge 2 ]]; then
-               $OPENSSL verify -purpose sslserver -CAfile "$bundle_fname" -untrusted $TEMPDIR/intermediatecerts.pem $HOSTCERT >$TEMPDIR/${certificate_file[i]}.1 2>$TEMPDIR/${certificate_file[i]}.2
+               $OPENSSL verify -purpose sslserver -CAfile <(cat "$bundle_fname" $ADDITIONAL_CA_FILES) -untrusted $TEMPDIR/intermediatecerts.pem $HOSTCERT >$TEMPDIR/${certificate_file[i]}.1 2>$TEMPDIR/${certificate_file[i]}.2
           else
-               $OPENSSL verify -purpose sslserver -CAfile "$bundle_fname" $HOSTCERT >$TEMPDIR/${certificate_file[i]}.1 2>$TEMPDIR/${certificate_file[i]}.2
+               $OPENSSL verify -purpose sslserver -CAfile <(cat "$bundle_fname" $ADDITIONAL_CA_FILES) $HOSTCERT >$TEMPDIR/${certificate_file[i]}.1 2>$TEMPDIR/${certificate_file[i]}.2
           fi)
           verify_retcode[i]=$(awk '/error [1-9][0-9]? at [0-9]+ depth lookup:/ { if (!found) {print $2; found=1} }' $TEMPDIR/${certificate_file[i]}.1 $TEMPDIR/${certificate_file[i]}.2)
           [[ -z "${verify_retcode[i]}" ]] && verify_retcode[i]=0
```

**Comment by drwetter** [comment]
Sounds like a good alternative!  Q is only how to deal with multiple private CAs: directory (``--add-ca=mydir``) or multiple files (``--add-ca=ca1.pem,ca2.pem``).

Tending toward the latter

**Comment by krissi** [comment]
In the example above, `ADDITIONAL_CA_FILES` is interpreted by the shell, so it is a mix of both ("up to the user").

```bash
FOO="/proc/sys/**/*_forward /proc/self/fd/[0-1] /etc/fstab"
(
shopt -s globstar
shopt -s failglob
echo $FOO
)
# => /proc/sys/net/ipv4/ip_forward /proc/self/fd/0 /proc/self/fd/1 /etc/fstab
```

**Comment by drwetter** [comment]
Thanks @krissi for your smart suggestion to this forgotten issue.

What I finally did probably won't work for directories or an expansion within testssl.sh as I wanted to catch some user problems. Also atm ADDITIONAL_CA_FILES cannot contain spaces.
