### ISSUE TITLE
[Feature request] Dockerfile - Include `openssl1.1-compat`

### ISSUE THREAD

**Issue by polarathene** [drwetter/testssl.sh#2314]
Extracted from https://github.com/drwetter/testssl.sh/pull/2305 (_specifically [this commit](https://github.com/drwetter/testssl.sh/pull/2305/commits/ec33e4c1f2a626b3572d3f7c00d9081f489f8e25)_)

**Which version are you referring to**
Both releases: `3.0.x` + `3.1dev`

**Please check this repo whether this is a known feature request**
This is for the recent upgrade to Alpine 3.17 where OpenSSL package is now the `3.x` series, instead of the previous `1.1` series.
- There [was an attempt to PR this](https://github.com/drwetter/testssl.sh/pull/2305). It was closed for proposing too many changes at once.
- [An observation with local performance](https://github.com/drwetter/testssl.sh/issues/2299#issuecomment-1409545691) of `1.1` performing notably better than `3.x` for a CI test suite.

**If your feature request otherwise is related to a usage problem, please describe it**
- It was observed to be about 30 seconds faster (_~190 sec vs ~220 sec_). About a 15% improvement in run time.
- There may be other reasons to carry both versions of OpenSSL packages in the image, at least until the `3.x` series is more broadly available (_Debian Bullseye for example deploys with `1.1`_).

**Describe the solution you'd like**
- Adding the `openssl1.1-compat` package (adds 4MB).
- Alternatively offering a Debian or similar base image variant for `glibc` where performance seems better than Alpine with `musl` at the expense of image size.

---

This is just a suggestion based on insights from the referenced issue and closed PR.

It might be worth waiting to see if it interests / impacts anyone else, or if they also get approx 15% faster run times (_both for parallel and single tests_).

**Comment by polarathene** [comment]
CI (GitHub Actions) workflow runs for the test cases I had observed performance of locally (_with `--openssl /usr/bin/openssl`_) now cover the `drwetter/testssl.sh:3.1dev` image changed from Alpine 3.16 (OpenSSL 1.1) to Alpine 3.17 (OpenSSL 3.0) below.

---

[Alpine 3.16](https://github.com/docker-mailserver/docker-mailserver/actions/runs/4061405206/jobs/6991408252#step:5:10) (199s):

```
ok 2 [Security] (TLS) (cipher lists) 'TLS_LEVEL=intermediate' + RSA in 34254ms
ok 3 [Security] (TLS) (cipher lists) 'TLS_LEVEL=intermediate' + ECDSA in 30780ms
ok 4 [Security] (TLS) (cipher lists) 'TLS_LEVEL=intermediate' + ECDSA with RSA fallback in 34941ms
ok 5 [Security] (TLS) (cipher lists) 'TLS_LEVEL=modern' + RSA in 32754ms
ok 6 [Security] (TLS) (cipher lists) 'TLS_LEVEL=modern' + ECDSA in 31752ms
ok 7 [Security] (TLS) (cipher lists) 'TLS_LEVEL=modern' + ECDSA with RSA fallback in 35344ms
```

[Alpine 3.17 update](https://github.com/docker-mailserver/docker-mailserver/actions/runs/4081010248/jobs/7034047808#step:5:10) (223s):

```
ok 2 [Security] (TLS) (cipher lists) 'TLS_LEVEL=intermediate' + RSA in 37618ms
ok 3 [Security] (TLS) (cipher lists) 'TLS_LEVEL=intermediate' + ECDSA in 35239ms
ok 4 [Security] (TLS) (cipher lists) 'TLS_LEVEL=intermediate' + ECDSA with RSA fallback in 39413ms
ok 5 [Security] (TLS) (cipher lists) 'TLS_LEVEL=modern' + RSA in 37449ms
ok 6 [Security] (TLS) (cipher lists) 'TLS_LEVEL=modern' + ECDSA in 36310ms
ok 7 [Security] (TLS) (cipher lists) 'TLS_LEVEL=modern' + ECDSA with RSA fallback in 37397ms
```

So local observations are likely to benefit the Github Actions CI runs by approx 15% as well if `openssl1.1-compat` were used instead.

**Comment by drwetter** [comment]
> CI (GitHub Actions) workflow runs for the test cases I had observed performance of locally (with --openssl /usr/bin/openssl) now cover the drwetter/testssl.sh:3.1dev image 

Probably I haven´t looked good enough at this. Any change in the Dockerimage which is not coherent with the pulled files is not something which I am really fond of -- for both the CI and the user image. 

For the former case the point of the CI test is to test the binary. I´d rather skip one test there. And to the user the image should hand out the same as if it's pulled from the repo.

In next development stage (after 3.2) is usage of a different openssl version per default probably a good idea (TBC).

**Comment by polarathene** [comment]
When I was talking about CI, I meant the CI runs on a project I maintain where `testssl.sh` was used via the Docker image.

---

> Any change in the Dockerimage which is not coherent with the pulled files is not something which I am really fond of -- for both the CI and the user image.

No change here. Just an additional package installed in the image that can be used with `--openssl` as an alternative binary.

The user running the image would explicitly provide that option and path to use the `openssl1.1-compat` binary.

> And to the user the image should hand out the same as if it's pulled from the repo.

Sorry, I'm not following?

With the upgrade to Alpine 3.17 base image, OpenSSL is 3.x series, where as previously it was the 1.x series. This is not related to `testssl.sh` beyond `Dockerfile`.

A pull from this repo doesn't control the OpenSSL provided within the base image (_or outside of Docker, whatever OpenSSL is on the host system_).

---

It's all good to decline this request :+1: 

Main benefit is the observed 15% faster performance running `testssl.sh` with the OpenSSL 1.x series.
