### ISSUE TITLE
Docker image problem?

### ISSUE THREAD

**Issue by OG-zz** [drwetter/testssl.sh#2324]
zz@nope:/# docker run --rm -ti drwetter/testssl.sh www.google.com

ATTENTION: No cipher mapping file found!
Please note from 2.9 on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.

Type "yes" to ignore this warning and proceed at your own risk --> yes

ATTENTION: No TLS data file found -- needed for socket-based handshakes
Please note from 2.9 on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.

Type "yes" to ignore this warning and proceed at your own risk --> yes

Fatal error: cannot exec or find any openssl binary

zz@nope:/#

What am I doing wrong? I did tried with :latest, :3.0, :3.1dev tags and the same problem occurred.

**Comment by drwetter** [comment]
hmm, works for me.

Could you please fill out the template and file again a proper bug report?

Thanks
