### ISSUE TITLE
Change Accept header to "*/*" instead of "text/*" for HTTP/1.1 GET request

### ISSUE THREAD

**Issue by rafiek** [drwetter/testssl.sh#2325]
Thank you for this great tool.

I have a question and possibly a feature change request. I noticed that when HTTP/1.0 is used the Accept header uses "\*/\*" as a MIME type. This is great! Works well and seems logical as the payload of the response is not really important when checking the certificate.

However, whenever HTTP/1.1 is used then the Accept header uses "text/*" as a MIME type. This causes some minor issues with some of the checks we are doing. An example of such a request here:

https://github.com/drwetter/testssl.sh/blob/e57527f3ec3b77a01773d3ebb383ca66d68fd3dd/testssl.sh#L17196

1. Why is it that when HTTP/1.1 is used the Accept header is "text/*" ?
2. If it isn't all that important, then could you please change it to "\*/\*"? That works well with all checks!

regards,
Rafiek

**Comment by drwetter** [comment]
Hi @rafiek ,

thanks! See PR above which will be merged this evening.

Cheers, Dirk
