### ISSUE TITLE
Brew package

### ISSUE THREAD

**Issue by frdmn** [drwetter/testssl.sh#233]
A package/formula for Brew (OS X) package manager would be nice!

**Comment by connorshea** [comment]
This has been added.

**Comment by drwetter** [comment]
Cool, thx a bunch! 

(The previous notification did not end up in my HAM folders.)

**Comment by frdmn** [comment]
Thanks!

**Comment by jrobertsz66** [comment]
I installed this on Mavericks and it hangs for me after line rDNS (192.168.1.95)  somednsname

**Comment by jrobertsz66** [comment]
I've been able to run the same script on ubuntu but I cannot get it to run on OSX.

**Comment by drwetter** [comment]
please provide proper input, I unfortunately can't read thoughts.

script -c "bash -vx testssl.sh --debug=2 <target> ".

**Comment by bknowles** [comment]
I think this comment belongs on issue #284 , where I have already responded.
