### ISSUE TITLE
[Feature request] add color parameters for both html and log

### ISSUE THREAD

**Issue by fuzzy17** [drwetter/testssl.sh#2331]
**Which version are you referring to**
 3.2rc2

**Describe your feature request (if it's a technical feature)**
Allow color in html, but not in log.

**If your feature request otherwise is related to a usage problem, please describe it**
Would be nice to have color in html, but not needed in log.  I look for "Overall Grade" in log and assign to a variable, but the escape codes messes up the email contents that I send.  Yes, I could strip the escape codes out of that variable.

**Describe the solution you'd like**
Two color parameters, one for html and one for log.

**Comment by drwetter** [comment]
That's a very special requirement which would make it too complicated/bloated at the moment.

See https://superuser.com/questions/380772/removing-ansi-color-codes-from-text-stream . 
``sed -e 's/\x1b\[[0-9;]*m//g'`` worked fine for me.
