### ISSUE TITLE
mimimal DNS done when asked to do none

### ISSUE THREAD

**Issue by digininja** [drwetter/testssl.sh#2361]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version
```
└─$ git log | head -1
commit be987d17a0c64c7f1c55c10afbee9172f415bd49
```

Just done a pull from 3.1dev branch.

**Command line / docker command to reproduce**
Asked for no DNS look up with `-n none`:
```
└─$ ./testssl.sh --sweet32 -n none 10.190.145.130
```

The scan starts and shows this:

```
rDNS (10.190.145.130):  (instructed to minimize DNS queries).
```

**Expected behaviour**
No DNS should be done, not minimised.

From a quick look at network traffic, I don't think it is doing the DNS lookups, just showing the wrong message, but haven't got time at the moment to fully debug it.

**Your system (please complete the following information):**
 - OS: Kali GNU/Linux Rolling

 - Platform: Linux 6.0.0-kali6-amd64 x86_64

 - OpenSSL: ``./bin/openssl.Linux.x86_64'``

**Additional context**
Also saw the problem with whatever version comes in the Kali package.

**Comment by drwetter** [comment]
Yup, thanks! The message is wrong.

**Comment by drwetter** [comment]
fixed now

**Comment by digininja** [comment]
I like an easy fix, thanks.
