### ISSUE TITLE
Instructions to use with boringSSL!

### ISSUE THREAD

**Issue by pramodrj07** [drwetter/testssl.sh#2368]
**Which version are you referring to**
3.1dev

**We are using Envoy and wanted to check how to use this tool with boringSSL. Another question is that since BoringSSL is a spin off from OpenSSL, Is there any disparity in listing of the Server's Ciphers if we do not compile the tool to use the BoringSSL? **

**Comment by drwetter** [comment]
testssl.sh comes with a version of openssl for tasks which cannot be done yet using sockets. You can use a different version of openssl but boringssl likely makes problems or doesn't work. Never tried.

**Comment by drwetter** [comment]
Closing this as we won't provide instructions for boringssl. 

If you want to make it work it might be an interesting project though.
