### ISSUE TITLE
testssl not detecting some cipher suites

### ISSUE THREAD

**Issue by moehkass** [drwetter/testssl.sh#2373]
I am using testssl version 3.0.7, when I run it on my server which is defined with a list of cipher suites, some of the cipher suites it does not detect them, so I was wondering why so?
The cipher suites that are not detected: **ECDHE-ECDSA-AES256-SHA384**, **ECDHE-ECDSA-AES128-SHA256**

I posted this question on stackoverflow: https://security.stackexchange.com/questions/270643/testssl-not-detecting-all-cipher-suites 
for more insight . My assumption is that testssl should be able to detect all cipher suites that a server support.

**Comment by drwetter** [comment]
Glad to help but as I don't have a crystal ball your input is not sufficient.

**Comment by moehkass** [comment]
Hello @drwetter Thank you for your propmt response!
did you check the attached stackoverflow question?
My question is why when I run testssl to scan the supported cipher suites on my server exposing and http service, why it does not detect all cipher suites? itn't it intended to detect all cipher suites ? or some cipher suites require additional configuration before running testssl ?

**Comment by drwetter** [comment]
As said, this is not sufficient. Please provide the host name and check e.g. with SSLlabs. I am pretty sure testssl.sh detects all ciphersuites and I guess the problem is the server side . But in order to check you need to provide more info. There's no additional configuration needed.

**Comment by dcooper16** [comment]
Hi @mhammadkassem,

It certainly seems that the answer that you have been provided on Stack Exchange is the correct one. Your response to Z.T. on June 9 suggests that your server does not have an ECDSA certificate, and people have explained why an ECDSA certificate is needed and how to create one. So, without further information it seems that testssl.sh is detecting all of the cipher suites supported by your server.

Given that it seems that it has already been explained to you on Stack Exchange why your server does not currently support the cipher suites listed above, why are you now asking here for an explanation as to why testssl.sh does not list all supported cipher suites?

**Comment by moehkass** [comment]
Hello @drwetter ,

Okay so for the sever side, it is a running an apache httpd which is configured with cipher suites inside the httpd.properties file.
httpd.properties file:

```
httpd.logLevel=info


httpd.accessLogActivated=false

# Enable the TRACE method (default: false)
# httpd.traceEnable=true

# Overrides the allowed SSL Ciphers in the context of https communication. The default list is provided below.
# httpd.sslCipherSuite=ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-CHACHA20-POLY1305,ECDHE-RSA-CHACHA20-POLY1305,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDHE-ECDSA-AES128-SHA256,ECDHE-RSA-AES128-SHA256


#################################### Certificate  ####################################
# Path to the server-side frontend certificate file of the load balancer. 
#httpd.certificate=../cert.pem

# Path to the private key corresponding to above certificate. 
#httpd.key=../key.pem

# Path to the server-side backend certificate file of the load balancer. 

#httpd.backend.certificate=../backend_cert.pem

# Path to the private key corresponding to above certificate. 
#httpd.backend.key=../backend_key.pem

```


and when I run the testssl scanner I get the output I shared in the stackoverflow question.
testssl command: testssl -E myserver.com:19000

**Comment by moehkass** [comment]
Hello @dcooper16 ,

I wanted to validate this here.

**Comment by drwetter** [comment]
see David's reply, @mhammadkassem , see lengthy explanations @ stackexchange.
