### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by l4rm4nd** [drwetter/testssl.sh#2374]
When cloning this git repository, testssl.sh will report the version 3.2rc2

When downloading the release, testssl.sh will report the version 3.0.8

When installing via package manager, testssl.sh will report the version 3.0.8

When scanning an example target HTTPS URL, only the 3.0.8 versions seem to report back a Client Renegotiation issue. The version 3.2rc2 does not and yields that everything is ok. Unfortunately, cannot share the scanned target IP.

**Comment by drwetter** [comment]
Short: 3.1dev branch , i.e. currently 3.2rc

The rest should be clear from the [readme](https://github.com/drwetter/testssl.sh#status)

If it helps we can do a released version for 3.2rc3

HTH
