### ISSUE TITLE
[BUG / possible BUG] DNS resolution fails in a container

### ISSUE THREAD

**Issue by mythi** [drwetter/testssl.sh#2378]
I'm checking my Kubernetes webhook TLS [services](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) using `testssl.sh` deployed. Things used to work with `drwetter/testssl.sh:3.0` but now fails with `drwetter/testssl.sh:3.2` (and `:latest`):

```
Fatal error: No IPv4/IPv6 address(es) for "<my service>" available
```

**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version ( ``git log | head -1``  / ``testssl.sh -v | grep from``): `drwetter/testssl.sh:3.2`

**Before you open an issue please whether this is a known problem by searching the issues**
couldn't find anything 

**Command line / docker command to reproduce**
`testssl.sh --openssl=/usr/bin/openssl --mapping iana -s -f -p -P -U  <my service>`

**Expected behavior**
`testssl.sh` to succeed the same way it does with `drwetter/testssl.sh:3.0`.

**Your system (please complete the following information):**
 - OS:  `drwetter/testssl.sh:3.2`
 
**Additional context**

**Comment by drwetter** [comment]
Hi @mythi ,

not sure whether you scan from within the k8s cluster or outside? From the inside: it's hard to tell what's going wrong as it depends on your DNS service and how you set it up. testssl.sh depends on a proper working resolver.

As a litmus test: Does (ping|host|dig|netcat) return the correct IP address?

There was one bigger DNS related change I recall btw 3.0 and 3.2 (d001bba86bbeee07ff2ced2dc146603f71f76a53) but as you don't use a proxy that shouldn't affect you.

**Comment by mythi** [comment]
> From the inside: it's hard to tell what's going wrong as it depends on your DNS service and how you set it up. testssl.sh depends on a proper working resolver.

From inside. I'm assuming the resolver works properly since it's the exact same cluster that works with `3.0` image but not when I move to `3.2`. I'll take a closer look on https://github.com/drwetter/testssl.sh/commit/d001bba86bbeee07ff2ced2dc146603f71f76a53 and try out the utils you suggested.

**Comment by drwetter** [comment]
if you have DNS query logs that would be also a useful source to look at

**Comment by mythi** [comment]
The (coreDNS) logs do not return any errors. `nslookup` returns an address and at least I can get `testssl.sh` with `--nodns=none --ip <IP from nslookup>` to work. Still debugging...

**Comment by drwetter** [comment]
Don't know about coreDNS but I just meant queries, so that you'd be aware that testssl.sh at least does a query and not only see a failed query.

**Comment by mythi** [comment]
> so that you'd be aware that testssl.sh at least does a query and not only see a failed query.

OK, I see. How do I get the logs from the DNS query. I can't see anything with `--debug 0...6` levels

**Comment by drwetter** [comment]
no clue for CoreDNS. 

But if your scan target is outside the cluster coreDNS is the forwarding server and the next hop might be a different DNS server (bind: https://www.thegeekdiary.com/how-to-enable-bind-query-logging-to-find-out-whos-querying-a-name-server/)

**Comment by mythi** [comment]
> no clue for CoreDNS.

I meant to ask how to debug what `testssl.sh` runs to do the query.

**Comment by drwetter** [comment]
Read the fine manual please ;-) hidden :-)  here: https://github.com/drwetter/testssl.sh/wiki/Findings-and-HowTo-Fix-them . best is 2a or 2b

**Comment by drwetter** [comment]
if you want to narrow it down: the functions is ``get_a_record()``, assuming there's no IPv6 in your cluster

**Comment by mythi** [comment]
> if you want to narrow it down: the functions is `get_a_record()`, assuming there's no IPv6 in your cluster

I'm still working on figuring out why this worked with 3.0 image and fails with 3.2 but the problem seems to be that `drill a <my service>`  fails (`ANSWER SECTION` is empty) with the `URI` I provided. Thanks for the wiki pointer, it helped a lot and fortunately 3.2 has script installed too! I'll keep you updated on what I find out.

**Comment by mythi** [comment]
3.2  image does not have `nslookup` installed so there is no working fallback since `drill` does not return an address. 3.0 ends up using `nslookup` after `drill` so I get an IP and this works.

**Comment by drwetter** [comment]
ok, thanks. Did you get why drill doesn't return an IP address?

**Comment by drwetter** [comment]
PS: other docker containers work -- I am pretty sure.

**Comment by mythi** [comment]
> ok, thanks. Did you get why drill doesn't return an IP address?

I was not using a FQDN and drill seems to expect that.

**Comment by vsbs-david** [comment]
Hello, I'm having a problem that might be related, containers of testssl.sh with both image tags 3.0 and 3.2 cannot resolve hostnames `.local`, an error like this appears: `Fatal error: Local hostname given but no 'avahi-resolve' or 'dig' available.`
Those commands are not available in the image, I'm not sure if they should or maybe testssl.sh could use other commands like drill or nslookup also for `.local` names. In the image 3.0, nslookup resolves my hostname, and after adding dig in the image 3.0 (via `apk update && apk add bind-tools`) testssl.sh works as expected. In the image 3.2 nslookup is not available as mentioned, but drill resolves the hostname correctly.

Then, could the Dockerfile be updated to include dig, or else use drill in the script also for `.local` hostnames?
Thanks

**Comment by drwetter** [comment]
Hi @vsbs-david ,

okay. That would be 1-3 lines in ``get_a[aaa]_record()`` but I don't have a resolver for mDNS to test it.

**Comment by drwetter** [comment]
For IPv4 $searchengine tells me ``drill @224.0.0.251 -p 5353 <HOSTNAME.local>`` should work.  Maybe you can try to insert a statement and verbosely report back

**Comment by vsbs-david** [comment]
> For IPv4 $searchengine tells me `drill @224.0.0.251 -p 5353 <HOSTNAME.local>` should work. Maybe you can try to insert a statement and verbosely report back

I tried that and it works for me but not because of that command actually returning IP addresses but because the function does not finish with fatal error and continues until doing a standard DNS query. I have created a PR and commented a bit more details there: https://github.com/drwetter/testssl.sh/pull/2417

**Comment by drwetter** [comment]
@mythi :

Seems there were two different issues here, so I'll close this now as a fix for @vsbs-david's issue is on it's way. Your issue, Mikko, seems to be solved as your latest statement was: "I was not using a FQDN and drill seems to expect that"

Let me know if that's not the case
