### ISSUE TITLE
[BUG] Strict-Transport-Security checking accepts malformed HSTS header

### ISSUE THREAD

**Issue by joshgordon** [drwetter/testssl.sh#2381]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version ( `27c77071ebd03ce88c2605b6f42768ff1d55b4bf`  / `testssl.sh       3.2rc2 from https://testssl.sh/dev/`)

**Before you open an issue please whether this is a known problem by searching the issues**
couldn't find anything 

**Command line / docker command to reproduce**
`testssl.sh https://malformed-hsts-header.joshgordon.dev `

Note: This subdomain is hosted on a cloudflare worker and I intend to keep it active indefinitely. 

**Expected behavior**
HSTS header is not valid. HSTS header is: 

```
$ curl -sS -D - malformed-hsts-header.joshgordon.dev -o /dev/null | grep Strict-Transport-Security

Strict-Transport-Security: max-age==31536000; includeSubdomains
```

You can see from the [chromium unit tests](https://github.com/chromium/chromium/blob/c4578471612ca23d9fe95da0e44c9d0853e3cd1b/net/http/http_security_headers_unittest.cc#L74) that a `max-age` with `==` is expected to not parse as a valid HSTS header. 

testssl.sh states that it is valid. 

**Your system (please complete the following information):**
 - OS: ``Fedora Linux 37 (Server Edition)``
 - Platform: ``Linux 6.0.15-300.fc37.x86_64 x86_64`` 
 - OpenSSL: ``./bin/openssl.Linux.x86_64'`` (openSSL provided with testssl)

**Additional context**
This is a pretty minor issue, and there's a few other sites on the internet that also incorrectly state that the HSTS header is valid, unfortunately.

**Comment by drwetter** [comment]
Hi,

thanks for the extended report.

I am afraid that from the development perspective this is more a feature than a bug. We would need a strict parser otherwise which not only checks for a double equal sign but for other nonsense too. That needs to be in line with the corresponding RFC. 

It's certainly something we want, so atm it's in the wishlist, not on the very top though -- unless someone steps in ;-)

Cheers, Dirk

**Comment by drwetter** [comment]
See https://www.rfc-editor.org/rfc/rfc6797#section-6.1.1

**Comment by drwetter** [comment]
It bugged me, so I thought I'll fix^Wimprove this ;-)

Please see the PR referenced
