### ISSUE TITLE
[BUG / Possible feature] Inconsistent "Secure Client-Initiated Renegotiation" with other tools

### ISSUE THREAD

**Issue by Tazmaniac** [drwetter/testssl.sh#2389]
Stable and dev branch are affected

**Command line / docker command to reproduce**
testssl.sh -R https://affected.vhost.net
* Testing for Renegotiation vulnerabilities
      Secure Renegotiation (RFC 5746)           supported (OK)
      Secure Client-Initiated Renegotiation     VULNERABLE (NOT ok), DoS threat

python -m sslyze --reneg affected.vhost.net
 * Session Renegotiation:
       Client Renegotiation DoS Attack:   OK - Not vulnerable
       Secure Renegotiation:              OK - Supported

As "affected.vhost.net" is not mine, real test host communicated to SWCONTACT

**Expected behavior**
testssl.sh should report 
    Secure Client-Initiated Renegotiation     not vulnerable (OK)

confirmed by manual testing of the Secure Client-Initiated Renegotiation availability.

Looking at the code, the two tools are in fact right because they are not testing the same thing.
In the run_renego() function there is a comment:
    # No SNI needed here as there won't be two different SSL stacks for one IP
This is right for the RFC 5746 Secure Renegotiation presence test but not for the second "Secure Client-Initiated Renegotiation" test.
As demonstrated by the communicated example (one of a long collected list), there is hosts/equipment where the client-initiated renegotiation is configured per vhost.
On the intended to be tested vhost, the configuration is not vulnerable.
But on the defaut vhost / no SNI vhost, the configuration is vulnerable.
sslyze is testing the expected vhost, but testssl.sh is not because SNI is disabled on the openssl s_client call.

Adding this little patch (diff genrerated against 3.0.7) fix the discrepancy
```
--- testssl.sh    2022-02-21 01:32:08.000000000 +0100
+++ testssl.sh        2023-09-05 15:06:20.982099278 +0200
@@ -14553,7 +14553,8 @@
      else
           # We need up to two tries here, as some LiteSpeed servers don't answer on "R" and block. Thus first try in the background
           # msg enables us to look deeper into it while debugging
-          echo R | $OPENSSL s_client $(s_client_options "$proto $BUGS $legacycmd $STARTTLS -connect $NODEIP:$PORT $PROXY") >$TMPFILE 2>>$ERRFILE &
+          # SNI needed here as this could be different per vhost
+          echo R | $OPENSSL s_client $(s_client_options "$proto $BUGS $legacycmd $STARTTLS -connect $NODEIP:$PORT $PROXY $SNI") >$TMPFILE 2>>$ERRFILE &
           wait_kill $! $HEADER_MAXSLEEP
           if [[ $? -eq 3 ]]; then
                pr_svrty_good "likely not vulnerable (OK)"; outln ", timed out"        # it hung
@@ -14561,7 +14562,7 @@
                sec_client_renego=1
           else
                # second try in the foreground as we are sure now it won't hang
-               echo R | $OPENSSL s_client $(s_client_options "$proto $legacycmd $STARTTLS $BUGS -connect $NODEIP:$PORT $PROXY") >$TMPFILE 2>>$ERRFILE
+               echo R | $OPENSSL s_client $(s_client_options "$proto $legacycmd $STARTTLS $BUGS -connect $NODEIP:$PORT $PROXY $SNI") >$TMPFILE 2>>$ERRFILE
                sec_client_renego=$?
                # 0 means client is renegotiating & doesn't return an error --> vuln!
                # 1 means client tried to renegotiating but the server side errored then. You still see RENEGOTIATING in the output
@@ -14579,7 +14580,7 @@
                               fileout "$jsonID" "MEDIUM" "VULNERABLE, potential DoS threat" "$cve" "$cwe" "$hint"
                          else
                               (for i in {1..4}; do echo R; sleep 1; done) | \
-                                   $OPENSSL s_client $(s_client_options "$proto $legacycmd $STARTTLS $BUGS -connect $NODEIP:$PORT $PROXY") >$TMPFILE 2>>$ERRFILE
+                                   $OPENSSL s_client $(s_client_options "$proto $legacycmd $STARTTLS $BUGS -connect $NODEIP:$PORT $PROXY $SNI") >$TMPFILE 2>>$ERRFILE
                               case $? in
                                    0) pr_svrty_high "VULNERABLE (NOT ok)"; outln ", DoS threat"
                                       fileout "$jsonID" "HIGH" "VULNERABLE, DoS threat" "$cve" "$cwe" "$hint"
```

**Thoughts**
As we are testing for a possible DoS vuln on the target equipment. Any found on a vhost of the target could affect all of them.
We could not discover all the vhosts to test them. But we could always test the default/without SNI one and the explicitly wanted one/with SNI (witch are the same if SNI is not available on the  target : harmless).
So a third test could be added in the -R category to test the default/non SNI vhost as testssl.sh originally do.

**Comment by drwetter** [comment]
Hi @Tazmaniac ,
thanks. For 3.2 that [was already done](https://github.com/drwetter/testssl.sh/commit/be987d17a0c64c7f1c55c10afbee9172f415bd49).

But you're right as far as the 3.0 branch is concerned. Mind to issue a PR -- as you found that?

**Comment by drwetter** [comment]
Fixed, see PR above
