### ISSUE TITLE
Server socket simulation like client simulation

### ISSUE THREAD

**Issue by vkosuri** [drwetter/testssl.sh#2413]
**Which version are you referring to**
3.2

I did searched in issue did not found this request, please do let me know if it was implemented.

I feature I am looking very similar to Client simulation in ssllabs https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#simclient similar to implement ServerSim which will provide the configuration in json to start the server feature with key, cert, and different parameters?

**Comment by drwetter** [comment]
Thanks but I believe it's too far off the scope of this project
