### ISSUE TITLE
On certain sites one or multiple warnings: grep: warning: stray \ before !

### ISSUE THREAD

**Issue by cjaone** [drwetter/testssl.sh#2431]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version 3.0.8.

**Before you open an issue please whether this is a known problem by searching the issues**
Couldn't find anything.

**Command line / docker command to reproduce**
- testssl.sh https://nextcloud.free.de

**Expected behavior**

Expected none of the multiple grep warnings below:

```
Testing HTTP header response @ "/" 

 HTTP Status Code             302 Found, redirecting to "https://nextcloud.free.de/login"
 HTTP clock skew              -1 sec from localtime
 Strict Transport Security    180 days=15552000 s, includeSubDomains
 Public Key Pinning           --
 Server banner                Apache/2.4.56 (Debian)
 Application banner           --
 Cookie(s)                    9 issued: 9/9 secure, 9/9 HttpOnly -- maybe better try target URL of 30x
grep: warning: stray \ before !
grep: warning: stray \ before !
grep: warning: stray \ before !
grep: warning: stray \ before !
grep: warning: stray \ before !
grep: warning: stray \ before !
grep: warning: stray \ before !
grep: warning: stray \ before !
grep: warning: stray \ before !
 Security headers             X-Frame-Options: SAMEORIGIN
                              X-Content-Type-Options: nosniff
                              Content-Security-Policy: referrer no-referrer
                              Referrer-Policy: no-referrer
                              Cache-Control: no-store, no-cache, must-revalidate
                              Pragma: no-cache
                              X-XSS-Protection: 1; mode=block
 Reverse Proxy banner         --
```

**Your system (please complete the following information):**
 - OS: ``Gentoo Linux``
 - Platform: ``Linux 6.1.28-gentoo x86_64``
 - OpenSSL: ``/usr/bin/openssl``
 - grep: ``grep (GNU grep) 3.11``

**Additional context**
I only saw this when checking sites related to Nextcloud.

[scan_until_warnings.txt](https://github.com/drwetter/testssl.sh/files/13195383/scan_until_warnings.txt)

**Comment by drwetter** [comment]
Thanks, looks like a known problem (#2241) occurring at a different spot., see  #2383 and #2242

My very educated guess is that ``sub_f5_bigip_check()`` is the culprit. Could you please check in line 3023 changing ``elif grep -Eq '^\!.*=$' <<< "$cookievalue"; then`` helps when removing the backslash? I don´t have grep 3.11 handy.

**Comment by drwetter** [comment]
PR submitted, see above. Actually this slipped though for 3.0 .

**Comment by cjaone** [comment]
I changed the line (it's line 2994 for me) to:

`elif grep -Eq '^!.*=$' <<< "$cookievalue"; then`

Without the backslash no warnings anymore: 👍

```
 Testing HTTP header response @ "/" 

 HTTP Status Code             302 Found, redirecting to "https://nextcloud.free.de/login"
 HTTP clock skew              -1 sec from localtime
 Strict Transport Security    180 days=15552000 s, includeSubDomains
 Public Key Pinning           --
 Server banner                Apache/2.4.56 (Debian)
 Application banner           --
 Cookie(s)                    9 issued: 9/9 secure, 9/9 HttpOnly -- maybe better try target URL of 30x
 Security headers             X-Frame-Options: SAMEORIGIN
                              X-Content-Type-Options: nosniff
                              Content-Security-Policy: referrer no-referrer
                              Referrer-Policy: no-referrer
                              Cache-Control: no-store, no-cache, must-revalidate
                              Pragma: no-cache
                              X-XSS-Protection: 1; mode=block
 Reverse Proxy banner         --
```

**Comment by drwetter** [comment]
Thx, fixed
