### ISSUE TITLE
compare with browser's ciphersuites

### ISSUE THREAD

**Issue by anarcat** [drwetter/testssl.sh#244]
great tool!

one thing this is missing, compared to (say) the Qualys SSL test suite, is a way to see which browsers are actually supported given the provided ciphersuite.

this would help a lot in diagnostics for browser problems... for example, i have heard reports that:

https://www.bidon.ca/fr/random/2014-01-02-teksavvy-ipv6-dhcpv6pd

... would work in recent versions of iceweasel, but not recent versions of chromium (debian sid). yet testssl doesn't report any anomaly.

**Comment by drwetter** [comment]
Hi again @anarcat,

thx for the flowers!

This is unfortunately not new either but still pending to be picked up from somebody, see #98.

Cheers, Dirk
