### ISSUE TITLE
[Question] TLS 1.2 sig_algs offered

### ISSUE THREAD

**Issue by B4t4l10n** [drwetter/testssl.sh#2440]
**Which version are you referring to?**
3.2rc3
----------------------------------------

Hello everyone,
I have a small question about the "TLS 1.2 sig_algs offered" check.

What does this check actually represent and where does the server use those offered sig_algs? Is it really concerning, when RSA+SHA1 is offered? How can this be disabled (where is this setting located - server/client)?

An explanation or a reference to an explanation would really helpful.

In the below example, is the offered RSA+SHA1 security concerning? 

![image](https://github.com/drwetter/testssl.sh/assets/144271799/d09ac18a-7a54-4791-a954-f6fb0d07a8dd)

**Comment by dcooper16** [comment]
> What does this check actually represent and where does the server use those offered sig_algs? Is it really concerning, when RSA+SHA1 is offered? How can this be disabled (where is this setting located - server/client)?

When using a cipher suite that offers forward secrecy, the server authenticates itself by signing some data. The client indicates which signature algorithms it is willing to accept and the server selects one based on what it is willing to use. "TLS 1.2 sig_algs offered" lists the signature algorithms that the server is willing to use with TLS 1.2.

If a client indicates that it will not accept signatures that use SHA-1, then the server cannot use SHA-1. However, the above check is only testing the server, so it can only be disabled by configuring the server to be unwilling to use SHA-1. How that is done would depend on what server you are using.

> In the below example, is the offered RSA+SHA1 security concerning?

See https://www.rfc-editor.org/rfc/rfc9155.html and the paper that it references (https://doi.org/10.14722/ndss.2016.23418).
