### ISSUE TITLE
Creation of tempdir assumes certain umasks

### ISSUE THREAD

**Issue by gammelalf** [drwetter/testssl.sh#2449]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version `3.0.8`

**Before you open an issue please whether this is a known problem by searching the issues**
Couldn't find anything 

**Command line / docker command to reproduce**
`umask 0177; testssl example.org`

**Expected behavior**
No `Permission denied` error when writing to the temp dir.

**Additional context**
The function `maketempf` uses `mktmp -d` to create the base temp dir.
When `testssl.sh` runs in an environment where a umask has been applied this directory might not have the `x` mode which is required to access a directory's children.

**Potential fix**
Set the `x` mode explicitly using `chmod u+x $TEMPDIR` directly after the `TEMPDIR=$(mktemp -d /tmp/testssl.XXXXXX)` line.

**Comment by drwetter** [comment]
Ok, thanks.

Don't know whether the approach "fixing user problems" is the right one unless this is a typical scenario in a special environment.

I'd rather add a sanity check in ``maketempf()`` whether it is really writeable.
