### ISSUE TITLE
global rating and issue summary

### ISSUE THREAD

**Issue by anarcat** [drwetter/testssl.sh#245]
it would be great to have a global rating (in percentage or A, B, ..F ratings, like Qualys) of the general quality of the SSL configuration for a given site.

then this could also show the summary of issues that failed to pass the tests and possibly suggested improvements.

**Comment by drwetter** [comment]
Hi @anarcat,

thx. For rating see #100. For improvements see #194 .

Thus closing.

Cheers, Dirk

**Comment by anarcat** [comment]
really closing, thanks for the references, sorry i didn't find those!
