### ISSUE TITLE
[BUG / possible BUG] Fatal error: URI comes last

### ISSUE THREAD

**Issue by frankiexyz** [drwetter/testssl.sh#2456]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version latest docker image

**Before you open an issue please whether this is a known problem by searching the issues**
Is related to / couldn't find anything 

**Command line / docker command to reproduce**
```
 ❯ docker run --rm -ti  drwetter/testssl.sh -h "Host: 1.1.1.1" https://1.1.1.1
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Fatal error: URI comes last


~
 ❯ docker run --rm -ti  drwetter/testssl.sh -h "Host: 1.1.1.1" 1.1.1.1
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Fatal error: URI comes last

```

**Expected behavior**
I am unable to pass `     -h, --header, --headers       tests HSTS, HPKP, server/app banner, security headers, cookie, reverse proxy, IPv4 address` to the testssl.sh  

**Your system (please complete the following information):**
 - OS: ``awk -F\" '/PRETTY_NAME/ { print $2 }' /etc/os-release``
 - Platform: ``uname -srm`` 
 - OpenSSL: ``testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'``

**Additional context**

**Comment by drwetter** [comment]
``-h `` is not meant to supply an additional header into the requests to the remote site. Additionally that (hopefully) should be futile when talking to cloudflare. Just use ``-h``

![image](https://github.com/drwetter/testssl.sh/assets/8036727/9931fc8c-3808-4814-8d8a-5fa05193d0a4)

**Comment by drwetter** [comment]
(don´t get why the time is off @ 1.1.1.1, is that really so?)
