### ISSUE TITLE
[BUG] MongoDB identification 

### ISSUE THREAD

**Issue by Tazmaniac** [drwetter/testssl.sh#2468]
The identification string for MongoDB is too loose.

Some HTTP sites are identified as "MongoDB" protocol:
https://www.mazarsrecrute.fr

The page is about ~2Mo but on one line and match the "MongoDB" keyword.

The proposed PR: https://github.com/drwetter/testssl.sh/pull/2467 fix this with a more precise string match.

**Comment by drwetter** [comment]
Mind backporting this to 3.0.x?

**Comment by Tazmaniac** [comment]
https://github.com/drwetter/testssl.sh/pull/2471 cherry-pick the fix to 3.0.x
