### ISSUE TITLE
[BUG] Secure client initiated renegotiation timing bug

### ISSUE THREAD

**Issue by Tazmaniac** [drwetter/testssl.sh#2469]
This is an old bug, more frequently triggered since the reduction of the sleep time of the renego loop.  

OpenSSL will buffer only the first command till the establishment of the session.
In case of slow session establishment, we could:
  * loose some renego trys missing proper mitigation implementation
  * loose some renego trys missing a real vulnerable host if 2/3 of the tries are lost during session establishment (very slow startup).

In the first case, some HTTP server properly implement mitigation closing connection after 10 tries, but we loose the second try command during session establishment doing effectively 9 tries and not 10 without observing connection close.
- https://intranet.routesdeguadeloupe.fr
- https://portail.baiemahault.fr
Inserting a one second wait before looping seems to fix these two cases, but:

In the second case, we have pathologically slow session establishment (a few seconds). Most renego commands are lost during the session start. On a vulnerable host, as more than 2/3 of the command where losts we falsely identify an exponential back-off mitigation.
- https://vcsa.ceva.com

The proper fix for all this cases is to wait for the session to be established before looping.

**Comment by drwetter** [comment]
Thanks, in the outcome I see only a change for portail.baiemahault.fr (top: w/o , bottom: w your PR):

![image](https://github.com/drwetter/testssl.sh/assets/8036727/07d67bfd-923c-43cd-ac09-35e1b91c7bfa)

They all reach the 10th attempt though. 

Is that what you meant?

**Comment by Tazmaniac** [comment]
Yes portail.baiemahault.fr before/after is OK
- vcsa.ceva.com : They fixed their performance problem and reach the 10 attempts with or without the fix in my case. During previous testing and fix development they only reach 4 attempts without the fix and so where falsely identified as "mitigated".
- intranet.routesdeguadeloupe.fr: hum, mystery. I checked locally and get the intended result all the time : unpatched => vulnerable. Patched "not vulnerable (OK) -- mitigated (disconnect after 10/10 attempts)". I re-checked with your actual 3.2 branch :  "VULNERABLE (NOT ok), DoS threat (10 attempts)", patched locally and get "not vulnerable (OK) -- mitigated (disconnect after 10/10 attempts)"

Do you try to connect to the URL with a navigator ? You should get a redirect to https://intranet.routesdeguadeloupe.fr/auth/ 

curl --insecure -I https://intranet.routesdeguadeloupe.fr
HTTP/1.1 302 Moved Temporarily
Date: Tue, 20 Feb 2024 07:37:36 GMT
Connection: Close
Location: /auth/
Cache-Control: no-store,no-cache,must-revalidate
Pragma: no-cache
Expires: -1
Last-Modified: Mon, 12 Jan 2000 13:42:42 GMT
Content-Type: text/html

**Comment by drwetter** [comment]
For intranet.routesdeguadeloupe.fr I always got ``VULNERABLE (NOT ok), DoS threat (x attempts)`` with x=6 for the actual branch and x=10 with your patch.

Anyway, I'll merge it. Thanks!
