### ISSUE TITLE
EC key length verdict odd?

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#249]
In routine run_server_defaults there is the following code:

          if [[ "$keysize" -le 768 ]]; then
               if [[ $sig_algo =~ ecdsa ]] || [[ $key_algo =~ ecPublicKey  ]]; then
                    pr_litegreen "EC $keysize"
               else
                    pr_red "$keysize"
               fi
          elif [[ "$keysize" -le 1024 ]]; then
               pr_brown "$keysize"
          elif [[ "$keysize" -le 2048 ]]; then
               out "$keysize"
          elif [[ "$keysize" -le 4096 ]]; then
               pr_litegreen "$keysize"
          else
               out "weird keysize: $keysize"
          fi

If I read this correctly EC keys get printed green if they are smaller or equal to 768bi, but printed in brown if they are =< 1024 bits. Is there no such thing as a too small EC key size?

**Comment by seccubus** [comment]
Also keys > 4096 bits get marked as weird.

**Comment by drwetter** [comment]
Thx, @seccubus . In fact it looks like there's some work to be done here.
