### ISSUE TITLE
Issue Severity List

### ISSUE THREAD

**Issue by sonawanesarvesh** [drwetter/testssl.sh#2494]
**Which version are you referring to**
v3.2

i tried to look for list of Severities generated by TestSSL tool 
like fatal, critical, high, medium, low, info, warn, ok - is there any further?

**Comment by drwetter** [comment]
nope -- depends how you read it. WARN means some test couldn´t be performed. If you count that one you also need to count fatal. That is when testssl.sh couldn´t continue.
