### ISSUE TITLE
Why is RSA+SHA1 in the "TLS 1.2 sig.algs offered" list

### ISSUE THREAD

**Issue by Charles1000Chen** [drwetter/testssl.sh#2495]
**Which version are you referring to**
```
###########################################################
    testssl.sh       3.2rc3 from https://testssl.sh/dev/
    (e3b3c35 2024-04-26 16:31:12)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)" [~94 ciphers]
 on seriemas1:/usr/bin/openssl
 (built: "Feb 16 08:51:30 2024", platform: "debian-amd64")
```

<img width="1099" alt="image" src="https://github.com/drwetter/testssl.sh/assets/24378960/facb11d4-ed4e-4ac3-9bbe-0a47cb716a5a">

As you can see in the sceenshot that the only TLS 1.2 cipher suite is "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384". It should not be the "RSA+SHA1" algorithm. Why the "RSA+SHA1" is in the "TLS 1.2 sig.algs offered" list?
In my test, any of the cipher suits below will introduce the "RSA+SHA1" in the "TLS 1.2 sig.algs offered" list.
```
			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
```

Is it expected result or a bug?

**Comment by dcooper16** [comment]
It is not a bug. If your server supports a cipher suite that uses RSA signatures, such as ones of the form TLS_ECDHE_RSA..., then it needs to support RSA signatures (RSA+... and/or RSA-PSS-RSAE+...). What hash function is used to create the RSA signature is not determined by the cipher suite. It is negotiated separately.

**Comment by Charles1000Chen** [comment]
@dcooper16 Thank you. I'm still a bit confused. Even though the hash function is negotiated separately, why I have clearly specified the "TLS_ECDHE_RSA_WITH_AES_256_GCM_**SHA384**" algorithm but the testssh tells that **SHA1** hash function is used? Shouldn't the hash function be SHA384? Any suggestion on how to eliminate weak SHA1 from the "TLS 1.2 sig.algs offered" list will be appreciated.

**Comment by dcooper16** [comment]
I would suggest looking at [NIST Special Publication 800-52](https://doi.org/10.6028/NIST.SP.800-52r2). Appendix B.1 explains how to interpret TLS 1.2 cipher suite names, and the example at the end of the section is very similar the one you mentioned. Section 3.4.1.4 talks about the signature algorithms extension.
