### ISSUE TITLE
[BUG] Inconsistent bold in report

### ISSUE THREAD

**Issue by digininja** [drwetter/testssl.sh#2499]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version ( ``git log | head -1``  / ``testssl.sh -v | grep from``)

A fresh pull from dev.

```
$ git log | head -1
commit 5b75dd7f01543a6224040a1412c4d10770dac3c7

$ ./testssl.sh -v | grep from
    testssl.sh       3.2rc3 from https://testssl.sh/dev/
```

**Before you open an issue please whether this is a known problem by searching the issues**
Couldn't find anything 

**Command line / docker command to reproduce**
Which was your command line? In addition the target of your scan would be helpful. If you don't want to disclose it publicly: ``grep SWCONTACT testssl.sh``.

Just running as normal against a site with some weak crypto.

```
./testssl.sh 1.2.3.4
```
I can send you an IP if you need it, but I don't think you probably will

If you look at the screenshot, the first three lines have their comments in bold, then LOW and Triple are not in bold, Obsoleted is, and then Strong isn't.

![image](https://github.com/drwetter/testssl.sh/assets/117081/7b5132f9-ba2b-4ce4-9522-8852ca9b84ed)

**Expected behavior**
Make the all consistent. Maybe just the bad stuff bold.

**Your system (please complete the following information):**
 - Ubuntu 22.04.4 LTS
 - Linux 5.15.0-105-generic x86_64

**Additional context**

**Comment by drwetter** [comment]
Thanks for the report! 


We only have a limited number of colors here: three shown, but there's also yellow for _low_ which isn't displayed here. so bold or not bold is used as an emphasis or attenuation.

Bold is just trying to indicate whether it is really good or really bad. Not bold means it's not the worst in the bad category or it's not the best in the good category.

**Comment by digininja** [comment]
So that is saying obsolete ciphers are really bad but triple DES is just
normal bad.

If it's deliberate that's fine, I'll try to remember to close this when
back at my desk.
