### ISSUE TITLE
If wildcard cert doesn't match ( isn't closed

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#250]
In the common name part of run_server_defaults

          if echo -n "$cn" | grep -q '^*.' ; then
               out " (wildcard certificate"
               if [[ "$cn" == "*.$(echo -n "$cn" | sed 's/^\*.//')" ]]; then
                    out " match)"
                    wildcard=true
               else
                    :
                    #FIXME: we need to test also the SANs as they can contain a wild card (google.de .e.g) ==> 2.7dev
               fi
          fi

If the wildcard doesn't match the bracket of "(wildcard certificate" is not closed and user not alerted for the mismatch.

**Comment by drwetter** [comment]
yes, thx. 

Just for clarification: Do you mean anything different as what the #FIXME said? Google.de seems to have been such an example but it doesn't work anymore.

Generally / other than the wildcard: the CN <--> hostname check is still an open point, see #94 .  It appeared not that easy to have a rock solid check here. Any help is welcome.

**Comment by drwetter** [comment]
Note to my self: ``echo "$var" | sed 's/pattern/replace/g' ``is old school, see e.g. https://twitter.com/nixcraft/status/559309442995351553 .

**Comment by seccubus** [comment]
I just means that you have to do an

Out ")"

Iso the : so the output is correctly formatted if there is a cn mismatch.

**Comment by drwetter** [comment]
That has been done. Seems either @dcooper16 or you fixed that.

Thx
