### ISSUE TITLE
[BUG] Incorrectly showing TLS 1.0 and 1.1 as offered

### ISSUE THREAD

**Issue by mrworf** [drwetter/testssl.sh#2500]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version 3.2rc3 from https://testssl.sh/dev/

**Before you open an issue please whether this is a known problem by searching the issues**
couldn't find anything 

**Command line / docker command to reproduce**
(see separate email)

**Expected behavior**
It shows TLS 1.0 and 1.1 as offered, which isn't correct. Running `openssl s_client -connect a.host.com:443 -tls1` produced the following output:
```
CONNECTED(00000003)
139660948477248:error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available:../ssl/statem/statem_clnt.c:1112:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
and the connection is dropped. The openssl command also returns non-zero. The 2nd line shows that no TLS 1.0 is available. 

If I rerun with `-debug` I see that the server responded as if you sent a HTTP request to an HTTPS server
```
0000 - 48 54 54 50 2f 31 2e 31-20 34 30 30 20 42 61 64   HTTP/1.1 400 Bad
0010 - 20 52 65 71 75 65 73 74-0d 0a 53 65 72 76 65 72    Request..Server
0020 - 3a 20 61 77 73 65 6c 62-2f 32 2e 30 0d 0a 44 61   : awselb/2.0..Da
0030 - 74 65 3a 20 54 75 65 2c-20 30 34 20 4a 75 6e 20   te: Tue, 04 Jun
0040 - 32 30 32 34 20 31 39 3a-31 32 3a 33 33 20 47 4d   2024 19:12:33 GM
0050 - 54 0d 0a 43 6f 6e 74 65-6e 74 2d 54 79 70 65 3a   T..Content-Type:
0060 - 20 74 65 78 74 2f 68 74-6d 6c 0d 0a 43 6f 6e 74    text/html..Cont
0070 - 65 6e 74 2d 4c 65 6e 67-74 68 3a 20 31 32 32 0d   ent-Length: 122.
0080 - 0a 43 6f 6e 6e 65 63 74-69 6f 6e 3a 20 63 6c 6f   .Connection: clo
0090 - 73 65 0d 0a 0d 0a 3c 68-74 6d 6c 3e 0d 0a 3c 68   se....<html>..<h
00a0 - 65 61 64 3e 3c 74 69 74-6c 65 3e 34 30 30 20 42   ead><title>400 B
00b0 - 61 64 20 52 65 71 75 65-73 74 3c 2f 74 69 74 6c   ad Request</titl
00c0 - 65 3e 3c 2f 68 65 61 64-3e 0d 0a 3c 62 6f 64 79   e></head>..<body
00d0 - 3e 0d 0a 3c 63 65 6e 74-65 72 3e 3c 68 31 3e 34   >..<center><h1>4
00e0 - 30 30 20 42 61 64 20 52-65 71 75 65 73 74 3c 2f   00 Bad Request</
00f0 - 68 31 3e 3c 2f 63 65 6e-74 65 72 3e 0d 0a 3c 2f   h1></center>..</
0100 - 62 6f 64 79 3e 0d 0a 3c-2f 68 74 6d 6c 3e 0d 0a   body>..</html>..
```

**Your system (please complete the following information):**
 - OS: `Ubuntu 20.04 LTS`
 - Platform: `Linux 5.10.102.1-microsoft-standard-WSL2 x86_64` 
 - OpenSSL: `OpenSSL 1.1.1f  31 Mar 2020`

**Additional context**

**Comment by dcooper16** [comment]
Hello @mrworf,

I believe that testssl.sh is correct here. My guess is that the second line of the response you are getting to `openssl s_client -connect a.host.com:443 -tls1` is indicating that the OpenSSL client you are using does not support TLS 1.0. Note that that error occurs when trying to construct a ClientHello.

I would suggest trying the following:
```
openssl s_client -connect a.host.com:443 -tls1 -cipher ALL:@SECLEVEL=0
```
This _should_ enable TLS 1.0.

The output from `--debug` seems correct. HTTPS is HTTP over SSL. The request is a HTTP request, it is just being sent over TLS.

**Comment by mrworf** [comment]
Fair enough, I did try with your parameters, and then it will handshake 1.0 and 1.1 (I wish OpenSSL was a bit more clear on who isn't doing TLS 1.0/1.1)
