### ISSUE TITLE
determine_trust continues even when openssl is too old

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#252]
if [[ $OSSL_VER_MAJOR.$OSSL_VER_MINOR == "1.1.0" ]]; then
          pr_litemagentaln "Your $OPENSSL is too new, needed is version 1.0.2"
          return 7
     elif [[ $OSSL_VER_MAJOR.$OSSL_VER_MINOR != "1.0.2" ]]; then
          pr_litemagentaln "Your $OPENSSL is too old, needed is version >=1.0.2"
     fi

Is a return 7 missing here?

**Comment by seccubus** [comment]
Also logic for old new seems to depend on current openssl version

**Comment by drwetter** [comment]
> Also logic for old new seems to depend on current openssl version

That I do not understand. FYI: in openssl_age() there are more checks / filters. 

WRT to "return 7":  I haven't done field tests for lower versions. I know that it works for some, it does not for others -- depends on the system.  So the reason behind this was for 1.1.0 to not do this test as I know it does not work (needs another check though as that was months ago). For 1.0.2 it does, for all others the test is being done but there's a warning.

In any case people are supposed to use the openssl version from github or openssl -- which hopefully is the case for >=80%. For others: testssl.sh is trying it's best and spit out a warning if s.th. is shaky or so.

Hope that explained it?

Cheers, Dirk

**Comment by seccubus** [comment]
Thanks I've added an addtl_warning to test results if version 1.0.2 is used.

With 'Also logic for old new seems to depend on current openssl version'

I mean that this test only seems to think version 1.0.2. is too old and version 1.1.0 is ok, but doesn't seem to warn or fail for other (older) versions.
