### ISSUE TITLE
[BUG / possible BUG] Chain of trust issue for Apple and Java OSes for certificates signed by emSign 

### ISSUE THREAD

**Issue by kansal15** [drwetter/testssl.sh#2525]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**

testssl.sh       3.2rc3 from https://testssl.sh/dev/

**Before you open an issue please whether this is a known problem by searching the issues**

testssl.sh output for the domains, which are signed by emSign CA (https://crt.sh/?caid=96590 and https://crt.sh/?caid=96925) are marked as 'Chain Invalid' for Apple and Java store

``Chain of trust               NOT ok: Apple (chain incomplete) Java (chain incomplete)``
``                                     OK: Mozilla Microsoft Linux ``

For example, for the domain - '**epramaan.meripehchaan.gov.in**' , testssl.sh is showing chain of trust issues whereas server is sending the proper chain. We can cross check from here also - https://www.ssllabs.com/ssltest/analyze.html?d=epramaan.meripehchaan.gov.in

**Command line / docker command to reproduce**

./testssl.sh epramaan.meripehchaan.gov.in
./testssl.sh dla.gov.in

**Expected behavior**

As per information available on crt.sh portal, emSign CA  (https://crt.sh/?caid=96590 and https://crt.sh/?caid=96925) , is trusted for Server Authentication across nearly all the OSes, so the certificate issued by emSign should not be marked as "chain trust issue" if it is providing proper chain. 

**Your system (please complete the following information):**
 - OS: ``awk -F\" '/PRETTY_NAME/ { print $2 }' /etc/os-release``
 Rocky Linux 9.3 (Blue Onyx)
 - Platform: ``uname -srm`` 
 Linux 5.14.0-362.24.1.el9_3.x86_64 x86_64
 - OpenSSL: ``testssl.sh -b 2>/dev/null | grep Using '``
 Using "OpenSSL 1.0.2-bad (1.0.2k-dev)" [~179 ciphers]
 - Bash: ``bash --version``
 GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)

**Comment by kansal15** [comment]
emSign root CA (emSign Root CA - G1 and emSign ECC Root CA - G3 ) is available in the Apple root store. Link - https://support.apple.com/en-us/103100

emSign root CA was added in the root store on Feb 08, 2022 through this commit - https://github.com/apple-oss-distributions/security_certificates/commit/0d0b4b0f6a4e01ebee50d1a84ab8d12535e76f75 

Update list of current root CAs in Apple trust store is available here -- https://github.com/apple-oss-distributions/security_certificates/tree/main/certificates/roots

**Comment by drwetter** [comment]
Hi,

thanks for the PR! I believe though you addressed only half of the problem as the Java Store wasn't updated. testssl.sh will still complain 

Then: It's probably better I'll try next week to update all the stores as the last update seem to be 9 months ago and check again those domains.

Stay tuned.

**Comment by kansal15** [comment]
@drwetter I deliberately add only Apple store in first PR. I was thinking to send separate PR for Java store. Please let me know your thoughts.

Regards,
Gaurav Kansal

**Comment by drwetter** [comment]
my thoughts see above. ;-)

**Comment by drwetter** [comment]
Thanks for your bug report. It has been fixed now.
