### ISSUE TITLE
testssl 3.2: Are local addresses deliberately filtered?

### ISSUE THREAD

**Issue by dueringa** [drwetter/testssl.sh#2529]
With testssl 3.2, the function `get_aaaa_record`  reads for e.g. dig

```
ip6=$(filter_ip6_address $(dig +search $DIG_R +short +timeout=2 +tries=2 $noidnout -t aaaa "$1" 2>/dev/null | awk '/^[0-9]/ { print $1 }'))
```

Regarding the `awk '/^[0-9]/ { print $1 }'`  part: Are ULA addresses deliberately filtered here?

My current use case is testing a DN42 host with a self-signed certificate. DN42 uses addresses in the fd00::/8 range.

**Which version are you referring to**
Github release "Release version 3.2rc3"

**Comment by drwetter** [comment]
> Are ULA addresses deliberately filtered here

no. It's a bug. Thanks for pointing out, @dueringa !

**Comment by drwetter** [comment]
Pls update and try again. Should be fixed. If not, pls speak up
