### ISSUE TITLE
Doesn't work on TLS 1.2 intolerant servers

### ISSUE THREAD

**Issue by lainegholson** [drwetter/testssl.sh#253]
Some b0rken servers don't accept connections using TLS 1.2, testssl.sh should test for this and downgrade appropriately. Instead, testssl.sh returns errors for many of the tests.

**Comment by drwetter** [comment]
?

**Comment by drwetter** [comment]
@lainegholson, I need an example here, pls. Could you provide one?

**Comment by lainegholson** [comment]
I can't really provide an example, because it was one of the servers on my local network, but configuring CUPS with a SHA-384 certificate might work (it did for me).
[testssl.sh on a TLS 1.2 intolerant server](https://github.com/drwetter/testssl.sh/files/72882/no-tls1-2.txt)

**Comment by drwetter** [comment]
Laine, thx. But I can't spot any error in your output -- except the cipher order.

Here the connect in line 1663  probably fails for some reason. The ciphers DES-CBC3-SHA AES128-SHA  AES256 are in $list_fwd. Can you debug this? 

Why is the section 'Testing all 181 locally available ciphers against the server' empty. Did you cut it or wasn't there any output?

Cheers, Dirk

PS: My cups servers show no such behavior. TLS 1.2 is enabled but for the problems I see that doesn't matter

**Comment by lainegholson** [comment]
There wasn't output because the my server failed the connections using TLS 1.2, and the server certificate needs to be SHA-384 (not SHA-1 or SHA-256), and maybe it needs to be on Ubuntu Trusty.

**Comment by lainegholson** [comment]
no longer relevant
