### ISSUE TITLE
Feature: CRLs and OCSP checks for revoked certificates [WIP]

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#254]
The CRL routine checks if CRL paths are provided, but not if the CRLs can actually be downloaded, can be parsed, are signed with the correct key and are actually valid.

**Comment by seccubus** [comment]
Same goes for the OCSP URL.

**Comment by drwetter** [comment]
Of course that would be great and check this. 

But....  :-) why I don't feel tempted to: testssl.sh needs to phone outside to the URL. That is a) sometimes not wanted b) sometimes not possible because of network restrictions.. c) Last but not least CRLs are quite huge.

What I think could be possible IF the user provides a cmdline switch like --revocation-check THEN testssl.sh can try to check the OCSP for revocation. IIRC I started ~2 years ago working on it.

For CRL it's more difficult as one needs to dl the stuff, curl or wget is another dependency. Maybe sockets are better.  In any case also the proxy cmd line option of testssl.sh needs to be honored.. 

It has low priority IMO.

**Comment by barf** [comment]
bump and +1 for this feature plz.

can be observed using openssl:
`openssl s_client -connect example.com:443 -tls1 -tlsextdebug -status`

"OCSP response" and "OCSP Response Data" sections should be found if server supports OCSP, validity checking is another matter of course... IMHO checking validity should be up to the tester, not everyone uses commercial/third party signatories anyway

**Comment by drwetter** [comment]
> "OCSP response" and "OCSP Response Data" sections should be found if server supports OCSP, 

nope. ``--status`` checks for OCSP stapling response, see ``s_client(1)`` and this **is** being checked. (you can compare the results e.g. from testssl.{sh,net}).

What needs to be done is as @seccubus suggested is to dl the CRL and to query the OCSP URL(s) if the certificate has been revoked. As for dl I am not tempted to use curl or wget I just committed a HTTPS get handler. POST needs to be done then as I guess not every issuer supports GET. Proxy support is missing too and later the high level stuff (permission flag to check with issuer and the check itself)

**Comment by dcooper16** [comment]
I haven't done much testing on it, but it may not be necessary to use curl, wget, an HTTP GET handler.

For OCSP responses, just provide the URI from the AIA extension to `$OPENSSL`
```
       -url responder_url
           specify the responder URL. Both HTTP and HTTPS (SSL/TLS) URLs can be specified.
```
There is already some code in `parse_tls_serverhelllo()` that is close to what is needed:
```
          if [[ -n "$hostcert_issuer" ]]; then
               $OPENSSL ocsp -no_nonce -CAfile $TEMPDIR/intermediatecerts.pem -issuer $hostcert_issuer -cert $HOSTCERT -respin $ocsp_response -resp_text >> $TMPFILE 2>$ERRFILE
               rm "$hostcert_issuer"
          else
               $OPENSSL ocsp -respin $ocsp_response -resp_text >> $TMPFILE 2>$ERRFILE
          fi
```
If `$hostcert_issuer` is not present (i.e., if the server only provided the end-entity certificate and no intermediate certificates), then nothing can be done. But, if the certificate belonging to the issuer of the issuer of the end-entity certificate was provided, then it _should_ be possible to do something similar to the first call, just replacing `-respin $ocsp_response` with `-url <url>`. The following seems to work, but would need more testing:
```
$OPENSSL ocsp -no_nonce -CAfile "$bundle_fname" -issuer $hostcert_issuer -cert $HOSTCERT -verify_other $TEMPDIR/intermediatecerts.pem -url <OCSP URI>  >> $TMPFILE 2>$ERRFILE
```
It would just be necessary to extract the first certificate from `$TEMPDIR/intermediatecerts.pem` into `$hostcert_issuer`.

For CRLs, there is the `-crl-download` option:
```
 Changes between 1.0.1l and 1.0.2 [22 Jan 2015
  *) New option -crl_download in several openssl utilities to download CRLs
     from CRLDP extension in certificates.
     [Steve Henson]
```
The `-crl_download` option is available for both `$OPENSSL verify` and `$OPENSSL s_client`. Unfortunately, when I tried it I seemed to frequently get an "Error loading CRL from ..." message, even though I was able to fetch the CRL using wget. But, I don't know whether I'm doing something wrong or its a problem with OpenSSL.

**Comment by drwetter** [comment]
For OCSP: thank for the heads up. And it might save also work for writing and parsing HTTP POST requests.

For CRL: Not sure as we loose compatibility. 

Cheers, Dirk

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by drwetter** [comment]
Would be great to have in in next release, privacyscore.org could also use it. 

There needs to be a a cmd line flag which allows to phone outside. ``-crl_download`` is good for modern OpenSSL but there needs to be later a fallback by using the ``http_get()`` https://github.com/drwetter/testssl.sh/commit/3a21097cc5278ae258a3e790d110babc972c5073 and maybe to-be-implemented ``http_post()``

LibreSSL support needs to be clarified too for ``-crl_download``

**Comment by drwetter** [comment]
As the help function and the commit log says: One needs to use supply an additional cmd line switch ``--phone-out`` -- this is for privacy reasons and avoid network connectivity problems.

Last but not least the CRL files can (still) be huge. During my testing  I encountered e.g. a file size of 3 MB.

**Comment by drwetter** [comment]
see referenced PRs and #1078. Expect 1-2 commits for fine tuning, but we can consider this solved
