### ISSUE TITLE
[Feature request] - missing dependencies

### ISSUE THREAD

**Issue by GChuf** [drwetter/testssl.sh#2541]
**Which version are you referring to**

3.2

**Describe your feature request (if it's a technical feature)**
In the case of some packages not installed on the system (im using ubuntu minimal server install), testssl.sh outputs errors like these:
```
Fatal error: You need to install hexdump for this program to work
Fatal error: Neither "dig", "host", "drill" nor "nslookup" is present
```

**Describe the solution you'd like**
Offer the user to install the necessary packages, or output how they can install it themselves.
Solutions for ubuntu:
```
sudo apt-get install bsdmainutils
sudo apt-get install dnsutils
```

**Comment by drwetter** [comment]
Sorry, we expect users to know how to add binaries to their system. Besides testssl.sh runs on a variety of platforms with different packet managers.
