### ISSUE TITLE
[BUG / possible BUG] typo in openssl-iana.mapping.html : "ECDHE-ECDSA-CAMELLIA256-SHA38" -> "ECDHE-ECDSA-CAMELLIA256-SHA384"

### ISSUE THREAD

**Issue by msakamoto-sf** [drwetter/testssl.sh#2542]
I found `ECDHE-ECDSA-CAMELLIA256-SHA38` in openssl-iana.mapping.html at branch 3.2, line 362:

https://github.com/drwetter/testssl.sh/blob/3.2/openssl-iana.mapping.html#L362C28-L362C45

```
<tr><td> [0xc073]</td><td> ECDHE-ECDSA-CAMELLIA256-SHA38   </td>(...)
```

This openssl name should be `ECDHE-ECDSA-CAMELLIA256-SHA384`. (char "4" is lack at the end)

for example, openssl 1.1.1k:

```
$ openssl ciphers -V -stdname "ALL:eNULL"
(...)
0xC0,0x73 - TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 - ECDHE-ECDSA-CAMELLIA256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=Camellia(256) Mac=SHA384
(...)
```

**Comment by drwetter** [comment]
Thanks!

**Comment by msakamoto-sf** [comment]
@drwetter Thank you very much !
