### ISSUE TITLE
[BUG / possible BUG]

### ISSUE THREAD

**Issue by Docslims-Su** [drwetter/testssl.sh#2543]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**

I am running version ( ``git log | head -1`` if running from the git repo. Otherwise ``testssl.sh -v | grep from``)

**Before you open an issue please whether this is a known problem by searching the issues**

Is related to / couldn't find anything 

**Command line / docker command to reproduce**

Which was your command line? In addition the target of your scan would be helpful. If you don't want to disclose it publicly: ``grep SWCONTACT testssl.sh``.

**Expected behavior**

A clear and concise description of what you would expect to happen.

**Your system (please complete the following information):**
 - OS: ``awk -F\" '/PRETTY_NAME/ { print $2 }' /etc/os-release``
 - Platform: ``uname -srm`` 
 - OpenSSL: ``testssl.sh -b 2>/dev/null | grep Using '``
 - Bash: ``bash --version``

**Additional context**

Add any other context about the problem goes here.

**Comment by drwetter** [comment]
?
