### ISSUE TITLE
Incorrect error message when crl cannot be parsed

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#255]
If CRL info doesn not contain any liens containing 'http' the followign error is returned

          pr_litemagentaln "no parsable output \"$url\", pls report"

I suspect this line should read

          pr_litemagentaln "no parsable output \"$crl\", pls report"

**Comment by drwetter** [comment]
Oh yes. Thx

**Comment by drwetter** [comment]
This is also done. Thx for reporting.
