### ISSUE TITLE
Error message not printed when sec_client-Renego answer is odd

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#256]
See:

               case $sec_client_renego in
                    0) pr_litered "VULNERABLE (NOT ok)"; outln ", DoS threat" ;;
                    1) pr_litegreenln "not vulnerable (OK)" ;;
                    *) "FIXME (bug): $sec_client_renego" ;;
               esac

A pr_litered statement is missing in front of FIXME

**Comment by drwetter** [comment]
thx, @seccubus
