### ISSUE TITLE
[BUG / possible BUG]  the JSON output of testssl.sh does not print "likely not offered"

### ISSUE THREAD

**Issue by meghakoundal** [drwetter/testssl.sh#2575]
We see in the result checker files tlsv1.0 flagged as likely, about tls1.1 and/or sslv3 I have no information. When i have a look at the testssl.sh report I see sslv3 - tls1.1 as likely not offered.
While they do print "likely not offered" in the tool output, they do not write this in the json output.
 
![image(2)](https://github.com/user-attachments/assets/8e413634-bced-4f67-88bd-bf31a24efc9b)

**Comment by drwetter** [comment]
Thanks for reporting. Yes, that needs to be fixed. 

If I read that correctly this (return value 4) happens only when a  STARTTLS problem is passed back. That maybe helpful to add a comment to all four appearances as "likely" sounds it deserves an explanation.

Mind a PR for those two (plus two) cases?
