### ISSUE TITLE
[BUG / possible BUG] : Docker hexdump is missing

### ISSUE THREAD

**Issue by maxhamon** [drwetter/testssl.sh#2586]
Hello,

I am using the latest Docker image from Dockerhub, and I encountered an issue where hexdump seems to be missing.

```bash
$ docker run --rm -ti drwetter/testssl.sh:latest google.com
Fatal error: You need to install hexdump for this program to work

$ docker run --rm -ti --entrypoint sh  drwetter/testssl.sh:latest                         
sh-4.4$ ls -l /usr/bin/hexdump
ls: cannot access '/usr/bin/hexdump': No such file or directory
```

However, using the 3.0 tag works as expected. After reviewing the Dockerfile, I believe that the symlink for hexdump should be placed in `/rootfs` rather than `/usr/bin`

**Comment by jpoggi** [comment]
I,

I'm facing the same issue.

Regards.

**Comment by drwetter** [comment]
sorry, I broke that yesterday. @maxhamon : mind a PR?

**Comment by drwetter** [comment]
nevermind... PR coming

**Comment by drwetter** [comment]
Thanks for reporting, fixed
