### ISSUE TITLE
Obsoleted CBC ciphers

### ISSUE THREAD

**Issue by miro-igov** [drwetter/testssl.sh#2606]
**Which version are you referring to**
3.0.x or 3.2? (please check also how old your version is compare to the ones here)
3.2rc3

Hello, testssl.sh reports 
Obsoleted CBC ciphers (AES, ARIA etc.)            offered
but i do not see any cipher with CBC in the name.
Ciphers below:
`TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA DHE-RSA-AES256-GCM-SHA384
                              ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-RSA-CHACHA20-POLY1305 DHE-RSA-CHACHA20-POLY1305 ECDHE-ECDSA-AES256-CCM8 ECDHE-ECDSA-AES256-CCM DHE-RSA-AES256-CCM8 DHE-RSA-AES256-CCM
                              DHE-RSA-AES256-SHA256 DHE-RSA-ARIA256-GCM-SHA384 ECDHE-ECDSA-ARIA256-GCM-SHA384 ECDHE-ARIA256-GCM-SHA384 TLS_AES_128_GCM_SHA256 ECDHE-RSA-AES128-GCM-SHA256
                              ECDHE-ECDSA-AES128-GCM-SHA256 DHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES128-CCM8 ECDHE-ECDSA-AES128-CCM DHE-RSA-AES128-CCM8 DHE-RSA-AES128-CCM DHE-RSA-ARIA128-GCM-SHA256
                              ECDHE-ECDSA-ARIA128-GCM-SHA256 ECDHE-ARIA128-GCM-SHA256`

Which one is the obsoleted CBC?

It would be good marking the weak ciphers in red so people can easy identify and disable them.

**Comment by drwetter** [comment]
That is an overview section. We don´t add ciphers there

You can either use --color=3 or use your terminal search function (iterm2, konsole, ..) or or open your eyes ;-) or write to a file and grep for it.

![image](https://github.com/user-attachments/assets/7ba6ef92-0a57-42fb-b943-f48e1dfea47b)

This is from KDEs konsole the output of scanning a broken server.

Cheers!

**Comment by miro-igov** [comment]
You must open your eyes. In first post i wrote waht ciphers returned by server. Nowhere a CBC is displayed.
Work on your attitude!
So the problem again:
testssl.sh 3.2 says the tested server supports Obsoleted ciphers. CBC no where in the returned ciphers list. Which one is the obsoleted?
Would be good marking bad ciphers in red for easy spotting.

**Comment by drwetter** [comment]
Hi,

sorry but you filed an incomplete bug report (or whatsoever -- the template was not really filled out) with one statement of output from testssl.sh and some ciphers which appear not in this format in the output. Please don't expect me to exfiltrate the rfc names from this list above and guess the remainder from the output. If you work on your reporting and don't give me the impression that you want to  get full services at the same time, we'll be happy to look into it. Thanks!
