### ISSUE TITLE
line 652: syntax error near unexpected token `else'

### ISSUE THREAD

**Issue by noahdain** [drwetter/testssl.sh#261]
in current master, there is only a comment as the body of an if statement (my bash does not like this).  Adding a ':' fixes it (true).
"""
sed -e '651s/# Ok/:/' testssl.sh
"""
$ bash --version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)

**Comment by drwetter** [comment]
Am 22. Dezember 2015 20:40:24 MEZ, schrieb noahdain <notifications@github.com>:
>in current master, there is only a comment as the body of an if
>statement (my bash does not like this)  Adding a ':' fixes it (true)
>"""
>sed -e '651s/# Ok/:/' testsslsh
>"""
>$ bash --version
>GNU bash, version 412(1)-release (x86_64-redhat-linux-gnu)

Thx for the hint. I fixed that yesterday. Pls do a pull.

Cheers, Dirk


-- 
Sent from my mobile
