### ISSUE TITLE
Color function maker

### ISSUE THREAD

**Issue by szepeviktor** [drwetter/testssl.sh#27]
```bash
# color = number of stars + ANSI escape code
declare -A COLORS=( [litegreen]='0\033[0;32m' [green]='2\033[1;32m' )

colorfuncmaker() {
    local COLOR_NAME
    local -i COLOR_STAR_NUM
    local COLOR_STARS=""
    local COLOR_CODE

    for COLOR_NAME in ${!COLORS[*]}; do
        COLOR_STAR_NUM="${COLORS[$COLOR_NAME]:0:1}"
        COLOR_CODE="${COLORS[$COLOR_NAME]:1}"

        if [ "$COLOR" == 0 ]; then
            # colored function
            eval "${COLOR_NAME}() { out \"${COLOR_CODE}\$1 \"; off; }"
        else
            # b/w function
            # generate stars
            if [ "$COLOR_STAR_NUM" -gt 0 ]; then
                printf -v COLOR_STARS '*%.0s' $(seq 1 ${COLORS[$COLOR_NAME]:0:1})
            fi
            eval "${COLOR_NAME}() { out \"${COLOR_STARS}\$1${COLOR_STARS} \"; }"
        fi
        # the common ...ln function
        eval "${COLOR_NAME}ln() { ${COLOR_NAME} \"\$1\"; outln; }"
    done
}
```

It makes testssl.sh smaller.

**Comment by drwetter** [comment]
@szepeviktor : Sorry for keeping this open for some long. 

Would you mind doing a PR?

**Comment by szepeviktor** [comment]
I am sorry. I'd like to contribute only one function.
This one generates all these: https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L256-L348
So your code gets shorter.

**Comment by szepeviktor** [comment]
> generates all these function

Should I explain what this means?

**Comment by drwetter** [comment]
Ok, no problem.

Like the idea though, so I reopened it for others to volunteer.

**Comment by szepeviktor** [comment]
The PR is easy. You just delete the literally defined function and but this one in your code.

**Comment by szepeviktor** [comment]
Then you call this one several times:
`declare -A COLORS=( [litegreen]='0\033[0;32m' [green]='2\033[0;32m' )`

**Comment by szepeviktor** [comment]
> removed the stars also from my code

So start should also be removed from this function.

**Comment by drwetter** [comment]
Am 07/23/2015 um 01:50 PM schrieb Viktor Szépe:
>     generates all these function
> 
> Should I explain what this means?

I got it, not sure whether the generated functions are kind of global then.
I assume they are, otherwise you wouldn't have suggested it.

**Comment by szepeviktor** [comment]
If they are not global, just make this function simply inline code.

**Comment by drwetter** [comment]
Thx!

**Comment by drwetter** [comment]
Needed to revert this.

Catch was the functions are being initiated at a fixed time instead of while calling.

Other solution needs to be found for this color_maker

**Comment by szepeviktor** [comment]
OK
