### ISSUE TITLE
@MAC users: using internal printf ok?

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#271]
I would need help: can somebody change all occurrences of ``/usr/bin/printf`` to just ``printf`` and test whether all still works?

Internal printf should be faster (and it's cleaner to use it) but I am not sure bash3 eats everything served this way.

Thx! Dirk

**Comment by kraigu** [comment]
```
$ uname -mrsv
Darwin 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
$ diff testssl.sh testssl-origprintf.sh 
304c304
< out()   { printf -- "${1//%/%%}"; }
---
> out()   { /usr/bin/printf -- "${1//%/%%}"; }
466c466
<      #printf -- "%d" 0x"$1"
---
>      #/usr/bin/printf -- "%d" 0x"$1"
471c471
<      printf -- "%x" "$1"
---
>      /usr/bin/printf -- "%x" "$1"
$ 
```
Tested against a public webserver. It *works*, but \c is inserted into various spots, eg:

` Null Ciphers                 \cnot offered (OK)\c`

**Comment by kraigu** [comment]
I forgot to add, that was a pull from master. If I should have tried a different branch, let me know, it's simple enough to retry.

**Comment by drwetter** [comment]
@kraigu, thx.

master was fine. "\c" is strange, understand what is means but not why bash3 prints it out....

The second printf: is only relevant at one place (try e.g. ``./testssl.sh --debug=4 -p <target>`` and look for the right dec2hex conversion for ``tls_sid_len``).

**Comment by drwetter** [comment]
@kraigu or any other with MacOSX: could you just do a pull and run it again?

**Comment by drwetter** [comment]
Am 24. Januar 2016 15:43:14 MEZ, schrieb Mike <notifications@github.com>:
>OK, pulled master and ran it as-is, looks good.


-- 
Sent from my mobile

**Comment by kraigu** [comment]
Your reply to my previous comment appears to be content-free, in case you were expecting that it wasn't. :)

**Comment by drwetter** [comment]
Am 24. Januar 2016 16:05:49 MEZ, schrieb Mike <notifications@github.com>:
>Your reply to my previous comment appears to be content-free, in case
>you were expecting that it wasn't. :) 

Oh, thx for the hint. :-)

What I probably erased was saying thx and that I am glad I got rid of all external printfs. 

Cheers, Dirk 




-- 
Sent from my mobile

**Comment by kraigu** [comment]
Haha, I figured it was something like that. Just wanted to make sure that weren't trying to ask me to try something else/new. :)
