### ISSUE TITLE
Lines shipped when using --file option

### ISSUE THREAD

**Issue by erwanlr** [drwetter/testssl.sh#273]
When using the --file option, if a target doesn't have a SSL/TLS server, the next target will be skipped.

Example:

Create a file containing
```
www.github.com:80
www.google.com
www.github.com
```

and run ```./testssl.sh --file path_to_the_file``` which will not scan www.google.com

![testssl-error](https://cloud.githubusercontent.com/assets/1668843/12579292/32fa2b5c-c427-11e5-8033-0205e073e970.png)

**Comment by drwetter** [comment]
Can reproduce it. Thx for reporting!

**Comment by erwanlr** [comment]
:+1:
