### ISSUE TITLE
smtp protocol violation

### ISSUE THREAD

**Issue by grinapo** [drwetter/testssl.sh#274]
Unfortunately you oversimplified a bit SMTP since you 
1) do not wait for server hello before firing EHLO, and
2) do not wait for response before starting STARTTLS,
bothe resulting SMTP protocol violations.

Waiting doesn't seem to resolve the problem but I didn't have the time to fully debug the protocol exchange (probably would require a bit of stracing since debug mode doesn't seem to echo all protocol traffic with timestamps).

**Comment by drwetter** [comment]
Pls read the code :-)

I am doing simplifications -- in the first round. That's a matter of speed and works ~9x%. It does not work for some exim servers in a certain configuration (not the default one, one which enforces the correctness of handshakes, can't remember the setting).

If that simplification fails however there'll be autoimagically another, proper round of handshakes in starttls_line(). You can enforce this in the first place by setting ``FAST_STARTTLS=false testssl.sh -t smtp <cmdline>``.

If there's still a problem, it would be great if you could give me an example.

**Comment by chrcoluk** [comment]
yeah you breaking SMTP protocol and hence I get the same issue, but at least you added a way to disable it.

**Comment by drwetter** [comment]
> yeah you breaking SMTP protocol and hence I get the same issue, but at least you added a way 
> to disable it.

That didn't help me. Does the automatic second round work or not (i.e. only ``FAST_STARTTLS=false`` works). If the latter is the case please file a proper report so th

**Comment by chrcoluk** [comment]
FAST_STARTTLS=false is what works yes.

**Comment by drwetter** [comment]
Ok, getting closer.

You have an example (IP) for me which I can test?

**Comment by grinapo** [comment]
There seem to be difference from the last time I've checked, since now protocol fallback actually works. (As a sidenote I have read the code and tried to force it but it's not simple to reverse engineer in 5 minutes. :-))

Right now it seems to handle the strict protocol servers well (without FAST_STARTTLS=false).

**Comment by drwetter** [comment]
Ok. Let me (here) know if you stumble over it again, I would reopen this. Details would be appreciated then. :)

**Comment by chrcoluk** [comment]
For me I still need to use the flag on the live git code (not release 2.6)

However the error is broken pipe.

output with --debug 2

 Testing protocols (via openssl, SSLv2 via sockets) 

 SSLv2      
=== sending "EHLO testssl.sh" ...

=== sending "STARTTLS" ...
cat: stdin: Connection reset by peer
... received result: 

=== sending with automated FAST_STARTTLS=false "STARTTLS" ...
./testssl.sh: line 308: printf: write error: Broken pipe
./testssl.sh: line 308: printf: write error: Broken pipe
./testssl.sh: line 308: printf: write error: Broken pipe
./testssl.sh: line 308: printf: write error: Broken pipe
./testssl.sh: line 308: printf: write error: Broken pipe
./testssl.sh: line 308: printf: write error: Broken pipe

If I add FAST_STARTTLS=false manually it works.

If you want to test on my mail server try mail.chrysalisnet.org

I got a feeling the issue might be with my client box tho, if relevant its FreeBSD 9.3.

**Comment by drwetter** [comment]
Thx @chrcoluk . Can reproduce that.

**Comment by drwetter** [comment]
Do you have an IDS in place or a feature of your SMTP server? Looks I can connect a couple of times, then not anymore. Also it looks like s.th. is rate limiting requests. ``./bin/openssl.FreeBSD.amd64 s_client -state -tls1 -starttls smtp -connect mail.chrysalisnet.org:25`` times out. Actually I don't see any SSL/TLS protocols supported which is twofold weird. First: configuration wise I doubt that but maybe you can check? Secondly: I see later successful handshakes (3DES, HIGH)

PS: The borken pipe I also spotted once on Debian 8. Connecting to another server with FreeBSD 9.3. worked fine for me.

**Comment by chrcoluk** [comment]
No IDS but there is a log watcher which will ban when certian patterns seen in logs, although it didnt ban me before when I did testing. I will disable it for a while and you can resume testing, just in case that did ban you.

**Comment by drwetter** [comment]
bear with me a few days pls

**Comment by chrcoluk** [comment]
you still need to run tests against my server?

**Comment by chrcoluk** [comment]
good news,, I found the cause what was making fast starttls fail.

Exim has a setting which enforces sync of commands to strict RFC complaince.

The setting is 'smtp_enforce_sync' and it defaults to true.
There is a pipelining setting which defaults to enabled, that loosens the sync requirements, but it doesnt disable unless 'smtp_enforce_sync' is set to false.

Glad I got to the bottom of this.

**Comment by seccubus** [comment]
@drwetter I believe this can be closed. Agree?

**Comment by drwetter** [comment]
The issue / report was kind of sparse, but it seems to me too. 

@chrcoluk: Is there still an issue?
