### ISSUE TITLE
Multiple certificate check does not show SHA-1 certificate

### ISSUE THREAD

**Issue by prdonahue** [drwetter/testssl.sh#276]
Here's how to get our SHA-1:

    $ openssl s_client -connect www.cloudflare.com:443 -tls1_1 </dev/null 2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm"
    Signature Algorithm: sha1WithRSAEncryption
    Signature Algorithm: sha1WithRSAEncryption

And here's what the script shows:

    Server Certifcate #1
    Server key size              2048 bit
    Signature Algorithm          SHA256 with RSA
    Fingerprint / Serial         SHA1 A27166492178CC73EDF2D171D87D5BA1484DFFF8 / E3BB289893780DEAB01913B0A1400D77
                                SHA256 996F1E3DB7354AE92CC98CE12E473A8D01FFFD3E52F39AC514FEAFA6156AA499
    Common Name (CN)             (no CN field in subject) (CN in response to request w/o SNI: "no CN field in subject")
    subjectAltName (SAN)         "cloudflare.com" "www.cloudflare.com" 
    Issuer                       "COMODO RSA Extended Validation Secure Server CA" ("COMODO CA Limited" from "GB")
    EV cert (experimental)       yes 
    Certificate Expiration       304 >= 60 days (2015-11-30 16:00 --> 2016-11-30 15:59 -0800)
    # of certificates provided   3
    Chain of trust (experim.)    "/etc/*.pem" cannot be found / not readable
    Certificate Revocation List  http://crl.comodoca.com/COMODORSAExtendedValidationSecureServerCA.crl
    OCSP URI                     http://ocsp.comodoca.com
    OCSP stapling                offered

    Server Certifcate #2
    Server key size              EC 256 bit
    Signature Algorithm          ECDSA with SHA256
    Fingerprint / Serial         SHA1 F6F6A4ABEDE20AFC147BEAFD1FAFC9304902EA49 / 066CB625C622BE29CA69425208A1AD28
                                SHA256 E5554E6A21828B6F17546C2B77227F37003C7A092693BEB394BEEFF80A735880
    Common Name (CN)             (no CN field in subject) (CN in response to request w/o SNI: "no CN field in subject")
    subjectAltName (SAN)         "cloudflare.com" "www.cloudflare.com" 
    Issuer                       "COMODO ECC Extended Validation Secure Server CA" ("COMODO CA Limited" from "GB")
    EV cert (experimental)       yes 
    Certificate Expiration       304 >= 60 days (2015-11-30 16:00 --> 2016-11-30 15:59 -0800)
    # of certificates provided   3
    Chain of trust (experim.)    "/etc/*.pem" cannot be found / not readable
    Certificate Revocation List  http://crl.comodoca.com/COMODOECCExtendedValidationSecureServerCA.crl
    OCSP URI                     http://ocsp.comodoca.com
    OCSP stapling                offered

**Comment by drwetter** [comment]
Thx for reporting.

@dcooper16 :  do you have an idea what's the problem could be?

**Comment by dcooper16** [comment]
I believe I see why this is happening. I did a bit of testing, a my results were consistent with prdonahue's comment.  www.cloudflare.com returns the SHA-1 certificate if s_client specifies "-tls1_1", but it returns the SHA-256 certificate if s_client specifies "-tls1_2 -cipher aRSA" (it returns the ECC certificate if s_cilent specifies "-tls1_2" without specifying a cipher).

My PR didn't change the behaviour of determine_tls_extensions in that it tries tls1_2, tls1_1, tls1, and ssl3 in succession and stops as soon as one works. So, since the TLS v1.2 connection attempt works, there is no attempt to connect using TLS v1.1.

I'll try modifying run_server_defaults so that it tries different protocols in addition to different sets of cipher suites. It will slow things down, but it might not be that much slower than the current code.

**Comment by dcooper16** [comment]
I tried adding another loop to run_server_defaults so that it tries each protocol (tls1_2, tls1_1, tls1, ssl3) separately, but that didn't solve the problem in this case. While www.cloudflare.com returns the SHA-1 certificate in response to:

    openssl s_client -cipher aRSA -connect www.cloudflare.com:443 -tls1_1

it returns the SHA-256 certificate in response to:

    openssl s_client -cipher aRSA -connect www.cloudflare.com:443 -tls1_1 -servername www.cloudflare.com

The SHA-1 certificate only seems to appear if the protocol is not TLS v1.2 and the server name indication extension is not sent. The result is that adding another loop to run_server_defaults will show all of the certificates for www.cloudflare.com if the URI provided at the command line is an IP address (e.g., 198.41.215.162), but the SHA-1 certificate still doesn't show up if the URI is the DNS name (www.cloudflare.com).

I created yet another version of the code that not only tries each protocol, but tries each with and without SNI, and this works. If you want to try it, it is available at https://github.com/dcooper16/testssl.sh/blob/check_all_protocols_with_and_without_SNI/testssl.sh. This code isn't ready for adoption yet, as I didn't make any changes to the code in certificate_info that tries connecting to the server without SNI and prints the results. At the moment, I can't think of a good way to display the results in a useful manner.

**Comment by prdonahue** [comment]
Correct, @dcooper16, we have some logic that basically says "if the user agent presents SNI then _at worse_ show SHA-2 RSA".

**Comment by drwetter** [comment]
Ok, @prdonahue. but that doesn't count then :-) doesn't it?

It seems only due to the vhost setting that the request without SNI ends up probably on the same host.

``openssl s_client   -connect testssl.sh:443   2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm"`` gives ``ecdsa-with-SHA256``, whereas 

``openssl s_client  -connect testssl.sh:443 -servername testssl.sh  2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm"`` returns ``sha256WithRSAEncryption``.

**Comment by drwetter** [comment]
sorry @prdonahue, wanted to wait until you're fine with that.

**Comment by drwetter** [comment]
For testing I added a line in testssl.sh which also tells the sig algo per cipher:

```
---------------------------------------------------------------------------------------------
 Start 2016-02-01 20:32:34    -->> 198.41.215.162:443 (cloudflare.com) <<--

 further IP addresses:   198.41.214.162 2400:cb00:2048:1::c629:d6a2 2400:cb00:2048:1::c629:d7a2
 rDNS (198.41.215.162):   --
 Service detected:       HTTP

 Testing all locally available ciphers per protocol against the server, ordered by encryption strength 

Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits
-------------------------------------------------------------------------
SSLv2 
SSLv3 
TLS 1 
 xc014   ECDHE-RSA-AES256-SHA           ECDH 256   AES        256              sha256WithRSAEncryption
 x35     AES256-SHA                     RSA        AES        256              sha256WithRSAEncryption
 xc013   ECDHE-RSA-AES128-SHA           ECDH 256   AES        128              sha256WithRSAEncryption
 x2f     AES128-SHA                     RSA        AES        128              sha256WithRSAEncryption
 xc012   ECDHE-RSA-DES-CBC3-SHA         ECDH 256   3DES       168              sha256WithRSAEncryption
 x0a     DES-CBC3-SHA                   RSA        3DES       168              sha256WithRSAEncryption
TLS 1.1 
 xc014   ECDHE-RSA-AES256-SHA           ECDH 256   AES        256              sha256WithRSAEncryption
 x35     AES256-SHA                     RSA        AES        256              sha256WithRSAEncryption
 xc013   ECDHE-RSA-AES128-SHA           ECDH 256   AES        128              sha256WithRSAEncryption
 x2f     AES128-SHA                     RSA        AES        128              sha256WithRSAEncryption
 xc012   ECDHE-RSA-DES-CBC3-SHA         ECDH 256   3DES       168              sha256WithRSAEncryption
 x0a     DES-CBC3-SHA                   RSA        3DES       168              sha256WithRSAEncryption
TLS 1.2 
 xcc14   ECDHE-ECDSA-CHACHA20-POLY1305  ECDH 256   ChaCha20   256              ecdsa-with-SHA256
 xcc13   ECDHE-RSA-CHACHA20-POLY1305    ECDH 256   ChaCha20   256              sha256WithRSAEncryption
 xc030   ECDHE-RSA-AES256-GCM-SHA384    ECDH 256   AESGCM     256              sha256WithRSAEncryption
 xc02c   ECDHE-ECDSA-AES256-GCM-SHA384  ECDH 256   AESGCM     256              ecdsa-with-SHA256
 xc028   ECDHE-RSA-AES256-SHA384        ECDH 256   AES        256              sha256WithRSAEncryption
 xc024   ECDHE-ECDSA-AES256-SHA384      ECDH 256   AES        256              ecdsa-with-SHA256
 xc014   ECDHE-RSA-AES256-SHA           ECDH 256   AES        256              sha256WithRSAEncryption
 x9d     AES256-GCM-SHA384              RSA        AESGCM     256              sha256WithRSAEncryption
 x3d     AES256-SHA256                  RSA        AES        256              sha256WithRSAEncryption
 x35     AES256-SHA                     RSA        AES        256              sha256WithRSAEncryption
 xc02f   ECDHE-RSA-AES128-GCM-SHA256    ECDH 256   AESGCM     128              sha256WithRSAEncryption
 xc02b   ECDHE-ECDSA-AES128-GCM-SHA256  ECDH 256   AESGCM     128              ecdsa-with-SHA256
 xc027   ECDHE-RSA-AES128-SHA256        ECDH 256   AES        128              sha256WithRSAEncryption
 xc023   ECDHE-ECDSA-AES128-SHA256      ECDH 256   AES        128              ecdsa-with-SHA256
 xc013   ECDHE-RSA-AES128-SHA           ECDH 256   AES        128              sha256WithRSAEncryption
 x9c     AES128-GCM-SHA256              RSA        AESGCM     128              sha256WithRSAEncryption
 x3c     AES128-SHA256                  RSA        AES        128              sha256WithRSAEncryption
 x2f     AES128-SHA                     RSA        AES        128              sha256WithRSAEncryption
 xc012   ECDHE-RSA-DES-CBC3-SHA         ECDH 256   3DES       168              sha256WithRSAEncryption
 x0a     DES-CBC3-SHA                   RSA        3DES       168              sha256WithRSAEncryption

 Done 2016-02-01 20:33:26    -->> 198.41.215.162:443 (cloudflare.com) <<--

----------------------------------------------------------------------------------------------



```

So in this case testssl.sh has done everything correctly.

**Comment by prdonahue** [comment]
> It seems only due to the vhost setting that the request without SNI ends up probably on the same host.
> 
> openssl s_client -connect testssl.sh:443 2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm" gives ecdsa-with-SHA256, whereas
> 
> openssl s_client -connect testssl.sh:443 -servername testssl.sh 2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm" returns sha256WithRSAEncryption.

No, this is how we operate; it serves the appropriate certificate regardless of whether SNI was used due to the IP configuration. It's a bit confusing without a broader overview, so let me explain:

**Free zones**
Free customers require the use of SNI. When they sign up, we throw their SANs (example.com and *.example.com) on an existing SHA-2 ECDSA certificate that's used by other free customers. Here's an example for you to test:

    $ DOMAIN=isgoodellfiredyet.com && openssl s_client -connect www.$DOMAIN:443 -servername www.$DOMAIN </dev/null 2>/dev/null | openssl x509 -text -noout | grep -oP "DNS:*.$DOMAIN|Signature Algorithm:.*"
    Signature Algorithm: ecdsa-with-SHA256
    DNS:isgoodellfiredyet.com
    Signature Algorithm: ecdsa-with-SHA256

And without SNI, free customers get an error, because we don't bind their certificate to the IP:

    $ DOMAIN=isgoodellfiredyet.com && openssl s_client -connect www.$DOMAIN:443  </dev/null 2>/dev/null | openssl x509 -text -noout | ggrep -oP "DNS:*.$DOMAIN|Signature Algorithm:.*"
    unable to load certificate

Free customers only get one type of certificate, so regardless of the CH parameters, they'll always be served this SHA-2 ECDSA (even if we suspect the user agent can't validate/use it).

**Pro ($20/mo) zones**
Paid customers (Pro/Business/Enterprise) on the other hand get served a certificate _regardless of whether SNI is in the ClientHello or not_. When a Pro customer signs up, we place their SANs (example.com, *.example.com) on three separate certificates that differ by signature algorithm: SHA-2 ECDSA, SHA-2 RSA, and SHA-1 RSA. These certificates then get bound to IP addresses where they will be returned with or without SNI. Note that Pro customers also currently share certificates with other Pro customers, but this is most likely changing soon to be more like Business and Enterprise.

Rather than duplicate examples here for Pro, I've shown below for Business. The "inducement" logic should be the same.

**Business ($200/mo) and Enterprise zones**
Like all paid zones, Business zones will have their certificates returned regardless of whether SNI is presented. The difference from Pro, however, is that these certificates are "dedicated" in the sense that no other customers SANs will be on there. Here's how to induce all the certificates:

**TLS 1.2 with SNI**
$ DOMAIN=nantucketairlines.com && openssl s_client -connect www.$DOMAIN:443 -servername www.$DOMAIN  </dev/null 2>/dev/null | openssl x509 -text -noout | ggrep -oP "DNS:*.$DOMAIN|Signature Algorithm:.*"
Signature Algorithm: ecdsa-with-SHA256
DNS:nantucketairlines.com
Signature Algorithm: ecdsa-with-SHA256

**TLS 1.2 without SNI**
$ DOMAIN=nantucketairlines.com && openssl s_client -connect www.$DOMAIN:443  </dev/null 2>/dev/null | openssl x509 -text -noout | ggrep -oP "DNS:*.$DOMAIN|Signature Algorithm:.*"
Signature Algorithm: ecdsa-with-SHA256
DNS:nantucketairlines.com
Signature Algorithm: ecdsa-with-SHA256

**TLS 1.2 where sigalgs contains only RSA+SHA256 (i.e., no ECDSA+SHA256)**:
    $ DOMAIN=nantucketairlines.com && openssl s_client -connect www.$DOMAIN:443 -tls1_2 -sigalgs RSA+SHA256 </dev/null 2>/dev/null | openssl x509 -text -noout | ggrep -oP "DNS:*.$DOMAIN|Signature Algorithm:.*"
Signature Algorithm: sha256WithRSAEncryption
DNS:nantucketairlines.com
Signature Algorithm: sha256WithRSAEncryption

**TLS 1.1 without SNI**:
DOMAIN=nantucketairlines.com && openssl s_client -connect www.$DOMAIN:443 -tls1_1 </dev/null 2>/dev/null | openssl x509 -text -noout | ggrep -oP "DNS:*.$DOMAIN|Signature Algorithm:.*"
Signature Algorithm: sha1WithRSAEncryption
DNS:nantucketairlines.com
Signature Algorithm: sha1WithRSAEncryption

**TLS 1.1 with SNI**:
$ DOMAIN=nantucketairlines.com && openssl s_client -connect www.$DOMAIN:443 -tls1_1 -servername www.$DOMAIN </dev/null 2>/dev/null | openssl x509 -text -noout | ggrep -oP "DNS:*.$DOMAIN|Signature Algorithm:.*"
Signature Algorithm: sha256WithRSAEncryption
DNS:nantucketairlines.com
Signature Algorithm: sha256WithRSAEncryption

I believe this last case is that one that tripped up your code. The reason that we serve SHA-2 here rather than SHA-1 has to do with the timeline of SNI vs. TLS 1.0 and 1.1 implementations. Here's a (hopefully) helpful series of events:

1. TLS 1.0 published January 1999 in RFC 2246 (https://www.ietf.org/rfc/rfc2246.txt).
2. SHA-2 published in 2001 by NIST.
3. SNI published in June 2003  as part of the TLS extensions RFC (https://www.ietf.org/rfc/rfc3546.txt).
4. TLS 1.1 published in April 2006 in RFC 4346 (https://www.ietf.org/rfc/rfc4346.txt).

As you can see, SNI came to market a couple years after SHA-2. In our extensive research, we were unable to find any platforms that supported SNI _but not_ SHA-2 with the exception of Chromium on Windows XP (pre SP3) between versions M06 when they used Microsoft's SChannel and M39 when they switched to NSS. (They of course later switched to BoringSSL, but that's irrelevant to this discussion). In fact, several TLS stacks - OpenSSL excluded - didn't bother adding SNI until they updated for TLS 1.1 sometime after 2006. Thus, we are confident that when a client sends us SNI, it can support SHA-2.

**Comment by drwetter** [comment]
Am 02/01/2016 um 07:25 PM schrieb dcooper16:

> The SHA-1 certificate only seems to appear if the protocol is not TLS v1.2 and the server name
> indication extension is not sent. The result is that adding another loop to run_server_defaults
> will show all of the certificates for www.cloudflare.com <http://www.cloudflare.com> if the URI
> provided at the command line is an IP address (e.g., 198.41.215.162), but the SHA-1 certificate
> still doesn't show up if the URI is the DNS name (www.cloudflare.com <http://www.cloudflare.com>).
> 
> I created yet another version of the code that not only tries each protocol, but tries each
> with and without SNI, and this works. If you want to try it, it is available at
> https://github.com/dcooper16/testssl.sh/blob/check_all_protocols_with_and_without_SNI/testssl.sh.
> This code isn't ready for adoption yet, as I didn't make any changes to the code in
> certificate_info that tries connecting to the server without SNI and prints the results. At the
> moment, I can't think of a good way to display the results in a useful manner.

That's secondary and we/I could figure out.

I need again look @ @prdonahue's mail but right now I am hestitant to check hosts
not specified, see SNI.

If I run the script from check_all_protocols_with_and_without_SNI on testssl.sh I see as
expected the
default host.

Cheers, Dirk

**Comment by drwetter** [comment]
Hi guys,

Just brainstorming. What would be the best in your opinion:

a) do an exception for cloudflare as a bigger player (test additionally tls_1.1 and non-SNI)
b) seeking for a broader solution (test more than a)

I am tending more towards a). It's cleaner, doesn't cost much additional time. I can't tell however what else is out there in the internet. 

Cheers, Dirk

**Comment by drwetter** [comment]
Hi @prdonahue / @dcooper16,

anything which speaks against another check tls_1.1 + non-SNI and parse the CN/.DNS field of the extension of that certificate. If it matches then we have another certificate? 

Cheers, Dirk

**Comment by dcooper16** [comment]
Hi @prdonahue ,

I was testing some code that I wrote for testssh.sh, and I encountered some odd results when testing the code against www.cloudflare.com. In particular, some attempts to connect using "openssl s_client" were failing when it seemed that they should have succeeded.

Is there an email address where I can send you more information about what I found?

Thanks,

Dave

**Comment by dcooper16** [comment]
Hi Dirk,

Do you have any thoughts on how you want to present the results in this case? At the moment, the client connects without SNI, the common name in the certificate obtained without SNI is compared to the common name in the certificate obtained with SNI, and then the results are displayed:

   Common Name (CN)             (no CN field in subject) (works w/o SNI)

   Common Name (CN)             "testssl.sh" (CN in response to request w/o SNI: "default.name")

   Common Name (CN)             "www.google.com" (works w/o SNI)

In the case of testssl.sh, it is clear that a different certificate is returned, but no information about the certificate is displayed other than the common name. In the other two cases, there's no information to indicate whether it is the same or a different certificate.

I think it would be easier for me to have a suggestion for what information the client should try to collect if I knew what the client was going to do with it (i.e., how will the information be displayed).

Thanks,

Dave

**Comment by prdonahue** [comment]
> Is there an email address where I can send you more information about what I found?

Sure, feel free to email me at [pat@cloudflare.com](mailto:pat@cloudflare.com).

**Comment by drwetter** [comment]
Hey Dave,

Am 03/23/2016 um 10:02 PM schrieb David Cooper:
> Hi Dirk,
> 
> Do you have any thoughts on how you want to present the results in this case? 
> At the moment, the client connects without SNI, the common name in the certificate
> obtained without SNI is compared to the common name in the certificate obtained
> with SNI, and then the results are displayed:
> 
> Common Name (CN) (no CN field in subject) (works w/o SNI)
> 
> Common Name (CN) "testssl.sh" (CN in response to request w/o SNI: "default.name")
> 
> Common Name (CN) "www.google.com" (works w/o SNI)
> 
> In the case of testssl.sh, it is clear that a different certificate is returned, but no information about the certificate is displayed other than the common name. 

If another vhost via non-SNI is being hit AND the CN is different, I guess it's enough just to
tell it like it would be done with testssl.sh (2)

In the case of this default vhost at testssl.sh's IPv4 address: it's completely differently configured.
Here a different scan would be needed anyway. Displaying the whole non-SNI certificate only wouldn't help that much
IMO and clog the output.

I like the idea that a tool is smart and does a lot of its tasks automagically but it shouldn't display
or even scan more than it was instructed to do. Example: ssllabs was(?) scanning often
www.<suppliedhostname>, also if it hit another host/IP.

> In the other two cases, there's no information to indicate whether it is the same or a different certificate.
> I think it would be easier for me to have a suggestion for what information the client should try to collect if I knew what the client was going to do with it (i.e., how will the information be displayed).

1) and 3) are basically the same (trailing part) -- except that 1) has the DNS information in the X509 v3 extensions
as SANs and the CN field is empty.

For cloudflare and friends -- hosts with multiple certificates sharing the same CN/DNS
SAN -- there's a proper output already, done by you. :) My idea would be just to
do another run with e.g. tls 1.1 + non-SNI, check whether the CN/DNS SAN matches and
if so display it completely as another certificate -- as it belongs the one host.

Or what else would you like to add here?


> Thanks,

Well, thank you Dave (and for the other great sounding PR from today!)

Cheers, Dirk

PS: There's still open issue to check CN and extensions against the hostname
(see #94). That will extend the check with ~another line. So a bit that
will change anyway.

**Comment by drwetter** [comment]
@dcooper16: just had a quick look here: wouldn't a single additional request with TLS 1.1 without SNI" help here?

I would love to get this off the table for 2.8

**Comment by dcooper16** [comment]
I started writing this code to add one additional request with TLSv1.1 without SNI and setting "-cipher" to "ALL:COMPLEMENTOFALL". However, I just discovered that that may not be enough. I seems to work in the case of www.cloudflare.com, but not for www.facebook.com. As shown below, www.facebook.com has two SHA-1 certificates, one RSA and one ECC, that are used with TLSv1.1 without SNI but not TLSv1.2 with SNI. If I just do one additional request with TLSv1.1 without SNI and setting "-cipher" to "ALL:COMPLEMENTOFALL" the SHA-1 ECC certificate is shown, but the SHA-1 RSA certificate is missed.

So, I can either make the code Cloudflare/Facebook specific and add two additional requests, one for RSA and one for ECC, or I can make it a bit more generic by adding seven additional requests, one for each public key type.

David

```
 Testing server defaults (Server Hello) 

 TLS extensions (standard)    "server name/#0" "renegotiation info/#65281" "EC point formats/#11" "session ticket/#35" "next protocol/#13172"
 Session Tickets RFC 5077     172800 seconds (PFS requires session ticket keys to be rotated <= daily)
 SSL Session ID support       yes
 TLS clock skew               random values, no fingerprinting possible 

  Server Certificate #1
   Signature Algorithm          SHA256 with RSA
   Server key size              2048 bits
   Fingerprint / Serial         SHA1 E95D7C0DF3E8F205A9B5A4570CDD20B8752784B1 / 0AE89D732FC11CC2833AECDF94CEE5D7                                                                                      
                                SHA256 A3F474FB17509AE6C5B6BA5E46B79E0DE6AF1BF1EEAA040A6114676E714C9965                                                                                               
   Common Name (CN)             "*.facebook.com" (wildcard certificate match) (works w/o SNI)                                                                                                         
   Server Name Indication (SNI) yes                                                                                                                                                                   
   subjectAltName (SAN)         "*.facebook.com" "facebook.com" "*.facebook.net" "*.fb.com" "*.fbcdn.net" "*.fbsbx.com" "*.m.facebook.com" "*.messenger.com" "*.xx.fbcdn.net" "*.xy.                  fbcdn.net" "*.xz.fbcdn.net" "fb.com" "messenger.com"                                                                                                                                                  
   Issuer                       "DigiCert SHA2 High Assurance Server CA" ("DigiCert Inc" from "US")                                                                                                   
   EV cert (experimental)       no                                                                                                                                                                    
   Certificate Expiration       365 >= 60 days (2016-02-29 19:00 --> 2017-06-01 08:00 -0400)                                                                                                          
   # of certificates provided   2                                                                                                                                                                     
   Chain of trust (experim.)    Ok                                                                                                                                                                    
   Certificate Revocation List  http://crl3.digicert.com/sha2-ha-server-g5.crl                                                                                                                        
   OCSP URI                     http://ocsp.digicert.com                                                                                                                                              
   OCSP stapling                --                                                                                                                                                                    
                                                                                                                                                                                                      
  Server Certificate #2                                                                                                                                                                               
   Signature Algorithm          SHA1 with RSA
   Server key size              2048 bits
   Fingerprint / Serial         SHA1 BB99476A7204F92CE2A573EDFF12C437A1C8EA54 / 0E743E11AAED3DB037E1556F286C3FE1
                                SHA256 8B96BA027E494077406D82C364E0DD2A9ECDE91625515B4E37D40F704869BEDE
   Common Name (CN)             "*.facebook.com" (wildcard certificate match) (works w/o SNI)
   Server Name Indication (SNI) no
   subjectAltName (SAN)         "*.facebook.com" "*.facebook.net" "*.fb.com" "*.fbcdn.net" "*.fbsbx.com" "*.m.facebook.com" "*.messenger.com" "*.xx.fbcdn.net" "*.xy.fbcdn.net" "*.xz.fbcdn.net" "facebook.com" "fb.com" "messenger.com" 
   Issuer                       "DigiCert High Assurance CA-3" ("DigiCert Inc" from "US")
   EV cert (experimental)       no 
   Certificate Expiration       212 >= 60 days (2015-04-09 20:00 --> 2016-12-30 07:00 -0500)
   # of certificates provided   2
   Chain of trust (experim.)    Ok   
   Certificate Revocation List  http://crl3.digicert.com/ca3-g29.crl
   OCSP URI                     http://ocsp.digicert.com
   OCSP stapling                --

  Server Certificate #3
   Signature Algorithm          SHA256 with RSA
   Server key size              256 bits
   Fingerprint / Serial         SHA1 A04EAFB348C26B15A8C1AA87A333CAA3CDEEC9C9 / 0ECB0939B2B10154B89570C7B22B7A47
                                SHA256 A626B154CC65634181250B810B1BD4C89EC277CEA08D785EEBE7E768BDA7BB00
   Common Name (CN)             "*.facebook.com" (wildcard certificate match) (works w/o SNI)
   Server Name Indication (SNI) yes
   subjectAltName (SAN)         "*.facebook.com" "*.facebook.net" "*.fb.com" "*.fbcdn.net" "*.fbsbx.com" "*.m.facebook.com" "*.messenger.com" "*.xx.fbcdn.net" "*.xy.fbcdn.net" "*.xz.fbcdn.net" "facebook.com" "fb.com" "messenger.com" 
   Issuer                       "DigiCert SHA2 High Assurance Server CA" ("DigiCert Inc" from "US")
   EV cert (experimental)       no 
   Certificate Expiration       212 >= 60 days (2014-08-27 20:00 --> 2016-12-30 07:00 -0500)
   # of certificates provided   2
   Chain of trust (experim.)    Ok   
   Certificate Revocation List  http://crl3.digicert.com/sha2-ha-server-g5.crl
   OCSP URI                     http://ocsp.digicert.com
   OCSP stapling                --

  Server Certificate #4
   Signature Algorithm          SHA1 with RSA
   Server key size              256 bits
   Fingerprint / Serial         SHA1 867CB2939487878A6E4DB25236AC92AA76F09DE3 / 08E4634BCB04FFBD670676D93BF06486
                                SHA256 0F99393D5318AED848B7287E5AACFE797CC5C571FFDFF88CB0B8D60B304D978F
   Common Name (CN)             "*.facebook.com" (wildcard certificate match) (works w/o SNI)
   Server Name Indication (SNI) no
   subjectAltName (SAN)         "*.facebook.com" "*.facebook.net" "*.fb.com" "*.fbcdn.net" "*.fbsbx.com" "*.m.facebook.com" "*.messenger.com" "*.xx.fbcdn.net" "*.xy.fbcdn.net" "*.xz.fbcdn.net" "facebook.com" "fb.com" "messenger.com" 
   Issuer                       "DigiCert High Assurance CA-3" ("DigiCert Inc" from "US")
   EV cert (experimental)       no 
   Certificate Expiration       212 >= 60 days (2014-08-27 20:00 --> 2016-12-30 07:00 -0500)
   # of certificates provided   2
   Chain of trust (experim.)    Ok   
   Certificate Revocation List  http://crl3.digicert.com/ca3-g29.crl
   OCSP URI                     http://ocsp.digicert.com
   OCSP stapling                --
```

**Comment by drwetter** [comment]
Closing via #371 . Thx also @prdonahue
