### ISSUE TITLE
Chain of trust.. list and directory of CA

### ISSUE THREAD

**Issue by Niko78** [drwetter/testssl.sh#287]
Hi,
I tried the dev one of testssl
chain of trust did not work, it search in ./etc/*pem 
why ? I changed it by /etc/ssl/certs/, now it works but the issue is that you display all list of CA present instead of just displai OK with the right one

example : 
 Chain of trust (experim.)    NOT ok: ACCVRAIZ1 (chain incomplete) ACEDICOM_Root (chain incomplete) AC_Raíz_Certicámara_S.A. (chain incomplete) Actalis_Authentication_Root_CA (chain incomplete) AddTrust_Low-Value_Services_Root (chain incomplete) AddTrust_Public_Services_Root (chain incomplete) AddTrust_Qualified_Certificates_Root (chain incomplete) AffirmTrust_Commercial (chain incomplete) AffirmTrust_Networking (chain incomplete) AffirmTrust_Premium_ECC (chain incomplete) AffirmTrust_Premium (chain incomplete) America_Online_Root_Certification_Authority_1 (chain incomplete) America_Online_Root_Certification_Authority_2 (chain incomplete) ApplicationCA_-_Japanese_Government (chain incomplete) Atos_TrustedRoot_2011 (chain incomplete) A-Trust-nQual-03 (chain incomplete) Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068 (chain incomplete) Baltimore_CyberTrust_Root (chain incomplete) Buypass_Class_2_CA_1 (chain incomplete) Buypass_Class_2_Root_CA (chain incomplete) Buypass_Class_3_CA_1 (chain incomplete) Buypass_Class_3_Root_CA (chain incomplete) CA_Disig (chain incomplete) CA_Disig_Root_R1 (chain incomplete) CA_Disig_Root_R2 (chain incomplete) Camerfirma_Chambers_of_Commerce_Root (chain incomplete) Camerfirma_Global_Chambersign_Root (chain incomplete) Certigna (chain incomplete) Certinomis_-_Autorité_Racine (chain incomplete) Certplus_Class_2_Primary_CA (chain incomplete) certSIGN_ROOT_CA (chain incomplete) Certum_Root_CA (chain incomplete) Certum_Trusted_Network_CA (chain incomplete) Chambers_of_Commerce_Root_-_2008 (chain incomplete) China_Internet_Network_Information_Center_EV_Certificates_Root (chain incomplete) CNNIC_ROOT (chain incomplete) Comodo_AAA_Services_root (chain incomplete) COMODO_Certification_Authority (chain incomplete) COMODO_ECC_Certification_Authority (chain incomplete) Comodo_Secure_Services_root (chain incomplete) Comodo_Trusted_Services_root (chain incomplete) ComSign_CA (chain incomplete) ComSign_Secured_CA (chain incomplete) Cybertrust_Global_Root (chain incomplete) Deutsche_Telekom_Root_CA_2 (chain incomplete) DigiCert_Assured_ID_Root_CA (chain incomplete) DigiCert_Assured_ID_Root_G2 (chain incomplete) DigiCert_Assured_ID_Root_G3 (chain incomplete) DigiCert_Global_Root_CA (chain incomplete) DigiCert_Global_Root_G2 (chain incomplete) DigiCert_Global_Root_G3 (chain incomplete) DigiCert_High_Assurance_EV_Root_CA (chain incomplete) DigiCert_Trusted_Root_G4 (chain incomplete) Digital_Signature_Trust_Co._Global_CA_1 (chain incomplete) Digital_Signature_Trust_Co._Global_CA_3 (chain incomplete) DST_ACES_CA_X6 (chain incomplete) DST_Root_CA_X3 (chain incomplete) D-TRUST_Root_Class_3_CA_2_2009 (chain incomplete) D-TRUST_Root_Class_3_CA_2_EV_2009 (chain incomplete) EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı (chain incomplete) EC-ACC (chain incomplete) EE_Certification_Centre_Root_CA (chain incomplete) E-Guven_Kok_Elektronik_Sertifika_Hizmet_Saglayicisi (chain incomplete) Entrust.net_Premium_2048_Secure_Server_CA (chain incomplete) Entrust_Root_Certification_Authority (chain incomplete) ePKI_Root_Certification_Authority (chain incomplete) Equifax_Secure_CA (chain incomplete) Equifax_Secure_eBusiness_CA_1 (chain incomplete) Equifax_Secure_Global_eBusiness_CA (chain incomplete) E-Tugra_Certification_Authority (chain incomplete) GeoTrust_Global_CA_2 (chain incomplete) GeoTrust_Global_CA (chain incomplete) GeoTrust_Primary_Certification_Authority_-_G2 (chain incomplete) GeoTrust_Primary_Certification_Authority_-_G3 (chain incomplete) GeoTrust_Primary_Certification_Authority (chain incomplete) GeoTrust_Universal_CA_2 (chain incomplete) GeoTrust_Universal_CA (chain incomplete) Global_Chambersign_Root_-_2008 (chain incomplete) GlobalSign_Root_CA (chain incomplete) GlobalSign_Root_CA_-_R2 (chain incomplete) GlobalSign_Root_CA_-_R3 (chain incomplete) Go_Daddy_Class_2_CA (chain incomplete) Go_Daddy_Root_Certificate_Authority_-_G2 (chain incomplete) GTE_CyberTrust_Global_Root (chain incomplete) Hellenic_Academic_and_Research_Institutions_RootCA_2011 (chain incomplete) Hongkong_Post_Root_CA_1 (chain incomplete) IGC_A (chain incomplete) Izenpe.com (chain incomplete) Juur-SK (chain incomplete) Microsec_e-Szigno_Root_CA_2009 (chain incomplete) Microsec_e-Szigno_Root_CA (chain incomplete) NetLock_Arany_=Class_Gold=_Főtanúsítvány (chain incomplete) NetLock_Business_=Class_B=_Root (chain incomplete) NetLock_Express_=Class_C=_Root (chain incomplete) NetLock_Notary_=Class_A=_Root (chain incomplete) NetLock_Qualified_=Class_QA=_Root (chain incomplete) Network_Solutions_Certificate_Authority (chain incomplete) OISTE_WISeKey_Global_Root_GA_CA (chain incomplete) PSCProcert (chain incomplete) QuoVadis_Root_CA_1_G3 (chain incomplete) QuoVadis_Root_CA_2_G3 (chain incomplete) QuoVadis_Root_CA_2 (chain incomplete) QuoVadis_Root_CA_3_G3 (chain incomplete) QuoVadis_Root_CA_3 (chain incomplete) QuoVadis_Root_CA (chain incomplete) Root_CA_Generalitat_Valenciana (chain incomplete) RSA_Security_2048_v3 (chain incomplete) Secure_Global_CA (chain incomplete) SecureSign_RootCA11 (chain incomplete) SecureTrust_CA (chain incomplete) Security_Communication_EV_RootCA1 (chain incomplete) Security_Communication_RootCA2 (chain incomplete) Security_Communication_Root_CA (chain incomplete) SG_TRUST_SERVICES_RACINE (chain incomplete) Sonera_Class_1_Root_CA (chain incomplete) Sonera_Class_2_Root_CA (chain incomplete) spi-cacert-2008 (chain incomplete) ssl-cert-snakeoil (chain incomplete) Staat_der_Nederlanden_Root_CA_-_G2 (chain incomplete) Staat_der_Nederlanden_Root_CA (chain incomplete) Starfield_Class_2_CA (chain incomplete) Starfield_Root_Certificate_Authority_-_G2 (chain incomplete) Starfield_Services_Root_Certificate_Authority_-_G2 (chain incomplete) StartCom_Certification_Authority_2 (chain incomplete) StartCom_Certification_Authority_G2 (chain incomplete) StartCom_Certification_Authority (chain incomplete) S-TRUST_Authentication_and_Encryption_Root_CA_2005_PN (chain incomplete) Swisscom_Root_CA_1 (chain incomplete) Swisscom_Root_CA_2 (chain incomplete) Swisscom_Root_EV_CA_2 (chain incomplete) SwissSign_Gold_CA_-_G2 (chain incomplete) SwissSign_Platinum_CA_-_G2 (chain incomplete) SwissSign_Silver_CA_-_G2 (chain incomplete) Taiwan_GRCA (chain incomplete) TC_TrustCenter_Class_2_CA_II (chain incomplete) TC_TrustCenter_Class_3_CA_II (chain incomplete) TC_TrustCenter_Universal_CA_I (chain incomplete) TeliaSonera_Root_CA_v1 (chain incomplete) Thawte_Premium_Server_CA (chain incomplete) thawte_Primary_Root_CA_-_G2 (chain incomplete) thawte_Primary_Root_CA_-_G3 (chain incomplete) thawte_Primary_Root_CA (chain incomplete) Thawte_Server_CA (chain incomplete) Trustis_FPS_Root_CA (chain incomplete) T-TeleSec_GlobalRoot_Class_2 (chain incomplete) T-TeleSec_GlobalRoot_Class_3 (chain incomplete) TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3 (chain incomplete) TURKTRUST_Certificate_Services_Provider_Root_1 (chain incomplete) TURKTRUST_Certificate_Services_Provider_Root_2007 (chain incomplete) TURKTRUST_Certificate_Services_Provider_Root_2 (chain incomplete) TWCA_Global_Root_CA (chain incomplete) TWCA_Root_Certification_Authority (chain incomplete) UTN_DATACorp_SGC_Root_CA (chain incomplete) UTN_USERFirst_Email_Root_CA (chain incomplete) UTN_USERFirst_Hardware_Root_CA (chain incomplete) Verisign_Class_1_Public_Primary_Certification_Authority_-_G2 (chain incomplete) Verisign_Class_1_Public_Primary_Certification_Authority_-_G3 (chain incomplete) Verisign_Class_1_Public_Primary_Certification_Authority (chain incomplete) Verisign_Class_2_Public_Primary_Certification_Authority_-_G2 (chain incomplete) Verisign_Class_2_Public_Primary_Certification_Authority_-_G3 (chain incomplete) Verisign_Class_3_Public_Primary_Certification_Authority_2 (chain incomplete) Verisign_Class_3_Public_Primary_Certification_Authority_-_G2 (chain incomplete) Verisign_Class_3_Public_Primary_Certification_Authority_-_G3 (chain incomplete) VeriSign_Class_3_Public_Primary_Certification_Authority_-_G4 (chain incomplete) VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5 (chain incomplete) Verisign_Class_3_Public_Primary_Certification_Authority (chain incomplete) Verisign_Class_4_Public_Primary_Certification_Authority_-_G3 (chain incomplete) VeriSign_Universal_Root_Certification_Authority (chain incomplete) Visa_eCommerce_Root (chain incomplete) WellsSecure_Public_Root_Certificate_Authority (chain incomplete) WoSign_China (chain incomplete) WoSign (chain incomplete) XRamp_Global_CA_Root (chain incomplete)
                                OK: AddTrust_External_Root
                                (Your openssl <= 1.0.2 might be too unreliable to determine trust)

+ it start with a NOK then in the end => OK with the right CA

thanks for comments

**Comment by drwetter** [comment]
Hi there,

Am 02/07/2016 um 12:14 PM schrieb Niko78:
> Hi,
> I tried the dev one of testssl
> chain of trust did not work, it search in /etc/*pem
> why ? 

Because this is the place where testssl.sh keeps its certificate stores
for some OS / browsers. testssl.sh is not relying on YOUR or any other INDIVIDUAL'S
certificate store.

> I changed it by /etc/ssl/certs/, now it works but the issue is that you display all list
> of CA present instead of just displai OK with the right one

Well, don't do it.

Maybe best is to check whether you pulled everything? Sounds to me like ./etc/*pem is
missing.


HTH, Dirk

**Comment by Niko78** [comment]
hey Dirk,
thanks for comments
ok I think I understood, so I have to put all CA I use in "/etc/"
it stays an issue, I changed local ca_bundles cause it's not "./etc/" but "/etc"... because testssl script could be in an other folder
Thanks

Niko

**Comment by Niko78** [comment]
hey Dirk,

Ok understood, I created "./etc/" with all pem files inside ans reput "./etc/*.pem" in testssl.sh
So I copied all pem inside
I rechecked my test server but I still get all the list.
sorry I don't understand why we get all the list, is it because you check one per one until you get the right one ? in that case I think there is no interest to display all that are "not ok"
In my corporate we use about 5 different CA, so if I put only these 5, each test will show me 5 not ok and 1 ok ?

thanks

niko

**Comment by drwetter** [comment]
Hey Niko,

Am 02/07/2016 um 12:56 PM schrieb Niko78:
> hey Dirk,
> thanks for comments
> ok I think I understood, so I have to put all CA I use in "/etc/"

no :-)

Here is the store: https://github.com/drwetter/testssl.sh/tree/master/etc

which shows up in ./etc/ (relative to testssl.sh) . A Linux store is
already there as ./etc/linux.pem. Others are mozilla.pem and microsoft.pem.


Cheers, Dirk

**Comment by Niko78** [comment]
ah ok !
great sorry for the noise

niko

**Comment by drwetter** [comment]
> In my corporate we use about 5 different CA, so if I put only these 5, each test will show me 5 
> not ok and 1 ok ?

if you would have one CA in your company it probably would look like attached.
![ca](https://cloud.githubusercontent.com/assets/8036727/12872275/32ef0f8e-cd9f-11e5-9a4c-2040ee447d6e.png)

This will be improved, see #230.

testssl.sh check against any store $CWD/etc/*pem . The ones which fail will be reported.

**Comment by drwetter** [comment]
> great sorry for the noise

no prob
