### ISSUE TITLE
Incorrect domain resolution with localhosts

### ISSUE THREAD

**Issue by andreild** [drwetter/testssl.sh#289]
Hello,

If you have in your /etc/hosts an entry such as "127.0.0.1 www.test.com.local", then when running testssl.sh www.test.com, testssl.ssh will attempt to connect to 127.0.0.1. By contrast, a browser will correctly go to www.test.com, and will only go to 127.0.0.1 when explicitly given www.test.com.local.

testssl.sh should resolve domains "correctly".

This happens because of https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L5718. I'll be submitting a PR shortly for this, but I don't know if my proposed fix is the best one. If not, perhaps someone else can look at this.

Regards,
Andrei

**Comment by teward** [comment]
I do not have a resolution for this, however I can confirm, oddly enough, this issue when using `www.domain.net` when a `www.domain.net.local` entry is in `/etc/hosts`.

This does not appear to happen, however, with the bare domain in the mix - i.e. `dark-net.net` works fine and does not appear to have this issue.

```
% ./testssl.sh www.dark-net.net
...
 Start 2016-02-08 06:32:56    -->> 127.0.1.4:443 (www.dark-net.net) <<--

 further IP addresses:   <snipped, but valid IPv6>
 A record via            /etc/hosts 
 rDNS (127.0.1.4):        --
 Service detected:       HTTP
``````

**Comment by andreild** [comment]
I've created a PR for it. Basically, the grep that parses /etc/hosts correctly accounts for e.g. comments and word boundaries, but doesn't consider that www.test.com.local is an entry distinct from www.test.com, but would still be matched by www.test.com due to the grep -w.

Arguably my fix is ugly, so if anyone has a better option, go for it.

**Comment by drwetter** [comment]
Am 02/08/2016 um 12:58 PM schrieb andreild:
> I've created a PR for it. Basically, the grep that parses /etc/hosts correctly accounts for
> e.g. comments and word boundaries, but doesn't consider that www.test.com.local
> <http://www.test.com.local> is an entry distinct from www.test.com <http://www.test.com>, but
> would still be matched by www.test.com <http://www.test.com> due to the grep -w.
> 
> Arguably my fix is ugly, so if anyone has a better option, go for it.

That would be the option I prefer. :-)

There's a parser for the file option and also is_ipv4addr(). Mybe that helps?

Cheers, Dirk

**Comment by andreild** [comment]
Hello Dirk,

I looked, but wasn't able to find a better place to put the check that there isn't some more stuff, in the hosts file, affixed after the matching regex. I looked at is_ipv4addr() but don't understand it well enough to change it, and I couldn't find the "parser for the file option".

Allow me to suggest, however, that the check belongs in get_local_a(). The issue is not whether it's an IPv4 address per se, but rather what exactly you have in the hosts file. You already parse the hosts file on line 5718, to exclude lines that start with a #, for instance. What I'm doing is adding another check to this same line.

Lastly, if you agree that this issue needs fixing and with my idea (if not its current implementation), you can fix it on your own branch, and then decline this PR. Won't mind.

Regards,
Andrei
