### ISSUE TITLE
Feature Request: Output to CSV/JSON?

### ISSUE THREAD

**Issue by madhuakula** [drwetter/testssl.sh#295]
Hi,

Would it be possible to put in a feature request to have output to csv/json? This would be very useful to make automating checks for websites, quicker and easier. 

Thanks

**Comment by teward** [comment]
Dupe: https://github.com/drwetter/testssl.sh/issues/31

**Comment by madhuakula** [comment]
Thanks for update.

**Comment by drwetter** [comment]
current master has CSV/JSON, see also ``testssl.sh --help``.
