### ISSUE TITLE
getopts for command line parsing

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#3]
currently cmd line parsing is not the greatest thing on earth

**Comment by drwetter** [comment]
Hi Peter,
would you have any time for this in the next couple of weeks? Cheers, Dirk

**Comment by PeterMosmans** [comment]
Dirk, I scheduled it in for the next weeks. Sorry about the delay ;)

**Comment by drwetter** [comment]
no reason to be sorry ;-)

BTW I liked the style of what you did in  test_ssl_handshake.sh

**Comment by PeterMosmans** [comment]
Just a heads-up, currently I'm in the process of refactoring that part (which turns out to be a fair chunk of code)...

**Comment by drwetter** [comment]
cool, take the time you need.

**Comment by PeterMosmans** [comment]
Please see pull request #78

**Comment by drwetter** [comment]
Finally! See c8d169cc0f0779445b2dedfb5c1921daedaf6846

For the record: getopt wasn't portable (GNU on Linux, different on BSD). getopts (bash) has only short options, this would have broken compatibility.

Kudos to Peter, now testssl.sh does that compatible for every OS and doesn't break compatibility..
