### ISSUE TITLE
give recommendantions

### ISSUE THREAD

**Issue by Niko78** [drwetter/testssl.sh#312]
hi,

that would be interesting to get recommendations when something is "NOT OK/VULNERABLE"
kind of piece of apache/etc.. code
remove rc4
fix heartbleed... etc

in clear recommendations to fix issues

thanks

nicolas

**Comment by Niko78** [comment]
instead of recommendations, maybe a link to a website with advice...

**Comment by drwetter** [comment]
HI @Niko78 

This has been discussed before, can't find it momentarily. There was already a suggestion how to to this.

Dirk

**Comment by drwetter** [comment]
see #194
