### ISSUE TITLE
Support client-auth certificates

### ISSUE THREAD

**Issue by teancom** [drwetter/testssl.sh#315]
I have many TLS servers that require a client-auth certificate to even negotiate a connection, and thus is required for scanning. Please add support for passing in client-auth certs, whether in JKS, PEM, or P12 format (i.e., whatever you support I can switch to using).

**Comment by drwetter** [comment]
Am 8. März 2016 22:28:18 MEZ, schrieb David Bishop <notifications@github.com>:
>I have many TLS servers that require a client-auth certificate to even
>negotiate a connection, and thus is required for scanning. Please add
>support for passing in client-auth certs, whether in JKS, PEM, or P12
>format (i.e., whatever you support I can switch to using).


There is support in dev for x509 based authentication already w/o certificates. Which means no application layer info like HTTP header. But that should suffice.

Dirk


-- 
Set from my mobile. Excuse my brevity&typos

**Comment by teancom** [comment]
Sorry, and I'm not trying to be difficult, but what's x509-based authentication if you're not talking about a cert? I've always associated x509 with certs, so I'm somewhat confused.

**Comment by drwetter** [comment]
Am 03/09/2016 um 05:57 AM schrieb David Bishop:
> Sorry, and I'm not trying to be difficult, but what's x509-based authentication if you're not
> talking about a cert? I've always associated x509 with certs, so I'm somewhat confused.

I just used a different term. :-)

Please keep in mind that the possibility for testing servers requiring (x509) certificate-based
authentication came with 2.7dev. It's not in 2.6.

Cheers, Dirk

**Comment by drwetter** [comment]
Closing.

Pls let me know if I got s.th. wrong
