### ISSUE TITLE
Support SNI on mail tests

### ISSUE THREAD

**Issue by chrcoluk** [drwetter/testssl.sh#316]
I am observing SNI seems to be non functional when using -t SMTP.

I see references to SNI in the code but the script is huge so I dont want to try and add the required arguments to the code.

My belief is because when I use the -S on its own just to see the certificate used, its not using the right certificate, yet my email client does use the right certificate.

Please update the script to utilise SNI on smtp and pop tests.

Thanks

**Comment by chrcoluk** [comment]
I can confirm manual testing with the " openssl s_client -starttls smtp -servername " command shows SNI is functional.

**Comment by drwetter** [comment]
SNI is used in HTTP.

For SMTP and SNI there's no such standard.  Preferred is to handle this via MX record. Not speaking about the fact that TLS encryption is a) opportunistic b) often cleints don't do strict certificate checking.

The only thing I know of is wrt to SMTP is TLSA records.

**Comment by drwetter** [comment]
PS: What is POP ;-)

**Comment by chrcoluk** [comment]
There is SNI in dovecot and exim, both very widely used server software.
Outlook, gmail, Thunderbird also all support SNI.

**Comment by drwetter** [comment]
there's no SNI in sendmail or postfix, both widely used server software. So for an exim server it's BS to rely on SNI, unless that exim is sure it won't talk to sendmail or postfix.

**Comment by drwetter** [comment]
@chrcoluk: I would need a detailed use case where testssl.sh currently fails and an explanation.

**Comment by chrcoluk** [comment]
For reference I did disable SNI as I had issues with the android k9 client not supporting it, so now am using one cert per ip, however I still would like the test in place as SNI does exist for email, is on the software I mentioned and will only get more popular as time moves forward.
I have no issue if you disable it by default, but please add a flag thats optional to enable it.

**Comment by afletch** [comment]
@drwetter SNI is now pretty widespread on mail (and even FTP), as services transition quickly to use free Let's Encrypt issued certificates. It would be great to see SNI support for these services in testssl.

**Comment by drwetter** [comment]
If somebody feels doing so and I someone points me to test machines: Ok.

**Comment by drwetter** [comment]
Just looking at the source codes from openssl 1.0.2 and openssl 1.1.1. Seems 1.1.1 has a ``-name`` switch for this? Looks to me like this would be also needed _currently_ for testssl.sh as there's are a few handshaskes left we do without sockets.

If anybody is willing to backport this please send a PR to https://github.com/drwetter/openssl-1.0.2.bad .

**Comment by afletch** [comment]
Exim does SNI
ProFTPd does SNI

**Comment by drwetter** [comment]
I meant a server = FQDN, not a service

**Comment by drwetter** [comment]
In the meantime: Postfix 3.4 has it also (Debian buster). 

Maybe this can be done earlier as in 3.1dev

**Comment by drwetter** [comment]
premature closing it, see PR #1281 pending and issue #1280.
