### ISSUE TITLE
tls 1.2 failing on bundled ssl binary on legacy ssl/tls

### ISSUE THREAD

**Issue by chrcoluk** [drwetter/testssl.sh#319]
So if I use the bundled ssl on smtp port 465 or pop/imap ports 993 995 then it will report tls 1.2 not working and also says there is no PFS ciphers as well on the tests, but I can confirm tls 1.2 is working fine on manual client connections.

If I use the openssl binary already on my server, those tests work fine and report both tls 1.2 and PFS working.

This issue doesn't occur on starttls connections.

**Comment by drwetter** [comment]
Am 03/11/2016 um 03:49 PM schrieb chrcoluk:
> So if I use the bundled ssl on smtp port 465 or pop/imap ports 993 995 then it will report tls 1.2 not working and also says there is no PFS ciphers as well on the tests, but I can confirm tls 1.2 is working fine on manual client connections.
> 
> If I use the openssl binary already on my server, those tests work fine and report both tls 1.2 and PFS working.
> 
> This issue doesn't occur on starttls connections.

Thx but w/o any ip address any but report is pretty much useless.
Please file a proper bug report. Then I reopen this.

Cheers, Dirk

Closed #319

**Comment by chrcoluk** [comment]
Well I think this is an issue with the bundled ssl binary rather than server, but the server been tested mail.chrysalisnet.org.

either SMTP or POP or IMAP will show the same results.

**Comment by drwetter** [comment]
I cannot observer this -- using ``OpenSSL 1.0.2-chacha (1.0.2d-dev)`` from ``built: "Jul  6 18:05:33 2015", platform: "linux-x86_64"``. It hangs however ion POP/IMAP on the cipher ``ECDHE-RSA-CAMELLIA128-SHA256``, not on SMTP.

**Comment by chrcoluk** [comment]
I am using the FreeBSD bundled binary.  FreeBSD 9.3 x64.

**Comment by chrcoluk** [comment]
I discovered the cause of the failure is when chacha cipher is added first in the server cipher preference order, after removing it this failure does not occur.

I hope this info is useful to you.

**Comment by drwetter** [comment]
Am 16. April 2016 06:55:20 MESZ, schrieb chrcoluk <notifications@github.com>:
>I discovered the cause of the failure is when chacha cipher is added
>first in the server cipher preference order, after removing it this
>failure does not occur.
>
>I hope this info is useful to you.

Thx. 
While your finding is appreciated I am not understanding this, nor can I reproduce that. 

Let me publish the new binaries I have and let's see then, ok?


Cheers, Dirk




-- 
Sent from my

**Comment by drwetter** [comment]
hi @chrcoluk,

can you please check out the latest 1.0.2.i-dev binaries from https://testssl.sh/ ?

Cheers, Dirk

**Comment by chrcoluk** [comment]
tomorrow yes, although I prefer to use older binary as that can test the older ciphers which got removed in 1.0.2i

**Comment by teward** [comment]
Erm, correct me if I'm wrong, but don't these custom binaries have the older ciphers back in?  What 'older ciphers' are you referring to?  (If you mean the ECDHE curves being removed, @PeterMosmans reversed that, we use their fork of OpenSSL for the binaries provided here and at testsslsh...)

**Comment by drwetter** [comment]
@teward: you're not wrong. :-) The new binaries add two ciphers and brings back the weak EC curves.

**Comment by teward** [comment]
@drwetter That's what I thought - I'm not sure that's as widely known though with the fork - most people base their assumptions on the base version and not @PeterMosmans 's amazing efforts and work! :)

**Comment by PeterMosmans** [comment]
Thanks for the kind words @teward . However, I rely on bugreports and suggestions to keep 1.0.2-chacha up-to-date and error free. So the fork is *teamwork* @drwetter @teward :smile:

**Comment by drwetter** [comment]
Am 27. Mai 2016 02:30:49 MESZ, schrieb Peter Mosmans <notifications@github.com>:
>Thanks for the kind words @teward . However, I rely on bugreports and
>suggestions to keep 1.0.2-chacha up-to-date and error free. So the fork
>is *teamwork* @drwetter @teward 

It's more. Spirit of open source! 


-- 
Set from my mobile. Excuse my brevity&typos

**Comment by chrcoluk** [comment]
ok thats good to hear, will test within next couple of hours.

**Comment by chrcoluk** [comment]
I pulled the dev code but its still using the 1.0.2e binary

**Comment by chrcoluk** [comment]
/bin/openssl.FreeBSD.amd64 couldn't establish STARTTLS via smtp to 78.46.185.207:465 it actually seems worse now.  As it wont test at all now on port 465 even if chacha is off on the server.  Note it is trying starttls when port 465 uses implicit ssl?

**Comment by drwetter** [comment]
can you please check out the latest 1.0.2.i-dev binaries from https://testssl.sh/ ?

**Comment by chrcoluk** [comment]
I am using those binaries.

Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on apocalypse:./bin/openssl.FreeBSD.amd64

The new failure on implicit ssl might be due to the newer testssl.sh code I pulled from git.  On port 25 with starttls the issue went away.

Right now I am waiting for the OS binary on 465, if that also fails I think its due to the code not the binary.

**Comment by chrcoluk** [comment]
sorry I forgot have to use --ssl-native with implicit ssl, rerunning the tests.

**Comment by chrcoluk** [comment]
works perfect now, sorry for the confusion with the missing native flag. :)

**Comment by chrcoluk** [comment]
just to avoid confusion, the bug report was valid, I was using the native flags on the initial post, is just I forgot to use again on the new binary initially, hope that clears things up if confusion.

**Comment by drwetter** [comment]
Hi @chrcoluk,

it's really hard to tell what the problem is as your description is somewhat confusing.

With the latest master (1.493 2016/06/06 11:42:15) -- I do not care for 2.6 any more -- and openssl 1.0.2i from https://testssl.sh/openssl-1.0.2i-chacha.pm.ipv6.Linux+FreeBSD.tar.gz I got the following results:

FreeBSD 9.3:
./testssl.sh -6 --ip=2a01:4f8:201:5465::2 mail.chrysalisnet.org:465:  WORKS
./testssl.sh --ssl-native -p -6 --ip=2a01:4f8:201:5465::2 mail.chrysalisnet.org:465  WORKS

Debian Linux:
./testssl.sh -6 --ip=2a01:4f8:201:5465::2 mail.chrysalisnet.org:465   WORKS
./testssl.sh --ssl-native -p -6 --ip=2a01:4f8:201:5465::2 mail.chrysalisnet.org:465  WORKS

IPv4 stalls and it looks to me there's fail2ban or the like preventing testing.

If you still encounter an issue I would need the testssl command line, openssl version, platform (uname -a) and the output where it fails and I am happy to reopen this.

Cheers, Dirk
