### ISSUE TITLE
check DV cert

### ISSUE THREAD

**Issue by Niko78** [drwetter/testssl.sh#321]
hi

that would be interesting top check if cert is a DV cert (Domain Validated)
just in checking OU 

openssl x509 -in test.crt -noout -text | grep Subject
 OU=Domain Control Validated

regards

nicolas

**Comment by drwetter** [comment]
Maybe with a minus score.

See e.g. https://raymii.org/s/blog/How_I_got_a_valid_SSL_certificate_for_my_ISPs_main_website.html
