### ISSUE TITLE
apple trusted CA

### ISSUE THREAD

**Issue by Niko78** [drwetter/testssl.sh#322]
hi,

would be interesting to add apple trusted ca in /etc to check if it's ok like others
=> https://support.apple.com/en-us/HT205204
nicolas

**Comment by drwetter** [comment]
ok! anybody can provide the bundle/store?

**Comment by Niko78** [comment]
will try to catch it
but if I read correctly => https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/security.1.html

" find-certificate [-h] [-a] [-c name] [-e emailAddress] [-m] [-p] [-Z] [keychain...]
Find a certificate item.  If no keychain arguments are provided, the default search list is
used."

=> Examples
security> find-certificate -a -p > allcerts.pem
Exports all certificates from all keychains into a pem file called allcerts.pem.

**Comment by drwetter** [comment]
Thx again!
