### ISSUE TITLE
Output for PFS is confusing

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#332]
There seems to be four different modes for printing the results of run_pfs when PFS is offered, depending on whether the --show-each and --wide flags are set.

The output seems okay is the --wide flag is set or if the --show-each flag is not set, but if --show-each is set and --wide is not, the output is confusing.

If neither flag is set, the output is "PFS is offered (OK)" in green, followed by a list of **supported** PFS cipher suites (in black).

If --show-each is set and --wide is not, the output is "PFS is offered (OK)" in green, followed by a list of **all** PFS cipher suites (in black), which I think is confusing.

I believe that for the case in which --show-each is set and --wide is not, either the --show-each flag should be ignored for this output line or something should be done to visually distinguish between the cipher suites that are supported and those that are not.

Thanks,

David

**Comment by drwetter** [comment]
Am 30. März 2016 16:43:07 MESZ, schrieb David Cooper <notifications@github.com>:
>There seems to be four different modes for printing the results of
>run_pfs when PFS is offered, depending on whether the --show-each and
>--wide flags are set.
>
>The output seems okay is the --wide flag is set or if the --show-each
>flag is not set, but if --show-each is set and --wide is not, the
>output is confusing.
>
>If neither flag is set, the output is "PFS is offered (OK)" in green,
>followed by a list of **supported** PFS cipher suites (in black).
>
>If --show-each is set and --wide is not, the output is "PFS is offered
>(OK)" in green, followed by a list of **all** PFS cipher suites (in
>black), which I think is confusing.
>
>I believe that for the case in which --show-each is set and --wide is
>not, either the --show-each flag should be ignored for this output line
>or something should be done to visually distinguish between the cipher
>suites that are supported and those that are not.

You're right. --show-each alone is BS in the PFS section. It could make sense if other ciphers would be greyed out. I'll fix that later if I am home.

Thx, Dirk




-- 
Set from my mobile. Excuse my brevity&typos
