### ISSUE TITLE
Feature / Run same command using --file

### ISSUE THREAD

**Issue by doubledeee** [drwetter/testssl.sh#336]
From my understanding, the --file requires a specific command for each line (with host).  It would be nice to be able to use --file to have one command run on a list of URLs.  Example:  Scan for RC4 ciphers in use on a list of servers.  
testssl -4 --quiet URL1
testssl -4 --quiet URL2

It would be nice to run testssl --4 --quiet --file pathtofile
where pathtofile would have a long list of URLs to find a specific vulnerability.

**Comment by drwetter** [comment]
yes, would be nice (btw: I should consider rename -4 as it can b mistaken by IPv4 only, see -4).

However I am afraid of  people confusing options. Besides testssl should be used as a tool not to help prevent users from putting one or two thoughts to it how to hold the hammer ;-)

Can you convince me why "file" containing your host (with the same) arguments  is not good enough?

**Comment by doubledeee** [comment]
Agreed on the -4, you could rename it to rc4. For me, it was clear because I read the details of help file. 

what I think is helpful is to have a file with hosts and thats it. Then when you run the script with desired parameters, it will run the same arguments for the hosts in the file. Right now, from my understanding, is the hosts file has to have each line specify all arguments instead of getting parameters from the script + file (list of hosts)

**Comment by drwetter** [comment]
Am 20. April 2016 04:51:03 MESZ, schrieb doubledeee <notifications@github.com>:

>what I think is helpful is to have a file with hosts and thats it. Then
>when you run the script with desired parameters, it will run the same
>arguments for the hosts in the file. Right now, from my understanding,
>is the hosts file has to have each line specify all arguments instead
>of getting parameters from the script + file (list of hosts)


Yes. Dor now you only can put hosts in the file and optionally some options.

The cmdline parser ignores other cmdline options if mass testing is being done as another instance per line in the file is being executed.

There needs to be a second parser or I need to find another elegant way of passing those options. There's also a potential conflict if there are two contradicting options.

For now the effort seems to big to add this convenience bits. I'll leave this open for later.


Cheers,, Dirk

-- 
Set from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment]
Actually I was talking BS this morning. Too early ;-)

During a boring train ride came the enlightenment that it is easy.

Enjoy, Dirk

-- 
Set from my mobile. Excuse my brevity&typos

**Comment by doubledeee** [comment]
Nice, thanks Dirk!  I tested this morning with new update and worked great.  Now I can massively automate scanning for particular vulnerabilities.
