### ISSUE TITLE
False positive from parse_tls_serverhello()

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#340]
I was just testing some code I wrote against an internal web server that I hadn't tried before, and it reported false-positive results. The problem seems to be the error response from the server. When tls_sockets() is called for SSLv3 (tls_sockets "00" "$TLS_CIPHER"), which the server does not support, the response is 15030000020228. However, when tls_sockets() is called with a TLS version that the server supports, but with a list of cipher suites that it doesn't support (e.g., tls_sockets 03 c0,3c), the response is: 1503030002017015030300020228.

The current version of parse_tls_serverhello() will always return 0 if the response begins with an alert that is an unrecognized name warning; it just assumes that this warning is followed by a server hello handshake message. In tls_sockets(), $lines is set to 2, so the check in tls_sockets() that the number of lines in the response isn't 1 doesn't catch the error either.

I don't know much about the server, other than "wget -S" reports that it is an Apache server.

I don't know whether this is a bug worth fixing. At the moment, it seems unlikely that one of the calls to tls_sockets() would fail as a result of the client hello not including any cipher suites supported by the server. The only way I can induce the bug using the current testssl.sh code is using the "--devel" option (e.g. bash testssl.sh --devel 03 "c0,3c" URI). The code that I've been developing at https://github.com/dcooper16/testssl.sh/blob/extended_tls_sockets/testssl.sh doesn't have this problem, since the parse_tls_serverhello() in that branch explicitly verifies that the response includes a server hello message.

Anyways, here is a dump of running  bash testssl.sh --devel 03 "c0,3c" URI: 
[debug3.txt](https://github.com/drwetter/testssl.sh/files/213378/debug3.txt)

Thanks,

Dave

**Comment by drwetter** [comment]
closing via #353.

Thx!
