### ISSUE TITLE
Feature Request - Test for incomplete certificate chain

### ISSUE THREAD

**Issue by cdloh** [drwetter/testssl.sh#344]
Would this be possible? Is it out of scope of what this does?

If people don't have the full chain put in place there are browsers that won't accept the connection.

**Comment by grandamp** [comment]
IMO, it would certainly be helpful!  Is there a desire to test the effect of HSTS, and user experience?  Some browsers may not function correctly if the trust anchor is not included with the entity and intermediate certificates.  Some clients build their own path to a trust anchor.

The following repo may be of interest:

https://github.com/18F/fpki-testing

**Comment by drwetter** [comment]
Hey Callum,

Am 23. April 2016 17:35:00 MESZ, schrieb Callum Loh <notifications@github.com>:
>Would this be possible? Is it out of scope of what this does?
>
>If people don't have the full chain put in place there are browsers
>that won't accept the connection.

See certificate chain in the output.

HTH, Dirk



-- 
Set from my mobile. Excuse my brevity&typos
