### ISSUE TITLE
SMTP and IMAP always go to 0/tcp

### ISSUE THREAD

**Issue by rmenessec** [drwetter/testssl.sh#347]
**IP:** [private]
**testssl.ssh version:** testssl.sh GitHub master (v2.4-487-g269a9e8)
**OpenSSL version:** shipped in testssl.sh GitHub master (v2.4-487-g269a9e8)
**Operating system:** Ubuntu Linux 15.10 (Wily)

Whenever a service is specified in the URI, testssl.sh appears to discard any provided port numbers and does not attempt to connect to default ports; instead, it attempts to connect to TCP port 0, which will always fail. I've been able to reproduce this with v2.6 and v2.7dev (current master on GitHub).

Unfortunately, this is an internal machine. I cannot provide logs without some way to scrub internal IP addresses and DNS records from the logs that testssl.sh generates.

I've tested it on several machines and looked over several packet captures: it really is trying to connect to 0/tcp. I've run '/usr/src/testssl.sh/bin/openssl.Linux.x86_64 s_client -connect 10.0.0.1:25' (x86_64 machine) and confirmed via packet capture that this works fine. Dovecot (the target service) throws SMTP errors, which I'd expect. When connecting with testssl.sh, tcpdump shows an immediate reset following the initial SYN; Linux' net stack is immediately rejecting the packet.

I can reproduce this response by running 'nmap -sT -p 0 [target]'.

Note: I've only attempted to test with smtp:// and imap:// at this time.

Please consider adding explicit support for smtps:// and imaps:// - this is what I'm actually trying to test, rather than SMTP and IMAP.

Thanks!

**Comment by drwetter** [comment]
Am 05/10/2016 um 09:02 AM schrieb rmenessec:

> Note: I've only attempted to test with smtp:// and imap:// at this time.

That should return an fatal error like "imap doesn't resolve to an IP address"

> Please consider adding explicit support for smtps:// and imaps:// - this is what I'm actually
> trying to test, rather than SMTP and IMAP.

You need you use ip:port and if needed -t/--starttls. https://<host:ip>
is the only exception as people want to copy it from the location bar
and you can specify a full URL here which might divulge different server headers
or cookies.


Don't know whether your request is reasonable to implement.

Either it a STARTTLS service is to be tested, then -t/--starttls is needed.

In any other case the application layer protocol is irrelevant as testssl.sh
will find out by itself.

Can't think of a case which won't confuse others or breaks compatibility,


Cheers, Dirk

**Comment by rmenessec** [comment]
Okay, I'm confused. the inline help for testssl.sh implies that it supports smtp:// and imap:// protocols. If I try to use those (ex: "testssl.sh smtp://localhost"), it tries to reach 0/tcp and fails. If I specify a port in the form "testssl.sh smtp://localhost:587", it tries to reach 0/tcp and fails.

In this case, "smtp.local.net" resolves to the same mail server, so I think that explains why the DNS lookup is succeeding. "imap" and "mail" and a couple other common names are also CNAMEs for the server.

If it's not possible to use protocol names like "smtp" in the URI, you may want to revise your documentation. As written, it strongly implies that URIs with
```
one of ftp,smtp,pop3,imap,xmpp,telnet,ldap
```
...are accepted by testssl.sh. If this is not the case, how do I specify a protocol to test? URIs with these parameters are extremely common, in my experience. I don't understand how supporting them would cause confusion.

I'm aware of the --starttls flag, but that's not what I want to test. Use of STARTTLS is an extremely bad idea; it's susceptible to a trivial MitM downgrade attack, like [sslstrip](https://moxie.org/software/sslstrip/). Instead, Postfix and Dovecot are configured to accept only TLS negotiation to open sessions, exactly like HTTPS. This is known as SMTPS and IMAPS.

Update - I've gotten testssl.sh to work with Dovecot. I think I may simply have failed to try 'localhost:993'. I still can't test against Postfix, however. testssl.sh does detect that it's not an HTTP service, but then it seems to fail to detect the protocol that's actually in use inside the TLS tunnel - it's just SMTP. testssl.sh reports that it's not an SSL/TLS service at all.

Postfix is configured like so (only non-default options shown):
```
smtpd_tls_dh1024_param_file = /etc/ssl/private/dhparams-postfix.pem
smtpd_tls_dh512_param_file = $smtpd_tls_dh1024_param_file
smtpd_tls_eecdh_grade = ultra
smtpd_tls_received_header = yes
smtp_enforce_tls = yes
smtp_starttls_timeout = 10s
smtp_tls_CAfile = [expunged]
smtp_tls_cert_file = [expunged]
smtp_tls_ciphers = high
smtp_tls_exclude_ciphers = aNULL, eNULL, EXPORT, DES, 3DES, RC2, RC4, MD2, MD4, MD5, PSK, DSS, SEED, SRP, IDEA, KRB5, ADH, aECDH
smtp_tls_fingerprint_digest = sha512
smtp_tls_key_file = [expunged]
smtp_tls_loglevel = 0
smtp_tls_mandatory_ciphers = high
smtp_tls_mandatory_exclude_ciphers = $smtp_tls_exclude_ciphers
smtp_tls_mandatory_protocols = !SSLV2,!SSLV3
smtp_tls_protocols = !SSLV2,!SSLV3
smtp_tls_security_level = must
tls_daemon_random_bytes = 64
tls_disable_workarounds = 0xFFFFFFFF
tls_high_cipherlist = ALL:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!SSLV2:!SSLV3:!RC2:!RC4:!MD2:!MD4:!MD5:!PSK:!DSS:!SEED:!SRP:!IDEA:!KRB5:!ADH:!aECDH:@STRENGTH
tls_preempt_cipherlist = yes
tls_random_bytes = 64
tls_random_prng_update_period = 10s
tls_random_reseed_period = 10s
tls_ssl_options = NO_COMPRESSION
```

**Comment by drwetter** [comment]
You probably confused the lines URI and protocol

```
partly mandatory parameters:
     URI                           host|host:port|URL|URL:port   (port 443 is assumed unless otherwise specified)
     pattern                       an ignore case word pattern of cipher hexcode or any other string in the name, kx or bits
     protocol                      is one of ftp,smtp,pop3,imap,xmpp,telnet,ldap (for the latter two you need e.g. the supplied openssl)
```

For localhost I can reproduce what you're saying. This needs to be addressed properly. Thx.

**Comment by rmenessec** [comment]
Exactly. That's the confusing part. [URIs take the form](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier):
```
protocol://host[:port]
```
I'm suggesting that either you change "URI" to "URL" and make it clearer that https:// URLs are a special case, or else treat all URIs equally.

Separately - I can't find a way to disable the HTTPS attack tests. Is there any? testssl.sh is executing them regardless of what protocol I'm testing. They should probably be disabled whenever testssl.sh detects - or the user specifies - a protocol other than HTTP inside an SSL/TLS tunnel.

Thanks!

**Comment by drwetter** [comment]
Am 11. Mai 2016 21:22:31 MESZ, schrieb rmenessec <notifications@github.com>:
>Exactly. That's the confusing part. [URIs take the
>form](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier):
>```
>protocol://host[:port]
>```
>I'm suggesting that either you change "URI" to "URL" and make it
>clearer that https:// URLs are a special case, or else treat all URIs
>equally.

I can do that but it coukd confuse others. But you should rather look at the definition in the help. It's clearly stated there.

>Separately - I can't find a way to disable the HTTPS attack tests. Is
>there any? testssl.sh is executing them regardless of what protocol I'm
>testing. They should probably be disabled whenever testssl.sh detects -
>or the user specifies - a protocol other than HTTP inside an SSL/TLS
>tunnel.

Nope. Your finding is not correct.


Cheers, Dirk

-- 
Set from my mobile. Excuse my brevity&typos

**Comment by rmenessec** [comment]
It's not "a finding." It's a suggestion.

Could you please provide a switch to disable the HTTPS vulnerability tests while I'm trying to test against non-HTTPS services?

Thanks!

**Comment by drwetter** [comment]
Am 12. Mai 2016 07:23:54 MESZ, schrieb rmenessec <notifications@github.com>:
>It's not "a finding." It's a suggestion.
>
>Could you please provide a switch to disable the HTTPS vulnerability
>tests while I'm trying to test against non-HTTPS services?

There's no need for it. It's done automatically. 



-- 
Set from my mobile. Excuse my brevity&typos

**Comment by rmenessec** [comment]
I haven't had a chance to look at the changes you made, but after pulling the latest master commits, I still can't test TLS on 587/tcp... and now trying 25/tcp just hangs. Doesn't matter what address or IP I pass or what host I test from.

Is testssl.sh even trying to detect SMTP on 587? It still says this is not an SSL / TLS service. Actual mail clients (Outlook, Thunderbird, KMail) are working fine on both 25 and 587. Packet capture confirms good TLSv1.0, 1,1, and 1.2 connections from mail clients.

If testssl.ssh is not testing for SMTP on 587/tcp, please see RFC 4409.

**Comment by drwetter** [comment]
> Is testssl.sh even trying to detect SMTP on 587? 

besides HTTP there's no real service detection done. The main goal of this program is testing the encryption, not any application layer (exception: HTTP).

Either applications/services are on a purely TLS enabled port (like 465) or required a STARTTLS handshake and addtionally a specification of the protocol before (587, 25). 

STARTTLS you have to specify as testssl.sh cannot year the users thoughts and testssl.sh by design makes no assumption on "port <--> STARTTLS needed".
