### ISSUE TITLE
PFS not detected correctly

### ISSUE THREAD

**Issue by selsky** [drwetter/testssl.sh#354]
I'm using the openssl available form Homebrew on OSX (1.0.2g) and when I connect to my starttls service, the output is:
```
$ /usr/local/opt/openssl/bin/openssl s_client -cipher ECDH:DH -starttls smtp -connect 192.168.0.100:587 < /dev/null 
CONNECTED(00000003)
---
no peer certificate available
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 628 bytes and written 507 bytes
---
New, TLSv1/SSLv3, Cipher is AECDH-AES256-SHA
Secure Renegotiation IS supported
Compression: zlib compression
Expansion: zlib compression
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AECDH-AES256-SHA
    Session-ID: E8D78F393A4CDE54561D068648D4DAAF349B1CA69C8E07F88C799C8C5C39AB83
    Session-ID-ctx: 
    Master-Key: 15897111FDE90886DCBA905A98038F5C8D1FE6584C5916CBD61F5FDC966A5D9F653C64E59408D33C40509574D2E1D175
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 76 03 c2 e1 60 4e b1 d3-d6 af 9b 64 0a a3 56 bd   v...`N.....d..V.
    0010 - 78 ca 30 dd 9a 17 26 1e-5a 44 5a 15 fd e0 09 43   x.0...&.ZDZ....C
    0020 - 96 8a 09 66 92 d6 e2 f4-2a 64 53 55 65 dc 82 e9   ...f....*dSUe...
    0030 - af c9 3b 40 0d 55 06 83-e7 98 c6 a4 b5 f5 2b 83   ..;@.U........+.
    0040 - 39 58 db b3 b4 54 22 32-c1 0c 98 68 54 99 1d 58   9X...T"2...hT..X
    0050 - 82 1e f9 ef 60 52 d3 3b-04 54 87 dd 6d ef 22 69   ....`R.;.T..m."i
    0060 - 3b 0b 9a 31 c6 0b bf 45-52 7f 31 18 72 3f e6 28   ;..1...ER.1.r?.(
    0070 - 5b ae b3 8f 6e 85 1c 07-ec 33 00 df ef 18 59 7d   [...n....3....Y}
    0080 - ba ac 07 ce 06 ed ca 6a-63 62 4b 06 d2 46 4e 7e   .......jcbK..FN~
    0090 - c9 b0 27 2b 7f f0 12 c2-ed fa 69 af 5a 0b 98 8a   ..'+......i.Z...
    00a0 - c2 3f 71 be b8 45 ee 8c-92 f6 fb 34 15 bd 80 12   .?q..E.....4....

    Compression: 1 (zlib compression)
    Start Time: 1463549643
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
250 DSN
DONE
```

However, testssl (today's git head) reports:
```
 Testing (perfect) forward secrecy, (P)FS -- omitting 3DES, RC4 and Null Encryption here 

NOT ok: No ciphers supporting Forward Secrecy offered
```

AECDH-AES256-SHA should be in pfs_cipher_list

**Comment by selsky** [comment]
AECDH is anonymous so the
```
[[ $(grep -ac "BEGIN CERTIFICATE" $TMPFILE) -eq 0 ]]
```
check fails.

**Comment by drwetter** [comment]
In general this test aims at not only a solid key exchange. It tries to weed out everything which makes FS useless. ADH/AECDH should be part of it. My description of this test was missing anonymous ciphers but looking at it now I don't know whether I should also keep 3DES and RC4 in there.

Opinions?

**Comment by drwetter** [comment]
Anonymous kx doesn't make sense here and misleads users. I added (see next commit) a more verbose description to clarify this.

You might want to have a look @ https://blog.qualys.com/ssllabs/2013/08/05/configuring-apache-nginx-and-openssl-for-forward-secrecy  and ignore the RC4 part (old beast mitigation).

**Comment by selsky** [comment]
The test checks the following ciphers: ECDH:DH.  This includes both anonymous and non-anonymous (and my server prefers the anonymous cipher).  The check should exclude anonymous ciphers since it doesn't want to see those in the response.

On https://github.com/drwetter/testssl.sh/commit/9a1425da14eeaaa20b9c692306a67eb8c493842a#diff-2b772c01e86977452d2db64b3031f913R3564
'ECDH:DH' should become 'ECDH:DH:!aNULL'

I'm testing against postfix and anonymous ciphers are OK for my use case per http://www.postfix.org/FORWARD_SECRECY_README.html

Thanks!

**Comment by selsky** [comment]
I'll move this to a new issue.
