### ISSUE TITLE
Avoid anonymous ciphers in PFS check

### ISSUE THREAD

**Issue by selsky** [drwetter/testssl.sh#355]
The test checks the following ciphers: ECDH:DH. This includes both anonymous and non-anonymous (and my server prefers the anonymous cipher, but has the non-anonymous ciphers as well). The check should exclude anonymous ciphers since it doesn't want to see those in the response.

On line 3564, 'ECDH:DH' should become 'ECDH:DH:!aNULL'

I'm testing against postfix and anonymous ciphers are OK for my use case per http://www.postfix.org/FORWARD_SECRECY_README.html

Thanks!

**Comment by drwetter** [comment]
Hi @selsky,

The current check doesn't include aNULL ciphers. Have a look at the while loop!

By coincidence I have a costumer using such a setting and I can't confirm that any aNULL cipher is listed in the output.
