### ISSUE TITLE
Fix IPv6 handling

### ISSUE THREAD

**Issue by typingArtist** [drwetter/testssl.sh#365]
testssl.sh doesn’t work on my computer (Gentoo, x86_64) using IPv6 addresses. I tried the following options: setting `-6` as an option, setting `--ip <ipv6_address>`, and additionally with either the supplied `openssl` binary or the system default `openssl-1.0.2h`, neither of them worked.

The first thing that doesn’t work is the host PTR lookup. I only see `--` displayed for the rDNS, and the tool asks me whether I want to proceed.

```
 Start 2016-05-27 15:57:19    -->> [xxxx:xxxx:xxxx:xxxx::xxxx]:443 (example.com) <<--

 further IP addresses:      xxx.xxx.xxx.xxx
 A record via            /etc/hosts
 rDNS [xxxx:xxxx:xxxx:xxxx::xxxx]:  --

 Your ./bin/openssl.Linux.x86_64 is not IPv6 aware, or [xxxx:xxxx:xxxx:xxxx::xxxx]:443 doesn't seem a TLS/SSL enabled server
 Note that the results might look ok but they are nonsense. Proceed ? 
```

Continuing seems to work in parts, but strangely the IPv6 results differ from the IPv4 results. For example, it shows me TLS 1.2, High grade encryption, as well as PFS ciphers not offered, which is plain wrong. The report is followed by a lot of false positives and wrong output, ending in an empty list of available ciphers and a 100% 'No connection' in the browser simulation.

The only solution which works on my computer is to patch away the line from the source that puts brackets around the IPv6 address, as in the following patch, and using the system-supplied `openssl` binary. As already discussed with @drwetter in https://github.com/drwetter/testssl.sh/pull/364, it seems that Gentoo applies a special patch to its openssl build which allows its `-connect` parameter to use a bracket-less address. However, all other used tools, be it dig/host/nslookup or the various network socket options seem to work way better and totally correct with the address having *no* brackets around it.

```
diff --git a/testssl.sh b/testssl.sh
index 029dcde..6ba1ff9 100755
--- a/testssl.sh
+++ b/testssl.sh
@@ -7101,7 +7101,6 @@ nodeip_to_proper_ip6() {
      local len_nodeip=0

      if is_ipv6addr $NODEIP; then
-          NODEIP="[$NODEIP]"
           len_nodeip=${#NODEIP}
           CORRECT_SPACES="$(draw_line " " "$((len_nodeip - 16))" )"
           # IPv6 addresses are longer, this varaible takes care that "further IP" and "Service" is properly aligned
```

**Comment by drwetter** [comment]
Hi @typingArtist 

don't know what your expectation is.... If testssl.sh would include this patch the shipped binaries and the FC openssl won't work! But the probably-RFC-non-compliant- BS-gentoo-openssl (sorry) is working. That's not what I want. :-)

What does 

``echo | openssl s_client -connect "[$(dig +short -t AAAA ipv6.google.com | tail -1)]:443"``

show on Gentoo?

**Comment by typingArtist** [comment]
FWIW, I now tried on a CentOS 7 box, and running it with just `-6` option enabled I see at least basically the same problems following the rDNS output line, like asking me for continuing, and then also wrong cipher and protocol support and false positives all over the place.

```
 Your ./bin/openssl.Linux.x86_64 is not IPv6 aware, or [xxxx::::xxxx]:443 doesn't seem a TLS/SSL enabled server
 Note that the results might look ok but they are nonsense. Proceed ?  y
```

However, if I turn to using the system-wide openssl binary with an *unpatched* testssl.sh script, things change to the better (even if it’s only openssl-1.0.1) and more or less the whole output makes sense. The only difference is that, obviously, HTTP2/ALPN is not supported just like 56 bit encryption, and it tells me that the chain-of-trust check might be erroneous due to the unreliable old openssl version.

Manually calling `openssl s_client` for supplied and system-wide binaries, I see the following results:

on Gentoo:
```
$ bin/openssl.Linux.x86_64 s_client -connect '[::1]:443' 2>&1 | head -n 1
getservbyname failure for :1]:443
$ bin/openssl.Linux.x86_64 s_client -connect '::1:443' 2>&1 | head -n 1
getservbyname failure for :1:443
$ openssl s_client -6 -connect '[::1]:443' 2>&1 | head -n 2
gethostbyname failure
connect:errno=0
$ openssl s_client -6 -connect '::1:443' < /dev/null 2>&1 | head -n 2
depth=2 …
verify return:1
```

on CentOS 7:
```
$ bin/openssl.Linux.x86_64 s_client -connect '[::1]:443' 2>&1 | head -n 2
WARNING: can't open config file: /etc/ssl/openssl.cnf
getservbyname failure for :1]:443
$ bin/openssl.Linux.x86_64 s_client -connect '::1:443' 2>&1 | head -n 2
WARNING: can't open config file: /etc/ssl/openssl.cnf
getservbyname failure for :1:443
$ openssl s_client -connect '[::1]:443' < /dev/null 2>&1 | head -n 2
depth=1 …
verify error:num=20:unable to get local issuer certificate
$ openssl s_client -connect '::1:443' 2>&1 | head -n 2
getaddrinfo: Servname not supported for ai_socktype
connect:errno=0
```

So, bottom line for the moment:
• The supplied openssl binary behaves equally bad on the two systems and doesn’t work with IPv6 addresses at all, with or without brackets
• reverse lookups for IPv6 addresses in `testssl.sh` never work with brackets applied around the addresses (i.e., when the patch is not applied)
• CentOS-supplied `openssl` works properly, even if it’s an older version, but only if the patch is *not* applied, i.e. with brackets
• Gentoo-supplied `openssl` works properly only without bracketed addresses, i.e. when the patch *is* applied

So, baby stepping the topic, I should first become able to have the supplied openssl work with IPv6 addresses at all.

@drwetter, are you sure that the Linux binaries for x86_64 work with IPv6 addresses at all? I tried the i686 and -krb5 binaries as well, and they all equally refuse to work (of which i686-krb5 wasn’t even able to run, lacking some libraries on the 64 bit computer).

**Comment by typingArtist** [comment]
just to make that point clear: My goal is not to fix possibly bad Gentoo behavior into the sources of testssl.sh, so please don’t put all your efforts on arguing that way. I just want the tool to work with IPv6 at all, and in the first attempt it looked more warranting to remove the bracketing from testssl.sh and use the system-wide openssl binary. You were completely right in refusing https://github.com/drwetter/testssl.sh/issues/364 but the issue is still there.

**Comment by typingArtist** [comment]
@drwetter, To answer your question:

```
$ echo | openssl s_client -connect "[$(dig +short -t AAAA ipv6.google.com | tail -1)]:443"
gethostbyname failure
gethostbyname failure
connect:errno=0
```

Now my question: what gives

```
dig -x [2a00:1450:4001:812::200e] +noall +answer
```

on your system? (the IPv6 address is the current AAAA of `ipv6.google.com`, but its PTR is `fra16s05-in-x0e.1e100.net`, at least on my computer)

I am not able to get that value back with brackets, only without, and that’s for either dig, host or nslookup. That’s why I think we need to go away from the bracketed version, at least for the rDNS step.

**Comment by typingArtist** [comment]
Just to repeat that: #366 only fixes the problem in `testssl.sh` under the assumption that the `openssl` binary is actually able to do IPv6 connections which doesn’t seem to be the case right now for the x86_64 and i686 Linux versions. Please also fix the binaries to include IPv6 support.

I’ll continue digging into the Gentoo IPv6 patch whether it can be inflated a little bit for supporting the bracketed representation of the addresses as well.

**Comment by typingArtist** [comment]
I have now successfully patched my Gentoo’s `openssl` binary such that it supports both bracketed and unbracketed IPv6 addresses as the `-connect` parameter. Patch is sent upstream, see https://bugs.gentoo.org/show_bug.cgi?id=584360

**Comment by drwetter** [comment]
Am 27. Mai 2016 20:25:32 MESZ, schrieb typingArtist <notifications@github.com>:
>Just to repeat that: #366 only fixes the problem in `testssl.sh` under
>the assumption that the `openssl` binary is actually able to do IPv6
>connections which doesn’t seem to be the case right now for the x86_64
>and i686 Linux versions. Please also fix the binaries to include IPv6
>support.

Matthias, don't know what binaries you are using. The ones at github have no IPV6 support yet -- as oppoeed to 1.0.2i @ https://testssl.sh.

Cheers, Dirk 


-- 
Set from my mobile. Excuse my brevity&typos

**Comment by typingArtist** [comment]
Yeah, sorry, I thought the binaries on github were the most recent ones, or even more recent than those offered on https://testssl.sh.

Are you planning of pushing them to the github repo? I think that would make sense, especially for devs who stick with the git repo.

**Comment by drwetter** [comment]
Am 05/30/2016 um 09:33 PM schrieb typingArtist:
> Yeah, sorry, I thought the binaries on github were the most recent ones, or even more recent
> than those offered on https://testssl.sh.
> 
> Are you planning of pushing them to the github repo? I think that would make sense, especially
> for devs who stick with the git repo.

partly, see #362.

-- 
Set from my mobile. Excuse my brevity&typos
