### ISSUE TITLE
Use 30 day expiry warning for Let's Encrypt, 60 day warning for all others'

### ISSUE THREAD

**Issue by chrcoluk** [drwetter/testssl.sh#367]
Can the code be changed to only show a warning below 30 days instead of 60 days if it detects a letsencrypt cert?

**Comment by teward** [comment]
I think this should be retitled to 'Certificate Expiration Warning Threshold for Let's Encrypt', as first-glance seems to me that the code doesn't have any Let's Encrypt handling currently.

**Comment by chrcoluk** [comment]
you right, but sadly I cannot edit the title now :(

**Comment by drwetter** [comment]
BTW: For that CA I divided the thresholds by two.
