### ISSUE TITLE
Failure with Certificate date format

### ISSUE THREAD

**Issue by logopk** [drwetter/testssl.sh#372]
Running 2.7dev on docker image of jumanjiman:

```
 Certificate Expiration       >= 60 daysdate: invalid date 'Aug 21 20:38:00 2016 GMT'
date: invalid date 'May 23 20:38:00 2016 GMT'
 ( --> )
```
enddate returns:
```
bash-4.3# openssl x509 -in host_certificate.txt -noout -enddate  | cut -d= -f 2
Aug 21 20:38:00 2016 GMT

```
and

```
bash-4.3# date --date="$(openssl x509 -in host_certificate.txt -noout -enddate | cut -d= -f 2)" +"%F %H:%M %z"
date: invalid date 'Aug 21 20:38:00 2016 GMT'

```

-------------------------------
```
bash-4.3# cat environment.txt 

CVS_REL: 1.398 2015/10/02 22:14:51
GIT_REL: 

PID: 108
bash version: 4.3.33
status: release
machine: x86_64-alpine-linux-musl
operating system: Linux
shellopts: braceexpand:hashall:interactive-comments

/usr/bin/openssl version -a:
OpenSSL 1.0.2-chacha (1.0.2d-dev)
built on: Mon Jul  6 18:05:33 2015
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_USE_BUILD_DATE -static -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_EXPERIMENTAL_JPAKE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/ssl"
OSSL_VER_MAJOR: 1
OSSL_VER_MINOR: 0.2
OSSL_VER_APPENDIX: -chacha
OSSL_BUILD_DATE: "Jul  6 18:05:33 2015"
OSSL_VER_PLATFORM: "linux-x86_64"

OPENSSL_CONF: /tmp/ssltester.EDkJoj/gost.conf

PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PROG_NAME: testssl.sh
INSTALL_DIR: /
RUN_DIR: .
MAPPING_FILE_RFC: 


CAPATH: /etc/ssl/certs/
ECHO: 
COLOR: 2
TERM_DWITH: 120
HAS_GNUDATE: true
HAS_SED_E: true

SHOW_EACH_C: 0
SSL_NATIVE: false
ASSUMING_HTTP false
SNEAKY: false

DEBUG: 1

HSTS_MIN: 179
HPKP_MIN: 30
CLIENT_MIN_PFS: 5
DAYS2WARN1: 60
DAYS2WARN2: 30

HEADER_MAXSLEEP: 5
MAX_WAITSOCK: 10
HEARTBLEED_MAX_WAITSOCK: 8
CCS_MAX_WAITSOCK: 5
USLEEP_SND 0.1
USLEEP_REC 0.2


locale doesn't exist

```

**Comment by logopk** [comment]
Oh, BTW, also on Date Headers:

`'HTTP clock skew              date: invalid date 'Thu, 02 Jun 2016 22:27:34 GMT
-1464906454 (± 1.5) sec from localtime
`

**Comment by drwetter** [comment]
The ``environment.txt`` (not final 2.6 release) and everything else is from the docker container? 

If so it appears kind of strange to me as I do not expect @jumanjiman to release s.th. which is not working.  But he's the person in charge here -- unless you run natively on OS X.

**Comment by logopk** [comment]
The environment.txt is from the container.

Apparently the fix worked on OSX. I guess this time it is the "if"-case of the HAS_GNUDATE that fails on alpine linux.

Just a comparison:

date on plain German OSX states:
```
>:~ logo$ date
Fr  3 Jun 2016 08:53:41 CEST
>:~ logo$ LC_ALL=C
>:~ logo$ date
Fri Jun  3 08:53:49 CEST 2016
```
on alpine date returns:
`Fri Jun  3 06:53:32 UTC 2016`

openssl from the cert returns:
`Aug 21 20:38:00 2016 GMT`

so that seems to be the same problem.

**Comment by drwetter** [comment]
@logopk: I am not sure what you wanted to tell me you beyond "Just a comparison".

My humble guess is that Alpine Linux (for docker) that it is not a full GNU date but supports ``--help`` testssl.sh decides by ``date --help`` whether ``date`` is GNU or BSD and picks the according cmdline options.  

Basically I am out of this as @jumanjiman maintains the docker image. ;-)

**Comment by logopk** [comment]
Hi Dirk,

well the formatting error is in the script. I tried to point out the culprit statements.

I assume a problem depending on the linux/os x version should be addressed here?

That's why I tried to help to reproduce the macos x issue #284.

**Comment by logopk** [comment]
So maybe @jumanjiman wants to check into the root cause?

**Comment by jumanjiman** [comment]
> My humble guess is that Alpine Linux (for docker) that it is not a full GNU date but supports --help testssl.sh decides by date --help whether date is GNU or BSD and picks the according cmdline options.

my container doesn't have gnu coreutils in it at the moment...an easy addition.
i can also add tzdata for good measure.

**Comment by jumanjiman** [comment]
@logopk can you please test with the wip image published from PR https://github.com/jumanjihouse/docker-testssl/pull/10 to https://quay.io/repository/jumanjiman/testssl?tab=tags

* wip image: `quay.io/jumanjiman/testssl:master-jumanjiman_pull_10`

**Comment by jumanjiman** [comment]
@logopk confirmed https://github.com/jumanjihouse/docker-testssl/pull/10 so it's merged.
latest image is now published at quay, and the `*-jumanjiman_pull*` tag is gone.

**Comment by drwetter** [comment]
thx!
