### ISSUE TITLE
No engine or GOST support via engine with your /usr/bin/openssl

### ISSUE THREAD

**Issue by oranze** [drwetter/testssl.sh#388]
Centos 7 64 bit. If I run from shell all fine. But if I run from php script by exec / shell_exec then got error.
<?php
$ssltest_result = shell_exec('/usr/bin/testssl --each-cipher '.$domain
var_dump($ssltest_result);

RESULT:
No engine or GOST support via engine with your /usr/bin/openssl

###########################################################
    testssl       2.6 from https://testssl.sh/
    (1.379B 2015/09/25 12:35:41)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.1e-fips 11 Feb 2013" [~121 ciphers] on
 dev:
 (built: "May  9 08:07:32 2016", platform: "linux-x86_64")

**Comment by drwetter** [comment]
Thx @oranze for reporting.

Closing because a) old testssl.sh version. b) not the recommended openssl version used c) little information. See also https://github.com/drwetter/testssl.sh/wiki/Bug-reporting.

My guess is that there's a problem finding OPENSSL_CONF. 

Cheers, Dirk

**Comment by drwetter** [comment]
PS: check ``open_basedir`` in ``php.ini``. testssl works with files in ``/tmp`` and php settings need to permit that.
