### ISSUE TITLE
Cleanup client simulation

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#393]
There is at least 1 task here:

1) Update the data. There's no need to include outdated firefox or chrome versions. 
2) Need to think over it, maybe it makes sense to use `-cc` for the whole nine yards of output and `-c` restrict on the clients which are relevant. Q then: what is relevant.

**Comment by seccubus** [comment]
Mark as "current":
* Android - all versions
* Baidu / Bing / Google / Yahoo / Yandex - Latest version only
* Chrome - Latest version only
* Firefox - Latest 3 versions
* IE / Edge - All unique combinations of platforms but only those with the highest ID
* Java - All versions
* OpenSSL - All versions
* Opera - Ignore all versions
* Apple ATS - All versions
* Safari - All versions

This gives a set which is similar to SSL labs.

Run only the "current" clients with -c add flag --all-clients to run all client simulations we have.

Each client has a tag that indicates the services it supports. Only run those simulations that make sense. Flag --all-clients overrides this too.

This should not be a major change from what I have now. And if you prefer I copy the data back into the main script.

**Comment by drwetter** [comment]
> This should not be a major change from what I have now. And if you prefer I copy the data back 
> into the main script.

Thought I answered to this but it looks I did not. 

Sure, yes pls!

**Comment by seccubus** [comment]
You have a PR for this already. #394

**Comment by drwetter** [comment]
Am 07/09/2016 um 01:55 PM schrieb Frank Breedijk:
> You have a PR for this already. #394 <https://github.com/drwetter/testssl.sh/pull/394>


Sorry, Frank. I missed your updates on this. You want me to manually handle
the patches or you want rather to rebase to the current master?

Cheers, Dirk

-- 
Sent from my mobile. Excuse my brevity&typos

**Comment by seccubus** [comment]
Dirk,

If you are willing to take that PR, then I'll make sure it merges.

**Comment by drwetter** [comment]
Hi Frank,

sure!

Cheers, Dirk

Am 15. Juli 2016 08:28:31 MESZ, schrieb Frank Breedijk <notifications@github.com>:
>Dirk,
>
>If you are willing to take that PR, then I'll make sure it merges. 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/issues/393#issuecomment-232870493


-- 
Sent from my mobile. Excuse my brevity&typos

**Comment by seccubus** [comment]
Just updated PR #394 and merged it with master. 
It should merge without any issues.
Let me know if this is all it takes or if you need to me to do more about it.

**Comment by chrcoluk** [comment]
remember firefox has a extended support release.  So that should be marked current also.

https://www.mozilla.org/en-US/firefox/organizations/

**Comment by seccubus** [comment]
Yes, ESR is included too.

**Comment by drwetter** [comment]
Am 07/17/2016 um 08:23 PM schrieb Frank Breedijk:
> Just updated PR #394 <https://github.com/drwetter/testssl.sh/pull/394> and merged it with master.
> It should merge without any issues.
> Let me know if this is all it takes or if you need to me to do more about it.

Thx @seccubus!

I am on the road this weekend looking for sun :-).


Cheers, Dirk

**Comment by drwetter** [comment]
PRs have been merged a long while back
