### ISSUE TITLE
MacOS X test requested

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#40]
Can't tell whether with that old openssl version (native but ports would be interesting too) a error free detection is possible. Without BSD ports under FreeBSD 9 I get useless results.

Can somebody please check against testssl.sh and let me know? Thx!

![b1aef072-71c1-11e4-87ce-285da782d678](https://cloud.githubusercontent.com/assets/8036727/5221575/47d995a0-767e-11e4-9588-b63ed379219e.png)

**Comment by dmitris** [comment]
Is it still outstanding?  Which command would you want to try on a Mac - 
./testssl.sh https://85.214.71.41 
or something else?

**Comment by drwetter** [comment]
That would be great! And the info on the OpenSSL version used (openssl version -a).

PS: The IP address above is not mine anymore. If you mind rather use something different (dev.testssl.sh or testssl.sh).

**Comment by drwetter** [comment]
can somebody help here for the upcoming 2.4?

**Comment by keith4** [comment]
Is there a specific version of OS X you want tested?

**Comment by drwetter** [comment]
Am 9. Mai 2015 19:38:49 MESZ, schrieb keith4 <notifications@github.com>:
>Is there a specific version of OS X you want tested?

I own no Apple, so basically every test would help. Best would be first the latest and greatest.

I will do final test on FreeBSD 9 too but I can't tell how much both differ.

Important to me would be glitches in the output and differences in the results.

Cheers, Dirk

**Comment by salt-lick** [comment]
OSX 10.10.3 
./testssl.sh testssl.sh

 ¡¡¡ <Enter> at your own risk !!! /usr/bin/openssl is way too old (< version 1.0)
 Proceeding may likely result in false negatives or positives

Followed this http://apple.stackexchange.com/a/126832 and it allowed me to run the script with out this that error. 

I then run into this issue. 

" Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            ECDHE-RSA-AES256-GCM-SHA384
 Cipher order
     Protocol:TLSv1: Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA Cipher:ECDHE-RSA-AES256-SHA ^C"

Remember when it it did this before?

**Comment by salt-lick** [comment]
also:

./testssl.sh dev.testssl.sh

#########################################################
testssl.sh v2.4rc1  (https://testssl.sh)
($Id: testssl.sh,v 1.242 2015/05/06 16:48:50 dirkw Exp $)

   This program is free software. Redistribution +
   modification under GPLv2 is permitted.
   USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

 Note: you can only check the server with what is
 available (ciphers/protocols) locally on your machine!
#########################################################

 Using "OpenSSL 1.0.2a 19 Mar 2015" [~     136 ciphers] on
 Dev_SH:/usr/local/bin/openssl
 (built: "reproducible build, date unspecified", platform: "darwin64-x86_64-cc")


Testing now (2015-05-09 22:38) ---> 81.169.199.25:443 (dev.testssl.sh) <---

 rDNS (81.169.199.25):   testssl.sh
 Service detected:       HTTP

--> Testing protocols (via sockets for SSLv2, SSLv3)

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 SPDY/NPN   http/1.1 (advertised)

--> Testing standard cipher lists

 Null Cipher              not offered (OK)
 Anonymous NULL Cipher    offered (NOT ok)
 Anonymous DH Cipher      offered (NOT ok)
 40 Bit encryption        offered (NOT ok)
 56 Bit encryption        Local problem: No 56 Bit encryption configured in /usr/local/bin/openssl
 Export Cipher (general)  offered (NOT ok)
 Low (<=64 Bit)           offered (NOT ok)
 DES Cipher               offered (NOT ok)
 Triple DES Cipher        offered
 Medium grade encryption  offered
 High grade encryption    offered (OK)

--> Testing server preferences

 Has server cipher order?     nope (NOT ok)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            DHE-RSA-SEED-SHA (limited sense as client will pick)
 Negotiated cipher per proto  (limited sense as client will pick)
     Cipher:0000:                   Protocol:SSLv3
     Cipher:DHE-RSA-SEED-SHA:       Protocol:TLSv1, Protocol:TLSv1.1, Protocol:TLSv1.2
     Cipher:ECDHE-RSA-AES256-GCM-SHA384: http/1.1
 No further cipher order check as order is determined by the client

--> Testing server defaults (Server Hello)

 TLS timestamp:               random values, no fingerprinting possible
date: illegal option -- -
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
./testssl.sh: line 1281: 1431229148 - : syntax error: operand expected (error token is " ")

**Comment by drwetter** [comment]
Thx for this one.

Need to provide a date function for BSD/Linux.. The cipher order formatting will be done also

**Comment by drwetter** [comment]
did some FreeBSD 9 tests.. Looking at that there's still some way to go. How realistic is that a MAC user doesn't use ports?

**Comment by salt-lick** [comment]
I would say, if you were on OSX and running this script, you would be using a port. 

________________

Latest Pull
./testssl.sh dev.testssl.sh
--> Testing HTTP header response

 HSTS              --
 HPKP              --
 Server            Apache 1.3.37 (Tunix)
 Application      tr: illegal option -- t
usage: tr [-Ccsu] string1 string2
       tr [-Ccu] -d string1
       tr [-Ccu] -s string1
       tr [-Ccu] -ds string1 string2

___________________________________________________

./testssl.sh reddit.com

 Cipher order
     Protocol:TLSv1: Cipher:ECDHE-RSA-AES128-SHA Cipher:ECDHE-RSA-AES128-SHA Cipher:ECDHE-RSA-AES128-SHA repeat

**Comment by drwetter** [comment]
Those two should fixed, thx for reporting!

FYI: Supporting bare openssl (FreeBSD has "OpenSSL 0.9.8za-freebsd") would be a pain -- I am testing the return values. With "normal" openssl binaries this works if the server doesn't provide the tested feature. OpenSSL 0.9.8za instead returns always 0 instead throws an error.

**Comment by salt-lick** [comment]
Looks like you got them now. Great work.

**Comment by drwetter** [comment]
Thx, @salt-lick!

@all: If there's anything else using ports, pls let me know. Otherwise I am closing this issue soon.

I will have a closer look @ #101, #102, #103 though but a first glance let me assume the old openssl is the culprit here. That won't be done in 2.4, maybe in a later release.

**Comment by drwetter** [comment]
done for 2.4
