### ISSUE TITLE
Variables and command-line options

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#404]
Around line ~135 in `testssl.sh`:

```
# following variables make use of $ENV, e.g. OPENSSL=<myprivate_path_to_openssl> ./testssl.sh <host>
# 0 means (normally) true here. Some of the variables are also accessible with a command line switch
# most of them can be set also by a cmd line switch
```

Are *some* or *most* variables *accessible* or *settable* via *command* or *cmd* line switch?

I know nitpicking while sleep deprived...

**Comment by drwetter** [comment]
Thx. 

For those simple things feel free to do a PR ;-)

**Comment by jpluimers** [comment]
(: My bash foo isn't good enough yet to see if it was `most` or `some`.
