### ISSUE TITLE
--debug parameter specs need update line number

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#405]
The drawback of using line numbers to spec out `--debug`

It's both at https://github.com/drwetter/testssl.sh/wiki/Usage-Documentation and around https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L6833

Currently it says:

         --debug <0-6>                 1: screen output normal but debug output in temp files.  2-6: see line ~120

It should be `~150` as per https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L150

But I think you should just write out the options in full like this:

    --debug <0-6>                 0: none
                                  1: screen output normal but debug output in temp files.
                                  2: list more what's going on, lists some errors of connections
                                  3: slight hexdumps + other info
                                  4: display bytes sent via sockets
                                  5: display bytes received via sockets
                                  6: whole 9 yards

--jeroen

**Comment by drwetter** [comment]
Thx @jpluimers. All agree, except the help function. I rather try to keep that small. Normally there shoold be a manpage (#130) but nobody volunteered yet

**Comment by jpluimers** [comment]
I think I fixed the wiki page: https://github.com/drwetter/testssl.sh/wiki/Usage-Documentation/_history

**Comment by drwetter** [comment]
Am 07/08/2016 um 12:25 PM schrieb Jeroen Wiert Pluimers:
> I think I fixed the wiki page:
> https://github.com/drwetter/testssl.sh/wiki/Usage-Documentation/_history
> 

thx
