### ISSUE TITLE
some `$DEBUG -eq` comparisons might be replaced by `$DEBUG -ge`

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#406]
I see various `$DEBUG -eq` comparisons where the number is not zero.

I think many of them can be replaced by `$DEBUG -ge` comparisons.

Examples:
- https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L2851
- https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L2860
- https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L2990

There are more...

--jeroen

**Comment by drwetter** [comment]
agreed -- as far as I can see. 

``-eq 2`` can be replaced by debugme()
