### ISSUE TITLE
Check for certificate mismatch

### ISSUE THREAD

**Issue by johndekroon** [drwetter/testssl.sh#409]
I like to see that Testssl.sh explicitly warns if the host is serving a different certificate (for example foo.com serves the certificate of bar.com).
To test this I currently use another tool, but it would be nice if I could drop that.

**Comment by drwetter** [comment]
Am 11. Juli 2016 11:49:57 MESZ, schrieb johndekroon <notifications@github.com>:
>I like to see that Testssl.sh explicitly warns if the host is serving a
>different certificate (for example foo.com serves the certificate of
>bar.com).
>To test this I currently use another tool, but it would be nice if I
>could drop that.

I like to see that too and hopefully we get that done soon. 

It's an older ssue which is not easy and robust at the same time to implement.

See #94.

Cheers, Dirk 



-- 
Set from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment]
see duplicate
