### ISSUE TITLE
HMAC Support

### ISSUE THREAD

**Issue by evadogstar** [drwetter/testssl.sh#421]
Hello, thanks for this tool.
Is HMAC supported? Is it possible to add HMAC key to test service that use it?  
https://en.wikipedia.org/wiki/Hash-based_message_authentication_code

**Comment by drwetter** [comment]
Sure.

Can you pls be more precise?

**Comment by evadogstar** [comment]
E.g. openVPN use HMAC key signature to verify that package come from source who know this HMAC signature otherwise all ip-packets refused by server. When client connect, it provide `hmac-ta-sectet.key` to server. Without providing known HMAC I can not test service with `testssl.sh`. 
https://tunnelblick.net/cHmacSignature.html

**Comment by drwetter** [comment]
Ah, ok. 

First the HMAC key in OpenVPN is something different in the context of testssl.sh. In OpenVPN it is a pretection against dos'ing the service.  

Then normally OpenVPN is for performance reasons operated over UDP. Even if you run it over TCP I assume testssl.sh cannot test OpenVPN. 

Hope the explanation helped, despite it wasn't what you wanted.
