### ISSUE TITLE
 Server banner - strange ANSI characters.

### ISSUE THREAD

**Issue by CRCinAU** [drwetter/testssl.sh#433]
Hi all,

Looks like the latest version of testssl has some strangeness with the "Server banner" line - where it wants to output every digit as a coloured digit - as well as ending the line with ^M.

Is this intentional and I just haven't made my ANSI -> HTML stuff flexible enough or has something slipped through the cracks?

**Comment by CRCinAU** [comment]
On the same note, looks like we're now doing funky highlighting on the Application banner line too?

**Comment by CRCinAU** [comment]
Tracking this down a bit.... It seems that the emphasize_stuff_in_headers() is a little different than the rest of the script... Everything else outputs ESC[x;xxm as the ANSI codes. emphasize_stuff_in_headers() seems to break the pattern here.

While its still correct to use sgr0, it seems to make ANSI -> HTML conversions a little more difficult.

**Comment by drwetter** [comment]
@CRCinAU : you gotta throw a bit more information at us, see https://github.com/drwetter/testssl.sh/wiki/Bug-reporting

The \033 are ANSI escape codes, tput is terminfo/termcap -- used by ``emphasize_stuff_in_headers()`` . Under Linux and BSD using TERM=xterm* it is/should be always the same code which you see.

**Comment by CRCinAU** [comment]
Ok, so I did much more digging into this - it seems that all other areas in testssl.sh use something like:
^[[1m blah blah ^[[m

Stuff formatted by emphasize_stuff_in_headers() ends up lines like:
^[[33m^[[1mX-Powered-By^[[m^O: PHP/^[[33m5^[[m^O.^[[33m3^[[m^O.^[[33m3^[[m^O

Now, I haven't been able to find anything about ESC[m^O as a valid ANSI code - so I'm not quite sure what to make of it. My primitive regex for ANSI -> HTML/CSS stuff to work properly has replaced ^O with </span> and ^[[m with </span>.

The ^[[m is certainly valid - but I can't find anything to explain what the ^O is afterwards.

As this is ONLY introduced with formatting performed by emphasize_stuff_in_headers(), then it seems that this may not be correct or wanted behaviour.

Now, digging further, it seems that emphasize_stuff_in_headers() uses $off for formatting. This is set via off=$(tput sgr0).

From what I've been able to find out, it seems that a 'reset' should be done via ^[[0m - but nothing seems to mention the Ctrl-O afterwards.

I'm certainly not an ANSI expert - so this may actually be correct behaviour - but it certainly is unique to this specific function when dealing with the output of the script.

**Comment by drwetter** [comment]
Am 08/06/2016 um 03:31 PM schrieb Steven Haigh:
> Ok, so I did much more digging into this - it seems that all other areas in testssl.sh use
> something like:
> ^[[1m blah blah ^[[m
> 
> Stuff formatted by emphasize_stuff_in_headers() ends up lines like:
> ^[[33m^[[1mX-Powered-By^[[m^O: PHP/^[[33m5^[[m^O.^[[33m3^[[m^O.^[[33m3^[[m^O
> 
> Now, I haven't been able to find anything about ESC[m^O as a valid ANSI code - so I'm not quite
> sure what to make of it. My primitive regex for ANSI -> HTML/CSS stuff to work properly has
> replaced ^O with and ^[[m with .

if you want to it by yourself I would have a peek @ the source code of AHA.

In general I am not sure what you're aiming at? You want to extend testssl to produce HTML?

> The ^[[m is certainly valid - but I can't find anything to explain what the ^O is afterwards.
> 
> As this is ONLY introduced with formatting performed by emphasize_stuff_in_headers(), then it
> seems that this may not be correct or wanted behaviour.
> 
> Now, digging further, it seems that emphasize_stuff_in_headers() uses $off for formatting. This
> is set via off=$(tput sgr0).

yes, see terminfo(5).

> I'm certainly not an ANSI expert - so this may actually be correct behaviour - but it certainly
> is unique to this specific function when dealing with the output of the script.

Keep in mind that the control codes might be OS and terminal depended.

Cheers, Dirk

**Comment by CRCinAU** [comment]
Yes, I've created perl scripts to create the report output as a html email and send it off, and also via a perl CGI to do queries from a web form.

I replaced using AHA with some basic regex stuff to allow me to display the output to the web cgi as the scan runs.

Within my RHEL7 install, I don't have a terminfo man page :\

**Comment by drwetter** [comment]
Am 6. August 2016 16:25:14 MESZ, schrieb Steven Haigh <notifications@github.com>:
>Yes, I've created perl scripts to create the report output as a html
>email and send it off, and also via a perl CGI to do queries from a web
>form.
>
>I replaced using AHA with some basic regex stuff to allow me to display
>the output to the web cgi as the scan runs.

Sounds to me you're trying to reinvent the wheel. Most folks use aha. Also I would recommend to have a look at the Web frontend from @thomaspatzke.

>Within my RHEL7 install, I don't have a terminfo man page :\

GIYF...


Cheers, Dirk 


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by CRCinAU** [comment]
Ok, so looking at the output of aha, it may be valid ANSI after all - as there are no problems there.... 

I didn't pipe via AHA previously because I had a ton of buffering problems - however I've redone my web stuff in perl via the IO::Pty::Easy module - as aha seems to be happy to do line by line in this mode.

As such, this is probably a good enough fix for what I need.... I can easily pipe the email reports via aha when complete where buffering isn't an issue at all. As such, I'll close this off.
