### ISSUE TITLE
Add environment variable for certificate location

### ISSUE THREAD

**Issue by madsolar8582** [drwetter/testssl.sh#435]
It is possible to overwrite the OpenSSL location using `OPENSSL=`, would it be possible to add another environment variable to set the location of the certificates used during the tests (e.g. `/usr/local/etc/openssl/cert.pem`)?

**Comment by drwetter** [comment]
Hi @madsolar8582,

almost everything is possible .. Often the question is whether it makes sense. ;-) I am not sure what you're suggesting but maybe this #230 is what you want? 

Cheers, Dirk

**Comment by madsolar8582** [comment]
Kinda. In the `determine_trust` function, the ca bundle is set to the installation directory's `etc` [subdirectory](https://github.com/drwetter/testssl.sh/blob/b0923a1833a71c157222318f6124f227a6a2fefc/testssl.sh#L3726). However, if you're just running the script wholesale, then there is no `etc` directory. If the `ca_bundles` variable could be set via an `ENV` setting, that I would think the script would be a bit more portable.

**Comment by drwetter** [comment]
Am 6. August 2016 18:06:46 MESZ, schrieb Madison Solarana <notifications@github.com>:
>Kinda. In the `determine_trust` function, the ca bundle is set to the
>installation directory's `etc`
>[subdirectory](https://github.com/drwetter/testssl.sh/blob/b0923a1833a71c157222318f6124f227a6a2fefc/testssl.sh#L3726).
>However, if you're just running the script wholesale, then there is no
>`etc` directory. If the `ca_bundles` variable could be set via an `ENV`
>setting, that I would think the script would be a bit more portable.

Ok, got it. 

Plan for the near future is to have some code external. So at some time you won't be able to run testssl.sh wholesale.

Also my humble guess is you don't have the certificate stores supplied by testssl.sh  just by coincidence lying around elsewhere... ;-)


Cheers, Dirk 


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by drwetter** [comment]
The certificates in "$INSTALL_DIR/etc/*.pem" are needed for this particular test. ``/usr/local/etc/openssl/cert.pem`` is not sufficient. In ""$INSTALL_DIR/etc/" are certificate stores from Linux, Apple, Mozilla, MS.

What do you mean by "wholesale", from a distribution?

**Comment by madsolar8582** [comment]
As in, being able to set the env variables, then pipe the script into bash via curl without having to install the script in its entirety.

**Comment by drwetter** [comment]
Sorry @madsolar8582 : this approach is simple and cool yes, but OTOH you cannot expect then that this works as expected. 

Need to sleep over it as your suggestion after checking "$INSTALL_DIR/etc/*.pem" to have a variable as a last resort has some attraction -- as an undocumented and not supported feature.

**Comment by drwetter** [comment]
see e2023f5. Enjoy
