### ISSUE TITLE
Strict Transport Security - False positive

### ISSUE THREAD

**Issue by arvinddoraiswamy** [drwetter/testssl.sh#436]
On a client site I was using this on, they had it correctly turned on with:

_Strict-Transport-Security: max-age=28800;includeSubDomains_

For some reason though, testssl.sh came back and said:

**_Strict Transport Security    HSTS max-age is set to 0. HSTS is disabled, includeSubDomains_**

**Comment by drwetter** [comment]
thx for reporting
