### ISSUE TITLE
Howto use Protocol LDAP

### ISSUE THREAD

**Issue by notes-jj** [drwetter/testssl.sh#437]
How can I use the LDAP Protocol, I don't understand the line from the documentation. Where should i put the protocol without the starttls?

>partly mandatory parameters:
>...
>protocol                      is one of ftp,smtp,pop3,imap,xmpp,telnet,ldap (for the latter two you need e.g. the supplied openssl)

I tried with no success:

    ./testssl.sh -U serverfqdn:636 ldap
    ./testssl.sh -U ldap://serverfqdn:636
    ./testssl.sh -U ldaps://serverfqdn:636
    ./testssl.sh -U ldap://serverfqdn
    ./testssl.sh -U ldaps://serverfqdn

It's always these two error:

>  Service detected:       Couldn't determine what's running on port 636, assuming no HTTP service => skipping HTTP checks

> Fatal error: No IPv4 address for "ldap" available

**Comment by drwetter** [comment]
Am 1. August 2016 13:49:32 MESZ, schrieb notes-jj <notifications@github.com>:
>How can I use the LDAP Protocol, I don't understand the line from the
>documentation. Where should i put the protocol without the starttls?
>
>>partly mandatory parameters:
>>...
>>protocol                      is one of
>ftp,smtp,pop3,imap,xmpp,telnet,ldap (for the latter two you need e.g.
>the supplied openssl)
>
>I tried with no success:
>
>    ./testssl.sh -U serverfqdn:636 ldap
>    ./testssl.sh -U ldap://serverfqdn:636
>    ./testssl.sh -U ldaps://serverfqdn:636
>    ./testssl.sh -U ldap://serverfqdn
>    ./testssl.sh -U ldaps://serverfqdn
>

-t ldap fqdn:636

Dirk 

-- 
Sent from my mobile. Excuse the autocorrection, my brevity&typos

**Comment by notes-jj** [comment]
Ok, this is for the starttls (-t), any way to use ist with non starttls port 636 to avoid the error:  

>Service detected: Couldn't determine what's running on port 636, assuming no HTTP service => skipping HTTP checks`

**Comment by drwetter** [comment]
./testssl.sh  serverfqdn:636

**Comment by jwilleke** [comment]
LDAP supports StartTLS on the standard port 389. Is there a method to perform  StartTLS tests available?

**Comment by drwetter** [comment]
./testssl.sh -t ldap <yourhost>:389
