### ISSUE TITLE
Is testssl.sh compatible with the Windows 10 bash shell?

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#438]
Not so much an issue as well as a question.

Don't have access to a Windows 10 system yet, but since it's supposed to run the bash shell: http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

Does testssl.sh work on that?

--jeroen

**Comment by teward** [comment]
Last I saw was a few weeks ago where the bundled OpenSSL that come with this tool does not work and you have to compile it yourself per the instructions under the OpenSSL directory in this repository.  It's also slow.  But technically it "does" (though I will not testify to how effective it is not its speed, I am regurgitating info from a now closed issue ticket)

**Comment by drwetter** [comment]
see #337 and @fishouttah20

**Comment by fishouttah20** [comment]
Yep, it works with the caveats @teward mentioned.
