### ISSUE TITLE
Hangs while determining Cipher Order

### ISSUE THREAD

**Issue by typingArtist** [drwetter/testssl.sh#442]
When testing one of my services, namely a cyrus-imapd using STARTTLS, testssl.sh hangs forever when trying the Cipher Order (4th point in Testing server preferences).

Seaching for the reason, it looks as if the first attempt, connecting with SSLv2 enabled, leads to a connection lost in a bad state. If I manually issue the relevant openssl command, I see the following output and a hanging openssl process:

```
$ bin/openssl.Linux.x86_64 s_client -ssl2 -connect my_server.example.com:143 -starttls imap
CONNECTED(00000003)
^C
$
```

Note that connecting with SSLv3, which is disabled just as SSLv2, gives a sane error message and an exit. While we could raise the question whether this is a bug on my server side, handling SSLv2 improperly, or it’s a bug in testssl’s openssl binary, I think that the script should be prepared for such cases anyway.

The following patch fixes the issue, but you might prefer a better solution.

```diff
diff --git a/testssl.sh b/testssl.sh
index 1d91590..2941306 100755
--- a/testssl.sh
+++ b/testssl.sh
@@ -3604,7 +3604,7 @@ cipher_pref_check() {
                continue
           fi
           # with the supplied binaries SNI works also for SSLv2 (+ SSLv3)
-          $OPENSSL s_client $STARTTLS -"$p" $BUGS -connect $NODEIP:$PORT $PROXY $SNI </dev/null 2>$ERRFILE >$TMPFILE
+          timeout 30s $OPENSSL s_client $STARTTLS -"$p" $BUGS -connect $NODEIP:$PORT $PROXY $SNI </dev/null 2>$ERRFILE >$TMPFILE
           if sclient_connect_successful $? $TMPFILE; then
                tested_cipher=""
                proto=$(awk '/Protocol/ { print $3 }' $TMPFILE)
```

**Comment by drwetter** [comment]
Am 9. August 2016 09:44:00 MESZ, schrieb typingArtist <notifications@github.com>:
>When testing one of my services, namely a cyrus-imapd using STARTTLS,
>testssl.sh hangs forever when trying the Cipher Order (4th point in
>Testing server preferences).
>
>Seaching for the reason, it looks as if the first attempt, connecting
>with SSLv2 enabled, leads to a connection lost in a bad state. If I
>manually issue the relevant openssl command, I see the following output
>and a hanging openssl process:
>
>```
>$ bin/openssl.Linux.x86_64 s_client -ssl2 -connect
>my_server.example.com:143 -starttls imap
>CONNECTED(00000003)
>^C
>$
>```
>
>The following patch fixes the issue, but you might prefer a better
>solution.
>
>```diff
>diff --git a/testssl.sh b/testssl.sh
>index 1d91590..2941306 100755
>--- a/testssl.sh
>+++ b/testssl.sh
>@@ -3604,7 +3604,7 @@ cipher_pref_check() {
>                continue
>           fi
>        # with the supplied binaries SNI works also for SSLv2 (+ SSLv3)
>-          $OPENSSL s_client $STARTTLS -"$p" $BUGS -connect
>$NODEIP:$PORT $PROXY $SNI </dev/null 2>$ERRFILE >$TMPFILE
>+          timeout 30s $OPENSSL s_client $STARTTLS -"$p" $BUGS -connect
>$NODEIP:$PORT $PROXY $SNI </dev/null 2>$ERRFILE >$TMPFILE
>           if sclient_connect_successful $? $TMPFILE; then
>                tested_cipher=""
>                proto=$(awk '/Protocol/ { print $3 }' $TMPFILE)
>```
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/issues/442

Thx.

There's already a PR for this from Thomas. 
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by typingArtist** [comment]
You mean it’s handled in #414. Would be great to see that one merged.

**Comment by drwetter** [comment]
Am 10. August 2016 15:18:20 MESZ, schrieb typingArtist <notifications@github.com>:
>You mean it’s handled in #414. Would be great to see that one merged.


ACK.  

Can't promise for 2.8 though as it needs some tweaking and testing. 


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection
