### ISSUE TITLE
missing dnsutils not detected correctly

### ISSUE THREAD

**Issue by evook** [drwetter/testssl.sh#448]
Today I noticed on a fresh debian jessie minimal installation that the command `dig` always exits 0 even if not provided by dnsutils, resulting in the cryptic error message: "Fatal error: No IPv4 address [...]" while the real error is the lack of dig. It fails quietly exiting 0. 

```
root@hostnameplaceholder:~# dig google.de 
root@hostnameplaceholder:~#
root@hostnameplaceholder:~# dig 
root@hostnameplaceholder:~# 
root@hostnameplaceholder:~# apt-get install dnsutils
[...]
root@hostnameplaceholder:~# dig google.de

; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> google.de
[...]

```
I could reproduce it with: Linux hostnameplaceholder 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Installed by the up to date netinstall iso, downloaded today. 

While this is a debian bug, it's probably worth mentioning because I had to "dig" (pun intended) longer then I am willing to admit and others might stumble over this bug too.

**Comment by drwetter** [comment]
Hello,

thx for mentioning. Two questions out of curiosity: is there a bug filed already at Debian? And: what does ``file  $(which dig)`` return?

Cheers, Dirk
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by drwetter** [comment]
@evook : ping
