### ISSUE TITLE
thousands of "RC4-MD5 between"

### ISSUE THREAD

**Issue by digininja** [drwetter/testssl.sh#457]
I've just ran the script against 5 sites, 4 ran  OK but one has got stuck in a loop printing "RC4-MD5 between" over and over.  This is how it starts:
```
 Testing server preferences

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1
 Negotiated cipher            AES256-SHA
 Cipher order
    SSLv2:     between
RC4-MD5 between
RC4-MD5 between
RC4-MD5 between
RC4-MD5 between
```
The first time this happened I didn't notice and got over 7000 entries in the log file before it gave up and carried on, I've not left it that long since but each time I've tried it it has dumped at least a few hundred.

Any ideas what is going wrong?

I'm running the latest master branch from Github.

**Comment by digininja** [comment]
Just tried on a second machine, got exactly the same issue.

**Comment by dcooper16** [comment]
I believe that this is a problem that I encountered with servers that support SSLv2. There is a problem with the way that testssl.sh extracts information from the output of OpenSSL when SSLv2 is used.

If this is the same problem as the one I encountered, then it should be addressed by #427.  In particular, on lines 3611 and 3636 of testssl.sh change:
```
cipher=$(awk '/Cipher.*:/ { print $3 }' $TMPFILE)
```
to:
```
cipher=$(awk '/Cipher *:/ { print $3 }' $TMPFILE)
```

**Comment by drwetter** [comment]
@digininja :Thx for reporting, Could you pls give it a shot?

**Comment by digininja** [comment]
Ye, will try it later today hopefully.

**Comment by drwetter** [comment]
The current master should work

**Comment by digininja** [comment]
That fixed it, thanks

**Comment by drwetter** [comment]
thx to @dcooper16 and you for reporting!
