### ISSUE TITLE
Consider also testing ssh vulnerabilities

### ISSUE THREAD

**Issue by jpluimers** [drwetter/testssl.sh#458]
Even though SSH is very different from SSL, it is interesting to know how safe an SSH server is.

Please consider SSH support to testssl.sh or create a testssh.sh

A starter for reading could be http://security.stackexchange.com/questions/92642/logjam-hardening-openssh-and-testing-it

**Comment by drwetter** [comment]
Hi Jeroen,

the handshake is completely different. Besides one nmap script does a pretty decent job for fingerprinting crypto parameters.

Thx, Dirk
-- 
Sent from my mobile. Excuse the autocorrection, my brevity&typos

**Comment by drwetter** [comment]
Pls see here: https://nmap.org/nsedoc/scripts/ssh2-enum-algos.html

**Comment by jpluimers** [comment]
Thanks. The criteria for ``ssh2-enum-algos`` are these:

  - The ``diffie-hellman-group1-sha1`` must not appear. It only has 1024 bit.
  - The ``diffie-hellman-group14-sha1`` must appear as it is 2048 bit.

**Comment by drwetter** [comment]
there is one more SHA1 for kx and also you gotta look at more params.

Can recommend this" https://stribika.github.io/2015/01/04/secure-secure-shell.html. 

Be careful not to lock yourself out though ;-)

**Comment by jpluimers** [comment]
Thanks a lot! I'll try to summarise here later. One day (:
