### ISSUE TITLE
OCSP stapling status shown as unknown in contradiction to manual s_client check

### ISSUE THREAD

**Issue by nachtgeist** [drwetter/testssl.sh#467]
testssl.sh current master reports an unknown OCSP stapling status even for known-to-be-good apache2 virtualhosts as reported by openssl s_client (Debian/Jessie).

**s_client:**
```
$ openssl version
OpenSSL 1.0.1t  3 May 2016

$ openssl s_client -connect 78.46.72.130:443 -servername nachtgeist.eu.org -tls1_2 -tlsextdebug -status | head -n20
CONNECTED(00000003)
TLS server extension "server name" (id=0), len=0
TLS server extension "renegotiation info" (id=65281), len=1
0001 - <SPACES/NULS>
TLS server extension "EC point formats" (id=11), len=4
0000 - 03 00 01 02                                       ....
TLS server extension "session ticket" (id=35), len=0
TLS server extension "status request" (id=5), len=0
TLS server extension "heartbeat" (id=15), len=1
0000 - 01                                                .
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = nachtgeist.eu.org
verify return:1
OCSP response: 
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
    Produced At: Sep  8 10:17:00 2016 GMT
    Responses:
    Certificate ID:
```

**testssl.sh:**
```
$ testssl -S https://nachtgeist.eu.org

No mapping file found

###########################################################
    testssl       2.8rc2 from https://testssl.sh/dev/
    (1.541 2016/09/07 19:34:26)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.1t  3 May 2016" [~104 ciphers]
 on enterprise:/usr/bin/openssl
 (built: "May 15 19:23:55 2016", platform: "debian-amd64")


 Start 2016-09-12 03:58:01    -->> 78.46.72.130:443 (nachtgeist.eu.org) <<--

 further IP addresses:   2a01:4f8:120:43c7:0:5::
 rDNS (78.46.72.130):    srv05.itamservices.de.
 Service detected:       HTTP


 Testing server defaults (Server Hello) 

 TLS extensions (standard)    "server name/#0" "renegotiation info/#65281" "EC point formats/#11" "session ticket/#35" "heartbeat/#15"
 Session Tickets RFC 5077     300 seconds (PFS requires session ticket keys to be rotated <= daily)
 SSL Session ID support       yes
 TLS clock skew               random values, no fingerprinting possible 
 Signature Algorithm          SHA256 with RSA
 Server key size              RSA 4096 bits
 Fingerprint / Serial         SHA1 9B81D80C00679604B8C3C179C80B61EFBF5696CA / 03677DD93BFEDB5C22527C778CC77B8FCADE
                              SHA256 C64BCB853EB8191ADF6D9BD632C3F66817BD969B2CDCE8D65B0BF2F264F7BCEE
 Common Name (CN)             "nachtgeist.eu.org" (CN in response to request w/o SNI: "itamservices.de")
 subjectAltName (SAN)         "nachtgeist.eu.org" "www.nachtgeist.eu.org" 
 Issuer                       "Let's Encrypt Authority X3" ("Let's Encrypt" from "US")
 Trust (hostname)             Ok via SAN and CN (SNI mandatory)
 Chain of trust               "/usr/bin/etc/*.pem" cannot be found / not readable
 EV cert (experimental)       no 
 Certificate Expiration       30 >= 30 days (2016-07-14 10:35 --> 2016-10-12 10:35 +0200)
 # of certificates provided   2
 Certificate Revocation List  --
 OCSP URI                     http://ocsp.int-x3.letsencrypt.org/
 OCSP stapling                (response status unknown)


 Done 2016-09-12 03:58:07    -->> 78.46.72.130:443 (nachtgeist.eu.org) <<--
```

In the traces above the testing was done against a vhost which has a LetsEncrypt-certificate configured via SNI.

Currently, the default vhost listening on the IP has a certificate configured which is signed by a not-well-known CA. However, testssl reported the same unknown OCSP response status, when I temporarily set the LetsEncrypt cert mentioned above also for the default vhost.

**Comment by drwetter** [comment]
Sometimes the stapling reponse from the server hangs. This is not an testssl.sh problem.

I assume this is the case here. Please try again.

Admittedly I could add a remark in those cases.


-- 
Sent from my mobile. Excuse the autocorrection, my brevity&typos

**Comment by nachtgeist** [comment]
I did, several times, while fooling around with --debug=1 --log and `grep -i ocsp`-ing the tmpfiles...without success. I reproducibly, and so far without exception, receive positive responses with s_client and negative ones (i.e. no occurrence of OCSP in the tmpfiles whatsoever) with testssl as described initially.

Could you elaborate on what you mean by "hanging stapling responses"? As I understand it, either there is a stapling message sent to the client, or there isn't.

**Comment by drwetter** [comment]
I see reproducibly with testssl.sh that it is offered and it works.

For nginx I read an explanation like 1-2 yrs back which also seemed plausible on one of my hosts: https://community.qualys.com/thread/12315 where I had similar issues. That is what I meant by "hanging stapling responses". Also the first queries after restarting nginx didn't work. Don't know whether this is similar with Apache.

All I can tell you on my side it looks fine every time I run it. At the moment I do not have debug code in testssl.sh for this, sorry,

I would recommend -- if not done yet -- to have a look in the web server logs and maybe the apache stapling variables (stapling cache, timeout, ...). If there's a general issue I would expect that apache is logging this -- but can't tell for sure.

Again, the ~6 times I ran testssl on that machine, it showed that stapling worked. Have you tried from a different client?

**Comment by nachtgeist** [comment]
Thanks for the link. Makes sense, however I'm testing an apache2.4. I even temporarily set the request worker count down to 1 and tried s_client and testssl intermitently for 20 times (each). Sadly, no change here.

> I see reproducibly with testssl.sh that it is offered and it works.

Did you run the test against the hostname from this ticket's initial message?

Could you please provide me with the temp files you get generated for a positive OCSP check? Maybe working out the differences I can track this thing down...
`bash -x testssl --color=0 --debug=1 --log -S https://nachtgeist.eu.org 2>bashlog` would be ideal :)

I'll send you an owncloud URL for uploading via PM...
Thanks!

**Comment by nachtgeist** [comment]
The already merged fix for this was a little premature. I just stumbled across some weird behaviour when testing nginx (ssl *does* work on the tested domain/IP):

```
$ testssl -S https://xx.xx.xx.xx

No mapping file found

###########################################################
    testssl       2.8rc2 from https://testssl.sh/dev/
    (c6133b2 2016-09-13 13:18:30 -- 1.541)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.1t  3 May 2016" [~104 ciphers]
 on enterprise:/usr/bin/openssl
 (built: "May 15 19:23:55 2016", platform: "debian-amd64")


 Start 2016-09-15 03:44:19    -->> xx.xx.xx.xx:443 (xx.xx.xx.xx) <<--

 rDNS (78.46.72.130):    foo.bar.
 Service detected:       HTTP

Strange, no SSL/TLS protocol seems to be supported (error around line 3988)

 Testing server defaults (Server Hello) 

 TLS extensions (standard)    (none)
 Session Tickets RFC 5077     (none)
 SSL Session ID support       yes
 TLS clock skew               random values, no fingerprinting possible 

 Done 2016-09-15 03:44:21    -->> xx.xx.xx.xx:443 (xx.xx.xx.xx) <<--
```

I'll open another PR fixing this aftereffect in a minute. I'm not sure though, wheter other locations using "-nextprotoneg" require a similar fix.
