### ISSUE TITLE
\c printed out in OS X/macOS

### ISSUE THREAD

**Issue by securitygeneration** [drwetter/testssl.sh#480]
For some reason macOS appears to print out "c" everywhere, as shown in the output below. Is there a fix for this?

Thanks!

```
--> Testing protocols c(via sockets except TLS 1.2 and SPDY/NPN)

 SSLv2      cnot offered (OK)c
c SSLv3      cnot offered (OK)c
 TLS 1      coffered
 TLS 1.1    coffered
 TLS 1.2    coffered (OK)c
 SPDY/NPN   cnot offered
```

**Comment by drwetter** [comment]
Hi,

 Stange.... which version of testssl.sh and is it everywhere? 

Dirk
-- 
Sent from my mobile. Excuse the autocorrection, my brevity&typos

**Comment by securitygeneration** [comment]
Hi Dirk,

It's testssl 2.6, and it's indeed everywhere both in Terminal.app and iTerm 2 (and zsh/bash).

**Comment by drwetter** [comment]
Hi there,

sounds still awkward as others tested that on OSX ok.  Could you please check out the current master and let me know whether the error persists?

testssl.sh is getting it's final polish for 2.8 release. Besides tons of new features there were numerous bugs squashed.... so even if your bug is being addressed in 2.6. you'd probably better off with the current master.

Cheers, Dirk

**Comment by securitygeneration** [comment]
I removed and reinstalled (using brew), and it pulls it from: https://codeload.github.com/drwetter/testssl.sh/tar.gz/v2.6

Same output.

**Comment by drwetter** [comment]
@securitygeneration: could you please dl the current version from https://raw.githubusercontent.com/drwetter/testssl.sh/master/testssl.sh ?

@jpluimers or @bad: can you verify 2.6 has such a weird output?

**Comment by xvn** [comment]
yes, the same issue with macOS Sierra. Tried the debug output and it shows - 

254> out(): /usr/bin/printf -- '\033[0;35m\nNo mapping file found'

No mapping file found269> pr_litemagenta(): pr_off
296> pr_off(): [[ 2 -ne 0 ]]
296> pr_off(): out '\033[m\c'
254> out(): /usr/bin/printf -- '\033[m\c'
c270> pr_litemagentaln(): outln
255> outln(): out '\n'
254> out(): /usr/bin/printf -- '\n'

**Comment by jpluimers** [comment]
Here it works fine, but I run a quite old OS using a bash shell.

```
Darwin 13.4.0
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F1911
```

I put an AHA html dump at https://gist.github.com/bfe9f0a2120defbbd3ea7afe5f812ff8 which you can view at rawgit.com/jpluimers/bfe9f0a2120defbbd3ea7afe5f812ff8/raw/213083974b82f33bc0e4cd7c0a91e368a838439c/www.xs4all.nl-via-testssl.sh-2.6-homebrew.html

Works fine here.

**Comment by drwetter** [comment]
that d2678003fede3d4295182fff9ce80fb9cab1b5c5 should address it. Please check

**Comment by securitygeneration** [comment]
Thanks, looks fixed on my end!
