### ISSUE TITLE
Detect (and properly handle) duplicate security headers

### ISSUE THREAD

**Issue by teward** [drwetter/testssl.sh#488]
One observation I made, while beating against a private Gitlab instance, was a case where HSTS headers are duplicated, which results in 'bad' HSTS.  This appears to be the case when duplicate headers are sent from a misconfigured server.  We should also test in other 'security header' checks if there are duplicate headers being sent (such as two `X-Frame-Options` or two `X-Content-Type-Options` for example)

SSL Labs' tests caught the duplicate headers.  The testssl.sh script did not.  When using a site such as websniffer.net to sniff the headers of a site with duplicate headers, it would be good to see if the same header is being provided twice.  If the same header is being provided twice, then warnings should show up.

We also need to handle duplicate headers better, because it renders like this from current master when there's dupes (on Ubuntu 14.04):

```
 Security headers             X-Frame-Options: SAMEORIGINX-Frame-Options: SAMEORIGIN
                              X-Xss-Protection: 1; mode=block
                              X-Content-Type-Options: nosniffX-Content-Type-Options: nosniff
```

**Comment by drwetter** [comment]
For HSTS, see my comment https://github.com/drwetter/testssl.sh/issues/489#issuecomment-250898277. (Also HPKP detects multiple headers, there is a warning)

For the other security headers admittedly there's space for improvements ;-)

Thank you!

**Comment by drwetter** [comment]
``X-Frame-Options: SAMEORIGINX-Frame-Options: SAMEORIGIN`` look really ugly. 

Thus priority changed.

**Comment by drwetter** [comment]
see 19b63aa8a9880a7a96afe46f2e7d311398ec1cee
