### ISSUE TITLE
HSTS Tests: Invalid Positive Result in presence of multiple 'Strict-Transport-Security' headers

### ISSUE THREAD

**Issue by teward** [drwetter/testssl.sh#489]
See #488 (related).  When there are more than one 'Strict-Transport-Security' header, HSTS checks should trigger with a warning, rather than accepting more than one header.

**Comment by drwetter** [comment]
Thank you @teward,

there IS a an output but not  a warning, see attached.
![screenshot_20161001_093136](https://cloud.githubusercontent.com/assets/8036727/19012572/0e909a4c-87ba-11e6-8601-11ef55dba8f3.png)

Is that what you mean -- color=>brown -- or is the detection in your case not working?

**Comment by teward** [comment]
I think it's two cases here, in reply to your question.

(1) The brown is not easily readable where specified; the patch that closed this issue makes it more readable.

(2) The second Strict-Transport-Security is being eaten somewhere along the line between my testing server and my private gitlab instance.  Going internal to my net, I can reproduce the detection of the duplicate headers by forcing nginx to be evil with headers, but while SSLLabs sees duplicate headers, testssl.sh and curl don't.  *shrugs*

Making the warning more clear with the color=> brown for medium severity alerts makes it more readable, though.

**Comment by drwetter** [comment]
Am 1. Oktober 2016 10:28:06 MESZ, schrieb Thomas Ward <notifications@github.com>:
>I think it's two cases here, in reply to your question.

[..]

>(2) The second Strict-Transport-Security is being eaten somewhere along
>the line between my testing server and my private gitlab instance. 
>Going internal to my net, I can reproduce the detection of the
>duplicate headers by forcing nginx to be evil with headers, but while
>SSLLabs sees duplicate headers, testssl.sh and curl don't.  *shrugs*

Ok, but this seems more a client side issue, right? 

Feel free to experiment with borken.testssl.sh. No creatures eating something in between...

I could also show the second line in testssl.sh but not in the current version. File an issue if you think it's important for 2.9dev.

>Making the warning more clear with the color=> brown for medium
>severity alerts makes it more readable, though.

Thanks for the feedback. 


Cheers, Dirk 




-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection
