### ISSUE TITLE
append not working for CSV

### ISSUE THREAD

**Issue by fishouttah20** [drwetter/testssl.sh#490]
I was trying to output json and csv at the same time and assumed it was an issue with doing both, but after having run a command with just csv output, it doesn't appear to be appending results to the file, but each host overwrites the results of the last one. Json append works fine. Running a command similar to:

./testssl.sh --openssl /path/openssl.Linux.x86_64 -f -p -y -Y -S -P -H -U -B -I -R -C -T -O -Z -F -A -J -D -s -4 --csvfile /path/sept-file.csv --append --openssl-timeout 15 --file /path/sept-input.txt

openssl-timeout was only used on 2.9dev and I tried both 2.8 and 2.9 with similar results.

I also noticed on 2.9dev that the last host in the --file didn't get scanned. I haven't run all the way through a scan on 2.8 to confirm if this is the case in both. 

Running on UBUNTU 15.x

On last thing, I don't have to specify the path to openssl on 2.8. When I run 2.9dev with -b it doesn't require the path either, but when running with --file it errors out not being able to find openssl, which is why i had to specify it above.

**Comment by drwetter** [comment]
Hello @fishouttah20 ,

thx for reporting.

Please only one bug per issue.

>I also noticed on 2.9dev that the last host in the --file didn't get scanned. I haven't run all the way 
through a scan on 2.8 to confirm if this is the case in both. 

couldn't reproduce it

> On last thing, I don't have to specify the path to openssl on 2.8. When I run 2.9dev with -b it doesn't require the path either, but when running with --file it errors out not being able to find openssl, which is why i had to specify it above.

couldn't reproduce it either

Cheers, Dirk
