### ISSUE TITLE
http2 support

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#50]
see e.g https://http2.golang.org/

**Comment by drwetter** [comment]
Even with old Debian wheezy.openssl shows google.de is offering h2-15:

    myprompt%: /testssl.sh -y google.de          
    
    #########################################################
    testssl.sh v2.3dev  (https://testssl.sh)
    ($Id: testssl.sh,v 1.201 2015/03/09 07:07:40 dirkw Exp $)

       This program is free software. Redistribution + 
       modification under GPLv2 is permitted. 
       USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!
    
     Note: you can only check the server with what is
     available (ciphers/protocols) locally on your machine!
     #########################################################
    
     Using "OpenSSL 1.0.1e 11 Feb 2013" [~111 ciphers] on
     XXXXX:/usr/bin/openssl
     (built: "Jan  8 21:12:53 2015", platform: "debian-amd64")
    
    
    Testing now (2015-03-16 10:49) ---> 74.125.136.94:443 (google.de) <---
    
     further IP addresses:   2a00:1450:4013:c01::5e
     rDNS (74.125.136.94):   ea-in-f94.1e100.net
     Service detected:       HTTP
    
     SPDY/NPN   h2-15, h2-14, spdy/3.1, spdy/3, http/1.1 (advertised)

    Done now (2015-03-16 10:50) ---> 74.125.136.94:443 (google.de) <---


With OpenSSL 1.0.2 that doesn't change (ALPN support?):

    myprompt% ./openssl64-1.0.2-static version                                        
    OpenSSL 1.0.2 22 Jan 2015
    myprompt% ./openssl64-1.0.2-static s_client -connect google.de:443 -nextprotoneg "" </dev/null       10:55:19
    CONNECTED(00000003)
    Protocols advertised by server: h2-15, h2-14, spdy/3.1, spdy/3, http/1.1
    [..]

**Comment by teward** [comment]
I see this was closed, do we intend to not include HTTP/2 ?
