### ISSUE TITLE
Question to Mac users

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#510]
Does this work on your (native) bash?

```
a="TESTSSL"
echo "${a,,}"

b="testssl"
echo "${a^^}"
```

**Comment by AlGreed** [comment]
MacBook Pro
```
olno-mac:~ root# /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

olno-mac:~ root# a="TESTSSL"
olno-mac:~ root# echo "${a,,}"
-sh: ${a,,}: bad substitution
olno-mac:~ root# b="testssl"
olno-mac:~ root# echo "${a^^}"
-sh: ${a^^}: bad substitution
```

**Comment by okoeroo** [comment]
To complete things, and my bash is from MacPorts:

bash-3.2$ which bash
/opt/local/bin/bash
bash-3.2$ bash --version
GNU bash, version 4.3.46(1)-release (x86_64-apple-darwin15.4.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
bash-3.2$
bash-3.2$ a="TESTSSL"
bash-3.2$ echo "${a,,}"
bash: ${a,,}: bad substitution
bash-3.2$
bash-3.2$ b="testssl"
bash-3.2$ echo "${a^^}"
bash: ${a^^}: bad substitution
bash-3.2$

**Comment by drwetter** [comment]
Ok, thanks @AlGreed & @okoeroo . More complicated than I thought.

Linux:
```
e > a="TESTSSL"
me > echo "${a,,}"
testssl
me > 
me > b="testssl"
me > echo "${a^^}"
TESTSSL
me > bash --version
GNU bash, version 4.1.10(1)-release (x86_64-suse-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
me > 
```
I realize under FreeBSD 9.X it doesn't work either (bash 4.3.33(0)-release)

**Comment by drwetter** [comment]
FYI: d698005313a9e79017c50392fbff483048386eb7#diff-2b772c01e86977452d2db64b3031f913
