### ISSUE TITLE
Secure Client-Initiated Renegotiation - lower importance

### ISSUE THREAD

**Issue by non7top** [drwetter/testssl.sh#532]
I suggest lowering the importance of this problem from red to yellow.
ssllabs claims this problem is not that critical as of now:
```Removed the recommendation to disable client-initiated renegotiation. Modern software does this anyway, and it might be impossible or difficult to disable it with something older. At the same time, the DoS vector isn't particularly strong. Overall, I feel it's better to spend available resources fixing something else.```

https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices

**Comment by drwetter** [comment]
Thx, @non7top .

We had some discussions here (https://github.com/drwetter/testssl.sh/issues/234#ref-issue-176097482) and myself on the ssllabs site @ github (https://github.com/ssllabs/ssllabs-scan/issues/410#issuecomment-253046623).

I just have a different opinion on this as Ivan which is simply that the DoS vector is strong enough to raise the hand. Mostly older systems are affected. If somebody can convince me that nowadays the old THC tool hasn't an impact on a vulnerable machine or the impact is not as big as I experienced ~4 years ago on apache (IIRC) I am happy to relax the warning. 

For STARTTLS enabled protocols it has been lowered though as the comparable tool hasn't shown a big impact. Also the effect seems to be depended on daemon used, for same protocol.
