### ISSUE TITLE
Browser Simulation includes ciphers not detected as enabled by host

### ISSUE THREAD

**Issue by fishouttah20** [drwetter/testssl.sh#539]
Android 2.3.7, IE 8 XP, Java 6u45 all list RC4-SHA as the negotiated cipher when RC4 is not offered by the server. In fact, no cipher without forward secrecy is offered. I'll send the test server domain name via Twitter DM.

This is the case in both 2.8 rc3 and 2.9dev latest.

**Comment by fishouttah20** [comment]
Found similar issue with ssllabs and looks like this is due to SNI and browsers without SNI support being able to negotiate RC4 with the primary host.

https://github.com/ssllabs/ssllabs-scan/issues/302

Would be a nice to have to alert on this elsewhere in the report, connecting to the host with SNI disabled and alerting on any cipher discrepancies.

Closing.

**Comment by drwetter** [comment]
Hi there @fishouttah20 ,

the clients you mentioned do not support SNI, see https://www.ssabs.com/ssltest/clients.html. So if such a client connects, it speaks the to default host (as you indicated) .That's what testssl is supposed to do too.

> Would be a nice to have to alert on this elsewhere in the report, connecting to the host with SNI disabled and alerting on any cipher discrepancies.

I was curious and wanted to check against the host you gave me. However that doesn't resolve anymore :-/   . caseking.de and www.lidl-voyages.ch look ok wgen comparing the -e and -c output.

Cheers, Ditk

**Comment by fishouttah20** [comment]
As a test server it might have been down. I tried just now and it was up. Twitter also seems to replace the link but I double checked and the name was right in my DM. Here is sanitised output of an -e and -c run:

$ ./testssl.sh -e xxx.co.uk

###########################################################
    testssl.sh       2.9dev from https://testssl.sh/dev/
    (f90da83 2016-11-30 07:55:54 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on xxx:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")


 Start 2016-12-01 00:18:22    -->>  <<--

 rDNS (xxx):    xxx
 Service detected:       HTTP


 Testing 359 via OpenSSL and sockets against the server, ordered by encryption strength 

Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.  Encryption Bits     Cipher Suite Name (RFC)
---------------------------------------------------------------------------------------------------------------------------
 xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH 256   AESGCM    256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384              
 xc028   ECDHE-RSA-AES256-SHA384           ECDH 256   AES       256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384              
 xc014   ECDHE-RSA-AES256-SHA              ECDH 256   AES       256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                 
 x9f     DHE-RSA-AES256-GCM-SHA384         DH 2048    AESGCM    256      TLS_DHE_RSA_WITH_AES_256_GCM_SHA384                
 x6b     DHE-RSA-AES256-SHA256             DH 2048    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256                
 x39     DHE-RSA-AES256-SHA                DH 2048    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA                   
 x9d     AES256-GCM-SHA384                 RSA        AESGCM    256      TLS_RSA_WITH_AES_256_GCM_SHA384                    
 x3d     AES256-SHA256                     RSA        AES       256      TLS_RSA_WITH_AES_256_CBC_SHA256                    
 x35     AES256-SHA                        RSA        AES       256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 xc02f   ECDHE-RSA-AES128-GCM-SHA256       ECDH 256   AESGCM    128      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256              
 xc027   ECDHE-RSA-AES128-SHA256           ECDH 256   AES       128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256              
 xc013   ECDHE-RSA-AES128-SHA              ECDH 256   AES       128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                 
 x9e     DHE-RSA-AES128-GCM-SHA256         DH 2048    AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256                
 x67     DHE-RSA-AES128-SHA256             DH 2048    AES       128      TLS_DHE_RSA_WITH_AES_128_CBC_SHA256                
 x33     DHE-RSA-AES128-SHA                DH 2048    AES       128      TLS_DHE_RSA_WITH_AES_128_CBC_SHA                   
 x9c     AES128-GCM-SHA256                 RSA        AESGCM    128      TLS_RSA_WITH_AES_128_GCM_SHA256                    
 x3c     AES128-SHA256                     RSA        AES       128      TLS_RSA_WITH_AES_128_CBC_SHA256                    
 x2f     AES128-SHA                        RSA        AES       128      TLS_RSA_WITH_AES_128_CBC_SHA                       
 xc012   ECDHE-RSA-DES-CBC3-SHA            ECDH 256   3DES      168      TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA                
 x16     EDH-RSA-DES-CBC3-SHA              DH 2048    3DES      168      TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA                  
 x0a     DES-CBC3-SHA                      RSA        3DES      168      TLS_RSA_WITH_3DES_EDE_CBC_SHA                      


 Done 2016-12-01 00:18:34    -->>  <<--
----------------------------------------------------------------------------------

 $ ./testssl.sh -c xxx.co.uk

###########################################################
    testssl.sh       2.9dev from https://testssl.sh/dev/
    (f90da83 2016-11-30 07:55:54 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on xxx:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")


 Start 2016-12-01 00:18:48    -->>  <<--

 rDNS (xxx):    xxx
 Service detected:       HTTP


 Running browser simulations via sockets (experimental) 

 Android 2.3.7                 TLSv1.0 RC4-SHA
 Android 4.0.4                 TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Android 4.1.1                 TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Android 4.2.2                 TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Android 4.3                   TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Android 4.4.2                 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Android 5.0.0                 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Baidu Jan 2015                TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 BingPreview Jan 2015          TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Chrome 47 / OSX               TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Firefox 31.3.0ESR / Win7      TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Firefox 42 OS X               TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 GoogleBot Feb 2015            TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 IE 6 XP                       No connection
 IE 7 Vista                    TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 IE 8 XP                       TLSv1.0 RC4-SHA
 IE 8-10 Win 7                 TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 IE 11 Win 7                   TLSv1.2 DHE-RSA-AES128-GCM-SHA256, 2048 bit DH, FS
 IE 11 Win 8.1                 TLSv1.2 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 IE 10 Win Phone 8.0           TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 IE 11 Win Phone 8.1           TLSv1.2 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 IE 11 Win Phone 8.1 Update    TLSv1.2 DHE-RSA-AES128-GCM-SHA256, 2048 bit DH, FS
 IE 11 Win 10                  TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Edge 13 Win 10                TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Edge 13 Win Phone 10          TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Java 6u45                     TLSv1.0 RC4-SHA
 Java 7u25                     TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Java 8u31                     TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 OpenSSL 0.9.8y                TLSv1.0 DHE-RSA-AES128-SHA, 2048 bit DH, FS
 OpenSSL 1.0.1l                TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 OpenSSL 1.0.2e                TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Safari 5.1.9 OS X 10.6.8      TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Safari 6 iOS 6.0.1            TLSv1.2 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Safari 6.0.4 OS X 10.8.4      TLSv1.0 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Safari 7 iOS 7.1              TLSv1.2 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Safari 7 OS X 10.9            TLSv1.2 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Safari 8 iOS 8.4              TLSv1.2 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Safari 8 OS X 10.10           TLSv1.2 ECDHE-RSA-AES128-SHA, 256 bit ECDH, FS
 Safari 9 iOS 9                TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Safari 9 OS X 10.11           TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH, FS
 Apple ATS 9 iOS 9             TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 256 bit ECDH, FS

 Done 2016-12-01 00:19:38    -->>  <<--
