### ISSUE TITLE
Testing server preferences and NPN

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#543]
I'm working on developing a sockets implementation of `cipher_pref_check()`. I think I have the first part of the function working, which handles the different SSL/TLS protocols, but I am trying to understand the purpose of the tests in the second part of the function.

testssl.sh uses the `-nextprotoneg` option of `$OPENSSL s_client` in several places. I understand its use in `determine_tls_extensions()` and `get_server_certificate()`, where the purpose is to determine whether the server supports the extension, and I understand its use in `run_spdy()`, where the purpose is to determine the list of protocols supported by the server. However, I don't understand its use in `run_server_preference()` or `cipher_pref_check()`.

In `run_server_preference()` and `cipher_pref_check()`, the code seems to treat the protocols advertised by the server in response to the NPN extension as if they just different TLS protocols (as are SSLv3, TLSv1, TLSv1.1, and TLSv1.2), and so checks for the negotiated cipher or cipher order for each NPN protocol supported by the server in addition to checking for each TLS protocol. In all of the tests that I have run, however, the response for each NPN protocol is exactly the same as for TLSv1.2, so I don't understand the reason for including these tests. Why not just list the advertised NPN protocols under " Testing protocols", but not mention them at all under "Testing server preferences"?

When the `-nextprotoneg` option is provided to OpenSSL, an empty NPN extension is sent to the server and, if the server supports the extension, the server sends back a list of the protocols that it supports. So, the server never sees the value provided to the `-nextprotoneg` option, and so it cannot affect the cipher that it chooses. In theory the server could choose a different cipher depending on whether or not the NPN extension is present in the ClientHello, but I haven't encountered any server that does.

When the OpenSSL client receives the response from the server, it uses the response to choose the next protocol, but it doesn't abort the connection if there is no protocol in common between the ones provided on the command line and the ones listed by the server, which is the reason that the connection can succeed even if the protocols offered by the server is empty. Here is the relevant text from the OpenSSL source code:

```
/*
 * SSL_select_next_proto implements the standard protocol selection. It is
 * expected that this function is called from the callback set by
 * SSL_CTX_set_next_proto_select_cb. The protocol data is assumed to be a
 * vector of 8-bit, length prefixed byte strings. The length byte itself is
 * not included in the length. A byte string of length 0 is invalid. No byte
 * string may be truncated. The current, but experimental algorithm for
 * selecting the protocol is: 1) If the server doesn't support NPN then this
 * is indicated to the callback. In this case, the client application has to
 * abort the connection or have a default application level protocol. 2) If
 * the server supports NPN, but advertises an empty list then the client
 * selects the first protocol in its list, but indicates via the API that this
 * fallback case was enacted. 3) Otherwise, the client finds the first
 * protocol in the server's list that it supports and selects this protocol.
 * This is because it's assumed that the server has better information about
 * which protocol a client should use. 4) If the client doesn't support any
 * of the server's advertised protocols, then this is treated the same as
 * case 2. It returns either OPENSSL_NPN_NEGOTIATED if a common protocol was
 * found, or OPENSSL_NPN_NO_OVERLAP if the fallback case was reached.
 */
```

So, I would recommend deleting the NPN related tests from `run_server_preference()` and `cipher_pref_check()`, as the tests don't seem to add anything.

**Comment by drwetter** [comment]
> In all of the tests that I have run, however, the response for each NPN protocol is exactly the same as for TLSv1.2

Subtle differences only, Facebook:
```
    TLSv1.2:   ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-ECDSA-CHACHA20-POLY1305-OLD ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384 
               ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA ECDHE-RSA-CHACHA20-POLY1305 ECDHE-RSA-CHACHA20-POLY1305-OLD ECDHE-RSA-AES128-GCM-SHA256 
               ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-SHA AES128-GCM-SHA256 AES256-GCM-SHA384 AES128-SHA AES256-SHA 
               ECDHE-ECDSA-DES-CBC3-SHA ECDHE-RSA-DES-CBC3-SHA DES-CBC3-SHA ECDHE-ECDSA-RC4-SHA ECDHE-RSA-RC4-SHA RC4-SHA 
    h2:        ECDHE-ECDSA-CHACHA20-POLY1305-OLD ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA 
               ECDHE-RSA-CHACHA20-POLY1305-OLD ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-SHA 
               AES128-GCM-SHA256 AES256-GCM-SHA384 AES128-SHA AES256-SHA ECDHE-ECDSA-DES-CBC3-SHA ECDHE-RSA-DES-CBC3-SHA DES-CBC3-SHA ECDHE-ECDSA-RC4-SHA 
               ECDHE-RSA-RC4-SHA RC4-SHA 
```
testssl.net (cloudflare):
```
    TLSv1.2:   ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-ECDSA-CHACHA20-POLY1305-OLD ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES128-SHA256 
               ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES256-SHA384 ECDHE-ECDSA-AES256-SHA 
    h2:        ECDHE-ECDSA-CHACHA20-POLY1305-OLD ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES128-SHA256 ECDHE-ECDSA-AES128-SHA 
               ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES256-SHA384 ECDHE-ECDSA-AES256-SHA 
```

**Comment by dcooper16** [comment]
Hi Dirk,

The differences you're seeing between TLSv1.2 and h2 for Facebook and Cloudflare are just because the testing for the two are different. `cipher_pref_check()` is using OpenSSL and `tls_sockets()` for TLSv1.2, but it is only using OpenSSL for h2. So, the TLSv1.2 list includes some ciphers that aren't supported by your OpenSSL, but that were found using `tls_sockets()`.

Note also that the code in `cipher_pref_check()` doesn't check for `SERVER_SIZE_LIMIT_BUG`. So, that could be another source for testssl.sh to report different results for TLSv1.2 versus the NPN protocols.

**Comment by drwetter** [comment]
Hi David,

sure, you're right. Looks I have another task for the weekend.

Cheers, Dirk

Am 24.03.2017 um 20:01 schrieb David Cooper:
