### ISSUE TITLE
How to use /etc/hosts settings?

### ISSUE THREAD

**Issue by natv** [drwetter/testssl.sh#549]
I need to directly scan a hostname that is behind a WAP, so I set the direct IPs in /etc/hosts

When I ping the hostname, I get the IP I want it to scan, but when I run the script it picks up the real IP.

I realize that nslookup & dig ignore /etc/hosts and that this is why, but is there any way (or any advice) on easily modifying the script or something in linux to easily force a particular hostname to resolve to a particular IP  (easily = temporarily)

**Comment by drwetter** [comment]
Oh, thanks for the filing this issue! Please try again.

OT: ``/testssl.sh --ip=<IPADRESS> <HOSTNAME>`` always works otherwise but now as it is fixed should not be needed.
