### ISSUE TITLE
Definitions of cipher lists in run_std_cipherlists()

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#554]
Hi @drwetter ,

I'm working to try to modify `run_std_cipherlists()` to use sockets, and I have a question about the definitions of the lists. Some are straightforward, but I am unclear about others.

```
     std_cipherlists 'NULL:eNULL'                       " Null Ciphers             " 1 "NULL"
```
The "Null Ciphers" list is easy; it is just those for which "Enc=NULL."

```
     std_cipherlists 'aNULL'                            " Anonymous NULL Ciphers   " 1 "aNULL"
```
"Anonymous NULL Ciphers" is those for which "Au=None."
```
     std_cipherlists 'ADH'                              " Anonymous DH Ciphers     " 1 "ADH"
```

 "Anonymous DH Ciphers" is those for which "Au=None" and "Kx=DH" (rather than "Kx=ECDH") 

```
     std_cipherlists 'EXPORT40'                         " 40 Bit encryption        " 1 "EXPORT40"
```
"40 Bit encryption" is those for which the "Enc=..." contains "(40)."

```
     std_cipherlists 'EXPORT56'                         " 56 Bit encryption        " 1 "EXPORT56"
```

This is the first difficult one, since 'EXPORT56' is not the same as ciphers with 56-bit encryption. Should the list be all ciphers that use 56-bit encryption, as the text that is displayed in the output implies, or only those that use 56-bit encryption that are marked as "export"?

```
> ./openssl.Linux.x86_64.krb5 ciphers -V EXPORT56
          0x00,0x63 - EXP1024-DHE-DSS-DES-CBC-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=DES(56)   Mac=SHA1 export
          0x00,0x62 - EXP1024-DES-CBC-SHA     SSLv3 Kx=RSA(1024) Au=RSA  Enc=DES(56)   Mac=SHA1 export
          0x00,0x61 - EXP1024-RC2-CBC-MD5     SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC2(56)   Mac=MD5  export
          0x00,0x65 - EXP1024-DHE-DSS-RC4-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x64 - EXP1024-RC4-SHA         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x60 - EXP1024-RC4-MD5         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=MD5  export

> ./openssl.Linux.x86_64.krb5 ciphers -V ALL:COMPLEMENTOFALL | grep "(56)" 
          0x00,0x63 - EXP1024-DHE-DSS-DES-CBC-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=DES(56)   Mac=SHA1 export
          0x00,0x15 - EDH-RSA-DES-CBC-SHA     SSLv3 Kx=DH       Au=RSA  Enc=DES(56)   Mac=SHA1
          0x00,0x12 - EDH-DSS-DES-CBC-SHA     SSLv3 Kx=DH       Au=DSS  Enc=DES(56)   Mac=SHA1
          0x00,0x0F - DH-RSA-DES-CBC-SHA      SSLv3 Kx=DH/RSA   Au=DH   Enc=DES(56)   Mac=SHA1
          0x00,0x0C - DH-DSS-DES-CBC-SHA      SSLv3 Kx=DH/DSS   Au=DH   Enc=DES(56)   Mac=SHA1
          0x00,0x1A - ADH-DES-CBC-SHA         SSLv3 Kx=DH       Au=None Enc=DES(56)   Mac=SHA1
          0x00,0x62 - EXP1024-DES-CBC-SHA     SSLv3 Kx=RSA(1024) Au=RSA  Enc=DES(56)   Mac=SHA1 export
          0x00,0x09 - DES-CBC-SHA             SSLv3 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=SHA1
          0x00,0x61 - EXP1024-RC2-CBC-MD5     SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC2(56)   Mac=MD5  export
     0x06,0x00,0x40 - DES-CBC-MD5             SSLv2 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=MD5 
          0x00,0x1E - KRB5-DES-CBC-SHA        SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(56)   Mac=SHA1
          0x00,0x22 - KRB5-DES-CBC-MD5        SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(56)   Mac=MD5 
          0x00,0x65 - EXP1024-DHE-DSS-RC4-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x64 - EXP1024-RC4-SHA         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x60 - EXP1024-RC4-MD5         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=MD5  export
```

```
     std_cipherlists 'LOW:!ADH'                         " Low (<=64 Bit)           " 1 "LOW"
```
Should "Low (<=64 Bit)" be all ciphers with at most 64-bit encryption? Is the idea that "56 Bit encryption" is actually only export ciphers with 56-bit encryption and "Low (<=64 Bit)" is those ciphers with <=64-bit encryption that are included in an earlier list (40-bit encryption, 56-bit export encryption, Null, or anonymous)?

```
> ./openssl.Linux.x86_64.krb5 ciphers -V "LOW:\!ADH" 
     0x08,0x00,0x80 - RC4-64-MD5              SSLv2 Kx=RSA      Au=RSA  Enc=RC4(64)   Mac=MD5 
          0x00,0x15 - EDH-RSA-DES-CBC-SHA     SSLv3 Kx=DH       Au=RSA  Enc=DES(56)   Mac=SHA1
          0x00,0x12 - EDH-DSS-DES-CBC-SHA     SSLv3 Kx=DH       Au=DSS  Enc=DES(56)   Mac=SHA1
          0x00,0x0F - DH-RSA-DES-CBC-SHA      SSLv3 Kx=DH/RSA   Au=DH   Enc=DES(56)   Mac=SHA1
          0x00,0x0C - DH-DSS-DES-CBC-SHA      SSLv3 Kx=DH/DSS   Au=DH   Enc=DES(56)   Mac=SHA1
          0x00,0x09 - DES-CBC-SHA             SSLv3 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=SHA1
     0x06,0x00,0x40 - DES-CBC-MD5             SSLv2 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=MD5 
          0x00,0x1E - KRB5-DES-CBC-SHA        SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(56)   Mac=SHA1
          0x00,0x22 - KRB5-DES-CBC-MD5        SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(56)   Mac=MD5

> ./openssl.Linux.x86_64.krb5 ciphers -V ALL:COMPLEMENTOFALL:@STRENGTH (with those <= 64 extracted)
     0x08,0x00,0x80 - RC4-64-MD5              SSLv2 Kx=RSA      Au=RSA  Enc=RC4(64)   Mac=MD5 
          0x00,0x63 - EXP1024-DHE-DSS-DES-CBC-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=DES(56)   Mac=SHA1 export
          0x00,0x15 - EDH-RSA-DES-CBC-SHA     SSLv3 Kx=DH       Au=RSA  Enc=DES(56)   Mac=SHA1
          0x00,0x12 - EDH-DSS-DES-CBC-SHA     SSLv3 Kx=DH       Au=DSS  Enc=DES(56)   Mac=SHA1
          0x00,0x0F - DH-RSA-DES-CBC-SHA      SSLv3 Kx=DH/RSA   Au=DH   Enc=DES(56)   Mac=SHA1
          0x00,0x0C - DH-DSS-DES-CBC-SHA      SSLv3 Kx=DH/DSS   Au=DH   Enc=DES(56)   Mac=SHA1
          0x00,0x1A - ADH-DES-CBC-SHA         SSLv3 Kx=DH       Au=None Enc=DES(56)   Mac=SHA1
          0x00,0x62 - EXP1024-DES-CBC-SHA     SSLv3 Kx=RSA(1024) Au=RSA  Enc=DES(56)   Mac=SHA1 export
          0x00,0x09 - DES-CBC-SHA             SSLv3 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=SHA1
          0x00,0x61 - EXP1024-RC2-CBC-MD5     SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC2(56)   Mac=MD5  export
     0x06,0x00,0x40 - DES-CBC-MD5             SSLv2 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=MD5 
          0x00,0x1E - KRB5-DES-CBC-SHA        SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(56)   Mac=SHA1
          0x00,0x22 - KRB5-DES-CBC-MD5        SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(56)   Mac=MD5 
          0x00,0x65 - EXP1024-DHE-DSS-RC4-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x64 - EXP1024-RC4-SHA         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x60 - EXP1024-RC4-MD5         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=MD5  export
          0x00,0x14 - EXP-EDH-RSA-DES-CBC-SHA SSLv3 Kx=DH(512)  Au=RSA  Enc=DES(40)   Mac=SHA1 export
          0x00,0x11 - EXP-EDH-DSS-DES-CBC-SHA SSLv3 Kx=DH(512)  Au=DSS  Enc=DES(40)   Mac=SHA1 export
          0x00,0x0E - EXP-DH-RSA-DES-CBC-SHA  SSLv3 Kx=DH/RSA   Au=DH   Enc=DES(40)   Mac=SHA1 export
          0x00,0x0B - EXP-DH-DSS-DES-CBC-SHA  SSLv3 Kx=DH/DSS   Au=DH   Enc=DES(40)   Mac=SHA1 export
          0x00,0x19 - EXP-ADH-DES-CBC-SHA     SSLv3 Kx=DH(512)  Au=None Enc=DES(40)   Mac=SHA1 export
          0x00,0x08 - EXP-DES-CBC-SHA         SSLv3 Kx=RSA(512) Au=RSA  Enc=DES(40)   Mac=SHA1 export
          0x00,0x06 - EXP-RC2-CBC-MD5         SSLv3 Kx=RSA(512) Au=RSA  Enc=RC2(40)   Mac=MD5  export
     0x04,0x00,0x80 - EXP-RC2-CBC-MD5         SSLv2 Kx=RSA(512) Au=RSA  Enc=RC2(40)   Mac=MD5  export
          0x00,0x27 - EXP-KRB5-RC2-CBC-SHA    SSLv3 Kx=KRB5     Au=KRB5 Enc=RC2(40)   Mac=SHA1 export
          0x00,0x26 - EXP-KRB5-DES-CBC-SHA    SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(40)   Mac=SHA1 export
          0x00,0x2A - EXP-KRB5-RC2-CBC-MD5    SSLv3 Kx=KRB5     Au=KRB5 Enc=RC2(40)   Mac=MD5  export
          0x00,0x29 - EXP-KRB5-DES-CBC-MD5    SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(40)   Mac=MD5  export
          0x00,0x17 - EXP-ADH-RC4-MD5         SSLv3 Kx=DH(512)  Au=None Enc=RC4(40)   Mac=MD5  export
          0x00,0x03 - EXP-RC4-MD5             SSLv3 Kx=RSA(512) Au=RSA  Enc=RC4(40)   Mac=MD5  export
     0x02,0x00,0x80 - EXP-RC4-MD5             SSLv2 Kx=RSA(512) Au=RSA  Enc=RC4(40)   Mac=MD5  export
          0x00,0x28 - EXP-KRB5-RC4-SHA        SSLv3 Kx=KRB5     Au=KRB5 Enc=RC4(40)   Mac=SHA1 export
          0x00,0x2B - EXP-KRB5-RC4-MD5        SSLv3 Kx=KRB5     Au=KRB5 Enc=RC4(40)   Mac=MD5  export
          0xC0,0x10 - ECDHE-RSA-NULL-SHA      SSLv3 Kx=ECDH     Au=RSA  Enc=None      Mac=SHA1
          0xC0,0x06 - ECDHE-ECDSA-NULL-SHA    SSLv3 Kx=ECDH     Au=ECDSA Enc=None      Mac=SHA1
          0xC0,0x15 - AECDH-NULL-SHA          SSLv3 Kx=ECDH     Au=None Enc=None      Mac=SHA1
          0xC0,0x0B - ECDH-RSA-NULL-SHA       SSLv3 Kx=ECDH/RSA Au=ECDH Enc=None      Mac=SHA1
          0xC0,0x01 - ECDH-ECDSA-NULL-SHA     SSLv3 Kx=ECDH/ECDSA Au=ECDH Enc=None      Mac=SHA1
          0x00,0x3B - NULL-SHA256             TLSv1.2 Kx=RSA      Au=RSA  Enc=None      Mac=SHA256
          0x00,0x02 - NULL-SHA                SSLv3 Kx=RSA      Au=RSA  Enc=None      Mac=SHA1
          0x00,0x01 - NULL-MD5                SSLv3 Kx=RSA      Au=RSA  Enc=None      Mac=MD5 
     0x00,0x00,0x00 - NULL-MD5                SSLv2 Kx=RSA(512) Au=RSA  Enc=None      Mac=MD5  export
```

**Comment by drwetter** [comment]
Generally/historically the original idea was to just test what openssl understands by ``openssl ciphers [-V|-v] <cipherstring>, see ciphers(1). 

For EXPORT56: Yes, there's an inconsistency in the output wrt to what is actually tested. I guess that should be adjusted so that it is being tested what the output indicates. For 40 Bit and EXPORT40 bit I see not difference -- with the binary provided at least.

(EXPORT should just stay EXPORT).

For LOW I am wondering whether this test is needed in addition? Is there anything which hasn't been covered by the previous test?

**Comment by dcooper16** [comment]
Okay, as noted in #573, I created a PR that extracts from cipher-mapping.txt the same ciphers as OpenSSL uses for each of the tests. Below is a description of each of the cipher lists and my comments on them.

It doesn't matter that much to me how these lists are defined, as long as the `$OPENSSL` and `tls_sockets()` versions are consistent. For my purposes, I need to compare the ciphers implemented by the server against SP 800-52.

`'NULL:eNULL'                       " Null Ciphers             "   1 "NULL"`
* Enc=None
* Okay

`'aNULL'                            " Anonymous NULL Ciphers   "   1 "aNULL"`
* Au!=NULL
* Okay

`'ADH'                              " Anonymous DH Ciphers     "   1 "ADH"`
* TLS cipher name is TLS_DH_anon_*
* Okay, but this is just the previous one minus the anonymous ECDH ciphers.

EXPORT40'                         " 40 Bit encryption        "   1 "EXPORT40"`
* cipher strength is 40 (all such ciphers are "export")
* Okay

`'EXPORT56'                         " 56 Bit encryption        "   1 "EXPORT56"`
* cipher strength is 56 AND cipher is marked as "export"
* Somewhat misleading since the description doesn't indicate that non-export ciphers are excluded.
* The ones that are marked as "export" are the ones that have "(1024)" in the "Kx=..." field.

`'EXPORT'                           " Export Ciphers (general) "   1 "EXPORT"`
- cipher is marked as "export"
- Okay, but if the 56-bit export ciphers were included in "56 Bit encryption," then this wouldn't really be needed, since all "export" ciphers use either 40 or 56-bit encryption.

`'LOW:!ADH'                         " Low (<=64 Bit)           "   1 "LOW"`
* Au!=NULL AND (cipher strength <= 64, but not "None") AND (cipher is not marked as "export")
* This is one 64-bit RC4 cipher plus the 56-bit ciphers that are not marked as "export".
* As noted below, "Low (<=64 Bit)" is just the "DES Ciphers" plus RC4-64-MD5.

`'DES:!ADH:!EXPORT:!aNULL'          " DES Ciphers              "   1 "DES"`
* Au!=NULL AND (cipher is 56-bit DES) AND (cipher is not marked as "export")
* These are the 56-bit ciphers that are not marked as export. So, it wouldn't be needed if "56 Bit encryption" included the 56-bit non-export ciphers.
* Also, this is the same as the "Low (<=64 Bit)" ciphers, just without RC4-64-MD5.

`'MEDIUM:!NULL:!aNULL:!SSLv2:!3DES' " \"Medium\" grade encryption" 2 "MEDIUM"`
* Au!=NULL AND (cipher is 128-bit SEED, RC4, or IDEA)
* Okay, as "Medium" is subjective

`'3DES:!ADH:!aNULL'                 " Triple DES Ciphers       "   3 "3DES"`
* Au!=NULL AND (cipher is 168-bit 3DES)
* Okay, includes all Triple-DES ciphers, except those will Null authentication.

`'HIGH:!NULL:!aNULL:!DES:!3DES'     " High grade encryption    "   0 "HIGH"`
* Au!=NULL AND (cipher is AES, Camellia, ChaCha20, GOST, or ARIA)
* Okay, as "High grade encryption" is subjective

**Comment by drwetter** [comment]
I am going to change this as follows:

* keep Null Ciphers
* keep Anonymous NULL Ciphers
* keep Anonymous DH Ciphers
* remove 40 or 56 bit export / no export ciphers
* new: _Export Ciphers_      (EXPORT40:EXPORT56:!ADH:!NULL)
* keep: LOW ciphers but label it as "DES + 64 Bit encryption (no export)" --> includes non-export ciphers with 56 DES and 64 Bit (1x RC4-64-MD5) 
* remove DES (see previous, there's only  included)
* redefine MEDIUM as
  ``openssl ciphers -V 'ALL:!aNULL:!AES:!CAMELLIA'| grep 128``
* new: _3DES (Medium)_  `` '3DES:!aNULL:!ADH' ``
* keep HIGH

Thinking about to add a category beyond HIGH (like STRONG) to include Mac=AEAD ciphers for some kind of extra "reward" (and exclude them from HIGH).

**Comment by drwetter** [comment]
see 036bf2e53cbd0922cd0b9d46d6e22fd46bbcbdad
