### ISSUE TITLE
Feature request - Scan WPA EAP

### ISSUE THREAD

**Issue by FrankSpierings** [drwetter/testssl.sh#562]
I'm currently testing the cipher suites of an inner EAP tunnel manually. This is quite a pain, but I don't have the time to write the code for it.

What I currently use is:
 - wpa_supplicant, with a configuration file specifying the parameter 'openssl_ciphers' (e.g: openssl_ciphers ="MD5").
- Wireshark, to proof the connection worked with the specified cipher suite.

The current limitations are:
- It is a slow manual method
- The openssl library it uses does not support LOW cipher suites, so no decent test.

I think this might need a modified wpa_supplicant, but it might be possible to do it with commands and a different library search path (to link a different openssl) for wpa_supplicant.

**Comment by drwetter** [comment]
For OpenSSL: feel free to use @PeterMosmans fork. There you would get the libraries from (here are only binaries).

For WPA: it's interesting but honestly personally I never did that and can't tell whether it fits into this project.

You have a few command lines which allow us to have a peek?

**Comment by FrankSpierings** [comment]
Okay for a phase_2 tunnel check I do the following.

Create a network configuration:

`network={
	ssid="MyExampleSSID"
	key_mgmt=WPA-EAP
	eap=PEAP
	identity="me@example-realm.com"
	anonymous_identity="me@example-realm.com"
	password="password"
	phase2="auth=MSCHAPV2"
	#openssl_ciphers="MEDIUM"
	#openssl_ciphers="aNULL"
	#openssl_ciphers="eNULL"
	#openssl_ciphers="3DES"	
	#openssl_ciphers="MD5"
	#openssl_ciphers="DHE"
          openssl_ciphers="RC4"
}`

Now connect to the accesspoint using the above config as example.conf and wireless interface 0:
`wpa_supplicant -i wlan0 -c example.conf `

If the log (or screen) shows the following message, it is a negotiation failure. The RADIUS server endpoint did not allow the use of any ciphers in the specified cipher suite string:
`SSL: SSL3 alert: read (remote end reported an error):fatal:handshake failure`

If the log (or screen) shows the following message, it is a client-side failure:
`TLS: Failed to set TLS connection parameters`
This occurs when you specify 'LOW' for an openssl version that does not have low ciphers compiled.
`openssl ciphers LOW`

To check the preferred cipher suite the server chose, I currently need to grab a packet capture.
`tcpdump -i any -s0 ether proto 0x888e -w capture.pcap`

Reading the capture file you can check which cipher has been chosen by the server. A small modification to the wpa_supplicant code could probably make it dump this information in the logs.

**Comment by drwetter** [comment]
Thanks, @FrankSpierings for the interesting explanation.

I am afraid this is beyond of the scope of this project.
