### ISSUE TITLE
Let's Encrypt certificate reports CRL issue 

### ISSUE THREAD

**Issue by gerhard-tinned** [drwetter/testssl.sh#587]
I have a certificate from Let's Encrypt and the testssl.sh report the following (in red).

<pre>
 Certificate Revocation List  --
</pre>

Why is it reported like an error??

**Comment by drwetter** [comment]
yes, thank you. 

It should be checked whether there's one mechanism of certificate revocation and if not then it should shout out loud.

**Comment by gerhard-tinned** [comment]
That sounds perfect. Can I help in any way?

**Comment by drwetter** [comment]
Thx. In general yes but I would prefer to have a look myself at this piece of code as it was written some time back I would do it differently today.

**Comment by gerhard-tinned** [comment]
No problem. ;) 

Let me know when I can test something. ;-)

**Comment by drwetter** [comment]
now e.g. ;-)

**Comment by gerhard-tinned** [comment]
I have tested it, works for me! Thanks for the quick fix. :)

I use the red colour to determine the number of errors. Or is there a better way?

**Comment by drwetter** [comment]
Thx for reporting!

At the moment there's no other elegant way. JSON or CSV output could better suit your needs..

Cheers, Dirk


⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by gerhard-tinned** [comment]
Well, I guess the standard would be json. But for me, a simple return code with the number of errors would be more than enough. 

I run the script for a number of hosts and would like to know for each of them if they passed(0 errors) or not (more than 0 errors).

**Comment by drwetter** [comment]
I wouldn't call them errors as in the sense of the program it is a malfunction. 

In any case, yes, sounds reasonable -- see #327.
