### ISSUE TITLE
Add SHA256 fingerprint

### ISSUE THREAD

**Issue by kyhwana** [drwetter/testssl.sh#59]
Add SHA256 fingerprint output, along with SHA1. ie:   out " Fingerprint / Serial         "
                outln "$($OPENSSL x509 -noout -in $HOSTCERT -fingerprint | sed 's/Fingerprint=//' ) / $($OPENSSL x509 -noout -in $HOSTCERT -fingerprint -sha256 | sed 's/Fingerprint=//' )/ $($OPENSSL x509 -noout -in $HOSTCERT -serial | sed 's/serial=//')"

**Comment by drwetter** [comment]
Thx & done (ab48c66).

Still a bit thinking though as a) SHA1 collisions need >= 2^57 tries and b) it makes that section of testssl.sh longer
