### ISSUE TITLE
Incorrectly reporting "days" instead of "seconds" for insufficient HPKP max-age values.

### ISSUE THREAD

**Issue by craSH** [drwetter/testssl.sh#591]
- testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -1)
`(89e8fca 2017-01-17 14:03:09 -- 1.565)`

- target IP
`Internal testing host - shouldn't matter`

Something that returns a very short max-age for the HPKP header, such as:

`Public-Key-Pins: pin-sha256="key1"; pin-sha256="key2"; pin-sha256="key..."; max-age=10`

- testssl.sh command line
  - `./testssl.sh <hostname>`

- openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
```
Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
on <myhost>:./bin/openssl.Darwin.x86_64
(built: "Sep  7 19:34:54 2016", platform: "darwin64-x86_64-cc")
```

- Your operating system (uname -a)
`Darwin <myhost> 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`

- what was happening (output is useful!) and what did you expect
There is a typo in the reporting of lower-than-ideal HPKP times. In `testssl.sh`, The `$HPKP_MIN` variable's internal value is in seconds, but the reporting messages on lines 1089 and 1090 assume it is in days. Either change the text to refer to seconds, or convert the value to days when reporting this condition.

**Example output for a server with HPKP max-age of "10" (seconds):**

`Public Key Pinning           3 keys, 10 s = 0 days (<2592000 days is not good enough), just this domain`

2592000 days is quite the max-age! :) 2592000 seconds is 60 days, which is the intended message here.

**Variable tuning/initialiation on lines 175:176 (final unit of time = seconds):**

```
HPKP_MIN=${HPKP_MIN:-30}                # >=30 days should be ok for HPKP_MIN, practical hints?
HPKP_MIN=$((HPKP_MIN * 86400))     # correct to seconds
```

**Example code on lines 1089:1090:**

```
pr_svrty_medium "$hpkp_age_days days (<$HPKP_MIN days is not good enough)"
fileout "hpkp_age" "MEDIUM" "HPKP age is set to $hpkp_age_days days ($hpkp_age_sec sec) < $HPKP_MIN days is not good enough."
```

**Comment by drwetter** [comment]
thx for reporting
