### ISSUE TITLE
testssl.sh/testssl.sh  -t smtp --jsonfile-pretty - invalid json generated

### ISSUE THREAD

**Issue by rzmf** [drwetter/testssl.sh#597]
`...
  ],
                    "browserSimulations": [
                    ]          "service"           : [
                    ],`

Missing , (comma) and newline after the (empty) section browserSimulations

**Comment by drwetter** [comment]
Thx for reporting.

Mind giving me a PR?

**Comment by drwetter** [comment]
cc'ing @AlGreed

**Comment by AlGreed** [comment]
hm. why is "service" after browserSimulation? As i remember browserSimulation was all time at the end (so need in comma) and the service block - at the beginning. Was the order changed? Will take a look at it, when i get some time.

**Comment by AlGreed** [comment]
I assume @rzmf, you have tested mailbox.com? There are multiple smtp servers. And with "**-t smtp -mx**" will be overall 3 servers tested. Right now --json-pretty does not support multiple servers.

**Comment by drwetter** [comment]
@rzmf have you tried a JSON validator?

**Comment by rzmf** [comment]
with current head all is good, thanks for fixing

**Comment by drwetter** [comment]
ok, thank you
