### ISSUE TITLE
openssl binary under LIS (bash for Windows)

### ISSUE THREAD

**Issue by marcstern** [drwetter/testssl.sh#605]
Under LIS, I get a "Segmentation fault (core dumped)" with the openssl.Linux.x86_64

Any idea? LIS is based on Ubuntu

Thanks

**Comment by teward** [comment]
Bash on Windows requires you to compile the OpenSSL fork yourself - it isn't the exact same as the environment the static builds were made for and has been an issue in the past.  The downside is you lose a lot of the ciphers/curves this way.  You may wish to just use the bundled OpenSSL that comes with the Linux subsystem.

**Comment by marcstern** [comment]
Thanks for the quick reply.
Any idea about the reasons/limitation why a standard Linux bin cannot be 
used under LIS?

**Comment by teward** [comment]
Probably has to do with the libraries and what is available.  I have not had to work with it on the linux subsystem for windows but in most cases it would be missing shared libraries, etc. that aren't bundled in WSL but are available in the full Ubuntu installs.

**Comment by drwetter** [comment]
gdb program core ;-)

**Comment by marcstern** [comment]
can't find it under LIS :-(
    
    
      
    
    On 01-02-2017 22:15, Dirk Wetter wrote:
    
    
      
      gdb program core ;-)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/drwetter/testssl.sh","title":"drwetter/testssl.sh","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/drwetter/testssl.sh"}},"updates":{"snippets":[{"icon":"PERSON","message":"@drwetter in #605: gdb program core ;-)"}],"action":{"name":"View Issue","url":"https://github.com/drwetter/testssl.sh/issues/605#issuecomment-276784420"}}}

**Comment by drwetter** [comment]
@teward  Is there a variable one can use to prevent testssl's binary to be picked up?

**Comment by teward** [comment]
@drwetter An alternative potential test would be as follows, adding to the 'if' block and such for testing if the bundled binaries exist (which sets the openssl variable in the script):

On Windows Subsystem for Linux, the file `/mnt/c/Windows/System32/bash.exe` will exist.  This is because the Windows Subsystem mounts the C drive, and that `bash.exe` is what opens then subsystem layer.

**Comment by drwetter** [comment]
Environment variable maybe?  My idea is to prevent the testssl binaries automatically being picked up -- as long as the core dump

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by teward** [comment]
@drwetter Let me poke the code and make a PR for consideration and testing.  I have a 'fork' of your project that forcibly uses the compiled binaries I have; a tweak of your existing `if` checks might be enough to implement my test, but the environment variable is OPENSSL= in the by-hand execution format I stated earlier.  That said, it's not 100% reliable.

**Comment by drwetter** [comment]
I am into reliability:)

What does env or set say?

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by drwetter** [comment]
If I look at it seems ok if just a few windows files are being tested like /mnt/c/Windows/systems.ini

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by teward** [comment]
@drwetter I'm currently testing /mnt/C/Windows/System32/bash.exe, which I know exists for Linux subsystem installed systems.  Tested myself just now.  I'm prepping a PR/diff for consideration.  Though, testssl.sh takes an eternity to do anything on the linux subsystem.
