### ISSUE TITLE
Local problem: No 40 Bit encryption configured in /usr/bin/openssl

### ISSUE THREAD

**Issue by flamecopper** [drwetter/testssl.sh#607]
Hi there,

I am using the latest version of testssl.sh however I am getting error on it.

>  Using "OpenSSL 1.0.2c 12 Jun 2015 (Library: OpenSSL 1.0.2k  26 Jan 2017)" [~125 ciphers] on
>  ECOPSGN102:/usr/bin/openssl
>  (built: "reproducible build, date unspecified", platform: "Cygwin-x86_64")
> 
> 
> Testing now (2017-02-01 14:30) ---> 65.61.137.117:443 (demo.testfire.net) <---
> 
>  rDNS (65.61.137.117):   --
>  Service detected:       HTTP
> 
> 
> --> Testing protocols (via sockets except TLS 1.2 and SPDY/NPN)
> 
>  SSLv2      not offered (OK)
>  SSLv3      not offered (OK)
>  TLS 1      offered
>  TLS 1.1    offered
>  TLS 1.2    offered (OK)
>  SPDY/NPN   not offered
> 
> --> Testing ~standard cipher lists
> 
>  Null Ciphers                 not offered (OK)
>  Anonymous NULL Ciphers       not offered (OK)
>  Anonymous DH Ciphers         not offered (OK)
>  40 Bit encryption            Local problem: No 40 Bit encryption configured in /usr/bin/openssl
>  56 Bit encryption            Local problem: No 56 Bit encryption configured in /usr/bin/openssl
>  Export Ciphers (general)     Local problem: No Export Ciphers (general) configured in /usr/bin/openssl
>  Low (<=64 Bit)               Local problem: No Low (<=64 Bit) configured in /usr/bin/openssl
>  DES Ciphers                  Local problem: No DES Ciphers configured in /usr/bin/openssl

**Comment by drwetter** [comment]
Are you using 2.9dev?

If yes, please see https://github.com/drwetter/testssl.sh/wiki/Bug-reporting.

**Comment by flamecopper** [comment]
No,

I am currently using 2.8rc3

###########################################################
    testssl.sh       2.8rc3 from https://testssl.sh/dev/
    (1.565 2016/12/20 13:26:11)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.0c  10 Nov 2016" [~143 ciphers]
 on ECOPSGN102:/usr/bin/openssl
 (built: "reproducible build, date unspecified", platform: "debian-amd64")

**Comment by drwetter** [comment]
As it says: it's a warning that your local openssl version doesn't support this. Either use 2.9dev or accept this warning ;-)
