### ISSUE TITLE
complete SWEET32

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#613]
remaining block ciphers:
* RC2, IDEA, DES
* clarify SSLv2 ciphers

**Comment by Calico90** [comment]
I hope the detection of SWEET32 will be added to testssl.sh soon. Maybe you can get some inspiration from here: 

https://github.com/adamcaudill/yawast/blob/39570a66c5bcefa25575ffb02379c440363fc941/lib/scanner/plugins/ssl/sweet32.rb

**Comment by drwetter** [comment]
> I hope the detection of SWEET32 will be added to testssl.sh soon. 

It is, since F. 2nd. Please read the content of this ticket thoroughly.

**Comment by drwetter** [comment]
SSLv2 is still open

**Comment by drwetter** [comment]
SSLv2 was done with latest commit
