### ISSUE TITLE
--show-each is default for -x <pattern>

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#616]
e.g. while testing ``./testssl.sh -x CBC <target>``

**Comment by dcooper16** [comment]
Isn't that the expected behavior for `-x`. I just took a quick look at the code for `test_just_one()`, and it seems to display every cipher that matches the "\<pattern\>" in every version of testssl.sh (2.2, 2.4, 2.6, 2.8, and 2.9dev).

**Comment by drwetter** [comment]
Okay,  thx. Used it not very often probably ;)

But it guess if one really want to see all the ciphers available one should use --show-each also here.

In needed for a costumers all  CBC ciphers of the server. The output of -x CBC then is not very handy.
