### ISSUE TITLE
Output HTML

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#619]
> > So, at the moment I can't think of a good way to make the available and unavailable ciphers easily distinguishable that works with HTML (as generated by aha) as well as in terminals with black backgrounds and terminals with white backgrounds.
> 
> As far as HTML is concerned: aha is a cool thing -- however I still consider it as a kludge -- a good working one though. My idea like two years back was to do this natively or via JSON-->HTML converter. Now as JSON is there I have my doubts that this is going to fly as the ideas of both are different: one is for humans, the other one is more a machine readable format. Conversion thus seems too complicated and HTML output would probably be easier if done natively by testssl.

I decided to look into getting testssl.sh to create HTML output, and I believe that I'm mostly there: https://github.com/dcooper16/testssl.sh/blob/generate_html/testssl.sh.

My basic idea was to change functions like `out()`, `pr_warning()`, etc. to output the input to the terminal and, optionally, to an HTML file. In order for this to work I needed to ensure that these functions were only called for output that should go to both the terminal and the HTML file. However, in some cases testssl.sh currently calls one of these functions and "captures" the output in a variable. So, I had to modify the code so that none of these functions were called for that purpose.

I also had to change the code a bit to ensure that all output that was intended for both the terminal and the HTML file was printed using one of these functions (e.g., not using `echo`).

As a general rule I assumed that debugging output should only be displayed on the terminal, so I call separate functions (e.g., `pr_warning_term()`) when the output should be displayed on the terminal but not in the HTML.

The code seems to be working okay, but needs more testing. The main problem at the moment is that the caller needs to provide the name of the file in which to output the HTML, and testssl.sl will append to that file. So, if you run testssl.sh multiple times and want the output to go to the same file name, you may have to delete the file yourself before each call.

As noted, the code is available at https://github.com/dcooper16/testssl.sh/tree/generate_html (just add an `--htmlfile <filename>` option to the command line). Please let me know if you think this is the right direction to go.

Thanks,

David

**Comment by drwetter** [comment]
👍  excellent! Ran it, looks good.

Let me have a look at the code. Call it a day now...

**Comment by dcooper16** [comment]
I've done some more work on this code over the past week and believe that it is ready to go.

The main issue at the moment is that all the output is sent to a single file, the one specified in the command line. This should work with the current code, but it would not work with `run_mass_testing_parallel()`. If that function were in use, then there would be no choice but to have the HTML for each server go into a separate file.

I can submit a PR if you'd like, but there is a good chance this PR would have some minor conflicts with the PR I just submitted (#630).

**Comment by drwetter** [comment]
see #634, #665, #31
