### ISSUE TITLE
Safari connection simulation is incorrect?

### ISSUE THREAD

**Issue by bknowles** [drwetter/testssl.sh#624]
Folks,

I've been using `testssl.sh` extensively to test the web services for a site I help administer for the Network Time Foundation, and I was very surprised to see that I was being told that Safari 9 would not connect to the server in question, whereas Safari 8 would be able to connect with TLS 1.2.  I tried connecting to the server with an actual copy of Safari on my machine, and it connected fine.

I then tried to compare this output with the results from [https://www.ssllabs.com/ssltest/](https://www.ssllabs.com/ssltest/) and found that they appear to have the same bug.

Can you help me figure out what would be the right way to debug and fix this issue?

Thanks!

**Comment by bknowles** [comment]
BTW -- unfortunately, the site is down at the moment, so I can't give you the URL to test against.  ;(

**Comment by drwetter** [comment]
No wonder ;-) testssl is using the client data from SSLlabs API (with permission). 

Would be curious to know details though but I am afraid I / we should just fwd those..

**Comment by bknowles** [comment]
Or maybe I should just file the bugs with SSLLabs directly?

**Comment by drwetter** [comment]
At least for curiosity I'd suggest to file it here first/too. You can directly check the ssllabs API via https://api.dev.ssllabs.com/api/v3/getClients.

Last but not least the simulation in testssl is static and would need to be updated manually.

**Comment by drwetter** [comment]
@bknowles : Is that still an issue?

**Comment by drwetter** [comment]
Timeout, closing TCP connection. Happy to reopen if you have more info.
