### ISSUE TITLE
Distrust WoSign and StartSSL CAs

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#626]
... at least for HTTP as Mozilla and Chrome do so.

Either by updating the certificate store for Mozilla (1) or implement a manual check whether any of those CAs are being used and then warn for HTTP usage (2). What the right path is depends IMO also on others, e.g. Linux: If those CAs disappear from ~/etc/ssl/  MTAs will get a problem and testssl needs to reflect this.

Currently I am more into (2)

**Comment by typingArtist** [comment]
You know that browsers will only choke on certs signed by these CAs if they are generated after a specific point in time, so the CAs and their certificates are not fully banned. So I’d not expect the Root CA certs to disappear from the CA stores anytime soon.

**Comment by drwetter** [comment]
I addressed this as harsh as SSLlabs is currently doing, i.e. As certificate from those providers is not trusted any more. I noticed that Chrome and Firefox distrust some certificates from StartCom, others not (yet).

This also applies for non-HTTP services...

2.8 will follow
