### ISSUE TITLE
testssl vs nginx+OpenSSL 1.1.0d+ChaCha20_Poly1305

### ISSUE THREAD

**Issue by jauderho** [drwetter/testssl.sh#629]
When running the latest testssl against this combination, it does not appear that the ChaCha cipher is being detected. 

However, using Qualys SSL Server test returns the following:
* TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)

**Comment by teward** [comment]
And you are using an OpenSSL binary with testssl.sh that supports the CHACHA ciphers right?

**Comment by teward** [comment]
@drwetter It looks like the binaries here don't have that CHACHA cipher.  Is it possible that it's looking for a newer invocation of the CHACHA ciphers than is provided in the fork of OpenSSL that we use?

**Comment by drwetter** [comment]
There are (mainly) two different ChaCha/Poly ciphers. Cca8 and friends are the ones which are RFC ciphers and made it  into openssl 1.1.0. The draft ciphers are cc13-cc15.

At the moment Only the latter ones are are supported by the binaries shipped.

See https://github.com/PeterMosmans/openssl/issues/38

However the coverage of sockets in 2.9dev has dramatically increased,  thx to @dcooper16 . So unless you run 2.8 thr newer ones should have beend detected 

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by drwetter** [comment]
![screenshot_20170212_113821](https://cloud.githubusercontent.com/assets/8036727/22861379/f9b37078-f117-11e6-8017-2c27955d601c.png)

**Comment by drwetter** [comment]
If anybody feels like stepping in and send @PeterMosmans a RR see my last comment: https://github.com/PeterMosmans/openssl/issues/38#issuecomment-274107871. Was the best I found so far

**Comment by jauderho** [comment]
So I can confirm that cca8 is now being detected on the 2.9dev branch. 

However, it was a little surprising to see that the PFS detection was not in the same order.

 ```
Testing robust (perfect) forward secrecy, (P)FS -- omitting Null Authentication/Encryption, 3DES, RC4 

 PFS is offered (OK)          ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-CHACHA20-POLY1305 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 
 Elliptic curves offered:     prime256v1 


 Testing server preferences 

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            ECDHE-RSA-AES256-GCM-SHA384, 256 bit ECDH (P-256)
 Cipher order
    TLSv1.2:   ECDHE-RSA-CHACHA20-POLY1305 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES128-SHA256
```

**Comment by drwetter** [comment]
Thx for the feedback.

> However, it was a little surprising to see that the PFS detection was not in the same order.

Understand. That would require additional code for each section. However that's the reason for the point "server preferences" --> "order" :-)  Everything else is not ordered and currently will be printed out as soon as it is detected.
