### ISSUE TITLE
CRL assumes HTTP

### ISSUE THREAD

**Issue by fvance** [drwetter/testssl.sh#636]
In 2.9dev, the code that looks at the CRL assumes that the CRL protocol is HTTP.  THE Crl list can be provided through LDAP.

Error message of "no parsable output" is printed when an LDAP CRL list is encountered first.

**Comment by dcooper16** [comment]
It seems that testssl.sh can handle a certificate that includes an LDAP URL to refer to a CRL, even if the LDAP URL comes first. However, testssl.sh will issue the "no parsable output" message if the CRL Distribution Points extension is present and contains at least one URI, but does not contain any HTTP URLs.

The offending line is the first one below. `$crl` contains all of the URIs in the CRL Distribution Points extension. If `$crl` is not empty then there is a check to see if `$crl` contains "http", and if it doesn't the "no parsable output" message is displayed.

According to "Blame" a change was made on September 28, 2015 (https://github.com/drwetter/testssl.sh/commit/cac49cb1f12dacb19a458939956f32174d5784b7). Before that there was just a check of the number of lines in `$crl`, but that commit changed the code to first check whether `$crl` contained `http` and to then flag an error if it didn't. @drwetter : Do you remember the reason for the change?

```
     elif grep -q http <<< "$crl"; then
          if [[ $(count_lines "$crl") -eq 1 ]]; then
               outln "$crl"
               fileout "${json_prefix}crl" "INFO" "Certificate Revocation List : $crl"
          else # more than one CRL
               out_row_aligned "$crl" "$spaces"
               fileout "${json_prefix}crl" "INFO" "Certificate Revocation List : $crl"
          fi
     else
          pr_warningln "no parsable output \"$crl\", pls report"
          fileout "${json_prefix}crl" "WARN" "Certificate Revocation List : no parsable output \"$crl\", pls report"
     fi
```

**Comment by drwetter** [comment]
Not anymore sure. Reason told me to change ot similar to OSCP. ;)

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​
