### ISSUE TITLE
2.8rc4 doesn't catch protocol negotiation error

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#641]
Hi @drwetter ,

Is there a reason that you made the following change in 2.8:
```
      pr_bold " SSLv3      $extra_spaces";
-     if "$using_sockets"; then
+     if "$using_sockets" && ! "$HAS_SSL3"; then
           tls_sockets "00" "$TLS_CIPHER"
      else
           run_prototest_openssl "-ssl3"
```

With 2.8rc3, testssl.sh caught an error with the local CUPS server on my virtual machine:
```
 Testing protocols (via sockets except TLS 1.2, SPDY+HTTP2) 

 SSLv2               not offered (OK)
 SSLv3               server responded with higher version number (TLSv1.2) than requested by client (NOT ok)
 TLS 1               offered
 TLS 1.1             offered
 TLS 1.2             offered (OK)
 Version tolerance   downgraded to TLSv1.2 (OK)
 SPDY/NPN            not offered
 HTTP2/ALPN          not offered
```

With 2.8rc4, testssl.sh does not catch the error unless I use a version of OpenSSL that does not support SSLv3. `run_prototest_openssl()` sends an SSLv3 ClientHello, the server responds with a TLSv1.2 ServerHello, OpenSSL notices the problem and converts it to a connection failure, so `run_protocols()` doesn't see that the server offered TLSv1.2 rather than refusing the connection.
```
SSL_connect:before/connect initialization
SSL_connect:SSLv3 write client hello A
SSL3 alert write:fatal:handshake failure
SSL_connect:error in SSLv3 read server hello A
140050711389856:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:365:
```

**Comment by drwetter** [comment]
hello @dcooper16,

cannot reproduce your error but admittedly my change didn't make sense. That was a leftover before my local CVS server died in December which I used for 2.8.

Thx, Dirk
