### ISSUE TITLE
--append: no footer / two footers

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#653]
Two problems here:

1) ``./testssl.sh -S --json-pretty --file testfile`` / ``./testssl.sh -S --json --file testfile`` have no footers and thus produce incorrect JSON. (``-S`` just as an example).
``--append`` seems to be the culprit: ``testssl.sh -S --json-pretty --warnings=batch -q --append dev.testssl.sh`` is being called. W/o ``--append`` ist works fine.

2) if a ``--json-file`` is being specified (e.g. ``./testssl.sh -S --json-pretty --jsonfile=aa.json  --file testfile``), which effectively calls ``./testssl.sh -S --json-pretty --jsonfile=aa  --warnings=batch -q --append dev.testssl.sh`` the file ``aa.json`` has two JSON footers

**Comment by AlGreed** [comment]
> 2) if a --json-file is being specified (e.g. ./testssl.sh -S --json-pretty --jsonfile=aa.json --file testfile), which effectively calls ./testssl.sh -S --json-pretty --jsonfile=aa --warnings=batch -q --append dev.testssl.sh the file aa.json has two JSON footers

Why would we use --json-pretty  and --jsonfile=aa.json together, if we have --jsonfile-pretty for this case? If we use them together, the same context will be saved twice, but in different formats, in one file.

**Comment by dcooper16** [comment]
He really meant using `--jsonfile-pretty` along with `--file`. This is based on a comment that I sent to Dirk:

> When I use both the "--json" option and the "--file \<testfile\>" option, the JSON files that are created for each line in "testfile" are missing footers. When I use the "--jsonfile \<jsonfile\>" option with the "--file \<testfile\>" option, the resulting JSON file has two footers. The same happens with "--json-pretty" and "--jsonfile-pretty".
> 
> Another problem I discovered is that if I use the "--jsonfile \<jsonfile\>" option with the "--file \<testfile\>" option, and "jsonfile" already exists, then testssl.sh will append the JSON output to "jsonfile" rather than overwriting (and it won't add a JSON header), even though I didn't include the "--append" option in the command line.

See also PR #652.

**Comment by drwetter** [comment]
done for both branches
