### ISSUE TITLE
Reporting output

### ISSUE THREAD

**Issue by daraniya** [drwetter/testssl.sh#68]
When running these checks, there is no good way to output to a file. I asked this question on Twitter, and it was suggested that I make this an issue...

What I'm looking for is something simple.  HTML is just fine. When I attempted to send the output to a file, the output was mangled with escape codes and the like. It would be great if I could get an HTML

**Comment by drwetter** [comment]
Am 2. März 2015 09:24:41 GMT+04:00, schrieb daraniya <notifications@github.com>:
>When running these checks, there is no good way to output to a file. I
>asked this question on Twitter, and it was suggested that I make this
>an issue...
>
>What I'm looking for is something simple.  HTML is just fine. When I
>attempted to send the output to a file, the output was mangled with
>escape codes and the like. It would be great if I could get an HTML

Pls try first COLOR=0 ./testssl.sh <cmdline>.

For nicer HTML formatting I'll leave this open and see when I/somebody else can implement this.  

Cheers, Dirk

**Comment by keith4** [comment]
FWIW, I've been running automated ssltest scans and using aha to save
the output as HTML. Works very well.

https://github.com/theZiz/aha

**Comment by daraniya** [comment]
"COLOR=0"  Just Works...  I don't want another program on a work computer
that just formats output...

**Comment by keith4** [comment]
Forgot to mention, in case anyone else is interested: it's packaged in
Debian/Ubuntu, at least.

Using it is as simple as testssl.sh whatever:443 | aha > foo.html

And you get to keep all the pretty colors ;-)

**Comment by daraniya** [comment]
aha wasn't available in kali, but was easy enough to build and cp to
/usr/local/bin

Works great... :) thanks for that...

Should I close the issue, or do you want to keep it as something to add
later?

**Comment by drwetter** [comment]
Am 2. März 2015 22:10:42 GMT+04:00, schrieb daraniya <notifications@github.com>:
>aha wasn't available in kali, but was easy enough to build and cp to
>/usr/local/bin
>
>Works great... :) thanks for that...
>
>Should I close the issue, or do you want to keep it as something to add
>later?

I want to keep it. Priorities are technical improvements though. 

Didn't know about aha either. Thx, keith4!

Cheers, Dirk

**Comment by drwetter** [comment]
This will be done with JSON, see #31.

**Comment by salt-lick** [comment]
![screen shot 2015-05-09 at 10 42 14 pm](https://cloud.githubusercontent.com/assets/3297736/7553002/b9f15e9a-f69c-11e4-8641-abefcc17b691.png)
Is there a reason those 2 greens are different?

**Comment by drwetter** [comment]
Am 10. Mai 2015 05:43:27 MESZ, schrieb Steven Barnes <notifications@github.com>:
>![screen shot 2015-05-09 at 10 42 14
>pm](https://cloud.githubusercontent.com/assets/3297736/7553002/b9f15e9a-f69c-11e4-8641-abefcc17b691.png)
>Is there a reason those 2 greens are different?

Yes, also e.g. the reds are different. They should reflect some kind of rating.

**Comment by jpluimers** [comment]
In case anyone want clickable `URI`s in the `html` output generated by `aha`, please test the `perl` replacement `regex` I posted at https://github.com/theZiz/aha/issues/20#issuecomment-249370480 as I'm anxious to see how well (or bad) that works. If it fails, please post a comment there.
