### ISSUE TITLE
"htmlfile exists. Either use --append or (re)move it"

### ISSUE THREAD

**Issue by malexmave** [drwetter/testssl.sh#680]
Running the latest commit from 2.9dev, I'm getting the aforementioned error, even if I am passing --append to testssl. Minimal steps to reproduce:

    touch /tmp/htmlfile
    ./testssl.sh --append --logfile /tmp/htmlfile [some domain]

Output will be:
```
###########################################################
    testssl.sh       2.9dev from https://testssl.sh/dev/
    (7543aa3 2017-03-27 08:59:29 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on ubu-vm-2:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")


Fatal error: "/tmp/htmlfile" exists. Either use "--append" or (re)move it
```

In case this makes a difference, I am running bash version 4.3.46(1)-release (x86_64-pc-linux-gnu). Please let me know if you need any additional information. Interestingly enough, the same command worked a few days ago, so it's probably something recently introduced.

I notice that the documentation for --append does not mention `<htmlfile>` as something that is influenced by the parameter, so it may be related to this. Is this expected behaviour, then? (In which case the error message should probably be changed)

Use case: I'm creating the htmlfile and a jsonfile using `mktemp`, which creates an empty file, so "appending" html would in fact mean "writing it to an empty file".

**Comment by drwetter** [comment]
yes, there were some changes also regarding overwriting without asking. Your case should be fixed now.

Please keep in mind that ``--logfile /tmp/htmlfile`` just creates a screen-based logfile using terminal escape codes. For native HTML output you have to use ``--htmlfile /tmp/htmlfile`` but then you shouldn't use append in the way you suggested as you miss the HTML header. Same should apply for JSON.

``help()`` clarified, too

**Comment by malexmave** [comment]
Thanks a lot! I also just noticed the log != html thing (I'm working on code I inherited from someone else), but since I have yet to find a place in our code where the (alleged) HTML file is used, I guess this has not yet caused any problems. I'll keep it in mind.
