### ISSUE TITLE
Make use of append option only when append to a file

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#684]
Historically ``--append`` was existing IIRC for safety reasons, so that for mass testing the out is being sent to ONE file it is **not** overwritten by subsequent writes for checks against other hosts.

In that sense the ``--append`` option should be used -- i.e. only when one output file is used ``--append`` should be used.

**Comment by drwetter** [comment]
``--append`` is currently being used _also_ for inheriting the signal to the child "we do mass testing".

**Comment by dcooper16** [comment]
How would you feel about adding a command line flag that is only intended to be used to signal to testssl.sh that it is a "child" in a mass testing? A flag that would be recognized by the code, but that wouldn't be advertised in the `--help` output. Perhaps `--mass-testing-child`. Then, functions such as `json_header()`, `csv_header()`, `html_header()`, and `html_banner()` wouldn't have to use the `$APPEND` flag as a way of trying to determine if mass testing is being performed.

At the moment `html_header()` does the following (and `json_header()` and `csv_header()` do the same):
```
     # Don't create HTML headers and footers in the following scenarios:
     #  * HTML output is not being created.
     #  * mass testing is being performed and each test will have its own HTML file.
     #  * this is an individual test within a mass test and all HTML output is being placed in a single file.
     if ! "$do_html" || \
        ( "$do_mass_testing" && ( [[ -z "$HTMLFILE" ]] || [[ -d "$HTMLFILE" ]] ) ) || \
        ( "$APPEND" && [[ -n "$HTMLFILE" ]] && [[ ! -d "$HTMLFILE" ]] ); then
               HTMLHEADER=false
               return 0
     fi
```
If there were a specific flag indicating mass testing, then the third line of this test could use that flag rather than `$APPEND` to determine whether "this is an individual test within a mass test."

**Comment by drwetter** [comment]
Am 27.03.2017 um 21:39 schrieb David Cooper:
> How would you feel about adding a command line flag that is only intended to be used to signal
> to testssl.sh that it is a "child" in a mass testing? A flag that would be recognized by the
> code, but that wouldn't be advertised in the |--help| output. Perhaps |--mass-testing-child|.

I vote in run_mass_testing() for CHILD=true ./testssl.sh ... or maybe CHILD_MASS_TESTING as
opposed
to the parent $do_mass_testing

> Then, functions such as |json_header()|, |csv_header()|, |html_header()|, and |html_banner()|
> wouldn't have to use the |$APPEND| flag as a way of trying to determine if mass testing is
> being performed.

+1

> At the moment |html_header()| does the following (and |json_header()| and |csv_header()| do the
> same):
> 
> |# Don't create HTML headers and footers in the following scenarios: # * HTML output is not
> being created. # * mass testing is being performed and each test will have its own HTML file. #
> * this is an individual test within a mass test and all HTML output is being placed in a single
> file. if ! "$do_html" || \ ( "$do_mass_testing" && ( [[ -z "$HTMLFILE" ]] || [[ -d "$HTMLFILE"
> ]] ) ) || \ ( "$APPEND" && [[ -n "$HTMLFILE" ]] && [[ ! -d "$HTMLFILE" ]] ); then
> HTMLHEADER=false return 0 fi |
> 
> If there were a specific flag indicating mass testing, then the third line of this test could
> use that flag rather than |$APPEND| to determine whether "this is an individual test within a
> mass test."

I appreciated the logic as it worked :-) but it took a moment understanding it.

How about making it snappier:

```
! "$do_html"  && HTMLHEADER=false && return 0
"$do_mass_testing" && ( [[ -z "$HTMLFILE" ]] || [[ -d "$HTMLFILE" ]] ) ) && HTMLHEADER=false &&
return 0
```

(is there a chance at this moment HTMLFILE is still empty??)

```
 ( "$CHILD_MASS_TESTING" && [[ -n "$HTMLFILE" ]] && [[ ! -d "$HTMLFILE" ]] ); then
```

as at least one of -z and -d were tested before: can this be shortened?


Cheers, Dirk

**Comment by drwetter** [comment]
That should be resolved
