### ISSUE TITLE
FREAK

### ISSUE THREAD

**Issue by schuetzm** [drwetter/testssl.sh#69]
INRIA yesterday disclosed a new SSL vulnerability:
https://freakattack.com/

**Comment by PeterMosmans** [comment]
The server-side check on (RSA) EXPORT ciphers is already there.. although under a different/no fancy name :)

**Comment by drwetter** [comment]
Am 4. März 2015 14:12:45 GMT+04:00, schrieb Peter Mosmans <notifications@github.com>:
>The server-side check on (RSA) EXPORT ciphers is already there..
>although under a different/no fancy name :)

 You're right. I can add the fancy name though later. 

Not read details completely yet but the point is >15 years old. Then there was a reason why it was called EXPORT ciphers.

The sad thing is only that so many servers still support it, one of them is one of my ISPs, Telefonica.   

Cheers, Dirk


-- 
Sent from my mobile

**Comment by drwetter** [comment]
I added a separate check in 77e2892 . It's restricted to EXPORT && RSA. By coincidence openssl  ciphers -V EXPORT and openssl  ciphers -V  'ALL:eNULL' | grep RSA | grep EXP are the same on my preferred machines. It warns also if there's no local support
