### ISSUE TITLE
hostname/local FQDN are not case insensitive

### ISSUE THREAD

**Issue by FinzelStefan** [drwetter/testssl.sh#691]
Hostnames (/etc/hosts) and DNS names should be case insensitive : https://tools.ietf.org/html/rfc4343

Please change
 ip4=$(grep -wh ...
 ip6 = $(grep -wh ...
too
 ip4=$(grep -whi ...
 ip6 = $(grep -whi ...

example:

$ testssl2.8.sh USLxxxSRV
everything is fine

$ testssl2.8.sh Uslxxxsrv

No mapping file found

###########################################################
    testssl2.8.sh       2.8pre1 from https://testssl.sh/
    (1.574 2017/03/27 20:37:06)

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.1e-fips 11 Feb 2013" [~121 ciphers]
 on defthwai1sgm:/opt/mysql/bin/openssl
 (built: "Sep 22 05:36:03 EDT 2016", platform: "linux-x86_64")

Fatal error: No IPv4 address for "Uslxxxsrv" available

**Comment by drwetter** [comment]
thx for reporting. Fixed now in stable and dev
