### ISSUE TITLE
Command option to only output vulnerabilities

### ISSUE THREAD

**Issue by zerosum0x0** [drwetter/testssl.sh#693]
testssl.sh is great at performing an audit, but sometimes you only want bad things to be spilled on your screen.

I generally run `./testssl.sh x.x.x.x | grep -i "not ok"`, which works well to filter out all the things that aren't problems, but it doesn't catch everything such as DH 1024 and missing TLS_FALLBACK_SCSV.

So this issue is a request to have a command argument to only spew out things that are bad.

**Comment by drwetter** [comment]
It's either a duplicate of #232  and except the screen and HTML output is has been addressed in #503, see ``--severity`` cmdline switch
