### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by leonardo0014** [drwetter/testssl.sh#70]
Hi,

how can i use testssl.sh with an Proxy for the test? 
My Test Website is behind a Real Proxy and have no or a localhost DNS local Lookup.
Local Proxysettings in the Bash doesn't work.

Can anybody help me?

**Comment by drwetter** [comment]
TL;DR: no, it's not possible. I would use *corkscrew* to ssh to a machine (running ssh on port 443) with free access to the internet and try from there or maybe *proxytunnel* works. 

testssl.sh is partly using *openssl s_client*, partly bash sockets. The latter one might not work with proxytunnel. DNS lookups for pt or cs: Can't tell off the top of my head

**Comment by drwetter** [comment]
BTW, see #124 . @newbigin implemented the changes (thx again!) to the code so that now it is possible.

A constraint is the capability of your proxy. You likely can't tunnel anything else than HTTP though it.
