### ISSUE TITLE
File names with space characters

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#702]
In developing PR #698 I discovered a problem with filenames that include space characters.

When mass testing is not being performed, then I have only verified the problem in two places, with log file names and with the "PATH" for the OpenSSL binary. PR #701 addresses the problem with log file names. I believe the issue could be addressed for the OpenSSL binary by placing every use of `$OPENSSL` in quotes, but I've haven't tried it yet.

The biggest problem I've encountered is if mass testing is being performed and a filename with space characters needs to be included in the command line for the child processes. Using the command line:
```
bash testss.sh --htmlfile my\ results testssl.sh
```
or
```
bash testssl.sh --htmlfile "my results" testssl.sh
```
results in an HTML file being created in the "my results" directory.

However, the command line:
```
bash testssl.sh --htmlfile "my results" --file testlist.txt
```
results in child processes being called with command lines like:
```
testssl.sh --htmlfile my results  --warnings=batch testssl.sh
```
and each child printing "Fatal error: URI comes last". A malformed file "my" is created that contains, for each row in "testlist.txt", the fatal error message and an HTML footer.

I tried to find a way to correct the command lines for the child processes, but nothing I tried worked.

**Comment by drwetter** [comment]
Short look at during lunch break:

It seems to me that the children need quotes or escaping the blanks too. Which probably requires all ``--XXXXfile`` and friends to be parsed for blanks at a certain time, e.g. in run_mass_testing

Maybe it is more elegant to escape the blanks with a backslash in the file names there...

**Comment by dcooper16** [comment]
I just submitted PR #706 to address this issue. I followed the guidance in http://mywiki.wooledge.org/BashFAQ/050, which suggests that in `run_mass_testing()` the command to create the child processes should be passed an array with the command line arguments rather than a string. I also followed one of the suggestions in http://stackoverflow.com/questions/10835933/preserve-quotes-in-bash-arguments in order to print the command line within `run_mass_testing`.

I left the `$CMDLINE` string unchanged, though. This means that if testssl.sh is called as follows:
```
bash testssl.sh --jsonfile-pretty "out file.json" --logfile "out file.log" 127.0.0.1
```
the "Invocation" line in the JSON file will be:
```
"Invocation"  : "testssl.sh --jsonfile-pretty out file.json --logfile out file.log 127.0.0.1",
```
and the first line of the log file will be
```
## Scan started as: "testssl.sh --jsonfile-pretty out file.json --logfile out file.log 127.0.0.1"
```

This is a bit misleading, since it makes it appear as if the invocation line was actually malformed, but http://jsonlint.com indicates that backslash characters cannot be used.

**Comment by dcooper16** [comment]
I made some more improvements to PR #706 this morning. It now uses an alternative approach from http://stackoverflow.com/questions/10835933/preserve-quotes-in-bash-arguments to create the command line string for printing (the approach described as "If you want to print the argument list as close as possible to what the user probably entered"). This approach places file names that have spaces in single quotes rather than using backslashes. So, the resulting string can be used for `$CMDLINE` as well in `run_mass_testing()` and `run_mass_testing_parallel()`.

**Comment by drwetter** [comment]
closing via #706
