### ISSUE TITLE
Multiple functions of -h flag

### ISSUE THREAD

**Issue by gniltaws** [drwetter/testssl.sh#717]
According to testssl's help, `-h` is used to both show help and gather the server headers.  In practice, `-h` will show the help, because that option is first in the `case` switch in `parse_cmd_line`. v I think I remember using `-H` to do this in the past, but that now does the heartbleed test.  

``` 
./testssl.sh --help | grep -i -- '-h,'
     -h, --help                    what you're looking at
     -h, --header, --headers       tests HSTS, HPKP, server/app banner, security headers, cookie, reverse proxy, IPv4 address
     -H, --heartbleed              tests for heartbleed vulnerability
```

I would suggest removing `-h` from the header option (and I'd be happy to submit a pull request for that), but I wasn't sure what your preference would be.

**Comment by drwetter** [comment]
Thanks for catching this!

Decided just the opposite :-) I'd like to keep the short and long options for the important stuff and help has already two options (besides ``help`` just run `testssl.sh`` wo/o anything)

**Comment by gniltaws** [comment]
Glad to help.

On a similar note, I just noticed that the usage section on https://testssl.sh/ shows:

- `-h` for help
- `-H` for headers
- `-B` for heartBleed

**Comment by drwetter** [comment]
yes, the web site is reflecting always the status of stable. Maybe I should clarify this better

**Comment by drwetter** [comment]
done :)
