### ISSUE TITLE
Support testing against Windows server OS

### ISSUE THREAD

**Issue by jauderho** [drwetter/testssl.sh#720]
Given the likelihood of someone using a browser/web server on a Windows server OS, it might be a good idea to provide tests against 2008, 2012 etc.

**Comment by drwetter** [comment]
What exactly: webbrowser on 2012 etc in the client simulation? 

Don't know whether there is a difference to the corresponding client OS. But testssl.sh uses the api from SSLlabs. We can supply separate data but would need then a handshake (pcap). 

Question is whether this is to be included in the standard run then. Unless it is a terminal server, this is not a scenario which is often used.. 

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by drwetter** [comment]
I do not have a server handy but if enough people raise their arms and feel this is important, we could include a client hello.

One can convert the TLS handshake with https://github.com/drwetter/testssl.sh/blob/2.9dev/utils/wireshark2ciphers.pl .
