### ISSUE TITLE
Add browser simulation for Edge 15

### ISSUE THREAD

**Issue by jauderho** [drwetter/testssl.sh#722]
It looks like Edge 15 ships as part of the Creators Update. Additionally, it's interesting to note that Edge 15 seems to only support TLSv1.2.

**Comment by drwetter** [comment]
ok, thx.

The SSLlabs API doesn't show it yet.

**Comment by jauderho** [comment]
I used the SSLLabs Client test.

**Comment by drwetter** [comment]
Well, then your client is being tested. That doesn't help me unfortunately.

If SSLlabs doesn't provide the data at a certain point an alternative might be to used the/a wireshark script to record the client hello.

**Comment by dcooper16** [comment]
I was just looking at https://api.dev.ssllabs.com/api/v3/getClients and see that it now has data for Edge 15, so it may be time to update etc/client-simulation.txt.

There is also data for Chrome 65, Firefox 59, Java 8u161, and Java 9.0.4.

**Comment by drwetter** [comment]
Thanks for the hint, @dcooper16 . Maybe I should monitor this.

If I counted correctly it's one handshake less. I didn't include Android clients to show up per default anymore which are according to http://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide @ 1% (100%=all Android versions) or less.
