### ISSUE TITLE
Scan Both IPv4 and IPv6

### ISSUE THREAD

**Issue by Night1** [drwetter/testssl.sh#723]
Hey!

Awsome script, I was wondeirng if one could scan both IPv4 and IPv6 or atleast have an option to force scan? 

irc RFC correct IPv6 should be preferd over v4 when v6 is detctec?

**Comment by drwetter** [comment]
Hey there too,

``-6`` scans _also_ for IPv6 addresses  (see help). However it's not enabled by default as a) it requires openssl binaries with IPv6 support, e.g the supplied ones. b) the network has to be IPv6 aware... which testssl.sh can't tell w/o doing ugly stuff.

If you only want to scan the IPv6 address you can supply it with ``--ip=``.

I don't care in scanning about the order as it is a test which checks all IP addresses. A browser/client uses only the first one which works.

Cheers, Dirk

**Comment by Night1** [comment]
Thank you for response, I do reliase that not everyone has dual stack network, so  for sslscan to asume it would be daft and as you stated to test for v6 is not as easy at it might have should been.   

For my rigg i  use current branch from git for openssl and is able to get working with v6 and with some modifications to sslscan.sh tlsv1.3-draft19 

Thank you for your response.
