### ISSUE TITLE
Why does FreeBSD need /dev/fd or fdescfs?

### ISSUE THREAD

**Issue by bknowles** [drwetter/testssl.sh#727]
Folks,

I saw #258, #398, and #441.  But what is not clear to me is why this is a problem at all on FreeBSD?  Why do we need `/dev/fs` or `fdescfs` at all?

Of course, I have an older FreeBSD machine that I would like to use for testing SSL connections, but I can't do that because this version is old enough that the `fdescfs` module doesn't exist, and so I can't use `testssl.sh` at all on this machine.

So, why do we have this dependency at all on FreeBSD?

**Comment by drwetter** [comment]
Hi,

that's a bash process thing  under FreeBSD (see e.g. https://lists.gnu.org/archive/html/bug-bash/2004-10/msg00080.html). Testssl.sh provides help resolving it. fdescfs should be available, but I am not enough of a FreeBSD expert and have not crystal ball why it is not in your case :)

Somebody else can help him?

Cheers, Dirk

**Comment by kraigu** [comment]
I don't know how old the version is OP is running that doesn't have fdescfs, but it seems to me that it must be incredibly ancient. A newer thread on fdescfs and why you might (or might not) need it:

https://forums.freebsd.org/threads/50214/

I probably don't have time to test myself right now, but I'd suggest that the OP try commenting out the helper bits from testssl and see how it runs on his system - but I'd suggest any truly ancient system might have plenty of other problems that might prevent testssl from running... like ancient versions of bash in ports. :)  OP, what version are you running, exactly?

**Comment by drwetter** [comment]
doing some housekeeping. Shouldn't stop the conversation though...
