### ISSUE TITLE
Issue on BEAST check

### ISSUE THREAD

**Issue by federicodotta** [drwetter/testssl.sh#734]
Hi! I found some differences in output of CBC check of testssl.sh and the output of other tools (like Qualys SSL Server Test). Sometimes testssl.sh says that the target server is vulnerable to Beast and the other tool that is mitigated server-side. I searched for CBC mitigations and one of them is reduce the lifespan of the SSL session. Is it possible that testssl.sh does not check for this mitigation in CBC check?

Thank you a lot for your great work!

**Comment by drwetter** [comment]
Hi there,

unless the server doesn't support TLS >=1.1 you get a similar message in testssl.sh (``VULNERABLE -- but also supports higher protocols (possible mitigation): TLSv1.1 TLSv1.2``)

The TLS session lifetime, practically maybe, haven't read about it and the original publication doesn't contain any hint. BEAST is anyway a vulnerability which requires at least control over the content in the browser, so speaking about practice this means that there are worse problems (control over the content in the browser means "game over").

SSLlabs.... I am not quite sure what the criteria is for server-side mitigation. The link close to the result points to an old document. As said testssl.sh considers it mitigated if a higher protocol is being offered by the server whereas SSLlabs does not. What counts here is what the client is choosing (protocol and cipher). For the general problem regarding cipher block chaining testssl.sh has also a check for ciphers >=TLS1.1 : LUCKY13.

Cheers, Dirk

**Comment by federicodotta** [comment]
Thank you a lot for your explanation!

Federico
