### ISSUE TITLE
Fails due to DNS resolution while accessing via proxy

### ISSUE THREAD

**Issue by techpavan** [drwetter/testssl.sh#748]
Hi,
testssl.sh when attempted to route via proxy is trying to do a host name resolution and fails as the host name does not resolve to a valid IP address. As the requests are routed via proxy, it is not expected that the machine where tests are run would be able to resolve the host address mentioned.

> 
> ###########################################################
>     testssl.sh       2.8 from https://testssl.sh/
>     (1.582 2017/05/10 19:04:47)
> 
>       This program is free software. Distribution and
>              modification under GPLv2 permitted.
>       USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!
> 
>        Please file bugs @ https://testssl.sh/bugs/
> 
> ###########################################################
> 
>  Using "OpenSSL 1.1.0e  16 Feb 2017" [~144 ciphers]
>  on user-w01:/c/OpenSSL-Win64/bin/openssl.exe
>  (built: "reproducible build, date unspecified", platform: "")
> 
> 
> mywebsite.com:443
> /
> Fatal error: No IPv4 address for "mywebsite.com" available
>

**Comment by drwetter** [comment]
Thx for the feedback.

Yup, this is known, see #739. However some want a local DNS resolution. 
Don't know yet whether I'll address this in 2.8 too.

**Comment by techpavan** [comment]
Thanks for the quick response. Hope to get a fix in upcoming newer versions.

**Comment by drwetter** [comment]
in the meantime ``--ip=<ipaddress>`` should serve as a workaround, albeit admittedly it's not really convenient

**Comment by drwetter** [comment]
WIP, see changelog in d64fabafd5fe62fa9192aca3b75c3689dcab46cb

**Comment by techpavan** [comment]
Glad that you did it. Will check that next time when I work on a similar environment.

**Comment by drwetter** [comment]
Won't do this anymore in 2.8. Please use 2.9.5 or 2.9dev
