### ISSUE TITLE
please add option to have testssl.sh fail (non-zero return code) if warnings or failures detected

### ISSUE THREAD

**Issue by jessefarinacci** [drwetter/testssl.sh#752]
Please add an option to have testssl.sh fail with a non-zero return code if it detects problems with an SSL configuration. This will let it play more nicely in our automation setups where we are running testssl.sh periodically. Having the CI build fail will make it more clear to our teams that there is something wrong without having to manually inspect the console output every time. Thanks! :smile:

**Comment by drwetter** [comment]
possible overlap with #327 -- maybe it just needs to be defined what the return value of a failure is as opposed to a finding, see https://www.monitoring-plugins.org/doc/guidelines.html

**Comment by jessefarinacci** [comment]
Sorry, I didn't see that one previously. Yes, #327 would solve my requirement. Closing this issue, thanks for the reference. I subscribed to #327.

**Comment by drwetter** [comment]
No prob, @jessefarinacci . Lets leave this open just to get the proper attention and also for discussion.

**Comment by trondvh** [comment]
+1

**Comment by drwetter** [comment]
Failures is the easy bait as opposed to nagios/icinga status, so I changed this to be hopefully included into next release.

**Comment by jeff1985** [comment]
I'm also searching for a way to integrate this tool to a CI server! Would be great, if you could implement this feature request!

**Comment by drwetter** [comment]
@jeff1985  For CI are your looking for exit codes in terms of rating or successful completion of the tests?

**Comment by jeff1985** [comment]
@drwetter yes, my idea is to run the checks and have them fail, if the certificate is outdated or any problem persists. for this I need a non-zero error code.

**Comment by drwetter** [comment]
closing now, see #985
