### ISSUE TITLE
BEAST and multiple IPs

### ISSUE THREAD

**Issue by Abb4d0n** [drwetter/testssl.sh#757]
By scanning a domain which resolves to more than one IP address, the first scanned IP is vulnerable to BEAST (TLSv1 and CBC ciphers) whereas the others (also TLSv1 and CBC ciphers) are marked with "no CBC ciphers found for any protocol (OK)". An example URL is github.com.

My request was: `./testssl.sh github.com`

**Comment by drwetter** [comment]
Thx for reporting
