### ISSUE TITLE
FreeBSD hangs on Testing Protocols

### ISSUE THREAD

**Issue by feld** [drwetter/testssl.sh#77]
On FreeBSD 10.1 the Testing Protocols seems to take forever... it's hanging while running locally_supported()

/usr/bin/openssl s_client -ssl3 SSLv3 | grep -q 'unknown option'

Not sure what's causing this right now because running that in a bash shell works just fine...

**Comment by drwetter** [comment]
Thx for reporting.

I labeled this as a bug though probably the openssl binary is to blame here.(on 10.0 it works for me).

In this release I will finalize the protocol check for HTTP via sockets. Pls let me now if

    DEBUG=3 ./testssl -q 00 <URI> 

(^^preview of what to come) or 

    ./testssl.sh -t smtp smtp.gmail.com:25

makes problems now.

**Comment by drwetter** [comment]
With the exception of STARTTLS or providing SSL_NATIVE=1 that should work now as also for SSLv3 sockets are used in the protocol check. 

If not, reopen this open pls.
