### ISSUE TITLE
Certificate Transparency

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#771]
I believe that testssl.sh should add a test for [Certificate Transparency](https://www.certificate-transparency.org/). Google Chrome plans to require Certificate Transparency for all publicly-trusted certificates starting in April 2018 (https://groups.google.com/a/chromium.org/forum/#!msg/ct-policy/sz_3W_xKBNY/6jq2ghJXBAAJ) and other browsers may choose to require it as well.

I have started work on code to test for Certificate Transparency at https://github.com/dcooper16/testssl.sh/tree/certificate_transparency. It seems to be working correctly, but it could certainly use more testing. Please try the code out and let me know if you discover any problems.

CT allows for information to be provided to the client in three ways: certificate extension, OCSP extension, TLS extension. I have tested the code with sites that use certificate and TLS extensions, but have not yet encountered a site that provides CT information in a stapled OCSP response.

For each certificate returned by the server, the code first checks whether the certificate includes a signed certificate timestamp (SCT) extension. If it doesn't, then checks whether the stapled OCSP response (if any) included an SCT extension. The second check specifically looks at the OCSP response provided to `get_server_certificate()` in the same call as the one that resulted in the certificate being checked.

If neither the certificate nor the OCSP response included an SCT extension, then a check is made for a TLS extension. `determine_tls_extensions()` (attempts to) check whether the server returns an SCT TLS extension.  So, if the server only has one certificate, then the code simply checks whether `$TLS_EXTENSIONS` lists the SCT extension.

If the server has more than one certificate, then it is possible that the server returns an SCT TLS extension for some but not all of its certificates. So, if the server has more than one certificate, then the code tries to re-create the call that `get_server_certificate()` made (same TLS version and cipher suites), but with a request for a TLS SCT extension. I have already found one server that returns a TLS SCT extension along with some, but not all, of its certificates, so in order to be accurate the check for the TLS SCT extension needs to be repeated for each of the server's certificates.

**Comment by drwetter** [comment]
Cool! 

⁣-- 
Sent via mobile. Excuse my brevity, typos and the autocorrection​

**Comment by dcooper16** [comment]
I just did some reorganizing of the code that I wrote for certificate transparency (CT).

Currently, testssl.sh only checks for the CT TLS extension ("signed certificate timestamps/#18") in a single call to `tls_sockets()` in `determine_tls_extensions()`. However, as I previously noted, I've encountered one server that has multiple certificates, where for some certificates the CT information is provided in a certificate extension and for others it is provided in a TLS extension. In this case, the certificate returned in response to the call to `tls_sockets()` in `determine_tls_extensions()` contains a CT extension, so no CT TLS extension is returned and "signed certificate timestamps/#18 is not included in the "TLS extensions (standard)" line.

In the reorganized code that I just posted, all of the calls to `certificate_transparency()` are made before the "TLS extensions (standard)" line is printed, and if any call to `certificate_transparency()` results in a call to `tls_sockets()` in which the server returns a CT TLS extension, then that extension is added to `$TLS_EXTENSIONS` before the "TLS extensions (standard)" line is printed.

I placed the calls to `certificate_transparency()` after the call to `determine_tls_extensions()` so that no additional tests are performed against the server in the common case in which the server has only one certificate.

**Comment by dcooper16** [comment]
I did some testing against a set of U.S. government servers, and here is what my code found. Of the 822 certificates detected Certificate Transparency information was provided for 429 of the certificates.

- For 389 of the certificates, the information was included in the certificate (i.e., a certificate extension).
- For 40 of the certificates, the information was provided in a TLS extension in the ServerHello.

My code did not detect any servers that provided Certificate Transparency information in a stapled OCSP response (either because no servers provided the information in this way or because there is a flaw in my code). The code did, however, detect 65 certificates for which a stapled OCSP response was provided, but (apparently) no Certificate Transparency information was provided.

**Comment by drwetter** [comment]
I think we can close this as your PR has been merged. The remainder (CT in stapled response) is a niche thing IMO. If you feel like adding this or consider this an issue which needs to be kept in mind, I supposed we'll see a PR or an issue filed from you anyway :-)
