### ISSUE TITLE
OpenSSL 1.1.1 and SNI

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#772]
As a result of #276 testssl.sh includes some tests that specifically check what a server returns when the ClientHello does not include an SNI extension. Currently, this is done by not including the `-servername` option in the call to `$OPENSSL s_client`. It appears, however, that starting with OpenSSL 1.1.1 this will no longer work.

In doing some tests against www.cloudflare.com I noticed that the server's SHA-1 certificate was being detected if OpenSSL 1.0.2-chacha was used, but not if OpenSSL 1.1.1 was used. I discovered that the problem is that OpenSSL 1.1.1 is including an SNI extension in the ClientHello even if the `-servername` option is not used; it populates the SNI extension with the value from the `-connect` option, even if it is an IP address. [I think this is a violation of RFC 6066, which seems to only allow DNS names in the SNI extension.]

This can be fixed in OpenSSL 1.1.1 by including the `-noservername` option in the `$OPENSSL s_client` command. So, I think that a check for `-noservername` needs to be added to `find_openssl_binary()` and then, wherever needed, the `-noservername` option needs to be added to the `$OPENSSL s_client` command line if `$SNI` is empty and the `-noservername` option is supported.

**Comment by drwetter** [comment]
Hi David,

thx & merged, after compiling a newer 1.1.1 version. The one I had from the end of April still showed the SHA1 cert.

What's bugging me a bit is that the openssl call became less transparent as a function is used which does the magic of supplying command line args or not (readability).

Cheers, Dirk
