### ISSUE TITLE
GREASE

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#791]
This is a follow up to #494 (which is about testing whether server's properly support version negotiation):
> Actually I thought it would be a good idea to reimplement a tolerance test for 2.9dev.

The IETF TLS WG adopted [draft-ietf-tls-grease](https://datatracker.ietf.org/doc/draft-ietf-tls-grease/) (Generate Random Extensions And Sustain Extensibility), which in some ways is an extension of the version tolerance test. The idea is to introduce unknown values into various places where the standard calls for servers to ignore unknown values in order to test that servers correctly ignore unknown values.

According to one [email](https://mailarchive.ietf.org/arch/msg/tls/k1KfZGwAGnZYgAsLN2sztRw5APc) on the TLS WG mail list, this technique has already been used to discover an implementation that would have failed a version tolerance test (based on TLSv1.3's new method of version negotiation).

I may be too early to implement [draft-ietf-tls-grease](https://datatracker.ietf.org/doc/draft-ietf-tls-grease/) (code points haven't been assigned yet), but we should consider whether testing of this sort should be added to testssl.sh at some point in the future.

**Comment by drwetter** [comment]
To me it sounds certainly an interesting idea. Chrome/Chromium make use of it since last fall IIRC.

The test would be separate then and checking whether the server responds in a not compliant way (aborts, hangs etc) ?

**Comment by dcooper16** [comment]
Yes, I think this should be a separate test. testssl.sh currently has tests to check for certain vulnerabilities (e.g., heartbleed), but otherwise it doesn't tend to check for implementation bugs that don't lead to security vulnerabilities. In fact, it does just the opposite; it silently tries to work around implementation bugs in order to correctly determine information about a server's configuration. For example, tests to determine what cipher suites a server supports are written to work around servers that have problems with ClientHello messages with more than 128 ciphers.

I think we should continue that idea; have other tests work around implementation bugs and have a separate test that looks for them.

**Comment by drwetter** [comment]
Assigned this one to me too. I am just scratching my head whether one or the other test should make it into the default run. Everything would be too much as the test consumes too much time. 

Last but not least SSLlabs has also ~3 checks.
