### ISSUE TITLE
Direct use of sed -E

### ISSUE THREAD

**Issue by matya** [drwetter/testssl.sh#798]
In function `run_hpkp` you use `sed -E` regardless of what you have found out via `HAS_SED_E`:

`sed -E 's/[^[:digit:]]//g'`

Full line:
```
hpkp_age_sec=$(awk -F= '/max-age/{max_age=$2; print max_age}' $TMPFILE | sed -E 's/[^[:digit:]]//g')
```
This breaks older sed versions that do not support `-E`, only `-r`.

**Comment by drwetter** [comment]
thx for noticing.
