### ISSUE TITLE
Inconsistent cipher lists in run_std_cipherlists()

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#802]
I tried running `run_std_cipherlists()` against a server that only supports one cipher: AES256-SHA. When using `--ssl-native` "High encryption (AES+Camellia, no AEAD)" is listed as offered, but when using sockets all categories report "not offered."

It seems that the definitions of the categories are not defined consistently between sockets and OpenSSL. For "High encryption" the definitions are:
```
# ~ equivalent to 'grep -w "GOST|128" etc/cipher-mapping.txt | grep -v '=None' | egrep -vw 'RC4|AEAD|IDEA|SEED|RC2'
```
and
```
HIGH:!NULL:!aNULL:!DES:!3DES:!AESGCM:!CHACHA20:!AESGCM:!CamelliaGCM:!AESCCM8:!AESCCM
```
The OpenSSL list includes 256-bit AES and Camellia ciphers, but the only 256-bit ciphers included in the sockets list are GOST ciphers.

I haven't done any other consistency checks, so I don't know whether there are any other discrepancies between the OpenSSL and sockets definitions.

**Comment by drwetter** [comment]
Thx for spotting this

**Comment by drwetter** [comment]
For the record: This is the difference after getting this corrected  -- left hand side openssl from Peter, right hand side sockets. (I didn't configure openssl to use GOST ciphers):

![diff](https://user-images.githubusercontent.com/8036727/28823059-15eeec16-76bc-11e7-956e-af9e1e2fb337.png)
