### ISSUE TITLE
HPKP "max-age" suggestion using wrong unit/unrealistic

### ISSUE THREAD

**Issue by m-ueberall** [drwetter/testssl.sh#808]
Excerpt from the HTTP header response test using testssl.sh 2.9dev (69eefee 2017-07-31 23:21:49 --):
` Strict Transport Security    365 days=31536000 s, includeSubDomains, preload`
` Public Key Pinning           6 keys, 86400 s = 1 days (<2592000 days is not good enough), includeSubDomains`

The suggested `max-age` setting seems to be 30 **days** (2592000 **seconds**) here as 7000+ years seems a bit unrealistic.

**Comment by drwetter** [comment]
thx
