### ISSUE TITLE
RFE: Add Windows CE / Windows Mobile 6 & 6.5 client test

### ISSUE THREAD

**Issue by CRCinAU** [drwetter/testssl.sh#819]
Sadly in the handheld industry, there is a ton of Windows CE 6 / 6.5 device still being sold today.

It would be very helpful to the poor system admins if this was represented in the client list to show if these devices will be able to connect.

**Comment by drwetter** [comment]
If somebody has the handshake data I am happy to add it. The wireshark script in the utils directory might come handy...

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by CRCinAU** [comment]
For the record, I have tried high and low to try and locate a concrete list - but nothing has been forthcoming.

If anybody does have this list, or a way to determine the list, I'm all ears.

**Comment by drwetter** [comment]
belongs to #1158
