### ISSUE TITLE
/etc/hosts with aliases and comments interpreted in a strange way

### ISSUE THREAD

**Issue by unixhex** [drwetter/testssl.sh#82]
very useful tool, but currently one needs to have a clean /etc/hosts ...

here the last lines of a valid /etc/hosts file, with aliases, the last line is commented

```
128.66.0.1    www.example.com blog.example.com test1
#128.66.0.2    example.org foo.example.org test2
```

case 1) test for line with aliases (without comment)
```
$ testssl.sh www.example.com
#########################################################
testssl.sh v2.3dev  (https://testssl.sh)
($Id: testssl.sh,v 1.229 2015/04/16 18:28:28 dirkw Exp $)

   This program is free software. Redistribution + 
   modification under GPLv2 is permitted. 
   USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

 Note: you can only check the server with what is
 available (ciphers/protocols) locally on your machine!
#########################################################

 Using "OpenSSL 1.0.1k 8 Jan 2015" [~109 ciphers] on
 hellaslaptop:/usr/bin/openssl
 (built: "Mar 19 15:25:09 2015", platform: "linux-x86_64")

/usr/local/bin/testssl.sh: line 1657: 128.66.0.1www.example.comblog.example.comtest1: Name or service not known
/usr/local/bin/testssl.sh: line 1657: /dev/tcp/128.66.0.1www.example.comblog.example.comtest1/443: Invalid argument
Unable to open a socket to 128.66.0.1www.example.comblog.example.comtest1:443 
Ignore? 
```

case 2)
test for host entry which is commented in the /etc/host (and should be completely ignored)

```
$ testssl.sh example.org
[...]
/usr/local/bin/testssl.sh: line 1657: #128.66.0.2example.orgfoo.example.orgtest2: Name or service not known
/usr/local/bin/testssl.sh: line 1657: /dev/tcp/#128.66.0.2example.orgfoo.example.orgtest2/443: Invalid argument
Unable to open a socket to #128.66.0.2example.orgfoo.example.orgtest2:443
Ignore? 
```
---

This did happen of course with real server names first,  but I did chose to protect the innocent (servers, if not admins ;-) ).

**Comment by drwetter** [comment]
Am 18. April 2015 15:59:42 MESZ, schrieb Hella Breitkopf <notifications@github.com>:
>here the last lines of a valid /etc/hosts file, with aliases, the last
>line is commented
>
>```
>128.66.0.1    www.example.com blog.example.com test1
>#128.66.0.2    example.org foo.example.org test2
>```
>
>case 1) test for line with aliases (without comment)
>```
>$ testssl.sh www.example.com
>#########################################################
>testssl.sh v2.3dev  (https://testssl.sh)
>($Id: testssl.sh,v 1.229 2015/04/16 18:28:28 dirkw Exp $)
>
>   This program is free software. Redistribution + 
>   modification under GPLv2 is permitted. 
>   USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!
>
> Note: you can only check the server with what is
> available (ciphers/protocols) locally on your machine!
>#########################################################
>
> Using "OpenSSL 1.0.1k 8 Jan 2015" [~109 ciphers] on
> hellaslaptop:/usr/bin/openssl
> (built: "Mar 19 15:25:09 2015", platform: "linux-x86_64")
>
>/usr/local/bin/testssl.sh: line 1657:
>128.66.0.1www.example.comblog.example.comtest1: Name or service not
>known
>/usr/local/bin/testssl.sh: line 1657:
>/dev/tcp/128.66.0.1www.example.comblog.example.comtest1/443: Invalid
>argument
>Unable to open a socket to
>128.66.0.1www.example.comblog.example.comtest1:443 
>Ignore? 
>```
>
>case 2)
>test for host entry which is commented in the /etc/host (and should be
>completely ignored)
>
>```
>$ testssl.sh example.org
>[...]
>/usr/local/bin/testssl.sh: line 1657:
>#128.66.0.2example.orgfoo.example.orgtest2: Name or service not known
>/usr/local/bin/testssl.sh: line 1657:
>/dev/tcp/#128.66.0.2example.orgfoo.example.orgtest2/443: Invalid
>argument
>Unable to open a socket to
>#128.66.0.2example.orgfoo.example.orgtest2:443
>Ignore? 
>```
>---
>
>This did happen of course with real server names first,  but I did
>chose to protect the innocent (servers, if not admins ;-) ).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/issues/82

Hi Hella,

thx for reporting. I'll fix that stupid error soon.

Cheers, Dirk 

PS: good hearing  from you

**Comment by drwetter** [comment]
fixed & tested.
