### ISSUE TITLE
JSON output to /dev/stdout and /dev/stderr not working

### ISSUE THREAD

**Issue by Vallant** [drwetter/testssl.sh#822]
Hello, for another application i need the output of testssl structured as json, however i do not want to write and then again read the file. Therefore i tried to append the output to /dev/stdout and /dev/stderr, however with JSON this seems not to work. It is possible to write CSV to /dev/stderr, it is not working with /dev/stdout as well though. 

testssl.sh --jsonfile /dev/stderr --append github.com #not working
testssl.sh --csvfile /dev/stderr --append github.com #working

**Comment by drwetter** [comment]
Don't know why stderr works in the first place and also why you want to do this... :-) Fifo or different file handle should be worth a try on your side.

The only difference in the code I spotted was that the CSVFILE was opened with echo and the JSONFILE w printf. I straightened this despite it didn't help.

I'll leave this open for a while. If nobody picks this up, I'll probably close it.

**Comment by dcooper16** [comment]
I traced the "problem" to the following line in `fileout()`:
```
[[ -f "$JSONFILE" ]] && (fileout_json_finding "$1" "$severity" "$finding" "$cve" "$cwe" "$hint")
```
According to the bash man page, "-f" is "True if file exists and is a regular file." Based on my testing, `/dev/stdout` and `/dev/stderr` are not "regular" files; they exist (`-e`), but are not regular (`-f`):
```
> [[ -e testsslNIST.sh ]] && echo "yes" || echo "no"
yes
> [[ -f testssl.sh ]] && echo "yes" || echo "no"
yes
> [[ -e /dev/stdout ]] && echo "yes" || echo "no"
yes
> [[ -f /dev/stdout ]] && echo "yes" || echo "no"
no
> [[ -e /dev/stderr ]] && echo "yes" || echo "no"
yes
> [[ -f /dev/stderr ]] && echo "yes" || echo "no"
no
```
I don't know why `-f` was used here, but I don't understand how writing the JSON or CSV output to stdout or stderr would work. How would the application that wants to consume the JSON or CSV separate the JSON or CSV from the other text that testssl.sh writes to stdout and stderr?

**Comment by drwetter** [comment]
> How would the application that wants to consume the JSON or CSV separate the JSON or CSV from the other text that testssl.sh writes to stdout and stderr?

exactly. In the long run we may use this fd for other things.

**Comment by Vallant** [comment]
Hi,
I want to use testssl as a part of a python program, i use it with python 
submodules, i redirect the regular outpout of testssl to /dev/null and pipe 
the output of stderr (where i let the program write the csv output).
I know that it would be possible to write a file and parse it afterwards, 
but as i want to use it in a server scenario i want to do it in-memory only.

Maybe this could be a kind of a feature request too- to get the structured 
output to the stdout with a command line flag as well? :-)

**Comment by drwetter** [comment]
Thx, @dcooper16 . I changed that -- no pain.

@Vallant : I can't guarantee it'll work forever. Trying another file descriptor or using mkfifo should be worth a try
