### ISSUE TITLE
Apple certificate store update

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#824]
Any volunteers? By next Monday preferably. Instructions here: 
https://github.com/drwetter/testssl.sh/tree/2.9dev/etc

(sorry, edited due to c&p error)

**Comment by fishouttah20** [comment]
[Apple.zip](https://github.com/drwetter/testssl.sh/files/1309014/Apple.zip)

168 certs from OSX 10.12.6 

Your instructions indicated going to "System" (in Keychain Access) but in 10.12.6 it looks like there is a "System Roots" section where these have all been moved to.

**Comment by naumanshah03** [comment]
[apple.zip](https://github.com/drwetter/testssl.sh/files/1309969/apple.zip)
 188 certs from OSX 10.11.6 (El Capitan). Selected all the certs except for **Developer ID Certification Authority**

Updated Procedure for Apple certs extraction https://github.com/drwetter/testssl.sh/blob/2.9dev/etc/README.md

1. open Keychain Access utility (Application -> Utilities)
OR
perform a Spotlight Search for Keychain Access

2. From the left pane in Keychains select System Roots and in Category select Certificates

3. All the certificates will be displayed in the right pane. Select all of them except for Developer ID Certification Authority and right-click select “Export n items”

**Comment by drwetter** [comment]
Ok, thanks a lot guys! 

@naumanshah03: Why would I want to consider the older OS? For the instructions: how about a PR?

**Comment by naumanshah03** [comment]
Actually, I had access to OSX 10.11.6 (El Capitan) that's the reason why I added the following zip file from the given version of OS. PR what does that mean?

**Comment by fishouttah20** [comment]
FYI, I went back through just to make sure I got all the certs when I extracted by mirroring the method naumanshah03 outlined and it resulted in the same 168 certs.

**Comment by drwetter** [comment]
ok, thx

**Comment by drwetter** [comment]
Time for an update again.

Anybody can help here for the 3.0 release?

**Comment by drwetter** [comment]
done via  f708e14
