### ISSUE TITLE
MS certificate store

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#825]
The solution current described @ https://raw.githubusercontent.com/drwetter/testssl.sh/8b076e9841bfc9e48593f6bb576e00af5e5bee64/etc/README.md for extracting Windows OS certificates doesn't work really good as it is been populated over time.

MS published a list of currently trusted CAs @ https://gallery.technet.microsoft.com/Trusted-Root-Certificate-123665ca . In total a whopping 300-something CAs. 

How to retrieve them **completely** either from a running OS or from *.microsoft.com ?

**Comment by drwetter** [comment]
Maybe somebody can step in here? I edited the excel file from MS with the CA names and fingerprints and exported it to a CSV file to https://gist.github.com/drwetter/7061eb1ce63926cf9cf82ba5745a50fe . 

As the certificates are public it should be possible to retrieve them from anywhere

**Comment by naumanshah03** [comment]
Make use of this tools in windows which will give you all the certs by using Windows Update
https://technet.microsoft.com/en-us/library/dn265983(v=ws.11).aspx#BKMK_CertUtilOptions
Write a script and extract all those certs into a single file as .pem format

**Comment by Niko78** [comment]
Hi Dirk,
last time I gave you the list I used that :
https://blogs.technet.microsoft.com/parallel_universe_-_ms_tech_blog/2015/10/22/export-all-your-trusted-root-certificate-from-local-machine-store/

**Comment by drwetter** [comment]
hi @Niko78 ,

from local machines that doesn't work as the result is not complete, MS distributes a base set and only if needed the third party store (and maybe primary) are being populated over time. I collected from 1x win 7, 1x win 8.1 and 1x win10 machines all certificates and retrieved ~80. MS (see gist) allows up to ~300.

Practically I cannot use one other machine I used last / beginning of this year, so my personal engagement which wasn't technically limited anyway is now barely enough. If there are better means (see @naumanshah03 ), I'd go that way -- however I'll take everything what is being offered ;-)

I barely remember though you gave me s.th. last time. I only remember probs with 2-3 hosts of yours. Pointer?

Cheers, Dirk

**Comment by drwetter** [comment]
Hi @naumanshah03 ,

> Make use of this tools in windows which will give you all the certs by using Windows Update
https://technet.microsoft.com/en-us/library/dn265983(v=ws.11).aspx#BKMK_CertUtilOptions
Write a script and extract all those certs into a single file as .pem format

would you be able to help? 

Cheers, Dirk

**Comment by drwetter** [comment]
@naumanshah03 : cool thank you!

I tried ``CertUtil –generateSSTFromWU TRoots.sst`` and then ``start explorer.exe TRoots.sst`` but ended up again with 84 certificates only .

**Comment by naumanshah03** [comment]
Hi @drwetter 
I wrote a Java program to convert the .crts to a single .pem file. Here is the .pem file for all the certs that were received by using CertUtil tool of windows

Here is the windows.pem file which you can verify (Had to rename it to windows.txt)
[windows.txt](https://github.com/drwetter/testssl.sh/files/1314134/windows.txt)
Also, I have added comments above each certificate with its subject name.

Use following command `CertUtil -syncWithWU -f -f .`

PS: The Java program is an ad-hoc program just to perform the above task :)

**Comment by drwetter** [comment]
Thx, @naumanshah03 . The crt files seem to be in DER format, so openssl can handle it as well.

Thanks again for your help -- I was looking for that a long while back 👍
