### ISSUE TITLE
Version number testing is invalid for LibreSSL

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#834]
There are several places in testssl.sh in which an action is taken based on which version of OpenSSL is being used. In some cases, the checks do not work correctly if LibreSSL is being used.  Here are some examples:

`determine_trust()`  includes to following code:
```
     if [[ $OSSL_VER_MAJOR.$OSSL_VER_MINOR != "1.0.2" ]] && \
          [[ $OSSL_VER_MAJOR.$OSSL_VER_MINOR != "1.1.0" ]] && \
          [[ $OSSL_VER_MAJOR.$OSSL_VER_MINOR != "1.1.1" ]]; then
          addtl_warning="(Your $OPENSSL <= 1.0.2 might be too unreliable to determine trust)"
          fileout "${json_prefix}chain_of_trust_Problem" "WARN" "$addtl_warning"
     fi
```
  I don't know whether LibreSSL can reliably determine trust, but its version number is not <= 1.0.2.

The version number checks in `run_renego()` don't include LibreSSL versions (or version 1.1.* of OpenSSL).

The check in `find_openssl_binary()`:
```
     case "$OSSL_VER_MAJOR.$OSSL_VER_MINOR" in
          1.0.2|1.1.0|1.1.1) HAS_DH_BITS=true ;;
     esac
```
leaves HAS_DH_BITS as false even though LibreSSL provides this information.

**Comment by drwetter** [comment]
Thanks for pointing this out! Fix follows, except ``run_renego()`` which needs to be done.

HAS_DH_BITS is checked (roughly) later again, see #190 . RH'ish distros backport(ed?) often features into OpenSSL but leave/left the version number as is. This was a kludge but worked.

For LibreSSL that worked probably too but to avoid the kludge a proper patch is now implemented.

**Comment by drwetter** [comment]
that is solved...
