### ISSUE TITLE
Homebrew installation not working due to "No cipher mapping file found!"

### ISSUE THREAD

**Issue by dteirney** [drwetter/testssl.sh#835]
I use homebrew to install testssl.sh. The 2.9.5-1 version is not working due to "No cipher mapping file found!"

ATTENTION: No cipher mapping file found!
Please note from 2.9dev on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.

Type "yes" to ignore this warning and proceed at your own risk -->

Not sure if it's an issue with the homebrew formula or something else. Any idea?

https://github.com/Homebrew/homebrew-core/blob/master/Formula/testssl.rb

**Comment by drwetter** [comment]
Hi there,

thx for reporting . Not sure why as in the release there should be a cipher mapping file.

Can somebody with a Mac help here?

Cheers, Dirk

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by doublewooly** [comment]
@dteirney What Mac OS version?

**Comment by dteirney** [comment]
macOS Sierra, but I just updated to macOS High Sierra.

I just did a brew upgrade and it looks like something has been updated.

`==> Upgrading 1 outdated package, with result:
testssl 2.9.5-1_1`

And it's working fine now. Yay! So, thank you if something was fixed.

**Comment by drwetter** [comment]
thx @dteirney for feedback and thank a lot @doublewooly for your help so far!
