### ISSUE TITLE
incorrect mappings in openssl-rfc.mapping.html

### ISSUE THREAD

**Issue by lunaqdm** [drwetter/testssl.sh#851]
There seem to be a few incorrect mappings present in the table at https://testssl.sh/openssl-rfc.mapping.html.

Specifically, the ones I've found are:
0x2c - 0x2e: seem to have the incorrect OpenSSL name (though I wasn't able to find the correct names in any OpenSSL documentation, so I can't verify this)
0xcc13 - 0xcc15: I am fairly certain that the cipher suites given by the table do not actually correspond to these numbers (and are not a complete listing of the cipher suites from the RFC), see https://tools.ietf.org/html/rfc7905#section-3

**Comment by drwetter** [comment]
Thx. Generally ``~/etc/cipher-mapping.txt`` --which is used by testssl.sh 2.9+ --is more up to date. If you or somebody else feels like contributing: either an automated generation from the txt file would be 
great or manual sync would be appreciated.

FYI: 0xcc13 - 0xcc15 are the old AGL ciphers which were later superseded by the new ones which made it into a RFC.  The naming scheme from the old ciphers is partly private (openssl name space) and partly borrowed from SSLlabs.
