### ISSUE TITLE
NMAP Intigration

### ISSUE THREAD

**Issue by cyberjacob** [drwetter/testssl.sh#86]
Would it be possible to do some kind of integration with NMAP and scan every open port on the host?

**Comment by drwetter** [comment]
Hi,

Am 04/28/2015 um 01:55 PM schrieb Jacob Mansfield:
> Would it be possible to do some kind of integration with NMAP and scan every open port on the host?

possible it almost everything. Question is whether it makes sense. ;-)

Nmap does a pretty decent job detecting the service behind an open port. Not
every open port is SSL enabled, nmap detects that pretty good too.
If such a port is detected I assume it's not too much asking to just start
testssl.sh .

Cheers, Dirk

**Comment by drwetter** [comment]
Feel free to reopen it if I misunderstood you
