### ISSUE TITLE
CAA record check does not consider whole DNS tree

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#862]
I originally thought that the issue was something else.
---

Old dig output (e.g. OSx):
```
$ dig atom86.net type257 +short
\# 38 0005696F6465666D61696C746F3A6162757365407363687562657267 7068696C69732E636F6D
\# 19 00056973737565636F6D6F646F63612E636F6D
```

Newer dig (e.g. latest Redhat 6.9)
```
> dig atom86.net type257 +short
0 iodef "mailto:abuse@schubergphilis.com"
0 issue "comodoca.com"
```
The latter appears not to be recognized by testssl.sh

**Comment by drwetter** [comment]
hello Frank,

works perfectly for me with e.g. SLES 11 which has the similar (first) output. Actually I was developing almost both the old and new one at the same time.

Do you have more details like OS, version of testssl.sh etc and the output?

Thx, Dirk

**Comment by seccubus** [comment]
We are getting findings that state that their are no CAA records for Atom86.net on the latter system.

**Comment by drwetter** [comment]
As said for me it works as expected. The information you gave me unfortunately doesn't get us further. If you see problems on your side please file a proper bug report in this issue. 

https://github.com/drwetter/testssl.sh/wiki/Bug-reporting

**Comment by seccubus** [comment]
@drwetter I stand corrected, I jumped to conclusions.

When I try to asses www.atom86.net it tells me I have not CAA records.

```
> ./testssl.sh -S www.atom86.net
<snip>
 DNS CAA RR (experimental)    --
<snip>
 DNS CAA RR (experimental)    --
```

However, atom86.net does have a CAA record:
```
> dig atom86.net caa

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.62.rc1.el6_9.4 <<>> atom86.net caa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40822
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;atom86.net.			IN	CAA

;; ANSWER SECTION:
atom86.net.		3600	IN	CAA	0 iodef "mailto:abuse@schubergphilis.com"
atom86.net.		3600	IN	CAA	0 issue "comodoca.com"

;; Query time: 18 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Wed Oct 18 07:26:27 2017
;; MSG SIZE  rcvd: 109
```

Testssl.sh, seems to ignore that CAA validation needs to look 'down' as per https://tools.ietf.org/html/rfc6844#page-7

So for www.atom86.net the CAA records of the following domains need to be examined untill a valid record is found:
* www.atom86.net.
* atom86.net. <- a record is present here
* net.
