### ISSUE TITLE
Litespeed hangers

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#87]
1) HTTP header request
2) Secure Client-Initiated Renegotiation
3) probably also just Renegotiation

**Comment by salt-lick** [comment]
Stevenb18 == me.

Keep up the great work.

**Comment by drwetter** [comment]
cool, thx

**Comment by drwetter** [comment]
Hi @salt-lick ,

could you please test that latest and greatest update? ;-)  2+3 should be addressed. 

As far as 1 is concerned: I haven't changed anything but the node you gave me doesn't stall at the header request anymore. Maybe dm me another one which shows that behaviour?

Cheers, Dirk

**Comment by drwetter** [comment]
Hey @salt-lick 

to me it looks 3)+2) are fixed -- pls have a look @ f3f3967 -- but as for 1) I am still missing the case where it happened.

Cheers, Dirk

**Comment by salt-lick** [comment]
Hey @drwetter, Looks like it does not stall anymore! Great work!

**Comment by drwetter** [comment]
Closing then. Thx for reporting
