### ISSUE TITLE
Use of variable with no value

### ISSUE THREAD

**Issue by dcooper16** [drwetter/testssl.sh#876]
The second call to `$OPENSSL s_client` in `run_server_preference()`  (on line 4816) is as follows:
```
$OPENSSL s_client $(s_client_options "$STARTTLS $STARTTLS_OPTIMAL_PROTO -cipher $list_fwd $BUGS -connect $NODEIP:$PORT $PROXY $addcmd2") </dev/null 2>$ERRFILE >$TMPFILE
```
`$addcmd2` is set to be an empty string at the beginning of the function and isn't set to anything else until after this call.

Originally, `$addcmd2` was set to be `$SNI` if `$STARTTLS_OPTIMAL_PROTO` was not SSLv2 or SSLv3, but then that was removed in the following commit: https://github.com/drwetter/testssl.sh/commit/cca1b4989091ee6ab646e58af80a0fc239617bdf.

I don't have any servers to test this against, but it seems that `$addcmd2` in this line should either be removed or replaced with `$SNI`, depending on the reason the line setting `$addcmd2` was removed in https://github.com/drwetter/testssl.sh/commit/cca1b4989091ee6ab646e58af80a0fc239617bdf.

**Comment by drwetter** [comment]
good catch. Thx
