### ISSUE TITLE
not easy to install /etc from testssl.sh documentation

### ISSUE THREAD

**Issue by jtmoon79** [drwetter/testssl.sh#877]
The document at https://testssl.sh/ reads

> Please note however that for 2.9dev you'll miss the mandatory files in `etc/` though. 

There are no instructions on the page to install the `etc/` files.  Nor are there instructions at https://github.com/drwetter/testssl.sh/ .

When running `testssl.sh`, I get message

     $ ./testssl.sh https://example.com
     
     ATTENTION: No cipher mapping file found!
     Please note from 2.9dev on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.
     
     Type "yes" to ignore this warning and proceed at your own risk -->

Given time, I'm sure I could figure this out.  However, it would be nice if the document at https://testssl.sh provided the steps for me.

**Comment by drwetter** [comment]
yeah, I realize your point. Need to improve the docu or supply the files.

Please help yourself @ https://github.com/drwetter/testssl.sh/releases/tag/v2.9.5-1 (bottom) or https://github.com/drwetter/testssl.sh/archive/2.9dev.zip

**Comment by drwetter** [comment]
Web site is updated. Thx for filing the issue.
