### ISSUE TITLE
URI input sanitize

### ISSUE THREAD

**Issue by salt-lick** [drwetter/testssl.sh#88]
I think a nice to strip http:// in front of the URI before running the test

Chrome/Firefox auto appends http(s):// to URIs that you copy out of the address bar and if you run your script with the http(s):// in there, it will fail. 

Ex.  ./testssl.sh http://google.com = Can't proceed: No IP address for "http" available

**Comment by drwetter** [comment]
supplying https works, even a full URL (the latter is recommended to do e.g.  cookie checking as the base URLs often do not issue a cookie).

To not handle http was on purpose as it appeared to me not make sense. If I copy https-URLs from the address bar of Chromium or Firefox I always copy https with it -- either using the mouse or c&p.

**Comment by drwetter** [comment]
Closing this one. Pls let me know if I missed something.
