### ISSUE TITLE
Support automatic filenames even with -oA

### ISSUE THREAD

**Issue by djcater** [drwetter/testssl.sh#887]
The `--log`, `--json`, `--csv`, and `--html` flags all use the `${NODE}-p${port}${YYYYMMDD-HHMM}.log` filename format, which automatically puts in the hostname, port, and timestamp. This is really useful.

The `-oA` flag is also useful for creating all 4 formats. It takes a basename as an argument, similar to Nmap.

I found myself wanting a combination of the 2 features, but it's not currently supported as far as I can see. Instead, I've stopped using `-oA` and manually use the other 4 flags at the same time.

I think it would be nice to have something like `-oA auto` (or some other keyword) which combines the 2 features, creating all 4 formats but with the auto-generated filenames.

**Comment by drwetter** [comment]
agreed, looks like a handy feature.

**Comment by drwetter** [comment]
``auto`` is a good suggestion as it is in use at other places.

Actually I wanted to postpone this as I am not yet happy with the ~thousand logging options and e.g. merge ``--log`` and ``logfile``. But that requires more thoughts to put into the command line parser.

Fix follows ...
