### ISSUE TITLE
docker = Unable to open a socket to :443 Ignore?

### ISSUE THREAD

**Issue by centminmod** [drwetter/testssl.sh#89]
I have testssl.sh setup in a docker image at https://github.com/centminmod/docker-ubuntu-nghttp2 and it use to run find until recently I get error

    #########################################################
    testssl v2.3dev  (https://testssl.sh)
    ($Id: testssl.sh,v 1.235 2015/04/22 16:24:38 dirkw Exp $)
    
       This program is free software. Redistribution + 
       modification under GPLv2 is permitted. 
       USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!
    
     Note: you can only check the server with what is
     available (ciphers/protocols) locally on your machine!
    #########################################################
    
     Using "OpenSSL 1.0.2-chacha (1.0.2b-dev)" [~179 ciphers] on
     16f99e499535:/usr/local/http2-15/bin/openssl
     (built: "reproducible build, date unspecified", platform: "linux-x86_64")
    
    /usr/bin/testssl: line 1562: : Name or service not known
    /usr/bin/testssl: line 1562: /dev/tcp//443: Invalid argument
    
    Unable to open a socket to :443 Ignore?   y

/etc/hosts in docker image

    cat /etc/hosts
    172.17.0.4      16f99e499599
    127.0.0.1       localhost
    ::1     localhost ip6-localhost ip6-loopback
    fe00::0 ip6-localnet
    ff00::0 ip6-mcastprefix
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters

**Comment by drwetter** [comment]
Hard to tell without telling me your cmd line. Pls let me know.

Cheers, Dirk

**Comment by drwetter** [comment]
the function in question is now (0aa8ac7) more robust. Closing
