### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [drwetter/testssl.sh#896]
Dear Mr. Wetter,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by drwetter** [comment]
Hello @sergeevabc ,

I am not the right person to ask. Maybe somebody else can step in here? @PeterMosmans : do you have by any chance a binary from your openssl fork? 

In the meantime I'll advise to use cygwin, MSYS2 or if you're using W10: WSL/bash on Windows or a docker container from @jumanjiman .

-Dirk

**Comment by jumanjiman** [comment]
@sergeevabc 

If you have the option to use docker container,
https://github.com/jumanjihouse/docker-testssl provides the details.

**Comment by PeterMosmans** [comment]
Hi @sergeevabc - you can find Windows OpenSSL standalone executables at https://www.onwebsecurity.com/pages/openssl.html

Cheers,

Peter

**Comment by drwetter** [comment]
Thx Peter!

**Comment by sergeevabc** [comment]
@PeterMosmans, there is no way to download 32-bit build because of error 404 and 64-bit throws error ```0xc000007b``` (probably because ```zlib1.dll``` is not included in the archive), let alone I’m not sure why you provided a link for OpenSSL in the first place as my question was about the possibility of compiling ```testssl.sh``` into executable.

**Comment by drwetter** [comment]
> as my question was about the possibility of compiling testssl.sh into executable.

this is not really possible, it is a shell script and it's per design not for compiling.
