### ISSUE TITLE
TLS alert after SSLv2 hello @ cloudflare

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#908]
Currently cloudflare hosts reply with a TLS alert to a SSLv2 hello. It should probably tell the client that SSLv2 is not available. 

As it is considered to be not a valid reply though, consequently testssl.sh labels it as "no valid SSLv2 server hello"

**Comment by drwetter** [comment]
@prdonahue, any clue?

**Comment by dcooper16** [comment]
Hi Dirk,

I just did some local testing with the master branch of [OpenSSL](https://github.com/openssl/openssl) and with [picotls](https://github.com/h2o/picotls) and I got similar results with both.

With OpenSSL up to version 1.1.0g I get an empty response to an SSLv2 ClientHello. With the draft OpenSSL 1.1.1 I get "15 03 04 00 02 02 50" (TLS alert message of "internal error").

With picotls I get "15 03 03 00 02 02 0a"  (TLS alert message of "unexpected message").

**Comment by drwetter** [comment]
Ah, ok. Thanks for the input. David! I am going to adjust the parser of SSLv2 then.

Interesting that the alert code / is different. Cloudflare returns x46= protocol version.

**Comment by drwetter** [comment]
Hi David,

could you please do a sanitity check with picoTLS and OpenSSL 1.1.1?

Cheers, Dirk

**Comment by dcooper16** [comment]
It works as expected with picoTLS and OpenSSL 1.1.1.

**Comment by drwetter** [comment]
Ok, thanks!
