### ISSUE TITLE
Please consider adding a "--overwrite" option

### ISSUE THREAD

**Issue by canoine** [drwetter/testssl.sh#927]
Hello,

I noticed that, unless "--append" is provided, "testssl.sh --XXXfile <somefile>" (replace "XXX" with 'html", "csv"...) expects "<somefile>" doesn't exist, or it exits with the following message :

"Fatal error: "<somefile>" exists. Either use "--append" or (re)move it"

I'm trying to set a cron job that updates the html output on a file which can't be deleted, for security reasons (script run by a dedicated account with restricted permissions, on a directory with sticky bit set). I know I can clear the file content before running the script, but I think adding the ability to do it directly inside the script would be more elegant.

What about adding a "--overwrite" option ?

**Comment by drwetter** [comment]
That is a seldom use case and there are a lot of command line options already.

How about using ``cp /dev/null your_file`` before. That would be least effort, is elegant and needs a small change though.

**Comment by canoine** [comment]
Of course I can clean the file (I already do, with  `>my_file`), and I understand that adding this option will fatten the script a few, takes some time, and isn't essential. That said, using this workaround and adding the "--append" parameter seems a little tortuous, doesn't it ?

**Comment by drwetter** [comment]
Welcome to the argument clinic. :)

I think it's better to be safe than sorry.


Again my question whether it would work for you zeroing the file before. Then I can make sure you can overwrite it .
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by drwetter** [comment]
Please try, see commit c23f478

**Comment by canoine** [comment]
OK, the commit avoids adding "--append" : if the file exists, and is empty, the script does what it has to do, and if the file isn't empty, it stops and complains. I'm fine with that.

Thank you for this huge project, and for bearing unbearable users like me. :)

**Comment by drwetter** [comment]
see PR pending

**Comment by canoine** [comment]
OK. Thank you.
