### ISSUE TITLE
Please consider adding full Cygwin support

### ISSUE THREAD

**Issue by ohadm2** [drwetter/testssl.sh#928]
Hi.

You have a really great script.

Unfortunately, it doesn't  fully support Cygwin so I can't get it to work under Windows.

I keep getting odd errors.

When I go over the code, I DO see Cygwin related code (e.g. line 12989) so I'm guessing it won't be hard 
to add the required adjustments.

Can you please make it run properly in Cygwin without any errors?

**Comment by drwetter** [comment]
Thx, @ohadm2 .

Can anybody take this on? My cygwin installation is resting in peace some where.

@PeterMosmans ?

**Comment by PeterMosmans** [comment]
Hi @drwetter and @ohadm2 - personally I prefer MSYS2 over cygwin _any time of day_ :wink: , but I do have an installation lying around somewhere. Which shell (type / version) are you using @ohadm2 ? Last time I checked it worked :thumbsup: with bash on cygwin ?

**Comment by ohadm2** [comment]
Thanks! :)

Yes. You're right. It's BASH.

I'm using the latest version which is: **GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)**

**Comment by PeterMosmans** [comment]
Hi @ohadm2 - could you please add the full command and output of the errors that you see, and which version (hash) you're using ? I don't see a line  12989 :wink: 

Thanks,

Peter

**Comment by ohadm2** [comment]
Hi.

Thanks for looking into it :)

1. To get the current status, I just downloaded the newest version of the script so the hash is:
$ md5sum.exe testssl.sh
94bb2d32df7ca5d637701fa22e05a63a *testssl.sh

2. In previous versions, I first got an error saying the script can't access its dependencies (the data files it uses to work) due to path errors and when I corrected the path manually I got a DNS resolving issue. From the looks of it, it seems like the path error is now gone which is great but the DNS error is still present (see a pic showing that).

3. The line I referred to is 11294 on the last version of the script and it reads:
 "
     elif [[ -e "/mnt/c/Windows/System32/bash.exe" ]] && test_openssl_suffix "$(dirname "$(type -p openssl)")"; then
"
On second thought it seems related to the built-in Bash feature of Windows 10 but it still proves support for Windows ... :)

4. I attached 2 pictures:
a. One is showing the script running and halting after a DNS failure (I ran general network commands after that to show that I do have internet and DNS access to the tested URL).
b. The second is showing versions: Bash version, Cygwin version and Windows version.

Regards,

![testssh sh-cygwin-err-1](https://user-images.githubusercontent.com/13061670/34475764-543d93ac-ef96-11e7-8237-679772b88b3a.png)
![testssh sh-cygwin-err-2](https://user-images.githubusercontent.com/13061670/34475766-545f6694-ef96-11e7-91f6-7568ac90cced.png)

**Comment by KaiserSoft** [comment]
I was recommended this script by a colleague this morning and promptly ran into the same issue :)
Under cygwin Windows, the following command adds an extra new line which results in IP lookup failure.

Line 12027
nslookup -querytype=a "$1" 2>/dev/null | awk '/^Name/ { getline; print $NF }'

If I change it to the following it will work
nslookup -querytype=a "$1" 2>/dev/null | awk '/^Name/ { getline; print $NF }' **| tr -d '\r\n'**



![capture](https://user-images.githubusercontent.com/2138606/36151435-77906d14-10c7-11e8-81d9-65eb29152be1.PNG)

**Comment by drwetter** [comment]
I am blindfolded here, so I wrapped all nslookups in ``strip_lf`` statements, just to be safe. 

@KaiserSoft : could you please pull and try again -- a full run?!

@ohadm2 : also your feedback would be appreciated.

Thx

**Comment by drwetter** [comment]
okay, thx for the confirmation.

**Comment by ohadm2** [comment]
Well...there are good news and bad news.

The good news is that it is finally working via Cygwin! 

Thank you so much and nice work finding that extra new line! :)

The bad news however is that for some reason the process is REALLY REALLY SSLLLOOOOWWW ....

It took me around an hour and a half (!) just to scan Google!

And the init process itself (before any input is printed) also took around 10 minutes.

![testssh sh-cygwin-working-1](https://user-images.githubusercontent.com/13061670/36211492-0c08f67c-11aa-11e8-8941-1148539e85b5.png)
![testssh sh-cygwin-working-2](https://user-images.githubusercontent.com/13061670/36211493-0c2eb3da-11aa-11e8-924a-fa43d50f0d37.png)

**Comment by drwetter** [comment]
Yup, this is known #610. Cygwin seems to be he slowest platform. But still -- an hour and a half is surprisingly much. 

You might want to try a different platform one or using docker instead.

The initialization could be due to ``prepare_arrays()``.  Running ``MEASURE_TIME=true ./testssl.sh <arg>`` or `MEASURE_TIME_FILE=<somefile> ./testssl.sh <arg>`` will give you little clue.

But in general I believe forking and subshells aren't really good emulated under cygwin. I swear there's no bitcoin mining taking place in between ;-)

**Comment by KaiserSoft** [comment]
I noticed the speed difference. Running it on a Linux VM is almost instant compared to a run under cygwin.
I'll try to look into it when I get some free time. Maybe different default timeouts for tools used ... feels a bit like it.
