### ISSUE TITLE
Secure Client-Initialized Renegotiation

### ISSUE THREAD

**Issue by davidepic91** [drwetter/testssl.sh#933]
Hi, I executed testssl.sh 2.9.5 on my local TLS 1.2 socket server implemented with openssl 1.0.2g. In the "Testing Vulnerabilities" part, I notice that it is vulnerable only to the "Secure Client-Initialized Renegotiation". 
<img width="1194" alt="solution_test_vulnerabilities" src="https://user-images.githubusercontent.com/9037424/33902618-e34fdcb6-df75-11e7-8ba1-28de3d258211.png">
I have some questions about this specific vulnerabilty.
1) What is the corresponding CVE ? I found a lot of information only about "Secure Renegotiation" attack which has been solved as stated here [OpenSSL CVE 2009](https://www.openssl.org/news/vulnerabilities.html#y2009).
2) Where can I find other details about it ? I read also this [interesting article ](https://securingtomorrow.mcafee.com/technical-how-to/tips-securing-ssl-renegotiation/) but I didn't find any official OpenSSL documentation about the specific "Secure Client-Initialized Renegotiation". In the [official page](https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_options.html) they talk about only of "Secure Renegotiation".

Thanks.

**Comment by dhd0004** [comment]
Hi, did you get any valuable information about this vulnerability?
I can not undestand why testssl says my server is vulnerable, and SSLLAbs says it is not.

Thanks
