### ISSUE TITLE
Allow specifying a CA cert file

### ISSUE THREAD

**Issue by Synchro** [drwetter/testssl.sh#941]
I'd like to be able to check the certificate chain to a server when using a local CA cert file (e.g. like [the bundle downloadable from curl](https://curl.haxx.se/docs/caextract.html)). In openssl I can use a `CAfile` switch, but the output from that isn't very readable, and I can see that there is some vestigial support for this in testssl.sh, but it appears to be commented out. Can we have this back in?

**Comment by drwetter** [comment]
Don;'t sure about your request....

The Mozilla bundle is included. 

If you want a private bundle you just can put them into the etc dir. But then you'll get warnings if you test other hosts do not have this bundle, see open issue #230.

**Comment by Synchro** [comment]
It's for testing configs where the locally installed CA certs needed to verify a connection are out of date or missing. I've had a huge spike in support requests relating to this recently because gmail changed its cert to one signed by a root cert that is (apparently) not included in many OSs. So it's really testing the client end more than the server, so it's exactly these warnings that I want it to show.

**Comment by drwetter** [comment]
``CA_BUNDLES_PATH=<your_path_here> ./testssl.sh <my_cmdline>``

**Comment by drwetter** [comment]
Did that answer your question?

**Comment by drwetter** [comment]
see e564783
