### ISSUE TITLE
[Request for Feature] Nmap input

### ISSUE THREAD

**Issue by AresS31** [drwetter/testssl.sh#945]
Hi,

What would you think of adding options to feed `testssl `with `nmap `scan results?

In order to automate testing, I think it would be nice to implement an option in `testssl `to automatically parse `nmap `scan results (.gnmap, or .xml) in order to obtain a list of hosts and SSL/TLS enabled services to use with `testssl`.

E.g. I have got 3 different hosts. `Nmap `detected 3 SSL/TLS enabled services, let's say 443, 8081 and 8441. I would like to be able to do something like:
`./testssl -U --input nmap_scan.gnmap` 

Best regards,
Alex

**Comment by drwetter** [comment]
```
testssl.sh  | grep -B2 nmap                                                                                                                                                     
     --file <fname|fname.gmap>     Mass testing option: Reads command lines from <fname>, one line per instance.
                                   Comments via # allowed, EOF signals end of <fname>. Implicitly turns on "--warnings batch".
                                   Alternatively: nmap output in greppable format (-oG) (1x port per line allowed)
--
     --html                        additional output as HTML to file '${NODE}-p${port}${YYYYMMDD-HHMM}.html'
     --htmlfile|-oH <htmlfile>     additional output as HTML to the specifed file or directory, similar to --logfile
     --out(f,F)ile|-oa/-oA <fname> log to a LOG,JSON,CSV,HTML file (see nmap). -oA/-oa: pretty/flat JSON. "auto" uses '${NODE}-p${port}${YYYYMMDD-HHMM}'
```

**Comment by AresS31** [comment]
I already tried that option and it prompts that error. It is a valid nmap grepable file. By the way it must be a typo but in the `testssl `help it says `fname.gmap` instead of `fname.gnmap`.
```
foo@bar:~/testssl.sh$ ./testssl.sh -U --file "/foo/nmap/Fast_SYN.gnmap"

###########################################################
    testssl.sh       2.9dev from https://testssl.sh/dev/
    (410c3d5 2017-12-21 09:45:05 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on niflheim:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")



Fatal error: Can't read file "/foo/nmap/Fast_SYN.gnmap"
```

**Comment by AresS31** [comment]
I solved the issue, it appears that `testssl `does not like space within the path of the `gnmap `file even when the path is enclosed between double quote.

**Comment by drwetter** [comment]
Typo: yes & thx.

If it says it can't read it -- you should believe the message -- it just can't read it then ;-) 

```
   if [[ ! -r "$FNAME" ]] && "$IKNOW_FNAME"; then
          fatal "Can't read file \"$FNAME\"" "2"
    fi
```
Unless you call it differently as you posted ...

**Comment by drwetter** [comment]
that works for me too:  ``testssl.sh -p --file "/tmp/i a/tcpSYNplus 20171211-2247.gmap"``

**Comment by tsion123456** [comment]
its only scanning the first port, how can i scan all the ports in the file?

**Comment by archidote** [comment]
Sorry to reopen this issue, as @tsion123456  said, it would be nice if this option was included in testssl.sh in the future. if anyone is motivated to try ^^

**Comment by drwetter** [comment]
Can you @archidote  pls be more specific wrt what doesn't work for you or what you feel is missing?

**Comment by archidote** [comment]
> Can you @archidote pls be more specific wrt what doesn't work for you or what you feel is missing?

Hi, 

I have the impression when I parse an nmap.xml that testssl doesn't check every port. I wonder how the detection is done. Is it based on the protocol type (http,smtp) or do you use another method?

**Comment by drwetter** [comment]
The detection of TLS-enabled ports is balanced, which means : Detect with some heuristics TLS-enabled ports and make educated guesses. We don't scan every port as  that could end up (best case) spending a large amount of time on ports where it doesn't make sense. In the worst case and if the server application doesn't play as nice as we expect there's a lockup. 

Last but not least testssl.sh is not a port/service scanner.  Nmap does a way better job of detecting a service -- see SERVICE column of nmap.  E.g. nmap -T -p 443 testssl.sh returns  https or ssl/http (if -V is supplied.)  Other ports which don't respond  as good (``nmap -sT -p25  smtp.google.com`` returns just smtp)  are listed (see ``ports2starttls()`` which is being called from ``nmap_to_plain_file`` containing the heuristics).
