### ISSUE TITLE
Add port flag support

### ISSUE THREAD

**Issue by theoren** [drwetter/testssl.sh#947]
1. Version: 2.8

2. PORT is not read from environment nor accepted as parameter. Sometimes scripting and providing https://{ip}:{port} is not trivial 

3. Read PORT from environment and accept --port {port} as paramter

Here is a copy patch :) based on 2.9dev
--- testssl.sh.orig     2017-12-11 23:38:26.000000000 +0200
+++ testssl.sh  2017-12-21 14:52:14.952180000 +0200
@@ -13421,6 +13421,7 @@
                                    Comments via # allowed, EOF signals end of <fname>. Implicitly turns on "--warnings batch".
                                    Alternatively: nmap output in greppable format (-oG) (1x port per line allowed)
      --mode <serial|parallel>      Mass testing to be done serial (default) or parallel (--parallel is shortcut for the latter)
+     --port <port>                 Does a default run against <port>

 single check as <options>  ("$PROG_NAME  URI" does everything except -E and -g):
      -e, --each-cipher             checks each local cipher remotely
@@ -15331,6 +15332,10 @@
                               help 1
                     esac
                     ;;
+                --port|--port=*)
+                     PORT="$(parse_opt_equal_sign "$1" "$2")"
+                     [[ $? -eq 0 ]] && shift
+                     ;;
                --serial)
                     MASS_TESTING_MODE=serial
                     ;;

**Comment by drwetter** [comment]
```
./testssl.sh                                                                                                                                                                                                                        

[..]

"testssl.sh <URI>", where <URI> is:

     <URI>                         host|host:port|URL|URL:port   port 443 is default, URL can only contain HTTPS protocol)

```

Sorry, that should suffice.
