### ISSUE TITLE
PrettyJSON consistency

### ISSUE THREAD

**Issue by AresS31** [drwetter/testssl.sh#952]
To keep consistency between the `Pretty JSON` output files for one host or multiple hosts, I would like to see the `port `entry inside the `scanResult `object in order to be able to automate the post-processing of `Pretty JSON` output files.

At the moment, when scanning a single host, the following output is being generated:
```
{
          "Invocation"  : "testssl.sh --quiet --protocols --json-pretty --nodns x.x.x.x",
          "at"          : "niflheim:./bin/openssl.Linux.x86_64",
          "version"     : "2.9dev 410c3d5 from 2017-12-21",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jun 22 19:32:29 2016",
          "target host" : "x.x.x.x",
          "**port**"        : "443",
          "startTime"   : "1513962798",
          "scanResult"  : [
          {
                    "service"         : "Service detected: HTTP",
                    "ip"              : "x.x.x.x",
                    "protocols"         : [
                            {
                                "id"           : "sslv2",
                                "severity"     : "OK",
                                "finding"      : "SSLv2 is not offered"
                           },{
```

When scanning multiple hosts, the output looks like this:
```
{
          "Invocation"  : "testssl.sh --jsonfile-pretty testssl_results_pretty.json --quiet --nodns --protocols --severity LOW --vulnerable --file full_SYN.gnmap",
          "at"          : "niflheim:./bin/openssl.Linux.x86_64",
          "version"     : "2.9dev 410c3d5 from 2017-12-21",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jun 22 19:32:29 2016",
          "startTime"   : "1513947600",
          "scanResult"  : [
          {
                    "target host"     : "x.x.x.x",
                    "**port**"            : "443",
                    "service"         : "Service detected: HTTP",
                    "ip"              : "x.x.x.x",
                    "protocols"         : [
                            {
                                "id"           : "tls1_1",
                                "severity"     : "CRITICAL",
                                "finding"      : "TLSv1.1 is not offered, and downgraded to a weaker protocol"
                           },
```
So for consistency could you please consider putting the `port `field within the `scanResult `object even when scanning only a single host.

Regards,
Alex

**Comment by drwetter** [comment]
Hi Alex,

thank you. 

I am hesitant, so maybe you could explain a bit better why post processing fails in your case. Logically this was designed on purpose as the parent object reflects the command line (ok, maybe except the startTime).

You can have a look @  9981d768799342585d336a0c37f0eec659a3ff6c in the mean time.

Dirk

**Comment by AresS31** [comment]
@drwetter I will give you an example.

I made a python script to format the `testssl `results to my liking. The following is a code snippet:
```
--- SNIP ---
data = json.load(args.input_file)

for values in data["scanResult"]:
        host_ip = values["ip"]
        port = values["port"]

--- SNIP ---
```

The issue I encounter is that when you launch `testssl `by giving it only a single target the `ip` field is not enclosed within the `scanResult` object. Whereas when you launch `testssl` with a list of targets or a nmap scan results the `ip` field is enclosed within the `scanResult` object. So what I suggest is to uniformise the pretty JSON format by always putting the `ip` field is enclosed within `scanResult`.

I hope I have been clear.

Best regqrds,
Alex

**Comment by drwetter** [comment]
Ok, thx. The piece I missed before was that in mass mode writing to one file the information was in the scanResults section.

Done, see 85c470fcdc89af6da7608b6584a35fb17c5efe45
