### ISSUE TITLE
Cipher quality: LOW due to "(cbc)" for ECDHE-RSA-AES128-GCM-SHA256

### ISSUE THREAD

**Issue by sxxs** [drwetter/testssl.sh#953]
Running 2.9dev 978478f from 2017-12-21

I see the following lines in json output (and corresponding output in stdout as well):
"id"           : "order_cipher",
"severity"     : "LOW",
"finding"      : "Default cipher: ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH (P-256) (cbc)"

However, ECDHE-RSA-AES128-GCM-SHA256 does not use cbc, but gcm. Therefore, I would have expected to see "OK" here. Or am I missing something?

**Comment by drwetter** [comment]
Ack & thx, Dominik. Seems we need more unit tests.

**Comment by drwetter** [comment]
FYI: I just pushed a change (7a1fb66) penalizing kx=RSA but using modern ciphers but there's still work which needs to be done.

If you spot further errors or inconsistencies pls let me know.
