### ISSUE TITLE
Informational announcement: Changes for JSON ahead

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#970]
Hi,

I've been working the last 2 days to get an improvement done in 2.9dev which will affect all folks using JSON (and CSV) as the output format for further processing. As the screen output won't be affected I thought a heads up would do good:

Following changes will be implemented shortly in 2.9dev:

1) The "id" will change in 90% of the cases. It'll be more verbose, acronyms with be written in capitals.

2) The repetition of the check name in "finding" will vanish. So instead of 

```
"finding" "Server banner identified: Apache" 
```

there will be only ``"finding": "Apache"``. The "id" will tell you where this finding belongs to: ``"id"           : "server_banner"``

This increases readability because of the redundant information in finding will disappear and for humans "id" will better explain what's this object is about. 

If you want to have a peak you should have a look @ the branch where this action is taking place: https://github.com/drwetter/testssl.sh/tree/new_json_for_serverdefaults. Some ids weren't converted yet but will be done soon -- either in that branch or after merge into dev.

Following pictures should give you an idea what I am talking about:

**OLD
===**
![screenshot_20180123_154809](https://user-images.githubusercontent.com/8036727/35282074-e3c72776-0054-11e8-8a2c-8e9cbd79d507.png)

**NEW
===**
![screenshot_20180123_154833](https://user-images.githubusercontent.com/8036727/35282449-d3c03d6c-0055-11e8-84e9-eb4218505d73.png)

**Comment by drwetter** [comment]
in vim diff mode:
![screenshot_20180123_160250](https://user-images.githubusercontent.com/8036727/35282852-eba30ca6-0056-11e8-8da9-c6d4b5afb0c2.png)

**Comment by bao7uo** [comment]
These are helpful changes, thanks :-)

**Comment by drwetter** [comment]
closed via e446c80

**Comment by drwetter** [comment]
I just committed some adjustments in d2d62a9.

As much as possible the ``jsonID``s were changed to OpenSSL / IETF names so that testssl.sh is more compliant to the rest of the world -- mainly in ``certificate_info()``. 

If you happen to spot improvements let me know or submit a PR.

**Comment by bao7uo** [comment]
Just had a quick read through - looks ideal, thanks.

**Comment by fogs** [comment]
Danke!
