### ISSUE TITLE
Request for further X.509 certificate checks and results logging

### ISSUE THREAD

**Issue by AresS31** [drwetter/testssl.sh#979]
Hello,

Would it be possible to add further checks for SSL/TLS X.509 certificate configurations, such as expiry, self-signed, untrusted, weak hashing algorithm, etc. And to actually log the results (prettyJSON) in a similar way than what is already implemented for SSL/TLS vulnerabilities?

Kind regards,
Alex

**Comment by bao7uo** [comment]
I think most of those checks are already performed. But it would be great to have it in the JSON output :-)

**Comment by drwetter** [comment]
I am confused as well. Expiry:

```
                 {
                                "id"           : "cert_expiration_status <cert#1>",
                                "severity"     : "OK",
                                "finding"      : "270 >= 60 days"
                           },{
                                "id"           : "cert_notBefore <cert#1>",
                                "severity"     : "INFO",
                                "finding"      : "2016-10-28 02:00"
                           },{
                                "id"           : "cert_notAfter <cert#1>",
                                "severity"     : "OK",
                                "finding"      : "2018-11-02 13:00"
                           }
````

self-signed: ``cert_trust`` and ``cert_caIssuers``
"weak hash": ``cert_signatureAlgorithm``
