### ISSUE TITLE
Line jump missing after TLS_FALLBACK_SCSV test result (before SWEET32 results)

### ISSUE THREAD

**Issue by jandr** [drwetter/testssl.sh#983]
In the development testssl version (2.9dev from https://testssl.sh/dev/ (7bf070b 2018-02-08 14:02:24 -- ),  after the TLS_FALLBACK_SCSV result there seems to be a missing line jump before the SWEET32 result (which appears at the end of that line)

See attached screenshot.
![image](https://user-images.githubusercontent.com/8058880/35982314-ca7a9e4a-0cef-11e8-8018-a9edf1e24e62.png)

**Comment by dcooper16** [comment]
Hi @jandr ,

Thanks for reporting this. This was missing in a few places in that function.
