### ISSUE TITLE
Come clear with the error codes

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#986]
At the moment testssl.sh exits with a code between 8 (good) and 13 (worst). This seems not particular useful. 

For long term there were some suggestions (see #985, #327, #752 ). That would require time to get this done properly.

For the time being (2.9dev) it would be great either to have an exit code or 0 (all tests performed successfully) or 1 (error performing the test) -- or an intermediate probably hackish solution.

**Comment by LeslieGerman** [comment]
Hi Dirk,
> At the moment testssl.sh exits with a code between 8 (good) and 13 (worst).
Does it mean, than if the exit code != 8, then something 'bad' happened/was detected?
Thanks.

**Comment by drwetter** [comment]
ATM you shouldn't care about the exit codes at all in terms of findings.
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by LeslieGerman** [comment]
Hello Dirk,

I see in the previous commits you started to address the exit status issue.

From my point of view - which is integrating testssl.sh in an automated framework (CI):

I would separate two cases:
- no attention needed, everything was OK.
- attention needed:
  - Either some (potential) security problem was detected.
  - Execution problem: an error happened while running the tool (domain name resolution problem, connection time-out, closed connection, programming error, etc.)

So I suggest something like:

  Status                | Exit code
--------------------- | -------------------
Everything was OK        | 0
Security Problems: Low | 1
...  | 2...
Security Problems: High | ....
Unused (reserved for future use)                       |  1000..5000
Execution errors             |  5001...

AFAI see you started to go in this direction...

The main point is to have a 'future-proof' consistent solution, which can last and can be relied on the long-term. The exact numbers do not matter too much for me... :)

Regards.

**Comment by drwetter** [comment]
> AFAI see you started to go in this direction...

nope, that's not exactly what is happening. Short term there will be **error** codes = checks could be performed (0) or not (1 per check).

Everything else comes later ~1-3 months.

Cheers, Dirk 



-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection
