### ISSUE TITLE
Empty finding causes corrupt json files

### ISSUE THREAD

**Issue by seccubus** [drwetter/testssl.sh#988]
#Please make sure that you provide enough information so that we understand what your issue is about.

   
1. testssl version from the banner (testssl.sh -b 2>/dev/null | head -4 | tail -2)

    testssl.sh       2.9dev fromhttps://testssl.sh/dev/
    (9b37932 2018-02-12 15:44:39 -- )

2. what exactly was happening, output is needed

We start seccubus with the following command line:
```
testssl.sh  --color 0 -p -S -P -h -U --fast --jsonfile=/tmp/seccubus.testssl.82454.json --file /tmp/seccubus.hosts.82452
```

/tmp/seccubus.hosts.82452:
```
www.seccubus.com
```

Output at offset 1490 is:

```
,         {
              "id"           : "ALPN",
              "ip"           : "www.seccubus.com/95.101.39.93",
              "port"         : "443",
              "severity"     : "OK",

          }
,         {
              "id"           : "ALPN",
              "ip"           : "www.seccubus.com/95.101.39.93",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : "http/1.1"
          }
```

3. what did you expect instead?

Output should be something like:
```
,         {
              "id"           : "ALPN",
              "ip"           : "www.seccubus.com/95.101.39.93",
              "port"         : "443",
              "severity"     : "OK",
              "finding"      : "(empty)"
          }
,         {
              "id"           : "ALPN",
              "ip"           : "www.seccubus.com/95.101.39.93",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : "http/1.1"
          }
```

Actually I would expect only one ALPN finding, I suspect this is because of the fileout statement on line 8027

4. steps to reproduce

   1. testssl.sh command line

testssl.sh  --color 0 -p -S -P -h -U --fast --jsonfile=/tmp/seccubus.testssl.82454.json --file /tmp/seccubus.hosts.82452

    1. if possible: target IP

seccubus.com on 95.101.39.95 (Subject to change as this is behind Akamai)
 
    1. openssl version used (testssl.sh -b 2>/dev/null | head -16 | tail -3)
 
 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on sbplt90dhhv2j:./bin/openssl.Darwin.x86_64
 (built: "Sep  7 19:34:54 2016", platform: "darwin64-x86_64-cc")

    1. your operating system (uname -a)

Darwin sbplt90dhhv2j 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by drwetter** [comment]
As the commit message says: There's now an extra reward if ALPN discovered "h2" (ALPN --> OK). Unfortunately the variable was the wrong one :-(

Thx for report, Frank!
